### ISSUE TITLE
German accents "Dialekte"

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1000]
@Gregoor
I wasn't sure whether #982 included german "Dialekte", yet. (I don't think so)
https://de.m.wikipedia.org/wiki/Deutsche_Dialekte

Which ones should we include?
All of them? Or just "Bundesländer" and Austria and Switzerland
What about German in African countries? (etc.)

**Comment by jf99** [comment]
I'd propose to include all Bundesländer + Austria and Switzerland. The list on Wikipedia includes too many possibilities. To be honest, I never heard the words "Ostflämisch" and "Geldersch" before. Wtf is that? I'm not sure whether even people from the specific region know that their dialect has that name.

I think we had a similar discussion a while ago, although I can't find the thread right now. Imho it would be best if the user could choose where he/she lives/grew up. Not all people who contribute to a language are native speakers. Take me as an example. I contributed to English, but live and have been grown up in Germany. I'm pretty sure that this has influenced the way I pronounce certain words in English. But as German is not an English accent, I always chose "Other". I sink, se way Germans speak English is pretty unique, sough :)

**Comment by ubahnverleih** [comment]
Using the Bundesländer sounds OK, because i think most people doesn't even know which exact type of dialect they speak. But then don't forget Austria (don't know if they have different dialects?), Switzerland, Belgium, Luxemburg.
What's about Süd Tirol in Italy and Elsass and Lothringen in France? Oh, and german is also "Nationalsprache" in Namibia.

Does anyone know how different the dialects are in the east european/asian countries? Is there a difference between the language of Kirgisistandeutsche, Russlanddeutsche, Kasachstandeutsche? There is a wikipedia category, but maybe it is possible to group most of them together: https://de.wikipedia.org/wiki/Kategorie:Deutschsprachige_Minderheit

**Comment by Djfe** [comment]
Yeah, you're probably right.
Especially since it's more of an accent and not a dialekt, we are actually talking about.
(All sentences are High German after all)

Ostflämisch and Geldersch are probably close to the netherlands/belgium, right? ^^
(rethorical question, I looked it up, after writing it down)
Flämisch is the Belgian version of Dutch for example.

Anyways, this might be better suited:
https://de.wikipedia.org/wiki/Hochdeutsche_Dialekte#Gliederung
or rather the individual pages (niederdeutsch/plattdeutsch is missing from the link above for some reason):
https://de.wikipedia.org/wiki/Niederdeutsche_Sprache#Gliederung_des_Niederdeutschen


https://de.wikipedia.org/wiki/Westmitteldeutsche_Sprachen
https://de.wikipedia.org/wiki/Ostmitteldeutsche_Dialekte
https://de.wikipedia.org/wiki/Alemannische_Dialekte
https://de.wikipedia.org/wiki/Bairische_Dialekte
https://de.wikipedia.org/wiki/Ostfr%C3%A4nkische_Dialekte
https://de.wikipedia.org/wiki/S%C3%BCdfr%C3%A4nkische_Dialekte

Don't forget netherlands btw.
They don't speak german natively, but lots of Dutch people learned it in school and could record their german, too.
https://de.wikipedia.org/wiki/Niederdeutsche_Sprache#Dialekte_in_den_Niederlanden

Even though there might be deeper dialects I would go by countries on that level:
Dutch, Swiss, Austrian/Tirol, Italian, French, Danish
I'm unsure about: Polish (it rather belongs to Schlesisch, I guess)

Also seems relevant: https://de.wikipedia.org/wiki/Schweizer_Hochdeutsch#/media/File:Sprachvariet%C3%A4ten_Deutsch.png

"German minorities" seems to be a good category as well. (Deutschstämmige/Auslandsdeutsche)
"Namibian". there are roughly 20000 namibians who still speak german according to the wiki.

I also thought about making it easier for people by allowing them to enter their postal code, but I'm unsure about it.

**Comment by Djfe** [comment]
Nevermind, I found something way better and complete :)
German Regiolekte:
https://de.wikipedia.org/wiki/Regiolekt#Deutschland
(it also lists them for Austria and Switzerland)

Good amount (not too many, not too few)

In addition:
Netherlands, Danish, French, Italien, Luxembourgian (do we want to call the last one Luxemburgisch or Lëtzebuergesch? or is it Luxemburger Hochdeutsch? https://de.wikipedia.org/wiki/Luxemburgische_Sprache#Hochdeutsch_in_Luxemburg)
Deutschstämmige/Auslandsdeutsche/Deutsche Minderheiten
Maybe also:
"Nataler Deutsch" and Namibian (maybe?)

Kinda relevant as well:
https://de.wikipedia.org/wiki/Deutsche_Dialekte#Dialekt_aktuell

**Comment by Gregoor** [comment]
Woohoo issue no 1000 🎉 🎈 

Thanks lots for the discussion! This topic has been on our mind last week as well and we're coming together this week with people more knowledgable than me on this topic. Apparently there is also some standardtisation in the speech recognition space happening around this topic. I'll post updates on this, once I get them 🙂 

Also haven't heard Regiolekt before, good stuff.

**Comment by jf99** [comment]
One thing that still bothers me: If you ask people about their dialect, some will answer that they don't have any. And that's true. Many students I met at university were from distant parts of Germany, but you couldn't hear that from the way they spoke, because they spoke standard German. That's why I'd prefer to ask people where they come from rather what dialect they speak.

**Comment by Djfe** [comment]
(perfect) high German is also a form of dialect imo, so we should have an entry for that. (the default one)

Regiolekt is the term linguistic people came up with for what happened to young people speaking in German but loosing deeper forms of dialects through school and growing up with high German. (there are some good articles explaining this in a better way).
it's probably what stays when dialects go extinct.

I'm very happy that Mozilla is about to consult scientists/experts on this since they probably know best what info they need in a good voice database and how people speak today :)
I as a contributor am not that knowledgeable and had to fallback to Wikipedia to find out more after all.

issue 1000 hype :yum:

**Comment by Gregoor** [comment]
I think asking people where they come from might actually be the most accurate version. Though for me, it likely wouldn't as I was brought up in Hesse, by parents who were brought up with Duisburger Platt and Moselfraenkisch, but then lived in Berlin for a few decades (hence losing/overwriting most of their dialect). For my studies I moved to Hamburg, which also had some influence on the way I talk. And then there is programming and english culture which is probably the largest influence on my dialect.
Anyway, I might be an outlier 🙈

**Comment by Djfe** [comment]
German just launched and we don't have any important German accents, yet.
Only accents from people from other countries.

Not Bairisch, not Hessisch, not Hochdeutsch etc.
Hochdeutsch is Deutschland Deutsch now 🤦‍♂️ 😆

**Comment by Djfe** [comment]
I still think, Dialects would be helpful for speech recognition:
https://www.youtube.com/watch?v=hkrx4vnJFCo

**Comment by Djfe** [comment]
What do you think about adding actual. sentences from Swiss German, Austrian German or Bairisch (etc.)?

The question came up in:
#1100

because there is Belgian Dutch and Dutch
(just like French and Belgian French)
Belgian Dutch definitely has differences so the question for them is: include both versions in one file or separate them for Dutch and Belgian speakers?

(I'm unsure whether Dutch people can pronounce Belgian Dutch right (you might want to ask that over there)

**Comment by danielsjf** [comment]
In the end 99% of the words are the same. The differences come mainly from words that are used in a different way or expressions that are in a different form. It is comparable to American English versus British English, minus the spelling differences.

By the way, the same question on accents is also relevant for Dutch, but how far should you go? When I want to use a speech assistant, I don't want to choose from a big list which accent I'm using. Optimally I would only select the language. In the same way that I can understand people from the Netherlands or the various accents within Belgium, I think the speech to text neural net should be able to do the same.

The main reason I see why it could be useful is for classification reasons. To match our "oh I think he is from that region" reflection. This context might also be interesting from a research point of view.

**Comment by Djfe** [comment]
> When I want to use a speech assistant, I don't want to choose from a big list which accent I'm using. Optimally I would only select the language.

you can always create a neural network (from this data) that detects the language the user is using and run it beforehand ;)
this way the user wouldn't need to select anything

**Comment by nukeador** [comment]
We are going to open a conversation on discourse about accents in the coming days with a proposal.

Please, add your feedback there so we can have a unified approach for all languages

https://discourse.mozilla.org/c/voice

Thanks for your contributions!

**Comment by Matthias84** [comment]
I continued this discussion  at discourse: https://discourse.mozilla.org/t/region-or-dialect/34632/3

**Comment by nukeador** [comment]
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
