### ISSUE TITLE
docker web_1 startup issue

### ISSUE THREAD

**Issue by zenogantner** [mozilla/voice-web#1001]
This is the output I get:
```
web_1      | PUT bucket code: 000
web_1      | Done!
web_1      | yarn run v1.5.1
web_1      | $ node scripts/dev-server.js
web_1      | module.js:549
web_1      |     throw err;
web_1      |     ^
web_1      | 
web_1      | Error: Cannot find module 'chalk'
web_1      |     at Function.Module._resolveFilename (module.js:547:15)
web_1      |     at Function.Module._load (module.js:474:25)
web_1      |     at Module.require (module.js:596:17)
web_1      |     at require (internal/module.js:11:18)
web_1      |     at Object.<anonymous> (/code/scripts/dev-server.js:2:15)
web_1      |     at Module._compile (module.js:652:30)
web_1      |     at Object.Module._extensions..js (module.js:663:10)
web_1      |     at Module.load (module.js:565:32)
web_1      |     at tryModuleLoad (module.js:505:12)
web_1      |     at Function.Module._load (module.js:497:3)
web_1      | error An unexpected error occurred: "Command failed.
web_1      | Exit code: 1
web_1      | Command: sh
web_1      | Arguments: -c node scripts/dev-server.js
web_1      | Directory: /code
web_1      | Output:
web_1      | ".
web_1      | info If you think this is a bug, please open a bug report with the information provided in "/code/yarn-error.log".
web_1      | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
voice-web_web_1 exited with code 1
```
I have zero experience with modern JavaScript/TypeScript, and almost no experience with docker, so maybe I am doing something obviously stupid.

I have the latest version of the voice-web repo.
> npm --version
5.6.0
> docker --version
Docker version 18.03.1-ce, build 9ee9f40
> yarn --version
1.6.0

Let me know if you need further information.

**Comment by zenogantner** [comment]
[yarn-error.log](https://github.com/mozilla/voice-web/files/2001281/yarn-error.log)

**Comment by Gregoor** [comment]
thanks for reporting this. I gotta admit, I'm not experienced with Docker either. I basically just run `docker-compose up` in the root dir and it works. Is that also what you did here? I'm running on the same Docker version.
Alternatively you can run `yarn` in root and then run `yarn start`. Though for testing clip saving & voting you'd have to setup S3 (https://github.com/mozilla/voice-web/blob/master/CONTRIBUTING.md#local-setup)

**Comment by zenogantner** [comment]
Thank you for your quick response, @Gregoor.

I did  `docker-compose up` and there got the errors, yes.

`yarn` and `yarn start` bring up a local web server on port 9000, which I can access. On the console, it complains about a missing DB connection -- but that is expected ...

If I understood it correctly, the charm of the docker solution lay in not having to worry about S3 and the DB ...

Anyway, I will keep trying, and report back.

**Comment by Gregoor** [comment]
Right, forgot to mention the DB setup. Docker indeed should make life easier here, I'm sorry it doesn't. I'll look into it again!

**Comment by jbinard** [comment]
I have the same issue with docker. I checked the NODE_ENV variable and nothing is set.

If I run `yarn` in the folder, everything works well.

**Comment by mikehenrty** [comment]
maybe @johngian has some ideas?

**Comment by jbinard** [comment]
Here are the steps I followed to setup voice-web locally:
- clone the repository
- go to the voice-web folder
- docker-compose up

When running:

`> docker-compose build --no-cache
> docker-compose up -d web s3proxy`

I can see in the logs that we still have the same issue:

`web_1      | Checking if s3 bucket exists...
web_1      | GET bucket code: 000
web_1      | Bucket does not exist. Creating one...
web_1      | PUT bucket code: 000
web_1      | Done!
web_1      | yarn run v1.6.0
web_1      | $ node scripts/dev-server.js
web_1      | module.js:549
web_1      |     throw err;
web_1      |     ^
web_1      | 
web_1      | Error: Cannot find module 'chalk'
web_1      |     at Function.Module._resolveFilename (module.js:547:15)
web_1      |     at Function.Module._load (module.js:474:25)
web_1      |     at Module.require (module.js:596:17)
web_1      |     at require (internal/module.js:11:18)
web_1      |     at Object.<anonymous> (/code/scripts/dev-server.js:2:15)
web_1      |     at Module._compile (module.js:652:30)
web_1      |     at Object.Module._extensions..js (module.js:663:10)
web_1      |     at Module.load (module.js:565:32)
web_1      |     at tryModuleLoad (module.js:505:12)
web_1      |     at Function.Module._load (module.js:497:3)
web_1      | error Command failed with exit code 1.
web_1      | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by jbinard** [comment]
It looks like yarn is not installing the dev dependencies when launched from the docker container.
If I run yarn locally, the dev dependencies are well installed.

**Comment by jbinard** [comment]
I made a new test by replacing yarn by "npm install" in the dockerfile and we have the same issue so this is not related to yarn :(

**Comment by johngian** [comment]
Hey @jbinard 
Can you send me the output of the following command:
``docker images | grep node``

**Comment by johngian** [comment]
yay i reproduced it:
```
db_1       | 2018-06-20 10:51:17 1 [Warning] 'proxies_priv' entry '@ root@4455abae7d51' ignored in --skip-name-resolve mode.
web_1      | GET bucket code: 404
web_1      | Bucket does not exist. Creating one...
web_1      | PUT bucket code: 200
web_1      | Done!
web_1      | yarn run v1.6.0
web_1      | $ node scripts/dev-server.js
web_1      | module.js:549
web_1      |     throw err;
web_1      |     ^
web_1      | 
web_1      | Error: Cannot find module 'chalk'
web_1      |     at Function.Module._resolveFilename (module.js:547:15)
web_1      |     at Function.Module._load (module.js:474:25)
web_1      |     at Module.require (module.js:596:17)
web_1      |     at require (internal/module.js:11:18)
web_1      |     at Object.<anonymous> (/code/scripts/dev-server.js:2:15)
web_1      |     at Module._compile (module.js:652:30)
web_1      |     at Object.Module._extensions..js (module.js:663:10)
web_1      |     at Module.load (module.js:565:32)
web_1      |     at tryModuleLoad (module.js:505:12)
web_1      |     at Function.Module._load (module.js:497:3)
web_1      | error Command failed with exit code 1.
web_1      | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
voice-web_web_1 exited with code 1
```

**Comment by johngian** [comment]
OK so the problem is the following:

* When we build the docker images for web yarn installs the dependencies just fine under ``./node_modules``
* When we run web using docker-compose we mount the repo folder to the container in order to be able to change the codebase for development
* In a clean repo "./node_modules" doesn't exist and overwrites the already installed dependencies

I am opening a PR to fix this.

**Comment by jbinard** [comment]
Great, and it explains why it's working fine when I run yarn locally. The node_modules folder is then created and populated with the dependencies.

Thanks @johngian

**Comment by zenogantner** [comment]
Works now for me with the change from #1130. Thank you for tracking this down!

**Comment by jimregan** [comment]
Had the same issue, #1130 worked for me too.
