### ISSUE TITLE
idea for an alternative data collection approach

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1002]
What do you think about the following idea, I just had:
Tell people what to talk about and then subtitle it afterwards. (write down topics -> record -> transcription)

This way we would get more authentic ways of how people speak casually (and not just high german)

examples:
- Order one beer
- Greet your friend (possible addition: how are you/long time no see)
- Ask your assistant to note down an important appointment (human assistant)
- "I want a ticket for xy pls" / "Hey hit me up with a ticket" etc.
- ask your smartphone to remember you of this and that at 22 o'clock

something along these lines

It's obviously more work.

But it could be connected in a certain way that also makes it less work:
let first gen speech recognition detect the text and ask users/contributors to correct mistakes in the detected sentence(s)  (active training)

**Comment by Djfe** [comment]
also cool would be a real time mode, where you just keep on talking and the speech recognition keeps on translating it into text and when it does a mistake you can cut the recording accordingly and enter corrected sentences.

**Comment by MichaelKohler** [comment]
This sounds interesting, let's have this discussion over at https://discourse.mozilla.org/c/voice/239 if there is still interest!
