### ISSUE TITLE
Contribute.json exists, but is missing some of the required keys

### ISSUE THREAD

**Issue by Undigon** [mozilla/voice-web#1003]
Title quoted from [Observatory by Mozilla](https://observatory.mozilla.org/analyze.html?host=voice.allizom.org)
`voice.allizom.org score: 95/100`

The **required keys** are without a doubt:
* **"urls":** *(Is voice.allizom.org "stage"? Is voice.mozilla.org "prod"?)*

And possibly, in order of importance as defined by [infosec.mozilla.org](https://infosec.mozilla.org/guidelines/web_security#contributejson):
* "participate": { **"irc":** } *(Would "chat" be enough?)*
* "participate": { **"irc-contacts":** } *(Any suggestions?)*
* "repository": { **"tests":** } *(Is "https://travis-ci.org/mozilla/voice-web/" a good value for that key?)*

The proposed values were adapted from Bedrock's contribute.json

**Comment by Gregoor** [comment]
Thanks for paying attention!

> "urls": (Is voice.allizom.org "stage"? Is voice.mozilla.org "prod"?)

Yes, that's correct.

RE participate, AFAIK we don't have an IRC channel, but we do have a Slack. Maybe we should add two keys for that, i.e. `slack` which is https://common-voice.slack.com/and `slack-invite` which is https://common-voice-slack-invite.herokuapp.com

And with tests you indeed have the right one as well.

👍

**Comment by Undigon** [comment]
Excelent. I will change that in nine hours.

**Comment by Gregoor** [comment]
Awesome, thanks for owning this! Now we ace the test 🎉 yay

![screenshot_2018-05-16 observatory by mozilla](https://user-images.githubusercontent.com/4051932/40104129-cf0d2422-58ef-11e8-8719-8c75d296211b.png)
