### ISSUE TITLE
Missing pluralization in strings

### ISSUE THREAD

**Issue by piotrdrag** [mozilla/voice-web#1008]
“contribute-more = Ready to do { $count } more?” and “clips-submitted = { $count } Clips submitted!” need to be pluralized, or they are untranslatable in many languages.

By the way, “toward-goal = That's <goalPercentage></goalPercentage> toward today's Common Voice { $goalType } goal. Thank you” and the two goal-type variables could use comments, so translators understand how the sentence is built.

CC @peiying2

**Comment by Gregoor** [comment]
Thanks for noticing that! Fluent docs are here: https://projectfluent.org/fluent/guide/selectors.html Will tackle on Monday if noone else takes it.

**Comment by Gregoor** [comment]
Done! Though I'm not sure if I have to rename the string (we already have a few translations which I wouldn't want to lose).
