### ISSUE TITLE
Latin

### ISSUE THREAD

**Issue by hs116693** [mozilla/voice-web#1009]
When one goes to request a new language, translation of Latin should be 'Latina' rather than 'Latine'.

**Comment by Gregoor** [comment]
Thanks for the tip, though from looking at [this](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) wiki list, both seem to work. I don't know enough about latin myself though 🙊

**Comment by Gregoor** [comment]
This isn't very actionable nor active, so I'll close it for now. Happy to reopen!
