### ISSUE TITLE
The link to the TED-LIUM corpus is outdated

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [mozilla/voice-web#1010]
The link to the TED-LIUM corpus on https://voice.mozilla.org/en/data is outdated. The latest version of the TED-LIUM corpus is v3, which may be found at https://lium.univ-lemans.fr/en/ted-lium3/

**Comment by missuniverse** [comment]
Correction, the link is: http://www.openslr.org/resources/51/TEDLIUM_release-3.tgz
The external url is the one you stated.

**Comment by lissyx** [comment]
@Franck-Dernoncourt Training has been done on v2 of the corpus, should we still update the link ?

**Comment by mikehenrty** [comment]
@lissyx yes we still want to update the link. even though the DeepSpeech models were based off the older version of the data, Common Voice is a separate project, and so we want to promote the most up-to-date dataset regardless of what DeepSpeech is using.

**Comment by kdavis-mozilla** [comment]
@mikehenrty @lissyx No models released by Deep Speech made use of TED data. TED data is not licensed so as to be usable in commercial products.

**Comment by Gregoor** [comment]
fixed through #1015
