### ISSUE TITLE
Webpage graph is still stuck at 379 validated hours

### ISSUE THREAD

**Issue by aladar42** [mozilla/voice-web#1011]
There should be some kind of explanation for this. Is the project not validating any more hours yet? Is the graph just stuck? I couldn't find any explanation of what is going on, and frankly, it is very discouraging to see the amount validated to be the same as 5-6 months ago. This should be addressed, I'm sure I'm not the only person who is wondering and having doubts about continuing to contribute validation.

**Comment by jf99** [comment]
I'm pretty sure it was at 365 about two weeks ago. I noticed that because it's the number of days in a year and probably also the approximate age of the project.

**Comment by jf99** [comment]
Could be related to #999 though. Maybe many people can't validate anymore so the progress is really stuck.

**Comment by Tignor82** [comment]
I just came across this project yesterday, and the graph was at 378.  Today it's at 379.  Not sure if either number is accurate, of course, but I noticed a change from yesterday to today.

**Comment by aladar42** [comment]
Yeah, today I can see it changed. Weird. All is fine on my end now, though.

**Comment by Gregoor** [comment]
[Those numbers were static for a while](https://github.com/mozilla/voice-web/issues/784), but now they sure aren't 🙂
