### ISSUE TITLE
Language name for Kabyle Shows the language code

### ISSUE THREAD

**Issue by belkacem77** [mozilla/voice-web#1018]
Common Voice web site shows the language iso code rather than the native name 'Taqbaylit'

**Comment by Gregoor** [comment]
Thanks for the report. Unfortunately for getting the native name, we currently use a libary based on ISO 639-1 which doesn't contain Kabyle. What we should do to support Kabyle and many other languages is to write a script that gets all the native names from their respective fluent files.

**Comment by belkacem77** [comment]
Does this mean we can't get Kabyle on Common Voice for now? Most tools, systems, applications nowadays, works with ISO-369-2,

**Comment by zbraniecki** [comment]
What would be even better is to use CLDR which has translation for `Kabyle` :)

For example: https://github.com/unicode-cldr/cldr-localenames-modern would solve it for you.

The overlay to get additional translations from fluent resources is something I believe would be of additional value and allow us to also provide translations for language names not in CLDR, or overwrite in case we have a better translation, but I think that starting with CLDR should fix the issue at hand.

**Comment by kdavis-mozilla** [comment]
@zbraniecki @Gregoor I love it when a plan comes together. [CLDR](https://www.unicode.org/cldr/charts/latest/supplemental/language_territory_information.html) is what Michael and I ended up settling upon for identifying languages and their dialects.

**Comment by belkacem77** [comment]
@Gregoor , thanks, finally we can go on with our corpora.
@zbraniecki , I think the link you gave is about ISO 639-1 language list.
CLDR full locale names id here : https://github.com/unicode-cldr/cldr-localenames-full/tree/master/main/kab.

**Comment by zbraniecki** [comment]
Also, a bit of my team's promo, but I hope in context :) We just published Internationalization docs for Mozilla developers - https://firefox-source-docs.mozilla.org/intl/index.html - should have most answers wrt. working with locales :)

**Comment by Gregoor** [comment]
![screenshot_2018-08-21 common voice by mozilla](https://user-images.githubusercontent.com/4051932/44407190-c1fe2500-a55d-11e8-95f1-55d4e3089794.png)
🙂 (sorry that it took some time)

**Comment by belkacem77** [comment]
Sorry, I forgot to close :) thanks for job
