### ISSUE TITLE
Add Korean Support

### ISSUE THREAD

**Issue by jjhttoz** [mozilla/voice-web#1023]
I found that Korean language is in progress in the languages category.

![a](https://user-images.githubusercontent.com/37290956/40585360-38d87f8c-61ec-11e8-8cb7-c41fdeb7bc58.png)

If we change "GET INVOLVED" to "참여하기" like other languages, It would be helpful to support Korean language.

**Comment by Gregoor** [comment]
Heya, thanks for noticing 🙂 Translations are handled on Pontoon, so if you know Korean, yo ucan add that string here => https://pontoon.mozilla.org/ko/common-voice/cross-locale.ftl/?string=177872

**Comment by jjhttoz** [comment]
I translated all resources from the above site into Korean !!
When and how is it patched?

**Comment by mikehenrty** [comment]
@jjhttoz that's great to hear! please send an email to me (mikey at mozilla.com). I will get you into our translation tool.

**Comment by peiying2** [comment]
@jjhttoz, thank you for contributing. Right now your translation is pending peer review. Let me introduce you to the community. Have them take a look. Once approved, they will be ready for staging and eventually add to production push.

**Comment by jjhttoz** [comment]
I am sending you a mail request. Is there anything else I can help you with? 
 
-----Original Message-----

**Comment by jjhttoz** [comment]
Thank you for the information. And I sent you a mail.
Is there anything else I can help you with?

**Comment by peiying2** [comment]
@jjhttoz I can see your email address and other contributors' email addresses in Pontoon. No need to send me request. Let me do it this way. I will give you translator access to Common Voice project. This way, you will see it on staging in less than half an hour. Then I will send you the intro so the Korean l10n community.

**Comment by jjhttoz** [comment]
Oh, I got you. I'm impressed that our translation is helpful.
I'll be waiting then.
