### ISSUE TITLE
Bug was found in common voice app

### ISSUE THREAD

**Issue by duswl9801** [mozilla/voice-web#1024]
A bug was found in the languages category in the common voice app 
when viewing mobile on iPhone&Android.

![3b52b443-99eb-4a4a-9665-689ac9295f05](https://user-images.githubusercontent.com/37291010/40585418-880875fc-61ed-11e8-897a-57036d386d52.png)
There is a blank space between Frisian and Welsh as shown in the picture.

**Comment by kdavis-mozilla** [comment]
Looks to be brezhoneg

**Comment by Gregoor** [comment]
I just updated the locales, thanks for the report!

@peiying2 could I somehow get a notification through Pontoon when a new language is added, so that I can react more quickly to it?
