### ISSUE TITLE
[Safari] App won't load on iOS/Safari v10

### ISSUE THREAD

**Issue by roaker** [mozilla/voice-web#1026]
A bug was found in the common voice app
when opening app mobile on iPhone,
 sometimes screen turns white. 
 it happens more often than I thought, and I think it needs correction.

**Comment by lukereichold** [comment]
This appears to be due to not having any launch images set.

**Comment by lukereichold** [comment]
Reproduced issue with iPod Touch running iOS 10.3.3. Appears to be an issue with the website generally supporting the iOS 10 version of WKWebView, since I could also reproduce this outside of the app by navigating to `https://voice.mozilla.org` in Safari on an iOS 10 device.

**Comment by MichaelKohler** [comment]
@lukereichold is this still an issue?

**Comment by OliverRM** [comment]
For me (iPhone 7, iOS 13) the issue is solved.
