### ISSUE TITLE
Bug: Automatically "Upload aborted" after some minutes when I pressed "Submit"

### ISSUE THREAD

**Issue by Sav22999** [mozilla/voice-web#1031]
(Language English)
When I press "Submit", after some minutes (more or less 3-5mins) system returns an error: "Upload aborted" (and asked me "Keep" or "Delete" recordings).
Basically, it's the same message when you press "Cancel submission".

In this way I can't submit my recordings.

I've checked on Firefox Desktop Windows, Firefox for Android and Opera Desktop Windows.
I've a good connection to network, so it's not a speed problem.

![immagine](https://user-images.githubusercontent.com/32335378/40747150-b3a13174-645c-11e8-877d-060defb681b6.png)
![immagine](https://user-images.githubusercontent.com/32335378/40747355-515bcf96-645d-11e8-9a58-b74ce2ad0ec1.png)

**Comment by Gregoor** [comment]
Is this still happening? If so, I'll reopen!

**Comment by Sav22999** [comment]
No, there isn't anymore :) thank you
