### ISSUE TITLE
Add `?` & keyboard icon to speak portal helper links

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#1032]
These are short & sweet -- at https://voice.allizom.org/en/speak `Unable to speak right now` needs a friendly `?` to round out the link's question. 

Additionally, we're missing the keyboard icon for the `keyboard shortcuts` button.

On staging:

<img width="403" alt="screen shot 2018-05-30 at 2 46 33 pm" src="https://user-images.githubusercontent.com/18686986/40749292-55d9939a-6418-11e8-8a4c-c8a1f1b0a31d.png">

**Comment by Gregoor** [comment]
(Another thing that is missing is something happening once you click that button 🙈 )

I wasn't able to get the icon from Zeplin, can you help @georai?

**Comment by m-branson** [comment]
>(Another thing that is missing is something happening once you click that button 🙈 )
Indeed! I thought you hadn't done work on it yet 😬 

I believe @georai has ideas to enhance this overlay solution you've come up with (which I assume is interim?). Request for you @Gregoor : if you implement interim changes to UI make an issue for the full UI version implementation later so we can be sure to track. :)

**Comment by Gregoor** [comment]
Yes, very much interim. I like that idea for tracking, is it alright if we use this issue for it (seems related enoguh to me)?

**Comment by Gregoor** [comment]
I changed the shortcuts modal to @georai's design. Looks much better now, thanks! 🙂 

I still need that keyboard icon for the button though, @georai. I can't download it from Zeplin for some reason.

**Comment by m-branson** [comment]
The interim shortcuts modal is looking good. Thanks both. @Gregoor will you have time to update the global modal style to the blue background color with updated drop shadow styling? Noticed that it's still black with no shadow on the card.

Current styling:
![screen shot 2018-06-04 at 8 56 43 am](https://user-images.githubusercontent.com/18686986/40930773-7f79a56e-67dd-11e8-9fae-0a694c4598c5.png)

Desired styling:
![screen shot 2018-06-04 at 9 02 53 am](https://user-images.githubusercontent.com/18686986/40930787-89f6357a-67dd-11e8-9360-b36d62a214b0.png)

Also, I'm able to download the keyboard icon...have you clicked on the little guy itself when you're in the button screen?

![screen shot 2018-06-04 at 9 52 51 am](https://user-images.githubusercontent.com/18686986/40930758-720c589a-67dd-11e8-91ed-dfcba10d3c85.png)

**Comment by Gregoor** [comment]
Yes, now it works. I think George updated it yesterday. Thanks! 🙂
