### ISSUE TITLE
During clip re-record, provide `cancel` action in active recording pill

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#1034]
Currently when re-record is selected from the `pill.done.recording` users are prompted to "Start Recording" & the option to "Cancel re-recording" is lost down in the bottom of the UI.

Instead:
- Utilize a "Cancel" link in the `pill.open.active.rerecording` that routes back to the last open clip.
- Bring the "Unable to speak right now?" link next to shortcuts back.
- Update the prompt above the clip card to read "Click [mic icon] to re-record"

<img width="1286" alt="screen shot 2018-05-30 at 2 57 18 pm" src="https://user-images.githubusercontent.com/18686986/40752719-913eafa8-6425-11e8-8080-75b1d6398e48.png">

**Comment by Gregoor** [comment]
Great point, thanks! I Should it be an underlined link? I think it should be distinct from the non-actionable `Start Recording` that usually sits there, no?

**Comment by m-branson** [comment]
Yes, agreed :) Underlined to convey that it's indeed clickable (in addition to the blue hover).
