### ISSUE TITLE
div.contribution.speak requires more padding around sentence card

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#1036]
@Gregoor we may need to talk about this one a bit 1:1 to better determine how to move forward.

The issues I'm seeing: content like the sentence cards and pills are too close together (tense!); while the outer content margin is quite large. Do we have room to widen the box model on desktop to allow for more "room to breathe"?

Note, I'm viewing at 1440 x 900 and feel we can achieve a bit less tension between all of the elements at the center of the page. e.g. increase space left and right of the sentence card, moving elements like the pills & top links further out. I do feel the spacing of the bottom UI is appropriate, especially for mouse tracking distance...this may be tricky. 😬

**Comment by Gregoor** [comment]
Desktop is now wider, I feel like that solved it, let me know if not 🙃
