### ISSUE TITLE
Update success screen secondary button styling

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#1037]
Currently the success screen utilizes two pill shaped buttons. I'd prefer that we utilize only one (black) as it draws primary attention. Therefore, can we update the style of our secondary CTA (edit profile) to a simple underlined link? Same text style as the button, just with an underline (and blue hover).

Current:

<img width="976" alt="screen shot 2018-05-30 at 5 08 20 pm" src="https://user-images.githubusercontent.com/18686986/40754124-70c0b2a6-642c-11e8-8f73-22a31f00e07b.png">

**Comment by Gregoor** [comment]
Thanks for that feedback :) usually our "text buttons" are not uppercased, should I change those as well then, or just make it a local version?
There's a different version of that screen when you're a new user. Should that change as well?

**Comment by m-branson** [comment]
Yes to changing on both returning and new user instances of the screen. :)

RE: button styling let's stay consistent with camel case so `Edit Profile` in this instance.
