### ISSUE TITLE
What is the meaning of the language progress indicator? 

### ISSUE THREAD

**Issue by danielsjf** [mozilla/voice-web#1038]
The highest values I see are 50%. Based on what are they measured? The pontoon translations as the first 50% and enough sentences as the last 50%?

**Comment by Gregoor** [comment]
Thanks for raising that issue, other people also shared that sentiment, which is why we now have some explanation on staging: https://voice.allizom.org/en/languages

**Comment by jf99** [comment]
So, what exactly is still missing for German? Is it only issue #1000 or is there more? Multi-language should have launched 3 weeks ago.

**Comment by danielsjf** [comment]
Yes, the same for Dutch where I've uploaded well over 2500 sentences. I also suggested all translations on Pontoon, but the approval stage seems to be the bottleneck.

**Comment by danielsjf** [comment]
As a more general comment, it would be good to have a call to action underneath the explanation of the progress indicator (which is very clear btw). So far the only place where you can find a good description on how to contribute is the global sprint explanation.

**Comment by danielsjf** [comment]
Great to hear! Is there a way we can contribute to the definition of these accents?

**Comment by Gregoor** [comment]
I'm about to learn what we're going with today, I'll put a braindump here after. [I think it'll be based on CLDR](https://github.com/mozilla/voice-web/issues/1018#issuecomment-393079572)

**Comment by mikehenrty** [comment]
Thanks for all your thoughts here everyone. We are currently revamping the languages page to incorporate this feedback. No need to keep this bug around.
