### ISSUE TITLE
Tooltip Styling (global)

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#1040]
Tooltip needs:

- text to be vertically centered in the pill
- black pill and black down arrow should be full #000; currently pill color looks lighter or as a gradient?
- ideally a max width of 180px

Current:
<img width="375" alt="screen shot 2018-05-31 at 5 09 03 pm" src="https://user-images.githubusercontent.com/18686986/40814667-69d55cf6-64f6-11e8-9fb3-4158a1e2957a.png">

Preferred:
<img width="272" alt="screen shot 2018-05-31 at 5 13 22 pm" src="https://user-images.githubusercontent.com/18686986/40814669-6eea958a-64f6-11e8-9511-eada97dfac84.png">

**Comment by Gregoor** [comment]
That color is indeed lighter, it's 4a4a. but the one from the designs has that same color. Should we go with black instead?
