### ISSUE TITLE
Disable 'Skip' button during active clip record

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#1043]
When mic is active, skip button should be disabled.

**Comment by Gregoor** [comment]
What I don't like about having it this way is the scenario where a user notices while speaking that they just can't get that sentence right. These are the click they'd have to do with new interaction:
1) Stop
2) Re-record
3) Skip

Whereas if we don't disable Skip and make it discard the recording, that scenario would only require a single click.

**Comment by m-branson** [comment]
To confirm: if we keep as is, a user may start recording > begin speaking clip A > press skip halfway through > fully speak clip B. Then when submitted for validation, that clip would be both partially one sentence and fully another sentence. Which sentence is shown for validation? Does it then cause more confusion to a listening user later on?

The insistence I have with doing the...

>
    Stop
    Re-record
    Skip
...method is to ensure the clip data being submitted is the best possible.

I understand the 1 click usability argument you've made, I'm concerned the data produced won't be as effective. Curious your thoughts here as well @mikehenrty?

**Comment by Gregoor** [comment]
Oh noes, something got lost in translation there. When you click skip your current recording is completely discarded and you get a new sentence. So when you record that sentence, the other partial recording.

**Comment by m-branson** [comment]
Ah got it, sold! Let's do the way you recommend, eg keep as is. :)

**Comment by Gregoor** [comment]
Cool 🙂
