### ISSUE TITLE
[Language Page] get "contribute" string into single cross-language ftl file

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#1056]
Perhaps we can think of a better way to do this through tooling?

**Comment by Gregoor** [comment]
The contribute string is in that file and translated to all launched languages now. I'll talk to @stasm next week (if he also has the time) about a different architecture for loading them strings (I have ideas! 🙃 ).

**Comment by stasm** [comment]
I'll be more than happy to talk about this! I sent you an invite for next week.

**Comment by mikehenrty** [comment]
Great, it sounds like we don't need this bug anymore. Feel free to re-open if I'm mistaken!
