### ISSUE TITLE
Define the browser support matrix

### ISSUE THREAD

**Issue by stasm** [mozilla/voice-web#1058]
What is the intended browser support matrix for http://voice.mozilla.org?

I'm asking because in https://github.com/projectfluent/fluent.js/issues/133 we're considering dropping the support for old versions of Chrome and Firefox as well as the support for IE11. Fluent is used the localize the Common Voice website. Dropping the support would mean that the `fluent/compat` builds would contain async functions and `function*` generators, which cause syntax errors in browsers which don't support them. On the upside, no more `regeneratorRuntime` required :)

Here's the list of browser versions we're currently considering supporting in Fluent's `compat` builds:

    Firefox >= 52,
    FirefoxAndroid >= 52,
    Chrome >= 55,
    ChromeAndroid >= 55,
    Edge >= 15,
    Safari >= 10.1,
    iOS >= 10.1

**Comment by stasm** [comment]
Do you only care about [browsers which support `MediaRecorder`](https://caniuse.com/#search=MediaRecorder)?

**Comment by Gregoor** [comment]
Heya @stasm, thanks for the notice 🙂 We do apparently have some IE11 users ([which I upset by recently breaking the site for them](https://github.com/mozilla/voice-web/issues/597)).
Since I'm biased as it'd make my life easier (and yours probably as well), I'd like to hear @mikehenrty's take on this.

RE MediaRecorder: That is (unfortunately) our current requirement for recording, but users without it can still validate clips and look at other pages of CV.

**Comment by mikehenrty** [comment]
Internet Explorer 11 is 2% of our users, with a 90% bounce rate. So I am not too concerned about lack of support.

That said, having syntax errors is kinda a problem, as I would love to at least be able to display our `Download Firefox` page even if only in English.

@Gregoor or @stasm, is it possible for us to trap this error, or run feature detection so that the site isn't just a blank screen for legacy browsers?

**Comment by mikehenrty** [comment]
also @stasm what's the standard way mozilla properties define their browser support matrix? meaning, do they have docs they host somewhere to show this?

**Comment by stasm** [comment]
> is it possible for us to trap this error, or run feature detection so that the site isn't just a blank screen for legacy browsers?

One way of supporting this use-case would be to do server-side rendering. I don't know, however, how much work it is to add it to Common Voice and I don't want to add extra work for you right now.

@Gregoor Would it be possible to have a some static content below or inside of the React root, which would remain visible when the JS errors?

> what's the standard way mozilla properties define their browser support matrix? meaning, do they have docs they host somewhere to show this?

I don't know what the best practice at Mozilla is. For Test Pilot, I found an [FAQ entry](https://github.com/mozilla/testpilot/blob/master/docs/faq.md#what-browsers-are-supported-by-test-pilot). For Screenshots, I filed an issue similar to this one :) As a consumer of this information, I would be happy with a paragraph in `CONTRIBUTING.md` or with a `.babelrc` with a `babel-preset-env` config similar to the list I pasted in the description above.

**Comment by stasm** [comment]
Also, I'm not sure if this is known, but here's what I see at https://voice.mozilla.org in IE11:

![image](https://user-images.githubusercontent.com/265818/41046753-3d79cac0-69ab-11e8-80ce-45536265956c.png)

The error in red says _Syntax Error_. Should I file a bug?

**Comment by Gregoor** [comment]
Thanks for looking into it! I accidently broke IE11 (#763) (and someone from the community noticed).

I'd love to put server side rendering in, but it's not very high up my list. So for now I just put the unsupported browser info in, which we also show for recording.

**Comment by stasm** [comment]
> I'd love to put server side rendering in, but it's not very high up my list. So for now I just put the unsupported browser info in, which we also show for recording.

Do you mean this as a temporary solution until the website is fixed in IE11, or as a long term stance on not supporting IE11? :)

**Comment by mikehenrty** [comment]
> Do you mean this as a temporary solution until the website is fixed in IE11, or as a long term stance on not supporting IE11? :)

Server-side rendering is not a temporary solution or work-around. It's simply a nice feature that has many advantages. But I don't want to talk about it as a way to support legacy browsers at this point.

To reiterate what (I think) we discussed at All-Hands, I'm fine with dropping support for IE, but I want to make sure we are displaying that nice "Download Firefox" message for those users :)

For this bug: let's define the browser support in our FAQ. What do you think @Gregoor ?

**Comment by stasm** [comment]
My question about the temporary solution referred to this part of @Gregoor's comment:

> I just put the unsupported browser info in, which we also show for recording.

Sorry for not making it clear.

> To reiterate what (I think) we discussed at All-Hands, I'm fine with dropping support for IE, but I want to make sure we are displaying that nice "Download Firefox" message for those users :)

That's how I understood our conversation as well. Thanks, @mikehenrty!

**Comment by Gregoor** [comment]
We now have a browser support matrix (basically the one from Fluent):
https://github.com/mozilla/voice-web/blob/master/docs/browser-support.md

Thanks for the discussion everyone!
