### ISSUE TITLE
[staging] "No" button is displayed before recording finished playing 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1066]

**Comment by Gregoor** [comment]
[That is by design](https://github.com/mozilla/voice-web/issues/382). The no-button comes in after 3 seconds.
I can definitely see that it can look weird. @m-branson should I maybe then show "yes" as well, but as a disabled button?

**Comment by m-branson** [comment]
>...show "yes" as well, but as a disabled button?
@Gregoor yes please :) Also, can we just have the buttons show immediately rather than on a delay at all?

**Comment by m-branson** [comment]
>Then I'll change it to show them immediately, but in a disabled state (with no being enabled after 3 seconds).

Perfect :)

**Comment by Djfe** [comment]
@viorelaioia the reason is, that you can tell, whether a recording is speaking everything correctly, before the recording finished.
Someone misspelled a word or the recording is a lot of silence -> you can abort and press No earlier.
