### ISSUE TITLE
{goalType} not properly replaced in goal-help string

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/voice-web#1068]
In the following string ([goal-type](https://pontoon.mozilla.org/fr/common-voice/all-resources/?search=goal-help&string=179265)) the variable is not properly replaced with the translation (`recording` should be `enregistrements`)

![screenshot_2018-06-06 common voice by mozilla](https://user-images.githubusercontent.com/1294206/41059513-adb853ec-69c4-11e8-8510-225472173d24.png)

**Comment by Gregoor** [comment]
Thanks for reporting that! It should be fixed now 🙂
