### ISSUE TITLE
Validated the same sentence/pronunciation twice

### ISSUE THREAD

**Issue by magopian** [mozilla/voice-web#1069]
Here's a screenshot of the requests made when validating some sentences on https://voice.mozilla.org/fr

<img width="739" alt="screen shot 2018-06-07 at 17 01 54" src="https://user-images.githubusercontent.com/167767/41108819-c19f7c80-6a75-11e8-87a0-fd6e72f6b6d4.png">

There's several weird things happening there:
1/ I get the https://voice.mozilla.org/api/v1/fr/clips?count=10 request several times in a row, the red squares in the screenshot (I guess i'ts because I've validated all the available clips at that point?)
2/ I get the same audio clip several times (probably same issue as above), the blue squares in the screenshot
3/ I got the same audio clip presented twice in a row (and validated it twice), the pink ovals in the screenshot

First POST:
```
curl 'https://voice.mozilla.org/api/v1/fr/clips/17302000/votes' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0' -H 'Accept: */*' -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'Referer: https://voice.mozilla.org/fr' -H 'Content-type: application/json; charset=utf-8' -H 'uid: d04a2398-b5f5-44c4-8082-5198975656a6' -H 'Cookie: _ga=GA1.2.801161008.1521640830' -H 'Connection: keep-alive' --data '{"isValid":true}'
```

Second POST:
```
curl 'https://voice.mozilla.org/api/v1/fr/clips/17302000/votes' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0' -H 'Accept: */*' -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'Referer: https://voice.mozilla.org/fr' -H 'Content-type: application/json; charset=utf-8' -H 'uid: d04a2398-b5f5-44c4-8082-5198975656a6' -H 'Cookie: _ga=GA1.2.801161008.1521640830' -H 'Connection: keep-alive' --data '{"isValid":true}'
```

I saved the full log of requests as HAR: https://send.firefox.com/download/c943aad462/#xfl9YnpfO3I599JbDuMBWA

**Comment by Gregoor** [comment]
Heya, thanks for the detailed look at this, much appreciated! 🙂 

1) Yes, that is for caching purposes, so that no one has to wait to validate more clips
2) That is an AWS thing I couldn't quite figure out yet, it only happens for the first clip though.
3) This sounds a bit like #1022, though seeing the same sentence twice in a row should be extremely unlikely (well at least for english, given that there are few french clips, this might be more likely). Did that happen to you more than once?

Thanks again!

**Comment by magopian** [comment]
You're much welcome, thanks a lot for your work, this service is awesome <3

The issue only occurred once, maybe I was just "lucky" :P

Regarding the caching purposes, I was going to create a new issue: it seems the audio files are often not taken from the cache, but are re-downloaded instead, not sure why (at least that's how it appears in the devtools).

If you look at the same audio files downloaded several times, well, it was re-downloaded each time, instead of being taken from the cache (see the last item which is clearly indicated as "cached").
That may be because of a firefox bug (i'm running Firefox Nightly), and might be better investigated in another issue. Would you like me to create another one?

**Comment by jf99** [comment]
@magopian This reminds me of [issue #281](https://github.com/mozilla/voice-web/issues/281#issuecomment-361079893).

**Comment by Gregoor** [comment]
Thanks @jf99 I thought it looked familiar!
