### ISSUE TITLE
Unable to contribute my voice

### ISSUE THREAD

**Issue by marco-c** [mozilla/voice-web#1070]
I'm trying really hard to find a way on the website to contribute my voice, but I'm miserably failing.

**Comment by parion** [comment]
Hey @marco-c, first to contribute your voice you'll need a functioning microphone. Make sure it works by testing it in the settings of your OS or in a voice-capturing program, such as Audacity.

Next, visit https://voice.mozilla.org/. You should see the following page.
![image](https://user-images.githubusercontent.com/4733032/41130095-c28cdeb2-6a7a-11e8-9651-66f44e411001.png)

To start contributing your voice, click on the "Speak up, contribute here" button in the middle of the page. The site should go to https://voice.mozilla.org/en/record and display a recording button, as so.
![image](https://user-images.githubusercontent.com/4733032/41130145-fc472342-6a7a-11e8-8971-f1b3f5d34043.png)

Now you're ready to start recording. Click the red button to begin the recording. If this is your first time on the site, your browser should give you the notice that the browser wants your permission to record your voice. Just allow.
![image](https://user-images.githubusercontent.com/4733032/41130238-5f01ed0a-6a7b-11e8-9953-d40ad09226d8.png)

After you finish saying the given phrase, click the red button again. Two more phrases will be presented to you to say. Finally, you should be taken to the confirmation page. Listen to your recording, redo any you messed up, and submit!

Let me know if that solves your issue!

**Comment by marco-c** [comment]
I was able to contribute English, I'm not able to contribute Italian.

**Comment by marco-c** [comment]
N.B.: In order to contribute English, I have to manually modify the URL from https://voice.mozilla.org/it to https://voice.mozilla.org/en.

**Comment by Djfe** [comment]
Hi Marco,

As you can see https://voice.mozilla.org/it/languages
Italian hasn't launched, yet.

We need more sentences in Italian before it makes sense for us to ask people to record their voices.

What you can do right now :)
You can either contribute new sentences under the cc-0 license here:
https://voice-sprint.mozilla.community/contributing/

Or you can contribute your voice to one of the other languages (like English for example)

@m-branson 
You have to change the page's language to be able to contribute in a language.
We are aware that this might be confusing at first.
In the future this might be part of your profile, so that you can contribute to both languages while using the italian interface or so.

Regards,
Djfe

**Comment by marco-c** [comment]
OK, I see. I think the interface is pretty confusing, as you can click "Contribute" and register, but then nothing happens.

**Comment by Djfe** [comment]
We are very greatful for your valueable feedback, thx for taking your time to report this.
A new more mature website was designed in parallel to the multi-language launch. This will be the next thing the team is working on, I think. I'm sure Megan will incorporate your feedback into it. She might've come up with ideas already. The team has only so much time and as the project grew priorities needed to be set, and work was split up.
The new design will address lots of problems that arose over time and were given to us through feedback like yours.
When you develop something, one big problem becomes that you can't take a look at your project with fresh eyes. So you overlook things.
Usability is definitely one of our main goals here.

Have a nice weekend,
Djfe

**Comment by marco-c** [comment]
No worries @Djfe, I understand ;)
I just wanted to point it out so that you know it could be confusing for some people.

**Comment by Djfe** [comment]
I should've taken a look at your profile hehe
You're part of Mozilla already.
Well, it can't hurt to be friendly and explain things. :)

**Comment by marco-c** [comment]
I've uploaded some sentences for Italian at https://voice-sprint.mozilla.community/contributing/.

**Comment by parion** [comment]
> I should've taken a look at your profile hehe
> You're part of Mozilla already.

Oh, well this is awkward... Apologies though, I had no idea you were trying to contribute in Italian.

**Comment by marco-c** [comment]
No worries, I should have described the issue in more detail :wink: 
BTW, I was unable to contribute in English too, I hadn't noticed the button at the top right to switch between languages.

**Comment by mikehenrty** [comment]
> BTW, I was unable to contribute in English too, I hadn't noticed the button at the top right to switch between languages.

something I hadn't considered was that people who could speak english but came from some country where we have a website translation (like Italy or Spain) would be shown their local language and so could have a heard time finding the "English" contribute portal. thanks for the flag. (cc @m-branson )
