### ISSUE TITLE
Question regarding the context of a string (website localization)

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1073]
Where is this displayed? (will this be)
https://github.com/mozilla/voice-web/blob/0b3a4d39fbfbb51699e56b671ecd4449ab14f598/web/locales/en/messages.ftl#L316

It's probably are short form for:
Are you unable to speak right now?
(right?)

**Comment by Gregoor** [comment]
It's shown in the new contribution experience (currently only on [staging](http://voice.allizom.org/)).

**Comment by Djfe** [comment]
lol I checked that page today but not "contribute" hehe

I still don't get the context though.
Will it always show up down there

"Sie können nicht mehr weiter sprechen/ungestört reden?" -> "Verifizieren Sie stattdessen ein paar Sätze" oder wie?
Die Übersetzung muss ja Sinn machen

**Comment by Gregoor** [comment]
Yes, I think that's the idea behind it! Might be inspired by Duolingo, which has a similar prompt. So that users don't feel like they can't interact just because can't talk right now.

**Comment by m-branson** [comment]
@Djfe this is indeed meant to point users to the 'Listen' portion of the portal to encourage contribution even if they find themselves in (for example) a public space where they aren't comfortable speaking out loud. It is indeed short form for "Are you unable to speak right now?". This is an attempt to use concise language and keep our calls to action less 'wordy'. ;) 

I'm curious if you've interacted with it in the contribution portal on staging? (thanks for pointing to @Gregoor) These call to action strings are meant to be interacted with in the front-end and may or may not always make sense when read individually outside of 'visual' front-end context.

**Comment by Djfe** [comment]
What about:
"Feeling more like listening (right now)?" / "Ihnen ist mehr nach Zuhören zumute?"

**Comment by Djfe** [comment]
or shorter:
"Rather listening than speaking"/"You (currently) prefer listening instead of speaking?"
"Lieber zuhören statt reden?"

**Comment by Djfe** [comment]
Sry for the third post (ups)
Anyways: yeah, I used the portal and wasn't 100% sure what it was meant for. I agree without allizom the context would've been 100% unclear hehe
Before listening I thought it might go away after the first submit.
But it's permanent.

**Comment by Djfe** [comment]
"I'm not feeling like talking/speaking."
"Mir ist grad nicht nach Reden zumute."

"I can't speak right now."
"Ich kann gerade nicht reden."

**Comment by mikehenrty** [comment]
great discussion, thanks everyone

@Djfe please use Pontoon for localization suggestions instead of github. closing this. if you would like to file a separate issue about the usability of this link, please do so.
