### ISSUE TITLE
CSP blocks script

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1074]
![Screenshot](https://i.imgur.com/WMYsJk7.png)

**Comment by Gregoor** [comment]
While no one likes errors, this one isn't critical as the inline script is only for IE11, which doesn't support CSP anyway 😁

**Comment by mikehenrty** [comment]
@Gregoor what's a good way to fix this? should we put it in the main app bundle?

**Comment by Gregoor** [comment]
@mikehenrty Since the main bundle is the one that syntax errors in non-supported browsers, we can't put it in there. Does CSP maybe allow hashes for inline scripts as well? It must right, since we do the same thing for analytics?

**Comment by mikehenrty** [comment]
Yes CSP hash or nonce would be one way to solve this. Another way would be to have a top-level js file that asyncronously loads bundle.js and traps any errors from it. Not sure what would be best
