### ISSUE TITLE
Should i validate if i hear a loud mouse click in recording ?

### ISSUE THREAD

**Issue by focom** [mozilla/voice-web#1078]
Was validating a couple of french sentences.
It appears that often the speaker once he has read the sentence take some time to click on the finish button.
So in the recording there is a large blank period followed by a loud mouse or trackpad click.
Should it be validated ? Will it interfer with ML algorythm ?

**Comment by jf99** [comment]
The ML algorithm will learn to separate the voice from background noise. In fact the developers will mix artificial noise into the recordings to make the speech recognition more robust. So clicking sounds should not be a reason for voting "Non".

**Comment by mikehenrty** [comment]
as @jf99 , you can ignore the clicks or background noise, or other artifacts and just focus on what was actually spoken. thank you for the question
