### ISSUE TITLE
record/play icon is missing in string on mobile contribute page

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1079]

**Comment by Djfe** [comment]
![screenshot_20180609-054635_01](https://user-images.githubusercontent.com/5685512/41187399-9ae20304-6ba8-11e8-87a4-431d0bf2ee2b.png)

**Comment by Gregoor** [comment]
That is by design, probably because with the text right next to the button the icon would look a bit redundant. I think we're good here.

cc @m-branson

**Comment by m-branson** [comment]
Yes, this was intentional to avoid icon redundancy. @Gregoor it does look like there's an extra space prior to the comma happening there (though I can't actually read what it says). Is that grammatically correct when translated or should the space be removed?

**Comment by Gregoor** [comment]
True, that space makes it look off. I'll see what I can do to get rid of it (without having to change the string in Pontoon).

**Comment by Djfe** [comment]
that extra space is also happening in english, but it's not as obvious there.
I fixed it manually in German (in the translation)

**Comment by Gregoor** [comment]
Huh thanks for pointing that out. There were indeed superfluous spaces in english (which probably made translators put them in as well).
