### ISSUE TITLE
No error: missing mic permission

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1080]
If you don't give the new contribute page a mic permission, then nothing happens (on mobile)

And you need to reload the page.

**Comment by Gregoor** [comment]
It does give you a message that permission has not been granted. Also afaik there's no way of having to reload the page. Do you have any actionable ideas around this?

**Comment by Gregoor** [comment]
Closing this since I currently don't see how we could make this any better atm (happy to read ideas though!)
