### ISSUE TITLE
Text is displayed in 4 lines

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1081]
![screenshot_20180609-060826_01](https://user-images.githubusercontent.com/5685512/41187556-025ad620-6bac-11e8-8a7e-6df3880dd61f.png)
It would be nice if the sentence would be displayed in only two lines.
"Falls nötig,..."

**Comment by Gregoor** [comment]
How about we change the translation to "Falls noetig, pruefen & neuaufnehmen"?
The chosen translation seems a bit verbose.
