### ISSUE TITLE
Feedback new search (languages page)

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1084]
On mobile it's not evident, that you aren't searching launched languages.
So german/deutsch doesn't show up.

The search icon is invisible in german, because it's to the right side.

Maybe you could display it like this:
Search icon, Vorbereitungsphase, Aufnahmephase.
When Vorbereitungsphase is selected the search icon is underlined (in red) as well.

The close icon is missing on mobile -> you can't close the search.

**Comment by mikehenrty** [comment]
cc @m-branson

**Comment by Gregoor** [comment]
The new search should've fixed all those issues 🙂
