### ISSUE TITLE
"Don't waste your breath"

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1089]
"Don't waste your breath" is rendered on top of the text/layout on mobile, which is kinda annoying.
And upon clicking close once the site should remember so by placing a cookie, to never show the dialog again. (IMO)

**Comment by Gregoor** [comment]
I would prefer it not being permanently hideable. Maybe hide it for a day when closed?

**Comment by Djfe** [comment]
sure, why not.
but it would already be a lot better if the banner wouldn't hide the website behind it. :)
