### ISSUE TITLE
add a "not yet validated" statusbar

### ISSUE THREAD

**Issue by paskalito** [mozilla/voice-web#1092]
on the mainpage there is this overall project status box. were it shows how many hours of validated sentences we have.
I suggest to have a second one (or a second colour added to it) that shows us how many unvalidated hours we have. additionally.

because
- it's cool to know
- if there are way more unvalidated hours it motivates to validate instead of reading new ones
- it shows more of the work that is already done hence it's motivating.
- if there is a lot unvalidated ones it may help to get that changed so more validated data can be used already

ps. also making the validation process more transparent would be cool. - is it valitated if one person validates it? - does it need more than one validation? - are things getting validated again if all the recordings have been validated once? - why is there no way to correct wrongly validated recordings.? ( in th ui) 

pps. also solving #336 would maybe help a lot to get more validations

**Comment by Gregoor** [comment]
Thanks for your thoughtful notes! I agree with you and we're looking into getting that into the new homepage.

cc @m-branson 

RE validation, this is how it works: When a clip has 2 or more votes for either yes or no, it is considered valid or invalid and will not be shown again.
I do agree that we might want to surface how that process works on the site itself.

**Comment by danielsjf** [comment]
Are there some statistics on validated versus not validated? Is it roughly the same or are there large differences? 

The statistics on the top of the page always make mee feel as if I should aim for a 50/50 ratio, while it should actually be 66/33. Maybe there could be a way to give incentives to achieve this ratio.

**Comment by Gregoor** [comment]
I don't have the numbers atm, will update this comment once I do.

Yes, one of the thinking around the new contribution experience is also guiding users to the kind of contribution we need more of.

**Comment by jf99** [comment]
> When a clip has 2 or more votes for either yes or no, it is considered valid or invalid and will not be shown again.

So 2 yes vs 1 no is considered valid? Or is it the difference that has to be at least 2? What about ratios of 13:11 then?

**Comment by Gregoor** [comment]
> So 2 yes vs 1 no is considered valid?

yup

> Or is it the difference that has to be at least 2? What about ratios of 13:11 then?

I think we want to get as much as possible out of as few votes as needed. Imo the 2 or more votes strategy achieves that.

**Comment by mikehenrty** [comment]
Great discussion everyone. In the new homepage design, this progress indicator is going away in favor of a more holistic stats/status approach. I'm tempted to close this bug, but I would want @m-branson to agree there's nothing actionable here for the short term.

**Comment by m-branson** [comment]
👍 @mikehenrty -- the updated stats will show as a graph that highlights `recorded hours` `validated hours` & `total Common Voice hours`. This will be viewable holistically across all languages, as well as viewable in each launched language.

Additionally, we're working through a clearer way to explain the contribution & validation procress, potentially on an `About` or `How it works` page. I believe @Gregoor has a spearate issue open with a diagram we'll be working from as the basis for our design/storyboard too.

Thanks all for the continual feedback! Keep an eye out for the homepage on staging in the near future. :)

**Comment by paskalito** [comment]
Great to hear things are getting sorted out and the best possible soloution is bein found from all the sides.

i just want to say that how i understand issue tracking its best to close them when the issue is actually resolved and that on production server.
it probably saves you from a lot of duplicates, people gonna make, also its just not resolved until it is.

excited to see it in production though/then :)

**Comment by mikehenrty** [comment]
> i just want to say that how i understand issue tracking its best to close them when the issue is actually resolved and that on production server.
> it probably saves you from a lot of duplicates, people gonna make, also its just not resolved until it is.

Yes, that is a good point @paskalito. But in this case, we are not actually doing what the bug is asking: `add a "not yet validated" statusbar`. Instead, we will be incrementally rolling out changes that address what you are asking for in a different way. So I will close this bug saying "we won't do this exactly, but we hear your concerns and will incorporate that into our plans"

Btw, you can a bit of what we are planning here:
https://projects.invisionapp.com/share/K4FV4BPY6TX#/screens/296514715
