### ISSUE TITLE
Localise the number of validated hours

### ISSUE THREAD

**Issue by Em-AK** [mozilla/voice-web#1099]
### Context
I validate sentences for the **french language** on https://voice.mozilla.org/fr

### Actual behaviour

At the bottom of the page the number of validated hours for the **english language** is displayed.
![selection_133](https://user-images.githubusercontent.com/1518393/41359669-49f8350e-6f2b-11e8-8584-20c17d6a540e.png)

### Expected behaviour

I would like to see the number of validated hours for the language I am currently contributing to (here french).

**Comment by mikehenrty** [comment]
Yeah, I'm going to close this since this widget is going away in favor of a more holistic stats/status homepage. Stay tuned for that!
