### ISSUE TITLE
In progress languages overview text is a bit odd

### ISSUE THREAD

**Issue by ftyers** [mozilla/voice-web#1102]
This text is a bit difficult to translate, perhaps the original wording could be changed?

![captura de 2018-06-13 23-53-12](https://user-images.githubusercontent.com/449545/41380350-fc2a1f1a-6f64-11e8-9f68-11fa93ee96c4.png)

"    In progress languages are currently being built for contribution by our communities; their progress reflects where they are across the website localization and sentence collection phases."

Perhaps something like:

"Here are the languages that people in our community are currently working on; the progress bars indicate how far along they are in the process of website localisation and sentence collection."

**Comment by mikehenrty** [comment]
cc @m-branson.
