### ISSUE TITLE
Word use in a language in different regions

### ISSUE THREAD

**Issue by danielsjf** [mozilla/voice-web#1105]
This is probably an issue that you've already seen in English as well. Most languages do not only have different accents, but also different words that are used in different regions. At the moment, only the accents are flagged, but not the words. In reality you will almost never see them mixed, but with the current setup this will be the case.

This might be something to take into account as a future development.

**Comment by mikehenrty** [comment]
Thanks for bringing this up @danielsjf. Yes, this is definitely something we are considering for the future. Take Chinese for instance, there are both multiple ways to write the language (traditional vs. simplified) as well as multiple ways to speak each writing style (mandarin vs. cantonese). It is something we are constantly considering. Let's close this bug, as I don't think there is anything actionable we can do for this in the code right now. If we want to have a longer community discussion about this, please consider posting to discourse:
https://discourse.mozilla-community.org/c/voice
