### ISSUE TITLE
Download Data By language

### ISSUE THREAD

**Issue by ad1rie1** [mozilla/voice-web#1111]
Hello, 
It can be a good idea to propose data by language in the download section.

Dear,

**Comment by mikehenrty** [comment]
We will definitely add this when we release data from the new languages. Stay tuned!

**Comment by azarezade** [comment]
@mikehenrty do you have any plan to release also the partial data from any language, since it seems a some language wouldn't be complete in the near future!

**Comment by Gregoor** [comment]
@azarezade We'll release everything we've collected up til December 2018 very soon.

**Comment by pcgreat** [comment]
@Gregoor Any updates on the release of partial data?

**Comment by Gregoor** [comment]
No updates yet, sorry. If you take this to our Slack or Discourse, people more qualified to answer that than me, might just respond :)
