### ISSUE TITLE
Set html lang attribute according to language

### ISSUE THREAD

**Issue by selimsumlu** [mozilla/voice-web#1112]
**lang** attribute is currently fixed to **en** for all languages.

`<html lang="en">`

This should be set according to the language used on the page. Setting it to "tr" for Turkish is specifically important because it causes capitalization errors otherwise.

**Comment by mikehenrty** [comment]
@stasm, is this something that should be fixed on the fluent side?

**Comment by Gregoor** [comment]
@mikehenrty I think that one's on us.

Probably best to run `document.documentElement.setAttribute('lang', locale)` in our locale change listener for now.

**Comment by stasm** [comment]
Thanks for asking, @mikehenrty, and thanks for answering, @Gregoor :) I was away for the weekend and yesterday. I agree that it's best to fix this in the app for now and I'm happy to see how simple the fix was.
