### ISSUE TITLE
Visualize the whole process

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#1116]
Possibly on an About-Page. Since I tend to think in diagrams, here is one:

![cv](https://user-images.githubusercontent.com/4051932/41493584-76ad2418-70bd-11e8-94f0-3fb0c09a1c3e.png)
(Note that the clip graveyard is/will be published as well, separately)

I see three different points here that could directly link into the experience (listen, speak & download). Imo that would be kind of nice as well.

(Here is the gliffy file if you want to play with it: [cv.gliffy.txt](https://github.com/mozilla/voice-web/files/2107731/cv.gliffy.txt))

cc @m-branson @mikehenrty

**Comment by Gregoor** [comment]
we have an about page now :)

https://voice.mozilla.org/about

**Comment by mbransn** [comment]
Yes we do! Thanks for the patience as we got this up.
