### ISSUE TITLE
Option to record own voice for a sentence in validation

### ISSUE THREAD

**Issue by ftyers** [mozilla/voice-web#1119]
Here is a feature idea (not high priority). When validating sentences it would be cool to have an option to "contribute your voice for this sentence".

It would require a bit of ux work to avoid messing up the flow.

**Comment by mikehenrty** [comment]
cc @m-branson

**Comment by m-branson** [comment]
Super intriguing! Great idea, could almost provide a lever switch to swap from play to record and back again. Thanks @ftyers 👍

**Comment by MichaelKohler** [comment]
As far as I know there is (will be) a trend towards a limit of 1 recording per sentence, so I'm closing this.
