### ISSUE TITLE
Listen and Home pages cache the null validation sentence

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/voice-web#112]
When everything has started and there are no sentences in S3 a null appears in the validation area.

If subsequently sentences are added the null remains despite sentences existing in S3

This is validated by a reload of the Listen or Home page when a null appears.

This is *not* critical as the easy solution is not code based, simply add one or more recordings to S3 before release.

**Comment by SofiCgr** [comment]
Hello! image for this bug
![null_at_validate](https://user-images.githubusercontent.com/2266663/27545769-98c4ccc8-5a88-11e7-8933-e0df78e2ffd1.jpg)

**Comment by mikehenrty** [comment]
This has been fixed. We at least now show an error message to try back later.
