### ISSUE TITLE
[staging] Sometimes the record remains locked to Play state 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1124]
I was able to reproduce this often on Windows 10, Mac and Ubuntu, latest Firefox and Chrome.
I don't have specific steps to reproduce for this, but while listening to several recordings, I noticed that some of them never stopped playing, so they were locked to Play - and only No options was displayed.
In order to get out of this situation, I had to select No.
See [video](https://drive.google.com/file/d/1EFUI7EQL8vRBmYJw7hKoqZeNitzALatm/view?usp=sharing) or screenshot. 
![locked](https://user-images.githubusercontent.com/5293100/41592490-666ee55e-73c5-11e8-936d-7f635928b77c.png)

**Comment by Gregoor** [comment]
I'm having a hard time reproducing this. Maybe we have a few overly long clips on staging. In those cases voting no would be the only right move.

**Comment by viorelaioia** [comment]
@Gregoor , I couldn't here any sound. The Play state situation took more than 1 minute and we cannot do a record that long, from what I tried. I can try to reproduce again, if that helps.

**Comment by Gregoor** [comment]
@viorelaioia True, recording is capped at 10 seconds, though someone could craft a request with a longer recording. Though a bug in the FE is probably indeed more plausible.
Do you have a rough number after how many listens that occured? I didn't have any "luck" after doing a few dozen.

**Comment by viorelaioia** [comment]
@Gregoor , I encountered that quite often last time I tested. I cannot seem to reproduce it easily now. 
I got in a similar state now by clicking Play and then Skip button (while the record was still playing): locked on Play, only "No" button was available. Should we disable Skip button when the record is playing?

**Comment by m-branson** [comment]
> Should we disable Skip button when the record is playing?

If this is the true source of the issue, I'm okay from a UX perspective disabling skip while the recording is playing.

**Comment by Gregoor** [comment]
Now the audio properly stops when skip is clicked. Thanks for raising this issue!
