### ISSUE TITLE
[staging] No feedback when switching from Speak to Listen and submitting clips 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1127]
STR:
1. Navigate to voice.allizom.org
2. Click Contribute
3. Add a recording 
4. Click "Unable to speak right now?" link
5. Click "Submit clips"

Expected:
Some kind of confirmation / success message that the record upload worked

Actual:
User is switched to "Listen" section

**Comment by mikehenrty** [comment]
Yes, there should be the pop-up asking users if they want to keep, submit, or delete their existing recordings.

**Comment by viorelaioia** [comment]
It shows the pop-up, but after the user selects to upload the recordings, there is no confirmation that the upload was successful.

**Comment by mikehenrty** [comment]
ah, I see. @m-branson, do you have thoughts on feedback for when a user submits clips via the "Are you sure?" popup?

**Comment by Gregoor** [comment]
Some extra info: We moved that process to the background, so if we were to show something it should be a global progress bar and/or a toast, so that users don;t have to wait.

**Comment by m-branson** [comment]
Thanks for the flag @viorelaioia -- @mikehenrty & @Gregoor this is something we've been tracking via pivotal and well, lost track of. 😬 (yay for getting everything over to github next sprint!).

Here was my initial request there:

>When clips are uploaded in the background (after user clicks submit) it takes ~1.5-3 seconds to complete. How can we visualize this progress to the user in a way that does not block them from continuing to contribute?
>
>Initial thought is a top of viewport, global progress bar with a toast message of "Clips successfully submitted!"

@Gregoor possible to get this implemented? Would be great for release, but ultimately could be a P1.

**Comment by Gregoor** [comment]
I just added a global upload progress indicator. RE the toast, should it look like the dark tooltip? And where would we want to position it?

**Comment by m-branson** [comment]
Thanks @Gregoor, loader is looking good. Can it be a bit darker in color, appreciate the gradient though. :)

Re: toast; I'm changing my mind re style and realize we actually have a toast already (see below):
<img width="269" alt="screen shot 2018-06-27 at 12 45 30 pm" src="https://user-images.githubusercontent.com/18686986/41995935-228991d8-7a08-11e8-8e96-a333900242ad.png">

Can we have the `5/5 clips uploaded` message (and share button) come in after the upload is successful? Seem counter intuitive to say they're uploaded before they are. 🤔

**Comment by Gregoor** [comment]
@m-branson the toast would imo need to be something that fits in with the rest of the page (e.g. outside of the contribution experience) as well, since the user could navigate anywhere while uploading.
So we could have that pill come in, though we should probably place it in a non-obstructive location, like bottom center? Also, do we want to use that pill style for the like copied (#1153) toast as well?

**Comment by m-branson** [comment]
Ah, yes great point(s)!

Okay, let's have the pill come in. I'm mildly concerned that black isn't the right color (blue may be more noticeable?) Top center with 60px of top padding seems best and shouldn't obstruct the contribution experience (desktop measurements).

And yes, this should be a global toast styling that can be applied to the link copied UI in #1153.

**Comment by Gregoor** [comment]
Also here: "Added it to staging, will wait for feedback before getting it onto prod and closing this issue."

Should it have the icon as well? If so, should all toasts have icons (e.g. link copied)?

**Comment by m-branson** [comment]
Thanks @Gregoor, feedback: utilize the green color as that denotes success across our UI. 

- [ ] Green pill background with white text
- [ ] Yes, the checkmark icon (white on the green background) for `Clips Uploaded` would be great
- [ ] Possible to add a fade in when it appears? Currently it's quite abrupt
