### ISSUE TITLE
[staging] High percentage for first time contribution

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1128]
After first 5 recordings contribution, I get the message "You've helped Common Voice reach 13% of its daily recording goal!" which seems a bit too high percentage for only 5 recordings.
How do you calculate the percentage shown when submitting recordings? I'm not sure what's expected behavior here.

**Comment by Gregoor** [comment]
The percentage is the total across users. So the calculcation is basically: `(all recordings so far today + your 5 recordings) / daily goal`. Maybe we should change the wording?

cc @m-branson @mikehenrty

**Comment by m-branson** [comment]
As this is on staging, I believe this is expected behavior based on how the calculation is done.

That said, for launch this will be the only place we're vocalizing that we have a daily goal; e.g. nowhere on the site does it say that our daily goal is 600 clips (as it will on the future homepage & user stats pages).

Is it possible to add that 600 clip info in to the messaging:

"You've helped Common Voice reach 3% of its `600 clip` daily [recording/validation] goal!"

cc @mikehenrty

**Comment by mikehenrty** [comment]
I would say remove the `clip` word

```
"You've helped Common Voice reach 3% of its 600 daily [recording/validation] goal!"
```

cc @Gregoor @m-branson

**Comment by m-branson** [comment]
If we remove `clip`, then I (as a users) want to know _600 of what?_

This reminds me, @flekkowich and I have an outstanding question re: clips vs. hours and how we're communicating them across the site. Will open a separate issue for discussion. :)

As this is how we currently communicate goals as a team, I would prefer to keep clip in the wording until we determine a different language direction.

cc @Gregoor

**Comment by mikehenrty** [comment]
> If we remove clip, then I (as a users) want to know 600 of what?

To me it's clear if we say `600 daily recordings` and `600 daily validations` what we are referring to. The text `600 clip daily recording goal` sounds awkward to me. I'd also suggest we use the word `our` vs. `it's`, as in `our recording goal`. Sounds less robotic.

But in the end, these are both nit picks, and the final say is yours @m-branson. If you say go with the original text, let's do get it in.

**Comment by m-branson** [comment]
`"You've helped Common Voice reach 3% of our 600 daily [recording/validation] goal!"`

Sold. Let's do this ^
