### ISSUE TITLE
local web app: recording works via localhost:9000, but not IP_ADDR:9000

### ISSUE THREAD

**Issue by zenogantner** [mozilla/voice-web#1131]
Hello, the web app works nicely when started with `docker-compose up`, just by going to http://localhost:9000 and recording. 127.0.0.1 (which is synonym) works okay as well.

However, when I use http://MY_IP_ADDR:9000/en/record (where MY_IP_ADDR is the IP address of my computer in the local network) from my computer, I can browse through the webapp, but when I click the "red button" on http://MY_IP_ADDR:9000/en/record, nothing happens -- recording does not start.

Any ideas how to fix this?

**Comment by zenogantner** [comment]
Is it correct to assume that the Docker method works *only* for local development?

**Comment by zenogantner** [comment]
[javascript console.txt](https://github.com/mozilla/voice-web/files/2123665/javascript.console.txt)

**Comment by mikehenrty** [comment]
@zenogantner do you see the permission dialog for microphone access when running through IP_ADDRESS? have you tried this in multiple browsers?

**Comment by zenogantner** [comment]
The reported problems were with Chromium.
With Firefox 60.0.2 it works.

**Comment by Gregoor** [comment]
Chrome doesn't allow getusermedia from untrusted sources, so that's
probably it. Maybe we should add a self signed cert to the docker setup?
