### ISSUE TITLE
Typos in Kyrgyz localisation

### ISSUE THREAD

**Issue by jonorthwash** [mozilla/voice-web#1148]
The text on the profile creation page for why a profile is needed currently reads as follows:
"Өзүнүз жөнүндө айрым маалыматтарды берүү менен, сиз «Common Voice»'го жүктөгөн аудио маалыматтар Ун таануу машиналарга бул маалыматтарды пайдаланууга жана алардын тактыгын жакшыртуу үчүн көбүрөөк пайдалуу болот."

There are a few typos.  The correct version should look more like this:
"Өзүңүз жөнүндө айрым маалыматтарды берүү менен, сиз «Common Voice»'ко жүктөгөн аудио маалыматтар үн таануу машиналарга бул маалыматтарды пайдаланууга жана алардын тактыгын жакшыртуу үчүн көбүрөөк пайдалуу болот."

**Comment by mikehenrty** [comment]
@JRMeyer any thoughts here? should we get this into Pontoon?

**Comment by ftyers** [comment]
I've added this as a [suggestion](https://pontoon.mozilla.org/ky/common-voice/messages.ftl/?search=%D3%A8%D0%B7%D2%AF%D0%BD%D2%AF%D0%B7&string=175912) (they look like typos to me), @jonorthwash now someone on the Kyrgyz translation team just needs to approve it. If you want access to fix translations directly you can contact @JRMeyer.

**Comment by mikehenrty** [comment]
Thanks @ftyers, sounds like the fix is coming in. Thanks for the report @jonorthwash
