### ISSUE TITLE
Remove sox from nodes as ffmpeg not sox is now used

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/voice-web#115]

**Comment by kdavis-mozilla** [comment]
We can punt on this for now, as having sox installed but unused on the nodes is fine.

**Comment by gozer** [comment]
I'll get to it Monday. Keeping dependencies clean is a good practice, but absolutely not time critical!

**Comment by mikehenrty** [comment]
@gozer do we still need this bug?
