### ISSUE TITLE
local web app: play/yes/no is always grayed out for verification

### ISSUE THREAD

**Issue by zenogantner** [mozilla/voice-web#1152]
I start the web app with `docker-compose up`.

Recording works (see #1131), but under both Chromium and Firefox I cannot verify sentences.
Having made recordings from different browsers, I would expect that to work.

I can also verify that there are several user directories with recordings:
`docker exec ${CONTAINER_ID} ls /data/common-voice-corpus/`

![grayed-out](https://user-images.githubusercontent.com/83638/41919572-1e1009b0-795f-11e8-8c64-fe85621f6927.png)

**Comment by mbransn** [comment]
Closing as this relates to out of date homepage experience.
