### ISSUE TITLE
[staging] Social overlay updates

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1154]
- `h1` needs to be visually centered in the space between the image and the social icons.
- Remove `<b>` tag from `Help us`
- `class="share-button"` appears to be sitting low within the pill background. When experimenting I increased bottom padding to 22px and this appeared to visually center.

<img width="1054" alt="social-overlay" src="https://user-images.githubusercontent.com/18686986/41928898-855e34a4-792b-11e8-9c1a-c86a77baa762.png">

**Comment by ftyers** [comment]
@m-branson would it be possible to add a VK link ? Documentation here: https://vk.com/dev/widget_share .. This would be particularly useful for languages in Russia.

**Comment by mikehenrty** [comment]
@ftyers can you file a separate bug for that? let's use this bug just to discuss the display issues for the overlay

**Comment by ftyers** [comment]
@mikehenrty oops, yeah, that's a good idea, sorry for the issue noise! :)

**Comment by MichaelKohler** [comment]
I don't think this popup is still a thing, but please feel free to reopen if I missed it.
