### ISSUE TITLE
[staging] Blue square to be removed

### ISSUE THREAD

**Issue by georai** [mozilla/voice-web#1155]
We need to remove the blue square : https://www.dropbox.com/s/4h5x44sm1raubs0/0r0a1u0p.png?raw=1
@m-branson @Gregoor

**Comment by m-branson** [comment]
@Gregoor is this an accessibility focused state? If so, we'll need to keep it in some capacity. Possible to make a 'circle'?

**Comment by Gregoor** [comment]
Yes, this is an accessibility thing. I found a solution which should stop these kinds of visual issues from popping up, while still having that indicator when using a keyboard.
