### ISSUE TITLE
[staging] Implement banner re: new contribution experience for launch

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#1158]
@Gregoor @mikehenrty just before all hands we got a banner design done to be displayed on the homepage; goal being to help drive bug reporting & use of the new experience.

https://zpl.io/2y7QKnK

Possible to get this implemented with launch? Does not block release, but should be prioritized. :)

**Comment by m-branson** [comment]
Also, food for thought on scroll functionality: check out the latest banner update on [mozilla.org](https://www.mozilla.org/en-US/). Appreciate that on scroll it sticks and provides an 'x' to dismiss.

**Comment by Gregoor** [comment]
@m-branson sticky sounds good 👍 Where should we position it?

**Comment by Gregoor** [comment]
@m-branson unfortunately with the way the homepage was built putting it over the wall of text and pushing everything down is anything but easy. So the simpler options would be:
- putting it over the text (making it closeable, so that people could still read the text)
- putting it under the text, over the listen widget

**Comment by Gregoor** [comment]
It's in on desktop. On mobile the homepage is unfortunately that big of a mess that I think I'll have to move it over the content there (and make it closeable).

Also @georai can you make sure that the eye icon for the take-a-look is exportable on Zeplin? I couldn't export it just now.

**Comment by m-branson** [comment]
@Gregoor on mobile let's layout this way:

![mobile-sketch](https://user-images.githubusercontent.com/18686986/42046522-f2805e26-7ab2-11e8-8232-412bde80e3f9.jpg)

...does this help alleviate the issue with pushing content down vs. going over it?

On desktop:
- can we make the `take a look` button visually center between the copy & the `help report bugs` button
- on hover `take a look` should be full white background
- make the banner text left align with the logo

![desktop-banner](https://user-images.githubusercontent.com/18686986/42047050-16f9a054-7ab4-11e8-8941-7436a4897e19.png)

**Comment by m-branson** [comment]
@Gregoor we also need the `x` on the desktop version. :)
