### ISSUE TITLE
[staging] Success screen percentage spacing issue

### ISSUE THREAD

**Issue by georai** [mozilla/voice-web#1161]
Finally I accomplished 20% but we need to add one more space to the % : https://www.dropbox.com/s/m3i4pipxwwmcir2/owe7muli.png?raw=1

@Gregoor

**Comment by Gregoor** [comment]
strange, looks good to me on FF & Chrome. What device/browser were you on @georai?

![screenshot_2018-06-27 common voice by mozilla](https://user-images.githubusercontent.com/4051932/41962653-dcc5a8e2-79f5-11e8-8999-3564b9a607d3.png)

**Comment by georai** [comment]
@Gregoor I used Chrome to see this issue, on FF looks good.

**Comment by Gregoor** [comment]
@m-branson @mikehenrty @viorelaioia can someone reproduce? It looks right to me across browsers

**Comment by Gregoor** [comment]
Nevermind, I found the bug!
