### ISSUE TITLE
[staging] Remove or keep validation on homepage for new contribution launch?

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#1163]
@mikehenrty @Gregoor for release, will we be removing validation from the homepage or leaving until new homepage goes up?

From a metric perspective, I believe it would be very useful to understand where validation are coming from. e.g. if we're leaving the homepage component for now, are we set up to accurately measure validation contribution in the portal vs. the homepage?

**Comment by Gregoor** [comment]
I think it makes sense to remove it. Let's go all-in with the new experience.

**Comment by mikehenrty** [comment]
I don't think we should remove it until we have the new homepage. This homepage widget has been a big part of the explanation about this project for new users, and gives them an easy way to see what this project is about. I am quite sure the listen numbers will go down and the overall experience will suffer if we remove it.

That said, we definitely should track these events differently. @Gregoor can you add a label to the listen event to track where it's coming from?

**Comment by Gregoor** [comment]
👍 on it

**Comment by m-branson** [comment]
Great, thanks for the thoughts there @mikehenrty. I agree that it's a solid explanatory feature for the current experience. We're aligned.
