### ISSUE TITLE
Validate user before allowing Votes

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#1169]
Since we use clip ids in the vote url (ex. `https://voice.mozilla.org/api/v1/en/clips/17349215/votes`), it's possible for a bad actor to enumerate those and send a bunch of invalid votes. Let's validate that the client_id of the request exists before accepting the vote.

**Comment by Gregoor** [comment]
Another idea for minimizing vote forgery:
Encrypt the clip IDs with a secret key, only the server knows. Should probably also contain the requesting user's ID, so it can't be reused. That would practically kill vote through enumeration as well.
