### ISSUE TITLE
Add social overlay button for VK

### ISSUE THREAD

**Issue by ftyers** [mozilla/voice-web#1170]
Would it be possible to add a [VK](https://en.wikipedia.org/wiki/VKontakte) link to the social overlay sharing thing? Documentation here: https://vk.com/dev/widget_share .. This would be particularly useful for languages in Russia where VK is the most popular site.

**Comment by mikehenrty** [comment]
@m-branson, i think this can be rephrased as a more general question: should we add region specific social sharing buttons to certain locales where platforms besides the twitter/facebook are popular?

**Comment by jonorthwash** [comment]
Isn't it the case that region-specific social sharing buttons are already being used?  Case in point: facebook.

**Comment by MichaelKohler** [comment]
I don't think this popup is still a thing, but please feel free to reopen if I missed it.
