### ISSUE TITLE
`goal-type-record` and `goal-type-validation` are used in different contexts

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/voice-web#1174]
I think we need new strings for the {$goalType} values in `toward-goal` and `goal-help-specific`. Right now they are both replaced with the same strings, and while it works in English, it’s almost impossible to get something working in other languages.

I think if you duplicate `goal-type-record` and `goal-type-validation` to use them only in one string, this should make things much easier.

Adding a localization note to `goal-help-specific` and `toward-goal` would be great too, explaining the possible values for each variable

**Comment by Gregoor** [comment]
I'm with you on adding more comments, but I need a bit more help understanding why it doesn't work in other languages (in the few romanic languages I know, it does work).

**Comment by TheoChevalier** [comment]
Thanks @Gregoor !
Let me take French as an example, it may be easier to explain. The TL;DR version is that I need to add different prepositions before `records` and `validations` in one case, and drop them in the other.

toward-goal=C’est <goalPercentage></goalPercentage> de l’objectif |d’enregistrements| quotidien de Common Voice. Merci
toward-goal=C’est <goalPercentage></goalPercentage> de l’objectif |de validations| quotidien de Common Voice. Merci

goal-help-specific=Grâce à vous, Common Voice a atteint <goalPercentage></goalPercentage> de son objectif quotidien de { $goalType } |enregistrements| !
goal-help-specific=Grâce à vous, Common Voice a atteint <goalPercentage></goalPercentage> de son objectif quotidien de { $goalType } |validations| !


Let me know if it’s not clear, it’s not super easy to explain

**Comment by mikehenrty** [comment]
> I think if you duplicate goal-type-record and goal-type-validation to use them only in one string, this should make things much easier.

@TheoChevalier thank you for reporting this! I believe I understand, but any chance you'd want to do a PR to show us what you mean?

**Comment by Gregoor** [comment]
Thanks for that example @TheoChevalier. That helped me understand it and I can see that many languages might have that problem. I'll create separate strings then!
