### ISSUE TITLE
Allow logged in users to disable contribution success screen & keep contributing

### ISSUE THREAD

**Issue by LucSalommez** [mozilla/voice-web#1179]
Hello, I really appreciate the new interface and especially being able to see the goals.

Nevertheless, having a special page after 5 validations and having to click on a button to keep validating is really annoying to me. I often validate hundreds of clips on the same contribution session and having this creates friction to me.

I would highly prefer a special page to see the current state of goals instead, so I can check whenever I want (I guess it is planned).
An other solution could be to display it only once when the user has finished to contribute.

I really appreciate the new design though, and the increased number of voice contributions we can do at the same time.

Keep the good job !
Luc.

**Comment by mikehenrty** [comment]
good feedback, flagging @m-branson

**Comment by m-branson** [comment]
Thanks @LucSalommez, we also heard this feedback at our All Hands mtg earlier this month. At the moment we are exploring an idea to provide some advanced options within a future `user settings/preferences` section. This could then be linked to the contribution success page & enabled logged in users to disable seeing it. 😊 I'm targeting our next sprint to update our wireframes with this approach & will link them here once I do!

And yes, we are indeed working on a personal 'stats' page where project goals, progress & personal level progress will be outlined in more detail.

>I really appreciate the new design though, and the increased number of voice contributions we can do at the same time.

Great to hear! Thank you for taking the time to contribute & feedback.

**Comment by LucSalommez** [comment]
I think it is a great thing to had `user settings/preferences` section !
Does it imply you are working on an account system with logging ?

I think that would be a good improvement as it is now stored in cookies and is not consistent across multiple computers.

I have seen your mockups and it seems like we will be able to compare ourselves with other contributors (which is really a good idea imo) so I guess you are planning to have accounts.

I think it still should be possible to contribute without having an account so one time contributors can contribute without having to create one.

Thanks for developing the project, I have been really interested in Common Voice since January and I appreciate your work.
Keep it up !

**Comment by mikehenrty** [comment]
> I think it still should be possible to contribute without having an account so one time contributors can contribute without having to create one.

Absolutely, we will always have a way to anonymously contribute voice data.

**Comment by makmanalp** [comment]
To add to this, it breaks the keyboard workflow when you're using the keyboard shortcuts (which is perhaps a thing you want to preserve even for anonymous users): "you helped us reach out x% goal" locks you out of any keyboard action and you have to move your hands off the keyboard and to the mouse to continue. Perhaps pressing any key to get rid of the dialog could work OK. 

Source: https://news.ycombinator.com/item?id=17438466

**Comment by m-branson** [comment]
>To add to this, it breaks the keyboard workflow when you're using the keyboard shortcuts (which is perhaps a thing you want to preserve even for anonymous users): "you helped us reach out x% goal" locks you out of any keyboard action and you have to move your hands off the keyboard and to the mouse to continue. Perhaps pressing any key to get rid of the dialog could work OK.

@makmanalp see @Gregoor's response from above:

>To get around this specific issue for now, I smuggled in a shortcut: You can press enter to continue recording/validating.

@Gregoor it's a great smuggle. 😊 Let me think on how to better display this shortcut on this screen.

**Comment by makmanalp** [comment]
@m-branson whoops, looks like I missed that! Just wanted to make sure it didn't get lost in the mix. Thanks a lot for your great work!

**Comment by m-branson** [comment]
@makmanalp appreciate it, all the eyes are helpful! Thanks for the contributions. ❤️
