### ISSUE TITLE
[New Interface] Sentences too long need scrolling

### ISSUE THREAD

**Issue by LucSalommez** [mozilla/voice-web#1180]
Hi, while contributing voice I have encountered a long sentence that couldn't fit inside the white rectangle.

I thus had to scroll to be able the read the sentence completely. This creates friction but the most important thing is that I had no clue I had to scroll until I used the 'play' button on the right to check if I spelled the sentence right, and found the displayed sentence was longer.

I am using a small laptop screen, maybe it is linked to that.
I suggest to change the size of the characters when the sentence is too long so it can fit in the rectangle.
An other solution could be to display an information to inform the user he has to scroll, otherwise people could contribute invalid sentences without even knowing it.

**Comment by mikehenrty** [comment]
great! flaggin @m-branson :)

**Comment by mikehenrty** [comment]
@LucSalommez can you provide us a screenshot when you see that again? it might also be that we have a sentence that is too long and we need to remove it

**Comment by mikehenrty** [comment]
Screenshot from @webstrand:

![screenie](https://user-images.githubusercontent.com/635365/42209910-28de21e6-7eb0-11e8-8480-8be35352e6c7.png)


> The full prompt should be, "Everyone else is smarter than me, and there's only 12 positions across the whole uni."

**Comment by MichaelKohler** [comment]
This is fixed
