### ISSUE TITLE
[New Interface] Uploading stuck leading to lose all records

### ISSUE THREAD

**Issue by LucSalommez** [mozilla/voice-web#1182]
I have encountered the same bug 3 times in the past 20 minutes while contributing voice : 
When I click to send the 5 records, I get on the page telling me about the current daily goal.

On the top of the screen there is a progression bar filling while the records are sent. Sometimes the record bar get stuck, and when I keep contributing even though I get not warning about upload issues, the daily goal stops progressing and the bar still stays at the same level.

To stop being stuck, I then have to reload the page after getting a browser warning about being about to 'loose the unsaved changes' (the locally stored records I guess).

At one moment I was keeping doing records for about 40 records before seeing it and it was quite frustrated to be forced to refresh and loose them.

I used to have upload issues with the old system but then I was asked if I wanted to retry the upload which was enough to keep going.
For now with the new system I even have troubles to see when there are upload issues because I pretty much try to be as effective as possible when recording (still checking for quality every time) and directly click to start a new round when getting on that page.

I think it's the same upload issue as before the new interface, but it still could be linked to the fact that I fastly click on the button to keep going so the records don't get the time to be uploaded.

**Comment by Gregoor** [comment]
Hi @LucSalommez, I'm very sorry for that frustrating experience. It sounds like your connection is unstable and the new experience doesn't handle that properly (while the old one at least had a retry option). I'll get on this right away, I hope you're willing to test if it got better after I got a patch in.
Thanks for reporting this in detail!

**Comment by Gregoor** [comment]
@LucSalommez I made those changes, now when an upload fails it retries 3 times and after that asks you if you want it to continue. I hope this fixes the problems you've been experiencing. Let me know if not!

**Comment by mikehenrty** [comment]
Let's close this for now, and if it resurfaces @LucSalommez we can re-open. Thanks for the report!
