### ISSUE TITLE
[validation] Explore showing 'time left of clip' as a reverse loader across card top or bottom

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1183]
@Gregoor @mikehenrty when validating, I often want to click yes or no before the clip has fully ended. Eg; the speaker is done speaking but the clip playback is not concluded.

Hypothesis: if I were able to visualize the 'time left of clip' I wouldn't be frustrated when the yes/no buttons didn't respond to my pre-clip termination clicks.

Proposal: Create a visual loader across the clip card bottom (or top) to help visualize how much time is left of the clip itself.

**Comment by LucSalommez** [comment]
Even though it would improve the situation to be able to see the remaining time, I would suggest an alternative.

Actually the `yes` button becomes clickable only after the end of the clip. On 95% of the clips I have to validate, I try to click something like 0.3 second before the end of the clip and I agree it is frustrating.

What I propose is to enable the button something like 0.3 second before end of clip, this way we don't get frustrated and get some time to validate other clips. I guess it would also take less time to develop compared to having a visual tool.

0.3 second being a very short time, there shouldn't be surprise words in that interval that would invalid the clip.

Nevertheless, clips with a long ending silence still are frustrating even with this solution.

**Comment by mbransn** [comment]
Closing out as this is my own request and I'll track it elsewhere.
