### ISSUE TITLE
Kyrgyz localisation issue

### ISSUE THREAD

**Issue by jonorthwash** [mozilla/voice-web#1187]
The following localisation is perplexing in Kyrgyz:
![2018-06-30-02 38 09_001](https://user-images.githubusercontent.com/963849/42122365-c24e212c-7c0e-11e8-9ea6-fd888d9b2015.png)

It should begin something more like this:
"[icon] басып,"

**Comment by ftyers** [comment]
@JRMeyer could you take a look at this? --- @jonorthwash you could make the suggestion in [Pontoon](https://pontoon.mozilla.org/ky/common-voice/).  Here are the two relevant strings:

* https://pontoon.mozilla.org/ky/common-voice/messages.ftl/?search=%D0%91%D0%B0%D1%81%D1%83%D1%83&string=179065
* https://pontoon.mozilla.org/ky/common-voice/messages.ftl/?search=%D0%B0%D0%BD%D0%B4%D0%B0%D0%BD&string=179048

**Comment by jonorthwash** [comment]
Hmm it looks like it'll need a whole restructuring of `actionType`...

**Comment by jonorthwash** [comment]
Another localisation is the following:
![2018-07-01-15 03 35_001](https://user-images.githubusercontent.com/963849/42137739-f3ec0a46-7d3f-11e8-8406-5af3cf90d49a.png)

It should just say "үзүндү".  This probably requires a restructuring of how plurals work in the localisation system.

**Comment by mikehenrty** [comment]
Thanks for raising this @jonorthwash. Indeed, Pontoon is the correct place to deal with localization issues. Let's use that platform to track this work.
