### ISSUE TITLE
[Profile] Cannot change main language from Profile Form

### ISSUE THREAD

**Issue by MaxValue** [mozilla/voice-web#1192]
This is actually 2 bugs in one.
iOS version: 12 beta
App Version: 1.0.1

I filled in my profile when I opened the app for the first time. I selected german and austrian german as dialect.

When opening the app later again, the settings changed to English. My phone language is English, maybe that is the reason. But be aware that my native language is fluent German.
I was unable to correct this, the fields for the language options were grayed out and would not react  upon touch. The dialect was empty however and I tried to change this at least, which brought up a list of English dialects.

**Comment by MaxValue** [comment]
Oh just now! I opened the app again and i could change my profile language by clicking on the “participate in the german project” (Mitmachen) on the main page (which I actually did on the first launch of the app). This participating-again procedure did actually update the language in my profile back to like it was before (german with austrian german).

**Comment by mikehenrty** [comment]
hi @MaxValue, thanks for reporting this. You can change the language of the mobile app by clicking the settings menu (3 dots in the upper-right corner), and then choosing the language from the drop-down menu.

But you are correct, you cannot select the language from the profile form on the profile page. There are a couple of things we can do here:
1.) Make this not look like a drop-down, but instead just a disabled field
2.) Allow users to change the language from this drop-down
3.) Remove this field from the profile.

Any thoughts @m-branson ?

**Comment by MaxValue** [comment]
Well, when I "created" (the first time I filled it in and pressed "Save") my profile, I selected german and austrian-german as my language.
Apparently, this was resetted or ignored in some way, because on next launch english without any dialect was visible in my profile.

The actual bug I wanted to report here is that the profile preferences are not remembered and a non-english user has to go to Dots-Menu > Contribute > Click desired language *every time* they startup the app to use it, because it will just show english phrases on startup instead of phrases in the users language.

I have the hunch that the app uses the phones' system language to set the language preferences in the app instead of using the profile preferences. For users like me this is kinda frustrating.

**Comment by mikehenrty** [comment]
> The actual bug I wanted to report here is that the profile preferences are not remembered and a non-english user has to go to Dots-Menu > Contribute > Click desired language every time they startup the app to use it, because it will just show english phrases on startup instead of phrases in the users language.

Ah, got it! @stasm, during fluent's language negotiation, is there a way to have it remember the users last manual setting of the language (ignoring the browser defaults)? Or I guess this is something we need to do on our end?

cc @Gregoor

**Comment by stasm** [comment]
Right, it's best to do it on your end. Fluent tries to be agnostic about how you store user's preferences. Common Voice might already be using some sort of persistent storage; it might be best/easiest to use the same approach for storing the language preference. 

I'm interested in documenting good practices around using `fluent-react`. This is a frequently needed feature which `fluent-react` doesn't provide out of the box. I'll follow this issue and I'll put together a bit of documentation about the solution.

**Comment by m-branson** [comment]
>But you are correct, you cannot select the language from the profile form on the profile page. There are a couple of things we can do here:
1.) Make this not look like a drop-down, but instead just a disabled field
2.) Allow users to change the language from this drop-down
3.) Remove this field from the profile.
>
>Any thoughts @m-branson ?

@mikehenrty @Gregoor I did not realize this was mapping this way -- Eg; localizing the site is fully overriding the profile language. This makes sense in retrospect, but yes, we need to improve the UI of the current form to better reflect this. I recommend*:

>2.) Allow users to change the language from this drop-down

...especially as localization dropdown on mobile has no screen real estate to be visible in the profile form. In effect, changing the language on the profile form will localize the site as well and be immediately reflected for users via their form.

*Note: this should be considered a short-term solve. The upcoming profile updates should alleviate the need for this and I do ultimately hope we can decouple the localization of the site from the profile form. This will in effect allow site localization to live separate from languages associated with a profile (which may be many) and truly enhance the UX based on user need.

**Comment by Gregoor** [comment]
The new profile experience addresses this. 🎉
