### ISSUE TITLE
incorrectly segmented Kyrgyz sentence

### ISSUE THREAD

**Issue by jonorthwash** [mozilla/voice-web#1194]
A Kyrgyz "sentence" presented to me was "Мен ага Мен акча берем."  This is not correctly segmented. 
 There's probably another sentence or two after this and then a деп and a main verb.  I.e., the second part of this "sentence" is embedded speech, and the first part is the subject and indirect object; the remainder of the non-embedded sentence is missing.

**Comment by jonorthwash** [comment]
Note that I recorded the sentence anyway and added дедим after it to make it grammatical.  But my recording (and the sentence) should probably be removed.

**Comment by mikehenrty** [comment]
@JRMeyer @ftyers  any thoughts here?

**Comment by JRMeyer** [comment]
@jonorthwash The segmentation was automated (not by hand), and this must have been split on punctuation incorrectly. Adding in extra words should be rejected, even if it makes the sentence more grammatical. The best case would be to remove sentences like this instead of trying to fix them.

@mikehenrty is there a way to identify and remove problem sentences like this?

**Comment by mikehenrty** [comment]
@JRMeyer yes, reviewing deleting them by hand :) 

In the past for English I have written some tools (for instance, [this](https://github.com/Common-Voice/text-tools/blob/master/process.js#L44)) to figure out a good split, but there is nothing that works in every case, and I don't have any expertise outside of English.

I think the best bet is to read over the sentences and delete the bad ones. I know that takes time though.

**Comment by JRMeyer** [comment]
@mikehenrty got it! I'll delete the problem sentences manually. Going over all of them by hand doesn't seem feasible, though, especially as the number grows. I should think that they will get thrown out by reviewers if they're incorrectly pronounced. If they're correctly pronounced, even if the sentence is grammatically strange / incorrect, for acoustic modeling it won't pose a problem.

**Comment by Gregoor** [comment]
This seems resolved, lmk if I should reopen
