### ISSUE TITLE
new interface grievances

### ISSUE THREAD

**Issue by jonorthwash** [mozilla/voice-web#1195]
I have some dislikes about the new interface:

- You have to record 5 sentences at a time, so if you screw up or there's an incorrectly segmented sentence (e.g., #1194) as the last sentence, then you can lose twice as much work as before with 3 sentences.  It no longer feels like a "short and quick" contribution—it feels much more involved, and more like I need to set specific time aside for it.

- There's no longer any indication of the total number of sentences that have been submitted for a language.

- The "listen" section seems broken (edit: now #1199):

![2018-07-01-15 00 04_001](https://user-images.githubusercontent.com/963849/42137711-7a978e36-7d3f-11e8-9e0c-150d79fedcdd.png)

- There are a number of font issues (#1141)

- The sentence is left-aligned instead of center aligned (with the record button):
![2018-07-01-15 01 55_001](https://user-images.githubusercontent.com/963849/42137728-bd8794e8-7d3f-11e8-9d3a-52aa9e57bf16.png)

**Comment by ftyers** [comment]
Regarding the "Listen" section, see #1199... This happens when you've listened to all the clips that have been recorded.

**Comment by mikehenrty** [comment]
> * You have to record 5 sentences at a time, so if you screw up or there's an incorrectly segmented sentence (e.g., #1194) as the last sentence, then you can lose twice as much work as before with 3 sentences. It no longer feels like a "short and quick" contribution—it feels much more involved, and more like I need to set specific time aside for it.

Thanks for the feedback. What do you mean `lose work`? Did you know you can re-record or skip sentences?

As for this being 'more involved` than before, we're experimenting with that number. We hope to land on the right amount soon.

> * There's no longer any indication of the total number of sentences that have been submitted for a language.

Was there an indicator for this before? I don't think there was. But to note, we have in the progress some pages that will tell you these numbers.

**Comment by mikehenrty** [comment]
cc @m-branson

**Comment by jonorthwash** [comment]
> What do you mean `lose work`? Did you know you can re-record or skip sentences?

I have in mind the scenario that happened to me: you record 4 sentences normally, and then get to one that's unrecordable. Without a skip function you're stuck: you must either record something or reset the page and start over.  That said, I wasn't aware of the skip function.  How do I use it?

**Comment by jonorthwash** [comment]
> Was there an indicator for this before?

Yes, there was an indicator at the top of the page with the number in red, followed by a 0 in black iirc.

**Comment by ftyers** [comment]
@jonorthwash are you referring to the numbers here?

![captura de 2018-07-03 09-22-23](https://user-images.githubusercontent.com/449545/42204689-a6deaede-7ea2-11e8-8ea7-0ce87aa764d8.png)

**Comment by mikehenrty** [comment]
>  That said, I wasn't aware of the skip function. How do I use it?

The skip button is in the lower right hand corner by the submit button.
![screenshot_2018-07-03 common voice by mozilla](https://user-images.githubusercontent.com/635365/42216152-29083c5e-7ec1-11e8-9c83-d1a899eb9ee7.png)

**Comment by jonorthwash** [comment]
@ftyers, yes, those numbers!

@mikehenrty, aha, thanks!

**Comment by jonorthwash** [comment]
@mikehenrty, you'll notice in one of my earlier screenshots in this post that the skip button is missing the ">>" icon.  That likely has to do with how I missed it.

**Comment by Gregoor** [comment]
The skip button should have the icon on all browsers now! And since the rest of the issues listed here are tracked in other issues, I think we can close this (lmk if I'm wrong 🙃 ).

Thanks y'all!
