### ISSUE TITLE
Optionally save location in profile

### ISSUE THREAD

**Issue by josselex** [mozilla/voice-web#1197]
It would be good if people could also add their geographic location (or where they were born or where their dialect roots are located) to their profile.

With this data one could make better text-to-speech for a lot local dialects. This would be awesome for protecting small language differences.

**Comment by mikehenrty** [comment]
Great suggestion @josselex. Indeed, we are constantly examining how to better track `accent` for our users, and region where you grew up is one of the factors (as well as what school you went to). For now though, we are doing this through the accent lists given to us by linguistic experts. In the future, we may reconsider, and have a more granular approach. cc @m-branson @kdavis-mozilla

**Comment by nukeador** [comment]
We are going to open a conversation on discourse about accents in the coming days with a proposal.

Please, add your feedback there so we can have a unified approach for all languages

https://discourse.mozilla.org/c/voice

Thanks for your contributions!
