### ISSUE TITLE
Legal review of technical architecture separating voice data collection and user info

### ISSUE THREAD

**Issue by geroter** [mozilla/voice-web#12]
Dependant on draft of architecture in issue #13

**Comment by geroter** [comment]
Marshall to be involved with the review of this.

**Comment by mikehenrty** [comment]
I think we'll have a better understanding of the architecture after sprint 1, so I am updating the milestone to 2.

**Comment by mikehenrty** [comment]
[Proposed architecture](https://docs.google.com/drawings/d/12FasUel5NH6poKLcJaxlYr64U6N6YEsyNs-wZJx_y04/edit) sent over to legal for review.

**Comment by mikehenrty** [comment]
No show stoppers raised from legal. Closing.
