### ISSUE TITLE
Turkish accents

### ISSUE THREAD

**Issue by erkinalp** [mozilla/voice-web#1200]
Add major accents with Karahan classifications:
İstanbul _standard dialect_ 
Ankara (rural) - 3.8 - Central Anatolian accent _"Orta Anadolu ağzı"_
İzmir (urban) - 3.1 - _İzmir accent_
Aydın - 3.1.3 - Aegean accent _"Ege ağzı"_
Trabzon - 2.1.2 - Caucasus-Eastern Black Sea accent - _"Doğu Karadeniz-Kafkas ağzı"_
Diyarbakır - 1.1.4 - Southeastern anatolian dialect - _"Güneydoğu Anadolu ağzı"_
Cyprus (Nicosia) - _"Kıbrısça"_

**Comment by mikehenrty** [comment]
@erkinalp where did this list come from?

**Comment by erkinalp** [comment]
Native speaker of Turkish. These accents are all easily distinguishable.

**Comment by makmanalp** [comment]
As a sidenote, Turk Dil Kurumu is the official Turkish Language Institution (https://en.wikipedia.org/wiki/Turkish_Language_Association)

**Comment by nukeador** [comment]
We are going to open a conversation on discourse about accents in the coming days with a proposal.

Please, add your feedback there so we can have a unified approach for all languages

https://discourse.mozilla.org/c/voice

Thanks for your contributions!

**Comment by nukeador** [comment]
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
