### ISSUE TITLE
Empty record page after reach 1000 records

### ISSUE THREAD

**Issue by irvin** [mozilla/voice-web#1205]
Reported by local contributor Shirley ( https://t.me/moztw_general/84516 )  

After reach 1000 records
<img width="334" alt="2018-07-02 11 47 09" src="https://user-images.githubusercontent.com/165936/42173785-bb838bfc-7e52-11e8-9aeb-d8e3bd0ffd2e.png">

The record page become empty. 
The verify page still work, and also still work under Chrome private browsing.

<img src="https://user-images.githubusercontent.com/165936/42173867-0772bd4e-7e53-11e8-801c-7df2b262244f.jpg" alt="photo_2018-07-02_23-42-47">

**Comment by irvin** [comment]
![photo_2018-07-02_23-42-47](https://user-images.githubusercontent.com/165936/42173867-0772bd4e-7e53-11e8-801c-7df2b262244f.jpg)

**Comment by mikehenrty** [comment]
thanks for the report @irvin. does reloading the site help? are there any errors in the javascript console?

**Comment by irvin** [comment]
@mikehenrty the user report it return normally today.
