### ISSUE TITLE
Add a example dataset to /data

### ISSUE THREAD

**Issue by irvin** [mozilla/voice-web#1206]
Some people is just curious about how the data looks like (like me), and perhaps no need for a full 12G dataset. 
We can add an example dataset like 100MB, and save much bandwidth (and money as #833) on both sides.

**Comment by Gregoor** [comment]
We'll have a new datasets page soon which'll also include smaller languages.

**Comment by Gregoor** [comment]
Here it is: https://voice.mozilla.org/datasets
