### ISSUE TITLE
Weird sentences.

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voice-web#121]
Jofish reported this:

![pasted image at 2017_06_16 04_47 pm](https://user-images.githubusercontent.com/973388/27248095-f0c13236-52b3-11e7-8b3e-bc9ca5e5962f.png)

**Comment by kdavis-mozilla** [comment]
Closed with 0f049ff

**Comment by mikehenrty** [comment]
Well, those aren't the only "weird" sentences, for instance (https://github.com/mozilla/voice-web/blob/master/server/data/temporary-sentences-2.txt#L865)

His landlady came to the door, loosely wrapped in dressing gown and shawl; her husband followed ejaculating.

If we are using text from material that is 50+ years old, I think we will need to verify each sentence before in goes into the database. Let's fix this in #23.
