### ISSUE TITLE
Pressing "No" on the last clip should stop the audio from playing

### ISSUE THREAD

**Issue by connorshea** [mozilla/voice-web#1217]
While validating clips, I ran into a clip which was just the word "F**ker" on loop with the bass boosted. When I pressed "No", I expected the audio to stop playing, but it continued until the clip ended. When the clip is malicious (admittedly a rare occurrence in my experience), this is pretty annoying.

It continued to play while on this screen:

<img width="1426" alt="screen shot 2018-07-03 at 12 08 23 pm" src="https://user-images.githubusercontent.com/2977353/42237072-f923fe80-7eb9-11e8-8ab4-e58c5fb71f23.png">

I'm not sure if this was because the clip happened to be the 5th clip in the set, or if this happens for all clips no matter what?

**Comment by mikehenrty** [comment]
I'm sorry you had to listen to that! @connorshea

**Comment by connorshea** [comment]
It didn't bug me much, I've seen worse :P Just wanted to make sure others don't have to deal with the same thing :)

**Comment by poush** [comment]
Similarly with the case of "Yes" as well.

**Comment by poush** [comment]
@Gregoor, Can I take this?

**Comment by Gregoor** [comment]
Of course :)
