### ISSUE TITLE
voice kabyle

### ISSUE THREAD

**Issue by aqvayli** [mozilla/voice-web#1219]

**Comment by mikehenrty** [comment]
@belkacem77 could you help us understand what this request is for?

**Comment by belkacem77** [comment]
@aqvayli please, don't send PR about the kabyle locale. I'm the alone responsible about the kab corpus. The team (academicians, authors, ...) is discussing the corpus on our FB page.

**Comment by lissyx** [comment]
@belkacem77 Could you share the link to this page ?

**Comment by belkacem77** [comment]
Hi @lissyx 
The kab localizers page: https://web.facebook.com/groups/165557820784383/?fref=nf
My Own profile: https://web.facebook.com/mouhouslimane.naithbelqacem
A general group where we are discussing general language: https://web.facebook.com/search/top/?q=tigejda%20n%20teqbaylit
A technical project about Kab NLP: https://gitlab.com/belkacem77/KabyleNLP
My own blog: https://taqbaylitassa.wordpress.com/

________

**Comment by aqvayli** [comment]
@belkacem77  
J'ai juste voulu tester!! désolé

**Comment by belkacem77** [comment]
@aqvayli 
thanks Farid.
Please, we have our tools to discuss about issues, corpora, localization.... the technical things should be shared with @S-Amiri  and me. Before sending them in Github!!!!!

**Comment by lissyx** [comment]
@belkacem77 Thanks, I can share the localizer group to people who might be interested in contributing then :)
