### ISSUE TITLE
Being asked to record the same sentence multiple times

### ISSUE THREAD

**Issue by LucSalommez** [mozilla/voice-web#1220]
Hi, in the old system it seemed like there was a protection to prevent a user to record himself on the same sentence multiple times, but with the new interface I have been asked multiple times to record a sentence I already did a few minutes before.

I think that can be problematic for the quality of the dataset as : 
- Multiple clips with the same voice on the same sentence can lead to overfit and brings less informations on how to pronounce than if it was recorded by someone else.
- I guess you collect X records for each sentence, which mean if I'm recorded 3 or 4 times on the same sentence, my voice will represent a higher percentage of that sentence recordings which leads to a lack diversity.

I wonder if being recorded multiple times on the same sentence is intended and if so I am curious to understand why.

Have a good day,
Luc.

**Comment by mikehenrty** [comment]
Hrmm, yeah we should have protections in place against this.

@Gregoor did we make any changes that would allow this to happen?

**Comment by LucSalommez** [comment]
Maybe it is linked to the other languages addition.
I've met this problem contributing for French language.

Oh I just remembered there is also a problem about duplicated sentences in the pool of sentences.
Maybe it was not the 'same' sentence for the database but it happened to be the same text as it was a duplicate.
Seems to be the most likely reason to me.

**Comment by mikehenrty** [comment]
> Maybe it was not the 'same' sentence for the database but it happened to be the same text as it was a duplicate.

If it's the exact same sentence, our system will detect that and only add one of them. But if they are even different by one letter, it will not.

**Comment by LucSalommez** [comment]
It seems duplicates exist in this file : 
voice-web/server/data/fr/ofis_publik_ar_brezhoneg.txt

Does the system verification happens after the storage of sentences or prior to it ?
Because if this file is the output of the system verification the issue could come from here.

**Comment by ftyers** [comment]
@mikehenrty no problem, but would it be possible to merge #1139 first ?

**Comment by mikehenrty** [comment]
@ftyers i don't mind, but i am not sure how long that one will take to be ready

**Comment by jf99** [comment]
This problem looks similar to #1067.

**Comment by Gregoor** [comment]
I don't see any recent changes that would cause it, so my intuition is also that it would be duplicate sentences in the corpus. Or sentences you already did were fixed and then you were served the corrected ones as well (as they have new IDs/we atm have no way to relate them to their incorrect versions)

**Comment by iveskins** [comment]
I have experienced multiple copies of the same speaking prompts also. I think the sentence api is sending the same thing multiple times.
![selection_024](https://user-images.githubusercontent.com/18106420/45922473-b492dc80-bf07-11e8-95a1-ee454a05cc7b.png)
![selection_023](https://user-images.githubusercontent.com/18106420/45922474-b492dc80-bf07-11e8-83a9-d7ac7788dfa4.png)

**Comment by Rots** [comment]
Still happened to me today on recording Estonian.

**Comment by Gregoor** [comment]
#2015 should've fixed it. Anybody still experiencing this?

**Comment by iveskins** [comment]
`for i in (seq 1 100); curl 'https://voice.mozilla.org/api/v1/en/sentences?count=10' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,ja;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36' -H 'Content-Type: application/json; charset=utf-8' -H 'Accept: */*' -H 'Referer: https://voice.mozilla.org/en/listen' -H 'If-None-Match: W/"-------------------gzip"' -H 'Connection: keep-alive' -H 'client_id: someID' --compressed |  jq > $i.vws.txt && sleep .5; end`

**Comment by iveskins** [comment]
I just tried this 
` for i in (seq 1 100); curl 'https://voice.mozilla.org/api/v1/en/sentences?count=10' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,ja;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36' -H 'Content-Type: application/json; charset=utf-8' -H 'Accept: */*' -H 'Referer: https://voice.mozilla.org/en/listen' -H 'If-None-Match: W/"-------gzip"' -H 'Connection: keep-alive' -H 'client_id: ----' --compressed | jq > $i.vws.txt && sleep .5; end`
(fish not bash sorry)

and then: 
```

ME@MyMac ~/voiceweb> cat *.txt | grep -e \"id\": | sort -n | uniq -c | wc -l
     435
ME@MyMac ~/voiceweb> cat *.txt | grep -e \"id\": | wc -l
    1000
ME@MyMac ~/voiceweb> cat *.txt | grep -e \"id\": | sort -n | uniq -d | head
    "id": "04a65766975450d101a3669c9b38ee50fc5727938dd4b8cb9fae3fe44b273fb1",
    "id": "04b1df5292b32880eb4de50c43cdbb021907b69d39acbee7f3a8d1d68102e123",
    "id": "04c731cd69712082aebf327a895d2f24bd5227994afeb83e51e0e3b9e82d4a3c",
    "id": "04d63416d1b72c938f4dd0861072ccc3ecccda07f92d20eaf67f48d1b377d694",
    "id": "04e595ce37bc0781a217d5b4cdca5611483bb006feb733632d2e29a8cb73a4ea",
    "id": "04ede5b5c587ff8d50485b217dbba13a9592d5bda95e24ff09f9d8cd6234bab9",
    "id": "04f5b2329fc852a62428ec63a3f216ed6b735cf2c4888ec53f0894c8cabb72d3",
    "id": "04f6a5f81bf506bab607b8b0d5bbd594c802f06b7325c4e2d050ed66a9462c34",
    "id": "04f8a4fdc59e0231f9f9adecf18ec31d95231a565d5c657035e60bae03a02082",
    "id": "05056b9ab56bb84e16faf5d17730f511d31d19c774cff4264525fbbde5228590",
ME@MyMac ~/voiceweb> cat *.txt | grep -e \"id\": | sort -n | uniq -c | head
   2     "id": "04a65766975450d101a3669c9b38ee50fc5727938dd4b8cb9fae3fe44b273fb1",
   2     "id": "04b1df5292b32880eb4de50c43cdbb021907b69d39acbee7f3a8d1d68102e123",
   2     "id": "04c731cd69712082aebf327a895d2f24bd5227994afeb83e51e0e3b9e82d4a3c",
   1     "id": "04cb5c76bd0c0263b3b64aee1404663d5f77271130b7c1b438149e7c8ab1db68",
   1     "id": "04ceefa36aaae27f73af6f491234b931db027b164941095e687b79de6cf61025",
   4     "id": "04d63416d1b72c938f4dd0861072ccc3ecccda07f92d20eaf67f48d1b377d694",
   1     "id": "04dcde2761cd5797dad9bed7e84bddb41cfa92400b85f30e41b4ad139f3e7645",
   1     "id": "04e41ca75373d71b68308a6c9a10cc542e1fca562b3554b0036a1e0b90b02cff",
   4     "id": "04e595ce37bc0781a217d5b4cdca5611483bb006feb733632d2e29a8cb73a4ea",
   2     "id": "04ede5b5c587ff8d50485b217dbba13a9592d5bda95e24ff09f9d8cd6234bab9",
ME@MyMac ~/voiceweb>
```
If you follow. so .. maybe there are still duplicates being returned if you just call the sentences api over and over.
I cant say I have seen it in the actual app because I haven't been using it recently.

**Comment by Gregoor** [comment]
Yeah you'd get multiples if the request doesn't include a client_id and also if you don't record clips for the given sentences (put differently, you'll get the same sentence multiple times until you record sth for it).

**Comment by iveskins** [comment]
Okay. did have a client ID in this test, i just deleted it in the comment. Obviously this doesn't test if the sentence repeats after submitting a recording. I wouldn't complain if this issue was closed.

**Comment by Gregoor** [comment]
Great, thanks for testing it :)
