### ISSUE TITLE
Redirect to other options of contributions when running out of sentences to speak

### ISSUE THREAD

**Issue by rotemdan** [mozilla/voice-web#1225]
After I record about 500-600 samples (English language) I start to get the same sentences over and over again (this happens earlier as well, but only occasionally). Clicking "Skip" may also show me a blank page at some point (and the number of sentences to record might be lower than 5). Eventually the "Speak" page permanently appears blank all the time. The only way to overcome this is to clear the cookies/local storage for the domain and create a new profile (possibly with a different `userId`).

I don't think there are any special errors in the browser console (I'm not sure though, there are a couple of `Content Security Policy` errors though).

(I'm using Firefox 61.0.1/Win10 64bit)

**Comment by rotemdan** [comment]
Here's a snapshot of my `localStorage` state for `voice.mozilla.org`, so you can try to replicate this yourself:

`
userdata: {"accents":{"en":"other"},"userId":"efbda901-6635-443c-b46c-174c173c2c0f","email":"m0pqncm0@gmail.com","username":"m0pqncm0","sendEmails":false,"accent":"other","age":"thirties","gender":"male","clips":0,"privacyAgreed":true,"hasDownloaded":false,"recordTally":526,"validateTally":0}
`

**Comment by Gregoor** [comment]
Hey, thanks for the detailed report and sorry for the problem. The localStorage dump is really helpful. My first intuition was that you landed in the dev or test bucket which both have only around 500 sentences in english atm. But you are in the train bucket which has around 4k active sentences, so that's a bit strange. I'll do some more investigating.

**Comment by Gregoor** [comment]
Ah no, from looking at your clips it seems like you're in the test bucket. which indeed only has 503 sentences. So for one we need more english sentences (kudos for hitting that number 🎉 ) and we also need a nicer view for people encountering this, similar to #989.

**Comment by rotemdan** [comment]
Thanks for the quick response. On an unrelated note: it may sound a bit surprising but I think even 4000 sentences might be too few for me! (I did more than a 1000 yesterday alone [I've reset the profile once]) :) (I think I'm having too much fun with this practicing my English accent 👍)

**Comment by Gregoor** [comment]
That's super awesome. I'll try to take the heavier usage more into account in the future. Nobody should see a blank screen!

**Comment by mikehenrty** [comment]
> On an unrelated note: it may sound a bit funny/surprising but I think even 4000 sentences might be too few for me! (I did more than a 1000 yesterday alone [I've reset the profile once]) :)

Holy cow! Thank you @rotemdan !

**Comment by connorshea** [comment]
Time to start contributing sentences I guess :P

**Comment by danielsjf** [comment]
Someone did some stuff in #902

**Comment by dabinat** [comment]
I am also getting the issue with a blank Speak page. But now that we have user profiles it's not as easy as trashing localStorage. All that does is log me out and then when I log back in again the problem reappears.

My record tally is at 601 so I guess I'm in the test bucket too. Perhaps users should be automatically transferred to a different bucket once they hit the limit?

**Comment by dabinat** [comment]
The sentence collector (currently being tested) should make adding sentences a lot easier, so hopefully this will be less of an issue once it goes live.

https://discourse.mozilla.org/t/sentence-collection-tool-development-topic/33390

**Comment by ynyrllw** [comment]
I'm getting the same issue with Welsh (465  speaking). Didn't know it was due to running out of sentences till I asked in the forums. I might attempt to contribute more sentences to welsh to help here.

**Comment by MichaelKohler** [comment]
As far as I know we'll go towards one recording per sentence. So I'm closing this, feel free to reopen if I'm wrong.
