### ISSUE TITLE
Display error message when browser does not support microphone. Prompt them to download FF or iOS app.

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/voice-web#123]

**Comment by mikehenrty** [comment]
@kdavis-mozilla Can you tell me more here? Do you mean, that recording won't work?

**Comment by kdavis-mozilla** [comment]
Just to let the mobile Safari users know that they should be using the iOS app and not the Safari browser as the browser will not be able to record.

**Comment by mikehenrty** [comment]
We need this for any browser that doesn't support mic, so I've updated the title here.

**Comment by mikehenrty** [comment]
fixed in https://github.com/mozilla/voice-web/commit/b60e187c58c15376443a57417cb6912796c453dd
