### ISSUE TITLE
Recording too resource hungry

### ISSUE THREAD

**Issue by jf99** [mozilla/voice-web#1230]
The recording page causes a very high CPU load, even if the user does not currently record anything (webpage just shows the sentence and waits for the user to click the record button). On a six year old machine with Core i5 @ 2,5 GHz, I could not manage to take a submittable recording. There was always too much noise and stuttering in the result because the computer could not manage to compress the audio data on-the-fly. With a newer computer, it works, but still it has a very high CPU load. Both computers run Arch Linux and the current version of Firefox.

**Comment by Gregoor** [comment]
Thanks for reporting this. Is it the same for the listen page? This is a good reminder for me to port the FPS check over from the old recording page. But I would also like to make the animation itself run smoother.

**Comment by belkacem77** [comment]
Didn't met this for now. I have a same processor  running Fx on windows with a dozen of tabs and among them Common Voice, and  some tools and : PyCharm, Visio , a Linux VM...
With 8GO RAM

![2018-07-09 13_56_40-gestionnaire des taches de windows](https://user-images.githubusercontent.com/7033740/42451774-189dfa2a-8380-11e8-92c3-4885504870ca.jpg)

**Comment by Gregoor** [comment]
I just put the FPS check and fallback to no animation back in. Might be a bit longer until I revisit the animation myself. If anyone feels like looking at it, I'm happy to review PRs for this (I'm happy in general when reviewing PRs 😁 ).

**Comment by jf99** [comment]
Sorry, false alarm. Although the CPU load is high, it turned out not to be the reason for the distorted recordings. I just oversteered my mic in the computer's audio settings, because I used another mic recently.
