### ISSUE TITLE
Submit button covers reviewing on mobile

### ISSUE THREAD

**Issue by ftyers** [mozilla/voice-web#1231]
From @mansayk:

![review-1](https://user-images.githubusercontent.com/449545/42451683-45035ca6-8388-11e8-83a0-d56d89395c49.png)

Ideally the submit button shouldn't be able to float over the review table thing.

Here are the browser details:

![review-2](https://user-images.githubusercontent.com/449545/42451691-4b4e3d06-8388-11e8-8244-50bbfe0dbf75.png)

**Comment by ftyers** [comment]
Here is another example, the last two recordings were covered, then the user tried to click on the button [↑] to try and  get out of the window  and ended up in this situation. Also, the [↑] button doesn't have any alt text.

![error-2](https://user-images.githubusercontent.com/449545/42466673-d9de8888-83af-11e8-9bff-1948031f4973.png)

**Comment by ftyers** [comment]
@Gregoor 

Can you reopen this? It has improved compared to [this](https://github.com/mozilla/voice-web/issues/1231#issuecomment-403560469) but the 5th button is stlil covered over.

**Comment by Gregoor** [comment]
From what I can tell it looks good on small devices now, no?

**Comment by MichaelKohler** [comment]
This is good now, indeed.
