### ISSUE TITLE
Changing limit of validation batch

### ISSUE THREAD

**Issue by lissyx** [mozilla/voice-web#1233]
Right now, we validate sentences 5 by 5, and there's a menu asking if we want to continue after completing a batch of five. This is a bit inconvenient when we want to validate a lot:
 - either, having a way in the profile to change the batch size,
 - or, disable this feature
 - or, add a shortcut to continue

**Comment by lissyx** [comment]
![capture d ecran de 2018-07-09 17-47-43](https://user-images.githubusercontent.com/1645737/42461185-32dc3198-83a0-11e8-9e7d-e1807dc5623b.png)

**Comment by rotemdan** [comment]
I've found this to be a slow-down/annoyance for recording as well. Another issue is that the button animation prevents (or at least makes it unreliable) to click the button to record/validate another set instantly when the screen appears. It might also be nice to alternatively have an 'auto-continue' feature which simply continues to validate/record another set immediately without delay.

**Comment by est31** [comment]
There is a keybinding to skip the screen: https://github.com/mozilla/voice-web/issues/1179#issuecomment-401529321

**Comment by rotemdan** [comment]
@est31 Thanks. I didn't know about the shortcut. Though I guess some people will still try to click the button (several times if needed) and the lack of responsiveness might be seen as a UI issue.

**Comment by lissyx** [comment]
Thanks @est31, indeed Enter works, but it's not documented in the shortcuts :)

**Comment by zecakeh** [comment]
I must say I understand why this step is needed in recording, to send the data at every 5 sentences. But it's kinda useless and breaks the flow during validation.
