### ISSUE TITLE
icon for voice web

### ISSUE THREAD

**Issue by somratking420** [mozilla/voice-web#1234]
Hi @mozilla, I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by Gregoor** [comment]
Heya, thank you for your kind words and your interest. There's some previous thought on this in #465. I think having a logo would be great.

cc @m-branson

**Comment by somratking420** [comment]
Hello,@gregoor,
Good Day, i make a logo icon for your project.I make a 2 logo for you.Which logo do you like? If you want to use this logo in your project, then comment below, I will give you the source file.
![voice](https://user-images.githubusercontent.com/40878798/42555131-0d477c66-8509-11e8-9a22-bada7f0268af.png)

**Comment by mikehenrty** [comment]
let's close this one in favor of 465, as that one has some discussion. @somratking420 , i'll re-post your image there.
