### ISSUE TITLE
On mobile Chrome for Android: blank screen after recording

### ISSUE THREAD

**Issue by ftyers** [mozilla/voice-web#1235]
After a user records something on their phone, they get a blank screen, they are not able to continue recording.

Here is the browser information:

![error-1](https://user-images.githubusercontent.com/449545/42466603-aa731a82-83af-11e8-9778-3babf196fcf1.png)

**Comment by mikehenrty** [comment]
@ftyers does this happen every time for you?

**Comment by ftyers** [comment]
Yes, we tried it with the same user 5 times in a row, each time it let her record one sentence, but when she tried to pass onto the next one she just got a blank screen (and it stopped loading).

**Comment by ftyers** [comment]
@mikehenrty @Gregoor ... it also works fine on my Android phone with Firefox 61.0

**Comment by mikehenrty** [comment]
Can anyone else reproduce?

**Comment by Basemindgirl** [comment]
well, what were you talking about. There is a program that gets what ever is on the phone of. Data recovery with a mac into a dead android. This has happened a few times . I think its caled the black scren of death. Use disk drilll . Where you talking about the mind or have a partner who aint write or i guess the phone and computer companies can black your screen. The phone stays on for months with a black screen. I went through about 15. Hack your own phone can get you the answer
