### ISSUE TITLE
Validations statistics when using keyboard shortcuts

### ISSUE THREAD

**Issue by lissyx** [mozilla/voice-web#1238]
Looking at the analytics, I only see 97 validations for july 9th, while I did at least 500. Are keyboard shortcuts properly ingested by analytics ?

**Comment by Gregoor** [comment]
Can you specify what you mean with analytics?
And yes, keyboard shortcuts should be counted just as much as clicks. But I'll investigate as soon as I have a clearer idea of what the problem is.

**Comment by lissyx** [comment]
@Gregoor Google Analytics

**Comment by lissyx** [comment]
Okay, I'm guessing it's just my fault, since I have Do Not Track enabled. I just had a look at the console, and I see `do not track header set, disabling analytics`.
