### ISSUE TITLE
Listening for validation  works in prod but not in staging envornment

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/voice-web#124]
Generally the error is something like

> Media resource blob:https://voice.allizom.org/afb69438-e283-ea4d-9548-fb8ebcefedbe could not be decoded.

in Firefox and

> GET blob:https://voice.allizom.org/811e7028-7742-4d27-a986-ef874427eca7 416 (Requested Range Not Satisfiable)

in Chrome

**Comment by kdavis-mozilla** [comment]
@gozer Maybe you can shed light on why this is so.

**Comment by kdavis-mozilla** [comment]
@mikehenrty Any idea on this?

**Comment by mikehenrty** [comment]
@kdavis-mozilla perhaps staging doesn't have proper S3 creds?

**Comment by kdavis-mozilla** [comment]
@mikehenrty To be sure I'd have to see the error logs.

**Comment by gozer** [comment]
Stage and Prod are exactly the same.

Only difference is that staging bucket contains audio clips that have been put there that are much older in terms of code base.

I've seen mp3 with zero size in there when sox was having issues transcoding.

Could that be it ?

**Comment by kdavis-mozilla** [comment]
Could be. I just got one clip to play from stage, the first time that's happened. So it seems as if this hypothesis is a good guess.

**Comment by gozer** [comment]
You should both be able to access stage logs from the SSO Dashboard now

tag:voice.node.stdout

Will contain all output from the node processes
