### ISSUE TITLE
Buggy sentence

### ISSUE THREAD

**Issue by est31** [mozilla/voice-web#1240]
I've recently this sentence:

> Might others within your organisation have some inkling as to the their desires?

The word "the" seems out of place here. It should be removed I'd say.

**Comment by mikehenrty** [comment]
great catch @est31. any chance you'd want to submit a PR to fix it?

https://github.com/mozilla/voice-web/blob/61a0fbb7c217e78837db50055bc972de11b9e8bf/server/data/en/elleo.txt#L91

**Comment by est31** [comment]
@mikehenrty sure. Do you know how I can get my sentences from the not-used category into the used one?

**Comment by mikehenrty** [comment]
@est31, submit a PR and let's talk about it in that thread. let's keep this bug to talk about fixing the broken sentence you mentioned.
