### ISSUE TITLE
network analysis, sometimes over 10 audio clips

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1256]
Is it correct that the new contribution tool sometimes downloads 10 audio clips at a time? (for example on validating audio no. 4 with yes)

(sometimes, because I haven't seen a pattern, yet)

![firefox_2018-07-12_23-11-19](https://user-images.githubusercontent.com/5685512/42660092-633fc5ac-862a-11e8-9a09-a1cf2dbeb290.png)

**Comment by Gregoor** [comment]
Yes, we cache enough clips for two batches of validation to be done

**Comment by Djfe** [comment]
sounds good, but I think, I saw it happen twice per (one) batch.
(and it still loads the file once on it's own per sample
I'll check that again

**Comment by Gregoor** [comment]
Thanks for taking a close look, happy to reopen when you notice something's off 👍
