### ISSUE TITLE
Can’t see the recording page

### ISSUE THREAD

**Issue by aelcenganda** [mozilla/voice-web#1263]
When i use the app on iOS 11.3.1 in SE. I clicke to open the voice recording page but it is blank. The listening page works quite fine.

**Comment by mikehenrty** [comment]
For me, it's the opposite, Speak page works, Listen page is blank. I'm using English, what language are you using @aelcenganda ?

**Comment by aelcenganda** [comment]
languge: zh-tw
It's an occasionally bug. It works for a while and crashes sometimes.

**Comment by Gregoor** [comment]
Does this still happen?

**Comment by Gregoor** [comment]
Let me know if it does, and we'll reopen
