### ISSUE TITLE
[Staging] Language Page Search UI Updates

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#1266]
@Gregoor few updates to make, but overall looking good.

- [x] Increase h2 padding-right on language cards to 1rem (improves breaking to two-lines on wider viewports)

Current
![current](https://user-images.githubusercontent.com/18686986/42773264-9b3c713a-88e1-11e8-83b6-03f4364aa1d2.png)
Proposed
![proposed](https://user-images.githubusercontent.com/18686986/42773271-9d85115e-88e1-11e8-8d99-e19b68e80f6e.png)

-----

- [x] Search icon reduce to 16x16 size and increase padding-top by 2px

Current
![current-search](https://user-images.githubusercontent.com/18686986/42773383-e9395b96-88e1-11e8-8b54-31d36aff140b.png)
Proposed
![proposed-search png](https://user-images.githubusercontent.com/18686986/42773391-ed107c04-88e1-11e8-86f3-f952b902ec8b.png)

-----

- [x] Close icon reduce to 10x10 size and increase padding-top by 2px

Current
![closed-current](https://user-images.githubusercontent.com/18686986/42774545-d709594e-88e6-11e8-94f6-b22a430405fc.png)

Proposed
![closed-proposed](https://user-images.githubusercontent.com/18686986/42774564-e0a6220c-88e6-11e8-9a9a-73e524eaede3.png)

-----

- [x] Mobile: see images below, recommend dropping search field below languages labels and leaving expanded (as on desktop). This should leave more room for the count as you have it built (rather than breaking the labels to two lines). Also please replicate icon notes from above in the mobile field. :)

Current
![mobile-search-current](https://user-images.githubusercontent.com/18686986/42774570-e51b4f9c-88e6-11e8-9b32-f1bddf536b1f.png)

Proposed
![mobile-search-proposed](https://user-images.githubusercontent.com/18686986/42774577-e75306a6-88e6-11e8-8228-089e844373b9.png)

**Comment by Gregoor** [comment]
Thanks for that feedback, it was very actionable and nice to work through!

**Comment by m-branson** [comment]
Thanks @Gregoor, it was fun to set up. ;) There's only one thing I see amiss still: on mobile the search result numbers are still breaking the label UI. Perhaps these numbers need to get smaller across the experience? I'd be more than fine if they were ~50% the size on both desktop and mobile executions. Realize this may be tricky to accomplish though. Let me know thoughts. :)

<img width="362" alt="current-mobile-stage-labels" src="https://user-images.githubusercontent.com/18686986/42836328-97eea6f0-89af-11e8-8635-40391619dca2.png">

**Comment by Gregoor** [comment]
Thanks for that flag. I decreased the size, though on an iPhone 5 it still breaks (on newer/larger models it looks fine).

**Comment by m-branson** [comment]
Thanks @Gregoor this is looking & working much better across viewports. Re: iphone 5, it's hard to account & support every viewport. One thought on this, perhaps we drop the count on screen sizes that width and below? Preference would be to degrade the UX intentionally & gracefully across smaller viewports rather than have it resort in a UX that is perceived as broken.
