### ISSUE TITLE
Skiping sentences

### ISSUE THREAD

**Issue by belkacem77** [mozilla/voice-web#1270]
When we skip a sentence, either for recoding or  listening, the system seems to suggest again and again the same skipped sentence. It's better to tag it and don't show it again for the same user (profile)

**Comment by valen214** [comment]
It's not the relating, and I do not want to open an issue, but it is pretty fun that I want to post this somewhere.

![image](https://user-images.githubusercontent.com/17940784/42967812-02d16626-8bd4-11e8-865c-4d38fb8a5491.png)
