### ISSUE TITLE
Switching from Speak to Listen on first time contribution doesn't upload my recordings

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1274]
STR:
1. Navigate to voice.mozilla.org to have your first contribution (or open in private window)
2. Click Contribute
3. Record 1-2 sentences
4. Click "Unable to speak right now?" link
5. Click "Submit clips"

Expected:
Progress bar is displayed, recordings submitted are counted

Actual:
Progress bar is not displayed, number of recordings submitted is 0 (on Homepage)

Reproducible on Windows 10, latest Chrome and Firefox. 
Issue is happening in both stage and prod.

**Comment by Gregoor** [comment]
Thank you, great catch! Problem was that privacy & terms weren't accepted yet. My quick fix was to show the privacy modal over the confirm modal which is a bit sub-optimal for two reasons: double modal and user has to click submit twice.
For now it beats not-uploading the clips and a better solution would require some rearchitecturing.
