### ISSUE TITLE
Manca le profilo - prime requesta de melioramento

### ISSUE THREAD

**Issue by Karm46** [mozilla/voice-web#1278]
Quando on comencia a laborar le profilo non es presentate al usator. Io non era secur que mi labor era ligate a mi profilo, solo post que tentava de lo modificar videva que le profilo active era illo mie.

**Comment by Gregoor** [comment]
@Mte90 can you help translate the problem? My italian is a bit rusty.

**Comment by Mte90** [comment]
This is interlingua and not italian but I know Carmelo.

**Comment by Gregoor** [comment]
Oh, I didn't even know that one. Thank you!

**Comment by Karm46** [comment]
When a user begins to work, the user does not clearly see his profile. So I was not sure that my voice recordings were related to my profile.

**Comment by Gregoor** [comment]
We'll have a new profile experience very soon, which'll hopefully make a user's contribution more clear.

**Comment by mikehenrty** [comment]
Thanks for the feedback @Karm46 ! Indeed we are changing how the "Profile" section works very soon, so the bug you mentioned should be fixed. If not though, let's re-open this issue.
