### ISSUE TITLE
Add note that current download is only English, and more languages are coming soon

### ISSUE THREAD

**Issue by luweishuang** [mozilla/voice-web#1279]
I want to download chinese dataset cellected by this tool but just find a effect way.  Is chinese dataset not available to our common people? I have downloaded 12G zip file and it only contains english data. Is it possible to download other language data from this project?

**Comment by Gregoor** [comment]
Hi, thanks for raising that issue. We don't (yet) have a continuous data publication mechanism. The dataset for download is indeed only english and from end of last year. We're starting to look into continuous publication now.

I just looked at the data download page and I think we should add information to the CV data download about the language contained (english) and when the data was bundled. Wdyt @mikehenrty @m-branson ?

**Comment by mikehenrty** [comment]
Seems like a good idea to me :+1:

**Comment by anzart** [comment]
🤞

**Comment by nicolaspanel** [comment]
Hi @Gregoor 
From https://voice.mozilla.org/fr/datasets it is now possible to download CV dataset 
However, it seems to be english-only. Is there a way to get `fr` data (recordings and associated transcriptions) ?
I tried https://s3.us-east-2.amazonaws.com/common-voice-data-download/cv-corpus-2019-01-08T19:40:23.120Z/fr.zip but transcriptions seems to be missing

**Comment by Gregoor** [comment]
Hi @nicolaspanel, we're working on finishing up the new release. It'll be on the site soonish and we'll announce that properly. For the beta data release (btw I removed the link, as we require people to get it through emailing us) you can get the transcripts from the discourse post (search the site for "clips.tsv").

**Comment by Gregoor** [comment]
Here it is: https://voice.mozilla.org/datasets
