### ISSUE TITLE
Make it easier to get up and running

### ISSUE THREAD

**Issue by est31** [mozilla/voice-web#1283]
In order to work on #336  I was trying out the steps laid out in [CONTRIBUTING.MD](https://github.com/mozilla/voice-web/blob/master/CONTRIBUTING.md) and while `docker-compose up` gave me a initially working website, I've gotten errors in two places. Each error made the site crash and rendered it inoperable, requiring me to restart the site manually, using `docker-compose up`.

The first error was of the kind

```
Error setting user bucket { Error: Column 'locale_id' cannot be null
```

I could fix it by enabling sentence import, by removing the // from [here](https://github.com/mozilla/voice-web/blob/4edc20649f73d2b90458adaeec82079bc0f276f7/server/src/server.ts#L192).

The second error was of the kind

```
[ERROR] TypeError: Cannot read property 'count' of undefined
```

I could fix it by changing [this.db.getValidClipCount(['en']))[0].count](https://github.com/mozilla/voice-web/blob/4edc20649f73d2b90458adaeec82079bc0f276f7/server/src/lib/model.ts#L169) to 9999.

It has taken me over one hour of guessing as well as reverse engineering to find fixes for these two issues. This makes it harder to get up and running and contribute to the project. It would be really cool to document the workarounds, make the code more resilient or do something else to get ppl up and running more quickly.

**Comment by Gregoor** [comment]
Hi, thanks for looking into it and sorry for those troubles! Those are recent regressions introduced by me, which I didn't notice because I didn't re-test them with an empty database.
0afab3293e3c8abb2a90f60919f59c97bf6c8e8e and fac68b6073047ca5a7b2b95fa873b33a79131438 should fix both issues.
