### ISSUE TITLE
Can I find a recording in the local area? Or can our recording be saved under a directory of the deployment server, allowing audio and text files to use the unique ID and naming the same?

### ISSUE THREAD

**Issue by ZerRui** [mozilla/voice-web#1290]
Can I find a recording in the local area? Or can our recording be saved under a directory of the deployment server, allowing audio and text files to use the unique ID and naming the same?

**Comment by mikehenrty** [comment]
@ZerRui did you look into using docker for your local setup? that environment uses s3proxy, which (if i understand correctly) allows you to store files on the file system.
