### ISSUE TITLE
"Ready to do 5 more" blinks when hovered and sending clips

### ISSUE THREAD

**Issue by zecakeh** [mozilla/voice-web#1295]
Every time the progress bar progresses on top (so I guess every time a clip is sent), the "Ready to do 5 more?" button blinks when it is hovered.
It doesn't look good and it also prevents people from actually clicking on the button before all the clips are sent.

**Comment by codesue** [comment]
Should people be able to click on the button before all the clips are sent?

**Comment by Gregoor** [comment]
Yes, the uploading continues in the background, so that one could keep contributing without being blocked by it.
