### ISSUE TITLE
[iOS] If app is launched while the phone is offline, app will never load even when internet is restored

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#130]
Right now, if the app is launched when offline, the only way to get it to work is to kill the app and relaunch after connecting to the internet. Instead, the app should detect when the internet comes back and reload the webview.

I could swear I saw this working at some point. In any case, this will block the ios release.

**Comment by mikehenrty** [comment]
@andrenatal  can you take a look at this?

**Comment by kdavis-mozilla** [comment]
@andrenatal Can you add this interval check right now. It needs to be there for the release.
