### ISSUE TITLE
db-monitor SSH issue strikes back

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#1303]
I'm getting
```
channel 0: open failed: administratively prohibited: open failed
stdio forwarding failed
ssh_exchange_identification: Connection closed by remote host
```
again when trying to SSH onto it. Unfortunately I don't have sufficient permissions to restart it, can you take a look?

**Comment by gozer** [comment]
Yeah, it's an unfortunate side-effect of the 2.3.0 bugfix I was talking about.

Should be back later today and the problem fixed once and for all.

**Comment by Gregoor** [comment]
Seems to still not work (not on staging either).

**Comment by mikehenrty** [comment]
@gozer, do we need to update our `nubis` version in the Common Voice repo to get the aforementioned bug fix?

**Comment by Gregoor** [comment]
@
