### ISSUE TITLE
Empty recordings

### ISSUE THREAD

**Issue by belkacem77** [mozilla/voice-web#1319]
We got a very large amount of empty recordings today within the kabyle locale!!!!
Could we know if it's the same user or sevral users?
Unfortunaltely we can't identify who, to warn him/them.

About 4/5 recordings are empty

**Comment by jf99** [comment]
Are you sure they are really empty? It might just be #1258. Please check your console for 403 errors before clicking No.

**Comment by belkacem77** [comment]
Yeah, I downloaded some of them. I voted my queue and now watching again. As we are few to work arround the kab locale I warned the team and we are wacthing if it will happen again. I'll come back later.

**Comment by belkacem77** [comment]
Here I got other empty recordings
![2018-08-06 22_03_17-common voice](https://user-images.githubusercontent.com/7033740/43740948-a90058f6-99c4-11e8-80f6-5080658a69f4.jpg)

**Comment by belkacem77** [comment]
Recorded file: here is a sample
[61265f7aeb9baa480f7391efb34db8174ae753261911ac789cf7513e0b3d56e9.zip](https://github.com/mozilla/voice-web/files/2264105/61265f7aeb9baa480f7391efb34db8174ae753261911ac789cf7513e0b3d56e9.zip)

**Comment by belkacem77** [comment]
I got several such recordings

**Comment by Gregoor** [comment]
Thanks for investigating it further. As soon as I can I will look into the database and hide those clips, so that the Kabyle collection efforts can go on. Thanks for hanging in there!

**Comment by belkacem77** [comment]
Thanks. Is there a second check later for the clips? I hope yes before any processing.

**Comment by belkacem77** [comment]
As I'm voting everyday, I think most of them are good.

**Comment by Gregoor** [comment]
The second check is the second yes-vote for the clip. So for the clip to be added to the dataset, it'd need to be approved by another person.

**Comment by belkacem77** [comment]
ok. Thanks
