### ISSUE TITLE
Language code shows up in dropdown

### ISSUE THREAD

**Issue by ftyers** [mozilla/voice-web#1320]
Not sure what the cause of this is, but with some languages (e.g. Hakha Chin) instead of the language name appearing in the drop-down, the language code does. Is it possible to fix this ?

![captura de 2018-08-06 17-39-41](https://user-images.githubusercontent.com/449545/43726631-f530011a-999f-11e8-946b-a85c475c68fe.png)

**Comment by mikehenrty** [comment]
I think we'd either have to hard-code it, or fix it in the upstream package we are using:
https://github.com/meikidd/iso-639-1

**Comment by ftyers** [comment]
@mikehenrty hmm... this code only does iso-639-1 codes, which represent a fraction of the world's languages, the three-letter codes. I've made a pull request upstream, but perhaps it might be better to fork it? There are other sources of language codes and names, for example in [apertium-apy](https://github.com/apertium/apertium-apy/tree/master/language_names). 

I've made an (unfortunately English-only) conversion of that data [here](https://file.io/IhlgGs).

**Comment by Gregoor** [comment]
There's some prior discussion on this in #1018 

Thanks for filing that PR. When we started using the iso-639-1 I didn't know it was limited. My new thinking is that we should extend our locale importer to grab the language names from their `messages.ftl` files. That'll require some fluent parsing, but there's packages for that.

**Comment by ftyers** [comment]
Upstream they suggest migrating to [this package](https://github.com/adlawson/nodejs-langs). Do you think that might be doable ?

**Comment by Gregoor** [comment]
Ah nice, haven't seen this one before. But I just went ahead and removed the iso-library dependency and instead parsed the names from our own translation files. It's on staging atm, will take it onto production early next week.

**Comment by Gregoor** [comment]
Done & Deployed
