### ISSUE TITLE
Suspicious stats for Welsh and Chuvash

### ISSUE THREAD

**Issue by ftyers** [mozilla/voice-web#1325]
According to the [non-english stats thread](https://discourse.mozilla.org/t/non-english-language-stats/29650/10) there were the following number of clips for Welsh and Chuvash:

```
| cy    |   1741 |     638 |
| cv    |   1314 |    1393 |
```

This should come to over an hour of audio. But on the [language stats page](https://voice.mozilla.org/languages) both languages come up with only 0 hours of audio. Perhaps it could be updated to fallback to minutes or perhaps there is a problem with the stats page?

**Comment by Gregoor** [comment]
With 1400 votes, at most 700 clips could be validated, which would amount to 55 minutes in Chuvash right now*. This is very much the best case though.
I like the idea of falling back to minutes though, related discussion in #1167. Wdyt @m-branson?

\* A clip needs two upvotes to be considered valid. We assume an average clip length of 4.7 seconds.
`700 * 4.7s ~= 55min`

**Comment by m-branson** [comment]
Thanks for flagging @ftyers. As we look into moving toward a holistic time based approach, I do agree that conveying at least a minute stamp in addition would be helpful. In #1167 I state:

>I recommend using a traditional 00:00:00 timestamp down to the second to help convey how each recording is moving a stat or goal needle.

I do feel this is the _most accurate_ route, though it could be a more belabored route. Perhaps we balance the two approaches and utilize a `00h 00m` display method to account for various UI needs across the site. (Will also state this in #1167 for continuity.)

This longer format would require more horz space to accommodate label & info though I have an idea of how to achieve that layout should we decide to go this route across the entire site (which I heartily advocate).

cc @mikehenrty

**Comment by Gregoor** [comment]
I changed the [`/languages`](https://voice.mozilla.org/en/languages) page validated time display accordingly.
