### ISSUE TITLE
Add "Russisch Deutsch" to the list of German accents

### ISSUE THREAD

**Issue by highsource** [mozilla/voice-web#1327]
According to [this document](https://www.destatis.de/DE/Publikationen/Thematisch/Bevoelkerung/MigrationIntegration/Migrationshintergrund2010220177004.pdf?__blob=publicationFile#page=34) there are 1.3M+ people with Russian migration background in Germany. This is one of the largest groups after Polen und Turken.

Russians living in Germany also tend to have a distinct accent and a way to speak.

Please let us add Russian to the list of German accents.

**Comment by highsource** [comment]
PR to fix this: #1328.

**Comment by highsource** [comment]
👍

**Comment by nukeador** [comment]
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
