### ISSUE TITLE
[ru] Create initial dataset of 500 Russian sentences

### ISSUE THREAD

**Issue by highsource** [mozilla/voice-web#1332]
As discussed [here](https://discourse.mozilla.org/t/russian-speech/18572/20), I would like to push Russian forward.

This is the first issue to provide Russian sentences.

I will work on this in [my fork](https://github.com/highsource/voice-web) and send the PR once I have 500 sentences.

My approach is simply to translate and adapt German sentences I dictate anyway.

Do I have to sign some contributor license?

**Comment by mikehenrty** [comment]
No need to sign any sort of contributor license. Once you submit your PR, it will be for public domain:
https://github.com/mozilla/voice-web/blob/master/server/data/LICENSE

Thanks for your help!

**Comment by highsource** [comment]
I've got 400 sentences so far.

**Comment by highsource** [comment]
Ok, got 500 sentences. Please see #1400.

**Comment by highsource** [comment]
@mikehenrty Could you please merge #1400 to close this issue?

Am I correct in thinking that we'll need 5k sentences to open voice recording/checking for Russian?

![image](https://user-images.githubusercontent.com/6707996/44443981-cb79a280-a5da-11e8-8ab0-2299dbcb5021.png)

**Comment by mikehenrty** [comment]
thanks, i made a quick comment on the PR
