### ISSUE TITLE
Arabic "Contribute" button is shown in the localized page

### ISSUE THREAD

**Issue by bidaian** [mozilla/voice-web#1334]
The "Get Involved" button, in https://voice.mozilla.org/languages is shown in the page's language, not in Arabic. Compare with Azerbaijani for example:

All localized pages show "Qoşul" for the button inside the Azerbaijani box.

For Arabic, the button gets the text from the page's localization, so i English you see "Get Involved" in German "Mitmachen", for Japanese "参加する".

Please note that Arabic is at 100% in Pontoon.

**Comment by SafaAlfulaij** [comment]
I think this is normal (after checking some other langauges). Since Arabic is still not added to the production server, the translations can't be fetched from the files.
In the testing server everything is correct: https://voice.allizom.org/en/languages

**Comment by mikehenrty** [comment]
@Gregoor is there a way to include languages in the cross-language local file that have not been deployed yet?

**Comment by Gregoor** [comment]
It looks like Get Involved is translated now :)

@mikehenrty nope, the cross-language file is always based on what's in the repo.
