### ISSUE TITLE
Esperanto profile shows English as language

### ISSUE THREAD

**Issue by bidaian** [mozilla/voice-web#1335]
When creating a new Esperanto profile, the only language in the form is English (Angla). That means no speakers can register.

**Comment by Gregoor** [comment]
Does Esperanto have accents? If so, they'd need to be added https://github.com/mozilla/voice-web/blob/master/web/src/stores/user.ts#L7
PRs are welcome.

**Comment by bidaian** [comment]
It does have accents, but they will taken into account once [this](https://projects.invisionapp.com/share/K4FV4BPY6TX#/screens/301676124) from #1315 lands, because they are related to the other languages of the speaker. In the meantime, there's only one accent. I just made the PR #1370.

**Comment by bidaian** [comment]
That PR did not fix the issue.

**Comment by Gregoor** [comment]
Thanks for the PR! That dropdown becomes unlocked once a language is contributable (has more than 5k sentences).

**Comment by mikehenrty** [comment]
@bidaian is this a duplicate of #1315?

**Comment by bidaian** [comment]
No. They are two different issues. This one will be solved when we get to 5k. It's actually not an issue, if I understand @Gregoor correctly in the above comment.

And #1315 will be fixed when [this](https://projects.invisionapp.com/share/K4FV4BPY6TX#/screens/301676124) lands. It's more a wishlist than an issue. It could be a duplicate of the main issue tracking the changes you plan to make.
