### ISSUE TITLE
[Edge] Record remains locked to Play state

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1338]
Environment:
Windows 10, latest Edge 

STR: 
1. Navigate to [https://voice.mozilla.org/en/listen](https://voice.mozilla.org/en/listen)
2. Validate several sentences

Expected: 
Stop button is shown after recording is done playing, Yes / No buttons are available for each sentence after record has stopped.

Actual:
Record doesn't stop playing after tens of seconds, no sounds is heard. Only Stop and No buttons are available. I need to refresh the page in order to hear the recordings again and be able to validate with both Yes / No options. 
See [video](https://drive.google.com/file/d/1cogu2TP4zSTvsJS5ntMTM3U3sKbxjCXo/view?usp=sharing).

**Comment by Gregoor** [comment]
Couldn't reproduce. Maybe an invalid recording? Did it happen often?

**Comment by mikehenrty** [comment]
@viorelaioia are you still able to reproduce? can you tell us if there are any errors in the javascript console?
