### ISSUE TITLE
 [nl] Create initial dataset of 500 Dutch sentences 

### ISSUE THREAD

**Issue by pcmill** [mozilla/voice-web#1340]
I would love to get the Dutch language going for this project. Like @highsource I have made a [fork](https://github.com/pcmill/voice-web) and will be making a list of sentences. 

Most of the sentences will be translated from the English list, but I will also try to make some originals ;)

**Comment by fredlockheed** [comment]
👍

**Comment by highsource** [comment]
Hey @pcmill how is it going?

I wonder, what is your method to gather/create sentences?

**Comment by pcmill** [comment]
I mostly (roughly) translate sentences from English. I made a list of categories and kind of filled them:

- General
- Foods and Drinks
- Months and Times
- Medical
- Nature
- Religion
- Social
- Sports
- Proverbs
- Technologie
- Business

My sentences got merged this day actually, but I think I can add some more sentences that reference more locations in Belgium since they also speak Dutch.

**Comment by danielsjf** [comment]
@pcmill today also another big merge was done for Dutch sentences, also in collaboration with Sjoerd. There I also included many locations, but the more the better.

**Comment by danielsjf** [comment]
Just saw that the limit has gone up from 500 sentences to 5000. Therefore we need an additional 1500 for the launch. @pcmill @sroet, interested in setting up a different collaboration channel?

**Comment by pcmill** [comment]
Sure, sounds like a good idea.

**Comment by highsource** [comment]
@danielsjf Where did you saw about the 5k limit?

**Comment by danielsjf** [comment]
If you go to the website, go to languages, click on the tab progress and you will see it. Under Dutch, it says 3600/5000.

**Comment by highsource** [comment]
@danielsjf Ok, I see, thanks. Russian is at 0 at the moment, I'm working on a fork, wasn't merged yet.

But it good to know which volume is required. Wasn't apparent for me before.

**Comment by sroet** [comment]
@danielsjf @pcmill Sorry, I will not be able to contribute constructively anytime soon. (currently in the middle of moving countries) I should be able to proofread, if required.

**Comment by pcmill** [comment]
No problem @sroet, I will try my best to come up with some more sentences. You already made most of them anyway.

**Comment by pcmill** [comment]
We are live on the website with Dutch, so I can close this issue :smile:

**Comment by danielsjf** [comment]
Finally! Thanks for the great work guys!

**Comment by Gregoor** [comment]
Awesome stuff y'all!

**Comment by danielsjf** [comment]
Submitted the news on [Tweakers](https://tweakers.net/nieuws/143005/nederlandstalige-gebruikers-kunnen-hun-stem-doneren-aan-open-mozilla-dataset.html) and now we are already at 2h30 recorded and 130 speakers ;-)

**Comment by mikehenrty** [comment]
Dutch is one of our fastest growing datasets right now! Great work everyone!
