### ISSUE TITLE
Add shortcut to continue with "do another 5?"

### ISSUE THREAD

**Issue by highsource** [mozilla/voice-web#1342]
I am actively using shortcuts and often do many quintets in a row.

It would be helpful to have the same shortcuts to go to the next quintet session: `a` for recording and `p` for listening. (Or whatever the localized variants are.) Instead of using the mouse to click the button.

**Comment by sroet** [comment]
I am pretty sure there is a secret "enter" shortcut for that

**Comment by highsource** [comment]
@sroet The point was to have *the same shortcuts* so that the user does not have to move hands.

**Comment by mikehenrty** [comment]
@sroet can you be more specific about which keys you would like to `do another 5`? or were you thinking any key?

**Comment by mikehenrty** [comment]
> @sroet can you be more specific about which keys you would like to do another 5? or were you thinking any key?

sorry I meant @highsource, not @sroet

**Comment by sroet** [comment]
@mikehenrty No problem

**Comment by highsource** [comment]
@mikehenrty The same shortcuts as for the main actions in the current activity. I don't know if they are language specific, but for German that would be:

* `A` - record next five.
* `P` - listen to next five.

The point is, when I listen, I have my hands on `P`. I want to continue listening, I either have to reach for `Enter` or use a mouse. Having a `P` shortcut to continue would save me this.

**Comment by mikehenrty** [comment]
@mbransn, this is feature request that would be very easy to implement. Alexey is asking that in addition to the "Enter" key, you can also use the Play and Record keyboard shortcuts to dismiss the "Success Modal" and move onto the next 5 contributions. What do you think?

**Comment by mbransn** [comment]
@mikehenrty thanks for the loop in. I appreciate this suggestion @highsource, it's a great one. To enable the best mental model mapping for are diverse contributor base, I propose utilizing the main actions as you suggested + the maintaining the enter key. Humans are all quite different and have different expectations, we would like to be as inclusive as possible. :)

@Gregoor can we ensure we make it clear in the shortcuts modal all of the keys that are specified as a shortcut for any action. Even if there are multiple?

Side note: I also have an open issue for a shortcut customization feature once we get profiles and settings in a solid place.

**Comment by Gregoor** [comment]
With the new profile experience you can now configure whether you want to see the success screen
