### ISSUE TITLE
Shard of dataset

### ISSUE THREAD

**Issue by Elch123** [mozilla/voice-web#1344]
Could you please allow for downloading a fragment (100Mb) of the dataset? The full dataset is large, and I lack space to expand the entire dataset.

**Comment by mikehenrty** [comment]
@Elch123 is there a particular fragment you are interested in? or just a representative sample?

**Comment by Elch123** [comment]
Just a representive sample, so I can begin work on a machine with an ssd that can't hold the full dataset.

**Comment by Gregoor** [comment]
Duplicate of #1206
