### ISSUE TITLE
Yes/No buttons are incorrectly displayed on hover in Edge

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1345]
[Steps to reproduce]:
1.Open Microsoft Edge
2.Go to https://voice.allizom.org/en/listen
3.Click the Play button
4.Hover over Yes and No buttons while the clip is playing

[Actual result]:
The icons for "Yes" and "No" buttons  are changed into a black square

[Note]:
The issue is reproducible in http://voice.mozilla.org/ also
The issue is intermittent.
The issue is not reproducible in Firefox and Chrome 
![yes-no](https://user-images.githubusercontent.com/41474886/44035405-1bb27ad4-9f18-11e8-819b-43cb903c6044.png)

**Comment by poush** [comment]
Edge seems disabled. Is it intended or due to these issues?

**Comment by poush** [comment]
Hi @mikehenrty, Is this still an issue? or the support of Edge is dropped?

**Comment by Gregoor** [comment]
It's not intentionally disabled, it broke in a previous release but it's unclear why (and Edge's error log is not helping much).

**Comment by MichaelKohler** [comment]
Can't reproduce anymore on latest Edge
