### ISSUE TITLE
Overly generic variables make translators sad

### ISSUE THREAD

**Issue by piotrdrag** [mozilla/voice-web#1357]
language-section-launched-description uses variables from elsewhere in the messages.ftl file, resulting in incorrect text:

![screenshot_2018-08-14 common voice by mozilla](https://user-images.githubusercontent.com/139229/44122322-a3aabbb6-a023-11e8-84e5-1cfa2e49ea49.png)

These variables should be unique for this particular string.

CCing @peiying2

**Comment by Gregoor** [comment]
Thanks for the report, can you elaborate for me why it doesn't work in that sentence?
Those words should reflect the name of the sections (Speak & Listen in english) to make clear how all these efforts tie into each other. Maybe Nagrywaj or Posłuchaj are not the right words in general?

**Comment by piotrdrag** [comment]
These are the right words (or more exactly, forms of words) for buttons on https://voice.mozilla.org/en/speak and https://voice.mozilla.org/en/listen (not available in Polish yet), but in this sentence we need a different form for it to sound correct to Polish users.

In general, using the same string in different contexts is a big no-no in i18n, as it almost always forces English grammar rules on translations.

By the way, looking at the mentioned pages, I noticed something else that won’t work well in Polish (and probably other languages):

![zrzut ekranu z 2018-08-16 16-58-49](https://user-images.githubusercontent.com/139229/44216714-dadd9380-a175-11e8-8c70-dd85cbb3cab2.png)

At the very least I need to move the count to the right of the label, but the order is currently hardcoded.

**Comment by Gregoor** [comment]
I see, thanks for the explanation and pardon my ignorance! Then we'll change all of those strings!

**Comment by Gregoor** [comment]
New strings for those cases will be on Pontoon in a bit. Once we have enough translations, I'll swap them out.

**Comment by piotrdrag** [comment]
Looks good, thanks a lot!
