### ISSUE TITLE
Languages page displays zero hours for languages with data

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/voice-web#1360]
Hi Common Voice folks, 

Looking at the [Languages page](https://voice.mozilla.org/en/languages) on the Common Voice site (from laptop) it seems as if some of the numbers for "Validated Hrs" are off.

Specifically, I know that Chuvash used to have at least one hour, but now it's displayed as having '0 Hrs'

![chuvash](https://user-images.githubusercontent.com/8389864/44140289-3dad724c-a03f-11e8-820d-6f5160144b56.png)

-josh

**Comment by ftyers** [comment]
This is related to #1325.

**Comment by Gregoor** [comment]
Indeed and I changed that just now. Hope the new format is more comprehensible 🙂

**Comment by ftyers** [comment]
@JRMeyer I think that there should definitely be over 1 hour of data with a single validation, but with double validation, I don't know, I would suspect not yet :( Having said that, basically anything that I've validated can be considered valid, so I don't know if it's possible to just flag those as having an extra vote?

**Comment by Gregoor** [comment]
I'd quite like such a system where we don't require multiple votes for clips that have been voted for by "trusted"-users. Maybe we should make some time for it. Wdyt @mikehenrty?

**Comment by mikehenrty** [comment]
I'm open to the discussion of such a thing. @ftyers already filed a bug for this: 
#1379
