### ISSUE TITLE
The "Speak up, contribute here!" button is displayed in another language for ~1 second when selecting FRYSK" or "GAEILGE" language

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1365]
[Environment]:
Windows 10, Chrome 68, Firefox 61, latest Edge
[2018-08-16_11h25_15.zip](https://github.com/mozilla/voice-web/files/2293000/2018-08-16_11h25_15.zip)

[Steps to reproduce]:
1.Open Microsoft Edge
2.Navigate to https://voice.allizom.org
3.Navigate to the languages drop-down 
4.Select "FRYSK" or "GAEILGE" language

[Expected result]:
The "Speak up, contribute here!" button should be displayed in the selected language

[Actual result]:
The "Speak up, contribute here!" button is displayed in another language for ~1 second

[Note]:
The issue is reproducible in http://voice.mozilla.org/  also

**Comment by Gregoor** [comment]
Since we're redoing the homepage anyway, I'll close non-critical bugs related to the old homepage
