### ISSUE TITLE
[Listen] Some clips don't contain text

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1366]
[Environment]:
Windows 10, Chrome 68

[Steps to reproduce]:
1.Navigate to https://voice.allizom.org/fr/listen
2.Press Skip shortcut until a clip with no text is displayed
3.Click Play button
4.Click Yes or No button

[Expected result]:
All clips should contain text

[Actual result]:
Some clips don't contain text
The clips without text can be played and can be marked as good or bad.

[Note]:
I reproduced the issue also for the English language
The issue is reproducible also in http://voice.mozilla.org/ 
[2018-08-16_14h46_24.zip](https://github.com/mozilla/voice-web/files/2293639/2018-08-16_14h46_24.zip)

**Comment by rleitan** [comment]
After a clip without text is displayed, the skip button must be clicked twice to take the action.

Reproduced on Win 10 - Chrome 68, Firefox 61 and iOS 12.0

**Comment by mikehenrty** [comment]
@rleitan is there sound on the clips where there is no text?

**Comment by rleitan** [comment]
@mikehenrty Yes, and the clip can be validated

**Comment by mikehenrty** [comment]
@rleitan I mean, does someone speak actual words on the recording? i'm trying to figure out if the sentence was blank when it was originally presented to the speaker

**Comment by rleitan** [comment]
@mikehenrty Yes, somebody speaks actual words on the recording. I' think that the sentence wasn't blank when the speaker recorded it.
