### ISSUE TITLE
[Safari] The "Shortcuts" and "Skip" buttons margins are not correctly displayed when are selected using the Tab key

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1367]
[Environment]:
Safari 11.1.2 on Mac OS 10.13

[Steps to reproduce]:
1.Navigate to https://voice.allizom.org/en/listen
2.Press Tab key to navigate through the buttons 

[Expected result]:
All buttons should be displayed with a black margin when are selected

[Actual result]:
"Shortcuts" and "Skip" buttons margins are not correctly displayed when are selected using the Tab key
"Skip" button is displayed with black lines after the next button from the page is selected with the Tab key

[Note]:
The issue is reproducible in http://voice.mozilla.org/ also
The issue is not reproducible in Firefox or Chrome

![safari](https://user-images.githubusercontent.com/41474886/44209032-d9f33480-a16a-11e8-9d1e-47a250dc952c.png)

**Comment by Gregoor** [comment]
looks good now :)
