### ISSUE TITLE
[Safari] Navigation through the page using the Tab key is not working in https://voice.allizom.org/en/speak

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1368]
[Environment]:
Safari 11.1.2 on Mac OS 10.13

[Steps to reproduce]:
1.Navigate to https://voice.allizom.org/en/speak
2..Press Tab key to navigate through the buttons

[Expected result]:
The buttons should be displayed with a black margin when are selected

[Actual result]:
No action when pressing the Tab key. The buttons are not selected

[Note]:
The issue is reproducible in http://voice.mozilla.org/ also
The issue is not reproducible in Firefox, Chrome or Edge
The same issue is encountered on https://voice.allizom.org/ page. "Help", "GitHub", "Discourse", "Twitter" and "Facebook" buttons are not selected with Tab key

**Comment by Gregoor** [comment]
Looks like it works now!
