### ISSUE TITLE
Graph for german is negative

### ISSUE THREAD

**Issue by est31** [mozilla/voice-web#1377]
See this screenshot:
![screenshot](https://user-images.githubusercontent.com/8872119/44248064-c686ae80-a1e8-11e8-9e30-942a91cf867e.png)

Here you can see that the graph is *negative* at the start. Negative counts are not possible. I guess there is something wrong with how the graph is being smoothed.

**Comment by jf99** [comment]
Cool, where did you take that screenshot from? Can't find the graph page.

**Comment by est31** [comment]
@jf99 it's on the new website: https://voice.mozilla.org/en/new

**Comment by est31** [comment]
The idea of having a graph is awesome, but there's clearly a bug somewhere. Negative counts are impossible :p.

**Comment by est31** [comment]
Commit b0b72b52a3aaffaa87db9e48caa5a58ba4f41ad1 has improved the situation. Now the screenshot for german is:

![screenshot](https://user-images.githubusercontent.com/8872119/44419249-ef0d0080-a57a-11e8-90fe-dc7e80cf4262.png)

But all the commit did was changing the intensity of the smoothing. With the "right" data, there might still be such negative values. So I won't close this unless @Gregoor disagrees :).

**Comment by est31** [comment]
A small search on the web gave me two "good" fixes to this: [first](https://en.wikipedia.org/wiki/Monotone_cubic_interpolation), [second](http://www.korf.co.uk/spline.pdf). Although I'm not sure whether the first one will work as our data is not guaranteed to be *monotonic*.

**Comment by Gregoor** [comment]
Very vigilant and I do agree with you that it's not quite fixed! We should use more data for that graph. Though I also like the first link you found, [D3 apparently also has an implementation of it](https://github.com/d3/d3-shape/blob/master/src/curve/monotone.js). Though I don't want to pull in a heavy dependency, so I think I'll try it with more data first

**Comment by Gregoor** [comment]
Monotonic cubic looks much better, thanks again for the pointer @est31!

**Comment by est31** [comment]
for the record, the fix was b83bbf35c6f8adcb92673991209b352fe606b199 . Thanks, @Gregoor !
