### ISSUE TITLE
Counting sentences

### ISSUE THREAD

**Issue by danielsjf** [mozilla/voice-web#1381]
I was checking the Dutch language, a language currently in progress. At the moment, the website tells us there are 3644 sentences. However, when I check the lines on Github, there is one large file (2874 lines) and a few smaller files (in total 506 lines according to Github). When I add the lines I find only 3380 sentences. Where are the additional sentences coming from?

Besides this, it would also be interesting to have the sentence statistic for the launched languages. Currently the launched languages only have the validated hours statistic.

**Comment by Gregoor** [comment]
Good catch, there was an error in the query. It's fixed on staging, will be on production in the next days.

RE sentence statistics: I agree, that it'd be nice to surface that somewhere. @m-branson wdyt?

**Comment by m-branson** [comment]
Agreed it's a good content/feature request to track for Language Page updates (which are on our roadmap). @Gregoor do you mind capturing as such for now?

**Comment by Gregoor** [comment]
Sure, where would I best capture that @mbransn? I could also add a Languages-page milestone and flag every GitHub issue that came or comes up with it.

**Comment by mbransn** [comment]
Perfect @Gregoor, that'd be super helpful. Labeling as `feature request` may also be good practice. Thank you!

**Comment by davidak** [comment]
Is this fixed now?

![Screenshot from 2019-06-08 14-03-45](https://user-images.githubusercontent.com/91113/59147029-412dee00-89f6-11e9-9af3-86aae1a87147.png)

**Comment by Gregoor** [comment]
Cool, yup! Thanks for going through these!
