### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1385]
[Environment]:
Windows 10, Chrome 68, Firefox 61, latest Edge

[Steps to reproduce]:
1.Open https://voice.mozilla.org/en/new

[Expected results]:
1. Listen section text should be "Ready to contribute"
2. "Ready to donate your voice" section should be displayed at the bottom of page
3. "Sign-up for email details" should be displayed at the bottom of page
4. Speak/Listen section: on hover: "Have you read our Terms" link should be displayed

[Actual results]:
1. Listen section text is "Help us validate voices"
2. "Ready to donate your voice" section is not displayed
3."Sign-up for email details" is not displayed
4. Speak/Listen section: on hover: "Have you read our Terms" link is missing

**Comment by Gregoor** [comment]
1. Text differ from the designs because we have a copywriter now who changed some of those.
2. Will add that and Mars later
3. The E-Mail signup part is still in triage.
4. done

**Comment by Gregoor** [comment]
2. done
