### ISSUE TITLE
[Edge]The background animation disappear for a second when the mouse is hovered over the Speak or Listen sections

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1386]
[Environment]:
Windows 10, latest Edge

[Steps to reproduce]:
1.Open https://voice.mozilla.org/en/new
2.Hover using mouse over the Speak and Listen sections

[Expected results]:
The Speak and Listen sections should expand and the background animation should be displayed

[Actual results]:
The background animation disappear for a second when the mouse is hovered over the Speak or Listen sections
![2018-08-20_16h12_09](https://user-images.githubusercontent.com/41474886/44342779-babf1480-a494-11e8-834b-44a9342f6e67.gif)

**Comment by Gregoor** [comment]
I think this is a bug in Edge, I created an issue in their tracker:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18746507/
