### ISSUE TITLE
" Help us get to " section is not correctly displayed 

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1387]
[Environment]:
Windows 10, Chrome 68, Firefox 61, latest Edge

[Steps to reproduce]:
1.Open https://voice.mozilla.org/en/new
2.Hover using mouse over the Speak and Listen sections

[Expected results]:
" Help us get to " test should be displayed above the play/speak icon

[Actual results]:
" Help us get to " test is displayed below the play/speak icon

[Note]:
On Firefox and Edge, the line between play/speak icon and text is missing
![help us get](https://user-images.githubusercontent.com/41474886/44343452-9ebc7280-a496-11e8-89b1-883104e26325.png)

**Comment by Gregoor** [comment]
I moved it below, so that the button moves around less. Afaik @georai was alright with that change (if not I'll reopen and we have to find a different solution).
