### ISSUE TITLE
The hours from homepage dashboard are overlapped

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1389]
[Environment]:
Windows 10 - latest Edge

[Steps to reproduce]:
1. Open https://voice.mozilla.org/en/new
2. Observe the "Voices Online Now" dashboard

[Expected results]:
The dashboard items should be properly displayed,
The hours should be displayed without AM/PM 

[Actual results]:
The hours are overlapped and the AM/PM details are displayed

[Note]:
On browser resize the hours and the dates from both dashboards are overlapped ( this is happening in Chrome and Firefox also)

![2018-08-20_17h24_38](https://user-images.githubusercontent.com/41474886/44346163-f9a59800-a49d-11e8-9830-a949ba72a2d4.png)

**Comment by Gregoor** [comment]
It looks correct on my Edge, can you enter `javascript:alert(navigator.languages)` into the address bar of a new tab? Might be specific to the OS language

**Comment by rleitan** [comment]
en-US is the OS language

**Comment by Gregoor** [comment]
Huh, that's mine as well. What's your Edge version? I'm looking at it with 42.17134.1.0

**Comment by rleitan** [comment]
Mine is 42.17134.1.0 also

**Comment by rleitan** [comment]
this issue is reproducible on iOS 11.4.1 also.
The AM/PM are not displayed but the hours are overlapped

**Comment by Gregoor** [comment]
Still can't reproduce on Edge, but just went ahead and hid every second bar on mobile. A better fix would be to only show the more recent bars, unfortunately there's no layouting help within SVG for that.

**Comment by Gregoor** [comment]
It looks nicer now on smaller viewports :)
