### ISSUE TITLE
Hero Speak/Listen

### ISSUE THREAD

**Issue by grailean** [mozilla/voice-web#1391]
@Gregoor 

- Lets change the elements of the Titles and waves: https://www.dropbox.com/s/mo8axomtb395kx2/lcvae3cv.png?raw=1

- On hove the Speak title is moving up the waves are becoming larger and new elements appearing: https://www.dropbox.com/s/aplqdr5n6sattvx/lvkdfau9.png?raw=1  Please for now add the opacity(50%) on hover lets have 100%  on the waves. I will work on SVG animations.

 - Same issue on Listen

**Comment by Gregoor** [comment]
@grailean I made changes for the first point, but I don't understand the second one.

**Comment by grailean** [comment]
@Gregoor Now we have the opacity 100% on the waves needs to be 50%, on hover we will have 100%
