### ISSUE TITLE
The page is not correctly displayed after zoom in/out and open the header menu

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1394]
[Environment]:
Windows 10( Chrome 68, Firefox 61, latest Edge), Mac OS 10.12 (Safari)

[Steps to reproduce]:
1. Open https://voice.mozilla.org/en/new
2. Zoom in the page until the header menu disappears ( Contribute, Datasets, Languages)
3. Click on the dots located in the upper right corner to expand the header menu ( Contribute, Datasets, Languages)
4. Zoom out to 100%
5. Scroll down

[Expected results]:
3. The header menu should be vertically displayed 
4. The page should be zoomed out and display the initial page
5. The page should be scrolled down to display all the initial info

[Actual results]:
3. The header menu is vertically displayed but is overlapped by Speak icon
4. The page is zoomed out and displays two header menus, two language drop-down and the speak and listen icons
5. The page displays only the header menu

![header menu](https://user-images.githubusercontent.com/41474886/44398545-e4d40d80-a54c-11e8-818c-44d8618e607e.png)

**Comment by MichaelKohler** [comment]
This looks better with the new interface.
