### ISSUE TITLE
[Safari] The language drop-down scrollbar is not displayed

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1395]
[Environment]:
Mac OS 10.12 (Safari)

[Steps to reproduce]:
1.Open https://voice.mozilla.org/en/new
2.Hover over the language drop-down 

[Expected results]:
The drop-down should be opened and should contain a scrollbar

[Actual results]:
The drop-down is opened but the scrollbar is missing
![language scrollbar](https://user-images.githubusercontent.com/41474886/44399194-4bf2c180-a54f-11e8-9101-2543d1b1c0b3.png)

**Comment by Gregoor** [comment]
That's Safari default behavior. I agree that it's a bit stupid, though their users might be used to it. Wdyt @mbransn, should we hack a scrollbar in there?

**Comment by rleitan** [comment]
The scrollbar appears if I press up/down arrows

**Comment by mbransn** [comment]
I mean, scrollbars are helpful. 🤷‍♀️ Ideally we'd have parity across all instances.

As for how this rates priority wise, I believe it may be lower on the to do list at the moment.

**Comment by MichaelKohler** [comment]
As mentioned before, this is default behavior. And that behavior can be adjusted in the MacOS settings.
