### ISSUE TITLE
[Safari] The animation margins are too dark

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1396]
[Environment]:
Mac OS 10.12 (Safari)

[Steps to reproduce]:
1.Open https://voice.mozilla.org/en/new

![animation color](https://user-images.githubusercontent.com/41474886/44399816-9412e380-a551-11e8-8ba9-31658144d775.png)

**Comment by Gregoor** [comment]
Already fixed on staging 🙂
