### ISSUE TITLE
Figure out approach to security review of products

### ISSUE THREAD

**Issue by geroter** [mozilla/voice-web#14]
Reach out Selena D

**Comment by mikehenrty** [comment]
Emailed Selena, waiting to hear back.

**Comment by mikehenrty** [comment]
Heard back from Selena, she recommended using a third party service. We are investigating this now.

**Comment by geroter** [comment]
Checking with IT security team for RRA.

Also getting a quote for an outside security firm.

**Comment by mikehenrty** [comment]
we have filed an internal bug to get a rapid risk assessment internally: https://bugzilla.mozilla.org/show_bug.cgi?id=1369189

**Comment by mikehenrty** [comment]
RRA started today. Should have a series of recommendations from Tristan Weir in the next day or so.

**Comment by mikehenrty** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1371458

Estimated Risk: low
