### ISSUE TITLE
Add loading spinner when loading Terms of service page

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1401]
[Environment]:
Windows 10, Chrome 68, Firefox 61, latest Edge

[Steps to reproduce]:
1.Open https://voice.mozilla.org/en/new
2.Hover over Listen or Speak section
3.Click "Have you read our Terms" link

[Expected result]:
The page should be redirected to https://voice.mozilla.org/en/terms

[Actual result]:
The page is redirected to https://voice.mozilla.org/en/terms page but for ~1 second appear only the header and the footer
![terms](https://user-images.githubusercontent.com/41474886/44448797-fb35a400-a5f4-11e8-9b07-11eb5ed14f38.gif)

The  "you" of Have you read our Terms sentence is cut 
![terms](https://user-images.githubusercontent.com/41474886/44448686-9e39ee00-a5f4-11e8-973b-e3b4df3dd289.png)

**Comment by Gregoor** [comment]
The typo was fixed in #1398 

We currently don't have loading states for privacy/terms sites (they're fetched from the Backend). I guess I could add a spinner
