### ISSUE TITLE
The dashboard drop-down text is too close to the drop-down arrow

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1402]
[Environment]:
Windows 10:
 Chrome 68, Firefox 61, latest Edge

[Steps to reproduce]:
1.Open https://voice.mozilla.org/en/new
2.Select Esperanto language
3.Observe the dashboards

[Expected results]:
All dashboards elements should be correctly displayed

[Actual results]:
The dashboards drop-downs text is too close to the drop-down arrow
This issue is reproducible for other languages too

![dashboardss](https://user-images.githubusercontent.com/41474886/44451352-37b8ce00-a5fc-11e8-8aee-3aa9830968be.png)

**Comment by Gregoor** [comment]
Looks fixed to me 🙂  (though I don't recall explicitly fixing it)

**Comment by rleitan** [comment]
I verified on Chrome 68, Firefox 61, latest Edge and it's fixed

**Comment by Gregoor** [comment]
Great, thanks!
