### ISSUE TITLE
Record your voice message

### ISSUE THREAD

**Issue by grailean** [mozilla/voice-web#1405]
On my 27" monitor the Ready to record your voice? on the Mars section is far away on right. Maybe we need a rule to be closer to Mars. @Gregoor

**Comment by mikehenrty** [comment]
@grailean can you attach a screenshot? also, can you be more specific about what you would like to see here instead? im not sure what you meant by "rule"

**Comment by grailean** [comment]
@mikehenrty Gregor already solved it. He uploaded the latest svg backgrounds and now looks perfect.

**Comment by mikehenrty** [comment]
great, thanks @grailean and @Gregoor !
