### ISSUE TITLE
Sign Up for Emails through the Footer

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#1408]
![footer_01](https://user-images.githubusercontent.com/4051932/46015887-b1e4e280-c0d3-11e8-9e07-e85e5f075ca7.png)
![footer_03](https://user-images.githubusercontent.com/4051932/46015889-b3160f80-c0d3-11e8-9f15-83039abd4525.png)
![nav_footer 2 hover](https://user-images.githubusercontent.com/4051932/46015890-b4dfd300-c0d3-11e8-8cd5-7171035afab4.png)
![nav_footer 2 done](https://user-images.githubusercontent.com/4051932/46015891-b6110000-c0d3-11e8-8dc7-8e8e6706b558.png)
![footer_02](https://user-images.githubusercontent.com/4051932/46015893-b7422d00-c0d3-11e8-9a1d-1e94f3328626.png)

**Comment by Gregoor** [comment]
@mbransn happy to put this in. Some unanswered questions, which I think we talked about before, but didn't answer yet:
1) Should this do the same thing as adding an email to the profile and checking the sendEmails flag? I.e. after filling it out and then navigating to profile, is that information filled in?
2) Would this be hidden after one subscriped (and the page was reloaded)?

**Comment by Gregoor** [comment]
I just realized that what I alluded to in the user settings docs also applies here, namely:

> The Email/Marketing team said it’d be painful to manage the “subscribed”-state on both our and their side and their recommendation was that we’d link to the Mozilla-wide email settings page

But that very much constrains what we can do here. It'd mean we'd have to always show the email subscription field, as we wouldn't know whether the user already signed up. We could still have our own flag in our DB but that would become invalid as soon as the user changes their setting through the Mozilla-wide email page.

**Comment by mbransn** [comment]
Hmm, alright. I'm fine with always showing the field. :) No need to over engineer it! More importantly, we will provide an updated email subscription section for you that includes a CTA to link out to the Moz-wide settings page.

**Comment by Gregoor** [comment]
[Backend endpoint is in place](https://github.com/mozilla/voice-web/blob/master/web/src/services/api.ts#L206-L209), only thing missing now is the frontend

**Comment by jkmdev** [comment]
@Gregoor Would it be okay with you if I tried to implement this?

**Comment by Gregoor** [comment]
@jkmdev more than okay! Let me know if you want to talk through it.

**Comment by mbransn** [comment]
@jkmdev here are links to UI for [desktop](https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be?seid=5af9ab33fa73f36910470ca0) and [mobile](https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be?seid=5bec4f08350a363ec3ce9f39), thanks for jumping in to help! 👏

**Comment by Gregoor** [comment]
1. Yes-ish. With the new profile experience coming, we'll know when a user has already signed up and will be able to hide it for them. But until that's landed, let's assume it's always displayed
2. Exactly. On the backend we make sure that the user doesn't subscribe multiple times.

**Comment by mbransn** [comment]
@jkmdev I'm happy to add you to the Zeplin instance, just need an email. :) If you feel more comfortable sending that to me individually, send to mbranson@mozilla.com -- excited to have you helping out!
