### ISSUE TITLE
[Win10] Edge, add message to say "Browser not supported"

### ISSUE THREAD

**Issue by paulsilaghi** [mozilla/voice-web#141]
[Affected versions]:
- Microsoft Edge v25

[Affected platforms]:
- Win 10 x64

[Steps to reproduce]:
1. Open https://voice.allizom.org/

[Expected result]:
- The app is displayed and works properly

[Actual result]:
- The app loads, but the UI is broken, basic functionality doesn't work (speak, listen)

**Comment by paulsilaghi** [comment]
If the browser is not supported, there should be an error message explaining this.

**Comment by kenrick95** [comment]
I think it is because MediaRecorder API not being supported yet in Edge, though it is "under consideration": http://caniuse.com/#search=MediaRecorder

**Comment by mikehenrty** [comment]
Hi @kenrick95, it's nice to see you here!

Good find! I think the best thing to do here is to simply display the "browser is not supported" message (rather than trying to do any sort of encoding ourselves).
