### ISSUE TITLE
Mars on Homepoage

### ISSUE THREAD

**Issue by grailean** [mozilla/voice-web#1411]
Please decrease the size with 20%. I will provide the waves and Mars in different layers maybe will hope to have a better quality of the Mars and a responsive Wave for a wide screen. @Gregoor

**Comment by grailean** [comment]
New svg files: https://www.dropbox.com/s/fj6zgkuijawqfes/Mars_%26_wave%28separate%29.zip?dl=0

**Comment by Gregoor** [comment]
@grailean lmk if it looks as expected (on staging)
