### ISSUE TITLE
Footer UI Updates

### ISSUE THREAD

**Issue by grailean** [mozilla/voice-web#1412]
@Gregoor On UI footer we have 2 line dividers of the menu items. Please add them.

**Comment by mbransn** [comment]
@Gregoor also, would be fantastic to get the email sign up added into the global [footer build](https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5ae0ce8d65c8158369977fd4). 😬

cc @mikehenrty for visibility.

**Comment by mbransn** [comment]
@Gregoor I see that you've opened #1408 for this, would be great to align all footer issues into one collective update when you're ready.

**Comment by Gregoor** [comment]
I thought they're distinct enough functionalities to justify separation (also #1408 requires some backend work, whereas this here is purely visual). I'll drop my email signup comment over there.

**Comment by mikehenrty** [comment]
@grailean can we add a screenshot for this? that way I can add a `help-wanted` tag and maybe get some contributor help.

**Comment by mbransn** [comment]
@Gregoor noted, great to keep them separated. Was hoping to get to up-to-date on how we were tracking against. :)

@mikehenrty apologies that Zeplin is not providing wider access to all of the screens. That said, we can also point contributors to the UI prototype where the footer states will be uploaded by @grailean  shortly. Will point to them here when they are available.

**Comment by mbransn** [comment]
@Gregoor sorry to reopen 😬 I hadn't had a chance to QA this on stage and wanted to quickly point out that the input background color (default state) should match the background color of `div.sharing` `background-color: hsla(0,0%,100%,.1);`
