### ISSUE TITLE
recording ending noice

### ISSUE THREAD

**Issue by qdinar** [mozilla/voice-web#1418]
when recording is stopped, ie at the end of it, sometimes there is a specific sound/noice. should users choose such recording as wrong or right, at the recordings validation page?

**Comment by qdinar** [comment]
i wanted to write "is recording ending noice allowed?" to the title/heading.

**Comment by qdinar** [comment]
i could not log in to https://discourse.mozilla.org/c/voice , so i write here.

**Comment by jf99** [comment]
Noise at the beginning, end or in the middle of a recording is allowed. As long as one understands exactly what the contributor was supposed to read, vote Yes.

You are not alone with your discourse issues: https://discourse.mozilla.org/t/2fa-cannot-be-mandatory/30352

**Comment by Gregoor** [comment]
As alluded to in #1419, all kinds of noise that might appear in the wild is welcome and should be considered valid
