### ISSUE TITLE
is additional sniffing noice allowed?

### ISSUE THREAD

**Issue by qdinar** [mozilla/voice-web#1419]
i see a recording where the reader makes some sniffing in middle of reading, which is not present in the text. should this be considered valid recording or not?

**Comment by Gregoor** [comment]
To quote the [FAQ](https://voice.mozilla.org/en/faq):

> **What is the level of quality needed for the audio in order to be used?**
> We want the audio quality to reflect the audio quality a speech-to-text engine will see in the wild. Thus, we want variety. This teaches the speech-to-text engine to handle various situations—background talking, car noise, fan noise—without errors.

So yes, we want everything that could appear in the wild, like sniffing noices, coughing, laughter etc.

**Comment by qdinar** [comment]
faq does not say about this situation. it lists only noices by other sources. i said about noice produced by the reader.

i think if they read in a language which includes the sniffing voice in the language phonemes, (if such language exists), then additional sniffing can be accounted/considered wrong reading.
