### ISSUE TITLE
[Win10] The app doesn't load on IE11

### ISSUE THREAD

**Issue by paulsilaghi** [mozilla/voice-web#142]
[Affected versions]:
- Microsoft IE11

[Affected platforms]:
- Win 10 x64

[Steps to reproduce]:
1. Open https://voice.allizom.org/

[Expected result]:
The app is displayed and works properly /
If the browser is not supported, there should be an error message explaining this.

[Actual result]:
The app doesn't load, black circle spins forever

**Comment by kdavis-mozilla** [comment]
@paulsilaghi Can you re-test.

There was during development a moment where some resources we not checked in. (See issue #137) The initial load waited until these non-existent resource where there, and thus caused the black circle to spin forever.

So a re-test will determine if you saw issue #137  or a different bug.

**Comment by paulsilaghi** [comment]
Still repro on IE11 - Win 10 x64.
https://www.youtube.com/watch?v=rN6CG1rSsyE

**Comment by kdavis-mozilla** [comment]
@paulsilaghi Thanks!

**Comment by kenrick95** [comment]
I think this is due to "Promise" not being available in any of the IEs.

![capture-promise](https://user-images.githubusercontent.com/3090380/28741985-c268bf12-7455-11e7-914d-56ad5667c260.PNG)

**Comment by mikehenrty** [comment]
Thank you for investigating this @kenrick95 .

Looking at our numbers, less than 1% use internet explorer, so I don't think this is a priority.

That said, it should be fairly easy to add a Promise polyfill to the /vendor folder to clear things up. This would at least allow IE users to see the "Browser not supported" message.
