### ISSUE TITLE
Language drop-down UI 

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1421]
[Environment]:
Windows 10:
Chrome 68, Firefox 61, latest Edge

[Steps to reproduce]:
1.Open https://voice.mozilla.org/en/new
2.Go to the language drop-down

[Expected results]:
The language drop-down should be grey and should not display the entire language name ("e.g. EN vs ENGLISH)

[Actual results]:
The down arrow is black and the language name displayed in the header of the drop-down is (e.g. ENGLISH)

**Comment by Gregoor** [comment]
@rleitan I don't quite understand in which language dropdown we'd want a short language name (afaik in none). Do you have a link to the designs for that?

**Comment by rleitan** [comment]
@Gregoor https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5b7694d3621f406ad07313d5, not sure if this is up to date

**Comment by Gregoor** [comment]
Ah, didn't realize we were talking about the header (as there are 3 language selects on that page). I guess if it's part of the design we indeed want it. Though I'm not sure whether all users know the language code of their language.
Just to make sure: @mbransn, do we want to abbreviate in the header language select? And if so, how would the dropdown look like, e.g. would it also show abbreviations or would it be wider?

**Comment by mbransn** [comment]
Thanks for the flag @Gregoor, I know it's part of the UI but I'm not convinced we should go the abbreviated route. Perhaps let's keep as full version for now and revisit this when we add the log in/sign up button (though I believe we'll still have the room).

**Comment by Gregoor** [comment]
Great, thanks!
