### ISSUE TITLE
what if only last consonant is not recorded, should it be accepted?

### ISSUE THREAD

**Issue by qdinar** [mozilla/voice-web#1425]
if reader stopped recording too early, and only the last consonant has not been recorded, but text is understandable and not ambiguous, should it be accepted?

i think, probably yes.

and i think, if it is ambiguous, due to / because other ending of the sentence may be, then no.

**Comment by kdavis-mozilla** [comment]
Confirm. If a word is cut-off, that's a "no".

**Comment by mikehenrty** [comment]
thanks kelly. closing this
