### ISSUE TITLE
Graphics issues (flicker) displayed on the listen/speak icon

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1428]
[Environment]:
 iOS 12.0

[Steps to reproduce]:
1.Open the Common Voice app with the new homepage
2.Tap the Speak area
3.Scroll down to display both areas (speak and listen)
4.Tap the Listen area

[Expected results]:
The Speak area should be compressed and the Listen area should be expanded 

[Actual results]:
Graphics issues (flicker) displayed on the listen icon while the Speak area is compressed and the Listen area is expanded

**Comment by rleitan** [comment]
Graphics issues displayed also on Play button located next to Mars and "Ready to donate your voice" in the bottom of the page

**Comment by Gregoor** [comment]
Can't reproduce on iOS 11. Can you record a video of the problem?
