### ISSUE TITLE
[Win10] The app doesn't load on Safari

### ISSUE THREAD

**Issue by paulsilaghi** [mozilla/voice-web#143]
[Affected versions]:
- Safari 5.1.7

[Affected platforms]:
- Win 10 x64

[Steps to reproduce]:
1. Open https://voice.allizom.org/

[Expected result]:
The app loads and works properly /
If the browser is not supported, there should be an error message explaining this.

[Actual result]:
The app doesn't load, black circle displayed on the homepage

[Notes]:
'Safari' browser is no longer supporter on Windows.

**Comment by mikehenrty** [comment]
Yeah, let's not spend any time on Safari for Windows.
