### ISSUE TITLE
iOS Homepage: "Back to top" is not working

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1431]
[Environment]:
iOS 12.0

[Steps to reproduce]:
1.Open the Common Voice app with the new homepage
2.Scroll down to the bottom of the page
3.Tap the "Back to top" link

[Expected results]:
The page should be scrolled to the top

[Actual results]:
Nothing happens
![ios back to tmop ink](https://user-images.githubusercontent.com/41474886/45044838-e8ea4a00-b079-11e8-8dd0-d1bde59b41e8.jpg)

**Comment by reinhart1010** [comment]
Also reproducible in Firefox Developer Edition 63 (20180917143811)

The button seems to have 2 DOM triggers, `click` and `onClick`. `click` event refers to an empty function.

![image](https://user-images.githubusercontent.com/17312341/45914606-603d1d80-be71-11e8-910e-524782becd38.png)

**Comment by Gregoor** [comment]
Works again on my mobile device, let me know if it still doesn't work on some.
