### ISSUE TITLE
Animation issues on Listen/Speak area when scrolling up/down

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1432]
[Environment]:
iOS 12.0

[Steps to reproduce]:
1.Open the Common Voice app with the new homepage
2.Scroll down to Listen area

[Expected result]:

[Actual result]:
"Speak" item is doubled(at the top of the page) while scrolling
Background a
[video-1536070678.zip](https://github.com/mozilla/voice-web/files/2349456/video-1536070678.zip)
nimation pieces displayed behind the Listen/Speak icons

**Comment by Gregoor** [comment]
Also don't get this one on iOS 11. I'll see if the iOS Emulator on Mac OS does the trick.
