### ISSUE TITLE
Homepage copy updates

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1433]
@Gregoor some slight copy layout updates for you on desktop, see below:

- [x] Increase max-width for `h1` to allow for 3 lines of text. 520px should do?
- [x] Combine the last two lines of `div.description` -- appears there is an errant `<br>` between them?

### Current:
![current-copy](https://user-images.githubusercontent.com/18686986/45062722-2392b900-b05f-11e8-860d-003220bb8937.png)

### With updates:
![updated-copy](https://user-images.githubusercontent.com/18686986/45062728-28576d00-b05f-11e8-9b86-95fb7be77127.png)

**Comment by mbransn** [comment]
@Gregoor I caught some additional things here:

- [ ] On the In Progress Languages version of the homepage, the last paragraph of copy is still subject to that pesky `<br>`. See first image.
- [ ] Can we fine tune all homepage versions and left align the copy blocks with the corresponding graphs below? See second image.
- [ ] On the In Progress Languages version of the homepage, please left align the Mars CTA with the graph above. See third image.

### Pesky break on alt-homepage:
<img width="1293" alt="last-paragraph-combine" src="https://user-images.githubusercontent.com/18686986/45122707-7df05000-b119-11e8-8eaa-cbfb4f5cf8a4.png">


### Copy alignment on all homepage versions:
<img width="1322" alt="copy-alignements-global" src="https://user-images.githubusercontent.com/18686986/45122946-2e5e5400-b11a-11e8-9195-3e1a6834f8fc.png">

### Left align language request CTA on alt-homepage:
<img width="1296" alt="mars-cta" src="https://user-images.githubusercontent.com/18686986/45122800-c60f7280-b119-11e8-860f-ce1e5080469b.png">

**Comment by Gregoor** [comment]
Thanks for that feedback, it made me rethink how I layout the stuff (which I did quite naively previously) and I think it looks much nicer now :)
