### ISSUE TITLE
All dropdowns hover vs. active UX/UI

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1434]
@Gregoor our dropdowns (all of them) should have distinct states: hover and active. 

[Hover](https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5b842dc0aa1c18057a22bd66) indicates that an element is clickable (eg; goes grey); 

[Active](https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5b842dc0b235ad47e3784741) provides the dropdown list _when_ clicked. Our current interaction of immediate list reveal on hover is very jumpy, distracting and doesn't leave the user much option to choose their adventure. 😉  

Plus, this will create more parity across viewports (all dropdowns are click/tap activated).

**Comment by Gregoor** [comment]
@mbransn I'm getting mixed signals here. When we talked about dropdowns before and not reimplementing defaults, the argument that convinced me was that we'd want something more immediate (/hoverable) for stats and the fact that the native dropdown just can't provide that.

>Active provides the dropdown list when clicked.

This seems to me to be a direct contradiction of that. So we do want native dropdown behavior now? Tbh I'm still in favor of the hover interaction, we could add a transition to make less jumpy?

**Comment by mbransn** [comment]
@Gregoor apologies for mixed signals (human error abounds apparently). That said, after having a think on this: Yes. Please make dropdowns active on click or tap.

Hope this helps, thank you!

**Comment by mbransn** [comment]
@Gregoor and re this: "Tbh I'm still in favor of the hover interaction, we could add a transition to make less jumpy?" The hover interaction as it is currently removes control from the user and forces viewing content they may not be ready for or prefer to see. The only way to know _for sure_ is to test this. At the moment, I do not think that should block our progress.

**Comment by mbransn** [comment]
FWIW I've double checked this with @georai as well, we're in agreement. Please build all dropdowns with separate hover and active states. Thank you. :)
