### ISSUE TITLE
Voices online is higher for one language than for all combined

### ISSUE THREAD

**Issue by danielsjf** [mozilla/voice-web#1438]
Not sure if we can already post issues on the new site. 

When I check the voices online now, it says 5 for all languages and 17 for Dutch by itself. There might be a caching issue.

**Comment by Gregoor** [comment]
🙈 yeah, very likely a caching issue. But I guess we could rewrite this to be more resilient towards these kinds of issues

**Comment by Gregoor** [comment]
https://github.com/mozilla/voice-web/commit/697222f2aa17ab889c0bed553f1ca3735456ca5c

consul is now used as a cache, so all instances are running on the same cache
