### ISSUE TITLE
Add custom messages language based

### ISSUE THREAD

**Issue by Mte90** [mozilla/voice-web#1446]
As Firefox already do for about:home can be helpful for a language to show specific messages to the users.
Like to promote events or updates, or a simple engagement for social networks of the local community.

**Comment by nukeador** [comment]
We have the ability now to surface banners with CTAs, as we did with the survey.

**Comment by Mte90** [comment]
There is a guide about how to use it for the community?
Also screen where that banner will be shown?

**Comment by nukeador** [comment]
Currently has been only used to surface a survey and the new goals feature for English. There is no procedure to request content there at the moment.

Having said that, if you community has a need, I would recommend to work with us to understand the problem and define the need and if we need to use that space to promote anything we can evaluate it. We can work on that document you had or you can open a discourse topic to frame the conversation.

Thanks!

**Comment by Mte90** [comment]
The idea at the basic was to reach the contributors of a language that now is impossible to do it.

**Comment by MichaelKohler** [comment]
@Mte90 can you start a Discourse topic?

**Comment by Mte90** [comment]
https://discourse.mozilla.org/t/how-to-reach-contributors-by-languages-for-communications/55103
