### ISSUE TITLE
The Listen icon colors should be more intense

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1447]
[Environment]:
Windows 10 : Chrome 68, Firefox 61

[Steps to reproduce]:
1.Open https://voice.mozilla.org/en/new
2.Observe the "Listen" icon colours

[Expected result]:
The colours should be more intense
![2018-09-11_14h19_26](https://user-images.githubusercontent.com/41474886/45365407-22c0d080-b5e5-11e8-83d5-2d51955a8339.png)

**Comment by rleitan** [comment]
@mbransn @grailean what do you think?

**Comment by MichaelKohler** [comment]
Looks pretty green to me now.
