### ISSUE TITLE
[Mac] Background image flashes on Safari

### ISSUE THREAD

**Issue by paulsilaghi** [mozilla/voice-web#145]
[Affected versions]:
Safari 10.1.1

[Affected platforms]:
Mac OS X 10.12.5

[Steps to reproduce]:
1. Open https://voice.allizom.org/
2. Go to the "Speak" page

[Expected result]:
The app loads and works properly /
If the browser is not supported, there should be a notification message on the homepage explaining this.

[Actual result]:
The app loads, a broken (flashing) animation is displayed on the homepage.
"Your platform is not supported" message displayed only on the "speak" page.

**Comment by mikehenrty** [comment]
We don't support Safari, so the error message is correct. We don't tell people on the homepage this is not supported because we want them to be able to read and listen there. Once they get to the speak page, that's a perfect time to direct them into the iOS app (or better, install Firefox!).

@paulsilaghi can you tell me more about the broken flashing animation? which animation is that?

**Comment by kdavis-mozilla** [comment]
@mikehenrty @paulsilaghi Just loaded https://voice.mozilla.org/ on Safari 10.1.1 on OS X 10.11.6 and saw no "flashing animation" other than the standard startup screen.

**Comment by kdavis-mozilla** [comment]
@paulsilaghi Can you give further details on the "flashing animation"?

**Comment by paulsilaghi** [comment]
the top animation the flashes over the navbar - https://www.youtube.com/watch?v=BzNm6cg1-nE

**Comment by kdavis-mozilla** [comment]
@paulsilaghi Wow as we have the same Safari version it's down to OS X 10.11.6 vs 10.12.5!?

**Comment by paulsilaghi** [comment]
I can also reproduce this on OS X 10.11.6, Safari 10.1.1 (11603.2.5), MacBook Pro Retina.

**Comment by paulsilaghi** [comment]
Everything's fine on iMac OS X 10.12.6, Safari 10.1.2 - so I guess it's a retina related issue.

**Comment by kdavis-mozilla** [comment]
@paulsilaghi Really strange! We're on basically the same machine but see different behavior.

I'm on a MacBook Pro (Retina, 15-inch, Mid 2014) with  OS X 10.11.6 using Safari 10.1.1 (11603.2.5) and I don't see that flashing.

What graphics card do you have on your MacBook Pro Retina? I've a Intel Iris Pro + NVIDIA GeForce GT 750M.

**Comment by paulsilaghi** [comment]
MacBook Pro (Retina, 15-inch, Late 2013), Intel Iris Pro 1536 MB

**Comment by kdavis-mozilla** [comment]
It doesn't look like we'll be able to solve this as it appears to be some deep MacBook Pro Retina issue.

So I'd motion to move this to "won't fix".

@mikehenrty What do you think?

**Comment by mikehenrty** [comment]
Won't fix it is.
