### ISSUE TITLE
Repetition of sentences (only ~50 unique sentences) with Welsh

### ISSUE THREAD

**Issue by GruffPrys** [mozilla/voice-web#1458]
Hi, myself and a few others are experiencing the problem described by rotemdam #1225, but with Welsh.

After relatively few recordings we're starting to see the same prompts over and over again. Occurs on Android and Win PC. In Chrome on Android I now see a blank screen for the 'Speaking' tab.

I skipped through them quickly until I stopped seeing new sentences, and saw only ~50 prompts in total. Here they are:

* A oes rhywbeth ar goll o'r pedwar pwynt bwled?
* Ai dyma'r ffurflen gywir?
* Allan nhw eistedd rownd y bwrdd a chael pryd iawn.
* Aros funud.
* Beth sy raid i fi wneud nawr i sortio fe mas?
* Beth sy'n bod?
* Beth ydy cadair Eisteddfodol?
* Beth ydy dy hoff bwnc?
* Beth yw cyfraith Hywel Dda?
* Beuno, trotscïaeth, peipen, cerrig llwydion, ffawt, tangnefedd, fwyell, hoe
* Ble mae pobl yn dod yn y gadwyn fwyd fel arfer?
* Bydd angen yr un sgiliau ar bob safle ond ar raddfa uwch.
* Bydd hi'n troi'n gymylog eto heno.
* Cafodd hyn ei ddangos yn erbyn yr Alban a Ffrainc.
* Cafodd y corff ei ddarganfod ger siop Tesco yn y ddinas ddydd Sul.
* Cafodd y ffordd ei chau yn dilyn y digwyddiad.
* Cafodd y rheithgor eu hanfon adref ddydd Gwener oherwydd salwch un aelod.
* Chwaraea fiwsig hapus 
* Chwaraea fiwsig roc
* Doedden nhw chwaith ddim yn fodlon dweud beth oedd gwerth y sustem sain.
* Dw i eisiau bwyd.
* Dw i wedi colli fy nhocyn.
* Dw i'n cefnogi Wrecsam.
* Dw i'n ofni pryfed cop.
* Dywedais i’r drefn wrtho.
* Faint o oriau fydd plentyn yn gweithio pob dydd?
* Faint o'r gloch fydd y bws nesaf yn mynd heibio?
* Ga i fy mhres pensiwn, plîs?
* Ga i siarad â Catrin, os gwelwch yn dda?
* I keep on seeing the following sentences:
* Mae fy chwiorydd yn dal i fyw a gweithio yn Llundain.
* Mae fy nain yn wyth deg heddiw.
* Mae gen i gath.
* Mae'n anhygoel.
* Mae'n ardderchog!
* Mae'n chwil.
* Nac ydw.
* Nid hwnna – y llall.
* Oni byddi gryf, bydd gyfrwys. 
* Posibiliadau damcaniaethol yw'r rhain ar hyn o bryd. 
* Prosser, llaeth, llaw, cegddu, stow, troell, teitl, Moi
* Roedd y Dreigiau ddwy gôl ar y blaen wrth droi, ac felly yr oedd hi.
* Sut mae eich gweithredoedd yn effeithio ar bobl eraill?
* Y broblem fawr yw bod Llundain yn rhy ddrud.
* Yn anffodus roedd rhaid i mi fynd nôl i ail-sefyll.

Is this a problem with caching, or are there simply not enough Welsh language prompts?

It's worth noting that I don't have this problem when I'm submitting English recordings, but I do encounter the same familiar Welsh sentences when using a fresh machine and browser to access the website.

**Comment by GruffPrys** [comment]
Just to add to this, one longterm user does seem to be able to record sentences bit find on my list above. However, every other contribution I've heard recently whilst validating have been from the limited list.

**Comment by danielsjf** [comment]
There are some subgroups. I think training test and validation. Training is the largest and the other two are smaller.

Therefore if the number of sentences is small, one of the groups can be small. An option is to contribute more sentences.

**Comment by GruffPrys** [comment]
@danielsjf Thanks for getting back to me.

I've just checked in https://github.com/mozilla/voice-web/tree/master/server/data/cy and there are over 1200 sentences for Welsh, so something isn't right if I'm only getting prompted to record ~50.

I've since validated sentences by others who don't have this problem (their recordings are not from the set of ~50 I listed above) which indicates that this is not affecting all contributors.

If my user profile is in some kind of testing or validation group, how do I get myself out of it?

**Comment by danielsjf** [comment]
I thought it was something similar to #1225. Now of course it could be another error as well. Probably some of the developers have to weigh in on this.

**Comment by danielsjf** [comment]
Apart from this, the goal is to remain in the same group. In order to improve the results of the STT engine, there should be a clear separation between test, training and validation. This means different sentences and different speakers.

Keep in mind that it is also better to have many different sentences. Somewhere else in the issues, it is mentioned that a couple rereads are fine, but after that the added value is low. With 1200 sentences, this means roughly 1200x3.7x5 = 6 hours of recordings. If you reason backwards, for Welsh this means that you currently have circa 8.5 reads per sentence on average. Time to increase the number of sentences I would say.

**Comment by jf99** [comment]
Yesterday I recorded some German sentences. After ~270 recordings, no more sentences were shown. The German corpus has 5803 sentences. So a bucket seemingly has the size of ~4.6 % of all sentences. Is the data split into 21 or 22 buckets? That seems a bit much.

If you visit the listen or record page **now**, there are still exactly the same sentences as yesterday.

**Comment by Gregoor** [comment]
The bucket problem seems to indeed also exist in german, thanks for reporting that. You're spot on, train only has 280 sentences. Here's some of my observations:
- (the commit)[https://github.com/mozilla/voice-web/commit/9ef084a5ee61b3d36c7ae86a5c9039e894790be2] that brought in a simpler splitting method is from May
- yet only the sentences added in the last month show that ideal split (60% in train), before the number of sentences in train are extremely low
- in the spirit of works on my machine: the split is correct when doing a local import

More sentences really would help for mitigating this problem.

**Comment by GruffPrys** [comment]
This is the PR I mentioned above:

https://github.com/mozilla/voice-web/pull/1480

If you could incorporate those additional sentences I'd be happy to test to see whether or not they make any difference.

**Comment by Gregoor** [comment]
Thanks for getting those new sentences in!

Another thing I'm pondering is removing the bucket restrictions for now (i.e. every user would be served every unused sentence). I share your concern about the current lack of sentence diversity in the main set (train) and that seems worse to me than having no split at all. But I'm no ML expert, so I'll talk with some people about it and will get back to you.

**Comment by GruffPrys** [comment]
Great, thanks for merging them in!

Any idea when they should start to appear on the server?

As to the bucket restrictions, I think there's a danger at present that users could be discouraged from contributing if they run out of fresh sentences to record. What proportion of users get assigned to testing? I find it strange that my Irish co-worker and I were both assigned to the test bucket (we were on the same wireless network if that plays a part). It's also strange that I seem to be assigned to the test bucket on fresh devices and browsers.

**Comment by Gregoor** [comment]
I'll do a deploy later today!

There should be a 60% chance for users to land in the train bucket, so the chance isn't too slim. But across multiple devices it indeed starts to get weird. I'll investigate that part of the equation as well.

**Comment by jf99** [comment]
> More sentences really would help for mitigating this problem.

Well, for German, we **already have** more than [10,000 sentences](https://github.com/jf99/voice-web/tree/german/server/data/de) waiting to be used. It's just that nobody has proofread them yet (apart from me, but I also wrote them and therefore probably didn't spot everything). So if we're talking about removing restrictions, maybe consider to remove the proofreading restriction? I'm going to make future PRs anyway when I spot mistakes in the corpus.

**Comment by Gregoor** [comment]
Huh, so I imported the new sentences on production and the split was as intended, e.g. german got 100 sentences in total of which 60 went into train (same for Welsh, the numbers just aren't as round which is why I took german as an example).

**Comment by GruffPrys** [comment]
Ok, so I guess 300 new Welsh sentences should result in 180 new training sentences. That should be enough for it to be obvious in the first set of five prompts.

I'll test it tonight and report back.

**Comment by Gregoor** [comment]
Great, thanks for the feedback. It's immensely helpful!

**Comment by GruffPrys** [comment]
Good news - I'm seeing fresh recording prompts!

We'll have to make sure to add further sentences as 230 for the testing bucket might still not be enough, but for now it should prevent contributors from quickly running out of material.
