### ISSUE TITLE
Let clip saving errors bubble up

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#1459]
Didn't happen on production in the last time, but we noticed that those errors are caught too early.

**Comment by mritunjaygoutam12** [comment]
I am working on this.

**Comment by mritunjaygoutam12** [comment]
In previous PR I separated the error message for confirm(msg) to identify is error ocuurs at server or on client's network. I am seeking for some better Idea for doing this. Any suggestions?
