### ISSUE TITLE
'Tap to play/stop' text is crossed out by black border

### ISSUE THREAD

**Issue by paulsilaghi** [mozilla/voice-web#146]
[Affected versions]:
- Chrome 59, Opera 45
- doesn't reproduce in Firefox 54

[Affected platforms]:
Win 10

[Steps to reproduce]:
1. Open https://voice.allizom.org/
2. Go to the "Speak" page
3. Complete 3 recordings

[Expected result]:
"Review recordings" page displayed properly.

[Actual result]:
'Tap to play/stop' text is crossed out by black border
![tap to play stop chrome](https://user-images.githubusercontent.com/29535384/27293046-f3f9133a-551d-11e7-835a-016e867538c2.png)

**Comment by mikehenrty** [comment]
fixed in https://github.com/mozilla/voice-web/commit/8203de2f4f9e618913c946d53d26d3143a9ddac1
