### ISSUE TITLE
Listen is not working on Safari

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1463]
[Environment]:
Android: Firefox, Chrome
iOS 11.4.1. Firefox , Chrome, Safari
Common Voice app

[Steps to reproduce]:
1.Open https://voice.mozilla.org/en/new
2.Go to Contribute -> Listen section
3.Tap Play button

[Actual result]:
The button is not actionable

**Comment by Gregoor** [comment]
Works on Android for me, I think this is a Safari bug

**Comment by rleitan** [comment]
I reproduced also on Common Voice app on iOS 11.4.1

**Comment by Gregoor** [comment]
I fixed this by reverting #1285, will be on production later today.

**Comment by rleitan** [comment]
I confirm it's fixed on Android: Chrome browser and on  iOS: Firefox, Chrome, Safari and Common Voice app
