### ISSUE TITLE
Common voice website is not displayed on older iOS versions (10.0.2)

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1464]
[Environment]:
iOS 10.0.2

[Steps to reproduce]:
1.Open https://voice.mozilla.org/en/new

[Actual result]:
The page is not displayed

**Comment by MichaelKohler** [comment]
Recording via mobile Safari on iOS is now implemented, and the native app is being decommissioned. https://discourse.mozilla.org/t/updates-to-common-voice-for-ios/58909
