### ISSUE TITLE
Clip behaviour merges in the next one after replay

### ISSUE THREAD

**Issue by danielsjf** [mozilla/voice-web#1467]
Sometimes I didn't understand a clip so I play it again. Since the clip is already played, both yes and no are activated. If I click one of both, the first clip still plays when the next one is already visible.

The bigger problem is that when the first clip ends, the buttons are again visible. I can therefore click yes or no for the second clip without ever listening to it.

I think the right behaviour here is that as soon as yes or no is clicked, the clip must be stopped and the buttons have to be reset.

**Comment by MichaelKohler** [comment]
It seems that going back is not possible anymore, so closing this one.
