### ISSUE TITLE
'Submit' recordings button is cropped

### ISSUE THREAD

**Issue by paulsilaghi** [mozilla/voice-web#147]
[Affected versions]:
- Firefox 54
- doesn't reproduce in Chrome 59

[Affected platforms]:
- Win 10 x64

[Steps to reproduce]:
1. Open https://voice.allizom.org/
2. Go to the "Speak" page
3. Complete 3 recordings

[Expected result]:
"Review recordings" page displayed properly.

[Actual result]:
'Submit' recordings button is cropped

![submit button cropped](https://user-images.githubusercontent.com/29535384/27293287-9daf6b22-551e-11e7-9691-7871bb8a3f66.png)

**Comment by mikehenrty** [comment]
I just checked on Windows 10, Firefox 54, and this looks fixed.
