### ISSUE TITLE
Sentences from another dataset appears

### ISSUE THREAD

**Issue by phobosjr** [mozilla/voice-web#1476]
Hi

We noticed an issue on the Common Voice interface yesterday at 18h, sentences of the French dataset appeared on the kabyle view, we checked our global corpus (Kabyle) and no sentence in French on the Kabyle corpus.

[Environment]:

Android : 5.1.1
Chrome App : 65.0.3325.109 FR  
Connection type : 4G 

![screenshot_2018-09-19-18-19-42](https://user-images.githubusercontent.com/18676491/45816431-e7f12380-bcdb-11e8-97f5-5d30cea408bb.png)
![screenshot_2018-09-19-18-23-32](https://user-images.githubusercontent.com/18676491/45816432-e7f12380-bcdb-11e8-8a54-881f4021a06a.png)
![screenshot_2018-09-19-18-23-36](https://user-images.githubusercontent.com/18676491/45816433-e7f12380-bcdb-11e8-8998-05e18bb28d67.png)
![screenshot_2018-09-19-18-23-44](https://user-images.githubusercontent.com/18676491/45816434-e889ba00-bcdb-11e8-884d-2235d7d361a6.png)
![screenshot_2018-09-19-18-23-48](https://user-images.githubusercontent.com/18676491/45816435-e889ba00-bcdb-11e8-8896-55146a403f04.png)

**Comment by mikehenrty** [comment]
@Gregoor any ideas what might be happening here?
