### ISSUE TITLE
Hard-coded strings in English

### ISSUE THREAD

**Issue by flodolo** [mozilla/voice-web#1490]
It looks like there are a few hard-coded strings:
* Voices Online Now (title above the graph)
* "Today's progress" and "Help us get to X" (hover on the mic or play images)

**Comment by rprys** [comment]
Any progress on this issue? - it looks ugly o non English web sites.

**Comment by Gregoor** [comment]
Thanks for the ping! 👍

**Comment by rprys** [comment]
You're welcome! :-)
