### ISSUE TITLE
Statistics per language

### ISSUE THREAD

**Issue by danielsjf** [mozilla/voice-web#1491]
As already mentioned on the side in #1381, it would be helpful to have a statistics page for a number of reasons.
* We might spot outliers like in #1458 more quickly. 
* It helps to educate people where the important contributions are. 
* It is quite useful as an initial data check for people that will use the data.

As you can see below, some of these statistics are already available elsewhere. This is not an exhaustive list. Rather some things I thought of at the moment that could be interesting.

- General statistics
  - Number of sentences
  - Number of hours recorded
  - Number of hours validated
  - Number of hours invalidated
  - Number of speakers
  - Number of accents
  - Individual word count (above 5000? Could be biased for some languages with combined words)
  - Number of recordings not in the sentence data (these are the corrected sentences)
- Ratios (this is mostly here to educate)
  - Average number of reads per sentence (plus a recommendation of it being below three?)
  - Percentage of validated recordings by the largest contributor (lower than 10%?)
  - Percentage male/female
  - Percentage per age group
- Table with same information as above, but grouped by subset (train, validation and test)

**Comment by danielsjf** [comment]
Only now saw #1410. Searched for statistics in the issue list. However, it can still be good to keep a full list here as the other one discusses a rather specific statistic.

**Comment by Gregoor** [comment]
I quoted your thoughts over in #262. I think it's best to capture our related thoughts in that issue.
