### ISSUE TITLE
Please explain (or remove) the "Leaderboard Visibility" string for l10n

### ISSUE THREAD

**Issue by TonnesM** [mozilla/voice-web#1495]
A recent changeset introduced the "Leaderboard Visibility" string. Asking around on IRC did not help making clear whether this was about the visibility _of_ the leaderboard, or a user’s visibility _on_ it. All I got back was the feature is not implemented yet, and I could not find recent issues clearly elaborating on the meaning.

Searching for "leaderboard" on GH results in e.g. issue #3, which implies a leaderboard is to be introduced all right, but that still doesn’t tell whether the option is about a user’s visibility _on_ it, although that would make the most sense.

Please elaborate on what is it about, or remove the string for now since it isn’t used yet. Also please include a l10n or context comment when used eventually, if possible. At this point, a number of locales seem to use "visibility _of_ the dashboard", which may be wrong now and in the future when left untouched.

**Comment by Gregoor** [comment]
I'm sorry for the confusion, that one's on me. There's a dilemma here; we want to launch new features in every language at the same time (and hence get the strings into Pontoon early), but it can be hard to understand what features are about before they launched. So thanks for raising this issue, it's sometimes hard to me to anticipate which string is unclear (the curse of knowledge).

Here's a screenshot of the dashboard:
![dashboard stats_01 1](https://user-images.githubusercontent.com/4051932/46146929-4c742b80-c264-11e8-95fe-80871639e096.png)

The visibility flag would control whether a user shows up in those leaderboards.

**Comment by TonnesM** [comment]
Thanks, clear. Would you know of any way to inform localizers? If not, we can probably rely on this issue to be findable either on GH or using a search engine, and the issue could be closed.

**Comment by mikehenrty** [comment]
cc @peiying2, as oversees the localization community for Common Voice, and can point contributors at this issue if people have questions. I'll close this issue for now, but we can re-open if people have further questions.
