### ISSUE TITLE
Bring back audio normalization

### ISSUE THREAD

**Issue by est31** [mozilla/voice-web#1498]
In order to hotfix #1463, the PR to implement audio normalization #1285 has been reverted. I think this was meant as a temporary measure until a good fix for that issue is found.

In the PR thread, I've [suggested](https://github.com/mozilla/voice-web/pull/1285#issuecomment-422404670) a possible proper fix for #1463 that would work with normalization enabled.

Just filing an issue because the discussion is already 2 weeks old and I didn't want to forget about it.

**Comment by rugk** [comment]
Or can't you just exclude Safari then from audio normalization?

**Comment by est31** [comment]
@rugk that's possible yes, but such an exclusion should best be tested before it's deployed, So in all cases we'd need someone who tests the new solution on safari. Also, I'd argue that it involves actually more code than just adopting the package, together with a worse experience for safari users, so I'd prefer to bring normalization to safari users as well.

**Comment by est31** [comment]
I've made a PR #1524. Please anyone with safari test it whether it now works! I don't have safari so can't test but I've tested it on Firefox and there it does work.

**Comment by Gregoor** [comment]
@est31 yeah I think that'd be fair, we (*you) tried to support it, but it's not making it easy.

**Comment by est31** [comment]
For reference, this was the commit that removed it again: 6644a127340ba1fb89321fe391ee626210fa2a04

**Comment by MichaelNMaggs** [comment]
If someone has time, it would be useful to integrate this into the main website. There are a non-trivial number of recordings that I am having to reject because, even with the sound fully turned up on my laptop, I can't be quite sure that they are saying exactly what is written

**Comment by MichaelNMaggs** [comment]
Linking to Discourse: https://discourse.mozilla.org/t/normalized-samples/38885

**Comment by ftyers** [comment]
Closing this as stale.
