### ISSUE TITLE
Severe performance issues in Chrome and Firefox

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#150]
The the website slows down my system to a crawl when running in Chrome. Turning on paint flashing shows that the entire page is re-rendered and CPU usage when idle is around 10-25%. I suspect it may be the "Click here to help me learn animation."

Firefox is around 40%-50%, just showing the main voice.mozilla.org page and not interacting at all.

**Comment by mikehenrty** [comment]
This is extremely valuable info. I'll try to do something here before next week.

**Comment by mikehenrty** [comment]
p1, to investigate

**Comment by mikehenrty** [comment]
@mbebenita can you tell us if this is still happening?

**Comment by kdavis-mozilla** [comment]
@mbebenita As the Robot's s"speaking" is now gone can you confirm if this is still happening?

**Comment by mikehenrty** [comment]
We've gotten rid of all animations on the homepage (robot speaking, pulsating buttons, spinning wheel, etc. On linux at least this appears to be solved. I'm closing for now, but let's re-open if this is still happening on osx.
