### ISSUE TITLE
How to Run this application

### ISSUE THREAD

**Issue by swathionchip** [mozilla/voice-web#1500]
Hi All,

I downloaded the voice-web.could you please tell me the procedure how to use this one in Localhost.

Thanks in Advance.

Regards,
Swathi.

**Comment by mikehenrty** [comment]
Hi @swathionchip, did you see our setup notes?

https://github.com/mozilla/voice-web/blob/master/CONTRIBUTING.md#setup

**Comment by immohsin** [comment]
HI @mikehenrty I have setup the project and when i go to recording page i get this error `/api/v1/user_clients/d1adc6e5-cb20-4a58-b630-0f42a0e52117 The specified bucket does not exist NoSuchBucket: The specified bucket does not exist`.

Can you please help me with that?

**Comment by Gregoor** [comment]
@immohsin sounds like you might not have setup S3? Here's the docs for that: https://github.com/mozilla/voice-web/blob/master/docs/HOWTO_S3.md
