### ISSUE TITLE
Duplicate clips for listen validation

### ISSUE THREAD

**Issue by bakwc** [mozilla/voice-web#1505]
Sometimes i receive the same sentence that I already validated just before (last sentence in 5 sentence batch appears as a first sentence in a new batch).

**Comment by jf99** [comment]
Exactly what I described in #1362, I think.

**Comment by mikehenrty** [comment]
i agree with @jf99 that this is a duplicate of #1362 (thanks for noticing). let's use that one to track this problem.

thanks for the report @bakwc !
