### ISSUE TITLE
Signficant gender imbalance in sample population

### ISSUE THREAD

**Issue by NAHarris** [mozilla/voice-web#1508]
Reviewing contributions recently, I noticed that every single sample I reviewed, without exception, was spoken by a male speaker. If this reflects the recent contributions to the entire dataset, I think the under-representation of female speakers has the potential to significantly impact speech recognition performance for end-users of the finished system.

While this is not a programming issue, I think it's clear that something should be done to remedy, or at least quantify, this problem.

**Comment by jf99** [comment]
I agree. If Mozilla is doing advertising somewhere, they should target a female group. Otherwise we will only have nerds that read about Common Voice on some tech-site.

**Comment by mikehenrty** [comment]
Let's use the discourse thread to discuss this, since it's not a code issue at the moment.

https://discourse.mozilla.org/t/gender-breakdown-of-english-language-dataset/32483/3
