### ISSUE TITLE
Scroll bar appears even though the page is fully visible and doesn't need to be scrolled.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#151]
![image](https://user-images.githubusercontent.com/311082/27297222-e213eaea-54d8-11e7-9722-91f11a58179c.png)

**Comment by mikehenrty** [comment]
This is done on purpose to avoid nasty full page reflows when switching between pages that do overflow and those that don't. This is not an uncommon web practice as the superfluous scrollbar is a small price to pay for the jank it avoids.
