### ISSUE TITLE
French sentences displayed when recording Kabyle sentences

### ISSUE THREAD

**Issue by mozillakab** [mozilla/voice-web#1527]
French corpus is displayed when recording Kabyle sentences.

Some kab users are facing this issue from time to time when using Chrome (French) on Android or Windows.
Mostly on Android with a slow connection.

No user reported this issue when using Firefox Kabyle even with a low connection.

![44319807_1948577771885218_7731316259538599936_n](https://user-images.githubusercontent.com/7033740/47255944-f2841180-d46f-11e8-8d0d-d2bbe4538f8d.jpg)

**Comment by lissyx** [comment]
What about Firefox French with slow connection?

**Comment by belkacem77** [comment]
Need to test, but i should make my connection slow.

**Comment by lissyx** [comment]
There should be devtools support now to emulate slow / loosing packets networks

**Comment by lissyx** [comment]
@belkacem77 Ok, carefully looking at your screenshot, I kind of see "/fr" at the end of the URL, so it'd be expected to see french sentences to read / record ; and thus the kabyle UI is kind of strange ?

**Comment by belkacem77** [comment]
@lissyx  I tried to reproduce the same scenario but nothing for now. I'll try to emulate using devtools as  you suggested.

**Comment by belkacem77** [comment]
This is the scenario.
The user connected to CV using Chrome French. He accessed to languages and clicked on Kabyle.
The UI displays in kab but the URL tool some time to switch to Kabyle. Then he got a French Sentence.
No user reported me the same behavior using Firefox.

**Comment by MichaelKohler** [comment]
Is this still happening?

**Comment by mozillakab** [comment]
@MichaelKohler A student who is working on the kab corpus as a part of the work given to him (topic for his engineering project) reported some French recorded Sentences withing the kab voice dataset. I'll check again with him.

**Comment by mozillakab** [comment]
@lissyx Mustapha Kamel reported again some French Sentences in the recorded kab dataset.

**Comment by rileyjshaw** [comment]
We have released a fix to this issue. Closing for now, but please let us know if you see anything similar in the future.

Thanks for the report!
