### ISSUE TITLE
Inconsistent padding in wordmark

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#153]
![image](https://user-images.githubusercontent.com/311082/27297290-1b4b27ec-54d9-11e7-8a45-ed3cd845388b.png)

It also appears in the footer,

![image](https://user-images.githubusercontent.com/311082/27297317-389d063a-54d9-11e7-86b7-52782146f6b9.png)

**Comment by mikehenrty** [comment]
we need to add 1 or 2 pixels to padding on "Common Voice" to follow style guide

**Comment by mikehenrty** [comment]
we need to add 1 or 2 pixels to padding on "Common Voice" to follow style guide
