### ISSUE TITLE
Left side of the background image doesn't have a smooth curve like the right side.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#154]
![image](https://user-images.githubusercontent.com/311082/27297423-a8f04154-54d9-11e7-91e1-37840a87eed1.png)

![image](https://user-images.githubusercontent.com/311082/27297410-9affb214-54d9-11e7-8dfb-3e7933a3449e.png)

Also, the distance is not equal on both sides.

**Comment by mikehenrty** [comment]
I'm pretty sure this was done on purpose by the designers, and I don't mind it. Closing as WONTFIX.
