### ISSUE TITLE
if a syllable is read incorrectly and then immediately corrected in a recording, should it be voted as correct?

### ISSUE THREAD

**Issue by qdinar** [mozilla/voice-web#1543]
.
off-topic: i have not tried to leave textarea here empty. i put a dot here. now i see it is a comment and i think probably it was possible to leave it empty, and there would probably be just no comment instead of this. and i cannot delete this comment now, only edit.

**Comment by Gregoor** [comment]
@kdavis-mozilla might have an answer for this

**Comment by MichaelKohler** [comment]
https://discourse.mozilla.org/c/voice/239

**Comment by qdinar** [comment]
is it a forum? this link opens a list of items (topic titles). when i tried to search for "corrected" i have seen some items that look as on topic, but i have not checked their contents yet. should not you provide a better link?

**Comment by MichaelKohler** [comment]
Yes, that's a forum, I should have added some text and not just the link, sorry. You can use the same credentials to log in as you are using on voice.mozilla.org. There might not yet exist an appropriate topic.
