### ISSUE TITLE
Charts Ui enhancements

### ISSUE THREAD

**Issue by grailean** [mozilla/voice-web#1548]
@Gregoor 
- Too much space between labels and numbers.
https://www.dropbox.com/s/7a9z6gu9j6j483s/Screenshot%202018-11-05%2009.51.23.png?dl=0

- On hover the text style is different, also the line of the hover is missing.
https://www.dropbox.com/s/ytgy4tnggkatfcb/Screenshot%202018-11-05%2009.53.30.png?dl=0

**Comment by MichaelKohler** [comment]
This looks good to me now. Feel free to reopen if I looked at the wrong stuff as the screenshots are not available anymore.
