### ISSUE TITLE
Gradient overlay looks a bit strange, since it doesn't always overlay the background image

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#155]
![image](https://user-images.githubusercontent.com/311082/27297536-0dff9ca2-54da-11e7-85b7-9f18225cfd2c.png)

**Comment by mikehenrty** [comment]
Those transparent backgrounds are always there in case something non-white goes behind the nav (which can happen in a few cases). Any ideas for a better approach @mbebenita ?

**Comment by kdavis-mozilla** [comment]
@mbebenita Ideas?

**Comment by mikehenrty** [comment]
This looks fine for now.
