### ISSUE TITLE
Voice Quality

### ISSUE THREAD

**Issue by aawaheed** [mozilla/voice-web#1552]
Hi,
very interesting project. Just a small feedback. As I was listening and verifying voice sample, I stumbled across to voice samples which were very low quality (that is hard to listen as spoken with low pitch). They were correct however I wish I could give some rating to it so only clearly heard samples can be used?

Thanks

**Comment by flyingpimonster** [comment]
As long as they're correct, they should be in the dataset. We *want* the resulting models to understand low-quality audio.

**Comment by aawaheed** [comment]
Thanks. That makes sense. We can close this issue
