### ISSUE TITLE
Invalid sentences/garbage in Welsh Sentences data, along with copyrighted data

### ISSUE THREAD

**Issue by cwd24** [mozilla/voice-web#1554]
Creating a new issue, as I'm unable to reopen #1523 which was closed prematurely.

A response was provided that did not answer all issues raised. As far as I'm aware:
1. The Wikipedia content has not been cleared for inclusion (derived work of CC-BY-SA).
2. Two files consist of content that does not have any natural valid sentence and should be removed (teitlau_wicipedia.txt and paldaruo.txt).

Therefore, the following three files should be removed:
- cwestiynau_wicipedia.txt
- paldaruo.txt
- teitlau_wicipedia.txt

**Comment by Gregoor** [comment]
I've reopened #1523. Let's keep the discussion going there, to make it easier to follow along
