### ISSUE TITLE
Inconsistent footer, when compared to Mozilla footer.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#156]
![image](https://user-images.githubusercontent.com/311082/27297566-2f4c7088-54da-11e7-9019-5cd7b71c0e76.png)

vs

![image](https://user-images.githubusercontent.com/311082/27297570-37bc7ed4-54da-11e7-9fdd-20cecf48f43b.png)

In particular, the font is not correct and the padding / spacing is off.

**Comment by kdavis-mozilla** [comment]
See [Test Pilot](https://testpilot.firefox.com/).

**Comment by mikehenrty** [comment]
This was by design. There was some discussion internally about this, but we consciously went with the shorter footer.
