### ISSUE TITLE
[enhancement] Add support for multilingual users

### ISSUE THREAD

**Issue by tinok** [mozilla/voice-web#1564]
As a (multilingual) user I'd like to be able to contribute to more than one language (speaking or listening). At the moment, once the user sets their language during sign up, it can't be changed. The user is forced to create a separate account. Many people are bilingual or multilingual.

I'd like to be able to work on as many languages as I'm comfortable in, or at least modify the language to be able to work on other datasets. 

This seems separate from #213.

**Comment by tinok** [comment]
Correction: I would like to be able to change the language on the profile page, where the language dropdown is disabled (e.g. https://voice.mozilla.org/fr/profile). It __IS__ possible to contribute to multiple languages but only when switching to other languages in the header dropdown. This is counter-intuitive and might prevent others from working on more than one language.

**Comment by Gregoor** [comment]
Thanks for the feedback! We're indeed working on this and there'll be a new profile experience very soon which makes adding accents for multiple languages more handy.

**Comment by nukeador** [comment]
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
