### ISSUE TITLE
Microsoft Edge and Common Voice

### ISSUE THREAD

**Issue by rprys** [mozilla/voice-web#1566]
I've just been to do a presentation on Common Voice to a large organisation which employs many thousands of Welsh speakers. Due to their security policies they run Microsoft Edge as the only browser.

When we tried the voice.mozilla.org/cy/new on a newish Lenovo laptop all we got was a blank screen. No error message or anything.

For our work with this organisation we need to be able to use Microsoft Edge. 
Please?

**Comment by Gregoor** [comment]
Thank you for that report! I remember it working in Edge before but I can indeed reproduce it not working in Edge atm. Unfortunately I can't even open the DevTools to debug it (they immediately crash). Can you open up the Developer tools (in the menu in the upper right corner) and the contents of the console here?

**Comment by rprys** [comment]
Yes I can open Developer tools and see the content of the Debugger. What would it be useful for me to do?

**Comment by Gregoor** [comment]
A screenshot or a copy-paste of the Console inside of the DevTools would be very helpful!

**Comment by rprys** [comment]
![cv edge debugger](https://user-images.githubusercontent.com/16651092/48443609-a0da5880-e789-11e8-8d82-8e1c3a07b568.jpg)

[anylitics.txt](https://github.com/mozilla/voice-web/files/2578152/anylitics.txt)
[gtm.txt](https://github.com/mozilla/voice-web/files/2578153/gtm.txt)
[index.txt](https://github.com/mozilla/voice-web/files/2578154/index.txt)
[new.txt](https://github.com/mozilla/voice-web/files/2578155/new.txt)
[Open+.txt](https://github.com/mozilla/voice-web/files/2578156/Open%2B.txt)
[Zilla.txt](https://github.com/mozilla/voice-web/files/2578157/Zilla.txt)

Let me know if there are any other files you need.

**Comment by Gregoor** [comment]
Thanks. A screenshot of the console tab's contents would be good. Here is where you'd need to click for that:
![inkedscreenshot_2018-11-14 48443609-a0da5880-e789-11e8-8d82-8e1c3a07b568 jpg jpeg image 1920 x 1200 pixels _li](https://user-images.githubusercontent.com/4051932/48475227-a329ca80-e7fc-11e8-884d-c237db568b03.jpg)

**Comment by Gregoor** [comment]
Thanks for that screenshot. After the newest Windows Update the DevTools also stopped crashing for me, and I can also see that error.

So one cause might be that Edge is quite behind on new-ish JS syntax (in this case from 2014). But even when I change Microsoft's TypeScript to target ES5 (which even IE11 would support), there's still a syntax error. TLDR: I haven't solved this yet.

**Comment by rprys** [comment]
That's OK - there may be millions of people who don't know what a browser is, out there waiting... ;-)

**Comment by Djfe** [comment]
Internet Explorer is affected as well

**Comment by rprys** [comment]
Any update on tjis issue?

**Comment by Gregoor** [comment]
I just looked at it again in Edge and the error message hasn't changed in usefulness and I couldn't find any more info on it. Sorry!

**Comment by Djfe** [comment]
Jay!
so it works again, nice
(I also wrote this to notify everyone here, since comment edits don't do that)

**Comment by rprys** [comment]
Sorry, I'm not getting anything from https://voice.mozilla.org or https://voice.mozilla.org/cy, just a blank screen in Edge. ;-(

**Comment by Gregoor** [comment]
Only on staging atm: http://voice.allizom.org/

Planning to deploy some time today

(sorry I tend to close issues once things are fixed on staging)

**Comment by rprys** [comment]
Ok, yes it works on my computer and on a computer at the above organisation. 

Thanks, that great!

**Comment by rprys** [comment]
It's been drawn to my attention that while the Listening page on  the site works, the Recording page brings up the 'Sorry your platform isnt supported yet' error message.
Could you have a look at this please?
Thanks.

**Comment by Gregoor** [comment]
Unfortunately Edge doesn't support the MediaRecorder API which we use for recording. I've tried to hack around that API a couple of time #469 but to no avail. I hope we'll have a WebAssembly version without that API at some point, but I think [Edge's switch to Chromium](https://blog.mozilla.org/blog/2018/12/06/goodbye-edge/) will happen earlier.

**Comment by rprys** [comment]
An update on this issue. The new Microsoft Edge, based on Chromium now supports Common Voice. Initially it did not support recording, so I put in a request to address that issue.
I've tested recording and verifying today on Microsoft Edge Dev Build 76.0.167.1and it works.
The final release is not likely to be available before the end of 2019 and then will be vetted for suitability by corporate users, so it's a long term fix for my original request.
Thanks for your help on this Gregoor.

**Comment by Gregoor** [comment]
Awesome, very happy to hear that. Thanks for filing that issue!
