### ISSUE TITLE
Link to stats page

### ISSUE THREAD

**Issue by ftyers** [mozilla/voice-web#1567]
I'm currently trying to explain to people how to see the stats, would it be possible to get a link that just shows this:

![captura de 2018-11-13 18-10-49](https://user-images.githubusercontent.com/449545/48434077-0d992700-e779-11e8-92e0-443fdf21814f.png)

Something like:  http://voice.mozilla.org/cnh/stats 

That would be great!

**Comment by ftyers** [comment]
I've tried to use webdriver to extract the SVGs but am not having much luck:
```
from selenium import webdriver

my_url = 'https://voice.mozilla.org/cnh/'


chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
driver = webdriver.Chrome(chrome_options=chrome_options,
  service_args=['--verbose', '--log-path=/tmp/chromedriver.log'])
driver.get(my_url)
print(driver.page_source)
svgs = driver.find_elements_by_tag_name('svg')
idx = 0
for svg in svgs:
	print(idx, svg)
	fo = open('/tmp/x'+str(idx)+'.png', 'w+');
	fo.write(svg.screenshot_as_png)
	fo.close()
	idx += 1

```

I just get:
```
      <h1>
        We’re sorry, but your platform is not currently supported.
      </h1>
```

**Comment by Gregoor** [comment]
Would it also work if it were a link to a homepage but scrolled down to those graphs?

**Comment by ftyers** [comment]
That would be a good quick fix yes!

**Comment by Gregoor** [comment]
It got a bit hacky unfortunately, so on some device sizes it might only scroll to the general direction of stats. It'll be at https://voice.mozilla.org/en/new#stats, once deployed
