### ISSUE TITLE
Footer display problems

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#157]
![image](https://user-images.githubusercontent.com/311082/27297617-80fa82f8-54da-11e7-81d9-a1f9ebf58277.png)

There are some issues with vertical spacing here and also the "Content available ..." sentence should not wrap.

**Comment by mikehenrty** [comment]
@mbebenita if "Content available .." didn't wrap it wouldn't display on the screen. Are you suggesting this should scroll or clip? In any case I would disagree.

The vertical spacing is indeed a bug.

**Comment by mbebenita** [comment]
This is a better screenshot, there's plenty of horizontal space. 

![image](https://user-images.githubusercontent.com/311082/27309881-6107ebd0-550b-11e7-914c-07890cc1d2d2.png)

**Comment by mikehenrty** [comment]
fixed in https://github.com/mozilla/voice-web/commit/249cebd7b85a03d77aba5d05c5542590d7e1a8f6
