### ISSUE TITLE
ISE page returned when editing email exists in another CV account 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1574]
Preconditions:
Have a CV account in staging

STR:
1. Login to CV staging with an email address different that the one used in the account from precondition
2. Navigate to Preferences page
3. Click Edit button for your email address
4. Enter the email address of the account from precondition

Expected results: 
Error message saying that the email address is already used for another account should be displayed

Actual results:
ISE page is displayed:
![duplicated email](https://user-images.githubusercontent.com/5293100/48499382-ffaed900-e840-11e8-8ef2-db5d5c437609.png)

**Comment by Gregoor** [comment]
Can you confirm that it's still not working? I tried with GitHub and Google, and got the message for both.

**Comment by viorelaioia** [comment]
It's working as expected now :+1: . Closing the bug.
