### ISSUE TITLE
Profile: small design issues

### ISSUE THREAD

**Issue by grailean** [mozilla/voice-web#1576]
Profile
Small design issues with spacing, color and measures.
https://www.dropbox.com/s/udb9qpgd145udzd/Screenshot%202018-11-14%2010.32.34.png?dl=0

**Comment by Gregoor** [comment]
RE: border-width: The border doesn't get thicker once focused (it's 1.6px for all). Subpixel border rendering is afaik browser specific.

Outstanding todos:
- [ ] different checkbox style
- [ ] required field (might need some triage, afaik we only wanted the 1st language field to be required)

**Comment by mbransn** [comment]
Closing, this is out of date and checkbox needs are captured elsewhere.
