### ISSUE TITLE
Profile: Add language flow is not implemented like in design.

### ISSUE THREAD

**Issue by grailean** [mozilla/voice-web#1577]
Here is the view that is in the style specific for button and dropdown: https://www.dropbox.com/s/fud5z154lqi5wty/Screenshot%202018-11-14%2010.34.10.png?dl=0

**Comment by mbransn** [comment]
@Gregoor good flag and as we just spoke about, this will become the unified solution. Let's keep as a P1 for now, as it isn't blocking release.

**Comment by Gregoor** [comment]
Dropbox link is dead and even for me it's hard to understand this issue now. let's open up a new one with a clearer description if there's still sth to do here.
