### ISSUE TITLE
Profile: the dropdown is not stylized

### ISSUE THREAD

**Issue by grailean** [mozilla/voice-web#1578]

**Comment by Gregoor** [comment]
Browser dropdowns can't be styled. I don't think this should be prioritized (cc @mbransn)

**Comment by mbransn** [comment]
@Gregoor we are creating a website with custom UI, dropdowns are part of that custom UI. We have styled dropdowns elsewhere on the site, why is this different? Also, which specific dropdown are we talking about -- @grailean screenshots _always_.

**Comment by Gregoor** [comment]
Sorry, should've been more clear: The field itself is stylized, the menu that drops isn't (as it's the system one currently).

**Comment by mbransn** [comment]
@Gregoor cool, I've been in and QA'd myself now. I feel we're okay to delay dropdown UI polish; perhaps we tackle in tandem with the language dropdown as talked about in #1577 ? If so, let's track this along with that in our Profile backlog.
