### ISSUE TITLE
Profile: we need to add the visible icon and check mark if it’s a good to save.

### ISSUE THREAD

**Issue by grailean** [mozilla/voice-web#1579]
Attached the icons that we need to add: https://www.dropbox.com/s/7dbyxsezc499l45/Screenshot%202018-11-14%2010.36.23.png?dl=0

**Comment by Gregoor** [comment]
As none of the fields (except for primary language) are required, what purpose do the icons serve?

**Comment by mbransn** [comment]
The design isn't updated with the latest required specs, I will take this on. cc @viorelaioia to close the loop on #1622

**Comment by mbransn** [comment]
Closing as this is out of date.
