### ISSUE TITLE
Flexible layout looks broken when it's in between states.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#158]
Wide screen

![image](https://user-images.githubusercontent.com/311082/27297851-5b77f780-54db-11e7-81e9-e442f0fc0042.png)

Slightly narrower screen:

![image](https://user-images.githubusercontent.com/311082/27297876-76c9001a-54db-11e7-88fc-db0fb83a8293.png)

A few pixels narrower:

![image](https://user-images.githubusercontent.com/311082/27297889-7f630018-54db-11e7-95a1-9706c822b964.png)

It looks okay when it's very narrow

**Comment by mikehenrty** [comment]
Looks like the "Voice Commons" title wraps when there's not enough horizontal space, which causes the navbar to be pushed down.

**Comment by kdavis-mozilla** [comment]
Can repo "Common Voice" wrap on Firefox on OS X
