### ISSUE TITLE
Avatar: small adjustments, missing messages.

### ISSUE THREAD

**Issue by grailean** [mozilla/voice-web#1580]
Please see below a list of small changes:
https://www.dropbox.com/s/ew2eidv58syyrod/Screenshot%202018-11-14%2010.45.30.png?dl=0

**Comment by Gregoor** [comment]
RE: file format, atm: png, jpg, svg and bmp are supported. So the copy here doesn't make that much sense I think. Change it to "Upload an image file" (cc @mbransn)?

I don't think having the copy makes much sense without the voice clips.

**Comment by mbransn** [comment]
@Gregoor here's copy for v1 profile launch, have updated our content outline to reflect this and tagged you there as well.

**H1**: Add an avatar to your profile
**File upload copy**: Upload an image file
**File upload CTA** (all on one line): Drag and drop or [browse]
_Gravatar stays the same_

Also, as we aren't launching with voice avatar feature, please log a ticket in the Profile epic so we can track future release.
