### ISSUE TITLE
Accent in Esperanto

### ISSUE THREAD

**Issue by RobinvanderVliet** [mozilla/voice-web#1589]
Currently there are 2 accents in the list for the language Esperanto (code: eo). The first word translates as "International" and the second word as "Other". I don't see the use of those 2 options, there is no special "international" accent of Esperanto. I think this selection field should be disabled for Esperanto.

![akĉento](https://user-images.githubusercontent.com/692029/48579942-19721e00-e91e-11e8-9407-6158deab8e0f.png)

**Comment by picsi** [comment]
Rather, it would be more useful if this field had all nationalities listed in it.

**Comment by Vanege** [comment]
I would prefer a list of native tongues, divided into dialects if possible.

**Comment by nukeador** [comment]
We are going to open a conversation on discourse about accents in the coming days with a proposal.

Please, add your feedback there so we can have a unified approach for all languages

https://discourse.mozilla.org/c/voice

Thanks for your contributions!

**Comment by nukeador** [comment]
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
