### ISSUE TITLE
Way too many font faces / styles / sizes, I count 13.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#159]
![image](https://user-images.githubusercontent.com/311082/27297996-dbd9b9c2-54db-11e7-9b96-ad451111e2a0.png)

![image](https://user-images.githubusercontent.com/311082/27297991-d7df2da2-54db-11e7-83ca-0558043eebe9.png)

![image](https://user-images.githubusercontent.com/311082/27298002-e0c79a12-54db-11e7-86db-bacd9c1e58b1.png)

![image](https://user-images.githubusercontent.com/311082/27298010-e53950cc-54db-11e7-82ec-b3daf49fd05a.png)

![image](https://user-images.githubusercontent.com/311082/27298014-e931a116-54db-11e7-9a6a-ed6918b02907.png)

![image](https://user-images.githubusercontent.com/311082/27298022-f0c16948-54db-11e7-9b18-4d50c6c5ea79.png)

![image](https://user-images.githubusercontent.com/311082/27298026-f458a440-54db-11e7-96bc-f00547e83911.png)

![image](https://user-images.githubusercontent.com/311082/27298035-fd22fd1e-54db-11e7-90ab-44aeca08ee8d.png)

![image](https://user-images.githubusercontent.com/311082/27298038-0140a6a8-54dc-11e7-8743-6c2eb99d5af2.png)

![image](https://user-images.githubusercontent.com/311082/27298043-067d899c-54dc-11e7-9c20-ead1236e8cec.png)

![image](https://user-images.githubusercontent.com/311082/27298056-0fb2a7fe-54dc-11e7-9cb2-0dec64961763.png)

![image](https://user-images.githubusercontent.com/311082/27298065-1ea1bc46-54dc-11e7-8b79-4334540be3d7.png)

![image](https://user-images.githubusercontent.com/311082/27298073-24be58e6-54dc-11e7-9d55-6d06fa34007e.png)

**Comment by mikehenrty** [comment]
Actually there are only 2 font-faces. Zilla slab, and sans serif. The different font-sizes are part of the design (to give it a kooky, off-grid look). Your feedback is noted, but short of a big redesign I don't see anything actionable here.

**Comment by mbebenita** [comment]
I'm referring to the combination of font face/size/weight/style.

**Comment by mikehenrty** [comment]
Understood. When we initially got the designs back from studio a few weeks ago, that would have been a good time to raise this issue. At this point though it's unclear what we should fix, how we should fix it, or how much time it would take me to fix it.

I think the best thing to do now is to go with what we have. That said, if you want to take a pass at this with a PR, we will definitely consider it!
