### ISSUE TITLE
Figure out *who* is submitting for review to Apple

### ISSUE THREAD

**Issue by geroter** [mozilla/voice-web#16]

**Comment by mikehenrty** [comment]
Assigning over to @kdavis-mozilla as he is driving the conversation with the engineering manager in charge of focus.

**Comment by kdavis-mozilla** [comment]
Meeting with Stefan, George, and myself setup for next Tue

**Comment by kdavis-mozilla** [comment]
Stefan will submit. In the mean time TestFlight demo versions will be managed by @andrenatal
