### ISSUE TITLE
Make sure we have HiDPI assets.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#160]

**Comment by mikehenrty** [comment]
We do have HiDPI assets, and indeed I've been using them as default (which is a different problem). @mbebenita are there any assets in particular that look funny?

**Comment by kdavis-mozilla** [comment]
@mbebenita Do you have specific assets in mind?

**Comment by mikehenrty** [comment]
this was referring to the robots being fuzzy when zooming in

**Comment by mikehenrty** [comment]
Since the robot asset is already being scaled down and is a vector png, I'm going to close this as Works For Me.
