### ISSUE TITLE
profile form, problem with an entry

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1602]
"Sex" on profile currently has a forth entry with no text:
![firefox_2018-11-20_01-15-46](https://user-images.githubusercontent.com/5685512/48743080-dbe4fc00-ec61-11e8-8c80-4be3b8d6ab88.png)

**Comment by MichaelKohler** [comment]
I'm pretty sure that's because we do want people to let it unset if they don't want to indicate a gender.
