### ISSUE TITLE
Additional data from the profile should be verified as well

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1603]
Age, accent and sex should be verified during listening (at least for a certain amount of strings for each speaker (or a certain percentage like each x-th string needs to be verified)) to actually allow the data to be useful for speech recognition engines and avoid trolls.

It could be useful to edit the data and keep the voice recording.
for these cases new value (unknown could be useful) or a greater age range

**Comment by kdavis-mozilla** [comment]
@Djfe Can this be verified?

Would one really know the difference between the voice of a 29 year old and a 30 year old?

**Comment by Djfe** [comment]
Good question

This issue is more about: Does the added information fit the voice that the user uploads? (to prevent trolls from harming speech engines with these infos)
Some voices don't change much over a lifetime but it's still possible to differentiate between child, young adult, adult and aged

Obviously if the troll still says the sentence correctly then the clip is still useful but it could decrease the accuracy of speech engines that rely on this data to be correct
At least I'm assuming that.

This process of verification could also be done at a later date. Maybe there aren't as many trolls as I fear (takes quite some effort after all).
Maybe it's only useful to check parts of the information: the accent for example. (in-case further accents are added later on (after sentences have been recorded already))

I just realized, that
> at least for a certain amount of strings for each speaker (or a certain percentage like each x-th string needs to be verified)

probably can't be done because the information is anonymized (no connection to the account)
So this can't be checked based on accounts

**Comment by MichaelKohler** [comment]
If this is still a concern, let's discuss on Discourse.
