### ISSUE TITLE
wrong z-index for an element

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1604]
The following div probably should be behind the blue transparent div not infront of it.
![firefox_2018-11-20_05-09-07](https://user-images.githubusercontent.com/5685512/48751082-d350ed80-ec82-11e8-9e14-06c906bd3cf0.png)
![firefox_2018-11-20_05-11-07](https://user-images.githubusercontent.com/5685512/48751085-d51ab100-ec82-11e8-951c-63d4c8f6d3d3.png)

**Comment by MichaelKohler** [comment]
I don't think this dialog is still a thing, but please feel free to reopen if I'm wrong.
