### ISSUE TITLE
Vertical align button text to icons.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#161]
![image](https://user-images.githubusercontent.com/311082/27298221-b0aa6bba-54dc-11e7-9b4c-970638a7739e.png)

**Comment by mikehenrty** [comment]
These are temporary icons, haven't put in the shiny new ones yet.

**Comment by Satana-Jhoni** [comment]
I

**Comment by kenrick95** [comment]
@mikehenrty add "Hacktoberfest" label to this issue too, maybe?

**Comment by mikehenrty** [comment]
> @mikehenrty add "Hacktoberfest" label to this issue too, maybe?

Good idea, but to be honest this is a harder problem than it looks. More like Trick-or-Treat than Hacktoberfest.
