### ISSUE TITLE
Line in clips.tsv with wrong tab separation

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/voice-web#1611]
A pandas import (`read_csv`) of a recent `clips.tsv` leads to at least one line with shifted columns.
`down_votes` contains `thirties` (age content) and therefore isn't interpreted as number. Details will follow once the current import process is done.

**Comment by tilmankamp** [comment]
There are actually quite a few samples that seem to have 'tabbing" problems - an example for reference:
`9250038f-2832-426e-be4d-9a8ad8d0d6f8/c1bf41ee6781177ced439733746f4686871a96fdfd281b78c0f4db69a810a4c3.mp3`

**Comment by tilmankamp** [comment]
Another observation: The number of affected clips happens to be 65535: 16-bit unsigned-int maximum.

**Comment by Gregoor** [comment]
I'm looking into it atm. So far I don't know where mysql's exporter went wrong, I'd have expected it to be battle-tested enough to not have encoding glitches, but well...

**Comment by Gregoor** [comment]
https://github.com/mozilla/CorporaCreator/issues/3
