### ISSUE TITLE
"Log in / Sign Up" button is misaligned on mobile 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1615]
Firefox for iOS:
![photo_2018-11-26_17-52-38](https://user-images.githubusercontent.com/5293100/49025413-463af680-f1a4-11e8-8ad8-f78b6feb5212.jpg)

CV app:
![photo_2018-11-26_17-52-41](https://user-images.githubusercontent.com/5293100/49025429-505cf500-f1a4-11e8-9121-15ebdead5e6f.jpg)

**Comment by WorldCodeCentral** [comment]
It doesn't even show up at all for me on GNU+Linux Firefox beta 64

**Comment by Gregoor** [comment]
@WorldCodeCentral this is not launched yet, it's only on staging atm

**Comment by Gregoor** [comment]
Menu's been merged, button isn't there on mobile anymore
