### ISSUE TITLE
Blank option displayed in Goals - languages drop-down

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1618]
[Environment]:
Windows 10 - Firefox, Chrome

[Precondition]:
Add  3 languages  in Profile

[Steps to reproduce]:
1.Login in Common Voice staging
2.Go to Profile- Goals
3.Go to "Your Languages" section and click down arrow

[Actual result]:
The first option from drop-down is blank
Sometimes, a black line is displayed after the drop-down is closed
![2018-11-27_14h50_26](https://user-images.githubusercontent.com/41474886/49083768-41367f80-f256-11e8-8c2b-0e3097217484.gif)

**Comment by MichaelKohler** [comment]
This view does not exist anymore.
