### ISSUE TITLE
Languages drop-down from Goals section overlaps the profile languages drop-down

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1619]
[Environment]:
Windows 10 - Firefox, Chrome

[Precondition]:
Add 3 languages in Profile

[Steps to reproduce]:
1.Login in Common Voice staging
2.Go to Profile- Goals
3.Go to "Your Languages" section and click down arrow
4.Hover using mouse over language drop-down displayed  in the upper right corner

[Expected result]:
Languages drop-down should be displayed, the drop-down opened in step 3 should not be visible

[Actual result]:
The drop-down opened in step 3 overlaps the languages drop-down
![2018-11-27_14h51_51](https://user-images.githubusercontent.com/41474886/49084020-fcf7af00-f256-11e8-8aba-81c727d1491f.gif)

**Comment by MichaelKohler** [comment]
This view does not exist anymore.
