### ISSUE TITLE
Extra pixels at the ends of the divider looks funny to me.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#162]
![image](https://user-images.githubusercontent.com/311082/27298273-d1020396-54dc-11e7-8aa7-57aaa69c2978.png)

**Comment by mikehenrty** [comment]
This is one an inconsistency with how browsers display padded lines. We could consider using an image here instead.

**Comment by mikehenrty** [comment]
using a dashed line here makes this a lot better
