### ISSUE TITLE
Profile Build Fine Tuning

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1622]
@Gregoor how might we get this current profile build:

![current-profile-page](https://user-images.githubusercontent.com/18686986/49119488-59f66380-f25d-11e8-80c2-f26c02797986.png)

To look more like [this intended profile build](https://zpl.io/an9zKMx):

![profile-ui-design](https://user-images.githubusercontent.com/18686986/49119514-72ff1480-f25d-11e8-8cbd-3b1614f58652.png)

Here's some mark up:

![marked-profile-page](https://user-images.githubusercontent.com/18686986/49120302-e35b6500-f260-11e8-8eec-6cb07a34cd74.png)

Also see #1621 for Sidebar specific notes

**Comment by viorelaioia** [comment]
@mbransn , @Gregoor in the [intended profile build](https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5b9977c64e416b0e55239f28), I see several fields marked as required. Should we have that implemented?

**Comment by Gregoor** [comment]
Added the tooltips, the rest looked already fixed.
