### ISSUE TITLE
Recording/Validating data on front page not updating

### ISSUE THREAD

**Issue by rprys** [mozilla/voice-web#1630]
There appears to have been a change lately in the behaviour of the front page recording/validating graph when choosing Cymraeg.
The data now appears to be stuck on: Recording 1m 53s and Validation 0.
I'm aware that people have been recording/validating.
![rec-val cymraeg](https://user-images.githubusercontent.com/16651092/49167370-271ba080-f32d-11e8-8060-adbec7ffed31.jpg)

Can this be checked?
Thanks

**Comment by rprys** [comment]
This appears to be working again now.
Thanks.

**Comment by Gregoor** [comment]
Happy to hear that. Sorry, it was caused by a half-baked caching system.
