### ISSUE TITLE
Dashboard Max-width too wide

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1632]
@Gregoor the dashboard desktop margins should be pinned to align with the header elements: logo and language dropdown. Currently it sits wide of our intended max-width.

![dashboard-current](https://user-images.githubusercontent.com/18686986/49171805-37635980-f2f4-11e8-8c9f-8ff5f6f99ae5.png)

Also, just noticed: We have a focus ring lingering on the stat counter after I click it. What's up with that? 🤔

**Comment by Gregoor** [comment]
The focus ring appears when you press any key, and shows the currently focused element
