### ISSUE TITLE
Dashboard speak & listen component CTA resize

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1636]
@Gregoor the 'help us get to...' CTA is stacking oddly for our dashboard components.

Suggestions: 
- move the counters (top and bottom) to the left, giving right side content more space
- allow the 'help us...' CTA to have a smaller min-width to avoid a restack
- for those who have reach top goals replace `infinity` w/ ∞ for now

![current-counter-layout](https://user-images.githubusercontent.com/18686986/49188080-5c6cc200-f31e-11e8-8b6e-47eab27eaaa3.png)

Also want to ensure we're tracking to add the goal % UI at some point?

**Comment by Gregoor** [comment]
Oh, that infinity was an accident 😁 Will get on it. The goal % ui fell off my radar, sorry!

**Comment by mbransn** [comment]
All good for the infinity, if people have surpassed our set goals its not a bad fallback if we use the icon.

I will log a goal % issue so we get it done as a p2

**Comment by Gregoor** [comment]
Thanks!
