### ISSUE TITLE
string mistake

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1641]
https://pontoon.mozilla.org/de/common-voice/messages.ftl/?search=request&string=193018

> Would you like to request your voice recordings **to** be deleted too, or do you prefer to keep them in the Common Voice dataset?

**Comment by Gregoor** [comment]
Afaik that's valid english

**Comment by Gregoor** [comment]
Afaik that's valid english

**Comment by Djfe** [comment]
I see, I added the "to" though (that's why it's bold)
So it's ok to not have a "to" between recordings and be?

**Comment by Gregoor** [comment]
Yes, both work :)
