### ISSUE TITLE
Add Italian dialects

### ISSUE THREAD

**Issue by marco-c** [mozilla/voice-web#1647]
There are several dialects in Italy with very different accents. It would be useful to collect this information about Italian speakers.

**Comment by nukeador** [comment]
We are going to open a conversation on discourse about accents in the coming days with a proposal.

Please, add your feedback there so we can have a unified approach for all languages

https://discourse.mozilla.org/c/voice

Thanks for your contributions!

**Comment by nukeador** [comment]
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
