### ISSUE TITLE
User profiles don’t work in the iOS app

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1649]
It’s impossible to login to a user profile in the iOS app because the browser you open the verification link in has to be the same one you made the request in, which you can’t do because the browser is embedded into the app and you can’t paste URLs into it.

Also, you can’t record anything in iOS web browsers and the site recommends you use the app instead. So there’s therefore no way to record on iOS and have those recordings logged to your account.

**Comment by Gregoor** [comment]
Thanks for raising this issue. Sorry we didn't think of it! From reading [this answer](https://apple.stackexchange.com/a/237355) we need to add a file to our server and change the iOS app.
Do we happen to have a willing iOS developer in our community who can look into the iOS side of things? I'm just leaving the country without my test devices, so it'd be another 12 days until I have a MacBook and an iPad.

**Comment by mbransn** [comment]
@dabinat +1, thank you for flagging this issue. We are actively working on a solution.

In the meantime, it is possible to login via a browser in iOS and _validate_ sentences. You are correct, _recording_ sentences in iOS is currently only possible in the iOS app (which is why the app exists). Every bit of contribution still helps, so hopefully you will still be open to validating on iOS while we work through the app login fix. Thanks again for your help and patience!

**Comment by dabinat** [comment]
> Do we happen to have a willing iOS developer in our community who can look into the iOS side of things?

If all it is is adding the entitlement file and making it open the URL in the web view, that seems pretty straightforward. I'd be happy to do it. Let me know when the apple-app-site-association file is on the server and I'll make the changes.

**Comment by Gregoor** [comment]
I'm not entirely sure if that's all that's needed. I think it depends on whether the WebView automatically picks up on the fact that it was opened through an universal link. I'm now looking into getting access to the iTunes account that manages the iOS app, so that I can get the appID. Unless anybody has it? (it should be in the format of `JHGFJHHYX.com.facebook.ios`)

**Comment by Gregoor** [comment]
@dabinat here we go: https://voice.mozilla.org/apple-app-site-association

**Comment by dabinat** [comment]
#1662

**Comment by Gregoor** [comment]
We have different login methods now, which iOS users can use to login 🚀

**Comment by rprys** [comment]
Hi Gregoor, I have a large organisation, (yes, the same one as with MS Edge ;-)) who would like to contribute using some of the iPads they have, but are having difficulty logging in using the iPad app. 
Are we nearly there? They've not been able to log in. 

What are the "different login methods now, which iOS users can use to login"? Thanks :-)

They are using Internet Explorer and Microsoft Edge, have some iPads and loads of Android phones. The android phones are OK but we're struggling with the rest of their equipment... I guess that it will be the same with many other organizations we aim to work with.

**Comment by Gregoor** [comment]
Heya, that's great to hear, sorry login has been difficult! When clicking login you should be presented with the following options:

- passwordless
- Firefox Accounts
- GitHub
- Google

Passwordless doesn't work on iOS atm, but the rest should be fine.

**Comment by rprys** [comment]
Thanks Gregoor, that's useful, but they are normal people in a work situation, they cant use personal accounts (Firefox/Google) at work and their unlikely to be on GitHub :-)

Any chance of getting that passwordless fixed asap?

**Comment by Gregoor** [comment]
Unfortunately not, sorry. We don't own the domain where authorization happens and hence can't associate it with the Common Voice app. To our knowledge that'd be the only way to unlock it on iOS.

On the bright side, Safari has started implementing the MediaRecorder API, so we won't need the app anymore soon(ish).

**Comment by rprys** [comment]
OK. If the API is implemented by a new version of Safari there is a chance it may not work on older iPads 1-3, I suppose. Hmmm...
I'm sure Apple would encourage them to go out and get nice new shiny devices... :-0

**Comment by Gregoor** [comment]
Yeah you're right, we wouldn't want to encourage that! If we find a way to support passwordless on iOS, we certainly will!

Maybe your colleagues could use the work mail to login with Firefox Account?
