### ISSUE TITLE
Samsung Internet no longer supported?

### ISSUE THREAD

**Issue by reinhart1010** [mozilla/voice-web#1650]
Hello,

After the addition of SSO login I would like to import my previous contribution counts from Samsung Internet, but unable due to the "Not Supported" error.

Here's the user agent.

```
Mozilla/5.0 (Linux; Android 8.1.0; SAMSUNG SM-J730G Build/M1AJQ) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/7.4 Chrome/59.0.3071.125 Mobile Safari/537.36
```

**Comment by Gregoor** [comment]
Thanks for raising this issue, it's supposed to be supported. The "not-supported" screen is a bit of a final error-fallback. I need to put something less confusing in there.
I'll look into it early next week!

**Comment by ftyers** [comment]
I just tested with Samsung Internet, it's not pretty but it works.

**Comment by reinhart1010** [comment]
Samsung Internet is based on older, but guaranteed to be stable (similar to Firefox ESR strategy) version of Chromium so yes Common Voice would work in that browser too!

**Comment by ftyers** [comment]
@reinhart1010 so it does work and this issue can be closed?

**Comment by reinhart1010** [comment]
Yes I can finally confirm that this issue was fixed.
