### ISSUE TITLE
[Priority] Update Privacy Policy and Terms

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1651]
@Gregoor please consider this a priority request: we have [Privacy Policy](https://docs.google.com/a/mozilla.com/document/d/1vYnFmf8bN19Q1aY0z0i6-u2irHho93dT6x9KUC5W6kQ/edit?disco=AAAACafv6xI) and [Terms](https://docs.google.com/a/mozilla.com/document/d/1vYnFmf8bN19Q1aY0z0i6-u2irHho93dT6x9KUC5W6kQ/edit?disco=AAAACafv6xM) that are ready for localization and implementation.

**Comment by Gregoor** [comment]
It's been updated through our legal docs infra.
