### ISSUE TITLE
Leaderboard on dashboard not updated instantly

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1653]
![screenshot from 2018-12-02 02-15-58](https://user-images.githubusercontent.com/91113/49334527-8c46ee80-f5d8-11e8-82ad-7825d72a9c2f.png)

In the screenshot you see, i have made 50 recordings, but the leaderboard on the bottom right shows only 35 (state of my contributions before todays).

When i reload the page, my recordings on the leaderboard are randomly 35 or 40. So you have probably load balancing and caching nodes, that are out of date.

So i suggest configure sticky sessions in the load balancer, so i get the same data on every reload and improve cache invalidation.

**Comment by Gregoor** [comment]
Heya, thanks for the report. Here's what's going on:
We're running 3 instances, each using their own in-memory cache. As they don't refresh in consistent intervals, they store the state of the application at different points in time (for 20 minutes). We need to replace that with a Redis shared between the instances ([similar to how we used consul before](https://github.com/mozilla/voice-web/commit/37675ff26c51c34fa5d9a09e11ffcc7f8ce062ef)).

**Comment by Gregoor** [comment]
We have a Redis now :)
