### ISSUE TITLE
Report abuse

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1655]
Have you ever considered recording a different sentence than displayed to troll other users? I have, so you better implement a feature to report abuse in verification screen, so users that abuse the system multiple times can get banned. That's hopefully not needed often so the work to moderate reports is not much.

**Comment by Gregoor** [comment]
Yes, feel free to leave your comments in #272. We haven't found the time yet unfortunately (and it hasn't been a significant problem).
