### ISSUE TITLE
Go back to dashboard from contributing

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1656]
When i click the back button on the contribution end screen i would like to see the dashboard instead of the homepage. What do you think?

![screenshot from 2018-12-02 02-49-30](https://user-images.githubusercontent.com/91113/49334729-2a3cb800-f5dd-11e8-8466-fd02082fa1cc.png)

**Comment by Gregoor** [comment]
Makes sense to me. Wdyt @mbransn?

**Comment by mbransn** [comment]
Brilliant catch @davidak -- yes, when logged in the back button can route back to the dashboard from either contribution method (speak/listen). When not logged in though, we should still be routing people back to the homepage. Thanks both!
