### ISSUE TITLE
Arabic Webpage - Missing Speak & Listen Buttons

### ISSUE THREAD

**Issue by coolfool999** [mozilla/voice-web#1657]
The Arabic webpage is missing the speak & listen buttons on chrome (Version 70.0.3538.110 - 64-bit) & chromium based browsers (i.e. Vivaldi), I've provided a screenshot to better convey this issue.

![964f43f5-06df-46b3-a76f-569bc5023fd6](https://user-images.githubusercontent.com/45539425/49342342-b7325080-f673-11e8-9c25-2c72432bd6a8.jpg)

**Comment by RobinvanderVliet** [comment]
That is because the Arabic project is not yet launched. Check the [Asturian](https://voice.mozilla.org/ast) or [Frisian](https://voice.mozilla.org/fy-NL) projects, they have a similar page, which only informs the user about the project.

**Comment by Gregoor** [comment]
We're looking into making sentence collection easier: https://discourse.mozilla.org/t/we-want-your-feedback-improving-the-sentence-collection/30358
So once the arabic community has collected enough [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) sentences we can activate it.
