### ISSUE TITLE
Use the same font for text that we want users to read.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#166]
![image](https://user-images.githubusercontent.com/311082/27298363-2d51700a-54dd-11e7-9970-ec6cd3b6f74b.png)

vs

![image](https://user-images.githubusercontent.com/311082/27298370-34948406-54dd-11e7-973a-25df27ea369f.png)

**Comment by mikehenrty** [comment]
This was by design, and came from the designers (not me this time). That said, the listen widget needs some polish, but we don't need this bug for that.

**Comment by mbebenita** [comment]
What looks better to you? I find it strange that a different font is used.

**Comment by mikehenrty** [comment]
It is indeed strange, and breaks some common UX guidelines to mix serif and san serif fonts. That said, Mozilla breaks this same rule on the current Mozilla.org site, and we did ask the designers to get "kooky."

Let's re-examine this when we polish the listening screen a little more, as right now we are not doing the designer's vision justice.
