### ISSUE TITLE
Unable to click fields on profile page

### ISSUE THREAD

**Issue by FabioRosado** [mozilla/voice-web#1660]
Hello,

When registering to voice, the form fields are not clickable. It took me a while to try with the tab key and using the tab key will focus on the next field and allowed me to fill in the form.

The dropdown menus also don't work when we tab into them, unless we press the up/down key on the keyboard.

The `Add Language` button was the only one working with a click, although after refreshing the page the button is not clickable and when tabbing through the form the button is never focus so I am unable to add a language to my profile.

Once finally registered, I went into the profile page but this issues still persist.

I'm using Safari Version 12.0.1.

**Comment by Gregoor** [comment]
Thanks for the report and sorry for the delay. I'm finally home again and have access to my MacBook for looking into Safari bugs! 🎉
