### ISSUE TITLE
Missing REPORTING.md

### ISSUE THREAD

**Issue by carolstran** [mozilla/voice-web#1661]
I noticed in both the README.md and CONTRIBUTING.md that there is a link to a REPORTING.md file that is unfortunately missing 😞

<img width="1284" alt="screen shot 2018-12-03 at 14 02 08" src="https://user-images.githubusercontent.com/26869552/49383635-7ab93000-f719-11e8-9ff9-3d17764cb07d.png">

Does the REPORTING.md file exist or would it need to be created? I noticed there is a link for how to report mentioned in the [CODE_OF_CONDUCT.md](https://github.com/mozilla/voice-web/blob/master/CODE_OF_CONDUCT.md) - so maybe it could work to link directly there?

If you tell me where to point the link, I would be happy to update the files 😊

**Comment by davidak** [comment]
It was just removed 10 days ago in https://github.com/mozilla/voice-web/pull/1646.

The text in both files needs an update. Maybe just link to the CODE_OF_CONDUCT file.
