### ISSUE TITLE
Learn from dict.cc experiences

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1663]
Do you guys know dict.cc, especially the aspect of recording the words and sentences?

https://contribute.dict.cc/?action=audio-history&f=--PENDING

Common Voice feels like the same "game" to me.

You can contribute by recording the dictionary entries and validate the recordings of others. You can also comment when validating, so the recording person can improve. For example common problems are bad audio quality or cut-off recordings. You also get a rank when contribute, what feels very encouraging! With higher rank, you get more voting power. This is my profile, for example: https://users.dict.cc/davidak/

You can see that some words triggered me and i had to pronounce them very graphically, what is inappropriate there and i got direct feedback from other users. That reminded me that trolling this way is only fun for myself but destructive for the project, so i stopped that. Related to https://github.com/mozilla/voice-web/issues/272

![vcds](https://user-images.githubusercontent.com/91113/49419504-6875db00-f787-11e8-89d2-8c16bcf1d22a.png)

![cds](https://user-images.githubusercontent.com/91113/49419544-9529f280-f787-11e8-9816-4ee2874a81f2.png)

You might want to speak to [Paul](https://users.dict.cc/Paul/) and learn from their experiences hosting the site, especially encouraging contributors and dealing with trolls.

See also:

- [Audio Recording Guidelines](https://contribute.dict.cc/guidelines/#section14)
- [notes on Voting Accuracy Level and voting power on the right](https://users.dict.cc/hall-of-fame/)

I think their system work very well to get high quality contributions from the community.

**Comment by MichaelKohler** [comment]
If this is still something to discuss, let's have this conversation over at Discourse: https://discourse.mozilla.org/c/voice/239
