### ISSUE TITLE
Look into disabling the microphone if no recording is going on.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#167]
![image](https://user-images.githubusercontent.com/311082/27298442-7ae10880-54dd-11e7-869f-d4ed1696d452.png)

The recording icon is a bit ominous when you click away on another tab.

**Comment by mikehenrty** [comment]
We have no control over this. FWIW firefox does the same thing

**Comment by mbebenita** [comment]
Are you saying there is no way to release access to the microphone? That's a bummer.

**Comment by mikehenrty** [comment]
As far as can tell, this icon will always display on both Chrome and FF once the user grants your page access to mic/camera. I'm not an expert, so if someone knows a way let's reopen this.
