### ISSUE TITLE
Can't Login, Session not created

### ISSUE THREAD

**Issue by codenoid** [mozilla/voice-web#1670]
Environment : 
   1. Version 70.0.3538.77 (Official Build) (64-bit)
   2. Linux Ubuntu 16.04 Xenial

Just like normal way, i request login url to my email, but after i access the url for sso login, the session not created (not logged), i don't know why

**Comment by davidak** [comment]
@codenoid you mean Chromium or Chrome, right?

Do you see any error message that could be helpful? Maybe in the JavaScript console of the browser?

**Comment by codenoid** [comment]
yes @davidak , here the screenshot after click SSO Login Url

![Console](https://i.postimg.cc/jdKJXQ78/Screenshot-from-2018-12-06-06-12-13.png)

**Comment by Gregoor** [comment]
You need to agree to the privacy policy and save, after that you should have an account :)

**Comment by codenoid** [comment]
what, i already have account, and my account is in rank #35 (if i not wrong) (for validating voice)

**Comment by Gregoor** [comment]
Sorry for the confusion: You had a local profile before which couldn't be shared between devices. Now that we have login, you need to confirm the new privacy policy again and then you can click save and you'll have an account.

**Comment by Gregoor** [comment]
Let me know if it's still not working as expected (then I'll reopen this)
