### ISSUE TITLE
Chromium 70: platform is not currently supported

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1671]
I get this message now, also in a strange place.

![screenshot from 2018-12-05 22-25-24](https://user-images.githubusercontent.com/91113/49545013-b2bca080-f8dc-11e8-9594-ff450cc23319.png)

![screenshot from 2018-12-05 22-11-15](https://user-images.githubusercontent.com/91113/49544763-f6fb7100-f8db-11e8-972e-d9b7564fe44a.png)

(Like you probably know, Chromium is compatible with Chrome and everything works.)

User-Agent Request Header is: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

---

Chromium Version 70.0.3538.110 
NixOS 18.09.1446.db561c90ef3 (Jellyfish)

**Comment by Gregoor** [comment]
Thanks! That message was supposed to only go out for IE. It should be fixed now.
