### ISSUE TITLE
Dates on Streaks

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1672]
Is it a bug that Streaks shows the same date on every goal?

![screenshot from 2018-12-05 23-37-23](https://user-images.githubusercontent.com/91113/49548701-db499800-f8e6-11e8-9ad6-fc06db8878ec.png)

---

Chromium Version 70.0.3538.110
NixOS 18.09.1446.db561c90ef3 (Jellyfish)

**Comment by Gregoor** [comment]
@davidak can you tell me what it now looks like for you? Thanks!

**Comment by davidak** [comment]
@Gregoor sure.

![screenshot from 2018-12-18 15-28-12](https://user-images.githubusercontent.com/91113/50160421-9c99e180-02d9-11e9-8768-0b841a33f803.png)

I havn't contributed three days ago, so it looks correct now.

**Comment by Gregoor** [comment]
Cool! Thanks for checking.
