### ISSUE TITLE
Choose file element shown in avatar upload

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1673]
![screenshot from 2018-12-05 23-42-15](https://user-images.githubusercontent.com/91113/49548948-9eca6c00-f8e7-11e8-8b69-f7af17471036.png)

---

Chromium Version 70.0.3538.110
Firefox 63.0.3
NixOS 18.09.1446.db561c90ef3 (Jellyfish)

**Comment by DivyeshPuri** [comment]
@davidak Can you explain your issue?

**Comment by davidak** [comment]
I think the "choose file" element should not be visible.

**Comment by MichaelKohler** [comment]
Can't reproduce.

**Comment by davidak** [comment]
yeah, don't look broken anymore

![Screenshot from 2020-03-03 21-55-20](https://user-images.githubusercontent.com/91113/75818739-ba961980-5d99-11ea-8aad-8e1e99336a2f.png)
