### ISSUE TITLE
strange characters in german goal sentence

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1678]
![screenshot from 2018-12-06 22-16-06](https://user-images.githubusercontent.com/91113/49612297-91bf8280-f9a4-11e8-84dd-79caff25059f.png)

These ">> <<" characters are not common in german sentences. To make this sentence more readable, i suggest to use "Bestätigungsziels (2.400)".

**Comment by Djfe** [comment]
Hi,
I know what you mean :) (I wasn't sure about it myself while translating it)
I chose Guillemets specifically though.

The correct way to write it would be „2.400“ or „Bestätigungsziels (2.400)“ (bottom/top, not both at the top)
To me that looks ugly.

Guillemets are a valid alternative in German and they are (pretty much) used exclusively in books:
![book](https://www.laser-line.de/media/object/ll/file/1-3/ev/ll17j7lpta7pyddev_buch.jpg)
https://www.laser-line.de/news/korrekte-anfuehrungszeichen

https://de.wikipedia.org/wiki/Anf%C3%BChrungszeichen#Deutschland_und_%C3%96sterreich

https://www.saxoprint.de/blog/regeln-anfuehrungszeichen-setzen/

I'm a native speaker btw.
so we cann  also discuss about this in German if you prefer that :)

An alternative would be:

> Sie haben Common Voice geholfen, 65% des heutigen Ziels von 2400 Bestätigungen zu erreichen!

What do you think?

**Comment by davidak** [comment]
>Sie haben Common Voice geholfen, 65% des heutigen Ziels von 2400 Bestätigungen zu erreichen!

that looks better

**Comment by Gregoor** [comment]
https://pontoon.mozilla.org/de/common-voice/messages.ftl/?search=haben+common+voice&string=179778
https://pontoon.mozilla.org/de/common-voice/messages.ftl/?search=haben+common+voice&string=179779

Those are the strings, feel free to change 🙃

**Comment by Djfe** [comment]
@Gregoor I wrote you a message on slack about the way numbers are displayed in German. What do you think?

**Comment by Gregoor** [comment]
This should be fixable through Pontoon, so I'm closing the issue. Lmk if I'm wrong!

**Comment by davidak** [comment]
@Gregoor thanks for giving the links. I suggested the change there.

**Comment by Djfe** [comment]
sry, I totally forgot about this.

Spricht etwas dagegen, daraus

> des heutigen Ziels von x Aufzeichnungen/Bestätigungen

zu machen?
Ich find das ansonsten komisch ^^
Bestätigungsziels von 2400
2400 was denn?

**Comment by davidak** [comment]
@Djfe ja, das würde etwas besser klingen.
Aber "des heutigen Ziels" hört sich an, als ob es ein Ziel gibt, aber Aufzeichnungen/Bestätigungen sind zwei verschiedene Ziele. Oder ist es klar, dass "Ziel ... von Bestätigungen" ein eigenständiges Ziel ist?

Wenn es einen Konsens gibt das entsprechend zu ändern kann ich das tun. Von meiner Seite spricht nichts dagegen.

**Comment by Djfe** [comment]
ich denke, dass das klar geht.
"des heutigen Ziels" schließt in meinen Augen nicht aus, dass es jeden Tag zwei Ziele gibt ^^
