### ISSUE TITLE
goal per language

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1679]
![screenshot from 2018-12-06 22-16-06](https://user-images.githubusercontent.com/91113/49612450-10b4bb00-f9a5-11e8-8f73-de39f0ea0f70.png)

The end screen says "todays goal", but that means actually the goal of the currently selected language. So please make it more clear in this and other places.

For example: "Sie haben Common Voice geholfen, 68% des heutigen Bestätigungsziels »2.400« für die Sprache Deutsch zu erreichen!"

**Comment by MichaelKohler** [comment]
Let's have this discussion over at https://discourse.mozilla.org/c/voice/239
