### ISSUE TITLE
daily goal for "all languages" is the same as every individual language

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1680]
![screenshot from 2018-12-06 22-33-33](https://user-images.githubusercontent.com/91113/49613122-085d7f80-f9a7-11e8-806d-0b37d2849678.png)

schouldn't it be more? maybe all individual goals combined, but that would not be achievable without active communities for every language!

**Comment by MichaelKohler** [comment]
Let's have this conversation over at Discourse: https://discourse.mozilla.org/c/voice/239
