### ISSUE TITLE
daily goal not reloaded when language is changed on the homepage

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1681]
## Steps to reproduce

1. open https://voice.mozilla.org/en
2. you see "Today's Progress" for english when moving the mouse over "Speak" or "Listen"

![efwf](https://user-images.githubusercontent.com/91113/49613407-d3056180-f9a7-11e8-931b-2476c70b4575.png)

3. change language
4. the language of the text changes, but the daily goal is still from english. it is different when you reload the page!

![wegre](https://user-images.githubusercontent.com/91113/49613450-e9abb880-f9a7-11e8-863f-143fa717a4f1.png)

**Comment by Gregoor** [comment]
Thanks! Should be fixed now
