### ISSUE TITLE
encourage the user to take a break from time to time

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1683]
I think a break after 30 minutes of contributing would be good. (maybe already earlier?)

Measuring the time a user spend is probably not that easy, but we can count contributions. 1 contribution would be one session of 5 sentences, recording or verifying.

It took me 44 seconds to verify and 2:25 minutes to record. So we could assume one contribution to take 1 minute.

So a user should get a hint to take a break at the end screen of every 30. contribution. (most users probably don't do that much)

![screenshot from 2018-12-06 23-12-57](https://user-images.githubusercontent.com/91113/49615135-db13d000-f9ac-11e8-8f86-768b2a922164.png)

The counter should reset when a user logs in, start a new session when the last session is 20 minutes ago or when the hint was displayed.

This is a practical implementation of the CODE_OF_CONDUCT: "Self-care is of utmost importance (take breaks, eat food, plenty of sleep)" (Maybe also show hint "Shouldn't you sleep now?" at night?)

**Comment by MichaelKohler** [comment]
Let's have this conversation over at Discourse: https://discourse.mozilla.org/c/voice/239
