### ISSUE TITLE
TypeError: undefined is not an object (evaluating '(e?e.locales:[]).map')

### ISSUE THREAD

**Issue by annag42** [mozilla/voice-web#1684]
Can you describe what steps lead to the error happening?

In Settings, decide to add another language, but leave the language-selection blank. 
Then, click on the Goals icon. 
See the error screen. 
Report this error. 

```
TypeError: undefined is not an object (evaluating '(e?e.locales:[]).map')
render@https://voice.mozilla.org/dist/7.bundle.js:1:722
li@https://voice.mozilla.org/dist/bundle.js:34:60107
Wi@https://voice.mozilla.org/dist/bundle.js:34:78739
$i@https://voice.mozilla.org/dist/bundle.js:34:79116
Na@https://voice.mozilla.org/dist/bundle.js:34:85539
Pa@https://voice.mozilla.org/dist/bundle.js:34:84919
La@https://voice.mozilla.org/dist/bundle.js:34:91130
Tn@https://voice.mozilla.org/dist/bundle.js:34:30695
Tn@[native code]
```

**Comment by Gregoor** [comment]
Thanks for the report! Can you try reproducing it on https://voice.allizom.org/? I realized that the error log reporting I put in is not terribly useful, so I'm test-driving sentry.io for debugging this (and other issues).

**Comment by annag42** [comment]
it doesn't seem to happen there, right now. sorry. :-/

**Comment by Gregoor** [comment]
Thanks for trying to reproduce! Some changes from staging are not on prod, maybe this got fixed accidently 🤞
