### ISSUE TITLE
queue not empty regarding homepage

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1685]
![screenshot from 2018-12-09 09-18-01](https://user-images.githubusercontent.com/91113/49695031-fc371500-fb94-11e8-8d53-4e72255aa99b.png)

Regarding the homepage, there is 7h of unverified recordings for german, but i get the message that the queue is empty.

![screenshot from 2018-12-09 09-30-51](https://user-images.githubusercontent.com/91113/49695052-22f54b80-fb95-11e8-9874-e3089a04bf3b.png)

(I don't think they are all from me :D)

**Comment by Gregoor** [comment]
The area between the graphs is actually not only not yet validated clips but also in valid clips. See #1410 for more
