### ISSUE TITLE
Info/Link in leaderboard when user has visibility set to false

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#1688]
Some users have been asking why they don't show up in the leaderboard. Maybe we should put an info banner / link into the leaderboard if they have the setting disabled.

Wdyt @mbransn?

**Comment by mbransn** [comment]
@Gregoor working through this with @grailean this sprint, will come back with a UX/UI rec. Thanks for calling out (esp. as this stumped me on staging as well when I first ran through setup, leaderboard visibility is off by default I believe).

**Comment by Gregoor** [comment]
Oh we do have that implemented now :)
