### ISSUE TITLE
The icons are not displayed on profile buttons when they are selected

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1689]
[Environment]:
iOS 12 - Firefox for iOS
Windows 10 - Chrome

[Steps to reproduce]:
1.Login to https://voice.mozilla.org
2.Go to https://voice.mozilla.org/en/profile/settings

[Expected result]:
The settings icon should be displayed on Settings button

[Actual result]:
The settings icon is missing when the button is selected 
![image1](https://user-images.githubusercontent.com/41474886/49745023-bb2f2580-fca6-11e8-8282-2656df788179.png)

**Comment by DivyeshPuri** [comment]
@rleitan Did you tried sliding your fingers on the profile navbar for more options?

**Comment by MichaelKohler** [comment]
This view does not exist anymore.
