### ISSUE TITLE
CSP directive on inline scripts

### ISSUE THREAD

**Issue by DivyeshPuri** [mozilla/voice-web#1691]
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'sha256-yybRmIqa26xg7KGtrMnt72G0dH8BpYXt7P52opMh3pY=' 'sha256-jfhv8tvvalNCnKthfpd8uT4imR5CXYkGdysNzQ5599Q=' https://www.google-analytics.com https://pontoon.mozilla.org https://optimize.google.com". Either the 'unsafe-inline' keyword, a hash ('sha256-wo4ogNJZER/XvjGDNEVen5XcmoQ/5zW+W9yHMsePNMQ='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by DivyeshPuri** [comment]
Can I work on this?

**Comment by lucaswerkmeister** [comment]
It looks like the script was touched by @Gregoor in 9813d40ef3010938c50e9022a6eaefb801374b90 and the CSP in `nubis/puppet/web.pp` or `server/src/server.ts` (not sure which one matters) wasn’t updated accordingly. (For comparison, 5e40466d845ff41da38e00c00e70495c7768a2ea updated both the scripts and the hashes, and then fc9cb8fded41e34b0b6b26ca0ab238d357cfd6d8 apparently fixed the hashes.)
