### ISSUE TITLE
antisemitic / homophobic sentence in common voice france

### ISSUE THREAD

**Issue by PhieF** [mozilla/voice-web#1693]
Hi,
This French sentence doesn't seem appropriate 

![capture d ecran de 2018-12-13 01-08-27](https://user-images.githubusercontent.com/26841885/49906988-8cff4080-fe74-11e8-868c-215ab1823a7c.png)

It literally means "Jews always need a proper? name (or surname, meaning "someone" I think) to suck" or something like that
I think you should remove it.

thanks ! :)

**Comment by Gregoor** [comment]
Thanks for the report! I've removed the sentence. More from the author are in this file:
https://github.com/mozilla/voice-web/blob/master/server/data/fr/libretheatre_3305.txt

If anyone with a better grasp of the language could check it, that'd be great!

**Comment by PhieF** [comment]
The author was sometimes accused of being antisemitic, I don't know much about it

https://fr.wikipedia.org/wiki/Jean_Giraudoux#Giraudoux_antis%C3%A9mite_et_raciste_?
