### ISSUE TITLE
verification session end screen broken for german

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1694]
verify end screen shows message from record end screen.

![screenshot from 2018-12-13 01-36-51](https://user-images.githubusercontent.com/91113/49907712-b2da1480-fe77-11e8-8ab2-f9e3f390fdd1.png)

i can not finish this verify session!

---

Chromium 70.0.3538.110
NixOS 18.09.1446.db561c90ef3 (Jellyfish)

**Comment by davidak** [comment]
New verification session. I was able to verify one recording and git this screen then.

![screenshot from 2018-12-13 01-42-14](https://user-images.githubusercontent.com/91113/49907893-69d69000-fe78-11e8-9400-dfc8278eb5b5.png)

**Comment by davidak** [comment]
No problem with english sentences.

![screenshot from 2018-12-13 01-46-03](https://user-images.githubusercontent.com/91113/49908063-1dd81b00-fe79-11e8-8c90-10a1e653b151.png)

**Comment by Gregoor** [comment]
Looks like the queue is empty for german (i.e. everything's validated). That it works on some reloads, is due to the instances not sharing a cache (yet).
