### ISSUE TITLE
daily verification goal

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#1695]
Why is the goal 2x the recording goal, but 3 verifications are needed? Should the daily goal not be to verify all recorded sentences?

**Comment by dabinat** [comment]
This is a good point. Maybe the verification target should be dynamic based on how many recordings are in the queue.

**Comment by Fatimuskii** [comment]
I have a little problem, but i dont know if i must write it here...
When i finished to listen som recording 5/5, it says "You've helped Common Voice reach 73% of our daily 2,400 validation goal!" 
my question here is: shouldn´t that changed if i listen to another 5/5 recordings?

Than you

**Comment by davidak** [comment]
@Fatimuskii the forum or chat would be a better place to ask i think.

I havn't done the math, but i think 5 recordings adds 0,5%, so when you have done 10, it's 1% higher.

**Comment by davidak** [comment]
https://voice.mozilla.org/en/about#how-it-works says now that 2 yes or no votes are needed to accept or reject a clip. So 2x the recording goal is fine.
