### ISSUE TITLE
Document data collection overall and review with Legal

### ISSUE THREAD

**Issue by geroter** [mozilla/voice-web#17]

**Comment by geroter** [comment]
@geroter to take a stab at this and run through Andre and Kelly

**Comment by geroter** [comment]
Basic architecture
https://docs.google.com/drawings/d/12FasUel5NH6poKLcJaxlYr64U6N6YEsyNs-wZJx_y04/edit

**Comment by mikehenrty** [comment]
@geroter how does this bug differ from #12 ?

**Comment by geroter** [comment]
It's an overlap. We can close this one.

**Comment by mikehenrty** [comment]
Closed as duplicate.
