### ISSUE TITLE
The color of the heart makes the text difficult to read.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#170]
![image](https://user-images.githubusercontent.com/311082/27298545-fd2a2830-54dd-11e7-9756-f068fb41a613.png)

**Comment by mikehenrty** [comment]
Any pixel people can help out? I think we just need to lighten the color of the hard slightly on this file:
https://github.com/mozilla/voice-web/blob/7d6bb745801d31cb1ae5673caf3c7928cf44c4fc/web/img/speech-bubble.png

We could also try making the background transparent?

**Comment by Kusaha** [comment]
There you go, hope this will work. Didn't make the transparent background version because I think that would look good at all. (and it's a speech bubble, it supposed to be white)
![speech-bubble](https://user-images.githubusercontent.com/7066695/28748081-5411e60c-74ae-11e7-84b8-e36646c1832b.png)

**Comment by mikehenrty** [comment]
Fixed from @xKeiro 's PR. Thanks!
