### ISSUE TITLE
Clicking twice on stop recording button breaks button

### ISSUE THREAD

**Issue by RobinvanderVliet** [mozilla/voice-web#1706]
When the stop recording button is pressed twice, it breaks the button. It disappears and can't be used again without refreshing the page. I think commit 79b1511 introduced this bug, but I am not sure.

This is how the button looks like afterwards:
![image](https://user-images.githubusercontent.com/692029/50175593-75550b80-02fd-11e9-9498-76dc699cfed9.png)

**Comment by poush** [comment]
I am able to replicate it on official installation, but not on my local installation from the updated master branch. Maybe the official installation is not up to date with the latest commit

**Comment by mritunjaygoutam12** [comment]
@poush same happens with me on double tap stop button on my local installation from the updated master branch
