### ISSUE TITLE
The text says help us validate 5 sentences, but only one appears.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#171]
![image](https://user-images.githubusercontent.com/311082/27298578-1aa3d546-54de-11e7-93c6-a620dbd41ae0.png)

**Comment by kdavis-mozilla** [comment]
@mbebenita I read this as a call to action, do five but here is your first.

**Comment by kdavis-mozilla** [comment]
@mbebenita I guess we need to determine how other users see this.

**Comment by mikehenrty** [comment]
Change text to say, Help us validate sentences.
