### ISSUE TITLE
Some of localized legal docs ready for production

### ISSUE THREAD

**Issue by peiying2** [mozilla/voice-web#1712]
@Gregoor Feel free to push the recently updated/newly added localized legal docs to production: https://github.com/mozilla/legal-docs/pulls?q=is%3Apr+is%3Aclosed. We are still waiting for 6 more locales (x2 docs) to be delivered at a later time. See https://bugzilla.mozilla.org/show_bug.cgi?id=1513394 for details.

**Comment by Gregoor** [comment]
@peiying2 common voice automatically renews the legal docs every 24 hours from that repo, no push necessary :)
