### ISSUE TITLE
Inconsistent buttons

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#172]
![image](https://user-images.githubusercontent.com/311082/27298616-3fb6d46e-54de-11e7-862d-b0b1cfb42d14.png)

![image](https://user-images.githubusercontent.com/311082/27298621-444a70f8-54de-11e7-91bc-7297e20d4640.png)

![image](https://user-images.githubusercontent.com/311082/27298631-49ac1ec0-54de-11e7-86de-9a7caa5d9cce.png)

They all seem like they zoom in by different amounts. It may be that the animation is using a percentage but that ends up looking strange. The save changes button becomes quite big.

**Comment by mikehenrty** [comment]
Nope they all zoom the same, by a factor of 1.1. I think the problem here is the inconsistent sizes with buttons.

**Comment by mikehenrty** [comment]
This will be fixed in an upcoming redesign of the profile page.
