### ISSUE TITLE
User demographics

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1722]
It would be helpful to see graphs of aggregate user demographics, so it would be easy to see which age groups and accents are over- or underrepresented in recordings.

**Comment by Gregoor** [comment]
That'll be included in our new datasets page! 🙂

**Comment by davidak** [comment]
This is now shown on the dataset page:

![Screenshot from 2019-06-08 13-23-34](https://user-images.githubusercontent.com/91113/59146606-ac74c180-89f0-11e9-968a-38404d5cc567.png)

So this issue can get closed?

**Comment by Gregoor** [comment]
True, thanks!
