### ISSUE TITLE
Enforce minimum recording length

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1723]
When validating I find lots of clips where the entire clip is a fraction of a second of background noise. The user evidently clicked record and then stopped it immediately.

The site should not allow users to submit recordings that are obviously too short to be valid. Maybe a 2 second minimum clip length? Or make the length x seconds*number of words?

**Comment by Gregoor** [comment]
We do have an enforced min length, but it was in the sub-second. I increased it to be 1 second, which I think is fair. There's some sentences which could be spoken in under 2 seconds. So I think this should be good for now.
