### ISSUE TITLE
Change color of play button

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1725]
The play button on the verification page is green and is right next to the Yes button, which is also green. Sometimes my brain wants to tap the green button to play but I accidentally approve the clip by mistake. 

This happens most often when I’m not sure about the clip and want to play it again before I make a decision. Also, sometimes the Yes button is not disabled before playing the clip due to bugs with the site, most often after the previous clip was skipped.

**Comment by Gregoor** [comment]
cc @mbransn

**Comment by MichaelKohler** [comment]
This screen has changed in the meantime, I'd say this is ok now.
