### ISSUE TITLE
Email field doesn't look like the others.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#173]
![image](https://user-images.githubusercontent.com/311082/27298684-7ef37d76-54de-11e7-9d3c-025e3b55bbea.png)

The label inside should move outside.

**Comment by DeathCamel57** [comment]
#342 should solve this issue, moving the label above the text input box.

**Comment by mikehenrty** [comment]
Fixes by #342.
https://github.com/mozilla/voice-web/commit/67262a13434fc40cef98e73d31b8df5654ded9f1
