### ISSUE TITLE
Stats showing 0 for "ALL" languages

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/voice-web#1735]
<img width="1410" alt="screenshot 2019-01-02 at 16 49 46" src="https://user-images.githubusercontent.com/330324/50599572-c264e000-0eae-11e9-86d6-00e52920a69b.png">

This shows 0 for the "ALL" languages. When selecting a specific language, the current total is correct.

<img width="1401" alt="screenshot 2019-01-02 at 16 49 56" src="https://user-images.githubusercontent.com/330324/50599591-d01a6580-0eae-11e9-9ae0-1d70f3673127.png">

**Comment by MichaelKohler** [comment]
This possibly regressed since https://github.com/mozilla/voice-web/issues/1680 was filed, as the screenshot there shows it correctly.

**Comment by geroter** [comment]
Verifying that I experience the same behaviour as reported by @MichaelKohler

**Comment by Gregoor** [comment]
Thanks!
