### ISSUE TITLE
Speak does not work for Slovenian language when signed into account

### ISSUE THREAD

**Issue by zerdo90** [mozilla/voice-web#1738]
For few days I see this when trying to contribute to speak section. It happens when I am signed into my account and both on PC and Android. Other languages are working fine.

![11123](https://user-images.githubusercontent.com/26620773/50681782-feae5280-100c-11e9-89eb-35d2d90809e8.jpg)

**Comment by Gregoor** [comment]
Thanks for the report and sorry for the empty screen! Can you tell me how many clips you've recorded in slovenian (you can see that on the dashboard when you change language in the top bar: https://voice.mozilla.org/sl/dashboard)?

**Comment by zerdo90** [comment]
Hi,

5230 in total and 2037 in Slovenian.

**Comment by Gregoor** [comment]
Wow, nice score! Unfortunately it looks like you've exhausted the slovenian sentence corpus. Sorry! We need to collect more sentences (and we are working on a tool for that: https://discourse.mozilla.org/t/we-want-your-feedback-improving-the-sentence-collection/30358/).

For the empty speak page, we're tracking this in #1225.
