### ISSUE TITLE
No clear indication that there is an error in the email field.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#174]
![image](https://user-images.githubusercontent.com/311082/27298746-c1e7dd34-54de-11e7-947c-c2491e4aeae7.png)

**Comment by kdavis-mozilla** [comment]
@mbebenita The red border seems clear to me. What enhancement would you suggest?

**Comment by mikehenrty** [comment]
Let's close this one as not actionable, but we'll leave the other profile bugs open to clean up the validation logic there ie. disabling buttons when they don't do anything.
