### ISSUE TITLE
Some clips not being served?

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#1741]
https://discourse.mozilla.org/t/recordings-are-never-validated/34750

**Comment by poush** [comment]
@Gregoor any suggestions on where to look for debugging, reproduce the situation?

**Comment by Gregoor** [comment]
@poush I just wanted to link to the query that gets clips for voting and then I noticed that it does not order by date (anymore?). So it maybe was an easy fix after all 🙈
