### ISSUE TITLE
rtl problem in arabic and persian website

### ISSUE THREAD

**Issue by herotux** [mozilla/voice-web#1747]
website show texts ltr
maybe need rtl direction for a div to fix this problem

https://voice.mozilla.org/fa

**Comment by herotux** [comment]
Tanks alot :rose:
Yes it is.

**Comment by yarons** [comment]
We are seeing the exact same issues with both Hebrew and Urdu on the staging websites:
Urdu - https://voice.allizom.org/ur
Hebrew - https://voice.allizom.org/he

**Comment by Gregoor** [comment]
Alrighty! I've spend some time looking into RTLing our site. The change should be on staging in a bit. Once it is, would you mind browsing around a bit and flagging issues?

One issue that I know of is the language selection, where the globe is still on the left. I'm going to rewrite that component completely soon anyway, so I didn't want to get too deep into it.

Another thing I was wondering: On the contribution screen the back arrow is pointing to the left. Should it be pointing to the right?

**Comment by peiying2** [comment]
https://voice.allizom.org/dv - the latest RTL language added to CV.

**Comment by peiying2** [comment]
@Gregoor not sure if you can see this without logging in: https://pontoon.mozilla.org/a/base/locale/?all=&o=-5.2.3. This is the best place to confirm that.

Right now we have Arabic, Dhivehi, Hebrew, Persian, Urdu working in CV projects (we have more RTL languages in Pontoon). Another is to get to the language for CV and check the strings' directions - would not advice that.

**Comment by Gregoor** [comment]
Thanks! Unfortunately that link is behind an admin login. I also just saw that the GraphQL also has a direction field. Would you advise against that one as well?

**Comment by 5y** [comment]
@Gregoor 

Just two small problems until now : 

 - The "Optional Demographic Data" drop-down menu on the main page should be mirrored. ("Arrow" transfer the left and "title and content" transfer the right.)

- Back Button and Skip Button in the "Speak" page should be mirrored.

Thank You.

**Comment by Gregoor** [comment]
RE the optional demographic dropdown: Can't do much about that one, as it's a screenshot.

RE the arrows: They're flipped now.

Thanks for the feedback! :)

**Comment by Gregoor** [comment]
@5y the text inputs on the profile seem wrong in RTL languages (text input is always LTR for those). Could I get your take on this?

**Comment by Anooshe** [comment]
@Gregoor In the main page? Could you please send me the link of the profile?

**Comment by 5y** [comment]
@Gregoor Do you mean in the main page? could you please sent me the link of the profile ?

**Comment by Gregoor** [comment]
@5y the profile page: https://voice.allizom.org/fa/profile/info
You need to be logged in to see the page though

**Comment by Gregoor** [comment]
Thanks, that's very helpful! I just pushed a commit addressing those.

Except for the add languages plus sign, as it's already mirrored from the LTR version. Shouldn't it be mirrored in this instance?

**Comment by 5y** [comment]
> Thanks, that's very helpful! I just pushed a commit addressing those.
> 
> Except for the add languages plus sign, as it's already mirrored from the LTR version. Shouldn't it be mirrored in this instance?

@Gregoor  you are very welcome.
It should be aligned looks like following example of Firefox for iOS in Persian.
The point is we put the sign on the right side and in some cases we mirrored the sign too.
![image](https://user-images.githubusercontent.com/1941933/51488209-2d247f80-1dba-11e9-9576-80bb179ac51c.png)

**Comment by Gregoor** [comment]
Alrighty, I moved it to the right. What confused me, is that it's on the right in LTR languages as well:

![screenshot_2019-01-21 common voice by mozilla](https://user-images.githubusercontent.com/4051932/51488773-bd58c980-1da6-11e9-9661-df57f453e61f.png)

I don't have a good intuition for when it should be mirrored and when not, so thanks for guiding me through it :)
