### ISSUE TITLE
Save changes button turns all yellow fields white, except for the email field.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#175]
![image](https://user-images.githubusercontent.com/311082/27298790-e77d8b98-54de-11e7-8aa8-5798030e8840.png)

**Comment by mikehenrty** [comment]
This was by design. There are two save buttons, each only applies to it's own fieldset. My personal feeling is that it would be weird if I click the "Save" next to the email field, and it save my demographics information. Not sure about the other way around for the Save changes button

**Comment by kdavis-mozilla** [comment]
As this is by design I'm going to close.
