### ISSUE TITLE
Infinite login loop on Firefox 60.4.0esr

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1756]
[Environment]:
Windows 10 - Firefox 60.4.0esr

[Steps to reproduce]:
1.Open Firefox with a new profile
2.Go to voice.mozilla.org
3.Login ( passwordless or using LDAP)

[Actual result]:
Infinite login loop

Browser Console errors:
Intl.PluralRules already exists and has NOT been replaced by this polyfill  bundle.js:6:2565
To force, set a global ClobberIntlPluralRules = true  bundle.js:6:2657
unreachable code after return statement

[Note]:
The issue is reproducible for new accounts and for accounts already created.
The issue is not reproducible on Firefox Nightly 66.0a1 or Chrome 
The issue is not reproducible on other websites( e.g. https://web-mozillians-staging.production.paas.mozilla.community/en-US/) using Firefox ESR

**Comment by Gregoor** [comment]
Thanks for the detailed issue!
