### ISSUE TITLE
persian voice 

### ISSUE THREAD

**Issue by herotux** [mozilla/voice-web#1758]
We are complated persian sentences and website translation but persian not lunched yet please do it .we are ready to record theme.
Thanks

**Comment by Gregoor** [comment]
That's awesome! I'm working on making the site more RTL today. I'll put something on staging today and link it here, if you'd like to review it. Then I'll activate Persian next week (since tomorrow is no-deploy friday).

**Comment by herotux** [comment]
Thanks alot .

**Comment by 5y** [comment]
@Gregoor Please let me know if you need any furthermore help on RTL review/improvement.

Thanks 
Reza (L10n Persian Team)

**Comment by herotux** [comment]
we have problem in div class=tabs we have a pic /img/signup-waves.png that cover text and register link
![image](https://user-images.githubusercontent.com/10483351/51346627-56d86080-1ab3-11e9-97d9-8e3b06ee18a0.png)

![image](https://user-images.githubusercontent.com/10483351/51346667-740d2f00-1ab3-11e9-8d83-9fded3d516b6.png)

**Comment by herotux** [comment]
@Gregoor
and we need better font like [vazir](https://github.com/rastikerdar/vazir-font) free font

**Comment by 5y** [comment]
@Gregoor Thank you.
I added two small problems in the mentioned thread.

**Comment by peiying2** [comment]
Also the language drop down menu, seems that the globe and the downward arrow are pushed together.

**Comment by 5y** [comment]
@peiying2  Thank you. I assumed @Gregoor knew on the overlaps in the language drop down and the backgrounds :D

**Comment by Gregoor** [comment]
Yes, we'll retouch the language dropdown soon, which is why I'm careful not to put too much time into it atm.

@herotux RE font:
I created a separate issue for it: #1763

As persian is activated on staging and we're only waiting for next week so that I can deploy (and we'll maybe get some more QA on RTL in general), I'd consider this issue resolved :)

**Comment by aminone** [comment]
"Speak" in [Speak page](https://voice.allizom.org/fa/speak) needs some margin to it's left instead of current margin-right
![common voice by mozilla](https://user-images.githubusercontent.com/6203366/51437179-df235500-1caf-11e9-824a-4914727aa8bf.png)

**Comment by Gregoor** [comment]
Thanks!

**Comment by 5y** [comment]
> Persian is on production now :)

Amazing Job @Gregoor. Thank you.

**Comment by Gregoor** [comment]
Thanks for all your help getting the UX right-ish :)
