### ISSUE TITLE
Review padding and alignment throughout the application

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#176]
In general, there are issues related to padding (mostly because it's inconsistent). For example:

![image](https://user-images.githubusercontent.com/311082/27298827-08edcb3a-54df-11e7-9f15-0cc7e5df0f94.png)

![image](https://user-images.githubusercontent.com/311082/27298849-1d422ab8-54df-11e7-9cb7-ce65cfe73c4d.png)

![image](https://user-images.githubusercontent.com/311082/27298866-287bdeec-54df-11e7-90b1-4917963c1d01.png)

![image](https://user-images.githubusercontent.com/311082/27298871-2d79799a-54df-11e7-912b-2deaf14f5c90.png)

**Comment by mikehenrty** [comment]
This was part of the design that we chose. Closing as invalid.
