### ISSUE TITLE
Search bar at https://voice.mozilla.org/en/languages does not find Japanese

### ISSUE THREAD

**Issue by jhortle** [mozilla/voice-web#1760]
Problem:
Searching "japanese" or "Japanese" in the search bar on webpage https://voice.mozilla.org/en/languages does not bring up Japanese under "In Progress". Searching "english" or "English" brings up English correctly. Searching just "ja" brings up Japanese correctly, for some reason.

Reproduce:
1. Navigate to [page](https://voice.mozilla.org/en/languages).
2. Type "japanese", "Japanese" and "ja" into the search bar.
3. Look at the results.

Browser/OS details:
Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
macOS Mojave 10.14.2

**Comment by Gregoor** [comment]
Not buggy, but limited. Thanks for the report! It was only searching for native names & locale code. So to explain the above:

German: Deuts**ch**land
Chinese: **zh**-TW
Breton: Bre**zho**neg

and so on.

Fix should be live early next week.
