### ISSUE TITLE
Add Basque accents

### ISSUE THREAD

**Issue by Txopi** [mozilla/voice-web#1761]
Please, add these Accents to Basque language:

- Mendebalekoa (Araka + Bizkaia + Gipuzkoako mendebaleko herri batzuk)
- Erdialdekoa edo Nafarra (Gipuzkoa + Nafarroa)
- Nafar-lapurtarra edo Zuberotarra (Lapurdi + Nafarroa Beherea + Zuberoa)

**Comment by Gregoor** [comment]
Heya, you can create a PR to add them here: https://github.com/mozilla/voice-web/blob/master/web/src/stores/demographics.ts

**Comment by Txopi** [comment]
OK, I created a PR: #1778

**Comment by nukeador** [comment]
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
