### ISSUE TITLE
UI issues : RTL regression

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1762]
[Environment]:
Windows 10 

[Steps to reproduce]:
1. Go to https://voice.allizom.org/dv/languages

[Actual result]:
1. The arrow down from languages drop-down is displayed on the right side (Chrome) and on the left side (Firefox), but in both cases overlaps other elements
2. The top logo (animated on page loading) overlaps text

![2019-01-18_14h43_39](https://user-images.githubusercontent.com/41474886/51388286-9776bf00-1b31-11e9-843b-bc77216ef588.png)
![2019-01-18_14h00_50](https://user-images.githubusercontent.com/41474886/51388490-3ef3f180-1b32-11e9-9d05-d58b65f223c5.png)

**Comment by Gregoor** [comment]
Thanks, fixed :)

**Comment by rleitan** [comment]
I still manage to reproduce the issue with the down arrow from languages drop-down. It looks the same on Firefox and Chrome now. 
![2019-01-21_11h03_44](https://user-images.githubusercontent.com/41474886/51463677-7e0d8700-1d6c-11e9-9586-5d973d55926d.png)

**Comment by Gregoor** [comment]
> 
> 
> Also, the dashboard's scrollbar has an extra black line when scrolling up/down on Firefox. (Chrome is not affected)
> ![2019-01-21_11h23_26](https://user-images.githubusercontent.com/41474886/51464741-fc6b2880-1d6e-11e9-86cd-1ed330c58450.png)

this looks like a bug in the english version? Let's track in a separate issue (though I also have trouble reproducing it).

**Comment by rleitan** [comment]
@Gregoor, I logged https://github.com/mozilla/voice-web/issues/1774 for the remaining issue. It seems only Firefox ESR is affected

**Comment by Gregoor** [comment]
Thanks!
