### ISSUE TITLE
Skip button is not working well in Italian

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1767]
[Environment]:
Windows 10

[Steps to reproduce]:
1. Go to https://voice.allizom.org/it/listen
2. Click "Skip" button

[Expected result]:
Other clip should be displayed

[Actual result]:
The text is not displayed and when "Play" button is clicked, the same clip can be heard

**Comment by JAGulin** [comment]
It seems to work on https://voice.mozilla.org/it/listen
Maybe there is a problem with the available strings in Italian for the staging server.

**Comment by MichaelKohler** [comment]
Can't reproduce
