### ISSUE TITLE
Add convenient way to immediately re-record a line

### ISSUE THREAD

**Issue by lucaswerkmeister** [mozilla/voice-web#1768]
When I mess up a line, to re-record it I have to stop the recording, move the mouse over to the “repeat recording” button, click it, and start the recording again. I think for power users it would be nice to offer a faster way to do this: a keyboard shortcut to do all this at once, so that you can instantly repeat the line.

Something similar to this was proposed in #​2 of https://github.com/mozilla/voice-web/issues/313#issuecomment-317114368 (cc @jdittrich and @mikehenrty), though not quite as focused on the “power user” usecase, and the issue has since been closed. (I do agree with @Gregoor that the page now lets me do the things I need, re-recording wise, I just wish it was faster.)

Alternatively, extreme power users apparently [assign this and other actions to a dedicated controller](https://twitter.com/ubahnverleih/status/1087111164461543425) (cc @ubahnverleih), so I guess that’s always an option :)

**Comment by mritunjaygoutam12** [comment]
should it be closed ?

**Comment by Gregoor** [comment]
Yes, thanks!
