### ISSUE TITLE
[Mac OS] Text is not correctly displayed on voice.allizom.org/dv

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1770]
[Environment]:
Mac OS 10.12 - Safari, Chrome

[Steps to reproduce]:
1.Go to voice.allizom.org/dv

[Actual result]:
Text is not correctly displayed
![49344584_2059867770771462_5020243949235732480_n](https://user-images.githubusercontent.com/41474886/51535445-2d238e80-1e51-11e9-8e51-967891eec6e7.png)

[Note]:
Firefox is not affected

**Comment by Gregoor** [comment]
Works for me, I think it depends on what fonts are installed on your machine. Imo it's fair to assume that Maldivian speakers have the right fonts installed.
