### ISSUE TITLE
Yes/No buttons incorrectly enabled after skipping

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1775]
When validating, the Yes/No buttons are only supposed to become enabled once the user has listened to the clip. However, in certain situations they can become enabled before the clip has been played.

Steps to reproduce:
1. Listen to a clip all the way through so that the Yes/No buttons become enabled.
2. Press the Skip button.

Result:
The new clip has the Yes/No buttons already enabled before you’ve even listened to it.

**Comment by Gregoor** [comment]
Oh we actually fixed that one :)
