### ISSUE TITLE
Text is not aligned to check box

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#178]
![image](https://user-images.githubusercontent.com/311082/27298967-8f0a074c-54df-11e7-85e2-9d02ec9f097b.png)

The placement of the "I'd like .." text doesn't look right.

**Comment by kdavis-mozilla** [comment]
I seem a similar alignment for OS X + Firefox

**Comment by kdavis-mozilla** [comment]
@mbebenita What OS + Browser are you using?

**Comment by DeathCamel57** [comment]
Same issue on:
**Browser:** Vivaldi | 1.8.770.56 (Stable channel) (64-bit) 
**OS:** Ubuntu 17.04 zesty
**Kernel:** x86_64 Linux 4.10.0-28-generic

![Picture](https://user-images.githubusercontent.com/1226646/28507383-67f388f4-7000-11e7-9159-046586ff7969.png)

**Comment by DeathCamel57** [comment]
#343 hopefully fixes it.
The description line had a fixed `1rem` left padding.
However, the checkbox above didn't have a set size. This caused different web browsers to render the size of the button differently.

The checkbox now has a size of `.8rem` wide and tall, with a `.1rem` margin on all sides.

**Comment by mikehenrty** [comment]
Fixed in #343
