### ISSUE TITLE
Right alignment on Profile screen is off.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#179]
![image](https://user-images.githubusercontent.com/311082/27299058-daf29f66-54df-11e7-9cd9-c5c6536fa4ad.png)

**Comment by kdavis-mozilla** [comment]
@mbebenita What browser and os were you using? For OS X + Firefox alignment seems fine to me

![image](https://user-images.githubusercontent.com/12054740/27427533-a213cf50-573f-11e7-837a-9e46abf6e220.png)

**Comment by mikehenrty** [comment]
can't repro for now
