### ISSUE TITLE
Referral API

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1791]
Here’s something that might help participation rates. I contribute to the project because I plan to eventually deploy STT capabilities to my company’s cloud platform.

I had the idea of asking people to contribute to Common Voice in order to get some kind of non-financial extra feature/benefit, however there is no way of confirming if they actually did so.

So what would be useful would be a referral API where I could generate a URL or a code they could enter on the CV site with a goal like “record 10 sentences”. I could then check server-side through the API that they completed the goal with a validation approval score of >85% to unlock the reward at my end.

**Comment by MichaelKohler** [comment]
Let's have this discussion over at Discourse.
