### ISSUE TITLE
Website doesn't perform well on tablet

### ISSUE THREAD

**Issue by Fjoerfoks** [mozilla/voice-web#1792]
As mentioned on https://discourse.mozilla.org/t/website-malfunction-on-tablet/35316 I'd like to raise the problem here too.
When I open up the website in either Firefox, Firefox Focus or Chrome on a tablet, the website doesn't perform well. You can't zoom the page and it seems it is not possible to scroll up or down.
Don't know if this is going to fixed, since it looks like apps are coming up for Android and iOS, but I think it should work properly on a tablet too.

**Comment by Gregoor** [comment]
Thanks for reporting this. It seems to affect certain device sizes (which is why we haven't been seeing it on iPads). This is going to be fixed, though I can't tell you when atm.
