### ISSUE TITLE
Show how many validators are online

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1793]
The home page shows how many “voices” are online for each language, which I assume means how many people are currently on the recording page.

But why does it only show speakers and not validators?

The reason I mention this is that I feel that CV may have a shortage of validators, at least in English. How do I know this? I have over 10,000 validations pending on the stats page, or in other words 10,000 clips I have validated that have yet to be validated by others.

Perhaps the site could note when there are lots of speakers online but few validators and encourage users to validate?

**Comment by mritunjaygoutam12** [comment]
> The home page shows how many “voices” are online for each language, which I assume means how many people are currently on the recording page.

I think voices online means here how many people are accessing the page it is not specific to task(speaking, validating) as I understand by looking at saveActivity function in [clip.ts](https://github.com/mozilla/voice-web/blob/c9eaf734aa63c60c481c522faa6b125bb356377d/server/src/lib/clip.ts#L37) . If I am wrong correct me. By the way we can have this feature for online validators to increase validators .

**Comment by Gregoor** [comment]
Spot-on, it indeed shows everyone who's online in a language (not just people who are contributing).
