### ISSUE TITLE
New Datasets : The page is not loaded on iOS

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1796]
[Environment]:
iOS version 11.4.1 - Firefox, Safari, Chrome

[Steps to reproduce]:
1.Open https://voice.allizom.org/am/new-datasets

[Expected results]:
The page should be loaded

[Actual results]:
"An error occurred. Sorry"

<img width="375" alt="imeage1" src="https://user-images.githubusercontent.com/41474886/52416277-eb9e0f00-2af1-11e9-9655-a4a584b94820.png">

**Comment by MaxiHD** [comment]
You type the incorrect url the url is: voice.mozilla.org

**Comment by Gregoor** [comment]
@Makilan voice.allizom.org is the staging url (so the URL in the first post is very much correct)
