### ISSUE TITLE
Tabbing between profile fields should go from email->checkbox, not email->submit

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#180]

**Comment by kdavis-mozilla** [comment]
@mbebenita Could you give a bit more detail. Which browser, if it was a browser. What happened vs what was expected to happen. 

From my own testing in Firefox on OS X the only strangeness is the first tab from the email field. It doesn't directly go to the checkbox. Is this what you mean?

**Comment by mikehenrty** [comment]
Updated the detail to be about the email->checkbox transition.
