### ISSUE TITLE
Balance validation between old and new clips

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1804]
My validation queue contains lots of clips from The Alchemist, SNIPS and other corpora that has since been removed from the rotation. Looking back at the commit history, it would appear this data was removed on Dec 6th 2017 (https://github.com/mozilla/voice-web/commit/0a405690e860c5a3da923d8838bb8a588fd07a0d), meaning that everything being validated right now (in English at least) has been in the queue for more than a year.

This means that it will be more than a year before any sentences added through Sentence Collector today will be part of the validated set. The new sentences are higher quality than the old ones and have far fewer errors. They are also more consistent due to validation and specific guidelines. It also means that if it's discovered that CV has word coverage problems, it will take more than a year to fix.

So maybe it's best to tackle the queue at both ends? Perhaps out of the 5 clips for validation, 3 are old and 2 are new? Or 4 old, 1 new? That would mean the old queue was still being churned through but at the same time we'd be getting a little bit of coverage of the new sentences.

**Comment by Gregoor** [comment]
I like that idea, thanks for chiming in! I'll bring it up in sprint planning.

**Comment by MichaelNMaggs** [comment]
Agreed.  Presenting recently-recorded sentences for review is also the only way that new readers will get any feedback on their recordings.  There's at least one new reader who now has over 5000 recordings, with zero validated; I hope they're good, but that's an awful lot of time wasted if it turns out there are problems.

**Comment by davidak** [comment]
Could we prioritize recordings of new users, so say their 10 first recordings get verified ASAP.

In combination with more detailed feedback (https://github.com/mozilla/voice-web/issues/1406), we can prevent many bad recordings (https://github.com/mozilla/voice-web/issues/1833)!

**Comment by MichaelKohler** [comment]
Let's discuss this over at https://discourse.mozilla.org/c/voice/239
