### ISSUE TITLE
[new-datasets] Show localized language as default in form select

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1808]
Language selector dropdown is empty when landing on new datasets page, prefer that it be populated with the current localization selection by default.

![download-language-select](https://user-images.githubusercontent.com/18686986/52814477-1d165d80-3051-11e9-9527-a2958716351f.png)

**Comment by Gregoor** [comment]
just an artifcat of the backend bundling infra not being quite ready yet, hence there being no data.
