### ISSUE TITLE
[new-datasets] Language selector (dropdown) border color

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1809]
Language selector border grey too light, update to #F9F9F9 to align with designs. 

Note: If easier to make a global color change to accommodate all dropdowns, whether on white or grey backgrounds, please do so (e.g. profile page dropdown selectors are same light grey but more visible as they are on white background).

On staging:
![download-language-select](https://user-images.githubusercontent.com/18686986/52814782-d1b07f00-3051-11e9-8219-8a481be359fe.png)

As designed:
![designed-dropdown-border-f9f9f9](https://user-images.githubusercontent.com/18686986/52814788-d6753300-3051-11e9-8bc3-04759103c99b.png)

**Comment by mbransn** [comment]
@Gregoor same goes for the email field as well, border color too light. Can we update global styles to the darker grey #F9F9F9.

![email-field-staging](https://user-images.githubusercontent.com/18686986/52819402-104c3680-305e-11e9-8152-26bf6c581aed.png)

**Comment by Gregoor** [comment]
#f9f9f9 looks lighter than what we have, so I color picked from the designs and got #e6e4e1 which I set to the global input border color
