### ISSUE TITLE
App is doubled vertically when clicking any nav menu items

### ISSUE THREAD

**Issue by robertpara** [mozilla/voice-web#181]
See screenshot. Repro'd in Chrome Version 59.0.3071.104, Windows 10

![image](https://user-images.githubusercontent.com/2819924/27299345-f5b6aac6-54e0-11e7-8746-af2a1ee566f7.png)

**Comment by mikehenrty** [comment]
I just tested on windows 10 with chrome, and I couldn't reproduce. @robertpara can you still repro?

**Comment by robertpara** [comment]
can't repro anymore, looks fixed @mikehenrty

**Comment by mikehenrty** [comment]
Great, thanks for the report and for following up @robertpara
