### ISSUE TITLE
[new-datasets] Add (m/k/g)B to dataset size notation

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1810]
Current staging build is missing the size notation after the number -- (M/K/G)B, see below:

On staging:
![download-language-select](https://user-images.githubusercontent.com/18686986/52814976-4daac700-3052-11e9-9834-424ad7fa0583.png)

As designed:
![designed-dropdown-border-f9f9f9](https://user-images.githubusercontent.com/18686986/52814982-526f7b00-3052-11e9-96a4-c1b6269bcc0c.png)

**Comment by Gregoor** [comment]
Will also add once we have real data
