### ISSUE TITLE
[new-datasets] Type appearing bold in multiple browsers/devices

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1812]
Most of the type across the page is appearing bolder / heavier than intended. Dropping in various screen shots of what I'm seeing on desktop that differs from styles in the design. @grailean can you help track these improvements w/ @Gregoor?

![screen shot 2019-02-14 at 2 05 03 pm](https://user-images.githubusercontent.com/18686986/52820767-c9f8d680-3061-11e9-9176-4feeb6b87f92.png)

![screen shot 2019-02-14 at 2 05 14 pm](https://user-images.githubusercontent.com/18686986/52820771-cebd8a80-3061-11e9-9d57-741d71183d4c.png)

![screen shot 2019-02-14 at 2 04 54 pm](https://user-images.githubusercontent.com/18686986/52820775-d4b36b80-3061-11e9-88a3-4da8e9732b2b.png)

![screen shot 2019-02-14 at 2 04 48 pm](https://user-images.githubusercontent.com/18686986/52820783-d9781f80-3061-11e9-8273-725e3bc1c8a8.png)

![screen shot 2019-02-14 at 2 00 48 pm](https://user-images.githubusercontent.com/18686986/52820791-dd0ba680-3061-11e9-8504-6c591076b98c.png)

**Comment by Gregoor** [comment]
We load [ZillaSlab](https://fonts.google.com/specimen/Zilla+Slab) in regular (400) and semi-bold (600). And I just checked the zeplin values for these screens and they align with what we're using on the site

**Comment by Gregoor** [comment]
@mbransn @georai Don't really know what to do here.

**Comment by mbransn** [comment]
Appears there isn't anything you can do. Browser artifact w/type is often an annoyance (at least on the design side). As long as the page is loading well and you've got the best values I think we're fine. Thanks for looking into it!
