### ISSUE TITLE
[new-datasets] Email component styling updates

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1813]
Various updates needed for email component styling, focusing on desktop first but most also affect mobile. cc @grailean for help tracking progress:
- subscribe button is too wide (on chrome it doesn't have a fill)
- checkbox appears to be browser driven, can we implement based on our designs?
- Subscribe button needs a hover state (dim or inverse)
- All type appears too heavy (addressed in #1812)

On staging:
![screen shot 2019-02-14 at 1 59 10 pm](https://user-images.githubusercontent.com/18686986/52821359-6b345c80-3063-11e9-8953-0717de923a85.png)

As designed:
![screen shot 2019-02-14 at 2 04 54 pm](https://user-images.githubusercontent.com/18686986/52821367-725b6a80-3063-11e9-9c75-722d4b652ec2.png)

**Comment by Gregoor** [comment]
it's only without fill when disabled (no email or checkbox not checked). There's also a bit of a hover state, though I guess it's a a bit subtle.

**Comment by Gregoor** [comment]
@georai I guess I'd need direction on how disabled should look otherwise

**Comment by georai** [comment]
@Gregoor adding in zeplin the hover state, disabled : https://www.dropbox.com/s/71okxnxn2xwxemd/Screenshot%202019-02-18%2013.44.10.png?dl=0
Uploaded in Zeplin.
