### ISSUE TITLE
Sentence Collector: ensure valid ending punctuation for uploaded sentences

### ISSUE THREAD

**Issue by MichaelNMaggs** [mozilla/voice-web#1815]
I see from recent sentence validations that quite a few texts are being uploaded with non-standard terminal punctuation (particularly commas) such as

_Robbery, bribery, fraud,_

These are causing differences between reviewers, with some such as myself ignoring the final comma as it makes no difference to the reader,  while others reject the text as invalid.  This particular example has been accepted on a two to one vote.  Many seem to be going the same way, but we really should not need to be voting on an issue which could so easily be dealt with by the sentence upload filter.

It would be very helpful if, at a minimum, the upload filter could block texts that end with a comma.  To be slightly more sophisticated, the English filter could block uploads having any terminal punctuation which is neither a full stop, a question mark, an exclamation mark, a closing parenthesis, or a single or double quotation mark.

**Comment by Gregoor** [comment]
Can you repost this issue to the [sentence-collector issues](https://github.com/Common-Voice/sentence-collector/issues)? Thanks!
