### ISSUE TITLE
[new-datasets] Mobile get-started subnav improvements

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1817]
@Gregoor @grailean can you both work together to align expectations for subnav implementation on mobile? The current build is missing the third subnav element and the side scroll functionality is missing.

Expected UX: subnav is sidescroll with three list items; only content for the selected list item is visible on the page. (currently all content is stacked on the page, too much for mobile)

![screen shot 2019-02-14 at 2 45 24 pm](https://user-images.githubusercontent.com/18686986/52822704-535ed780-3067-11e9-9371-c32bfa67035f.png)

**Comment by Gregoor** [comment]
it does have side scroll and the third items is there. Should we maybe have an indicator? Not sure if there's a straightforward cross browser way, but I can spend some research time.

**Comment by mbransn** [comment]
@Gregoor the space between the 2nd and 3rd items seems to be wider than between 1st and 2nd. If we decrease that spacing the 3rd item would then be peaking / partially visible and indicated that it's side scroll-able. See screenshot from [zeplin](https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5bfbfa59a6dc504991a014e2) below:

![screen shot 2019-02-19 at 3 02 25 pm](https://user-images.githubusercontent.com/18686986/53053891-8fbf7880-3457-11e9-9278-ee20c9130959.png)

Ideally the content for each section would only be visible if the subnav item is selected. This would cut down on the amount of page jump we're experiencing and remove the need for the subnav to be sticky on mobile. cc @georai

**Comment by Gregoor** [comment]
fixed the width issue. RE having it be a tabs interface on mobile: This is a heavier lift. Can we stay with the sticky nav for now?

**Comment by mbransn** [comment]
Yeah I'm good with that. :) Thanks for fixing the width!

**Comment by georai** [comment]
@Gregoor @mbransn  https://invis.io/2NNFARMCU3Q#/328733955_Datasets_Mobile_1

I created how the menu needs to look here. uploaded in zeplin.

**Comment by mbransn** [comment]
@georai thanks for this...assuming when the menu is open it'll just use native select UI?

@Gregoor ^^ this is another option, but it is not a blocker to release. Take a look and let us know what you think.

**Comment by grailean** [comment]
Yes.

**Comment by Gregoor** [comment]
Interesting! Looks more straightforward then I thought, but I won't get to it before release.

**Comment by mbransn** [comment]
@Gregoor I just opened #1839 to track future iteration of this. Let's review options once the page is up for a bit.
