### ISSUE TITLE
Unable to login or register

### ISSUE THREAD

**Issue by ReidAnderson** [mozilla/voice-web#1818]
Hello,

I really hope I'm not missing something obvious in the UI here, but I can't seem to login or register for an account. Here's my tale in picture form:

I hit the login/signup button.

![image](https://user-images.githubusercontent.com/1248890/52830535-b5830100-3096-11e9-9fbc-c07263b1c119.png)

I get taken to a page that has a place for an email, but no sign up option.

![image](https://user-images.githubusercontent.com/1248890/52830557-d64b5680-3096-11e9-9987-b2dc9f6fc66d.png)

Even if I enter the email that I think I may have registered for an account with at one point last year, my password doesn't work, and there's no recovery option. Hitting the link to login with another account just sends me back to the email entry screen. 

![image](https://user-images.githubusercontent.com/1248890/52830619-20343c80-3097-11e9-9d88-85216e54ac16.png)

Again, I'm a little worried I'm missing something uber obvious here and apologies for the time waste if so. But I can't seem to figure it out. Let me know if there's any other information I can provide.

Thanks

**Comment by Gregoor** [comment]
@hmitsch can you help?

**Comment by hmitsch** [comment]
Hi @ReidAnderson,

sorry for the late reply. You have a _Contributor LDAP_ account registered on the email address listed on your Mozillians.org profile (https://mozillians.org/u/RAnderson/).

For this reason, the authentication flow for you is:
* Enter your email `r**n@gmail.com`
* Enter your Mozilla LDAP password
* Enter MFA code

Are you not using your _Contributor LDAP_ any longer? You probably used that for checkins to the Mercurial source code repository.

If you don't need that LDAP account any longer, we can remove it and you will then be able to authenticate using passwordless email.

Best regards,
   Henrik

**Comment by ReidAnderson** [comment]
Hello,

To be honest I had forgotten that I had an LDAP account. I haven't committed to the Mercurial source code repository in a number of years, and my Firefox account lets me access mozillians. With that and unless I'm missing something, I think it probably makes the most sense to remove the LDAP account.

Thanks for the response,
Reid

**Comment by hmitsch** [comment]
Contributor LDAP decommissioning is tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1529084

@ReidAnderson, I am closing this ticket. Once the bugzilla ticket is closed, you should be able to login to Common Voice.

Thanks for all the love and care you put into this. It's great to see a Lightning contributor resurface as a Voice contributor. The Mozilla network rules!

Best regards,
   Henrik

**Comment by Gregoor** [comment]
Thanks Henrik!
