### ISSUE TITLE
New Datasets page is displayed only in English

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1819]
[Steps to reproduce]:
1. Open https://voice.allizom.org/en/new-datasets page
2. Change language from the language drop-down

[Expected results]:
New datasets page should be displayed in selected language

[Actual results]:
Datasets page is displayed in English, but the options displayed in the navigation bar are displayed in the language selected

**Comment by Gregoor** [comment]
huh, works for me

**Comment by rleitan** [comment]
It's reproducible only for ADY, AF, AM, AN, AS languages. Not sure if this is unexpected for now? It think the issue can be closed
@Gregoor

**Comment by poush** [comment]
I'm able to reproduce the same. It works only for English. Opening this [link](https://voice.allizom.org/an/new-datasets) directly gives a blank page. This is because https://voice.allizom.org/locales/an/messages.ftl is not found on the server

**Comment by Gregoor** [comment]
That's exactly right, those languages don't have the necessary translation files yet. I guess a check would be nice-to-have

**Comment by bobchao** [comment]
It might be some kind of fallback: with a browser specified accept languages as "zh-TW,en-US;q=0.8,en;q=0.5,zh;q=0.3", it shows zh-TW after you select ADY.

![2019-03-05 12 23 39](https://user-images.githubusercontent.com/168931/53780923-8f3bdd00-3f41-11e9-952e-eaa62e87881e.png)
