### ISSUE TITLE
Loading animation is broken on IE11, Windows 10

### ISSUE THREAD

**Issue by robertpara** [mozilla/voice-web#182]
![image](https://user-images.githubusercontent.com/2819924/27299700-120f0b0e-54e2-11e7-9ff5-aa2664d51a6c.png)

**Comment by paulsilaghi** [comment]
dupe of https://github.com/mozilla/voice-web/issues/142

**Comment by mikehenrty** [comment]
I don't think this is a dupe of #142, since this one is only about the loading animation itself, whereas that one is about the app never even loading.

**Comment by kenrick95** [comment]
I'm guessing that this issue is caused by the usage of CSS variables, which are unsupported in IE.

![capture-css-var](https://user-images.githubusercontent.com/3090380/29004083-88a11c0c-7af4-11e7-9a26-b33bffdf1d6e.PNG)

**Comment by mikehenrty** [comment]
@kenrick95 here's our integration server with your changes:
https://voice.allizom.org/

What do you think, can we call this fixed?

**Comment by kenrick95** [comment]
I think yes, we can close it. :tada:

![giphy](https://user-images.githubusercontent.com/3090380/29177745-13e65cca-7e22-11e7-8a71-4613745ed725.gif)
