### ISSUE TITLE
New Datasets: Newsletter subscription can be done with invalid email(format)

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1820]
STR:
1.Go to new datasets page
2.Go to Newsletter subscription section
3. Check the Privacy Policy checkbox
4. Enter invalid email: e.g. x@y 

[Expected result]:
The email should be seen as invalid

[Actual result]:
Subscribe button becomes actionable

[Note]:
The issue is not reproducible with e.g. x@

**Comment by Gregoor** [comment]
[It's notoriously hard to correctly validate email addresses](https://en.wikipedia.org/wiki/Email_address#Validation_and_verification), browsers implementation, which this form relies on, errs on the side of being overly lenient. I'm okay with that.
