### ISSUE TITLE
[new-datasets] Input style 

### ISSUE THREAD

**Issue by georai** [mozilla/voice-web#1825]
@Gregoor The input field needs to be different: https://www.dropbox.com/s/r72efc96n994wi9/Screenshot%202019-02-18%2013.51.24.png?dl=0 
with 2px corner radius.

**Comment by georai** [comment]
@Gregoor Also, I made some changes for the mobile view: https://invis.io/2NNFARMCU3Q#/328733955_Datasets_Mobile_1

**Comment by Gregoor** [comment]
fixed the radius! Let's track the other mobile view separately
