### ISSUE TITLE
Blank page displayed when opening https://voice.allizom.org/ ADY, AF, AM, AN, AS 

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1827]
[STR]:
1.Open https://voice.allizom.org/an/new-datasets

[Expected result]:
The page should be correctly displayed

[Actual result]:
Blank page

[Note]:
The issue is not reproducible if the page is already loaded in another language ( e.g. EN), then select one of the affected languages ( e.g. ADY)

**Comment by Gregoor** [comment]
might've accidently fixed it. Works for me atm.
