### ISSUE TITLE
Can't accept or refuse sentences

### ISSUE THREAD

**Issue by dag7dev** [mozilla/voice-web#1829]
Hello, as the title, I can't directly accept or refuse any sentence unless I fully hear them.
This is so unconfortable, because I need to fully hear the sentence while I hear at first which it is wrong so I'd like to refuse it, but it takes me more time than the usual.

**Comment by Gregoor** [comment]
Hello, you can actually down-vote a clip after 3 seconds. For up-voting we need to make sure the full clip is heard, otherwise we risk having clips with extra utterances.
