### ISSUE TITLE
Test microphone access on Chrome / Windows

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#183]
I tried this several times and on Windows. I I had previously disabled the microphone, i can't get it enabled again for the app. I get stuck in a loop. Could just be me, but it would be good to make sure this is not happening for others as well.

**Comment by mikehenrty** [comment]
Unfortunately, we have no control over this. If the user clicks the "Block Always" or "Never Allow" option, most user agents will not display a prompt to the user again until they manually allow this in settings.

**Comment by paulsilaghi** [comment]
In Chrome, you have to click on the left of the location bar and then allow the mic from the list. I'm very happy to say Firefox has a better permissions handling.

**Comment by kdavis-mozilla** [comment]
As this is a UI/UX issue with the Chrome browser on Windows and out of our control, I'm going to close this.
