### ISSUE TITLE
[New Datasets]: Other voice Datasets UI issues

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1831]
[Environment]:
iOS (iPhone 6)- Firefox, Safari

[STR]:
1.Open https://voice.allizom.org/an/new-datasets
2.Scroll down until "Other voice Datasets" section
3.Click "See more" button from LibriSpeech
4.Click "See more" button from TED-LIUM Corpus

[Expected result]:
3. "Download" button should be displayed (LibriSpeech section)
4. "See less" button should be correctly displayed
5."See more" button should be named "More" and "See less" - "Close" https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5bfbfa59a6dc504991a014e2

[Actual result]:
3. "Download" button is not displayed (LibriSpeech section)
4. "See less" button is truncated

![img_0045](https://user-images.githubusercontent.com/41474886/53106721-47c65180-353c-11e9-9b94-36b75d9ac7f1.PNG)

[Note]:
The issue is not reproducible on Samsung 8

**Comment by Gregoor** [comment]
LibriSpeech doesn't have a single downloadable thing, which is why there's no  button for it.

**Comment by rleitan** [comment]
I confirm it's fixed
