### ISSUE TITLE
Download checkboxes are not correctly displayed

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1832]
[Environment]:
iOS (iPhone 6)- Firefox, Safari

[STR]:
1.Open https://voice.allizom.org/an/new-datasets
2.Click "Enter Email to Download"

[Actual result]:
Download checkboxes are not correctly displayed: both for checked and unchecked state

![img_0046](https://user-images.githubusercontent.com/41474886/53107905-bdcbb800-353e-11e9-86f0-535b08f4be5d.PNG)

[Note]:
Not reproducible on Android

**Comment by rleitan** [comment]
Please note that this also happens to the checkbox from Subscribe section

**Comment by poush** [comment]
This page seems blank at my end (on both firefox and chrome)

**Comment by poush** [comment]
It worked On changing it to "en". Is this normal or a possible bug?

**Comment by rleitan** [comment]
Fixed, great!
