### ISSUE TITLE
[iOS] Prevent webapp content from being selected inside the Webview

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voice-web#184]

**Comment by andrenatal** [comment]
Test with this initially:

`{
    -webkit-touch-callout: none;
    -webkit-user-select: none;
}
`

**Comment by mikehenrty** [comment]
@andrenatal this seems fixed to me. what do you think?

**Comment by kdavis-mozilla** [comment]
@andrenatal @mikehenrty I can still select text on iPad + iPhone in the iOS app.

**Comment by andrenatal** [comment]
Me too.

**Comment by MichaelKohler** [comment]
Given that the focus will be on the Web experience and not on the iOS experience, I'm closing this.
