### ISSUE TITLE
Subscribe banner is still displayed after user subscribes to newsletter

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1841]
**STR:**
1. Login to voice.allizom.org
2. Navigate to new datasets page
3. Scroll down to the "Subscribe to our newsletter" section
4. Click Subscribe button

**Expected:**
Subscribe banner disappears, as user is subscribed.

**Actual:**
Subscribe banner is still displayed, the button is disabled. After doing a page refresh, the button is enabled again.  

**Note:**
This also happens for users who are not logged in.

**Comment by rleitan** [comment]
I confirm it's fixed!

**Comment by viorelaioia** [comment]
@Gregoor , for logged in users the Subscribe banner is still displayed after the users subscribes and refreshes the Datasets page. I would expect to show the banner for logged in users only until they subscribe. Thoughts?
