### ISSUE TITLE
[new-datasets] Download button is missing a language name

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/voice-web#1844]
Download button for Common Voice dataset: ✅
![image](https://user-images.githubusercontent.com/1294206/53301279-afd0ac80-3848-11e9-834b-865ff94ae962.png)

Download button for others datasets: ❌
![image](https://user-images.githubusercontent.com/1294206/53301048-3df76380-3846-11e9-9890-c9f008b17f0b.png)

While this trick works in English, other languages may expect something after `Download` in “Download { $language }”, or use different formatting to make it work with the different values. So the `download-language` string can’t be used sometimes with a language value, and some other times without it, to only display “Download”.

My suggestions on how this can be fixed:

- Always provide a value to the `{ $language }` variable
Or
- Expose a new string without a variable: `download_button = Download`

It may be that the code passing the value is not yet ready, but I wanted to report this early as it may require exposing a new string.

**Comment by Gregoor** [comment]
Thanks for reporting this! I indeed thought I could just reuse that string (and reduce the localization burden). I'll add a new string then!
