### ISSUE TITLE
When I download dataset, I can submit empty email field

### ISSUE THREAD

**Issue by MekliCZ** [mozilla/voice-web#1846]
When I submit empty email field, it doesn't throw any error, just „Thanks, we'll be in touch“

**Comment by r00ster91** [comment]
I think this is fixed now. When I didn't enter an email, I can't click **Download Language** (the button is gray).
![image](https://user-images.githubusercontent.com/35064754/53584113-37892480-3b83-11e9-9510-f6072aa869ba.png)

**Comment by Gregoor** [comment]
It is! Thanks for reporting this
