### ISSUE TITLE
Add a microphone test button

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1848]
There are lots of things that could cause bad recordings and there really isn’t a clear way to tell in CV if my microphone is setup correctly in my OS, the recording volume is acceptable, my browser is correctly allowing access to the mic, etc.

So what I often do is record the first clip as just a mic test, play it back and then re-record it correctly.

There are lots of blank clips in the validation queue and it occurred to me today that people may have actually intended these to be recordings but there was some issue with the mic they didn’t know about (it seems to be uncommon for people to play their recordings back again).

So an actual mic test button or maybe a mic test page that appears when the user first clicks the recording page would make this easier and hopefully would reduce the number of blank or low-volume recordings.

**Comment by MichaelNMaggs** [comment]
Yes, this would be really helpful.

**Comment by Parikshit-Hooda** [comment]
What we can do is reroute them to a third party website where they can properly setup their microphone. How does this sound? I would be happy to raise a PR if people agree on this.

**Comment by dabinat** [comment]
There could be site-specific browser settings or plugins that are preventing Common Voice from accessing the mic, so being able to record on another site wouldn't necessarily mean that everything would work properly on Common Voice.

**Comment by MichaelKohler** [comment]
Let's discuss this over at https://discourse.mozilla.org/c/voice/239 and then document the solution in GitHub.
