### ISSUE TITLE
SentenceCollector: loading page too slow

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/voice-web#1849]
@nukeador - maybe we can calculate the number of sentences collected once a day and cache that number instead of counting in real-time?

This message on the [home page](https://common-voice.github.io/sentence-collector/#/) takes too long to load.

First you see this:

```
Loading sentence collector data...
```

Then later, this:

```
The Common Voice Sentence Collector has collected 279499 sentences in 29 languages!
```

**Comment by Gregoor** [comment]
Heya, can you move the issue over to the sentence collector issue tracker: https://github.com/Common-Voice/sentence-collector/issues/

Thanks!

**Comment by JRMeyer** [comment]
thanks for the pointer:)
