### ISSUE TITLE
local setup

### ISSUE THREAD

**Issue by bayethiernodiop** [mozilla/voice-web#1852]
Hello, need help.
is there a guide to setup voice-web on a local server, because i am in a hurry and need to build a small audio to text data in WOLOF language from multiple users.
Any quick way of doing this.
Thx in advance.

**Comment by Gregoor** [comment]
Heya, unfortunately it's not super straightforward, but here's the guide:
https://github.com/mozilla/voice-web/blob/master/CONTRIBUTING.md

**Comment by bayethiernodiop** [comment]
ok thanks a lot, but at least it's possible to use this project, add a language and it's transcripts to build a dataset.

**Comment by Gregoor** [comment]
Yes, very much so! If you to add a new language, you'd need to add a localization on Pontoon:
http://pontoon.mozilla.org/

And once it's translated you can use the sentence collector to start collecting and verifying sentences for it:
https://common-voice.github.io/sentence-collector/

Once it's translated and it has 5k sentences, we'll unlock it on the site!

**Comment by bayethiernodiop** [comment]
Yes i'm aware of this process, but i don't need to translate the website or have 5k transcriptions, i just wanna collect something like 20 speakers inside my companies for about 50 sentences. and use that to fine tune an ASR model built with kaldi. Of course i'm planning to made the wolof language disponible in common voice but for now as i said i'm in a hurry. thx for your quick responses.

**Comment by Gregoor** [comment]
Fair enough and thanks for thinking about publishing it! :)

**Comment by bayethiernodiop** [comment]
Does this mean what i want now is not possible even when deploying the project locally?

**Comment by Gregoor** [comment]
It is possible. You'd need to add your sentences under `/server/data/:your-locale-code`, add your translation under `/web/locales/:your-locale-code` (or just copy the english one) and then if you re-run the `import-locales` script, it might just work. That's from the top of my head, haven't tried it yet and you might have to do some fumbling to figure it out exactly.

**Comment by bayethiernodiop** [comment]
oh perfect. thanks a lot. closing this issue.
