### ISSUE TITLE
Attempting to record Urdu clips redirects to Urdu

### ISSUE THREAD

**Issue by amingilani** [mozilla/voice-web#1857]
I've added Urdu as my native language. Trying to record Urdu opens `https://voice.mozilla.org/en/speak`, changing it to `https://voice.mozilla.org/ur/speak` redirects back to the former.

The text on the page is in English. Here's a screenshot

<img width="1370" alt="screen shot 2019-02-28 at 8 52 54 pm" src="https://user-images.githubusercontent.com/1188552/53579248-0a487080-3b9b-11e9-9d62-205ddc7af770.png">

**Comment by GAntoine** [comment]
Urdu hasn't yet been launched (as per [languages](https://voice.mozilla.org/en/languages`)), so the site and speak/listen isn't yet available.

**Comment by amingilani** [comment]
In that case, you likely want to remove the Urdu tab in recording page. I'll send a screenshot, currently I'm AFK.

**Comment by amingilani** [comment]
In that case, you likely want to remove the Urdu tab in recording page. I'll send a screenshot, currently I'm AFK.

**Comment by ftyers** [comment]
@amingilani if you would like to enable Urdu, it can be done by following these steps:

* Finish translating [Common Voice](https://pontoon.mozilla.org/ur/common-voice/) in [Pontoon](https://pontoon.mozilla.org/)
* Make an account in [sentence collector](https://common-voice.github.io/sentence-collector/), add Urdu language in your profile and add and validate sentences

After these two steps are done, Urdu can be enabled for collection in Common Voice. If you would like help with any of these steps, please feel free to ping me.
