### ISSUE TITLE
validation problem with the docker installation

### ISSUE THREAD

**Issue by bayethiernodiop** [mozilla/voice-web#1859]
with the help of @Gregoor  i managed to install locally the project using the docker setup; recording is working but can not validate, the listen page show the audios but when i click on play button the audio is not stopping and i can only click the NO button and not the OK(button is disabled) to validate the recording.

Any help please.

**Comment by bayethiernodiop** [comment]
after checking the navigator inspection the error is : Content Security Policy: The page’s settings blocked the loading of a resource at http://s3proxy/common-voice-corpus/6c243c07-7f27-486e-9c2e-d126c8aad283/19a680c10d8cf602ae227a509b04f974992e0e2a42ca96a3f57144c581f7ad91.mp3?AWSAccessKeyId=local-identity&Expires=1551430693&Signature=0GlsIGZEgzUh3ugOhzeGP6iR240%3D (“connect-src”).
Any help pls

**Comment by bayethiernodiop** [comment]
After trying to modify CORS conf and even disabling it on the code nothing worked. so i went to aws and followed the tuto, still using the docker deployment but i keep getting the error "The specified bucket does not exist" also looks like my config.json in (server/src) is not recognised i had to modify the config-help.ts in server/src directly.

**Comment by bayethiernodiop** [comment]
i don't know if it's due to andrewgaul/s3proxy

**Comment by Gregoor** [comment]
Not sure if that's it, but the config.json needs to be at the root of the project.

**Comment by bayethiernodiop** [comment]
thx for your response. by root you mean in the voice-web folder.
because i put it there with this content but it's not taken into account even the server port(which was just for testing)
{
        "BUCKET_NAME": "speech-wolof",
        "BUCKET_LOCATION":"https://s3.eu-west-1.amazonaws.com",
        "SERVER_PORT": 9001
}

**Comment by bayethiernodiop** [comment]
ok. so the config.json doesn't work with the docker serving.
cant do validation in the docker serving due to the CORS problem.
finally i used the local installation without docker and it's working correctly. thx @Gregoor

**Comment by Gregoor** [comment]
Cool! Happy to hear that, sorry to hear about Docker. It's not been as reliable as hoped, I'm thinking about removing it from our instructions.

**Comment by bayethiernodiop** [comment]
ok, it caused me lot of problem. thanks for your support.

**Comment by hamid914** [comment]
I fixed the "The specified bucket does not exist" error by adding a `console.log(bucket);` command in `/code/node_modules/aws-sdk/lib/services/s3.js:835`:
```
 833     var req = resp.request;
 834     var bucket = req.params.Bucket || null;
 835     console.log(bucket)
 836 
 837     if (!error || !bucket || error.region || req.operation === 'listObjects' ||
 838         (AWS.util.isNode() && req.operation === 'headBucket') ||
```
To do this, I ran `docker-compose up -d` and then exec into `web` container. After editing the code, I restarted the docker with `docker-compose restart`. Then I saw this log in `docker-compose logs --follow`:
```
web        | [BE] common-voice-clips                                                                                                                                                           
web        | [BE] { NoSuchBucket: The specified bucket does not exist   
```
I found out that there should be a `common-voice-clips` in S3 provider (local mode for now).
Then I ran :
```
$ docker exec -i -t s3proxy ash
# apk add curl
OK: 85 MiB in 57 packages
# curl -X PUT http://127.0.0.1:80/common-voice-clips
# exit
```
Now the bucket is exist and recorded files would be saved in
