### ISSUE TITLE
docs/specs/ returns 404

### ISSUE THREAD

**Issue by myakura** [mozilla/voice-web#1862]
https://mozilla.github.io/voice-web/docs/specs/index.html returns 404, although there are files in the repo.

**Comment by Gregoor** [comment]
Is it linked somewhere? You can still find it here: https://github.com/mozilla/voice-web/blob/master/docs/specs/index.html
But good note that I should maybe cleanup that folder

**Comment by myakura** [comment]
I found the link while reading https://medium.com/mozilla-open-innovation/prototyping-with-intention-33d15fb147c2 .

**Comment by Gregoor** [comment]
Ah, thank you! Apparently our GitHub Pages were disabled, possibly by me. Didn't realize we were linking to it. They're active again and so that link works again. Thankslots for reporting this!
