### ISSUE TITLE
Empty and corrupt files in the tarballs.

### ISSUE THREAD

**Issue by xorgy** [mozilla/voice-web#1871]
At least two of the tarballs on the Datasets page contain a certain number of empty (zero byte) or corrupt/incomplete clips.

In en.tar.gz from a couple days ago, I found 398 clip files which were zero bytes in size, or otherwise corrupt or incomplete. It seems as though at least one other tarball, de.tar.gz, has some of its own empty files.

### See also
https://discourse.mozilla.org/t/zero-byte-files-in-german-language-set-new-official-release/36372/3

**Comment by MichaelKohler** [comment]
I'm closing this given that there is a Discourse topic around this.
