### ISSUE TITLE
Error when validating samples

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voice-web#188]
I got this error in my third sample:

<img width="1134" alt="screenshot 2017-06-19 16 41 51" src="https://user-images.githubusercontent.com/973388/27310332-5b8b9dac-550e-11e7-860f-5b3e59ba03d7.png">

**Comment by kdavis-mozilla** [comment]
What's your userid?

**Comment by andrenatal** [comment]
1 - http://voice.mozilla.org/
2 - Firefox Dev Edition

**Comment by kdavis-mozilla** [comment]
Was able to repo. I'll explore more.

**Comment by kdavis-mozilla** [comment]
Just tried 100 times for a reproduction on localhost and couldn't reproduce it.
Just tried 100 times for a reproduction on staging and couldn't reproduce it.
Just tried 100 times for a reproduction on production and couldn't reproduce it.

My guess is that it's servers in the elastic group spinning up or down.

**Comment by paulsilaghi** [comment]
Just got a 'null' sample on https://voice.allizom.org.
Chrome 59, Win 10.
![null listen](https://user-images.githubusercontent.com/29535384/27379142-d2abbc08-5682-11e7-8d2b-e05753629c51.png)

**Comment by kdavis-mozilla** [comment]
@paulsilaghi Did you have this happening more than once?

**Comment by paulsilaghi** [comment]
Yes, reproduced again after validating ~50 recordings.

**Comment by kdavis-mozilla** [comment]
@paulsilaghi I'm not sure if this is a code bug or infra bug as staging over the last 2-3 hours has been failing.

**Comment by andrenatal** [comment]
Just got this issue too in my first sample.

**Comment by kdavis-mozilla** [comment]
@andrenatal Which issue? `null` or `undefined`? Which server too.

**Comment by andrenatal** [comment]
Firefox for Android
voice.mozilla.org

![screenshot_20170621-094032](https://user-images.githubusercontent.com/973388/27397220-6f4323da-566a-11e7-9a93-b9080d3d5d87.png)

**Comment by mikehenrty** [comment]
hopefully this will be fixed in#193

**Comment by kdavis-mozilla** [comment]
@andrenatal @paulsilaghi This should be fixed with commit 617d796 

If you see either issue here again please re-open.
