### ISSUE TITLE
link the mobile apps to a local deployment

### ISSUE THREAD

**Issue by bayethiernodiop** [mozilla/voice-web#1883]
Hello, i want to know if there is an "easy" way to link the mobile apps to a local deployment and deploy that version to ;obile store or just built it and share it with the users like i did for the web version. Thx in advance.

**Comment by Gregoor** [comment]
Heya, I haven't looked too much at the native app code yet, but I think the URL is hardcoded. So if you grep for `voice.mozilla.org` you should find what needs replacing. For iOS you'd need to publish it for other users to be able to use it. In Android you can just send the resulting apk around.

**Comment by bayethiernodiop** [comment]
thx. so i guess i will have to dig in all files to see where the link of the server app is given.

**Comment by MichaelKohler** [comment]
Given the focus on the website, I'm closing this one.
