### ISSUE TITLE
Prioritize unique clips for validation

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1885]
During a discussion on Discourse, it was revealed that only one recording of each sentence is actually used for training DeepSpeech:
https://discourse.mozilla.org/t/why-train-tsv-includes-a-few-files-just-3-of-validated-set/36471/6

This was a surprise to myself and other reviewers. I understand that those clips can still be used for other purposes, however the stated goal of Common Voice is to improve voice recognition technology, so shouldn’t it be optimized for that purpose?

None of the new sentences from Sentence Collector are getting through in English because there’s a backlog of old sentences to get through first. The majority of these appear to be duplicates.

So, in effect, we have to get through thousands of clips that probably won’t even be used in order to get to more useful clips. I’ve validated quite a lot of clips so far but I’m not strongly motivated to put additional time and effort into an action that may ultimately be pointless.

It seems to me that the site should be serving up clips for validation based on how unique the sentence is, rather than their recording date, so that unique clips are given a priority over duplicates.

**Comment by Gregoor** [comment]
Thanks for raising this issue and the recommendation. I think what you're saying makes a whole lot of sense. I think we already have a clips_count column on each sentence, so this shouldn't make the query too much more expensive. I'll look at it next week!

**Comment by MichaelNMaggs** [comment]
Very much agree with @dabinat here.  I'm going to stop work on recording validation for now, as it seems that in English at least, most of the year-long backlog won't actually be used. Happy to continue once something like this idea has been implemented, or duplicates have been removed entirely.

**Comment by Gregoor** [comment]
That's fair! I've just

**Comment by Gregoor** [comment]
alrighty, it's on prod!
