### ISSUE TITLE
Same string ID with updated content not shown in Pontoon

### ISSUE THREAD

**Issue by peiying2** [mozilla/voice-web#1886]
@Gregoor 
Comment FAQ
Context faq-why-my-lang-a
Resource web/locales/en/messages.ftl

It has following English text:

"Mozilla doesn’t pick or favor any one language over another. Instead, Common Voice is a purely community-driven initiative, but it takes <multilangLink>several steps to add a new language</multilangLink> and begin collecting voice donations. First, the Common Voice website needs to be translated so community members can access the contributor experience in their own language. Next, we need a large collection of copyright-free sentences for people to read outloud. Once both of those requirements are satisfied a language is “launched” on Common Voice for people to start recording their voice and validating others donations. If you want to help launch a new language, head over to our <sentenceCollectorLink>sentence collection tool</sentenceCollectorLink> to get started."

However the last sentence ("If you want to help launch a new language, head over to our <sentenceCollectorLink>sentence collection tool</sentenceCollectorLink> to get started.") was added later. This is not shown in Pontoon as fuzzy or untranslated. This will be missed in all the locales already completed the translation earlier.

Please use a new string ID for update, or it will not be captured in Pontoon.

**Comment by TonnesM** [comment]
See #1858.

**Comment by Gregoor** [comment]
Thanks!
