### ISSUE TITLE
Refreshing the page resets the language of stats

### ISSUE THREAD

**Issue by ftyers** [mozilla/voice-web#1894]
It would be really great if refreshing the page maintained the state of the language. E.g. I click on Kyrgyz for the graph thing and then it shows me how many hours in Kyrgyz then I refresh the page and then it shows me "All" again. 

Even more ideal would be to have a auto-updating/polling option.

**Comment by MichaelKohler** [comment]
I'd say this is a duplicate of https://github.com/mozilla/voice-web/issues/1565
