### ISSUE TITLE
iOS app login issues

### ISSUE THREAD

**Issue by MichaelNMaggs** [mozilla/voice-web#1895]
While validating recordings, the iOS app repeatedly presents me with the page "Keep track of your progress with a profile ... Login/Sign Up" even though I am already logged in - as I can tell by going back to the main Speak/Listen page which shows my contribution numbers at top right.

Also, if I try to re-login via email, that does not work.  I receive the email, but clicking on the orange button "Sign in to Voice.Mozilla.org" simply takes me back to the login page where I am again invited to log in via email, Firefox, GitHub or Google.

I'm running iOS 12.1.4 on an iPhone.

**Comment by hmitsch** [comment]
Hi @MichaelNMaggs,

unfortunately, email login does not work on the iOS App. For more details, please see https://github.com/mozilla/voice-web/issues/1649#issuecomment-467935679

I got rid of the Login/Signup UI by logging in via Firefox Accounts, then killing the app and relaunching it.

Best regards,
   Henrik
