### ISSUE TITLE
Selection of repeated recording to include in the corpus

### ISSUE THREAD

**Issue by MichaelNMaggs** [mozilla/voice-web#1896]
I understand from https://discourse.mozilla.org/t/why-train-tsv-includes-a-few-files-just-3-of-validated-set/36471 that where a sentence has been recorded several times, only a single recording is used for the training dataset, to avoid introducing bias. Where there are multiple recordings, it would be interesting to know how the individual one to be used is currently selected.   

If you spend time listening to the recordings, it becomes evident very quickly that there are huge differences in the clarity and accuracy of individual readers. Some readers are just scraping past validation, whereas others are consistently fluent and clear. Rather than selecting the individual recording at random, or taking the first one, I suggest that better results could be achieved by looking at the reader 'recording accuracy', and biasing the selection towards readers with the highest values.

Given the very large proportion of repeated recordings within the corpus, this would I think make a measurable difference.

**Comment by kdavis-mozilla** [comment]
The clearest recording doesn't always help a STT trained on the recording the most. A STT system has to learn to deal with noise, low volumes, slight mumbles....

**Comment by MichaelNMaggs** [comment]
It's not the recording clarity that's the issue, but the accuracy of the utterance. Readers with lower accuracy scores typically stumble more, pause at unexpected points, guess at unfamiliar pronunciations etc.

**Comment by kdavis-mozilla** [comment]
"...stumble more, pause at unexpected points, guess at unfamiliar pronunciations etc."

That's the world that a STT engine has to deal with. If everyone had perfect enunciation creating a STT engine would be much easier.

So having some of these stumbles, pauses, and the like in the data set is a good thing. It teaches an engine how to be effective in the real world.
