### ISSUE TITLE
There was, at least in the past, a bug in voice-web that presented users with HTML fragments to read

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/voice-web#1901]
In the most recent English data release there is in `test.tsv` a transcript with the text "", HTML fragments were removed from the transcripts, that has the corresponding audio:

```bash
87369eabded58abe351f3cca1af834d39de0ba420ea27a51e815ae8c079f3956cd097472a3481a58d7de5be87b6c38a9a07178bb26bb38203e6b5b0baab1c1c8.mp3 
```

which, if you listen to it, consists of someone reading an HTML fragment.

**Comment by kdavis-mozilla** [comment]
The CorporaCreator rejects such sentences, see [here](https://github.com/mozilla/CorporaCreator/blob/master/src/corporacreator/preprocessors/common.py#L94) and [here](https://github.com/mozilla/CorporaCreator/blob/master/src/corporacreator/corpora.py#L15).

So it looks like an out of date version of the CorporaCreator was used to create the release corpus which is another problem.

**Comment by Gregoor** [comment]
Those sentences should be all gone by now, any recommendations what we should do on the Common Voice side of things to mitigate this issue?
