### ISSUE TITLE
[regression]Stats page is not correctly displayed

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1904]
[Environment]:
iOS- Safari, Firefox

[STR]:
1.Go to https://voice.mozilla.org/en/stats

[Expected results]:
The page should be correctly displayed: https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5c87cf9ae1c597198e449e00

[Actual result]:
The content is not correctly displayed
![IMG_0062](https://user-images.githubusercontent.com/41474886/54825344-fd103480-4cb5-11e9-8d8d-a6ad02a248ee.jpg)

[Note]:
Not reproducible on iOS app

**Comment by Gregoor** [comment]
Which iOS version is that?

**Comment by rleitan** [comment]
iOS ver 11.4.1 - but it's not reproducible anymore. I will close this bug!
