### ISSUE TITLE
Contribution: back button remember where you were on dashboard

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1905]
[Environment]:
Windows 10 - Firefox Release 65.0.2

[Preconditions]:
set goals (weekly or daily for both Listen and Speak)

[STR]:
1.Go to https://voice.allizom.org/en/goals
2.Go to Custom goals section and click "Speak button"
3.Record a clip then click back arrow button located in the top-left corner
4.Click "Submit clips" button from Finish recording dialog prompt

[Expected result]:
Goals screen should be displayed, Speak section from Custom goals should be updated with 1 recording

[Actual result]:
Stats screen is displayed and Speak section is not automatically updated

[Note]:
Speak goal is updated after page refresh
The goal is automatically updated for Listen
The issue is not reproducible for weekly or daily - Speak only

**Comment by Gregoor** [comment]
accidently fixed that one :)

**Comment by rleitan** [comment]
@Gregoor - when click on submit clips or back button the page is redirected to stats screen instead of goals screen ( from where we went to contribute). is that a bug?

**Comment by Gregoor** [comment]
I think we want the back button to point to the start page of the dashboard, which is stats. So this is intentional. Unless you have a different take @rleitan @mbransn or @LRSaunders4?

**Comment by mbransn** [comment]
@Gregoor I do agree with @rleitan here, the back button from contribution should return to your dashboard start point.

**Comment by Gregoor** [comment]
@mbransn So should back always take you back to where you were previously on the site (which might be languages or dataset) or should it only do that for dataset sub pages?

**Comment by mbransn** [comment]
I think you meant dashboard sub pages and if so, yes, only for dashboard sub pages. :) This is a logged-in, profile owner use case IMO.

**Comment by Gregoor** [comment]
yup, whoopsie 🙊 So just to make sure I'm implementing it right: When coming from any of the dashboard sub pages (stats, goals or awards) to the contribution portal, the back-link should take them back to that page. Other wise if they have an account, the back button points to the stats page and if they don't have an account to the home page. Cool?

**Comment by mbransn** [comment]
Perfect :) Thanks for writing it out.

**Comment by Gregoor** [comment]
Since this is not super-straightforward and there's stuff that's easier to do, I'll postpone it for today (i.e. won't look at this again until I'm back)

**Comment by Gregoor** [comment]
forgot to close this one, it's been implemented
