### ISSUE TITLE
The text from Speak section is repositioned when hovering over "Create a custom goal" button

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1908]
[Preconditions]:
Have English language added to your profile
no custom goals added

[STR]:
1.Open https://voice.allizom.org/es/stats
2.Go to speak section and hover using the mouse over "Create a custom goal" button

[Actual result]:
The text from the entire Speak section is repositioned 
https://vimeo.com/326333557

[Note]:
Not reproducible for Listen section - Espanol 
Reproducible also for Magyar language - Listen section

**Comment by MichaelKohler** [comment]
Can't reproduce
