### ISSUE TITLE
The "Create a custom goal" button for Listen section is missing after setting a goal for Speak only

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1910]
[Preconditions]:
Have english language added to the profile
No custom goals set

[STR]:
1.Open https://voice.allizom.org/es/stats
2.Click "Create a custom goal" button from Speak section
3. Set a goal for speak only
4.Go back to stats page

[Expected result]:
The "Create a custom goal" button should be displayed for Listen section

[Actual result]:
The "Create a custom goal" button for Listen section is missing
![2019-03-25_16h41_20](https://user-images.githubusercontent.com/41474886/54928980-81b0bc00-4f1d-11e9-9fb0-10fc3358098c.png)

**Comment by Gregoor** [comment]
That's by design, since one can only have one goal at a time.

**Comment by rleitan** [comment]
Closing this issue as per comment 2
