### ISSUE TITLE
Show validated uniques in homepage graph

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1912]
DeepSpeech uses only one recording of a sentence for its model and a large number of the recordings in the most recent dataset release were duplicates.

It’s therefore not clear how close we are to the goal of several thousand hours of validated unique recordings just by looking at the graph showing the total number of validated hours.

Total validated hours is still useful to know, so I don’t think it should be removed, but I think a third line should be added to show the number of unique validated recordings.

**Comment by MichaelNMaggs** [comment]
I too would like to see this information. Even if the stats don't look good it's still important to know how we are doing. And publishing the information may encourage ideas from the community which are focussed more specifically on getting that figure up.

**Comment by MichaelKohler** [comment]
Let's have this conversation over at Discourse to see how many people would be interested in this.
