### ISSUE TITLE
Awards:The yellow star is displayed with delay

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1916]
[Preconditions]:
Log in with a valid account
No awards displayed

[STR]:
1.Open https://voice.allizom.org/en/awards\

[Actual result]:
The yellow star is displayed with delay
https://vimeo.com/327014877

**Comment by Gregoor** [comment]
yup, that happens with all our images which aren't inlined. I guess we could inline this one.

**Comment by Shivansh2407** [comment]
Can you explain which part of code has this issue . Please let me know soon .

**Comment by aryamanpuri** [comment]
@phirework @MichaelKohler Is this still a valid issue?

**Comment by manishkr1101** [comment]
@Gregoor This issue does not persist now. So, you should close this issue. 
Thanks.
