### ISSUE TITLE
[RTL language]:Listen button overlaps listen progress on Stats page

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1917]
[Preconditions]:
Log in with a valid profile
Add English to the profile language

[STR]:
1.Open https://voice.allizom.org/dv/stats

[Actual result]:
Listen button overlaps listen progress 
"Help us to get to.." button from Listen should be displayed in the left side of progress
 "Create a custom goal" buttons should have space between 

![2019-03-28_14h13_17](https://user-images.githubusercontent.com/41474886/55157434-017c9780-5165-11e9-9a43-84b3b379c950.png)

**Comment by rleitan** [comment]
![2019-03-28_14h32_47](https://user-images.githubusercontent.com/41474886/55157965-71d7e880-5166-11e9-82cc-c118e8b61a7e.png)

**Comment by rleitan** [comment]
![2019-04-15_15h36_03](https://user-images.githubusercontent.com/41474886/56133179-7c7ee400-5f94-11e9-9360-1a12a8672eb3.png)


![2019-04-15_15h37_58](https://user-images.githubusercontent.com/41474886/56133181-7f79d480-5f94-11e9-9f8d-eaab80a295f3.png)

The Create a Custom Goal and "Listen" icon are still to close to the text. Not sure how should look? @Gregoor

**Comment by Damian96** [comment]
![Screenshot_2019-11-22 Common Voice by Mozilla](https://user-images.githubusercontent.com/19414954/69441385-4dfb8f80-0d53-11ea-9e04-9df37b571ae9.png)
* OS: Linux 5.0.0-32-generic
* Version: 70.0.1

`Create a Custom Goal` and `Listen` icon are still overflowing their containers.
CSS selectors:
* `div.progress-card a.button.rounded.custom-goal-button`
* `a.button.outline.rounded`

**Comment by mbransn** [comment]
Thanks for the additional flag here @Damian96 we're also tracking in #2434

**Comment by rileyjshaw** [comment]
This should be fixed by https://github.com/mozilla/voice-web/pull/2510.
