### ISSUE TITLE
Error when moving forward from step 2 -> step 3 in editing goals

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1921]
[Preconditions]:
Set a goal 

[STR]:
1. Go to https://voice.allizom.org/en/goals
2. Click edit button from Custom Goals section
3. Select "Yes" button from "Do you want to continue?" modal
4. Click next button from editing mode: step 1 to step 2
5.Click next button from step 2 without selecting number of clips

[Actual result]:
An error occurred. Sorry!

[Note]:
The issue is not reproducible if the number of clips in step 2 is selected

**Comment by Gregoor** [comment]
I can't reproduce and I wonder: Do you maybe have a goal with the old numbers set? It might not be able to handle that state well atm

**Comment by rleitan** [comment]
Yes, that was the problem. I cannot reproduce it by editing a new goal

**Comment by Gregoor** [comment]
Great, thanks for looking into it!
