### ISSUE TITLE
Blank stats page

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1923]
For a couple of days now the stats page has been completely blank. A Goals option also appears, which is blank too.

I wasn’t aware that Goals had shipped to the public site yet. Was this deployed by mistake?

**Comment by Gregoor** [comment]
Sorry I was on vacation.

I'm sorry to hear stats were blank for an extended period of time. A couple of days I certainly haven't seen before. Let's keep an eye on this!

Goals was there before already, we just moved it from the profile sub-menu to the dashboard sub-menu.

**Comment by dabinat** [comment]
FYI, this is still occurring.

**Comment by Gregoor** [comment]
Indeed. Our infra engineer found an error log that might very well be related: `LockError: Exceeded 10 attempts to lock the resource \"clip-leaderboard[null]-lock\"`. It's coming from Redis, but I don't know why it's happening yet.

**Comment by dabinat** [comment]
Here's what I see in Chrome's console when I try to view the stats page:

> 23:36:08.595 api.ts:54 GET https://voice.mozilla.org/api/v1/user_client/goals 504 (GATEWAY_TIMEOUT)
> 
> 23:36:08.596 api.ts:70 Uncaught (in promise) Error
>     at p.<anonymous> (api.ts:70)
>     at Generator.next (<anonymous>)
>     at a (index.js:20)
> 
> 23:36:08.615 api.ts:54 Fetch failed loading: GET "https://voice.mozilla.org/api/v1/user_client/goals".

**Comment by Gregoor** [comment]
it should be much better now, lemme know if not!

**Comment by dabinat** [comment]
I'm no longer getting the 504 error in the console but it's still blank for me.

Interestingly, I signed up for a new account with a dummy email and I could view the stats page from that account. So maybe it's specific to my account? Perhaps it's something to do with the number of validations I have - it's over 6 figures now.

**Comment by davidak** [comment]
When i open https://voice.mozilla.org/de/stats directly in Chromium on Linux or Android, i see this:

![Screenshot from 2019-06-08 13-27-06](https://user-images.githubusercontent.com/91113/59146672-5b190200-89f1-11e9-958a-1e6af4a443c6.png)

I submitted the sentry report. I hope all needed details are included.

**Comment by MichaelKohler** [comment]
@davidak is this still happening?

**Comment by davidak** [comment]
@MichaelKohler no. i get redirected to https://voice.mozilla.org/de/dashboard/stats and from there to https://auth.mozilla.auth0.com/
