### ISSUE TITLE
change the number of maximum record for a user

### ISSUE THREAD

**Issue by bayethiernodiop** [mozilla/voice-web#1925]
Hello, so i deployed locally the voice-web app, but a user pointed to me that he couldn't record new audios after many recording in a given day(the recording page was blank), and after some days he could again record new audios with same account. so my guess is that there is a parameter that limit the number of recording per user per day. if that's the case can someone help in where to  modify that number. Thx in advance.

**Comment by mritunjaygoutam12** [comment]
@bayethiernodiop while going through the code I never encouter such a case where rendering for speak page is blocked on some condition but it is possible it may have. 


> he couldn't record new audios after many recording in a given day(the recording page was blank), and after some days he could again record new audios with same account. 

Does this happen oftenly?

**Comment by dabinat** [comment]
The usual explanation for this is that the user was assigned to the test set, which has a smaller number of sentences. No sentences appeared because the user had recorded all of the sentences in the set. New recordings were available later because more sentences were added.

But if you’re on a local server that last part may not be the case. Were extra sentences added?

**Comment by bayethiernodiop** [comment]
> @bayethiernodiop while going through the code I never encouter such a case where rendering for speak page is blocked on some condition but it is possible it may have.
> 
> > he couldn't record new audios after many recording in a given day(the recording page was blank), and after some days he could again record new audios with same account.
> 
> Does this happen oftenly?

Yes very often i had the same issues with 3 different users

**Comment by bayethiernodiop** [comment]
> The usual explanation for this is that the user was assigned to the test set, which has a smaller number of sentences. No sentences appeared because the user had recorded all of the sentences in the set. New recordings were available later because more sentences were added.
> 
> But if you’re on a local server that last part may not be the case. Were extra sentences added?

Thanks. No i didnt add any sentences after the first uploading the first sentences files. how a user can be added to a test/train/dev set or is that done automatically. and if that's the case can i change that for a user.

**Comment by bayethiernodiop** [comment]
And it can't be things related to dev/train/test set assignment since after some time without adding any new sentences the user can record again

**Comment by mritunjaygoutam12** [comment]
@bayethiernodiop it happens with me too some times when running with docker. But I found that because of importing sentences take some time, after import completed I refresh the page it works.

I will try to look at this again.

**Comment by bayethiernodiop** [comment]
@mritunjaygoutam12 Thanks for your responses. I run the app without docker and to import sentences i only did it once. so i am a bit lost here because for one user after some recordings the recording page was blank and after sometime it worked again without me modifying any things.

**Comment by Gregoor** [comment]
Maybe they used it from a different browser/private tab/cleared their browser data? That's the only other explanation that comes to my mind atm.

RE the bucketing, we actually want to remove that, as we've learned that we can just do that after the fact (when bundling the clips).

**Comment by bayethiernodiop** [comment]
@Gregoor  I dont get your point about the browser, i mean how that could bring the blank page

**Comment by Gregoor** [comment]
Oh sorry, that was indeed not clear from my comment, let me try to unwind it:

When you open the site for the first time a user ID is created for you and you're also put in one of three buckets. Sentences are also in one of those three buckets. You'll then only receive sentences you haven't read from your bucket, even if you close & re-open the browser.
Now if you use a different browser / private window or clear your browser data you'd receive a new ID and would be put in a new (or the same bucket).

Am I making more sense now?

**Comment by bayethiernodiop** [comment]
Ah ok i understand, so that still work if you have an account? Also does thiis mean if a user record all the sentences of a bucket, he is not able to record the same sentences without changing broweser,...

**Comment by Gregoor** [comment]
Not quite, your user ID is tied to your account, so even if you use the account in different browsers you'd still be served from the same pool of sentences.
And yes, once you've recorded all the sentences from your bucket, you'd be served no more sentences.

**Comment by bayethiernodiop** [comment]
ah ok that make sense. This is weired because i know someone who was using the same account. had a blank page but after some time(maybe days) things were again ok

**Comment by JAGulin** [comment]
There seems to be an agreement that this issue is based on a misunderstanding. Should it be closed @bayethiernodiop ?

Yet, it would reduce misunderstandings if instead of a white page there could be a lead text explaining the situation. E.g. "There is currently no available sentences for you in the selected language. Please come back later. " Saying sentences, work or contribution opportunity should make it general to both recording and validation. Possibly relevant to add some info about problem solving or link to a discourse thread about it. Easily done @Gregoor ?

**Comment by bayethiernodiop** [comment]
yes @JAGulin this can be closed and yes your proposition of an error message would be more helpful than a blank page. what i end up doing is to change manually in the database the buckets associated to users.
