### ISSUE TITLE
Blank sentences from issue #191 are still in S3 and can be validated

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/voice-web#193]
The blanks sentences from issue #191 are still stored in S3 and need to be removed.

**Comment by paulsilaghi** [comment]
Sometimes I click 'Play' and the button never reverts to its initial state (like the recording is playing forever).  Is it related to the blank sentences issue?

**Comment by kdavis-mozilla** [comment]
Not related, but my guess that's from someone pushing record and letting it record for a long time while saying nothing.

**Comment by kdavis-mozilla** [comment]
Likely, the easiest solution to this is to delete all data in S3 associated with these blanks sentences.

**Comment by kdavis-mozilla** [comment]
@gozer TLDR Would is be possible to hand delete some data from the live S3 bucket?

A bit longer version: Previously the problem of issue #191 caused some sentences consisting only of white space to be presented to the users. These got saved in S3 along with their audio after people "read" them. After issue #191 got fixed, the offending sentences are still in S3 and occasionally people are asked to verify them.

The proposed solution is find out, from diff, how much white space was in these sentences, find the hash of these white space sentences, then remove the S3 entries corresponding to these white space sentences using their hash. We will need to do this eventually to clean the data set.

Parallel to that we can add in code that never allows one to verify sentences consisting only of while space.
