### ISSUE TITLE
Some Design issues

### ISSUE THREAD

**Issue by georai** [mozilla/voice-web#1931]
- [ ] https://voice.allizom.org/en/goals.  Get started on center and on hover like this https://www.dropbox.com/s/kc58d4v6782it41/Screenshot%202019-03-27%2014.08.58.png?dl=0

- [ ] Waves and border missing: https://www.dropbox.com/s/fxg6at9pc1ddkhy/Screenshot%202019-03-27%2014.18.00.png?dl=0

@Gregoor #

**Comment by Gregoor** [comment]
@georai the images are gone

**Comment by georai** [comment]
1. https://www.dropbox.com/s/4rbjsqza53fc3w6/Common%20Voice.png?dl=0 please take a look @Gregoor 
2. https://www.dropbox.com/s/50fjokulx8vuoby/Screenshot%202019-04-15%2012.57.27.png?dl=0 Maybe Cancel instead of X and Next needs to be like in the design
3.https://voice.allizom.org/en/awards let's align center the copy: When you complete a personal goal, your awards will show up here.

**Comment by Gregoor** [comment]
1) Done

2) was lost on me, maybe I'll find time for it!

3) can you get me a screenshot, I'm not sure I understand

Thanks!

**Comment by mbransn** [comment]
Closing and will revisit with future goal / award setting UI iteration.
