### ISSUE TITLE
Firefox not recognized

### ISSUE THREAD

**Issue by hitgoeb** [mozilla/voice-web#1934]
voice.mozilla.org states «We’re sorry, but your platform is not currently supported.» I'm using Firefox 66.0.2 on elementary OS.

**Comment by lissyx** [comment]
> voice.mozilla.org states «We’re sorry, but your platform is not currently supported.» I'm using Firefox 66.0.2 on elementary OS.

@hitgoeb Can you ensure this is running vanilla Firefox with WebRTC features enabled ? Usually that message means the microphone is not exposed.

**Comment by hitgoeb** [comment]
I don't know about WebRTC, but everything is working as expected (including sound recording).

**Comment by MichaelKohler** [comment]
@hitgoeb is this still happening?

**Comment by hitgoeb** [comment]
@MichaelKohler No.
