### ISSUE TITLE
Some buttons do not have cursor state on hover may be due to padding

### ISSUE THREAD

**Issue by nagpalm7** [mozilla/voice-web#1935]
STR: 
![voice-web](https://user-images.githubusercontent.com/32512296/55801138-07726100-5af3-11e9-9210-3f0ac0639658.gif)

**Comment by MichaelKohler** [comment]
This still applies for the record button. Looks like only the `button` has the cursor property set, but not the background div, which is wider than the button. However as also only the button is clickable, I think this makes sense.
