### ISSUE TITLE
Language dropdowns should be sorted by translated title

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1945]
The language dropdowns on the homepage, as far as I can tell, appear to be sorted by language code.

So for English, “German” (de) is listed before “English” (en) and “Chinese” (zh) is listed last.

This makes no sense alphabetically and it can be hard to locate specific languages. It would make more sense for the dropdowns to be sorted by the translated language name.

**Comment by Mika-net** [comment]
@dabinat @Gregoor If its alright I can take a stab at this.

**Comment by Mika-net** [comment]
@dabinat @Gregoor  this issue should be marked as closed as on the production site the changes have been made

**Comment by Gregoor** [comment]
Great, thanks for looking into it!

**Comment by dabinat** [comment]
Was this deployed to production? I can't notice a difference. "German" still appears before "English" for me.
