### ISSUE TITLE
Share your goal screen is still displayed after sharing the goal

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1947]
[Preconditions]:
Set/Edit a daily goal 

[STR]:
1.Click Confirm goal button
2.Click "Share my goal" button
3. Choose sharing options then click the "x" button

[Expected result]:
Share your goal dialogue prompt should be closed
Share your goal screen should not be displayed anymore

[Actual result]:
"Your weekly goal has been created" screen is displayed, also the goal can be shared again
![2019-04-15_15h02_38](https://user-images.githubusercontent.com/41474886/56131204-84885500-5f8f-11e9-8476-de29f4dfaed1.png)

**Comment by rleitan** [comment]
cc @mbransn

**Comment by mbransn** [comment]
Agreed with expected result, thanks for filing @rleitan 👍
