### ISSUE TITLE
User can create a custom goal when the site is not localized to EN

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1948]
**STR:**

1. Login to https://voice.allizom.org/en
2. Add "English" to your Languages 
3. Navigate to Dashboard page
4. Choose a language different from English in the localization drop down 

**Expected:**
As per [designs](https://projects.invisionapp.com/d/#/console/13381937/296514715/comments/111956605), "Create a Custom Goal" button should not be available, as the site is not localized in EN

**Actual:**
 "Create a Custom Goal" button is available
![custom goal](https://user-images.githubusercontent.com/5293100/56287314-ae26b500-6124-11e9-8f38-39e3ef60ab55.png)

**Comment by viorelaioia** [comment]
Hi @mbransn ! Can you please confirm when should we allow users to create a custom goal? 
From [conversation](https://projects.invisionapp.com/d/#/console/13381937/296514715/comments/111956605) in invision, looks like user needs to have English in Languages **and** also the site localized to EN, so that we allow goals creation. Does this condition still applies?
CC @Gregoor

**Comment by mbransn** [comment]
👋 @viorelaioia yes! The create custom goal CTA should not be visible in the example you posted above. We're launching goals only in english and only for english language contribution for this beta.

**Comment by Gregoor** [comment]
@mbransn I feel like I'm a bit out of the loop, I thought we want to show the custom goal stuff when the site is either localized in english or the user has english in their list of languages. Or is it that we want different rules for the stats page vs the goals page?

**Comment by mbransn** [comment]
@Gregoor sorry this one slipped through my inbox cracks! Don't want you to feel out of the loop 😞 lots going on discussion wise. Here's what I wrote in InVision during our UX phase:

<img width="404" alt="Screen Shot 2019-04-26 at 11 45 35 AM" src="https://user-images.githubusercontent.com/18686986/56829580-ffb3fb80-6818-11e9-9658-302527ed3352.png">

The site should be localized to English for the goals info to show on the dashboard.

(Side note: You may be confusing this with the constraints for showing the goals banner info on the homepage maybe? I do remember that we did decide via Vidyo that would be visible to anyone on the site who had English in their profile, regardless of site localization. This helps people understand that beta goals are available for English contribution. Happy to discuss further elsewhere next week.)

**Comment by Gregoor** [comment]
Thanks for being patient with me (for something that amounted to changing 2 characters). I think I indeed got those two mixed up. So many channels of communication 🙈 

Apropos, can you remind what the "goals banner info on the homepage" is about? Is that something we already have / should have? @mbransn
