### ISSUE TITLE
Goals are not updated after opting in 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1953]
**Precondition:**
Have a custom goal in your voice.allizom.org profile (e.g "45 clips to listen - Daily goal")

**STR:**
1. Edit the custom goal from precondition
2. Update the custom goal (e.g: "105 clips to speak - Weekly goal")
3. Select the checkbox "I’d like updates and goal reminders to keep current with Common Voice"
4. Confirm your updated goal 

**Expected:**
Goal is updated to the one set in step 2 

**Actual:**
Goal is not updated, initial goal (from precondition) is shown. User needs to refresh the page to see the updated goal.

**Comment by Gregoor** [comment]
Thanks for the report! I do remember seeing that bug as well. But now I can't reproduce it anymore. Also tried with a new account.

**Comment by viorelaioia** [comment]
I cannot reproduce this issue anymore either. I will close it for now and leave a comment if I see it happening again.
