### ISSUE TITLE
"You've got an award" notification is shown 2 times 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1957]
**STR:**
1. Login to your common voice profile in staging
2. Create a new custom goal of 15 daily recordings
3. Navigate to "Listen" page and record 15 sentences => "You've got an award" notification is displayed
4. Navigate to Stats page and click the circle progress with 100% of clips you recorded 

**Expected:**
Goal page is returned

**Actual:**
 "You've got an award" notification is displayed again

**Comment by mbransn** [comment]
The you've got an award notification should actually be a banner that persists until interacted with via CTA or `x` for dismiss. See the [wireframes](https://overflow.io/s/92K0N8/?node=14878542) and [banner UI](https://zpl.io/aXM9Z0j). Also noted as part of #1918
