### ISSUE TITLE
Validation issues in wiki import 

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1958]
The big batch of sentences added in commit https://github.com/mozilla/voice-web/commit/2fd87cf433aae2648cff724647ef9fa381d0473b has quite a lot of sentences that should have failed validation.

**Non-English characters**

> At that time Ueshiba was referring to his martial art as "Aiki Budō".

> He was from the area of Álftafjörður in west Iceland.

**Symbols / abbreviations that should be converted to words**

> The main provider of international bus connection in Bosnia & Herzegovina is Eurolines.

> He was buried at St. Peter’s, and was succeeded by Pope Paschal I.

> For example: the Unix command grep -E 'fu|bar' matches lines containing 'fu' or 'bar'.

> First publications of his compositions included the String Quartet No.

**Misspellings**

> The Population Departement of the United Nations prepared the following estimates.

**Sentences related to navigating the Wikipedia site**

> See "graph embedding" for other related topics.

> See Eusebius, Hist.

**Long / tedious sentences**

> Approaches include positivism, interpretivism, rational choice theory, behaviouralism, structuralism, post-structuralism, realism, institutionalism, and pluralism.

(I thought the limit was supposed to be 100 characters?)

> Digraphs: Ay "ay", Ch "chee", Ee "ee ee", Sh "shee", Ty "tyee".

**Short sentences**

> Richard Denton.

> Jun.

> vii.

> Pomeroy et al.

> I.e.

> Ch.

> method.

> Nebo.

> Thus, e.g.

**Some words, especially foreign or scientific terms, are hard to pronounce**

> Pierre Curie was introduced to Maria Skłodowska by their friend, physicist Józef Wierusz-Kowalski.

> Recently, a very different pigment has been found in some marine γ-proteobacteria: proteorhodopsin.

> Bacterial chlorophyll b has been isolated from Rhodopseudomonas spp.

> The name was contrived by the railway for publicity and to outdo Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch.

> Other streets include Afstralias, Agiou Konstantinou or Agyia, Aretha, and Notara.

> Pavel Melnikov-Pechersky, Velimir Khlebnikov, Pyotr Boborykin, Eugenia Ginzburg, Leo Tolstoy, Daniil Mordovtsev, Alexander Tarasov-Rodionov.

(several of these probably fall into the "tedious" category too.)

**Partial sentences**

> their refractive index is different along their axis as opposed to perpendicular to it.

> is applied to species he described.

> a fully documented genealogy e.g.

> are verbs.

> , there has been only one female bell-ringer.

**Non-sensical sentences**

> Goodbye, Your Father

> Only the plural form "" is used even when addressing one person.

> Street the Medal of Honor.

> The subspecies "C. graminis santonico" is associated with "".

> They also released a best of album, "".

**Profanity / offensive terms**

> "You Fucked Up" later reappears as track one on their release "".

> ' What the fuck is that, I'm going to make "The Low End Theory"".

> Motherfuckers was like, 'You're a white boy, what the fuck are you rapping for?

> I know if I say, 'Don't kill', niggas won't kill".

**Sentences not in English**

> Détection des fossés comblés sur terrains sans végétation grâce à l'humidité rémanente des remblais.

I found all of these examples just by browsing the first 30% or so of the file. They were extremely easy to find. In my opinion all wiki sentences should be taken out of rotation until they can be properly validated by the community.

**Comment by dabinat** [comment]
By the way, I am happy to improve the importer script if it's made available somewhere. Maybe it's something that should be included in the voice-web repo?

I also think it would be helpful to have the script output a separate JSON or CSV file, like Sentence Collector does, showing which page the sentence originally came from. This would help in tracking down bugs and blacklisting any pages if necessary.

**Comment by dabinat** [comment]
I have a basic script to filter out some of the more egregious ones:
https://github.com/dabinat/cvtools

I want to work on it a little more before I create a PR for the fixes. But even now it's filtering out 117k sentences, with I'm sure many additional sentences remaining to be filtered. So the rate of validation failures is probably >= 10%, which is a very high rate of failure.

**Comment by MichaelNMaggs** [comment]
Well done!  You could also check against a bad-word list (for profanities etc).  When validating sentences from public domain books I find that most failures come from unbalanced quote marks of various types, though that may be less important for Wikipedia sentences. Your 100 letter cut-off, while sensible, isn't used for sentences that go through the sentence collector. I'm away for a few days so can't volunteer time just at the moment I'm afraid.

**Comment by Gregoor** [comment]
Thanks for putting that work in! The current version of the sentence scraper lives in this repo:
https://github.com/fiji-flo/common-voice-yotp/tree/english

Happy to look at PRs! In the coming weeks we'll also reach out more asking for help with scraping other languages (and improving the ones we have, english and chinese).

**Comment by dabinat** [comment]
> Your 100 letter cut-off, while sensible, isn't used for sentences that go through the sentence collector.

I know 100 was mentioned on Google Docs but I will double-check what it is in Sentence Collector. However my goal was to filter out sentences I described above as tedious. I feel that any script that is importing masses of sentences without human input should be conservative. It should err on the side of caution and any correct words filtered out can always be manually added through Sentence Collector.

**Comment by MichaelKohler** [comment]
> I know 100 was mentioned on Google Docs but I will double-check what it is in Sentence Collector. 

The Sentence Collector uses a limit of 14 words for English.

**Comment by dabinat** [comment]
So there's no character limit as well? My script has 14 words and 100 characters as limits.

**Comment by MichaelNMaggs** [comment]
I agree with you, and with your implementation of a word-length cutoff as well. I’d prefer a lower word cutoff as in my experience reading accuracy falls off rapidly with sentence length, even with the usually-simpler sentences from novels. I’ve reduced my novels cutoff to 12 and am thinking of reducing it further to 10. 

Michael

**Comment by dabinat** [comment]
Added a PR to improve the wiki data: https://github.com/mozilla/voice-web/pull/1963

**Comment by dabinat** [comment]
Added PR to strip another 61K sentences from the file: #1989
