### ISSUE TITLE
Footer buttons should open pages in new tabs on desktop

### ISSUE THREAD

**Issue by paulsilaghi** [mozilla/voice-web#196]
Since 'Cookies', 'Legal', 'Creative Commons License' buttons are pointing to other domains, they should open pages in new tabs instead of the current tab, in order not to close the user's app.

**Comment by kdavis-mozilla** [comment]
What about iOS?

**Comment by paulsilaghi** [comment]
Similar behavior on iOS - the above pages are opened in the same screen of the app. I'm not exactly sure what's suppose to happen here. The top 'Close' button from the footer pages quickly takes you back on the app screen, so it looks ok IMO.

**Comment by kdavis-mozilla** [comment]
Sorry I wasn't clear enough.

As both the iOS and WebApp are targeting the same code, if we have the WebApp open a tab for the 'Cookies', 'Legal', and 'Creative Commons License,' how will that effect the iOS app as the iOS app has no notion of 'tabs'.

**Comment by paulsilaghi** [comment]
I can't answer to this question, we should probably ask an iOS developer.

**Comment by kdavis-mozilla** [comment]
@andrenatal Could you comment?

**Comment by paulsilaghi** [comment]
Actually there must be a way: the 'learn more' link from the privacy opens the page in a new tab on desktop, but uses the same screen on iOS.

**Comment by andrenatal** [comment]
External links aren't open in the same screen, but in a browser view on top of the app. That's the standard behavior of every app on ios since doing that you retain the user and increase its engagement. 

@mikehenrty asked for this here: https://github.com/mozilla/voice-web/issues/87#issue-235708554

**Comment by andrenatal** [comment]
Reopening after realize the bug is actually related with desktop and not ios.

**Comment by mikehenrty** [comment]
This is fixed with a couple of commits, but mostly this one: https://github.com/mozilla/voice-web/commit/249cebd7b85a03d77aba5d05c5542590d7e1a8f6
