### ISSUE TITLE
Link "pt-BR" localization to "pt"

### ISSUE THREAD

**Issue by nukeador** [mozilla/voice-web#1962]
Hi,

Dataset languages include Portuguese "pt" without any variants but currently we just have pt-BR localization.

As a temporal way to fix Portuguese dataset collection, I would like to request we use pt-BR localization for pt and enable it on the site, this way we will be able to add sentences.

pt-BR should redirect to pt on the site.

Cheers.

**Comment by kdavis-mozilla** [comment]
pt-BR and pt are spoken quite differently and written somewhat differently.

**Comment by nukeador** [comment]
Let's have a conversation about this before closing the issue, thanks.

**Comment by kdavis-mozilla** [comment]
Oh sorry, didn't mean to close this.

**Comment by nukeador** [comment]
Based on the conversations we had about language strategy, let's move ahead to avoid blocking Portuguese anymore.

@Gregoor can we mirror for now "pt-BR" into "pt" and enable the site just in "pt"?

**Comment by Gregoor** [comment]
@nukeador we can, haven't renamed a locale before, wanna make sure I get the process right. Let's put it onto the todos for next week! (Don't think it'll take long, it's just a first)

**Comment by peiying2** [comment]
I am working on something similar for other projects: consolidating two bn-* locales to bn. This is what we are doing so we don't lose the data in Pontoon:

Gregor:
- create a pt repo
- move pt-BR repo to pt
- remove pt-BR repo (let us know when this is done)

Pontoon:
- disable pt-BR (to stop contributing to the locale)
- migrate pt-BR data to pt (including contributor's history)
- L10n PM confirms the update and comment in the issue, so we can close the task.

**Comment by nukeador** [comment]
@peiying2 can you clarify what do you mean by "repo" here?

My understanding is that we should move/rename folders.

Thanks!

**Comment by nukeador** [comment]
@Gregoor please review all proposed changes

https://github.com/mozilla/voice-web/pull/2132

**Comment by peiying2** [comment]
While you are at it, pls remove bn-BD locale too, since you already have `bn` there.

**Comment by nukeador** [comment]
@peiying2 pt-BT → pt folder change has been committed to master

**Comment by nukeador** [comment]
Changes are now on production 

https://voice.mozilla.org/pt

@Gregoor We might want to redirect the old /pt-BR/ url to the new /pt/ one

**Comment by Gregoor** [comment]
Oh yeah, good idea! Will do
