### ISSUE TITLE
Add the ability to report a bad sentence

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1966]
There should be the ability to report a bad sentence from both the recording and validation pages. 

I feel this is more necessary now that the wiki sentences have been added without manual validation.

To prevent abuse, it’s probably best for a sentence to require two reports before it gets flagged up. And perhaps a limit on the number of reports that a user can make within a certain timeframe.

The best solution would be for a flagged sentence to be removed from rotation and put into Sentence Collector for manual validation, but I know there’s little interaction between the two sites right now.

So perhaps a quick interim solution is to create a daily report of flagged sentences that volunteers can manually submit PRs to fix.

**Comment by Gregoor** [comment]
I like the idea! We do already track skipped_sentences (and do nothing with it), maybe we could surface that in the same report or just use that

**Comment by nukeador** [comment]
See #890 

Let's centralize the request here :-)
