### ISSUE TITLE
[iOS] Scrolling doesn't work on iPad 4

### ISSUE THREAD

**Issue by paulsilaghi** [mozilla/voice-web#197]
Device: iPad mini 4
OS: iOS 10.3.1

Scrolling doesn't work, so I'm not able to see the footer on the homepage.
Note that this doesn't reproduce on iPhone 6S / iOS 10.3.3.

**Comment by kdavis-mozilla** [comment]
I can repo on

Device: iPad Air 2
OS: iOS 10.3.2

**Comment by mikehenrty** [comment]
@andrenatal can you have a look at this? is there a way we can re-enable top level scrolling on the ipad? and does it look ok if we do?
