### ISSUE TITLE
Homepage banner for personal goals

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#1976]
@Gregoor homepage banner for announcing goals is needed:

- [x] This banner has two different use cases:
- Logged in profile owners will see a CTA for : get started
- Anyone not logged in will be prompted to : ~create an account~ Log In / Sign Up

- [x] The banner is persistent until dismissed via the close `x`

- [x] The banner should use our current banner UI on zeplin

- [x] Banner copy: Help reach 10,000 hours in English, set a [personal goal] (link to Discourse post)

**Comment by Gregoor** [comment]
Oh so we're only showing it when a user visits the homepage?

Also I guess it'd be best if it wouldn't overlap the nav (like the awards banner currently does)?

I'm pushing a version now that (imo) does the wrong thing for both of those questions (shows on every page & overlaps nav), but I'll hover this issue to make sure I get it right quickly after launch.

**Comment by mbransn** [comment]
> Only show it when a user visits the homepage?
Yes

> Should it overlap the nav (like the awards banner currently does)?
Ideally below the nav, is this possible?

<img width="1136" alt="Screen Shot 2019-04-29 at 9 17 05 AM" src="https://user-images.githubusercontent.com/18686986/56913392-6843e800-6a66-11e9-8288-ed914e9a8b35.png">

> How to indicate the discourse link? Single color underline looks a bit weird, and gradient is not an option.

For this banner let's make all copy white and link underline with blue on hover

**Comment by mbransn** [comment]
@Gregoor note in initial description that CTA text for logged out / non -profile owner has changed to `Log In / Sign Up`
