### ISSUE TITLE
"Go To" links in production

### ISSUE THREAD

**Issue by csepanda** [mozilla/voice-web#1978]
Hi, I have noticed minor issue with [FAQ page](https://voice.mozilla.org/en/faq#localization).
At the bottom of the page there are light gray links to staging server and localhost :)

See screenshots attached below:
![image](https://user-images.githubusercontent.com/16517888/56928810-9e25b280-6ae0-11e9-8ab3-770b7eb3a77d.png)

![image](https://user-images.githubusercontent.com/16517888/56928996-26a45300-6ae1-11e9-8377-91023852c6d3.png)

Maybe it is desired developers' useful bookmark but for some people it might be seen very strange.

Reproduced in Mozilla Firefox 65 on Linux in staging and production.

**Comment by Gregoor** [comment]
Dang, I thought I hid them well 🙈 

It's our sneaky way of testing the local/staging web version in the iOS app, which points to the production site by default. 

We'll have a new FAQ soon, then those links will be gone. Though I also don't have a plan yet on how we'll test staging in the iOS app then. Fortunately the iOS app won't be needed for much longer 🎉

**Comment by csepanda** [comment]
> Though I also don't have a plan yet on how we'll test staging in the iOS app then. 
What about "Test flight" / local testing?
