### ISSUE TITLE
Missing word on https://activate.mozilla.community/en-US/commonvoice web page

### ISSUE THREAD

**Issue by venterce** [mozilla/voice-web#1979]
On the common voice web site, under the lone cowboy/cowgirl Activity flow, the first sentance seems to be missing a word.

It says "Do a marathon session or try create a routine that makes it easy to remember to contribute."

I think it should say something like "Do a marathon session or try TO create a routine that makes it easy to contribute."   Or even better add the "to" and then say something like "on a regular basis." at the end.

**Comment by venterce** [comment]
Oops, I just found a duplicated word/typo  in another sentence in the same section of the same page.

Under the heading: To review clips

"Once you have reached 15 mins of your voice it’s more useful if you to to the Listen section and help review other people’s voices."

I'm thinking that they meant to say:
"Once you have reached 15 mins of your voice it’s more useful if you GO to the Listen section and help review other people’s voices."

**Comment by venterce** [comment]
I seem to have closed this issue and I can't find a way to reopen it.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. A copy update is tracked here: https://github.com/mozilla/activate.mozilla.community/issues/345. This will be changed to "Try a marathon session or create.."

@Gregoor can you close this issue?
