### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1980]
For the past 8 hours or so I've been unable to login to the site. When I click the SSO link in my email, it takes me to https://voice.mozilla.org/login-success which shows a blank white page. (This behavior also occurs with the alternative authentication methods.)

If I change the URL to https://voice.mozilla.org to take me back to the homepage, I am still not logged in at the top right. I have reproduced this behavior in multiple browsers.

Very rarely, I am able to login successfully but then I get logged out again pretty quickly.

As this behavior only started today, maybe it has something to do with the new personal goals feature that just shipped?

**Comment by BhuvanaMeenakshiK** [comment]
Me too facing the same here. I tried to log in through all the accounts of mine say, Google, Firefox and Github but still facing the same issues.

**Comment by rory** [comment]
I also have this issue. FF dev tools says:

    Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: 

( also here https://discourse.mozilla.org/t/impossible-to-login/34763 )

**Comment by dabinat** [comment]
It’s working for me now. Is anyone else still getting this? If not I’ll close this issue.

**Comment by Gregoor** [comment]
Thanks for reporting it! It should indeed be working again. I've spend the day extinguishing the fire I set yesterday

**Comment by BhuvanaMeenakshiK** [comment]
It is working well for me sa well. Thanks
