### ISSUE TITLE
Two sentences repeat on about us page

### ISSUE THREAD

**Issue by zerdo90** [mozilla/voice-web#1981]
On https://voice.allizom.org/en/about page under the "≥ 2 No votes" and "Common Voice Dataset" headlines there is the same text: "When a user rejects a voice clip it returns to the Queue. If rejected a second time, the voice clip is moved to the Clip Graveyard." 

I suppose under the "Common Voice Dataset" should be something else?

![about](https://user-images.githubusercontent.com/26620773/56953661-57b27100-6b3d-11e9-9b8a-8b1309a40ac9.jpg)

**Comment by Gregoor** [comment]
Thanks for the report!

cc @munteanu210

**Comment by munteanu210** [comment]
@zerdo90 thanks for identifying this! I am working on changing it already.

**Comment by munteanu210** [comment]
@mbransn @georai These two texts were identical on the design. See [screenshot](https://www.screencast.com/t/CfJ1ggl6pb). Please provide the correct / unique texts per each of these two sections, and I will update them.
