### ISSUE TITLE
"Your weekly goal has been created" message is shown after creating a daily goal

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1983]
**STR:**
1. Login to your common voice profile on prod
2. Navigate to Goals page
3. Create a new **daily goal** of 15 recordings 

**Expected:**
"Your daily goal has been created" message is displayed

**Actual:**
"Your **weekly goal** has been created" message is displayed. See [video](https://vimeo.com/333338938)

**Comment by arnavvats** [comment]
Hi, I'd like to work on this bug.

**Comment by Gregoor** [comment]
Great, thanks! Let me know if I can assist.

**Comment by arnavvats** [comment]
Unable to reproduce the bug currently,
looked inside the custom-goal-lock component and seems like it renders the custom goals only they already present. Can you take a look?

**Comment by arnavvats** [comment]
Hi, found the bug and change the code. Please review my pull request.
Thanks
