### ISSUE TITLE
Add more space on the left side of the screen 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1984]
For Stats and Awards pages
<img width="1278" alt="Screen Shot 2019-04-30 at 17 34 56" src="https://user-images.githubusercontent.com/5293100/56969941-d07df100-6b6e-11e9-9bc1-815a8d65620a.png">
See [designs](https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5c9018f29f489505cacd3d20)

**Comment by arnavvats** [comment]
Hi, added a small fix to the css. Please review.

**Comment by Gregoor** [comment]
Awesome, thanks for looking into it :) Could you create a separate PR for it? the FAQ PR is likely gonna be reviewed by someone else

**Comment by arnavvats** [comment]
Created a separate one. Thanks
