### ISSUE TITLE
[mobile] Robot picture overlaps the "Become a Partner" button

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1991]
Environment:
iPhone 7 and X, iOS 12.2, Firefox and Safari

![photo5931728274390626444](https://user-images.githubusercontent.com/5293100/57061628-434db000-6cc6-11e9-90eb-b938ad4bf0c2.jpg)

CC @munteanu210

**Comment by munteanu210** [comment]
Thanks for identifying and reporting this. Working on it already.

**Comment by munteanu210** [comment]
@viorelaioia, I fixed this problem.

**Comment by viorelaioia** [comment]
Verified as fixed!
