### ISSUE TITLE
Go to staging/Go to localhost links on FAQ page

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1995]
Environment:
Windows 10, Mac OS 10.14 - Firefox, Chrome
[STR]:
1.Open https://voice.allizom.org/en/faq-new
2.Scroll down to the bottom of the page

[Actual result]:
Go to staging/Go to localhost links are displayed with grey colour

![2019-05-02_12h27_54](https://user-images.githubusercontent.com/41474886/57066948-4f416e00-6cd6-11e9-9746-eda9d1fe86e0.png)

**Comment by rleitan** [comment]
@munteanu210

**Comment by munteanu210** [comment]
Thanks for your feedback. Working on it already.

**Comment by munteanu210** [comment]
@rleitan, I fixed this problem.

**Comment by rleitan** [comment]
Verified as fixed!
