### ISSUE TITLE
Searching by empty space returns results

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1996]
[STR]:
1.Open https://voice.allizom.org/en/faq-new
2.Go to the search bar and press space bar once
3.Press space bar once again

[Actual result]:
2. All results are displayed
3.What is Common Voice? subsection is displayed

![2019-05-02_15h01_25](https://user-images.githubusercontent.com/41474886/57073934-35f6ec80-6ceb-11e9-93d4-b3b0fc345093.png)

@munteanu210 is this expected?

**Comment by munteanu210** [comment]
@rleitan thanks for your feedback. I will fix this so that when you press the space bar once and then a second time, no results are displayed. I think that I should also trim the first and last space in case someone accidentally adds space before and/or after the searched words. Let me know your thoughts.

**Comment by munteanu210** [comment]
@rleitan thanks for your feedback. I will trim the first and last space.

**Comment by munteanu210** [comment]
@rleitan, I fixed this problem.

**Comment by rleitan** [comment]
@munteanu210 as per your comment: " I will fix this so that when you press the space bar once and then a second time, no results are displayed". 
After the fix, when I search by first space, then second space I get all the results. So there is no difference how many spaces I enter in the search bar.

**Comment by munteanu210** [comment]
@rleitan I made the search ignore the spaces when they are alone by themselves, or at the beginning or end of a word. Spaces are being considered only when they are in between words. So, yes, adding multiple spaces will not trigger the search. The page will continue to show all the answers as it does by default.
