### ISSUE TITLE
Security warning dialog prompt when trying to submit a message via Contact form

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1998]
[STR]:
1.Open https://voice.allizom.org/en/about#get-involved
2. Click the Contact button 
3.Fill the Contact form and click Submit

[Actual result]:
Security warning dialog prompt displayed
![2019-05-02_15h59_40](https://user-images.githubusercontent.com/41474886/57076879-4dd26e80-6cf3-11e9-83d6-063a9f9667cf.png)

@munteanu210

**Comment by munteanu210** [comment]
@rleitan thanks for your feedback. Working on it already.

**Comment by munteanu210** [comment]
@rleitan this warning dialog shows on the live site too: https://www.screencast.com/t/EuJEAmju4l   You can reproduce this in Firefox. This problem will disappear if / when an internal HTTPS address will be added to this form. Until then, mailto will always show this warning dialog.

**Comment by munteanu210** [comment]
@Gregoor I see what you say. Thanks for confirming that you also see this as being an issue outside our control. Let me know whether we want to keep this item open until someone from FF responds, or we close it?

**Comment by Gregoor** [comment]
Yeah let's keep it open for a bit, until we have an idea when it'll be fixed (or if sth can be done from our side). There's already plenty of discussion happening on that ticket, so I'm optimistic :)

**Comment by Gregoor** [comment]
The issue on Bugzilla got tagged as resolved, so I guess this should now work correctly in Nightly :)

**Comment by rleitan** [comment]
It's fixed in Nightly!

**Comment by munteanu210** [comment]
@Gregoor that's great! Thanks for letting us know.
