### ISSUE TITLE
[iOS app] About Us menu buttons are displayed with no text and icons

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1999]
**STR:**
Navigate to Abouts Us page
Scroll down

**Expected:**
Buttons with icons and text are displayed on the bottom of the page. See [designs](https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5c88f7dfa1202f046ea39559) are displayed

**Actual:**
Buttons are displayed on the bottom of the page with no text and icons. See [video](https://vimeo.com/333748263)

**Note:**
This is happening only on the Common Voice iOS application

CC @munteanu210

**Comment by munteanu210** [comment]
@viorelaioia thanks for your feedback. Working on it already.

**Comment by munteanu210** [comment]
@viorelaioia I found the Common Voice iOS application for the live site on the AppStore, and downloaded it to my iPhone. Can you give or email me instructions on how I can get the iOS application that opens the beta/test site?

**Comment by viorelaioia** [comment]
hi @munteanu210 ! If you go to FAQ page on the mobile Common Voice app, then scroll down to the bottom of the page, there is a "Go to staging" button available, barely visible. Taping that button will take you to the staging version of Common Voice, where the "About" page is available.

**Comment by munteanu210** [comment]
@viorelaioia thanks for directions. I found the "Go to staging" button.
