### ISSUE TITLE
Hire a UX/UI person

### ISSUE THREAD

**Issue by geroter** [mozilla/voice-web#2]
Need a UX/UI contractor for roughly 1-2 weeks for interaction and visual design of the responsive website layout.

**Comment by geroter** [comment]
George talking to:
http://www.thegeekettez.com/hellogeekettez/

https://www.iglika.co/contact/

**Comment by geroter** [comment]
Aiming for a final decision on this by May 15th.

**Comment by mikehenrty** [comment]
\o/
