### ISSUE TITLE
Discourse button is not correctly displayed

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2000]
[Environment]:
Windows 10 , Mac OS 10.14 - Firefox, Chrome
Android - Firefox

[Note]:
The issue is not reproducible on iOS(iPhone 7)

[STR]:
1. Open https://voice.allizom.org/en/about#get-involved

[Expected result]:
Discourse button should look as per wireframes: https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5c928d675947a201e25becdd
[Actual result]:
Discourse button is not correctly displayed

![2019-05-02_16h44_47](https://user-images.githubusercontent.com/41474886/57079711-99881680-6cf9-11e9-8388-becdbf8a4c8e.png)

@munteanu210

**Comment by munteanu210** [comment]
@rleitan thanks for your feedback. Working on it already.

**Comment by munteanu210** [comment]
@rleitan @Gregoor I fixed this one and it was merged with the master.

**Comment by rleitan** [comment]
Verified as fixed
