### ISSUE TITLE
Partners button is selected when clicking Get involved button

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2001]
[Environment]:
Windows 10 - Firefox, Chrome
not reproducible on Mac 10.14 - Firefox
[STR]:
1.Open https://voice.allizom.org/en/about
2. Click "Get involved"  wave button

[Expected result]:
Get involve wave button should be highlighted and the page should be scrolled to Get Involved section

[Actual result]:
Partners wave button is selected instead of  Get involve one and the page is scrolled to Get Involved section

![2019-05-02_16h47_20](https://user-images.githubusercontent.com/41474886/57080030-5b3f2700-6cfa-11e9-97bc-eff2474e9aeb.png)

@munteanu210

**Comment by arnavvats** [comment]
Hi, fixed the issue. Please review PR.

**Comment by munteanu210** [comment]
@arnavvats thanks for fixing this! I checked it and it works great! We will merge this.

**Comment by munteanu210** [comment]
@Gregoor this current issue (#2001) was solved and merged. It works good now. Please close this issue at your earliest convenience. Thank you.

**Comment by rleitan** [comment]
Verified as fixed!
