### ISSUE TITLE
Add personal goals prompt to submission success screen

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#2008]
@Gregoor can we add the [personal goals prompt copy](https://overflow.io/s/92K0N8/?node=38f4d754) to the submission success screen for english localized profile owners?

Copy has changed a bit from that linked UX screen:

>Help reach 10,000 hours in English, set a personal goal
>`Get started`

**Comment by mbransn** [comment]
FYI @viorelaioia @rleitan

**Comment by Gregoor** [comment]
Just noticed that it's already implemented 😁 It's only shown when you don't have goal set yet though.
