### ISSUE TITLE
Mind the goals gap

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#2009]
@Gregoor we've got some wayward padding or margin beneath the goals section. Should always be flush with the footer, halp please. :)

![Screenshot_2019-05-02 Common Voice by Mozilla](https://user-images.githubusercontent.com/18686986/57095749-6ed19a00-6cc8-11e9-9343-901dbec8cfa7.png)

FYI @viorelaioia @rleitan

**Comment by Gregoor** [comment]
Huh, I don't see that gap in Chrome nor FF. Was it Safari? Then I'll check on a macbook later today.

**Comment by mbransn** [comment]
Intriguing. I was on Nightly 🌃

**Comment by f0cus10** [comment]
Checked Safari. Could not reproduce.
