### ISSUE TITLE
[mobile] Page scrolls up when expanding a question from FAQ page

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2010]
**Env:**
iPhone 7, iOS 12.2, Firefox and Safari

**STR:**

1. Navigate to https://voice.allizom.org/en/faq-new
2. Scroll down and tap a question in order to expand it
3. Scroll down to see the entire content, then tap another question

**Expected:**
Question is expended and the answer is displayed

**Actual:**
Page is scrolled up, answer is not visible entirely. User needs to scroll down in order to see the entire content of the answer. See [video](https://vimeo.com/333958167)

CC @munteanu210

**Comment by munteanu210** [comment]
@viorelaioia thanks for your feedback. I am working on it.

**Comment by arnavvats** [comment]
Hi, made a small fix, please review PR.

**Comment by arnavvats** [comment]
Hi, please review the PR.

**Comment by munteanu210** [comment]
@arnavvats I checked your PR. Unfortunately, your update didn't fix the problem. I added a 200ms timeout for executing scrollIntoView and it seems to work well at the first glance. However, reviewing your PR further, there are two problems that I identified: 

- a) the title still goes under the menu on FAQ answers that have a lot of text, such as [this one](https://www.screencast.com/t/TXYJUomZvv9q); 
- b) I doubt that this would be accepted: document.querySelector('.question-block.active'). 

I am working with the team on identifying a solution to this current issue (#2010).

**Comment by arnavvats** [comment]
okay, thanks

**Comment by arnavvats** [comment]
what should be a better alternative for querySelector here?

**Comment by munteanu210** [comment]
@arnavvats, I am discussing with the team about alternatives. Will let you know what we decide.

**Comment by munteanu210** [comment]
@viorelaioia @arnavvats I fixed this issue by allowing multiple FAQ questions to be opened at the same time on mobile. I tried a few other ways to fix this, but it was always causing additional problems. This fix works great.
