### ISSUE TITLE
About & FAQ code review

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#2011]
I'm going to have to agree with my first reaction, I think the code looks great overall. Here's a couple of things that could still be improved upon:

## JS
https://github.com/mozilla/voice-web/blob/86c94714998e5061ce6c4f1f0dde1fe2df2672cb/web/src/components/pages/about/how-it-works.tsx#L210-L230
- [x] The naming here is a little unclear to me (`FLOWCHART` vs `flowchart`). The elements of the flowchart could maybe be named something like `chartNode`?
- [x] it's also unclear to me where the naming numbers come from, maybe add constants with descriptive names instead or a comment that explains them all

https://github.com/mozilla/voice-web/blob/86c94714998e5061ce6c4f1f0dde1fe2df2672cb/web/src/components/pages/about/how-it-works.tsx#L210-L221
- [x] could be combined with a fragment (`navType == 'mobile' && <><Child1/><Child2/></>`)

https://github.com/mozilla/voice-web/blob/86c94714998e5061ce6c4f1f0dde1fe2df2672cb/web/src/components/pages/about/slider.tsx#L22-L35
- [x] `slides` can be a constant outside of state (as it doesn't change)
- [x] `nextSlide` and `prevSlide` aren't needed, can be derived from `activeSlide` and `slides.length`

https://github.com/mozilla/voice-web/blob/86c94714998e5061ce6c4f1f0dde1fe2df2672cb/web/src/components/pages/faq/faq.tsx#L35
- [x] TS should be able to derive the type of the event itself (and more accurately as `React.MouseEvent<Something>`), so no manual typing necessary :)

https://github.com/mozilla/voice-web/blob/86c94714998e5061ce6c4f1f0dde1fe2df2672cb/web/src/components/pages/faq/faq.tsx#L144-L149
- [ ] Unless the existence of children is dynamic, I'd prefer it to be consistenly written as `<button><SomeChild/></button`

https://github.com/mozilla/voice-web/blob/0ed6fb257cf5588987425267b0a98e8b9522546f/web/src/components/pages/faq/selectors.tsx#L131-L139
- [x] I have mixed feelings about this: I think it's a little hard to read, but I think I also wrote it in a very similar way for the old FAQ page. So I shouldn't throw stones from within my glasshouse. If you have an idea how to make it less concise and more readable that'd be great, if not I'll think about it because I feel responsible for having laid the foundation 😁 

https://github.com/mozilla/voice-web/blob/0ed6fb257cf5588987425267b0a98e8b9522546f/web/src/components/pages/faq/selectors.tsx#L140-L154
- [x] let's `return true` early if `!search` (reduces nesting)
- [x] if we use [`.some()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) instead of `.reduce()`, we don't need the `carry` (and it's faster, because it stops as soon as an element satisfies the condition
- [x] `aId` is the name of the list and of its elements. Clearer/differentiated naming would help readability here
- [x] micro (err, nano?)-optimization for `!stringContains(getString(qId), search) && !answerFound`: flip the conditions as the latter is quicker to check

## CSS
- [x] no need to browser-prefix in the CSS, we have PostCSS plugin that takes care of that
- [x] the about CSS could be subdivided into multiple files, I think the high level selector match pretty nicely with the already existing component subdivision:
![Screenshot (15)](https://user-images.githubusercontent.com/4051932/57145662-ffd96b80-6dc3-11e9-8a1a-69691d421883.png)
- [x] somewhat related to the point above, the nesting is a little too deep for me to get a good overview. So far we don't have any hard and fast rules about max nesting depth, but my gut feeling is sth like ~5 layers deep. Let me know if you feel differently about that. A way to fix it: use classnames that are unique enough that you can safely lift the selectors a (few) layers up
- [x] since we're talking linting, I noticed that I've been relying on the luxury of having an editor that shows duplicate CSS rules (i.e. multiple declarations of the same property). There's a couple of those in the files. Let me know if you want me to set up a linter so that you'd have an easier time finding those.

## Other
- [x] PNG optimization isn't part of our build pipeline, [pngquant](https://github.com/kornelski/pngquant) can help with that

Thanks again for your great work, @munteanu210! Let me know if you'd like to talk about any of this, happy to discuss, find solutions or take back things I might've misunderstood or be wrong about 🙂 

Oh and happy that you've added `classnames`, should've done that a while ago. It just makes things easier to read and less error-prone.

**Comment by munteanu210** [comment]
@Gregoor thanks a lot for your thorough review and feedback! I will work on these updates next, and I will let you know if any questions.

**Comment by munteanu210** [comment]
@Gregoor, I implemented some of your feedback already. I'm still working on it and will submit the rest of the updates shortly.

**Comment by Gregoor** [comment]
Great work, thank you! :)
