### ISSUE TITLE
multiple dummy user_clients with new client_id created on page reload

### ISSUE THREAD

**Issue by imans777** [mozilla/voice-web#2015]
Hi,
I noticed a bug when I used this app which, if proven to be correct and not a mistake of mine, will make some part of our data misjudged and invalid!

I cloned the project and brought up the database. I tried to login and completed my profile and a new record added to user_client table. So far so good. Then I tried refreshing the page multiple time and I noticed that sometimes a new record is added to user_clients! This new record has its every fields NULL, except the client_id, and this new client_id is used, fortunately not when voting or recording new clip, but when fetching new sentences. On this condition, it shouldn't fetch our sentences or the sentences that we've voted so far, but because of this bug, our client_id is changed, and because of that, we would receive those sentences too! and we can vote on our sentences or sentences that we've voted before! And this has a real bad effect in our final result.

Fortunately, as I said, when we record new clip or vote to a clip/sentence, our original client_id is used, so that won't be any problem.

P.S. I looked up where this problem occurs and I noticed it was in `server/src/lib/api.ts:getRouter()`, when we check for `UserClient.hasSSO` and in its `else` part, it will create a new user_client (`this.model.db.saveUserClient`), which results in this problem.

Thanks in advance.

**Comment by Gregoor** [comment]
Hi,

thankslots for the detailed report, much appreciated! And unfortunately I can reproduce it. I do remember it working as intended, but I guess there were some unforeseen ripples, as it goes. An indicator that we should have test suites covering this? Probably.

I just pushed a commit that prefers using the auth0 user's client_id, if available. But it's late, so I wanna make sure it works as expected tomorrow before pushing it to production. Also I should prevent the frontend from generating new client_id's on refresh (i.e. figure out what even caused this).

Thanks again for your diligence!

**Comment by Gregoor** [comment]
Alright, some good news: It was a recent regression indeed. In a commit 2 weeks ago I've disabled localStorage-persisting of a user's account (so that we don't show notifications based on outdated information). Unfortunately the presence of that field was used to determine whether a new ID needs to be generated. Now it also depends on whether the account is currently being fetched.

Thanks again! Very helpful report!
