### ISSUE TITLE
A dot is added when pressing space bar in search input field

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2016]
[Environment]:
Mac OS 10.14 - Chrome, Safari
not reproducible on Windows 10 - Chrome

[STR]:
1.Open https://voice.allizom.org/en/faq-new
2.Go to search bar and type something (e.g voice)
3.Add two spaces with the space tab

[Expected results]:
Two spaces should be added

[Actual result]:
A space and . are added

https://vimeo.com/334441768
@munteanu210

**Comment by munteanu210** [comment]
@rleitan you will be able to make the two space tabs convert to a dot on other web pages, browsers, and even in text editors. That's a setting on your Mac. You can enable or disable this setting. Here is an [article about that](https://www.idownloadblog.com/2016/12/19/how-to-stop-your-mac-from-inserting-a-period-when-you-double-press-the-space-bar/). This being said, there is nothing I can do here, so as this is a keyboard setting controlled by every Mac user.
