### ISSUE TITLE
Datasets do not download in Chrome

### ISSUE THREAD

**Issue by LRSaunders4** [mozilla/voice-web#2025]
When trying to download the datasets, I cannot check the two check boxes required to enable the download button after I enter my email. 

This only happens in Chrome, not in Firefox.

![dataset_bug_1](https://user-images.githubusercontent.com/48598353/57453810-f3726a00-722c-11e9-8245-55a41bf9bcff.png)

**Comment by f0cus10** [comment]
Can confirm this issue exists in `Chromium 74.0.3729.131` in **both** the staging and release server. 

I could not reproduce the issue in `Firefox 68.0a1 Nightly`.

The attributes are being passed as `read-only` for the checkbox elements.
