### ISSUE TITLE
change the bucket of a user

### ISSUE THREAD

**Issue by bayethiernodiop** [mozilla/voice-web#2027]
Hello i have deployed the project locally but since i dont have many sentences, my users have blank pages when they record all the sentences in their allocated buckets (train/dev/test set) is there a way to change their bucket manually in the database. i tried to change the values in the table user_client_locale_buckets but no effect. Thanks in advance

**Comment by Gregoor** [comment]
Heya, while the bucket tables are still there, we're not using them anymore on master (as they didn't have the intended effect).

**Comment by bayethiernodiop** [comment]
ok i see but the user is still affected to a bucket for recordings ? cause some of my recorder can't record anymore yet they didn't record all the sentences in all buckets

**Comment by Gregoor** [comment]
They should now be able to record every sentence available, as sentences aren't served by bucket anymore

**Comment by bayethiernodiop** [comment]
ah ok thx. is this change new because i think i have the version that was available since about 3 months.

**Comment by Gregoor** [comment]
Yup! It's a bit of a recent change, since we weren't satisfied with the results of bucketing. If you update to the latest version of master, it should be gone

**Comment by bayethiernodiop** [comment]
ah perfect. thanks a lot
