### ISSUE TITLE
Enable Nepali (ne-NP) locale in Common Voice for voice collection.

### ISSUE THREAD

**Issue by roshangm1** [mozilla/voice-web#2034]
We have nearly 1000 approved sentences and want to start recording and validating voices for these sentences. Can you please enable Nepali locale in the common voice website?

**Comment by roshangm1** [comment]
//cc @Gregoor @MichaelKohler

**Comment by MichaelKohler** [comment]
The sentences will be part of my next export (around mid next week I'd say)

**Comment by Gregoor** [comment]
The requirement is atm 5k sentences, it will be semi-automatically enabled (aka ping me and I'll run the script) .
