### ISSUE TITLE
After we show the privacy policy, we should say thank you

### ISSUE THREAD

**Issue by jofish** [mozilla/voice-web#205]
Right now we just dump the user back on the recording page. It's not clear what happened. We should have an interstitial dialog of some kind saying "Thank you! We'll add your sentences to the language model" or whatever.

**Comment by jofish** [comment]
Sorry, this is in the IOS app.

**Comment by mikehenrty** [comment]
Yeah, this is a problem. We have a whole onboarding flow we are working on (which includes what happens after your first submission. Stay tuned!

**Comment by mikehenrty** [comment]
Let's close this bug for now. We already say thank you on the submit page. And we will soon add a whole new first time experience to address this bug, but we will open new bugs for that.
