### ISSUE TITLE
New UI Issue Partners page

### ISSUE THREAD

**Issue by georai** [mozilla/voice-web#2056]
Mobile: please take a look: https://zpl.io/V1Ok7Mk

Desktop: zpl://screen?pid=5a9eec5c53a9a2685450d4be&sid=5cdf46f99544091df5826509

![Common Voice (1)](https://user-images.githubusercontent.com/9335801/58513100-b71b9500-816c-11e9-8210-a08628730aaa.png)
![Common Voice](https://user-images.githubusercontent.com/9335801/58513101-b71b9500-816c-11e9-8e19-e18e46995613.png)

**Comment by Gregoor** [comment]
I made some of those adjustments, the ones I didn't make:

Everything concerning the benefits section, I've left it as is from the home page for now.

Scroll bars are not shown on Apple operating systems. Nothing sane we can do here.

Some of the comments I couldn't quite parse like:
"Add a line", "Looks grey", "Zeplin changes", "Small changes on the waves"

I need something a little more explicit please.
