### ISSUE TITLE
Page broken after language was added to profile

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#2064]
## Steps to reproduce

1. add a language to profile
1. open homepage

It looks like this for me:

![Screenshot from 2019-06-08 14-26-22](https://user-images.githubusercontent.com/91113/59147292-ee563580-89f9-11e9-9c9c-c1f9a1db47c0.png)

related to https://github.com/mozilla/voice-web/issues/2063

## Workaround

reload page

**Comment by Gregoor** [comment]
Couldn't reproduce. Maybe a temp outtime. Does it still happen?

**Comment by davidak** [comment]
I'm also not able to reproduce this again.
