### ISSUE TITLE
Language not added to profile

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#2065]
## Steps to reproduce

1. add language to profile
1. save settings
1. reload page

It looks like this now

![Screenshot from 2019-06-08 14-31-28](https://user-images.githubusercontent.com/91113/59147321-4bea8200-89fa-11e9-8451-6ce848512c0e.png)

All data is gone!

## Workaround

reload page and clear cache (Control+Shift+R)

## Related to

https://github.com/mozilla/voice-web/issues/2064
https://github.com/mozilla/voice-web/issues/2063

**Comment by Gregoor** [comment]
I'm having trouble reproducing this, are there any other steps that reproduce it? Does it also happen with new profiles?

**Comment by davidak** [comment]
I'm able to reproduce it even on another computer.

Also with a new account adding the first language.

**Comment by Gregoor** [comment]
Weird, can't reproduce even on Chrome. Maybe some addon? Does it happen in private mode as well?

**Comment by davidak** [comment]
>Does it happen in private mode as well?

yes

**Comment by Tretboot** [comment]
I can reproduce it too. Just reload the profile and its empty, Control+Shift+R and its back. 

Tested on Google Chrome 74.0.3729.169 on Windows 10 Pro 1809

**Comment by Gregoor** [comment]
Can someone create a screen recording for me? I unfortunately can't seem to reproduce it with any of my profiles.

**Comment by davidak** [comment]
>Can someone create a screen recording for me?

@Gregoor sure

[simplescreenrecorder-2019-06-13_14.35.14.webm.zip](https://github.com/mozilla/voice-web/files/3286023/simplescreenrecorder-2019-06-13_14.35.14.webm.zip)

**Comment by Gregoor** [comment]
Awesome, thankslots David! Unfortunately I'm still not able to reproduce this.

@rleitan if you have time, can you help me reproduce this?

**Comment by davidak** [comment]
@Gregoor what's your setup?

When i reload and clear the cache (Control+Shift+R), i also not get the data every time, like you see at the end of the video.

**Comment by Gregoor** [comment]
I've tried both FF 68 and Chrome 75. Actually was able to reproduce it once on Chrome, but so far only once, which makes it hard to debug what's going on.

**Comment by Gregoor** [comment]
Thanks everyone for the help, I think I found the timing issue and took this as an opportunity to refactor the whole component. It will be on staging (https://voice.allizom.org) in less than an hour.

Happy to get reports if anything on staging still feels broken!

**Comment by davidak** [comment]
I can not reproduce it on staging. Good job! :tada:

**Comment by Gregoor** [comment]
Awesome, thanks again for the help and detailed reports!
