### ISSUE TITLE
List locales with localized discourse and change links on the site

### ISSUE THREAD

**Issue by nukeador** [mozilla/voice-web#2070]
We should have a list with all the locales currently with a localized discouse subcategory and make sure we change any discourse link on the site to include that.

Current locales with discourse

de,
fr,
it,
es,
zh-TW

We can dynamically change urls just adding the locale code, example

https://discourse.mozilla.org/c/voice/fr

**Comment by nukeador** [comment]
@Gregoor Is it OK if I create a PR with discourse.json with the list of locales and then we'll figure out the implementation on the site?

Asking because Activate site wants to consume this list of locales for the same purpose, and makes more sense to be maintained in the same place we list other characteristics of Common Voice locales.

**Comment by nukeador** [comment]
Clarification, I don't want to push to prioritize any changes on voice-web, just to have the list in the repo for now.

**Comment by Gregoor** [comment]
@nukeador sounds good, implementation should be fairly straightforward, so I can quickly do it once we have the list of locales.

**Comment by nukeador** [comment]
https://github.com/mozilla/voice-web/pull/2072
