### ISSUE TITLE
Ensure locale metadata is passed to newsletter/email subscriptions

### ISSUE THREAD

**Issue by nukeador** [mozilla/voice-web#2073]
We need to make sure when a user subscribes to the newsletter/email from a localized version, we capture the locale variable and pass that to Salesforce, so we can have that metadata for localized comms.

**Comment by Vishal19111999** [comment]
I want to solve this as my first bug. Can anyone guide me?

**Comment by Gregoor** [comment]
Great! What I'd grep for is the places where synchronize subscriptions status with `basket`. It might already be centralized in one place. And here's the basket docs: https://basket.readthedocs.io/newsletter_api.html#news-subscribe

**Comment by parshva-b** [comment]
@nukeador @Gregoor  Is this issue still open and unassigned? I would love to work on this issue

**Comment by phirework** [comment]
We don't have the capability to localize email right now and the whole Basket connection is being revisited, so I will close this for now.
