### ISSUE TITLE
Need sync from sentence collector

### ISSUE THREAD

**Issue by mozillakab** [mozilla/voice-web#2074]
It has been a while that we didn't get a new sych from SC. I'm seeing some hard corpora added. 
We gave up with Sentence Collector?
We have more that 10 000 vanlidated sentences for kab waiting for sync.

**Comment by MichaelKohler** [comment]
https://github.com/mozilla/voice-web/pull/2071/files#diff-f32e35d65911c87beedd37ad900aa81c has the latest export. This here can be closed.

**Comment by mozillakab** [comment]
Thanks @MichaelKohler I did'nt see.
