### ISSUE TITLE
Enable "rm-sursilv" on staging

### ISSUE THREAD

**Issue by gion-andri** [mozilla/voice-web#2076]
Romansh Sursilvan "rm-sursilv" is completely translated on Pontoon (https://pontoon.mozilla.org/rm-sursilv/common-voice/). It would be nice, if we could have a look at it on staging to check if everything looks good and is translated in the proper context. 
Thanks!

**Comment by peiying2** [comment]
@Gregoor please help investigate this. If it is fluent issue, @stasm will be able to answer.

**Comment by stasm** [comment]
This might be a bug in `fluent-langneg`, sorry about it. I'll investigate.

**Comment by stasm** [comment]
I've just published `fluent-langneg` 0.2.0 with a fix contributed by @gion-andri :) Thank you!

**Comment by gion-andri** [comment]
@Gregoor How are you handling dependency updates in this project? Do you bump them on a regular basis? Do you have a process there in place that has to be followed? Or shall I open a PR to update `fluent-langneg` to v0.2.0?

**Comment by Gregoor** [comment]
No process really, I just sporadically update all the deps. Which is what I'll do now. Thanks for the fix!

**Comment by gion-andri** [comment]
@Gregoor Thanks a lot for the update! It seems to work now all fine 👍
