### ISSUE TITLE
Way to download more than one dataset without having to fill out email N times

### ISSUE THREAD

**Issue by ftyers** [mozilla/voice-web#2080]
I want to download all the datasets apart from English, French, German and Chinese. There should be a way to do this without having to fill out the email address N times. 

I am logged in as my Common Voice user, so perhaps the email thing could just be disabled for those people who are logged in and they could just get a download icon next to the dataset ideally one that was in the HTML and could be scraped from the command line.

**Comment by Gregoor** [comment]
I've pushed a commit that logs every download link to the console, once you've triggered the first download (so that the legal flow is still in-place).
