### ISSUE TITLE
Blue dividers are displayed in language drop-down

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2082]
[Environment]:
Mac OS 10.14 - Firefox Release

[STR]:
1.Open https://voice.allizom.org/en/datasets
2.Minimize the window size( mobile size)
3.Click the language drop-down menu
4.Hover the listed languages from the bottom-up

[Actual result]:
The languages are divided by blue lines

https://drive.google.com/file/d/1yX6vGBBEb9p-eEhZFOI_DYOGeAtr2gKa/view?usp=sharing

[Note]:
The issue is intermittent

@Gregoor

**Comment by Gregoor** [comment]
Looks like a Fx rendering bug, couldn't reproduce it. Let's keep an eye on it
