### ISSUE TITLE
English sentences made it in French dataset during Wikipedia import

### ISSUE THREAD

**Issue by lissyx** [mozilla/voice-web#2084]
At least one occurrence:
 - `server/data/fr/wiki-2.fr.txt`:Served with it, a vegetable and potatoes in one of a dozen tempting styles.

cc @Gregoor

**Comment by lissyx** [comment]
From `server/data/fr/wiki-2.fr.txt`:
 - What's it going to do, vanish?
 - Is it not going to be there when I get back?

**Comment by lissyx** [comment]
Maybe we could leverage something like https://github.com/kent37/guess-language

**Comment by lissyx** [comment]
https://pypi.org/project/guess_language-spirit/

@Gregoor If you don't have time I'll try and use that tomorrow to do some cleanup. In the mean time, there may be some PRs in flight to fix some of those sentences identified by contributors

**Comment by nukeador** [comment]
Thanks @lissyx if you can do PR with removals that would be. We need to also understand how many are there and guess why they got into the French wikipedia extraction.

**Comment by lissyx** [comment]
> Thanks @lissyx if you can do PR with removals that would be. We need to also understand how many are there and guess why they got into the French wikipedia extraction.

Someone else is going to send some PRs, I'll tackle the rest tomorrow.

**Comment by lissyx** [comment]
ok, I'm having troubles getting something really usable out of this tool: lots of false positives and false negatives ...

**Comment by lissyx** [comment]
```
#!/usr/bin/env python3

import sys
import argparse
import guess_language
import json

def main(lang, hints, file, debug):
    rejected = {}
    count = 0

    for line in file:
        guessed_lang = guess_language.guess_language(text=line, hints=hints)
        if guessed_lang != lang:
            if not guessed_lang in rejected.keys():
                rejected[guessed_lang] = []
            rejected[guessed_lang].append(line)

            if debug:
                print('reject', guessed_lang, line)

        count += 1

        if not debug:
            sys.stderr.write('Treated: ' + str(count) + '\r')

    sys.stdout.write(json.dumps(rejected))

if __name__ == "__main__":
    PARSER = argparse.ArgumentParser(description='Checking per-line language of a text file')
    PARSER.add_argument('--lang',
                        required=True,
                        type=str,
                        help='Language code supported by guess_language-spirit')
    PARSER.add_argument('--hints',
                        default='',
                        required=False,
                        type=str,
                        help='Comma-separated language codes hints')
    PARSER.add_argument('--file',
                        required=True,
                        type=argparse.FileType('r'),
                        help='Text file to check')
    PARSER.add_argument('--debug',
                        default=False,
                        required=False,
                        type=bool,
                        help='Show progress per line, instead of global ')
    PARAMS = PARSER.parse_args()

    main(lang=PARAMS.lang, hints=PARAMS.hints.split(','), file=PARAMS.file, debug=PARAMS.debug)
```

And running:
`$ python3 check_lang.py --lang fr --hints fr --file server/data/fr/wiki-2.fr.txt > server/data/fr/wiki-2.fr.txt.rej `

**Comment by lissyx** [comment]
So, it looks like, we have roughly:
 - 2400 invalid sentences in `server/data/fr/wiki-1.fr.txt` over 1000000
 - 3114 invalid sentences in `server/data/fr/wiki-2.fr.txt` over 1094942

**Comment by lissyx** [comment]
@nukeador Do you think there is value in merging the little python tool ?

**Comment by nukeador** [comment]
We would have to integrate it on the wiki extractor I guess. @Gregoor ?

**Comment by lissyx** [comment]
> We would have to integrate it on the wiki extractor I guess. @Gregoor ?

That might be a good thing, but I might not have time to do that. it could also be of value for filtering other datasets (I plan on having a look at that later as well).

**Comment by lissyx** [comment]
> ```
> $ wc -l server/data/fr/wiki-*.fr.txt ; wc -l server/data/fr/wiki-*.fr.txt.new
>   1000000 server/data/fr/wiki-1.fr.txt
>   1094942 server/data/fr/wiki-2.fr.txt
>   2094942 total
>    997588 server/data/fr/wiki-1.fr.txt.new
>   1091842 server/data/fr/wiki-2.fr.txt.new
>   2089430 total
> ```

Running a bit differently to catch more (the example from the first post was not caught at first):
```
$ python3 check_lang.py --lang fr --hints fr,en --file server/data/fr/wiki-1.fr.txt > server/data/fr/wiki-
$ python3 check_lang.py --lang fr --hints fr,en --file server/data/fr/wiki-2.fr.txt > server/data/fr/wiki-2.fr.txt.rej
$ python3 apply_reject.py --source-file server/data/fr/wiki-1.fr.txt --target-file server/data/fr/wiki-1.fr.txt.new --reject-file server/data/fr/wiki-1.fr.txt.rej 
$ python3 apply_reject.py --source-file server/data/fr/wiki-2.fr.txt --target-file server/data/fr/wiki-2.fr.txt.new --reject-file server/data/fr/wiki-2.fr.txt.rej 
```

And the result is:
```
$ wc -l server/data/fr/wiki-*.fr.txt
  1000000 server/data/fr/wiki-1.fr.txt
  1094942 server/data/fr/wiki-2.fr.txt
  2094942 total
$ wc -l server/data/fr/wiki-*.fr.txt.new
   994804 server/data/fr/wiki-1.fr.txt.new
  1088382 server/data/fr/wiki-2.fr.txt.new
  2083186 total
```

**Comment by Gregoor** [comment]
Awesome, thanks Alexandre. Yeah let's add it to the list of things, we should add. I'll create a tag for it.
