### ISSUE TITLE
Some sentences are written with capitals

### ISSUE THREAD

**Issue by paulsilaghi** [mozilla/voice-web#209]
Chrome 59, Win 10
Not sure if expected or not, but we may want to keep the consistency.

![capitals](https://user-images.githubusercontent.com/29535384/27378950-2986188a-5682-11e7-9619-93c07ca8a81a.png)

**Comment by kdavis-mozilla** [comment]
It is on purpose[[1](https://github.com/mozilla/voice-web/blob/master/server/data/funny.txt#L35)]. It's a joke[[2](http://funnytweeter.com/me-ah-now-i-will-drift-gently-off-to-dreamland-refrigerator-i-shall-make-us-some-ice-cubes/)].

**Comment by mikehenrty** [comment]
no one ever said they were good jokes ;)

**Comment by paulsilaghi** [comment]
:))
thanks for explaining, guys.
