### ISSUE TITLE
It is not possible to listen for samples on Focus for Android

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voice-web#210]

**Comment by kdavis-mozilla** [comment]
This is blocked by mozilla-mobile/focus-android#804

**Comment by kdavis-mozilla** [comment]
Changing priority as focus can't play audio using our current setup mozilla-mobile/focus-android#804

**Comment by mikehenrty** [comment]
This was fixed when we switched to playing directly from s3 rather than streaming from our app.
