### ISSUE TITLE
"About" page - sentence makes no sense

### ISSUE THREAD

**Issue by Adrijaned** [mozilla/voice-web#2107]
Page "About", first sentence of second paragraph under "Why Common Voice?" makes no sense, at least to me. The sentence, for reference, is "Both of these projects are part of our efforts to bridge the digital speech divide." - seems like there might be a few words missing? Could someone explain me the intended meaning, or fix the sentence if it is indeed incorrect?

**Comment by Gregoor** [comment]
Both is referencing Common Voice and Deep Speech, which are named in the first paragraph.

**Comment by Adrijaned** [comment]
I'm talking now specifically about the second part of the sentence, "bridge
the digital speech divide". Bridge the _gap_ digital speech divide_s_? What
gap, then? Or is there something else missing? Or, equally probable option,
am I just missing something? Or overthinking it in some way?

**Comment by Gregoor** [comment]
Oh, thanks for the elaboration. I misunderstood the first comment then. The grammar looks correct to my english-as-a-2nd-language-eyes. I also don't quite understand where "gap" comes from in your comment. One can bridge a divide, but also a gap. Or is it confusion about "divide" being a noun in this context?

**Comment by Adrijaned** [comment]
Wait, divide is also applicable as noun? That might explain a lot. So from
a context and some handy examples sentences it could be understood as "to
bridge the difference between digital data and natural speech" (kinda
weirdly expressed, but captures my intention well)? Correct me if I'm
wrong. I daresay I understand English fairly well, but this sentence caught
me off guard. Also, even Cambridge dictionary I'm used to use to look up
things in for reference rates such use of the word as C1 level English, so
would it still be possible to change that sentence somehow to ease the
reading for us clueless non-native speakers?

**Comment by Gregoor** [comment]
Yes, that's what that sentence is conveying! And neat, didn't know Cambridge did language levels.

We could aim for more accessible english, I'm not sure how to strike the best balance here though. I like how our copywriter makes those sentences punchy.

**Comment by Adrijaned** [comment]
I mean, I would not consider rewriting it to be the highest priority, especially if it would not read as nice afterwards. You can still kinda guess what the poet tries to say, and I would not have even noticed this were I not trying to translate it on the Pontoon. So unless you have any more comments on this, I'd consider this issue resolved, feel free to close whenever you see fit.

**Comment by Gregoor** [comment]
Cool, agreed! Thanks for reaching out.
