### ISSUE TITLE
Duplicated text on Privacy Policy

### ISSUE THREAD

**Issue by reinhart1010** [mozilla/voice-web#2108]
![Screenshot_20190716-141833_Firefox](https://user-images.githubusercontent.com/17312341/61273907-d16d0900-a7d4-11e9-9568-7fc79ac97d29.jpg)

**Comment by Gregoor** [comment]
That indeed looks off, thanks for the report! Our legal docs live over here: https://github.com/mozilla/legal-docs/blob/master/Common_Voice_Privacy_Notice/en.md

@peiying2 should I take a stab at fixing that sentence?

**Comment by MichaelKohler** [comment]
This has been fixed in the meantime.
