### ISSUE TITLE
Callback URL mismatch

### ISSUE THREAD

**Issue by EuphoriaCelestial** [mozilla/voice-web#2113]
My docker-build instance of CV is having problem with login function. After click Login, it show a Auth0 page, says: 
      "The provided redirect_uri is not in the list of allowed callback URLs."
It doesnt show the correct URL to add to Auth0 setting page as usual, I dont know how to solve this
It happen after I try to remove port number from my website's URL (from abcxyz.com:9000 to abcxyz.com).

**Comment by EuphoriaCelestial** [comment]
#Update: after I added another callback URL in Auth0 setting page ("localhost:9000"), finally it can go to the login page, but after click Login, it say "unable to connect to localhost:9000
![Screenshot from 2019-07-18 11-46-39](https://user-images.githubusercontent.com/43977734/61429818-f2a73400-a951-11e9-9a84-e466c3fea312.png)
"

**Comment by MichaelKohler** [comment]
Is this still happening? If so, can you provide logs?

**Comment by EuphoriaCelestial** [comment]
I have fixed the issue, thank you!
