### ISSUE TITLE
'All languages' goals awards are displayed in stats when selecting a language

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2120]
[Precondition]:
Have a  CV profile with multiple language added
Have award for a language (e.g. English)

[STR]:
1.Set a goal for other language and achieve it (e.g. daily goal for listen - German language)
2.Go to https://voice.allizom.org/en/stats page and select German from Your Languages section
3.Click Awards button

[Expected results]:
Only awards for selected language should be displayed

[Actual result]:
All awards are displayed

I expect to see all awards only when I select "All languages"
@mbransn should be displayed on which language we got the award?

**Comment by mbransn** [comment]
This is a good question @rleitan -- @Gregoor currently is someone able to duplicate awards? meaning achieve all of the same awards across all of the languages? My expectation would be yes, but I realize that we may not have implemented this way. e.g. If I contribute in English for the first time and get the 1st contribution award; then I contribute for the 1st time in German I should also get the 1st contribution award.

>I expect to see all awards only when I select "All languages"
>@mbransn should be displayed on which language we got the award?

@rleitan Ideally yes, though I realize we didn't prepare UI for this. @Gregoor is it possible to create language subcategory rows for awards within their categories of Daily, Weekly, etc?

**Comment by Gregoor** [comment]
Yup, all the awards are for across languages. Didn't start tackling the missing custom goals features (https://github.com/mozilla/voice-web/issues/1909), let's continue that tracking over there (and maybe prioritze to tackle it now.
