### ISSUE TITLE
TypeError: this.scroller is null when clicking Listen button from goals page

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2123]
[Precondition]:
Have Chuvash language added to your profile
Add a listen goal for Chuvash language

[STR]:
1.Go to https://voice.allizom.org/en/goals page 
2.Select Chuvash language
3.Press Listen button from Custom goals section

[Expected result]:
The page should be properly redirected to https://voice.allizom.org/cv/listen

[Actual result]:
Browser console error: TypeError: this.scroller is null bundle.js:97:174055
    componentDidUpdate https://voice.allizom.org/dist/bundle.js:97

Sometimes, the page (https://voice.allizom.org/cv/listen) is blank for ~2 seconds then it's loaded

**Comment by Gregoor** [comment]
I can't seem to reproduce it, is it still occuring?
