### ISSUE TITLE
404 Error when opening manage subscriptions link

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2124]
[Precondition]:
Have a goal set

[STR]:
1.Go to edit your goal
2.On the 4th step, click the Manage Subscriptions link

[Actual result]:
The link redirects the page to https://www.mozilla.org/en-US/cv/newsletter/existing/e609957b-9d37-462d-9432-3375287c48f2 and 404 Error is displayed

[Actual result]:
<img width="1173" alt="Screenshot 2019-07-25 at 14 41 36" src="https://user-images.githubusercontent.com/41474886/61875445-ec353100-aeea-11e9-8d5a-daef22fff54d.png">

**Comment by Gregoor** [comment]
Unfortunately there's no management interface for the email backend we use on staging (which I assume is where this was encountered?)
