### ISSUE TITLE
The updates from subscriptions page are not updated on goals edit

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2125]
[Precondition]:
Sign up for Common Voice newsletters, goal reminders and progress updates
Create a goal
[STR]:
1.Click to edit your goal ( voice.mozilla.org)
2.On 4th step of goal edit, click the Manage subscription link
3.Click " Remove me from all the subscriptions on this page" button, then save the preferences
4.Go to Goal edit and reload the page 

[Expected result]:
The subscription checkbox should be displayed

<img width="204" alt="Screenshot 2019-07-25 at 15 59 58" src="https://user-images.githubusercontent.com/41474886/61880485-476c2100-aef5-11e9-8c16-e57d98d30421.png">

[Actual result]:
You're currently set to receive emails such as goal reminders, my progress updates and newsletters about Common Voice message is displayed

**Comment by Gregoor** [comment]
I guess we need to change copy here, to not say that "one is subscribed" @mbransn

**Comment by mbransn** [comment]
@Gregoor @rleitan I actually believe the expected result should be that both checkboxes are available on page reload after unsubscribe. The Privacy checkbox is tied to the email sign up, not the goal itself, and the screenshot Roxana shared actually shouldn't exist or even be possible. If one unsubscribes both checkboxes should be present, unchecked, on reload.

**Comment by Gregoor** [comment]
@mbransn As subscriptions are still managed through the mozilla.org email settings page, we couldn't really show the subscription step again here. So imo this view should link there, but with copy indicating whether one is subscribed or not.

**Comment by mbransn** [comment]
Ah I see now, so once you sign up for a Common Voice email you will always have to manage your subscription at mozilla.org, whether currently subscribed or not. I guess then that yes, we'll want to update copy above manage subscriptions button as you mentioned @Gregoor.
