### ISSUE TITLE
Deploying on cloud vm [Can't record a voice]

### ISSUE THREAD

**Issue by amansulaiman** [mozilla/voice-web#2134]
Hello Pals,

I am trying to setup voice-web inside a GCP vm to try collecting voice from and see how s3 works but, everything is working fine locally but in cloud it can't record a voice. It seems ffmpeg depends on host machine microphone to process audio or what is the issue?

**Comment by Gregoor** [comment]
Hey there 👋 

can you give more detalis on what kind of error you're seeing exactly?

**Comment by amansulaiman** [comment]
As per my investigation, the below piece of code in voice-web\web\src\components\pages\contribution\speak\speak.tsx
  `if (
      !this.audio.isMicrophoneSupported() ||
      !this.audio.isAudioRecordingSupported() ||
      isFirefoxFocus()
    ) {
      this.isUnsupportedPlatform = true;
    }`
is working perfectly in local computer with audio hardware enable, but on GCP VM it always return false making the App to be showing unsupported error message when ever you  open speak page.

**Comment by Gregoor** [comment]
Is it maybe running on HTTP (without TLS)? Afaik some browsers don't allow recording for that.

**Comment by amansulaiman** [comment]
Thank you for your suggestion, I will configure the ssl and get back to you

**Comment by amansulaiman** [comment]
IT is now working! @Gregoor Thanks
