### ISSUE TITLE
"could not fetch sentences" error when clicking "Record your voice" button from Listen

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2136]
[Precondition]:
Add to your profile a language that doesn't have clips in Listen section (e.g. dutch)

[STR]:
1.Go to dashboard and select dutch language from Your languages section
2.Set a Listen goal for dutch
3.Go to Dashboard - Goals and click Listen button from Custom Goals section -> he page is redirected to voice.allizom.org/nl/listen
4.Click the red button ("register your voice")

[Expected result]:
The page should be redirected to voice.allizom.org/nl/listen

[Actual result]:
The page is redirected to  voice.allizom.org/nl/listen, but it's blank

Browser Console error:
could not fetch sentences <unavailable> bundle.js:1:104801
    refill https://voice.allizom.org/dist/bundle.js:1
    l https://voice.allizom.org/dist/bundle.js:1

[Note]:
The issue is reproducible only first time this flow is followed for a language
After I reloaded the page I got: Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). error in the browser console, then it's displayed correctly after ~4 minutes

**Comment by Gregoor** [comment]
Can't reproduce atm
