### ISSUE TITLE
Translation issue: kab locale

### ISSUE THREAD

**Issue by mozillakab** [mozilla/voice-web#2141]
Translation on Pontoon:

When trying to translate this string into Kabyle (please see above), I'm getting and this error: The following checks have failed -   Expected a character from range: "a-zA-Z"

String to translate:

This setting controls your leaderboard visibility. When hidden, your progress will be private. This means your image, user name and progress will not appear on the leaderboard. Note that leaderboard refresh takes ~{ $minutes }min to populate changes.

Kab translation:

Aɣewwaṛ-a ad isefrek askan n umḍiq n umsizzwer-ik. Ma tefred-t, asfari-ik ad yeqqim d abaḍni. Aya yemmal-d d akken tugna-ik, isem-ik n useqdac akked usfari-ik u d-ttbanen ara deg umsizzwer. Ẓeṛ d akken ileqman n umsizzwer yettawi azal n  ~{$ minutes} n tisdatin akken ad d-ffɣen ibeddilen.

![2019-08-01 19_32_31-Common Voice · Kabyle (kab)](https://user-images.githubusercontent.com/7033740/62318511-49f1ec00-b49c-11e9-9346-e4f6b4308d5a.jpg)

**Comment by Gregoor** [comment]
It looks like there's a space between $ and minutes. Can you try again
without that?

**Comment by mozillakab** [comment]
I copied the same string as the source. Thanks it worked
