### ISSUE TITLE
Voice Wave Avatar improvements

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#2143]
I see the Voice Wave Avatar feature was added. https://github.com/mozilla/voice-web/issues/1591

I wanted to test it, but didn't know first what to say.

To guide the user better, show some sentences a user might want to say.

Finnaly, after just reading text from the page, i said:

"Hello, i'm David and this is my voice."

---

Also the voice wave looks very thin after reloading the page:

![Screenshot from 2019-08-02 14-45-29](https://user-images.githubusercontent.com/91113/62371098-3eea9a80-b534-11e9-9afa-6644edab15c3.png)

---

The text say: "Other users will be able to hover and listen to your clip."

But i was only able to click on my profile picture to play the audio. No hovering...

Is this feature meant when you don't want to have an avatar picture? Or in addition to that?

Thanks for your work!

**Comment by Gregoor** [comment]
Woops, thanks for catching this. It wasn't meant to be on prod. @mritunjayz did our production flag disappear?
