### ISSUE TITLE
Stats Dashboard fail on Load [500 (Internal Server Error)]

### ISSUE THREAD

**Issue by ibuioli** [mozilla/voice-web#2147]
This is happing one week ago. The dashboard of stats ([https://voice.mozilla.org/es/dashboard/stats](https://voice.mozilla.org/dashboard/stats)) fail to load data in every language, and with every browser (Firefox, Chrome, Vivaldi, Android, etc). Maybe you are working at this, but I can't find an issue reported.

Screeshot:
![stats](https://user-images.githubusercontent.com/7343538/62482028-689cff00-b78a-11e9-8736-1b41df97060d.jpg)

And this is the Error on Web Console:
`api.ts:54 GET https://voice.mozilla.org/api/v1/user_client/goals 500 (Internal Server Error)
api.ts:73 Uncaught (in promise) Error: {"message":""}
    at p.<anonymous> (api.ts:73)
    at Generator.next (<anonymous>)
    at o (index.js:20)`

**Comment by Gregoor** [comment]
Thanks for reporting this, it wasn't on my radar yet! Will post here when I know more.

**Comment by MoHD20** [comment]
I'm having this exact problem too. Here's what appears on the console now 
![image](https://user-images.githubusercontent.com/12420351/62552017-3fa16a80-b86d-11e9-9a95-73fedbaebf61.png)

Here's my username: "None"
I used GitHub to login if that makes any difference

**Comment by Gregoor** [comment]
Thanks! Might've found the (one?) problem, can any of you check if the issue persists?

**Comment by MoHD20** [comment]
Works like a charm Now! Thanks.

**Comment by Gregoor** [comment]
Awesome, thanks for testing! I'm gonna leave this open until @ibuioli verifies that it works for him too :)

**Comment by ibuioli** [comment]
Yes! Its work fine now. Thanks!
