### ISSUE TITLE
Recording is not working on Focus for Android

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voice-web#215]

**Comment by andrenatal** [comment]
When we push the recording circle, we get a popup message saying we need to allow microphone access, and when we hit 'Retry' the page reloads.

**Comment by mikehenrty** [comment]
For now, I've added the "Platform not supported" message for focus on both ios and android

https://github.com/mozilla/voice-web/commit/ef065c507a394ec8bb2178268b038b1af409e12a

**Comment by andrenatal** [comment]
On iOS browsers, the link to the App store should be displayed.

**Comment by kdavis-mozilla** [comment]
This is blocked by mozilla-mobile/focus-android#805 which indicates Focus does support recording.

**Comment by kdavis-mozilla** [comment]
Changing priority as Focus can not record audio mozilla-mobile/focus-android#805

**Comment by MichaelKohler** [comment]
Given that Focus for Android is now in maintenance mode, I'm closing this.
