### ISSUE TITLE
Suggestion : Addining review to the sentences we verified 

### ISSUE THREAD

**Issue by yamamashakaa** [mozilla/voice-web#2156]
I was verifying arabic voices in commonVoice and while listening to some sentences I clicked yes by mistake to a recorded voice while it is definitely no but I had no option to change my choice .I think adding review to the sentences we verified  or allow us to edit our choice is a good idea specially that sometimes you click unconsciously the exact button of the previous sentence

**Comment by MichaelKohler** [comment]
Can you create a post at https://discourse.mozilla.org/c/voice/239 to discuss this? Thanks!

**Comment by yamamashakaa** [comment]
@MichaelKohler  Done
