### ISSUE TITLE
Untranslatable plural strings

### ISSUE THREAD

**Issue by piotrdrag** [mozilla/voice-web#2159]
Strings like `activity-needed-calculation`, `help-reach-hours`, `n-clips`, and `visibility-explainer` can’t be properly translated to many languages, because they lack plural handling.

CC @peiying2

**Comment by peiying2** [comment]
Thanks @piotrdrag for raising the issue.

**Comment by Gregoor** [comment]
Oh, dang. thanks for raising it. Do I need to create new strings or can I just add pluralization to the english string?

**Comment by Pike** [comment]
We're using Fluent, so you can pluralize the strings for Polish. You need to go through the source editor to do so, that's https://bugzilla.mozilla.org/show_bug.cgi?id=1394110.

This should be OK to close.

**Comment by Pike** [comment]
@piotrdrag, do you need help with these?

**Comment by piotrdrag** [comment]
Thanks, but I just used workarounds that should work for now.
