### ISSUE TITLE
Error setting for Portuguese language

### ISSUE THREAD

**Issue by eduaddad** [mozilla/voice-web#2166]
the accent (linguistic variation) of the Portuguese language is not set and 

the language name is PT but should not be Português in the language bar

language variations : [https://en.wikipedia.org/wiki/Portuguese_dialects](url)

**Comment by Gregoor** [comment]
I've updated the string manually, but ultimately that data comes from Pontoon where the translation hasn't been approved yet:
https://pontoon.mozilla.org/pt/common-voice/web/locales/en/messages.ftl/?string=201209

So if it's not approved on the next import, the name will reset.

Wrt accents: @nukeador knows more about that, he'll be back in less than 2 weeks.

**Comment by eduaddad** [comment]
Language variations not available

It is not possible to set up an accent in Brazilian Portuguese) in the profile.

**Comment by nukeador** [comment]
We are currently working on a better way to handle accents, and that's why we haven't added any new ones to languages.

The good thing is that once we implement the new strategy, people will be asked to set their accent and that info will be added to previously recorded clips, so we won't lose any data for not having it now.

**Comment by Kiude** [comment]
Hi ! Is there any scheduling of this settings update? Im pretty sure my European Portuguese records might get downmarked by the overwhelming Brazilian community if not labeled as different ^^

**Comment by nukeador** [comment]
@Gregoor Is there a quick way if we are seeing a significant increase of rejections for Portuguese?

Like in other languages, people shouldn't reject different accents. In Spanish I've been hearing more than 10 different accents and people are accepting all of them.

**Comment by Gregoor** [comment]
We don't have easy plotting capabilities yet, once we have the dashboard, such a task should be simple enough
