### ISSUE TITLE
Cancel button is not clickable when recording a voicewave for the first time

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2177]
[Environment]:
Windows 10, Mac 10.14 - Firefox

[STR]:
1.Login in https://voice.allizom.org/
2.Go to https://voice.allizom.org/en/profile/avatar
3.Click "Create Voicewave" button and record your voice
4.Click "stop recording" button
5.Click "Cancel" button

[Expected result]:
Retry button should be displayed instead of Cancel button - see [designs](https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5d12406cd17e52705b13c595)
Cancel/Retry button should be clickable

[Actual result]:
Cancel button is not clickable
Console error:

<img width="1432" alt="Screenshot 2019-08-22 at 19 01 43" src="https://user-images.githubusercontent.com/41474886/63510229-be8dd880-c4e6-11e9-9695-ba9509b7f4ab.png">

[Note]:
The issue is not reproducible on "Recreate voicewave"

@mritunjayz

**Comment by mritunjayz** [comment]
I missed the case for the first time recording. Thanks @rleitan

**Comment by rleitan** [comment]
Verified as fixed!
