### ISSUE TITLE
Voice avatar recording should not be available on mobile

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2178]
**Env:**
iOS 12.4, Firefox an Safari

**STR:**

1. Login to CV staging
2. Navigate to Settings - Avatar

**Expected:**
Voice avatar recording should not be available, as recording is not working on mobile

**Actual:**
"Recreate Voicewave" button is available, even though recording is not working.

**Comment by Gregoor** [comment]
cc @mritunjayz

**Comment by mritunjayz** [comment]
Yeah, I see. Thanks @viorelaioia

**Comment by mritunjayz** [comment]
@Gregoor @dabinat @viorelaioia voice avatar should not be available on mobile which does not support recording? And what should be the screen then without recording?

**Comment by mritunjayz** [comment]
Actually, I am asking what should be the title then. Should it be same  "Add an avatar to your profile and say “hello!” " ?

**Comment by rleitan** [comment]
> Actually, I am asking what should be the title then. Should it be same "Add an avatar to your profile and say “hello!” " ?

@mbransn

**Comment by mbransn** [comment]
@mritunjayz @Gregoor first -- which mobile browsers aren't supporting recording?

**Comment by mritunjayz** [comment]
I only know about Firefox but I think these are all iOS 12.4, Firefox and Safari as mentioned by @viorelaioia

**Comment by mbransn** [comment]
Got it, forgot that it's not Sept. yet and Apple hasn't released the new update to hopefully rectify this. So it'd be best to just hide the voice avatar divs until they are functional on iOS. Once they're functional we'll reveal them. @Gregoor thoughts?

**Comment by Gregoor** [comment]
All iOS browsers, Safari and Edge don't support recording yet. And both Edge & Safari beta do, so salvation is imminent :)
Agree with megan wrt hiding them.

**Comment by Gregoor** [comment]
fixed in #2182
