### ISSUE TITLE
On the review page, there should be the ability to redo a sentence

### ISSUE THREAD

**Issue by evaryont** [mozilla/voice-web#218]
A couple of times I've noticed others, and myself, messing up the initial few words or trailing off or what have you. I haven't submitted my recordings that include mistakes (closing the tab and re-opening it) but others might have. It'd be great if in the review step of recording samples, there was an option to delete and redo a sentence. Perhaps I can speak more clearly, or carefully reread the sentence and make sure my read is accurate.

*Edit*: This is on the website. (https://voice.mozilla.org/record) Firefox 54.0 on Windows 10.

**Comment by mikehenrty** [comment]
Hi @evaryont , thank you for the report!

I agree this is a big problem, and we have a bug for this here: #204. We'll use that bug to track this issue.
