### ISSUE TITLE
The uploaded voicewave is not played

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2183]
[Environment]:
Windows 10- Firefox

[STR]:
1.Login in https://voice.allizom.org/
2.Go to https://voice.allizom.org/en/profile/avatar
3.Create and upload a Voicewave
4.Click "Play" button after the voicewave is uploaded

[Expected result]:
The voicewave should play

[Actual result]:
The "Stop" button is displayed for ~1 second, then the Play button is displayed 
Console error: NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.

@mritunjayz

**Comment by mritunjayz** [comment]
#2175 it also related to this !

**Comment by mritunjayz** [comment]
should close it !
