### ISSUE TITLE
New Catalan wiki sentences don't appear anywhere

### ISSUE THREAD

**Issue by jaumeortola** [mozilla/voice-web#2184]
The Catalan sentences extracted from Wikipedia and added 10 days ago (#2164) never appear, either in recording or in validation. Could you check it and see what's happening, @Gregoor?

Is this related to #2128?

**Comment by Gregoor** [comment]
Oh it looks like we didn't have a deploy to production last week. Will do that this week (probably tomorrow). Thanks for the notice!

**Comment by ftyers** [comment]
@jaumeortola is this still a problem?

**Comment by jaumeortola** [comment]
No. It is fixed.
