### ISSUE TITLE
Extract data based on votes from the SQL database

### ISSUE THREAD

**Issue by maureendss** [mozilla/voice-web#2185]
Is there an available open-source script to extract the collected data and turn them into the same structure as the final datasets in eg https://voice.mozilla.org/en/datasets, taking into account the votes (filtering out those with downvotes), and creating the related tsv files from there?
Thanks

**Comment by Gregoor** [comment]
The code that does the collecting and bundling is indeed available:
https://github.com/Common-Voice/common-voice-bundler
https://github.com/mozilla/CorporaCreator

Unfortunately we currently don't (and can't) offer direct access to the database and S3 as they contain privacy sensitive data. So any filtering you want to do, you'd need to do based on the released datasets.
On the upside, each language's archive should contain a file pointing to the valid clips, you could use that to extract what you need.

**Comment by maureendss** [comment]
That's great, I was looking for the common-voice-bundler one. Thanks!
