### ISSUE TITLE
Investigate iOS wrapper app for mobile website

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#22]
Is it possible for us to publish a "wrapper" app on the app store, and then change the content later? If so, let's build it!

**Comment by kdavis-mozilla** [comment]
Just looked this up and we're walking a fine line[[1](https://developer.apple.com/app-store/review/guidelines/#minimum-functionality)]:

<img width="735" alt="app" src="https://cloud.githubusercontent.com/assets/12054740/25983604/1eaedd9a-36e6-11e7-8de8-f20dab86f5ad.png">

**Comment by mikehenrty** [comment]
This is done.
