### ISSUE TITLE
Reword recording directions.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#220]
Currently, the text reads "Please read the above sentence and tap to record.", it would be more accurate to say: "Please tap to record and read the above sentence aloud."

**Comment by kdavis-mozilla** [comment]
I'm going to change this wording a bit to be even more clear. Instead of

> Please tap to record and read the above sentence aloud.

I'm going to use

> Please tap to record then read the above sentence aloud.

Just so we don't loose the sentence starts.

**Comment by mbebenita** [comment]
👍
