### ISSUE TITLE
Voice avatar plays every time I hover over the 3-dots user menu 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2203]
**Env:**
Mac 12.4, Firefox, Safari

**STR:**
1. Login to Common Voice staging
2. Hover over the 3-dots user menu in order to expand the menu options

**Expected:**
Menu options are displayed, voice avatar doesn't start playing. In plays only when doing hover over picture avatar or username

**Actual:**
Menu options are displayed, voice avatar starts playing.

**Note:**
The avatar plays every time the users wants to navigate to a page via the user menu, as it expands on hover action.

CC: @mbransn , @Gregoor, @mritunjayz

**Comment by mritunjayz** [comment]
Now, I have done it for both username and avatar only.

**Comment by mritunjayz** [comment]
@Gregoor should close it
