### ISSUE TITLE
Wrong css styles for RTL languages

### ISSUE THREAD

**Issue by MohsenEbrahimi86** [mozilla/voice-web#2205]
Some nodes in pages have styles that didn't true in RTL languages.
Example number 1:
In page:
[https://voice.mozilla.org/fa/faq#using-common-voice](url)
with node:
.faq-hero .question-block:nth-child(2n) .faq-a
has style:
left:calc(-100% - 6rem)

![image](https://user-images.githubusercontent.com/998540/64378123-3c062c80-d041-11e9-8c87-0efe16805640.png)

but it should be:
left:calc(+100% + 6rem)
![image](https://user-images.githubusercontent.com/998540/64470266-ae683100-d155-11e9-9979-a7ee67fd5715.png)

Example number 2:
In page:
[https://voice.mozilla.org/fa/dashboard/fa/stats](url)
with node:
.language-select
doesn't have:
text-align:center
![image](https://user-images.githubusercontent.com/998540/64378148-4b857580-d041-11e9-978c-1ae1236b02e8.png)
but it should be something similar this:
![image](https://user-images.githubusercontent.com/998540/64470269-c50e8800-d155-11e9-9dea-95ad7fdef0ed.png)

**Comment by rileyjshaw** [comment]
This should be fixed by https://github.com/mozilla/voice-web/pull/2510.
