### ISSUE TITLE
Allow arbitrary goal amounts

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#2206]
Creating a custom goal requires you to select from a fixed list of recording/validating amounts. I have found these amounts to be too low to be useful for me. For instance, I always hit the highest weekly goal on the first day of the week.

There should be an option to allow me to type in my own daily/weekly goal amount.

**Comment by MichaelKohler** [comment]
Would you mind starting a discussion over at Discourse to see what the best solution for this is?
