### ISSUE TITLE
Figure out what the back button should do when reviewing (re-recording) sentences.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#221]
If the user clicks the X button to re-record a sentence then the red back button should probably take them back to the submit page, not the previous sentence.

**Comment by mikehenrty** [comment]
I see two other possible options:
1. don't show back button when re-recording
1. don't show the back button at all now that we allow re-recording

**Comment by mbebenita** [comment]
I think I'd vote for 1.

**Comment by mikehenrty** [comment]
also, the numbers (3 of 3) are also confusing

**Comment by mikehenrty** [comment]
also we could re-record in place

**Comment by mikehenrty** [comment]
let's investigate re-recording in place, and do it if not too risky

if not, on re-record screen hide back button, and clip count

**Comment by mikehenrty** [comment]
it looks like @kdavis-mozilla was right, making this screen be able to re-record in place requires significant changes to the listen-box, so we will go with the second alternative: hiding back button and clip count

**Comment by mikehenrty** [comment]
fixed in https://github.com/mozilla/voice-web/commit/bd1713282612c25b51288662c1f7de6aac143cb8
