### ISSUE TITLE
Top contributors names are cut off in the leaderboard

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2213]
**Env:**
iPad Pro (11-inch), iOS 12.4, Firefox, Safari
iPhone 7, iOS12.4, Firefox, Safari

**Description:**
Names are not displayed on certain devices, as they don't fit. I couldn't find designs with how the table should look on mobile / tablet view, but I suppose we want people's names displayed, in order to be able to identify them. @mbransn , can you please confirm this? Thanks!

![photo_2019-09-12_15-05-13](https://user-images.githubusercontent.com/5293100/64782951-2fb52e80-d56f-11e9-89f0-0609b3d9dd18.jpg)
![photo_2019-09-12_15-07-05](https://user-images.githubusercontent.com/5293100/64782952-2fb52e80-d56f-11e9-80fd-ad668976127d.jpg)

**Comment by mritunjayz** [comment]
@Gregoor should close it
