### ISSUE TITLE
Suggest a fixed sentence

### ISSUE THREAD

**Issue by Mte90** [mozilla/voice-web#2229]
Our experience show that have a wrong sentence or badly reviewed create issues with the project brand.
Include a way to suggest a new sentence can be useful to involve more the contributors but also improve the quality of the sentences.

**Comment by reinhart1010** [comment]
We already have https://common-voice.github.io/sentence-collector/
Probably a better way to solve this is to provide link to above site in the main Common Voice website.

**Comment by Mte90** [comment]
The idea was to:

* report the wrong sentence
* suggest a new one

As it is now this is a task very long that require another tool and a lot of steps.
