### ISSUE TITLE
Horizontal Scrolling on main page should not be possible

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/voice-web#2239]
On the main page (voice.mozilla.org) it's currently possible to scroll horizontally without actually having more content.

<img width="774" alt="Screenshot 2019-10-02 at 21 04 44" src="https://user-images.githubusercontent.com/330324/66073946-aaa6af00-e547-11e9-92d6-ea1c60801c9a.png">

**Comment by aditya-hari** [comment]
I would like to work on this issue. Which file should I be looking at to see how to fix this?

**Comment by TheGameFreak720** [comment]
I would love to contribute also to this issue

**Comment by saranshbarua** [comment]
I found a quick fix for this, will submit a PR soon.
