### ISSUE TITLE
Common Voice Not supported on Focus for Android

### ISSUE THREAD

**Issue by GeekyShiva** [mozilla/voice-web#224]
I was using firefox focus on android 6.0 Infocus device and common voice is not supported here 

it says to download firefox or chorme to use it .
[screenshot](https://drive.google.com/file/d/0B9TkcFiJdIn8cjBwaUJvaFNadmM/view?usp=sharing)

**Comment by kdavis-mozilla** [comment]
Yes this is a known issue.

To streamline the browsing experience and boil it down to it's most useful core Focus currently doesn't allow for recording audio. So, if one wants to contribute audio to the project on Android, one has to use Firefox or Chrome.

I'm sorry for the inconvenience.

**Comment by kdavis-mozilla** [comment]
Closing as this issue duplicates issue #215
