### ISSUE TITLE
[iOS] Long sentences don't fit the green container on iPhone SE

### ISSUE THREAD

**Issue by paulsilaghi** [mozilla/voice-web#225]
device: iPhone SE
os: iOS 10.0.2
Doesn't reproduce on iPhone 6S/iOS 10.3.3.

![long sentences](https://user-images.githubusercontent.com/29535384/27482826-a08a8ad8-582b-11e7-84e8-c8d90149772e.PNG)

**Comment by kdavis-mozilla** [comment]
Duplicate of issue #74?

**Comment by paulsilaghi** [comment]
I think #74 is about recording screen, here we are on the "listen" screen

**Comment by mikehenrty** [comment]
ideally, the green box expands vertically, so let's investigate this

backup, just clip the text and descrease line-height

**Comment by paulsilaghi** [comment]
As a result of the fix:
![image1](https://user-images.githubusercontent.com/29535384/27735390-ffd6b364-5da7-11e7-9e58-7f0d326b9f87.PNG)
![image2](https://user-images.githubusercontent.com/29535384/27735392-035108a0-5da8-11e7-833d-7fb76c05ce59.PNG)

**Comment by mikehenrty** [comment]
We've cleared out all the long sentences from being able to be spoken, so let's call this fixed.
