### ISSUE TITLE
add some events to Google Analytics

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#228]
* recording
* submitting recordings
* listening
* profile filing out

**Comment by mbebenita** [comment]
This is how we implemented this in another app.

https://github.com/wasdk/WasmFiddle/blob/master/src/State.tsx#L8

https://github.com/wasdk/WasmFiddle/blob/297fb3484c08f569063d2490cd6d5a35f20fa123/index.html#L30
