### ISSUE TITLE
Challenge sign up pop up

### ISSUE THREAD

**Issue by georai** [mozilla/voice-web#2281]
1. Remove the icon.
2. Not the right grey.

https://www.dropbox.com/s/u7ndpofoko31vth/Screenshot%202019-11-08%2016.14.15.png?dl=0
https://www.dropbox.com/s/qeod5n8iwv4ot85/Screenshot%202019-11-08%2016.18.50.png?dl=0

@mbransn @rileyjshaw

**Comment by mbransn** [comment]
@rileyjshaw this one is still P0, grey is too light for accessibility and icon is confusing / not needed.

**Comment by phirework** [comment]
This should be fixed on Staging, can one of you verify and close? https://voice.allizom.org/en?challenge=pilot&team=mozilla

**Comment by mbransn** [comment]
Verified! Thanks :)
