### ISSUE TITLE
Implement challenge invite modal frontend

### ISSUE THREAD

**Issue by georai** [mozilla/voice-web#2283]
https://www.dropbox.com/s/qvtpzmnv5hhsl57/Screenshot%202019-11-08%2016.29.35.png?dl=0

1. The close icon needs to be grey.
2. Something with the hand, do Ineed to reexport?
3. Spacing between speak and listen  is more than in design.

@mbransn @rileyjshaw

**Comment by catherine917** [comment]
@rileyjshaw I can't assign this task to myself. Could you help assign it to me? Now I am trying to fix it.

**Comment by rileyjshaw** [comment]
@catherine917 assigned.

**Comment by rileyjshaw** [comment]
@georai this should be fixed on staging. Can you confirm?

**Comment by mbransn** [comment]
@rileyjshaw re-triggering this onboarding modal is tough on my end. Can you send through a screenshot?

**Comment by rileyjshaw** [comment]
@mbransn there's currently a bug preventing the onboarding modal from appearing: https://github.com/mozilla/voice-web/issues/2346

Once that issue is closed, it should be visible at https://voice.allizom.org/en/dashboard/challenge?first=1

**Comment by mbransn** [comment]
Confirmed fixed!
