### ISSUE TITLE
Invite pop-up

### ISSUE THREAD

**Issue by georai** [mozilla/voice-web#2284]
https://www.dropbox.com/s/yvj0m2lmfdf0g9t/Screenshot%202019-11-08%2016.33.45.png?dl=0

1. Close icon grey.
2. The style of the copy link is different.
3. On hover we designed before with grey fill.

@mbransn @rileyjshaw

**Comment by catherine917** [comment]
Hands up

**Comment by catherine917** [comment]
PR https://github.com/mozilla/voice-web/pull/2316 fixed this issue

**Comment by mbransn** [comment]
Confirmed fixed!
