### ISSUE TITLE
Listen section doesn't work correctly

### ISSUE THREAD

**Issue by Sav22999** [mozilla/voice-web#2285]
The listen section doesn't work correctly. It shows just few sentences and then it shows "We don't have anything to validate in this language, help us fill the queue.".
But, actually, there are sentences to validate ... it happens also to new volunteers.
It happened in the Italian language (I don't know in other languages).

**Comment by phirework** [comment]
This doesn't seem to be an issue any more so I'm closing for now. Feel free to reopen or create a new issue if something else pops up.
