### ISSUE TITLE
[mobile]: The link icon is misaligned on "Copy link" button

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2292]
[Environment]:
iOS 13.1 - Firefox

[Precondition]:
Join a team for Voice challenge

[STR]:
1.Go to https://voice.allizom.org/en/dashboard/challenge
2.Tap the "Invite+" buttton

[Expected result]:
Invite colleagues and friends prompt should be correctly displayed

[Actual result]:
The link icon is misaligned on "Copy link" button
![75380093_463074454564091_7990369282171076608_n](https://user-images.githubusercontent.com/41474886/68662708-0f412a80-0546-11ea-88fb-aca10315379f.jpg)

**Comment by adsingh14** [comment]
I'm working on it!

**Comment by adsingh14** [comment]
@rleitan Can you please redirect us to the exact page ?
I'm not able to find it via web app.

**Comment by rleitan** [comment]
@adsingh14 Go to https://voice.allizom.org/en?challenge=pilot&team=mozilla, Join the Mozilla team with a valid email, then navigate to https://voice.allizom.org/en/dashboard/challenge and click the "Invite+" buttton

**Comment by adsingh14** [comment]
@rleitan Sign-in via e-mail isn't working ! It asks me to fill the e-mail again !

**Comment by rleitan** [comment]
@adsingh14 do you have an account on voice.allizom.org with that email? you should try to login via the website, not the web app

**Comment by adsingh14** [comment]
@rleitan I've made an account via 'Gmail and Github' login option. None of them are working.

**Comment by phirework** [comment]
@adsingh14 Can you post the exact steps you're taking to get the error? I just tried using @rleitan's link using an existing account, a brand new email that I'd never registered before, and connected to my Github, and all of them worked. After login I'm prompted to create a profile (if new account) and then going to dashboard again I see the page that says the challenge has not started yet.

**Comment by adsingh14** [comment]
On first run, it took me to the profile page successfully. But won't take me to the second link.

**Comment by adsingh14** [comment]
@phirework First link take me to the profile page successfully(after google login). But the second link redirect me to the login page.

**Comment by adsingh14** [comment]
Where's the invite+ button ?
@rleitan

**Comment by rleitan** [comment]
https://drive.google.com/file/d/18aQXaxAm8HyFSZRskeCgNs8s4egPBcFY/view , please note that the issue is reproducible on mobile - iOS

**Comment by adsingh14** [comment]
@rleitan That's visible on desktop version only. Anyways, I have figured out the fix but don't know how to run it on local server! 

I got a problem with 'docker'.

**Comment by adsingh14** [comment]
@rleitan  **docker-compose up** is stuck on 'Building web'. Any lead ?

**Comment by phirework** [comment]
@adsingh14 Unfortunately we don't have the tech resources on our team to support troubleshooting local dev environments. The docker setup has some bugs which is a known issue and it's on our roadmap. I've gotten stuck on the 'building web' piece before, and usually it just took a little longer than usual but would still eventually build. Try increasing the timeout in your docker config (usually it defaults to 60s).

**Comment by adsingh14** [comment]
@phirework  I've not installed standalone MySQL. Is it okay to proceed with XAMPP ?

**Comment by phirework** [comment]
@rleitan @adsingh14 We've been doing a lot of bugfixing and QA-ing today for the partner challenge and it looks like it's possible this bug got picked up in one of those changes, can you see if this is still reproducible?

**Comment by rleitan** [comment]
I cannot reproduce the issue anymore. Closing the bug!

**Comment by adsingh14** [comment]
@phirework I've build the web component successfully, but unable to launch it!
