### ISSUE TITLE
[mobile]:Icon missing from Build profile section

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2293]
[Environment]:
iOS 13.1 - Firefox

[STR]:
1.Sign up for Voice challenge

[Expected result]:
The page should be redirected to Build profile page.
Build profile section should have an icon like on desktop
![2019-11-12_12h32_11](https://user-images.githubusercontent.com/41474886/68664101-74961b00-0548-11ea-958e-727b32a8d532.png)

[Actual result]:

![75279325_535822120312741_397674844457533440_n](https://user-images.githubusercontent.com/41474886/68664123-8081dd00-0548-11ea-8a0a-5bd23a00d371.jpg)

**Comment by phirework** [comment]
This should be fixed on Staging, can you confirm and close if passed?

**Comment by rleitan** [comment]
Verified as fixed!
