### ISSUE TITLE
Should not be able to join multiple teams for Voice Challenge

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2294]
[STR]:
1.Go to https://voice.allizom.org/en?challenge=pilot&team=ibm and click to join the Voice Challenge for a team ( e.g. IMB)
2.Login with a valid email
3.Go to https://voice.allizom.org/en?challenge=pilot&team=sap and click to join the Voice Challenge for another team with the same email (e.g. SAP)
4.Login with the same email from step 2

[Expected result]:
Should be displayed a message that the entered email is already used in Voice Challenge for another team
@mbransn what do you think?

[Actual result]:
Login is successful

**Comment by mbransn** [comment]
Hmm, this is a good flag. @rileyjshaw @phirework I'd think this would display an error after authentication returns the person back to Common Voice, yes? Because we'd want logic that doesn't enable people to be part of two teams. Thoughts?

**Comment by phirework** [comment]
There is already logic that prevents a user from enrolling with a different team. In the interest of time and there not being a UI mock for error states, going to suggest that if an already-enrolled user tries to use the invite link again, they just get routed to the challenge dashboard.

**Comment by mbransn** [comment]
Sounds good on this end. Future state could be error message handling, though for the pilot I agree with the dashboard touting approach. Thanks!
