### ISSUE TITLE
Brazilian Portuguese and Dialects of other languages

### ISSUE THREAD

**Issue by gbaptista** [mozilla/voice-web#2301]
Hi folks!

Common Voice is an awesome project. Thank you very much for that!

I have noticed the recent change: _Link "pt-BR" localization to "pt" #1962_

I believe that this could lead to a lot of adverse side effects. My main concerns:

- Deprive countries of using this technology
- Loss of new contributors
- Loss of the contributions made so far

I'm also concerned if this is something that is happening to other languages.

Those concerns are a personal point of view. I can not speak for all Brazillian and would like to hear other opinions.

### Deprive countries of using this technology
Brazilian Portuguese and Portuguese from Portugal are profoundly different. I am Brazilian and talked to other people in Brazil about it. If something is translated to Portuguese from Portugal or speak in Portuguese from Portugal, it's not translated to Brazilian Portuguese.

I would love, for example, to build something with open source projects like [Mycroft](https://github.com/MycroftAI/mycroft-core) or [Leon](https://github.com/leon-ai/leon) in combination with [Arduino](https://github.com/arduino/Arduino) for my family. I could automate something for my mon's house, but she doesn't speak English and would not use something in Portuguese from Portugal because this is hard to understand and will never feel like something built for Brazilians. I have developed some experiments and toys with Arduino with my 10-year-old son, and the same applies here; Portuguese from Portugal doesn't make sense for him.

They feel that they can't have access to this kind of technology; it's something just for other countries and sees the Portuguese from Portugal as a bad workaround that not worth using it.

### Loss of new contributors
If someone from Brazil wants to contribute to the project and only see PT, it does not makes sense to contribute. It's not something that we can use, because it's not our language and forecasting, we would disturb the Portuguese from Portugal. A lot of "correct" spellings will be marked as wrong and vice versa. And honestly, if we do not see pt-br, it's better to accept that our language is not supported, and it's better to use the English version of something.

I make a personal experiment talking with some Brazillian friends about contributing to this project, and all of them have denied because it does not make sense to contribute to Portuguese from Portugal. To avoid some bias, I have tried some times advocate saying: "well, to the computer it's the same thing, we have different accents in Rio de Janeiro, Porto Alegre, São Paulo, Recife... Portuguese from Portugal it's just another accent for the computer..."; They just don't buy it.  A Brazillian friend of mine that have traveled to Portugal says that he spends two days to start to have some understanding of signs and the spelling.

It's sad to lose the potential contributions of an entire country.

### Loss of the contributions made so far
We have a lot of contributions. If people from Portugal start correcting the Brazillians spelling, a lot of things will be flagged as wrong. If Brazilians start to check the Portugueses spelling, the same applies here. We will end up with a "kind of global Portuguese" that is not suitable for any country at the end of the day.

If there is some technical issue, to avoid losing the contributions, maybe it's better to shut down temporarily the Portuguese page until we can find another option than unify the languages.

### Finally

There is something that I could to help you folks with that? Do my arguments make sense? There is some technical context for this change that am I missing?

I would love to discuss this further to get a better solution for the community.

**Comment by gbaptista** [comment]
Doubts and concerns were addressed in the Discourse thread: https://discourse.mozilla.org/t/concerns-about-brazilian-portuguese-and-dialects-of-other-languages/48767/2

Thanks!

**Comment by datasintese** [comment]
**This was a bad decision by the mozilla team.**

![image](https://user-images.githubusercontent.com/49621297/133657472-52eb9951-753d-472f-8780-9d94378282ca.png)
