### ISSUE TITLE
Intermittent issue: An error occurred when opening https://voice.allizom.org/en/dashboard

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2302]
[STR]:
1.Open https://voice.allizom.org/en?challenge=pilot&team=mozilla
2.Join the Mozilla team voice challenge
3.Go to dashboard from https://voice.allizom.org/en?challenge=pilot&first=1&achievement=1

[Expected result]:
Dashboard page should be correctly displayed

[Actual result]:
"An error occurred. Sorry!" message is displayed
https://drive.google.com/file/d/10QC-K1ZtoTGyk4LFBRiNsAYkgVS6tpxk/view?usp=sharing

@rileyjshaw

**Comment by phirework** [comment]
This is fixed on staging, as far as we can tell. Can you verify and close if fixed?

**Comment by rleitan** [comment]
I can reproduce it

**Comment by rileyjshaw** [comment]
I just pushed some further fixes to this part of the dashboard. Can you still reproduce @rleitan?

**Comment by rleitan** [comment]
I cannot reproduce it anymore! Closing the bug
