### ISSUE TITLE
"My points" section is displayed on Challenge page 

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2304]
[Precondition]:
Join the Voice challenge

[STR]:
1.Go to https://voice.allizom.org/en/dashboard/challenge page

[Expected result]:
Challenge page (pre-challenge) should look as per designs

[Actual result]:
"My points" section is displayed on Challenge page 
![2019-11-13_16h08_56](https://user-images.githubusercontent.com/41474886/68771040-ea28e680-062f-11ea-853b-a4a85e15e8ee.png)

**Comment by phirework** [comment]
Fixed on stage.

**Comment by rleitan** [comment]
Verified as fixed!
