### ISSUE TITLE
Invite link is not correct

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2305]
[STR]:
1.Join a team for the Voice challenge (e.g. mozilla)
2.Go to Dashboard and click "Invite+" button
3.Click "Copy link" button
4.Verify the copied link

[Expected result]:
The copied link should be https://voice.mozilla.org/?challenge=pilot&team="team from step1"&invite=#####

[Actual result]:
The copied link is https://voice.mozilla.org/?challenge=pilot&team=SAP&invite=##### , no matter which team joined in step 1

**Comment by rileyjshaw** [comment]
Still in progress at https://github.com/mozilla/voice-web/pull/2308/

**Comment by rileyjshaw** [comment]
Fixed on staging @rleitan

**Comment by rleitan** [comment]
Verified as fixed!
