### ISSUE TITLE
Challenge page is available for users who didn't sign up for the challenge via the url

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2306]
**STR:** 
1. Login to Common Voice staging with an account not signed up for the challenge
2. Navigate to "/dashboard/challenge" page

**Expected:**
User is redirected to "/dashboard/stats/" page, as he/she is not part of any team in the challenge

**Actual:**
Challenge page is displayed, Invite button is available.

![image](https://user-images.githubusercontent.com/5293100/68774157-55c18280-0635-11ea-9863-91e651cfc811.png)

**Comment by phirework** [comment]
This is up on stage. https://voice.allizom.org/en/dashboard/challenge

**Comment by viorelaioia** [comment]
@phirework , this is still happening for me, Challenge page is displayed for an account who is not signed up to the challenge

**Comment by viorelaioia** [comment]
I confirm this is fixed.
