### ISSUE TITLE
Possible to get multiple invite_send achievements

### ISSUE THREAD

**Issue by rileyjshaw** [mozilla/voice-web#2311]

**Comment by rileyjshaw** [comment]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/1840854/68803587-0cba0000-062e-11ea-8bd8-e3a152954021.png">

Uh oh 😅

**Comment by rileyjshaw** [comment]
@can-007 are you able to look into this?

**Comment by can-007** [comment]
Is it reproducible?
I think this phenomenon is possible if the challenge star_date had been changed every time invite_send bonus has been earned.

**Comment by rileyjshaw** [comment]
Yep it's reproducible. @phirework noticed the same thing.

**Comment by can-007** [comment]
Well, I have trouble reproducing it on my dev environment and check the code logic again, I will try different ways to reproduce it and also try to reproduce it on the staging server.

If you have time, can you provide some more information:
@phirework , can you describe the exact step to reproduce it?
@rileyjshaw , can you post a image show the challenges' start_date?

**Comment by can-007** [comment]
This issue arises because the DB is gating all the date related checks, and the invite_send SQL in backend doesn't consider the time before or after the challenge, simply allowing to earn the bonus.
There should be stricter checks.

**Comment by mbransn** [comment]
@phirework @rileyjshaw is this indeed `P0`? Unsure of the full issue due to issue description.

**Comment by phirework** [comment]
I would say no, the issue is that we're potentially giving users too many points, but that's something that can be adjusted and cleaned up after the fact.

**Comment by mbransn** [comment]
Got it, downgraded.
