### ISSUE TITLE
TypeError: "he.b[u.enrollment.team] is undefined

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2318]
[Precondition]:
Join a team for Voice Challenge, then navigate to https://voice.allizom.org/en/dashboard/challenge?date=2019-11-20

[STR]:
1.Open a new tab and join the Voice challenge for a different team with a different account
2.Go to the tab from precondition and reload it

[Expected result]:
Dashboard - challenge page should be displayed for the account used to login in step 1

[Actual result]:
"An error occurred. Sorry!" message is displayed

![2019-11-14_12h05_06](https://user-images.githubusercontent.com/41474886/68848065-54956180-06d8-11ea-9d6e-dfecf361877d.png)

[Note]:
It works fine on second reload

**Comment by phirework** [comment]
I'm unable to reproduce this locally - any luck @rileyjshaw?

**Comment by phirework** [comment]
On staging I'm finding that if I: 

* Sign into one account, and go to the dashboard
* Try to enroll a second account in a different tab in the same browser

As soon as I hit "login" on the second account (or click the email verification link or whatever), the first tab reloads and sends me to the auth screen. I imagine this is a security precaution and the desired behaviour. So I also cannot reproduce the steps described on Staging.

**Comment by rleitan** [comment]
> On staging I'm finding that if I:
> 
> * Sign into one account, and go to the dashboard
> * Try to enroll a second account in a different tab in the same browser
> 
> As soon as I hit "login" on the second account (or click the email verification link or whatever), the first tab reloads and sends me to the auth screen. I imagine this is a security precaution and the desired behaviour. So I also cannot reproduce the steps described on Staging.

I confirm it's happening as in the above comment!
