### ISSUE TITLE
clear staging s3 bucket

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#232]
there is some weird data

**Comment by kdavis-mozilla** [comment]
@gozer Is this possible to do? We don't have the credentials.

**Comment by gozer** [comment]
Sure, you could do it yourself via ssh and all that fun stuff, or I can do it in 2 minutes

**Comment by gozer** [comment]
Deletion of all content in the staging bucket in progress...

**Comment by gozer** [comment]
Done, it's empty now

**Comment by kdavis-mozilla** [comment]
@gozer Thanks!
