### ISSUE TITLE
"My points" section never gets updates

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2321]
**STR:**
1. Sign up for the challenge
2. Navigate to Listen page and validate one sentence

**Expected:**
User should have 100 points shown in "My points" section (50 for sign up and another 50 for first contribution)

**Actual:**
"My points" section shows 0 points. I waited for more than 2 hours and logged out and logged back in and it still shows 0 points.
Email I used: parsmoz1@gmail.com

**Comment by phirework** [comment]
This should be fixed now, same issue as #2322.

**Comment by viorelaioia** [comment]
I confirm this is fixed
