### ISSUE TITLE
Challenge dashboard- individual contributions are not updated

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2322]
[Precondition]:
Join the Voice Challenge (the voice challenge started e.g. go to https://voice.allizom.org/en/dashboard/challenge?date=2019-11-20)

[STR]:
1.Go to https://voice.allizom.org/en/dashboard/challenge?date=2019-11-20 
2.Go to Current challenge -  individual section and click the Speak or Listen button
3.Contribute for Speak or Listen with 1 clip and upload it
4.Go to .Go to https://voice.allizom.org/en/dashboard/challenge?date=2019-11-20 

[Expected result]:
Invididual contribution should be displayed

[Actual result]:
Individual controbution is not updated
![2019-11-14_15h00_31](https://user-images.githubusercontent.com/41474886/68859241-8239d500-06ef-11ea-8732-52b31cd2efba.png)

**Comment by phirework** [comment]
As discussed in in standup, the issue here was that the database logic ignored all activity outside of the start/end dates of the challenge. We've changed the challenge starting date on **staging only** to be November 10th, so all of the activity is now be showing up. Can you confirm that you're seeing your own contributions?

**Comment by mbransn** [comment]
Realizing that this is related to #2337 and #2336 which I was testing on production and verified there that points are not being reflected after contribution.

I've just tested again on staging and have no points reflecting 5 recorded clips contribution, will check back in 20 mins. Current state on stage:

<img width="1419" alt="Screen Shot 2019-11-18 at 11 24 33 AM" src="https://user-images.githubusercontent.com/18686986/69083082-41470680-09f6-11ea-80b7-f9eb1b421614.png">

**Comment by mbransn** [comment]
@rileyjshaw FYO for @can-007 @catherine917 to review #2337 against this issue as well. Are they all connected? 

@phirework from what I’m seeing we should remove the resolves tag?

**Comment by rileyjshaw** [comment]
@can-007 @catherine917 as discussed in our meeting, please look into this.

**Comment by can-007** [comment]
For now, after I checked in staging database, I think this is not an point-calculation error.
@mbransn , you mentioned "_immediately_", so probably its about the cache.
Just want to clarify that:
_everything that is showing up on the challenge board is cached, "My Points", "Individual progress", all the "Leaderboard" etc._
Tell me if some of them shouldn't be cached, or should have different caching delays.

As I checked in the **staging** database, the individual points are added up correctly:
`55 points = 5 clips + 1 bonus (first_contribution) * 10;`
As enrolled at `11-18`, challenge starts at `11-10`, thus no sign_up_first_three_days bonus.
I checked at  `2019-11-19 04:36:09` which is the time on database server.

I will post more if I found anything contradictory to my previous findings.

**Comment by mbransn** [comment]
@can-007 I believe we should cache only the leaderboard as we do for the original `Stats` dashboard. That would mean removing the cache, and the delay, for `My points` and `Individual progress`  The cache would stay in effect for all leaderboards. 

@rileyjshaw @phirework of course the final decision lies with you re: infra load. If you’re comfortable though I’d like to move forward with the above.

**Comment by mbransn** [comment]
From mtg w/ @rileyjshaw @phirework -- first look into changing cache timer post-launch to ensure infra stability. There are also ways to optimize the build of points to reduce server load, this is a more expensive engineering effort and will be explored once pilot launch is live and stable.

@phirework can you confirm which cache edits land to prod from latest PRs and we'll log next steps separately?

**Comment by mbransn** [comment]
@LRSaunders4 can you verify on your end that points are updating?

**Comment by rileyjshaw** [comment]
I believe this was fixed in https://github.com/mozilla/voice-web/commit/8776c09aa799b85b65b969f8b70b5f8322255489. Awaiting confirmation.

**Comment by mbransn** [comment]
Confirmed fixed!
