### ISSUE TITLE
"Team Progress" and "Top Contributors" dashboards are empty, even though people signed up and contributed to the challenge

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2324]
I used several test accounts to sign up for the challenge in the SAP team
I also contributed with some of those accounts.
Though, the "SAP Team Progress" and "Overall Challenge Top Contributors" dashboards are still empty. Users who accepted the SAP team invite to the challenge should be displayed here.

![Screenshot_2019-11-14 Common Voice by Mozilla](https://user-images.githubusercontent.com/5293100/68860388-1a38be00-06f2-11ea-83d7-dbfb59f7cd38.png)

**Comment by can-007** [comment]
There are several minutes delay, to reduce the server load.
For now, it is 20 minutes.
Maybe it is too long, but an acceptable delay should be discussed.

**Comment by viorelaioia** [comment]
@can-007 , I joined the team with different accounts hours ago and the dashboards are still empty.

**Comment by phirework** [comment]
The issue here was that the database logic ignored all activity outside of the start/end dates of the challenge. We've changed the challenge starting date on **staging only** to be November 10th, so all of the activity is now be showing up.

**Comment by viorelaioia** [comment]
I confirm that both dashboards are populated now.
