### ISSUE TITLE
Team sign up percentage is updated only for the last user who joined the team challenge

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2325]
**STR:**
1. Login to CV with an account who signed up for the challenge in a team (e.g: IBM)
2. Navigate to [Challenge](https://voice.allizom.org/en/dashboard/challenge?date=2019-11-20) page 
3. Copy the Invite link
4. In a private tab, paste the Invite link and sign up with a different account
5. Navigate to [Challenges](https://voice.allizom.org/en/dashboard/challenge?date=2019-11-20) and note the percentage of team invites in the Current Challenge section
6. Switch to the account from step 1, logout and login 
7. Navigate to [Challenge](https://voice.allizom.org/en/dashboard/challenge?date=2019-11-20) page 

**Expected:**
Team invites percentage matches is the same for both accounts

**Actual:**
Team invites percentage is different for the 2 accounts, the number increased only for the invitee (last person who joined the challenge)

![image](https://user-images.githubusercontent.com/5293100/68862161-9f71a200-06f5-11ea-933c-584ca9e84241.png)

![image](https://user-images.githubusercontent.com/5293100/68862198-ad272780-06f5-11ea-9c78-02355adffaa3.png)

**Comment by phirework** [comment]
Was the team percentage still un-updated after 20 minutes for the first account? We do have logic in the code that calculates updated values for the user's own actions, so that new users will see their effect on the challenge right away, but all other users will need to wait for the 20 minute db delay to get updated stats.

**Comment by rileyjshaw** [comment]
I just tried to reproduce, and noticed the same thing. However, after about 20 minutes (approximate, so it could longer), a hard refresh of the page resulted in equal percentages for everyone.

@viorelaioia, are you able to check the accounts again and see if the team percentages are now equal?

**Comment by viorelaioia** [comment]
I confirm the percentage got updated after a page refresh, for both test account. Closing the issue
