### ISSUE TITLE
Overall Challenge Top Team table is empty

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2327]
[Precondition]:
Each team has team members in Voice challenge
Each team has team members who contribute

[STR]:
1.Login with a valid account - join the voice challenge
2.Go to https://voice.allizom.org/en/dashboard/challenge?date=2019-11-20
3.Verify the Overall Challenge Top Team table

[Expected result]:
The Overall Challenge Top Team table should have info and the ranking should be correct

[Actual result]:
The Overall Challenge Top Team table is empty

**Comment by phirework** [comment]
The Overall Challenge Top Team is updated manually by engineers, so you won't see it automatically update.
