### ISSUE TITLE
Verify that referrer links in enroll table are correct

### ISSUE THREAD

**Issue by phirework** [mozilla/voice-web#2332]
Happened to be looking at the Stage db to troubleshoot login stuff, and noticed that enroll links are stuff like these: 

* https://auth.mozilla.auth0.com/login?state=<STATE_TOKEN>&client=<CLIENT_TOKEN>&protocol=oauth2&acco
* https://voice.allizom.org/en/profile/info
* https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=<CLIENT_ID>&as=<ALIAS>&destination=https%3A%2F%2Fauth.mozilla.auth0.com&approval_state=<APPROVAL_STATE>
* https://accounts.google.ro/
* https://github.com/
* https://accounts.google.ro/accounts/SetSID
* https://voice.allizom.org/en/profile/info?challenge=pilot&first=1&achievement=1
 
Is this actually the referer data we want?

**Comment by rileyjshaw** [comment]
Thanks, I noticed this last night as well! Looking into it 👍

**Comment by rileyjshaw** [comment]
Hoping https://github.com/mozilla/voice-web/pull/2362 will improve our records. It's deploying to the staging server now.

**Comment by rileyjshaw** [comment]
@phirework and I just confirmed that referrer tracking is fixed & working. Email clients don't broadcast their referrer info, but if someone signs up from Twitter, Facebook, etc. we’ll know about it.
