### ISSUE TITLE
Team members can still see users who set the visibility to "Private" in the leaderboard

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2338]
**Preconditions:**
Have 2 users part of the same team in the challenge

**STR:**

1. Login with first account
2. Navigate to Challenge page
3. Change visibility to Private in the leaderboard
4. In a new private tab login with the 2nd account
5. Navigate to Challenge page

**Expected:**
User who set his visibility to Private is not displayed in the leaderboard 

**Actual:**
User is displayed in the leaderboard, even though he set his visibility to Private

User iam_test has visibility set to Private:
![image](https://user-images.githubusercontent.com/5293100/68949289-65220680-07c2-11ea-93b5-9af67376f88d.png)

User qaioana can see the  iam_test user in the leaderboard:
![image](https://user-images.githubusercontent.com/5293100/68949324-7834d680-07c2-11ea-9599-8caffbe3d11f.png)

**Comment by mbransn** [comment]
@viorelaioia did you wait the 20 minutes to be certain it wasn't the caching delay?

@rileyjshaw @phirework I'm still seeing on the profile page (when I come from invite link) that we're missing the team only option for leaderboard visibility in that dropdown.

**Comment by rileyjshaw** [comment]
@viorelaioia are you still seeing this issue?

@mbransn I have all three options available on my logged-in accounts:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/1840854/69108261-f692b200-0a28-11ea-8a96-9e25ef337bbf.png">

From your description, it sounds like you noticed this on the initial profile screen shown immediately after creating a new account from the challenge enrollment link. Is that correct?

**Comment by mbransn** [comment]
@rileyjshaw correct, UX expectation would be that people have the option to choose team only during their profile setup process, not after.

**Comment by viorelaioia** [comment]
Leaving this open because the "Visible within challenge team" option is not available on Profile page on sign up. The bug I described in this ticket is not reproducible anymore.

**Comment by rileyjshaw** [comment]
https://github.com/mozilla/voice-web/commit/03dd08438ffa794181490236244a0e93862557ca fixes this; it'll be on prod within the hour.
