### ISSUE TITLE
User gets the 50 points notification only after contributing to 5 sentences in Speak

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2341]
**STR:**

1. Sign up to the challenge
2. Navigate to Challenges page
3. Click "Speak"
4. Record 1 sentence

**Expected:**
Users gets "50+ points" notification as he did the first challenge contribution (as per points breakdown document)

**Actual:**
Nothing happens. User has to record 5 sentences in order to get the "50+ points" notification.
This is working on Listen contribution.

**Comment by can-007** [comment]
I think this is an expected result. Clips are submitted in packs by default.
There are 2 ways to submit less than 5 clips:
1) click the arrow icon on the left of the "Speak" button, you will get a modal dialog for submitting clips;
2) click the "Listen" button, you will also get the modal dialog for submitting clips.

**Comment by rileyjshaw** [comment]
This is also the behaviour I expected – @mbransn can you confirm?

**Comment by mbransn** [comment]
+1, this is as expected. Closing!
