### ISSUE TITLE
1 point received for each clip

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2343]
[Precondition]:
Join the Voice challenge
Have some points

[STR]:
1.Go to https://voice.allizom.org/en/dashboard/challenge
2.Click Listen/Speak and start contributing

[Expected results]:
Should not receive points for each contribution

[Actual results]:
1 point is added for each clip ( visible in challenge dashboard after a while)

![2019-11-15_16h55_40](https://user-images.githubusercontent.com/41474886/68955470-c51eaa00-07ce-11ea-8310-39789689dc26.png)

**Comment by rileyjshaw** [comment]
Hi @rleitan! To clarify, is the issue here that `Mozilla Team Progress` should be showing 758?

@mbransn for visibility / clarification.

**Comment by mbransn** [comment]
@rleitan receiving a point per clip recorded or contributed to is expected result, 1:1 clip:point ratio. 

@rileyjshaw I am noticing a leaderboard point display lag which I assume is the leaderboard cache? shown in Roxana's screenshot here with the leaderboard not reflecting the 8 add'l points. If so, quite alright, just confirming. Close this out if we're aligned.

**Comment by mbransn** [comment]
Actually the question I posed above is captured in #2337, will follow up on that cache question there. Closing this out.
