### ISSUE TITLE
Tutorial for running it on local machine.

### ISSUE THREAD

**Issue by adsingh14** [mozilla/voice-web#2353]
This project is really good and helpful. I like to be a part of it by adding lines of code but can't able to run it. 

It would be great if anyone could upload a video tutorial for setting up this on local machine including dependencies installation.

**Comment by rileyjshaw** [comment]
Hi @adsingh14, have you seen our [Contributing to Common Voice](https://github.com/mozilla/voice-web/blob/master/CONTRIBUTING.md) document?

**Comment by adsingh14** [comment]
Yes @rileyjshaw, it's complex for me. 

I've installed all dependencies, ran 'npm, yarn, docker-compose up' commands. But it can't run **http://localhost:9000**.

**Comment by can-007** [comment]
`docker-compose up` should've taken care of all the database related matters, but you do need to pay attention to the disk space, in some cases, it might exceed the disk size of the docker image.

I would recommend to very carefully read the [configuration](https://github.com/mozilla/voice-web/blob/master/CONTRIBUTING.md#configuration) and [authentication](https://github.com/mozilla/voice-web/blob/master/CONTRIBUTING.md#authentication) part of the document that riley mentioned.

**Comment by adsingh14** [comment]
I skipped Auth0 a/c which was the reason behind this.
Now, I can guide a new contributor to setup this project on local.

**Comment by adsingh14** [comment]
I'm not able to access other pages except the home page. 
I've double check the contribution file before re-opening this issue. 

Here are the pages which aren't working as the live version:
- Contibute (Only Speak/Listen icon is visible)
- Login page isn't working: How could I check the code after signing in ?

**Comment by phirework** [comment]
Hi @adsingh14 - are you sure your auth0 credentials are actually being read by Docker? You'll need to add it in `docker/local-docker-config.json`. Check your startup logs to see if there are any error messages around not being able to find `config.json` or not finding Auth0 credentials.

**Comment by adsingh14** [comment]
Hi @phirework , Do I need to create **config.json** file ?

Here's my Auth0 configuration: 
![image](https://user-images.githubusercontent.com/35252877/69373808-a76bac00-0cca-11ea-9555-cda441fde790.png)

Still, I'm getting '**config.json**' not found error on using `yarn start` command.
![image](https://user-images.githubusercontent.com/35252877/69374012-27921180-0ccb-11ea-86f9-80c4fe247d87.png)

**Comment by phirework** [comment]
@adsingh14 If you're using `yarn start` instead of Docker then it's not going to read `docker/local-docker-config.json`. Try copying everything in that file to a new `config.json` file in the root directory of the project.

**Comment by adsingh14** [comment]
Got another error ! I've re-cloned it again and followed the instructions, it's not working with 'yarn'.

**Comment by adsingh14** [comment]
I got this while using `docker-compose up` cmd. It doesn't load the '**localhost:9000**'.

![image](https://user-images.githubusercontent.com/35252877/69479743-e1ea5b80-0e26-11ea-952d-ff5e834fed50.png)

**Comment by adsingh14** [comment]
@phirework 
I got this while using `docker-compose up` cmd. It doesn't load the '**localhost:9000**'.

![image](https://user-images.githubusercontent.com/35252877/69479743-e1ea5b80-0e26-11ea-952d-ff5e834fed50.png)

**Comment by can-007** [comment]
The logs seem to be normal docker logs, not the backend/frontend log.

For login page issue, I think a picture/screenshot would help a lot.

**Comment by aryamanpuri** [comment]
I have the same issue , can anyone help me with this @phirework @rileyjshaw 
> Here are the pages which aren't working as the live version:
> 
>     * Contribute (Only Speak/Listen icon is visible)
>
