### ISSUE TITLE
Successful login to CV should always redirect to dashboard

### ISSUE THREAD

**Issue by phirework** [mozilla/voice-web#2355]

**Comment by mbransn** [comment]
If enrolled in current, ongoing challenge, redirect should prioritize Challenge dashboard over Stat dashboard.

**Comment by rileyjshaw** [comment]
> If enrolled in current, ongoing challenge, redirect should prioritize Challenge dashboard over Stat dashboard.

Thankfully, this should happen already as the default dashboard view for an enrolled user is the Challenge tab :)

**Comment by rleitan** [comment]
related to https://github.com/mozilla/voice-web/issues/2384

**Comment by rileyjshaw** [comment]
@mbransn should all logins, regardless of challenge status, go to the dashboard? Or is this challenge-specific?

**Comment by mbransn** [comment]
all logins. challenge logins > challenge tab; non-challenge logins > stats tab
