### ISSUE TITLE
Clicking on enrollment link while logged in should not require a second login

### ISSUE THREAD

**Issue by phirework** [mozilla/voice-web#2356]

**Comment by mbransn** [comment]
Confirming that this is about an existing CV account holder who's currently logged into CV receiving+engaging a challenge invite link.

If so, the expected result is that engaging an invite link would trigger enrollment flow without additional authentication.

**Comment by phirework** [comment]
Yep, that is correct!

**Comment by can-007** [comment]
Does it involve any OAuth authorization flow?
