### ISSUE TITLE
New sign up w/successful email opt-in still showing empty email state on profile page

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#2358]
Expected: sign up for challenge > opt-in to emails when building profile > receive emails to inbox > profile page no longer shows email opt-in > settings screen shows email opt-in confirmation & link to manage settings

Actual: sign up for challenge > opt-in to emails when building profile > receive emails to inbox > **profile page still shows email opt-in** > settings screen has no email opt-in confirmation or ability to manage settings

<img width="1447" alt="Screen Shot 2019-11-17 at 9 46 18 AM" src="https://user-images.githubusercontent.com/18686986/69011459-5ef56c80-091f-11ea-906f-33cbe0283639.png">

**Comment by phirework** [comment]
Yep, this is a known issue based on investigations in #2330 - the medium term solution suggested in there should fix it, but I'm probably not going to look at that until mid-end of next week.

**Comment by mbransn** [comment]
Got it, will close this then. Thanks for confirming.

**Comment by phirework** [comment]
Re-opening it as a P1 since we're closing #2330
