### ISSUE TITLE
cannot log in/sign up on a local machine

### ISSUE THREAD

**Issue by parthparmar7** [mozilla/voice-web#2361]
I was trying to test out the log in/sign up feature locally without using docker.

I created the Auth0 account, added the allowed callback URL and added the following lines with my credentials to config.json which I created in the base folder

```
 "AUTH0": {
 "DOMAIN": "<domain_here>",
 "CLIENT_ID": "<client_id_here>",
 "CLIENT_SECRET": "<client_secret_here>"
}
```

but I am still not able to get to the log in/sign up page and it just shows 

`{"message":""}
`

I also tried adding the auth0 credentials to the tsconfig file but same error

Where am I going wrong ?

**Comment by can-007** [comment]
I recommend to check the mysql server for the db credentials.
Also, there should be some errors from the backend in the console. It could help in troubleshooting this.

**Comment by parthparmar7** [comment]
Yes, I think that was what was causing the login to not work as mysql was not configured properly.

Thanks
