### ISSUE TITLE
Week of challenge doesn't get updated on first login in week 2

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2365]
**STR:**

1. Login to CV staging with an account signed up to the challenge in the first week (until Nov 17)
2. Navigate to Challenge page

**Expected:**
Current challenge is "Let's get social" (week 2)

**Actual:**
Current challenge is "Sign up and Contribute" (week 1). After a page refresh, the week gets updated.

![challenge page-2019-11-18_12 11 15](https://user-images.githubusercontent.com/5293100/69044372-7c006d00-09fd-11ea-9321-efbd6cf474c3.gif)

**Comment by mbransn** [comment]
@rileyjshaw @phirework this is correct on prod, flagging that we verify this is fixed on stage prior to a future deploy.

**Comment by phirework** [comment]
This is probably because we changed the challenge start date on staging to be November 10th so that we could test with a live challenge, so according to that start date it IS now week 2. I can change it back on stage if desired.

**Comment by mbransn** [comment]
Not necessary, just confirming that we're all aligned and understand why things are showing up the way they are. Thanks for confirming the logic. :)
