### ISSUE TITLE
The URL from the invitation link is the same for each invite that is sent

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/voice-web#2367]
STR:

1. Login into common voice account
2. Click on the "Invite" button 
3. Copy the link 
4. Close the window
5. Repeat the above steps 

Expected:
The URL of the invite link should be different each time. 
This is the link URL: https://voice.allizom.org/?challenge=pilot&team=mozilla&invite=b1b1e7cc-0a06-11ea-bb30-067a2205f3e0

Actual:
The URL of the invite link is the same each time when you use it.

**Comment by phirework** [comment]
I was under the impression that this is expected behaviour? The invite token is linked to the person who generated the invite token, it shouldn't be randomizing. @mbransn can you confirm?

**Comment by rileyjshaw** [comment]
@phirework that is correct. @ovidiuboca1: if you log in with a different user, it will give you a different invite link. Invite links are unique to the account you're logged in as, but will always be the same for any given user.

**Comment by mbransn** [comment]
+1
