### ISSUE TITLE
User doesn't get the onboarding modal when signing up from invite link

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2368]
**STR:**

1. Navigate to a challenge invite link with an account never used in Common Voice
2. Accept privacy policy and click "Save" button

**Expected:**
4 steps [onboarding modal ](https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5d97a8a8451c970245fd6a80) is displayed

**Actual:**
User remains on Settings page

**Comment by mbransn** [comment]
@viorelaioia on production, yes? Yesterday this was working for @phirework and myself -- @rileyjshaw are you able to reproduce?

**Comment by viorelaioia** [comment]
Just verified on prod and it works as expected. Therefore, I'm gonna close it.
