### ISSUE TITLE
devops : Upload of this clip keeps failing at server, reload the page or try after sometime

### ISSUE THREAD

**Issue by tgkprog** [mozilla/voice-web#2369]
"Upload of this clip keeps failing at server, reload the page or try after sometime" keep seeing this error using Firefox 68.0 (64-bit) on Ubuntu 18.10

**Comment by phirework** [comment]
Thanks @tgkprog! We're aware of the issue and looking into it right now.

**Comment by phirework** [comment]
@tgkprog Could I ask you to try submitting a clip to our staging server? We're testing a fix: https://voice.allizom.org/en/speak

**Comment by rileyjshaw** [comment]
We've got another fix out with https://github.com/mozilla/voice-web/pull/2373; it should hit the staging server soon.

**Comment by rileyjshaw** [comment]
Confirmed that this is fixed on prod.
