### ISSUE TITLE
Individual count amounts for speak and listen are inversed on Challenge dashboard

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#2372]
@rileyjshaw currently speak is at 200 and listen is at 100.

<img width="1434" alt="Screen Shot 2019-11-18 at 10 30 14 AM" src="https://user-images.githubusercontent.com/18686986/69080519-0393af00-09f1-11ea-8f87-54273fa9ed62.png">

Expected:
Listen goal is 200
Speak goal is 100

FWIW Listen will always be the larger goal throughout the challenge. :)

**Comment by rileyjshaw** [comment]
On it.

**Comment by rileyjshaw** [comment]
@mbransn confirming these goals are correct:

|        | Listen | Speak |
|:------:|:------:|:-----:|
| Week 1 |   200  |  100  |
| Week 2 |   100  |   50  |
| Week 3 |   200  |  100  |

**Comment by rileyjshaw** [comment]
(Confirmed in a different thread)

**Comment by viorelaioia** [comment]
@rileyjshaw , was this deployed in prod as well? I confirm it works well in staging, but I can only see week 2 with the corresponding value.

**Comment by mbransn** [comment]
Confirmed deployed to prod.
