### ISSUE TITLE
Mobile Challenge dashboard UI fixes

### ISSUE THREAD

**Issue by georai** [mozilla/voice-web#2374]
https://www.dropbox.com/s/zvst5c5g67jc4tt/Screenshot%202019-11-18%2016.21.28.png?dl=0

1.This should be named "My Points."
2.There should be a full button Invite
3.Tab should be blue
4. It shows only when you have points. If no points were allowed just remove
5. Spacing should be 20 px from the border
6. Under numbers should be a line 

https://www.dropbox.com/s/3zrd4l9mpymzlqx/Screenshot%202019-11-18%2016.22.13.png?dl=0

1.Fix the numbers
2.Fix the buttons
3.The % sign should be aligned with the top of the number. And the number should be 24 semibold
4.Spacing should be no more than 20 px
5.Put the dropdown "show all challenges" 

@mbransn @rileyjshaw

**Comment by rileyjshaw** [comment]
@catherine917 please take a look at this when you have a chance.

**Comment by catherine917** [comment]
@georai If I click the dropdown `show all challenges` what would happen?

**Comment by mbransn** [comment]
@catherine917 the expanded content is shown in the mobile design here: https://zpl.io/VxQm9ZJ
