### ISSUE TITLE
Tablet - Challenge screen

### ISSUE THREAD

**Issue by georai** [mozilla/voice-web#2376]
https://www.dropbox.com/s/iyhlll9zvhthaui/Screenshot%202019-11-18%2016.28.10.png?dl=0

1.The tabs needs to be in line with me points and invite button.
2. Please add points
3. Please add the icon and invite
4. In my design the tab is blue not black
5. Please add the line.
6. Please Add   +50 points Way to send your first invite!
7. The ribbon icon is missing Show my rankings
8. Please move to the left according to the column  Approved and  Accuracy
9. Too much space between the number and icon.
10. Can we have here the scroll, please let me know if I need to add load more button here?
11. Is missing the ribbon icon.

@mbransn @rileyjshaw

**Comment by rileyjshaw** [comment]
@catherine917 please take a look at this when you have a chance.

**Comment by catherine917** [comment]
@georai 
For No.7, the ribbon icon is missing because the current account 's visibility is `Hidden.` You can set it as `Visible for team only` or `Visible for all.`   and the ribbon icon will show up. 
No.11 is the same as the above.

**Comment by catherine917** [comment]
@georai And I have a little bit confused about the No.10. Now we have a scroll and the more button.
