### ISSUE TITLE
Inconsistent behavior on sign-up vs login using an invite link

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2384]
[Precondition]:
Have an invite link - from account 1
Have account 2 created in CV production

[STR]:
1.Open the invite link in a tab
2.Login with account 2 credentials

[Expected result]:
The page should be redirected to challenge dashboard after a successful login ( like it's happening on sign-up for new accounts)
@mbransn 

[Actual result]:
The page is redirected to https://voice.mozilla.org/en?challenge=pilot&first=1&achievement=1 and the homepage is displayed

![2019-11-19_12h37_35](https://user-images.githubusercontent.com/41474886/69139531-60fb2f00-0ac9-11ea-8808-9b31c0ff816e.png)

**Comment by mbransn** [comment]
Yes, this is expected based on P0 implementation. We'll continue to track this via #2355, closing.
