### ISSUE TITLE
Sign up toast gets displayed on every page refresh

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2387]
**STR:**

1. Sign up to the challenge with an account not used before in Common Voice
2. Check the privacy policy checkbox and click Save
3. Click Next in the onboarding modal, then "X", when reaching the last step => Challenges page is returned, 50+ bonus for sign up toast is displayed
4. Refresh the page

**Expected:**
Page is refreshed, nothing happens

**Actual:**
Onboarding modal is displayed again. After clicking "X" in order to dismiss it, the user receives 50+ bonus for sign up toast again. This happens on every page refresh.

**Note:**
Points are not actually added to user profile.

![iuqqx-095iv](https://user-images.githubusercontent.com/5293100/69161784-573af100-0af4-11ea-9b8c-7af43ebbb790.gif)

**Comment by rileyjshaw** [comment]
This was fixed on staging last night and should now be fixed on prod.

Note: I notice you're testing on prod. Please don't create any more test accounts on prod, as the challenge is now officially underway! 🎉
