### ISSUE TITLE
Capitalize individual title on weekly challenge card

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#2389]
Can we update `individual` to be title case `Individual` for consistency with `Team`?

<img width="159" alt="Screen Shot 2019-11-19 at 9 46 43 AM" src="https://user-images.githubusercontent.com/18686986/69196119-703aa680-0ae2-11ea-97db-fb143672675b.png">

**Comment by mbransn** [comment]
@catherine917 are you able to update this today? cc @rileyjshaw

**Comment by rileyjshaw** [comment]
Done! On its way to staging now.

**Comment by mbransn** [comment]
Thank you!
