### ISSUE TITLE
Error when signing-up using an invite link

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2393]
[Precondition]:
Have an invite link - from account 1
Have account 2 created in CV production

[STR]:
1.Open the invite link in a tab
2.Login with account 2 credentials (e.g. login with google)

[Expected result]:
The page should be redirected to challenge dashboard after a successful login 

[Actual result]:
The oage is redirected to: https://voice.mozilla.org/callback?code=Y2bT06wNI5hHDYB2&state=U2FsdGVkX19Lh7Qos9n1YEb%2BAb8AssYai5ozlv8W9XbDETmKdv0iSIPdVDQPd%2FGlmCItDc9IltvRgGw8XKhE89%2BrngeOyRTk9j41dF7Q3BQAU5xnl0G2otGfPtTngbW%2B8XR5NVZbej5XKbvk%2Fa%2FBdSn7RPR5OUCXMulUt4V%2FModtYNN9fU%2B08TA82JjoNKn9vOY9h5adDrtHarsNbQ3O40p3I%2Bq5vZl%2Bv%2FgJChAlHow%3D

![2019-11-20_12h18_53](https://user-images.githubusercontent.com/41474886/69230536-214b4a80-0b90-11ea-8e03-9d30ab77ae43.png)

Update:
I used an invite link generated yesterday, it works fine with the officil invite link sent by George via email
@rileyjshaw is this expected I guess?

**Comment by can-007** [comment]
> Open the invite link in a tab

Is it that you have one tab with account 1 logged in, then open another tab and try to login account 2 using that invite link?

**Comment by rleitan** [comment]
I cannot reproduce it anymore with a link generated today. I'll close the bug for now
