### ISSUE TITLE
Buttons overflow in some languages like greek.

### ISSUE THREAD

**Issue by emilio** [mozilla/voice-web#2417]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1597630

**Comment by mbransn** [comment]
@emilio thanks for reporting, see also #2434 -- are there recommendations you can provide for greek specifically to improve the text translation in overflow areas?

**Comment by emilio** [comment]
I'm not greek, so not many :)

**Comment by Damian96** [comment]
this issue is duplicate, see [https://github.com/mozilla/voice-web/issues/1917](https://github.com/mozilla/voice-web/issues/1917).

**Comment by mbransn** [comment]
Ah, @emilio apologies for assuming you were! And thanks @Damian96 we are indeed getting multiple reports on this and will work to mitigate in the coming months. Appreciate the patience.

**Comment by rileyjshaw** [comment]
This should be fixed by https://github.com/mozilla/voice-web/pull/2510.
