### ISSUE TITLE
The Team progress table is empty

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2419]
[Environment]:
Windows 10 - Edge, Firefox

[Precondition]:
Join the Voice Challenge using an invite link
Create a new account

[STR]:
1.Go to Dashboard

[Expected result]:
The Team progress table should be populated 

[Actual result]:
The Team progress table is empty

**Comment by phirework** [comment]
This is on staging, right? With the changed challenge dates?

**Comment by mbransn** [comment]
@rleitan can you confirm that you're referring to "Overall Challenge Top Team"? If so, this is as expected; team points are tied to the weekly challenge and populated manually at week's end (tomorrow).

**Comment by rleitan** [comment]
> @rleitan can you confirm that you're referring to "Overall Challenge Top Team"? If so, this is as expected; team points are tied to the weekly challenge and populated manually at week's end (tomorrow).

I'm referring to "Mozilla Team Progress". The issue is still reproducible

![2019-11-26_11h59_17](https://user-images.githubusercontent.com/41474886/69619428-39b1de00-1044-11ea-9d22-63103da27155.png)

**Comment by rleitan** [comment]
> This is on staging, right? With the changed challenge dates?

I can reproduce it in staging only.

**Comment by can-007** [comment]
The challenge on stage starts on 11-19.
Only 3 Mozilla members set their visibility to be `team_only`; others `private`.
All the 3 Mozilla members' contributions and achievements are earned before that date. Thus, no one has any points during the challenge.

cc @phirework  , do you think this is expected behavior?

**Comment by phirework** [comment]
@can-007 Yeah that's expected behaviour. @rleitan I can change the challenge start date on staging to be Nov 11th again if it makes testing life easier (though I don't think it's relevant for you any longer). Going to close this issue in the meantime.
