### ISSUE TITLE
The Accuracy values should be displayed on a single row

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2420]
[Precondition]:
Join the Voice Challenge

[STR]:
1.Go to https://voice.mozilla.org/en/dashboard/challenge
2.Observe the Team Progress table

[Expected result]:
The Accuracy values should be displayed on a single row

[Actual result]:

![2019-11-25_19h24_03](https://user-images.githubusercontent.com/41474886/69563303-869ca280-0fb9-11ea-89f0-3bd9a6ca2083.png)

**Comment by viorelaioia** [comment]
I confirm it's fixed!
