### ISSUE TITLE
Page is not scrolled up to Leaderboard visibility when setting visibility for top contributor

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2426]
**STR:**

1. Sign up to a challenge in CV prod
2. Navigate to challenge page
3. Click "Set my visibility" button from Top contributors table on the bottom of the page

**Expected:**
Page is automatically scrolled up to Leaderboard visibility options

**Actual:**
Page is not scrolled, user has to manually scroll up to see the Leaderboard visibility options. 
See [video](https://drive.google.com/file/d/1c_ze5R24hegtKiofwNs2Hn4L3ksnisgz/view?usp=sharing)

**Comment by mbransn** [comment]
+1 re: expected result. attn: @rileyjshaw

**Comment by rileyjshaw** [comment]
Thanks for the ping @mbransn! Fixed in https://github.com/mozilla/voice-web/commit/3bcc694e44fa38e70a414f01a4aa5e19acdc488b, should be on staging soon.

**Comment by viorelaioia** [comment]
@rileyjshaw , I cannot verify this on staging, as the challenge has reached the 3 weeks and the dashboards are not displayed anymore (see below). 
Can we change the start date, so that the challenge is still active in staging, in order to test this?

![image](https://user-images.githubusercontent.com/5293100/70050367-70a16a00-15d7-11ea-874c-147cef4ccd35.png)

**Comment by mbransn** [comment]
@viorelaioia thanks for flagging, we're working to get stage updated to allow verification. Reopening until that happens.

**Comment by rileyjshaw** [comment]
Date is updated! This is now fixed on staging.

**Comment by viorelaioia** [comment]
This is fixed on desktop, but it's still happening on mobile (see below). 
Can we fix it on mobile as well? @rileyjshaw , @mbransn 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5293100/70438551-c2923600-1a96-11ea-9073-a35ad5db5650.gif)
