### ISSUE TITLE
Overall Challenge Top Team leaderboard doesn't show rankings beyond 3rd (or, 3th 😅) place

### ISSUE THREAD

**Issue by rileyjshaw** [mozilla/voice-web#2432]
In the challenge mocks, we display a ranking for each team. Even ones that didn't win points:

<img width="467" alt="image" src="https://user-images.githubusercontent.com/1840854/69689781-b3ff5400-107e-11ea-9199-f91cd2383dbc.png">

Right now, we're only showing the top three teams. This is hard-coded on the server.

![image](https://user-images.githubusercontent.com/1840854/69690429-9df29300-1080-11ea-898d-7c7a058d7949.png)

If the feedback from https://github.com/mozilla/voice-web/issues/2431 is that the Overall Challenge Top Team board should show achievement rankings, we can close this issue.

**Comment by rileyjshaw** [comment]
Closing this issue, since #2431 closed as showing achievement rankings. Pinging @mbransn and @georai to confirm that there are no prizes beyond `3rd` place.

**Comment by mbransn** [comment]
@rileyjshaw this was a programmatic decision with @LRSaunders4 re: 4th place points -- if @LRSaunders4 wants to add points for 4the, go for it!
