### ISSUE TITLE
Challenge achievements need a way to specify which week they apply to

### ISSUE THREAD

**Issue by rileyjshaw** [mozilla/voice-web#2433]
Spin-off of https://github.com/mozilla/voice-web/issues/2431.

Upon adding the Week 1 prizes:

```
INSERT INTO earn (achievement_id, team_id) VALUES(3, 1);
INSERT INTO earn (achievement_id, team_id) VALUES(4, 3);
INSERT INTO earn (achievement_id, team_id) VALUES(5, 2);
```

This happened:

![image](https://user-images.githubusercontent.com/1840854/69701228-516b7f80-10a1-11ea-8117-6ae1ad733ea7.png)

Observed: Week 1 results ended up in Week 2, and Week 1 shows a three-way tie for first.

Expected: Week 2 should remain blank. Week 1 should display what's currently in Week 2.

**Comment by rileyjshaw** [comment]
The big query that handles this is in `leaderboard.ts@getTopTeams`. The bug is: since team prizes are awarded manually _after_ the week in question, `earned_at` is not matching our date constraints of falling _within_ the nth week. I think relying on the date of `earned_at` here at all is brittle, but for now pushing the week out by 1 should solve the immediate problem. I'll push a hotfix, but I'm leaving this open for a proper fix in the morning @phirework @can-007.

The achievements to week mapping is as follows.

Week 1:

- challenge_engagement_rank_1
- challenge_engagement_rank_2
- challenge_engagement_rank_3

Week 2:

- challenge_social_rank_1
- challenge_social_rank_2
- challenge_social_rank_3

Week 3:

- challenge_validated_rank_1
- challenge_validated_rank_2
- challenge_validated_rank_3
- challenge_contributed_rank_1
- challenge_contributed_rank_2
- challenge_contributed_rank_3

**Comment by can-007** [comment]
Apologies for the big query to get top teams.

For this bug, how about using SQLs like this:
`INSERT INTO earn (achievement_id, team_id, earned_at) VALUES(3, 1, (SELECT TIMESTAMPADD(SECOND, 7*24*60*60-1, start_date) from challenges where url_token = 'pilot'));`
make it the last second earning.

**Comment by phirework** [comment]
Hmm I think for non-weekly achievements we'll still need the date that it was earned, but it might be worth considering adding an extra column to the `achievements` table that defines which week's points it's meant to count for, with `NULL` meaning "any week"?

**Comment by rileyjshaw** [comment]
> adding an extra column to the achievements table that defines which week's points it's meant to count for, with NULL meaning "any week"?

Great idea! @can-007 @phirework do one of you have the bandwidth to take this on?

**Comment by phirework** [comment]
@rileyjshaw Yep I can deal with that.
