### ISSUE TITLE
Show exact number of recorded / validated hours

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#2436]
Now that English has reached 1000 validated hours, the homepage graph is a lot less useful because you can no longer see the exact number of hours. It shortens it to "1.0k" so it's rounding down to the closest 100 hours. At the average rate of English validation (assuming no marketing campaign boosts) it takes ~3 months to hit 100 hours, so the graph will only update four times a year.

I can understand why you would want to shorten the label for space reasons on the graph, but I think it's useful for the exact amount to still be accessible somewhere - perhaps by hovering over the graph or validated hours label?

**Comment by rileyjshaw** [comment]
This should be fixed by https://github.com/mozilla/voice-web/pull/2510.
