### ISSUE TITLE
Collaborate with VoxForge on a common library?

### ISSUE THREAD

**Issue by nclm** [mozilla/voice-web#244]
Not sure if this is the right place for a suggestion, but couldn’t find another way:

[VoxForge](http://voxforge.org) does exactly what Common Voice is doing, although with an older interface. It‘s nice to have several initiatives to do voice collecting, but at one point the libraries of recordings associated with the original sentences would be better shared across the projects!

**Comment by kdavis-mozilla** [comment]
About two years ago I'd talked to Ken MacLean  about a collaboration. We're open to working together if VoxForge is.

**Comment by klainkaliber** [comment]
Voxforge is not restricted to English language - a collaboration would be beneficial for all the people with different mother tongue than English - like me!

**Comment by mikehenrty** [comment]
We are going to try and publish the VoxForge data along with our own. Let's close this for now as something we are exploring.

**Comment by davidak** [comment]
Maybe VoxForge could setup an instance of your software and use all the CC-BY-SA sentences that you can't use (because dataset should be CC0 license). Is the project dead? Last news is from 2015.
