### ISSUE TITLE
Contributors not listed on team leaderboard when they are set to Visible. 

### ISSUE THREAD

**Issue by LRSaunders4** [mozilla/voice-web#2444]
Lenovo reported that they are unable to see all of the contributors that have set themselves to visible on the team leaderboard. 

"Most of our members are registered with webpage ([as linked](https://voice.mozilla.org/en?challenge=pilot&team=lenovo)). But some of the members are not listed in the Lenovo team. Although we have set the visibility as “Visible for team only”, but I can’t see some members."

**Comment by mbransn** [comment]
Attn: @rileyjshaw

**Comment by rileyjshaw** [comment]
I just responded in the email – it would be very helpful to get one of the emails that isn't showing up (cc @LRSaunders4).

I'm looking into possible causes in the meantime.

**Comment by rileyjshaw** [comment]
An email just came confirming that this is now fixed. My guess is that there were some caching delays which have now resolved.
