### ISSUE TITLE
Lack of clear "Other" accent option

### ISSUE THREAD

**Issue by rileyjshaw** [mozilla/voice-web#2446]
I just came across https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352/55. It sounds like we have future plans to implement a finer-grained and more flexible accent strategy.

In the meantime, there appears to be [a](https://github.com/mozilla/voice-web/issues/296) [lot](https://github.com/mozilla/voice-web/issues/242) [of](https://github.com/mozilla/voice-web/issues/268) [confusion](https://github.com/mozilla/voice-web/issues/395) coming from the signup process, since we don't surface an "Other / unspecified" option:

<img width="937" alt="image" src="https://user-images.githubusercontent.com/1840854/70004749-46d73d00-151c-11ea-9f02-b3734eccddba.png">

From https://github.com/mozilla/voice-web/issues/242:

> …maybe a clarification like this should be made near the "English accent" field… because otherwise the options in the list give the impression that people outside of English-speaking countries are not supposed to contribute.

I received similar feedback this afternoon in a direct message. A Canadian-born Spanish speaker messaged me this afternoon, saying:

> (I was) thinking that my accent could be "English speaker" but saw it was for "real" Spanish people…

This seems to go directly against the spirit of Common Voice. It sounds like there's a ton of history behind this decision, so @mbransn I'll follow your lead. I think a lightweight option for the time being is to switch the blank select state to "Unspecified", and keep all values sent to the server untouched.

What do you think? cc. @phirework

**Comment by mbransn** [comment]
Thanks @rileyjshaw -- this is a great flag and a known issue. I'd like to wait to deploy any changes to accent collection as there is quite a lot of accent collection research happening at the moment by @nukeador with various linguistic experts around this very topic. Based on their findings we plan to rework the collection UI, including testing for usability, to ensure the data collected is rich and usable across the board. @nukeador please feel free to link to the most relevant research postings here for those interested in following the topic. Going to close as we'll tackle as part of a wider Accent Strategy Implementation epic in 2020.
