### ISSUE TITLE
Team leaderboard displays inconsistant usage of "--" vs. "4th"

### ISSUE THREAD

**Issue by rileyjshaw** [mozilla/voice-web#2448]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/1840854/70105212-0a2b4480-15f5-11ea-9a6f-55a57fcf8248.png">

From https://voice.mozilla.org/en/dashboard/en/challenge

**Comment by can-007** [comment]
I didn't get the `inconstant `part here.
Does it mean that when the team doesn't earn bonus in 2nd week, it should show `--` instead of the rank `4th`, even though it has earned some bonus in the 1st week?

**Comment by rileyjshaw** [comment]
@can-007 thanks for clarifying! I think it would look better to have `4th` show up in the first week as well, and save `--` for weeks that haven't happened yet.
