### ISSUE TITLE
Automatically detect too much noise in samples, prompt to re-record

### ISSUE THREAD

**Issue by SofiCgr** [mozilla/voice-web#246]
An active noise control must be adding. Many samples had a lot of noise or is broken. These samples will have to be re-recorded  and auto-remove. You must give this choice to the volunteers to re-recorded :) It is better to ask for something to say 3- 4 times the same samples. You will get better results! The fourth time he will say it better and you'll get cleaner samples :) 

nice try! :)

**Comment by mikehenrty** [comment]
Hello @SofiCgr 

We have made it so that you can now delete and re-record your voice samples. Does this address your concerns?

**Comment by SofiCgr** [comment]
hello @mikehenrty Thanks for your answer!

Just check the validating donations with "nope"

I checked same samples yesterday. Had a serious problem. This must be done automatically. My english is not very good but I want to help :) You can do that. When you see squared waves With high levels of waves than normal. Then you probably have noise. and you can remove this sambles and tell the volunteer to re-record it again. I know the Web Audio API has no settings for these things. But some way must be exist :)

**Comment by mikehenrty** [comment]
We actually like having some background noise, because it makes the voice recognition agorithm able to understand us when there is background noise.

But if we have so much noise that a human cannot understand the audio, that is a problem.

That said, there might be some processing we can do (either with web audio, or the backend) where we can automatically filter clips with too much noise. We'll use this bug to track investigating that.

**Comment by SofiCgr** [comment]
Something else that can be useful :)

> In telephony, the usable voice frequency band ranges from approximately 300 Hz to 3400 Hz
> https://en.wikipedia.org/wiki/Voice_frequency

So if we use one bandpass filter and we cut all the other noise  it will be easier to voice recognition agorithm

> Standard second-order bandpass filter. Frequencies outside the given range of frequencies are attenuated; the frequencies inside it pass through.
> https://developer.mozilla.org/en-US/docs/Web/API/BiquadFilterNode

We want to recognize voice with some background noise. But with a lot of noise can not be recognized
Usually when the volume is too high we have deformation. This somehow need to check . My old pay speech recognition program had a bar and when I was talking, it showed the volume of the voice When it became red i understood that it has noise.

I will check again for the voice frequency band ranges in my books because i do not remember it and I'm not so sure about wiki because this is just talking about TV.

**Comment by kdavis-mozilla** [comment]
@SofiCgr We want to record the entire spectrum. We are creating a speech corpus that _can be_ used for STT, but can also be used for other applications. Prematurely manipulating the signal without all downstream applications in mind limits the usefulness of the corpus. Thus it is something we do not want to do.

**Comment by SofiCgr** [comment]
@kdavis-mozilla 
oh sorry :) I thought you want to do the voice synthesizer or speech recognition  and for these two noise is a real problem. but if you want to use them for other things the samples must be kept clean :)

**Comment by kdavis-mozilla** [comment]
@SofiCgr for STT the noise isn't a problem; it's actually an advantage. A STT engine has to be robust against noise it encounters in the real world.

For TTS yes, noise is a problem. Doing TTS one would want to remove the noise.

However, this corpus is multi-purpose. So, we wouldn't want to remove noise at this early stage. We want to let the various users of the corpus remove or not-remove noise as they see fit for their applications.

**Comment by SofiCgr** [comment]
@kdavis-mozilla The harmonics of voice they are not removed from what I said :) You can put the voice in whatever space you want with filters. The voice harmonic is the one you want to be clean for STT not noise :) but if you believe something different you can try :)
