### ISSUE TITLE
UI of percentage until goal is reached on Stats page is broken 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2462]
On https://voice.allizom.org/en/dashboard/en/stats:

![Screenshot_2019-12-09 Common Voice by Mozilla](https://user-images.githubusercontent.com/5293100/70427836-1e9c9080-1a7e-11ea-8806-2bce4de1dbec.png)

**Comment by rileyjshaw** [comment]
Likely related to https://github.com/mozilla/voice-web/issues/2447
