### ISSUE TITLE
UI bug: extra background under email subscription checkbox in footer

### ISSUE THREAD

**Issue by rileyjshaw** [mozilla/voice-web#2463]
<img width="84" alt="image" src="https://user-images.githubusercontent.com/1840854/70461652-0886d400-1a6e-11ea-8ec7-b7ab6e1237b6.png">

**Comment by Kriyszig** [comment]
I created #2464. A review would be great.

P. S. the Docker build has failed in CI with the error
```bash
The command "echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin" failed and exited with 1 during .
```
marking it red. A re run should hopefully give us the correct CI results

**Comment by rileyjshaw** [comment]
Oh no, sorry @Kriyszig! This bug was fixed in https://github.com/mozilla/voice-web/commit/fa5f837386591668f3f6213ec152f987c8817792.

We appreciate your contribution, please feel free to take a look at other UI bugs such as https://github.com/mozilla/voice-web/issues/2462.
