### ISSUE TITLE
Invite button is available when there is no active challenge

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2466]
**STR:** 
1. Login to your Common Voice account
2. Navigate to Challenges page

**Expected:**
"Invite" button is not available, as there is no challenge in place

**Actual:**
"Invite" button is available, even though there is no active challenge.

![image](https://user-images.githubusercontent.com/5293100/70524930-e6b14e00-1b4e-11ea-91c4-f529fc6755aa.png)

@mbransn , can you please confirm that the expected results are correct? Thanks!

**Comment by mbransn** [comment]
@viorelaioia thanks for flagging -- the invite button is actually okay to stay here independent of the challenge. We're looking to bring the invite button to the overall dashboard and rework as a general invite mechanism for Common Voice. I'd see leaving it here as first step. Going to close cc @rileyjshaw
