### ISSUE TITLE
We’re sorry, but your platform is not currently supported.

### ISSUE THREAD

**Issue by cristianursena** [mozilla/voice-web#2477]
Hi, we installed out instance ov voice-web on our server but when we try to load it we get : We’re sorry, but your platform is not currently supported. We are using latest chrome and mozilla and still get the same error. We are using the public ip to access it and get this error. We don't use localhost:9000 instead ip:9000. Can someone help?

http://13.81.96.116:9000

Platform: Ubuntu 18.04
Nodejs: 10.17.0
Npm: 6.11.3
Yarn: 1.21.1
FFmpeg: 3.4.6
Mysql: 5.7.28

Thank you

**Comment by cristianursena** [comment]
we are using the public ip to access it and get this error. we dont use localhost:9000 instead ip:9000

**Comment by nukeador** [comment]
You need to serve all your content using https for the browser webRTC to work.

**Comment by phirework** [comment]
Discussed over slack, closing issue.

**Comment by dingxuan92** [comment]
Hi @phirework, 

I am also facing the same issue, can I get some help from this.

Thank you!

**Comment by nukeador** [comment]
@dingxuan92 please check previous messages, you need to serve the content over https for browsers to all webrtc to work.
