### ISSUE TITLE
Implement better sentence selection mechanism to promote word diversity

### ISSUE THREAD

**Issue by reinhart1010** [mozilla/voice-web#2484]
Hello, I'd like to suggest an improvement of sentence selection mechanism (that are used to show users which one to speak) in Common Voice to improve the word diversity (**not** the word `diversity`). This mechanism will involve large database work and analysis.

The background behind this suggestion is the fact that the sentence corpus we use does not guarantee an equal distribution of word frequency. Some words may have been overused throughout the corpus (such as `the`, which has been used 1,058,221 times on English) while there are many (more than 300,000 unique words in English) of them that only appear once inside the corpus.

The current sentence selection algorithm, [`findSentencesWithFewClips()`](https://github.com/mozilla/voice-web/blob/54beabc81934518372edbc913049401e37698439/server/src/lib/model/db.ts#L160), only selects sentences based on the number of clips the sentence has been associated. However, as new sentences are added, the frequency and discoverability of rare words to speakers will gradually decrease unless if those were added in new sentences. This will then cause an inequality of training data for individual words in the voice dataset, which may impact the overall accuracy and performance of the trained STT model.

To reduce this issue I suggest to create a **vocabulary index** from the entire language corpus, consisting both the word as well as their frequency (in logarithmic scale). Words that end with punctuation marks (`.,?!`) should be separated from the original as they may have been pronounced differently in certain languages.

![image](https://user-images.githubusercontent.com/17312341/70849177-7dfb0600-1ead-11ea-88b1-cb233e78845b.png)

Then, a **clip target** is set up to determine the minimum number of verified clips of each word, based on the calculated frequency values. By using the above example (without considering logarithmic scales), we can set a target of 100 validated clips per month for each word that occurs once, 200 for twice, 300 for three times, and so on.

When a user requests a "random" sentence, the API will then look up on words that are under the clip target. It then finds and passes a random (yes, this one's random) sentence that includes the given word to the user. Once the user's clips has been accepted and validated, the clip counter of each contained word is increased.

With this mechanism, words that appear more frequently in the corpus should be able to pass the clip target very easily, reducing need to load sentences that contains multiple frequent words. This is also effective to eliminate potentially duplicate sentences from being spoken by speakers, such as `I am happy` with `I am very happy`. Finally, less-frequent words in Common Voice corpus are given a chance to be spoken by diverse speakers, as well to be trained in STT engines.

**Comment by MichaelKohler** [comment]
Let's start a discussion at https://discourse.mozilla.org/c/voice/239 and document the outcome (decision) in a new GitHub issue.
