### ISSUE TITLE
Top Contributors leaderboard shows nothing on Stats dashboard

### ISSUE THREAD

**Issue by rileyjshaw** [mozilla/voice-web#2486]
<img width="598" alt="image" src="https://user-images.githubusercontent.com/1840854/71023987-e3c7d780-20d1-11ea-9212-7396864b6a44.png">

@phirework and I are going to look into this. It's related to some leaderboard investigations we're doing this week.

**Comment by rileyjshaw** [comment]
(As mentioned in https://github.com/mozilla/voice-web/issues/1821, this relates to some cache issues we've been noticing)

**Comment by phirework** [comment]
Closing this because we're revamping the whole thing, whoot.
