### ISSUE TITLE
Foreign language clips appearing in English validation queue

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#2488]
I've been noticing foreign language clips appearing in the English validation queue recently. These contain characters that do not exist in English and would have been filtered out by Sentence Collector.

Additionally, the user speaks them fluently and without hesitation, which would probably not be the case if the user was expecting to speak a clip in English.

So for these reasons, I think this is not a case of a sentence in the wrong language being mistakenly included but that clips correctly recorded in other languages are somehow making it into the English validation queue.

![IMG_8075](https://user-images.githubusercontent.com/18251622/71032174-a8c1a600-20c9-11ea-9a56-6619a4b27571.PNG)

![IMG_7961](https://user-images.githubusercontent.com/18251622/71032189-b119e100-20c9-11ea-9da4-4a8724df014d.PNG)

**Comment by stefangrotz** [comment]
I have seen similar things in German. I think most of these sentences can be avoided by using a whitelist for the alphabet of one language or a blacklist for letters like cyrilic, greek and non-english-latin letters. This blacklist should be part of both, the wiki extractor and the sentence collector.

**Comment by phirework** [comment]
Yikes, super good flag, thanks you two!

**Comment by phirework** [comment]
@stefangrotz @dabinat Circling back to this, do you have an approximate sense of when this started?

**Comment by dabinat** [comment]
@phirework Not sure... maybe a week or so before I reported it.

But the clips should be fairly easy to find because many of them contain characters that don’t exist in English (see my screenshots above).

**Comment by dabinat** [comment]
@phirework I was validating some clips and came across a foreign language one. I reported it and moved onto the next clip. The next clip was the exact same voice speaking a sentence in English.

This made me wonder if this has something to do with recording in one language and then switching and recording in another. Perhaps a cache or session variable somewhere still retains the previous language ID?

**Comment by phirework** [comment]
@dabinat That's a great clue, thanks for that. We have a migration script that'll fix the ~700 clips that are currently mislabelled that'll land on production later this week / early next week, and I'll file a JIRA ticket to investigate the language setting mechanics more fully.

**Comment by stefangrotz** [comment]
The same bug is happening in Esperanto in the last Days. It is a language where it is very likely that people also donate other languages.

What is the best thing to do when this happens? Ignore the sentence, klick no or report it?

**Comment by MichaelKohler** [comment]
There is another mention of that here: https://discourse.mozilla.org/t/beim-anhoren-satze-in-anderer-sprache/55729

**Comment by nukeador** [comment]
This issue is also being mentioned here

https://discourse.mozilla.org/t/listening-validating-for-dutch-language-turns-up-a-lot-of-frysian-frysk-sentences/59603/4

**Comment by rileyjshaw** [comment]
We have released a fix to this issue. Closing for now, but please let us know if you see anything similar in the future.

Thanks for the report!

**Comment by robovoice1** [comment]
check this one out: bug #3374
single english sentence/clip in german section
