### ISSUE TITLE
Problems with sentences in Russian

### ISSUE THREAD

**Issue by iLeonidze** [mozilla/voice-web#2497]
From my point of view, as a native speaker of the Russian language, sentences have a variety of problems:
1) Russian sentences have a very strong political bias, and strong clericalism. In life, not so many people speak in that way, and I'm afraid that the neural network will have issues with sentences recognition based on such a dataset.
2) Many sentences in the dataset are duplicated: they differ in several words, or even letters. I will give an example:
```
Выступление президента Республики Кипр.
Выступление президента Республики Палау.
Выступление президента Республики Перу.
Выступление президента Республики Польша.
Выступление президента Республики Суринам.
Выступление президента Республики Хорватия.
Выступление президента Республики Чад.
Выступление президента Республики Чили.
Выступление президента Республики.
```
or
```
Благодарю посла Германии за его заявление, за его объявление и за его добрые слова.
Благодарю посла Демиралпа за его заявление.
Благодарю посла Египта за ее заявление.
Благодарю посла Звекича за его заявление.
Благодарю посла Илиопулоса за его выступление от имени Европейского союза.
Благодарю посла Индии за его выступление и предоставляю слово послу Венесуэлы.
Благодарю посла Индии за ее заявление.
Благодарю посла Ирана за его выступление.
Благодарю посла Испании за его заявление и за его добрые слова.
Благодарю посла Италии за его замечания и за его теплые слова.
Благодарю посла Италии за его заявление.
Благодарю посла Казахстана за его заявление и за его добрые слова.
Благодарю посла Канады за ее заявление.
Благодарю посла Кеннеди за ее заявление и теперь предоставляю слово послу Марокко.
Благодарю посла Кеннеди за ее заявление.
Благодарю посла Китая за его заявление и за его поддержку.
Благодарю посла Китая за его заявление.
Благодарю посла Китая.
```
or
```
Бангладеш имеет честь руководить этим процессом.
Бангладеш имела честь руководить этим процессом.
```
There is a suspicion that this dataset was artificially generated. There is no sense from the volume of such similar political sentences.
3) The texts have a one-sided political bias, they lack, for example, culinary category, or computer subjects. The texts do not have modern slang or modern language turns, such as "туса", "инстаграм", "видос", "звякнуть", "чекнуть", "кек" and the like. ~~There is no bad language in the text.~~
4) The texts simply do not have a huge number of words used in everyday life, for example, such as
- модный (fashionable)
- школа (school)
- бульвар (boulevard)
- мяч (ball)
- классно (cool)
- отлично (cool/excellent)
- супер (cool/super)
- гараж (garage)
- пирог (pie)
- ботинок (boot)
- черный, белый, оранжевый (black, white, orange)
- песня (song)
- жанр (genre)
- лента (ribbon/feed)
- плеер (player)
- тусовка (party)
- магазин (store)
- And many others
5) For now, Russian section at common-voice.github.io has a huge queue of texts, but, apparently, there are no more people who check them. 

So, I have a few questions/suggestions:
1) Can we remove a huge number of unnecessary similar political sentences?
2) Is it possible to somehow add sentences without waiting for someone who once checks them? My colleague and I are ready to add a lot of sentences from different spheres of life, so that the dataset becomes closer to normal speech. Can we do this directly via pull or we should wait for an eternal check? We are ready to voice all that we add.

**Comment by spartedo** [comment]
Fully agree with this statement, also many parts of incoming text has political context, that need to be moderated.

**Comment by iLeonidze** [comment]
Found a repo with russian sentences datacet: https://github.com/Koziev/NLP_Datasets
The author automatically collected texts from fiction. Asked the author to publish texts under CC0.

**Comment by nukeador** [comment]
In order to centralize the conversation, let's continue in this existing topic

https://discourse.mozilla.org/t/russian-senteces-are-low-quality/50941/

Once we have reached an agreement we will be able to open a change request if needed here.
