### ISSUE TITLE
Add voice verification functionality

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#25]
Users can help us validate voice input. Right now we don't have this scoped, so we would need to do that if this becomes a priority.

This was originally brought up in issue #3.

**Comment by breandan** [comment]
Out of curiosity, is Mozilla planning to open source the data from *all* recordings, or just the ones marked as valid? I have an application that requires training data from valid and invalid speech recordings, so it would be useful to see all the recordings and their corresponding valid/invalid label. Thanks, looking forward to the data set!

**Comment by mikehenrty** [comment]
> Out of curiosity, is Mozilla planning to open source the data from all recordings, or just the ones marked as valid? I have an application that requires training data from valid and invalid speech recordings, so it would be useful to see all the recordings and their corresponding valid/invalid label.

Oh interesting use case! There's no reason why we couldn't release the invalid data set as well if people would find it useful. Can you tell me a little bit more @breandan about why you would need that?

**Comment by breandan** [comment]
Having the recordings marked invalid would be *extremely* useful for [speech verification](https://en.wikipedia.org/wiki/Speech_verification) tasks. Specifically, I would like to use these to train a pronunciation scoring model, and need recordings labeled correct and incorrect to develop a good speech distance metric.

**Comment by mikehenrty** [comment]
Good to know @breandan, we've noted this. Stay tuned!
