### ISSUE TITLE
Problem repeat 5 listen (all language) with Common Voice

### ISSUE THREAD

**Issue by hellosct1** [mozilla/voice-web#2502]
hi,

I've created a post on Discourse that explains an annoying problem

https://discourse.mozilla.org/t/problem-repeat-5-listen-all-language-with-common-voice/50967

thanks

**Comment by phirework** [comment]
This should be fixed, can you verify?

**Comment by hellosct1** [comment]
hi,
Very thanks. 

I just ran the tests, and it's fine.

thank you for correcting


Christophe
