### ISSUE TITLE
problem Goals (all language)

### ISSUE THREAD

**Issue by hellosct1** [mozilla/voice-web#2503]
Hi,

A problem I've been spotting for several days, but I've managed to clarify it...

You no longer display the message of the goal reached when you just do the listen mode.

The tests I've done for any challenge with different account : 
Talking: Okay.
Both... okay.
Listen : NO 

the objective is reset to zero when the 24 hours have passed.

thanks
Christophe

**Comment by phirework** [comment]
Hi @hellosct1, thanks for reporting this issue. This should be fixed now, can you verify?

**Comment by hellosct1** [comment]
hi,
Very thanks. 

I just ran the tests, and it's fine.

thank you for correcting


Christophe
