### ISSUE TITLE
[Mac] Refresh blocked on /speak page

### ISSUE THREAD

**Issue by rileyjshaw** [mozilla/voice-web#2513]
Our shortcut handlers are correctly blocked when [`ctrl` | `alt` | `shift`] is pressed. However, shortcuts _do_ run when Mac's `command` key is down. This has unintended effects, such as overriding the default refresh behaviour (`command` + `r`) on the /speak page.

**Comment by phirework** [comment]
Awesome, thanks for noticing + fixing!
