### ISSUE TITLE
The icons on about page are sometimes too big

### ISSUE THREAD

**Issue by Adrijaned** [mozilla/voice-web#2516]
![Screenshot_20200104_150218](https://user-images.githubusercontent.com/22203805/71766746-828e6980-2f03-11ea-9b45-2b4ed01f95fa.png)
Happens on Firefox nightly for me, and only sometimes, goes away when reloading the page

**Comment by kosciCZ** [comment]
Happens for me too, in Firefox 71

**Comment by rileyjshaw** [comment]
I think I have a fix for this, but I'm having trouble reproducing the original issue. Can you please provide more detailed steps so I can ensure I have a solution?

**Comment by rileyjshaw** [comment]
@Adrijaned @kosciCZ can you please confirm that this is now fixed on https://voice.mozilla.org/about?

**Comment by kosciCZ** [comment]
It seems fixed for me, I wasn't able to get it to bug out again. Thank you!

**Comment by rileyjshaw** [comment]
Great! Thanks for verifying.
