### ISSUE TITLE
Layout broken on small screens

### ISSUE THREAD

**Issue by davidak** [mozilla/voice-web#2517]
This is how the website looks on my 12.5" Thinkpad X230 (1366x768 pixels) with german locales. I think 12" is a common format for notebooks and should not break the layout.

![Screenshot from 2020-01-04 23-29-38](https://user-images.githubusercontent.com/91113/71772433-1c2d3980-2f4b-11ea-8f0e-fb6dccf3c3cf.png)

**Comment by phirework** [comment]
@davidak Thanks for the report! This has been flagged by a bunch of other users already and is fixed by #2510. You can see it on staging at https://voice.allizom.org/de/dashboard/stats and it will land on production within the next week or so.
