### ISSUE TITLE
Share function during sentence recording

### ISSUE THREAD

**Issue by stefangrotz** [mozilla/voice-web#2529]
During the sentence recording there is a little "basket" icon that lets you share the link voice.mozilla.com to twitter and facebook:

![Bildschirmfoto 2020-01-13 um 14 45 00](https://user-images.githubusercontent.com/5982239/72264809-9e88be00-361b-11ea-94ab-3f8ce830a262.png)

- Why does this exist at every sentence you record?
- It doesn't have a explain text when you hover it like the other two icons.

This icon is very confusing for me and I don't find it useful at this position at all. Do I misunderstand this feature?

**Comment by phirework** [comment]
@mbransn Do you have any insight into the origin of this?

**Comment by mbransn** [comment]
@stefangrotz thanks for asking. This function originated as a concept for providing people a way to share Common Voice via a specific recording they've contributed; this could be via a social channel or merely as a link. Agreed that it should have a tooltip (e.g. "Share your clip") to provide some context -- apologies that this wasn't caught in original testing. I'll file a bug to get that updated.

As for how useful the interaction is in this position, that is still being determined. Your feedback is helpful to hear. There is also share capability on the submission success screen (see below) and we're working to understand how much people do or don't engage with sharing to better iterate on the feature over time. 

<img width="1455" alt="Screen Shot 2020-03-03 at 4 58 23 PM" src="https://user-images.githubusercontent.com/18686986/75834473-ec46ba80-5d70-11ea-9187-42bbe90e70e1.png">

I'm going to close this out and track update of the tooltip separately, thank you!
