### ISSUE TITLE
Intermittent failures dowloading /dist/bundle.js

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#254]
About every other request seems to fail. Could be an issue with our deployment. Investigating now.

**Comment by mikehenrty** [comment]
@gozer Any idea's about this?

**Comment by kdavis-mozilla** [comment]
@gozer It there any way we can escalate this? We're beginning a press push today and we would like to have the site working for the push.

**Comment by mikehenrty** [comment]
Gozer fixed this by deleting a bunch of zombie auto-scaling groups. Site's back up functioning normally now.
