### ISSUE TITLE
Where do I see how many recorded clips got accepted?

### ISSUE THREAD

**Issue by r00ster91** [mozilla/voice-web#2543]
So on https://voice.mozilla.org/en/dashboard/stats I can see my voice stats and in Top Contributions I can see my amount of recorded clips, but where do I see how many of those recorded clips actually got approved and accepted into the dataset? I remember there was a percent stat showing that, but it’s not there anymore. Was it removed?

**Comment by phirework** [comment]
Hi @r00ster91! You are correct that the percentage stat used to be visible in your dashboard stats. We're reworking that entire feature right now, and have temporarily replaced it with a simple count while we figure out next steps. There are more details in the Discourse post here: https://discourse.mozilla.org/t/numbers-of-checked-sentences-not-shown-in-dashboard/51804/4
