### ISSUE TITLE
Pronunciation guide on record/playback page

### ISSUE THREAD

**Issue by bitplane** [mozilla/voice-web#2548]
### User story

As a voice donor
I want guidance on how a word is pronounced
So that I can add sentences that contain unfamiliar words

As a reviewer
I want guidance on how a word should be pronounced
So that I can properly review sentences that contain unfamiliar words

### Idea

It'd be pretty simple to have each word be a link to Wiktionary's pronunciation guide for that word, encouraging users to learn about words that they don't know how to pronounce.

### Discourse thread

https://discourse.mozilla.org/t/idea-pronunciation-tips-on-recording-playback-screen/52811/2

**Comment by MichaelKohler** [comment]
Thanks for creating that discourse post. Let's close this issue here and create a new one if there is a tangible action coming out of this.
