### ISSUE TITLE
Cannot Change Avatar: Says image is too large regardless of size

### ISSUE THREAD

**Issue by tawandamoyo** [mozilla/voice-web#2554]
Cannot change avatar on the profiles page. It gives a popup that says image is too large (attached below). 

I'm on Windows 10, using Chrome.

![avatar error screenshot](https://user-images.githubusercontent.com/17948595/73720950-d1f6ce00-472b-11ea-9ec6-7192c3257266.png)

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. I'll close this as a duplicate of https://github.com/mozilla/voice-web/issues/2405
