### ISSUE TITLE
Donate existing transcriptions

### ISSUE THREAD

**Issue by PhoenixIV** [mozilla/voice-web#2559]
I want to transcribe public (CC-BY and the like) audio files. Is or can there be a way to donate those to the system? They need to be transcribed anyway and I can imagine more people can make use of that. How cool would it be to have a transcription tool that uploads bits of voice with it's transcription to the commons?

**Comment by stefangrotz** [comment]
I had similar plans. AFAIK they don't import audio files that comes from other sources than the website. But it is always possible to create your own dataset and mix it with common voice when you train your own language model. Creating your own dataset also has the advantage that it can have a stricter license than CC0 like CC-BY.

One thing that I could imagine: once a language has enough data to create a first (bad) speech recognition system you can use this system to transcribe audio from all kind of sources automatically. These transcriptions then have to be checked manually, but this is surely less work than transcribing everything manually. It would be great if Mozilla could create tools for this and this could lead to a lot of other side datasets with data that is public but not CC0.

**Comment by MichaelKohler** [comment]
This sounds like a great conversation to have over at Discourse: https://discourse.mozilla.org/c/voice/239

Thanks :)

**Comment by PhoenixIV** [comment]
Still did not transfer this. Might loose quite some ideas this way..

**Comment by MichaelKohler** [comment]
What I meant with my comment is "please re-open a thread on Discourse", not that we're gonna do that, sorry for the misunderstanding.
