### ISSUE TITLE
Logging in the iOS app is impossible due to sandboxed cookies

### ISSUE THREAD

**Issue by kornelski** [mozilla/voice-web#2564]
When I try to register or log in in Mozilla Common Voice app for iOS, I’m required to receive an email from Mozilla SSO service and follow a link from the email. 
The problem is that the email link opens in Safari. There is no way to open it in the app. The in-app browser doesn’t even have an address bar. 

iOS sandboxes cookies and won’t expose Safari cookies to the app, so the Voice app never learns that I have got the email.

**Comment by MichaelKohler** [comment]
Recording via mobile Safari on iOS is now implemented, and the native app is being decommissioned. https://discourse.mozilla.org/t/updates-to-common-voice-for-ios/58909
