### ISSUE TITLE
“Unsupported Browser” error while trying to record on iOS

### ISSUE THREAD

**Issue by reinhart1010** [mozilla/voice-web#2565]
After logging in to Common Voice via Firefox Accounts, trying to record voice returns an “Unsupported Browser” error.

![69902077-BDB0-4087-9E85-6F401F81B8FB](https://user-images.githubusercontent.com/17312341/74516679-5f63ca80-4f43-11ea-89ee-056f82f8082b.png)

Reproducible on Safari (Mic permissions ON), Firefox for iOS, and even the Common Voice app.

Not reproducible when the user was logged out.

**Comment by AigizK** [comment]
@MichaelKohler 
I solved a similar problem on my project with this library: 
https://github.com/ai/audio-recorder-polyfill
DEMO:
https://ai.github.io/audio-recorder-polyfill/

**Comment by MichaelKohler** [comment]
Recording via mobile Safari on iOS is now implemented, and the native app is being decommissioned. https://discourse.mozilla.org/t/updates-to-common-voice-for-ios/58909
