### ISSUE TITLE
"Download" button has placeholder "${Language}" in its label when site is viewed in German

### ISSUE THREAD

**Issue by theHacker** [mozilla/voice-web#2573]
**Reproduction steps**
- Open "Datasets" in German (https://voice.mozilla.org/de/datasets)
- Click the button "Zum Download E-Mail-Adresse eingeben"

**Actual**
The download button has `{$Language} herunterladen` as a label.

**Expected**
The download button uses the language chosen in the dropdown for the label.
For example `Englisch herunterladen` or `Deutsch herunterladen`.

**Screenshot**
![mozilla-voice-bug-language-button](https://user-images.githubusercontent.com/7399011/75101522-f5e85980-55dd-11ea-8f0a-7c37b2271603.png)

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. I've added a fix as a suggestion here: https://pontoon.mozilla.org/de/common-voice/web/locales/en/messages.ftl/?string=195019 . I hope somebody will accept it :)

**Comment by MichaelKohler** [comment]
This is now fixed. Thanks for reporting!
