### ISSUE TITLE
Enable new locale Venecian (vec) on staging + production

### ISSUE THREAD

**Issue by peiying2** [mozilla/voice-web#2586]
The locale is 100% complete: https://pontoon.mozilla.org/vec/common-voice/. Please enable it at the next code push. Thank you!

**Comment by MichaelKohler** [comment]
PR for this repo here: https://github.com/mozilla/voice-web/pull/2589
PR for Sentence Collector: https://github.com/Common-Voice/sentence-collector/pull/302

Sentence Collector has been deployed and users now can select that in their profile and start to add sentences.
