### ISSUE TITLE
Maximum Width should be applied to the Text Area in the Report Section

### ISSUE THREAD

**Issue by aryamanpuri** [mozilla/voice-web#2587]
**Describe the bug**
On expanding the Text Area in the report section , there should be certain maximum limit .

**To Reproduce**
1. Go to https://voice.mozilla.org/en/speak
2. Click the report button in the bottom
3. Check the `Other` checkbox 
4. Expand the Text Area

![Screenshot from 2020-02-26 22-39-57](https://user-images.githubusercontent.com/43513114/75370022-7a8eec80-58ea-11ea-84ac-295eb6e10c55.png)

** Expected behavior**
There should be a certain maximum width to write the report .

**Additional Behaviour**
@phirework @MichaelKohler Let me know, I would like to work on it.

**Comment by MichaelKohler** [comment]
Given that the dialog has a fixed width, I'd say this is very reasonable to do.

**Comment by aryamanpuri** [comment]
@MichaelKohler Can I work on this ?

**Comment by MichaelKohler** [comment]
I'd say so. There is a small chance there is a reason not to do that, but in the end I'd say this makes sense. However, please don't be mad at me if this ends up not being wanted :)

**Comment by aryamanpuri** [comment]
Yes I guess this makes sense , as there is fixed dialog width , and the user do not want to scroll horizontally everytime the text is more than that  633px.

**Comment by aryamanpuri** [comment]
Solved in #2604
