### ISSUE TITLE
Local dev: "./config-helper"' has no exported member 'getSecrets'

### ISSUE THREAD

**Issue by rileyjshaw** [mozilla/voice-web#2612]
On my local devserver, I'm seeing: 

```
src/main.ts(1,21): error TS2305: Module '"./config-helper"' has no exported member 'getSecrets'.
```

Should be an easy fix – it looks like it's got to do with the config changes over the past few days. Logging it here for Monday.

**Comment by manishkr1101** [comment]
@rileyjshaw I am using [docker setup](https://github.com/mozilla/voice-web/blob/master/CONTRIBUTING.md#docker-setup) on my local machine and not getting any such error. 
I am able to launch homepage.
Does this still persist to your local devserver
