### ISSUE TITLE
Unexpected language change in the website

### ISSUE THREAD

**Issue by kdalkafoukis** [mozilla/voice-web#2614]
### Description

The language of the website changes after using auto-fill from chrome with english(uk) selected language.

- preselected language for the website **english**
- Browser **chrome**

### Steps to reproduce

1. Go to https://voice.mozilla.org/en/datasets

![image](https://user-images.githubusercontent.com/4775609/76154793-6dd47a80-60da-11ea-9595-8a2e73b43c13.png)

2. In the email text field choose an email with uk language

![image](https://user-images.githubusercontent.com/4775609/76154900-03bcd500-60dc-11ea-9625-2dc74f3d8af8.png)

3. the result is the language to automatically change to polish even though the selected language is english

![image](https://user-images.githubusercontent.com/4775609/76154807-a70cea80-60da-11ea-8842-49babbaffd6d.png)

My apologies if the issue is irrelevant with the website.

**Comment by MichaelKohler** [comment]
I could reproduce this, very interesting. United Kingdom -> UK -> uk (Ukranian)? The same also happens with a German (de) address for example

**Comment by MichaelKohler** [comment]
@mbransn I assume that is not intended, right?

**Comment by mbransn** [comment]
Nope, not intended. Thanks for flagging @kdalkafoukis -- were you able to download the language you intended?

And to confirm, the website is triggered to localize to the language tied to the auto-complete email address (EN -> UK) ; the dataset language selected to download does not change (remained as EN).

@ovidiuboca1 are you able to reproduce?

**Comment by MichaelKohler** [comment]
> And to confirm, the website is triggered to localize to the language tied to the auto-complete email address (EN -> UK) ; the dataset language selected to download does not change (remained as EN).

Yes, the dataset language does not change, just the UI language.

**Comment by ovidiuboca1** [comment]
@mbransn 
I tested this and I can reproduce it on Windows 10, Mac OS 10.14 with Chrome browser.

**Comment by phirework** [comment]
Is the language code in the URL changing when you hit autocomplete? Or does the URL still say `/en/datasets` and you're just looking at Polish/German/whatever somehow?

**Comment by ovidiuboca1** [comment]
The language code in the URL is changing. If I select Romanian the URL will be https://voice.mozilla.org/ro/datasets

**Comment by phirework** [comment]
Cool, we'll try to get a fix for it in this sprint. Thanks for reporting @kdalkafoukis!

**Comment by phirework** [comment]
My apologies for never circling back on this but was fixed a few sprints ago! The issue had to do with Chrome's autocomplete changing our language state if there was a country attached to the email address that you're autocompleting with. Thanks again for the report + troubleshooting.
