### ISSUE TITLE
Build stats page

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#262]
* how many total recordings
* how many hours
* how many people contributed
* how many validated sentences

**Comment by orschiro** [comment]
There should be an individual stats page or section on your profile. Otherwise I lose interest as a contributor if I don't have any data or information about the impact and effect of my contribution. 

What is being done with it? How do my contributions fit into the bigger picture?

**Comment by joshua-montgomery** [comment]
I feel the same way, we need to create some feedback that shows:

1. What is the goal - how many do we need?  I hear Google used 33,000 hours of data to train English.  Do we need this much data for each language?  Lets set a goal for each language, then have a party ( virtual or otherwise ) when our community reaches the goal.

How are my contributions relative to other contributors based on sign up date (i.e. how am I progressing over time relative to other people who are playing ).

I think it is more important to show users how they are progressing over time rather than their total contribution.  If someone has 200 hours of audio and I only have 0.5 that is demotivating.  If I see that they added 0.25/day and I am adding 0.30 per day then that is great.

**Comment by orschiro** [comment]
A good example that comes to mind is Google maps. It's called local guide.
They give you challenges, points, badges and metals and unlock features
like becoming a reviewer or getting free Google drive space.

**Comment by mikehenrty** [comment]
Hi both, thanks for your thoughts here. We do have some plans for an individual profile page that includes things like achievements and stats. See our spec:
https://mozilla.github.io/voice-web/docs/specs/index.html

That said, we are still deciding how to implement that and what to work on first, so your feedback is super helpful.

This bug however is more for us to have a meta-dashboard to quickly see how far along everyone's contributions are towards our ultimate goal of 10K hours for english (other languages to follow soon).

**Comment by orschiro** [comment]
@mikehenrty on what can I give my feedback?

On the Spec Export page you linked to, I have a lot of slides in the sidebar to choose from. Which one is the one you meant?

**Comment by mikehenrty** [comment]
@orschiro you can give your feedback on anything you would like, both in the app and on the specs, by filing github issues. The feedback I was mentioning was what you had already given in this bug.

For the spec, I was actually referring to the overall experience and not any single slide. That said, there is a slide called "Achievements" which can give you some information about the achievements piece.

**Comment by SirCmpwn** [comment]
There should also be a big progress meter on the home page, showing the total hours recorded up to the goal of 10,000, plus the total hours of audio verified. If we get there we should also break it down into goals per demographic, like 10,000 hours of male/female samples and samples in each accent.

**Comment by mikehenrty** [comment]
If there are any UX'ers reading this bug, we'd love some help coming up with what this page would look like. Otherwise you will have my design, which will be very bad :)

**Comment by orschiro** [comment]
@mikehenrty let's take yours first and then we improve. :-)

**Comment by Djfe** [comment]
how stats could look like: (rather how the graphs look)
https://location.services.mozilla.com/stats

**Comment by Gregoor** [comment]
@danielsjf (over in #1491)

> As already mentioned on the side in #1381, it would be helpful to have a statistics page for a number of reasons.
> 
>     * We might spot outliers like in #1458 more quickly.
> 
>     * It helps to educate people where the important contributions are.
> 
>     * It is quite useful as an initial data check for people that will use the data.
> 
> 
> As you can see below, some of these statistics are already available elsewhere. This is not an exhaustive list. Rather some things I thought of at the moment that could be interesting.
> 
>     * General statistics
>       
>       * Number of sentences
>       * Number of hours recorded
>       * Number of hours validated
>       * Number of hours invalidated
>       * Number of speakers
>       * Number of accents
>       * Individual word count (above 5000? Could be biased for some languages with combined words)
>       * Number of recordings not in the sentence data (these are the corrected sentences)
> 
>     * Ratios (this is mostly here to educate)
>       
>       * Average number of reads per sentence (plus a recommendation of it being below three?)
>       * Percentage of validated recordings by the largest contributor (lower than 10%?)
>       * Percentage male/female
>       * Percentage per age group
> 
>     * Table with same information as above, but grouped by subset (train, validation and test)

**Comment by MichaelKohler** [comment]
I think it's worth looking at this again, maybe we could provide some of this data on the dataset download page?

**Comment by mbransn** [comment]
@MichaelKohler all of the use cases outlined here are captured in scoping documents for community metrics dashboard needs and some of the basic data points are already live on the site as part of the stats dashboard. Closing as the original intent of this ask was met by the introduction of stats to the site in 2018.
