### ISSUE TITLE
name of Bashqort language wrong

### ISSUE THREAD

**Issue by jonorthwash** [mozilla/voice-web#2646]
(I'm not sure where to file this issue, so if this isn't the right place, could someone help me?)

Pontoon lists the Bashqort language (`bak`) as "Bashkirs".

This is probably a mistake in clipping the Russian name, башкирский.  In English, it's the plural of the colonial demonym, somewhat like saying "Eskimos" instead of the name of a particular language.

This mistake is potentially offensive, so should probably be fixed quickly.

**Comment by MichaelKohler** [comment]
Looks like this is the language name overall in Pontoon, not just for Common Voice: https://pontoon.mozilla.org/ba/

@peiying2 can you help here?

**Comment by peiying2** [comment]
I can help resolve this. @jonorthwash could you point me to a website to confirm this? What we have right now if from Wikipedia. I can't just add a language without some reference material. Thank you!

**Comment by peiying2** [comment]
We can always reach out to the two contributors to the project right now to confirm one way or another.

**Comment by jonorthwash** [comment]
> @jonorthwash could you point me to a website to confirm this? What we have right now is from [Wikipedia](https://en.wikipedia.org/wiki/Bashkirs).

That page appears to be for (and again, the word "Bashkirs" refers to) the ethnic group, not the language.  The Wikipedia page on the language is [here](https://en.wikipedia.org/wiki/Bashkir_language).

You'll note that the page that you linked to does mention the endonym Bashqort, though the language page only lists it as the endonym through transcription.

A source for the name might be [Ethnologue](https://www.ethnologue.com/language/bak).  They seem to prefer Bashkort (as the more "English-looking" form of the indigenous name), but they do list Bashqort as an alternate spelling.

**Comment by jonorthwash** [comment]
![Screenshot from 2020-03-26 19-42-18_modified](https://user-images.githubusercontent.com/963849/77706938-22571300-6f9a-11ea-8a54-d2f103631b05.png)

**Comment by jonorthwash** [comment]
![Screenshot from 2020-03-26 19-44-47](https://user-images.githubusercontent.com/963849/77706992-44e92c00-6f9a-11ea-8266-1c50f4bc0310.png)

**Comment by jonorthwash** [comment]
![IMG_20200326_194902](https://user-images.githubusercontent.com/963849/77707271-0607a600-6f9b-11ea-8fba-fc1542310e58.jpg)

From Nicholas Poppe (1964) - Bashkir Manual.

**Comment by jonorthwash** [comment]
It appears that a whole bunch of localisations blindly used the "English" name too :(  It might be best to unapprove any translations that are simply "Bashkirs" or similar.  I've gone through and suggested corrections to a couple based on Wikipedia, but I'm not really qualified to be offering suggestions for most of those languages.

**Comment by IlnarSelimcan** [comment]
"Bashkirs" is clearly wrong as the name of the language. Should be either "Bashkir" or "Bashqort". I'd go with "Bashqort", since "Bashkir" is how the language is called in Russian, whereas "Bashqort" is the endonym.

My native language is Tatar, which is a language closely related to and mutually intelligible with Bashqort.

**Comment by jonorthwash** [comment]
> "Bashkir" is how the language is called in Russian

Russian is the conquering/coloniser/settler language, in this situation—a situation Mozilla should probably try to be sensitive to.

**Comment by fitojb** [comment]
This issue should be moved to the mozilla/pontoon repository.

**Comment by peiying2** [comment]
Let's keep the issue here as it is primarily a CV project issue.

@jonorthwash @IlnarSelimcan Could you let me know the following:
- Could you agree on which language name to use?
- Is the script ok or should it be changed to Latin? (Right now it is in Cyrillic)
- Would either one of you are going to contribute to the language? Right now we have two contributors but neither has translator or manager access so their work is left as suggestion.
- Would either of you be willing to discuss the change of the language name with the two contributors? I can send an introduction. 

There are languages we currently have that use different writing systems for the same language (Punjabi in India vs Punjabi in Pakistan, for example), but so far we have contributors from India so we keep it in one script. This is another wrinkle need to iron out.

**Comment by peiying2** [comment]
I have changed the name in Pontoon to `Bashkir` for now.

**Comment by IlnarSelimcan** [comment]
> Let's keep the issue here as it is primarily a CV project issue.
> 
> @jonorthwash @IlnarSelimcan Could you let me know the following:
> 
>     * Could you agree on which language name to use?

My choice: "Bashqort" @jonorthwash ?
> 
>     * Is the script ok or should it be changed to Latin? (Right now it is in Cyrillic)
> 

Cyrillic is right.

>     * Would either one of you are going to contribute to the language? Right now we have two contributors but neither has translator or manager access so their work is left as suggestion.

I've written to Bashqort Wikipedians and rnuriev1 has also signed up on Pontoon and started translating there. He is a long-time admin of Bashqort Wikpedia and has a very good command of the Bashqort language. Imo, he certainly can be given rights to approve the translations.

Alternatively, now that I have someone who can oversee my Bashqort translations and whom I can consult, I can  serve that role.

> 
>     * Would either of you be willing to discuss the change of the language name with the two contributors? I can send an introduction.

I'll send an email right away and also ask whether rnuriev1 is ok with managing the translatios.
 
> 
> 
> There are languages we currently have that use different writing systems for the same language (Punjabi in India vs Punjabi in Pakistan, for example), but so far we have contributors from India so we keep it in one script. This is another wrinkle need to iron out.

**Comment by AigizK** [comment]
@peiying2 @jonorthwash @IlnarSelimcan 
Hi, i'm first people, who began to support bashkort's language in https://pontoon.mozilla.org/. The official name of my republic is Bashkortostan. It is official government site https://pravitelstvorb.ru/en/
BASHKORT is the correct name for the language.

About script - Cyrillic is correct and we have additional letters: ә,ө,ҡ,ғ,ҫ,ҙ,һ,ң,ү

>>Would either one of you are going to contribute to the language
Yes, I'm going to do it. At this point, I'm assembling a team and dealing with financial issues. 

>>but neither has translator or manager access so their work is left as suggestion.
Give me those rights, please.

**Comment by jonorthwash** [comment]
> About script - Cyrillic is correct and we have additional letters: ә,ө,ҡ,ғ,ҫ,ҙ,һ,ң,ү

@AigizK, you mean "additional" letters beyond *Russian* Cyrillic.  Cyrillic is more than just Russian though :)  Please don't let Stalinist language policy make you think that that the Bashqort alphabet is just a permutation of the Russian alphabet....  The Russian alphabet itself is a permutation of "true" Cyrillic, whatever that means.

> My choice: "Bashqort" @jonorthwash ?

> BASHKORT is the correct name for the language

My preference is for Bashqort, but if @AigizK prefers the Russian-intermediate transliteration of "Bashkort", that's probably okay too.  I use the former spelling in my academic work, though.

**Comment by AigizK** [comment]
@jonorthwash 
Before the USSR, the Bashkirs used Latin script. On the translation, I consulted with two scientists. They are Bashkir by nationality. They said it's already customary to translate bashkir. But if you want to highlight how it sounds in this project, you have to write BASHQORT.
So I refuse the Bashkort option. And let it be either Bashqort or Bashkir.

**Comment by peiying2** [comment]
Thank you @AigizK, @jonorthwash and @IlnarSelimcan thanks for getting back to me. Looks like we need to decided between Bashqort or Bashkir. I will close this issue and send an email to include current contributors so you can collectively decide who is the manager, and who can be a translator - there is a documentation on the roles and responsibilities. @jonorthwash what is your email address if you want to participate in the conversation?

**Comment by jonorthwash** [comment]
> @jonorthwash what is your email address if you want to participate in the conversation?

jonathan.n.washington [æʔ] gmail [dɑʔ] com
