### ISSUE TITLE
Hitting "save" or "submit" buttons should give visual response feedback

### ISSUE THREAD

**Issue by orschiro** [mozilla/voice-web#267]
1. Go to https://voice.mozilla.org/profile
2. Edit your profile
3. Click on "Save"

It doesn't provide you with any feedback. Thus you don't know if it actually saved your changes.

**Comment by pathaktejpal** [comment]
yes, +1 for it. I clicked about 5 times on save and after that, i just refreshed a page to find it does save our data but no confirmation.

**Comment by angelawyman** [comment]
This could use feedback or confirmation such as: a message like "Great! or Success! your profile has been updated" , a form reset, a plus sign changed to a check mark, etc. I clicked Save about 3 times, too.

**Comment by orschiro** [comment]
Another case I found is "submit". Sometimes I press "submit" and it just takes a few seconds for the page to show me the next sentences. However, because I don't get any feedback on the process, I tend to click again because I think I haven't properly pressed the button. This completely screws up the submission.

![image](https://user-images.githubusercontent.com/170947/28501889-d24b402c-6fe5-11e7-8032-a4d09e4e679d.png)

**Comment by orschiro** [comment]
Love the new visual response to submitting your sentences!

![peek 2017-07-27 06-07](https://user-images.githubusercontent.com/170947/28654107-02ab08ac-7292-11e7-9045-13b4c699d04d.gif)

**Comment by mikehenrty** [comment]
Whoops, meant to close this one when I submitted the above change.

https://github.com/mozilla/voice-web/commit/c84ce400f03030a463bdc813dd3cd11516bad3b2
