### ISSUE TITLE
'Sorry, there was an issue' text recommendation for misheard commands

### ISSUE THREAD

**Issue by Githubuxer** [mozilla/voice-web#2676]
When Firefox Voice doesn't hear a proper audio command, it says 'Sorry, there was an issue' with a red exclamation mark below. Shouldn't it be something more casual like 'I did not hear that, please try again' or simply 'Please try again', or 'Can you repeat that'

The text 'Sorry, there was an issue' makes it seem like a technical issue vs just needing the user to repeat or speak a command.

**Comment by MichaelKohler** [comment]
This is not the correct repo for Firefox Voice. Please keep using firefox-voice-feedback.herokuapp.com as you have before. Thanks for your feedback!
