### ISSUE TITLE
Failed commands and feedback loop suggestion.

### ISSUE THREAD

**Issue by Githubuxer** [mozilla/voice-web#2677]
When commands fail or do nothing, no information is being communicated to the user as to why nothing happened, other than just showing the checkmark and the words but not performing any subsequent action.

There needs to be a better voice command feedback loop that explains why nothing happened, explains what happened, or suggests how to make something happen.

**Comment by MichaelKohler** [comment]
This is not the correct repo for Firefox Voice. Please keep using firefox-voice-feedback.herokuapp.com as you have before. Thanks for your feedback!

**Comment by Githubuxer** [comment]
My apologies, thanks Michael
