### ISSUE TITLE
on profile page please add other countries in english accent

### ISSUE THREAD

**Issue by pathaktejpal** [mozilla/voice-web#268]
Hi guys, I am from India and when I checked profile page I wanted to select Indian English. but it's not present and saw many other countries are also not present. so please if you can add it.

thank you.

**Comment by dmateusp** [comment]
Some other significant European accents aren't there either, not sure a dropdown would be enough but rather a Search

**Comment by pathaktejpal** [comment]
this kind of drop down will be best.
this will contain all the countries and let them allow to search for it inside drop down itself.

http://phppot.com/demo/dropdown-with-search-using-jquery/

**Comment by Omniscimus** [comment]
Not including non-English accents was a conscious choice, see issue #242.

But I agree that Indian English should probably be in the list.

**Comment by kdavis-mozilla** [comment]
I agree the lack of a India and South Asia accent is s bug.

**Comment by kdavis-mozilla** [comment]
Added pull request in PR #270

**Comment by mikehenrty** [comment]
We now have India & South Asia in the drop down. Thanks for the suggestion everyone!

**Comment by mikehenrty** [comment]
and thanks @kdavis-mozilla for the fix!
