### ISSUE TITLE
Why validate sentences?

### ISSUE THREAD

**Issue by orschiro** [mozilla/voice-web#269]
What's the reason why people have to validate sentences?

I would assume that people are capable of reading a short single sentences the way its written.

Why would I thus have to validate their sentence?

Or is the purpose more to ensure that what they said is actually understandably acoustically?

**Comment by lopis** [comment]
Because of griefing? People can read *if they want* but pranksters are bound to show up and ruing the party for everyone else.

**Comment by orschiro** [comment]
Fair point. I didn't think of trolls. Thanks!

**Comment by mikehenrty** [comment]
Not just trolls, sometimes people have microphone issues, and sometimes people forget to "unmute" their microphone. Sometimes people submit after not recording anything.

So it's like you said, we need to make sure a human can understand the recording before we can expect a computer to do so.
