### ISSUE TITLE
Missing Polish Dataset download option

### ISSUE THREAD

**Issue by kwasnydam** [mozilla/voice-web#2702]
Hey there at Mozilla and thank you for this dataset! Recently it seems you have released Polish language. 
![Screenshot from 2020-04-30 13-16-24](https://user-images.githubusercontent.com/32868095/80704496-f244e780-8ae4-11ea-82e0-fdc99ec16a48.png)

However, when I go to https://voice.mozilla.org/en/datasets and go through the `Lanugage` droplist I cannot find `Polish`. Is it because it is still not ready for a public release or is it missing by mistake?

**Comment by MichaelKohler** [comment]
Polish was enabled on Common Voice around 4 months ago: https://github.com/mozilla/voice-web/pull/2524/files#diff-8c75a07172bee459bac9400f5ecfb950R33 (mid of January)

The data from the current release is based on what we had on 2019-12-10, and therefore Polish was not part of that. I'd expect it to be part of the next release though.

See also https://discourse.mozilla.org/t/polish-dataset-download/52707

**Comment by kwasnydam** [comment]
Great, thank you for a quick answer and pointing me to the relevant thread, cheers :>
