### ISSUE TITLE
Launching the Odia (language code: or) language for speak and listen

### ISSUE THREAD

**Issue by psubhashish** [mozilla/voice-web#2715]
Though the Common Voice Languages page shows that 2684 out of 5000 sentences have been reviewed, all the sentences (5784) have been reviewed and validated on the Sentence Collector. Localization is also 100% done. Can I request for updating the data on the Common Voice portal and move Odia to the "Launched"? 🙏
<img width="729" alt="Screenshot" src="https://user-images.githubusercontent.com/1258090/81541975-91919680-9391-11ea-8136-46c8da8b9d3c.png">

**Comment by MichaelKohler** [comment]
This will be done once https://github.com/mozilla/voice-web/pull/2714 is merged and released.

**Comment by psubhashish** [comment]
Awesome. Thanks for this very quick update, Michael.

**Comment by soumendrak** [comment]
@MichaelKohler , #2714 is closed now. Can we please look into this PR now? Thanks.

**Comment by phirework** [comment]
Hello! The release went out this morning and Odia is now available for contribution on the platform. Thanks for your patience. 

https://voice.mozilla.org/or/speak

**Comment by soumendrak** [comment]
Thanks a lot @phirework and @MichaelKohler .
