### ISSUE TITLE
Code snippet/icon missing for ‘add to homescreen’ on iOS

### ISSUE THREAD

**Issue by Githubuxer** [mozilla/voice-web#2718]
Code snippet/icon missing for ios ‘add to homescreen’ function.

It’s great that voice is now a website to reduce app development issues and user install issues, but the code snippet and icon is missing to make it look like an app on iOS, which is very easy to implement:

https://www.create.net/support/adding-an-ios-home-screen-icon-for-your-website

This is what it currently looks like:

![image](https://user-images.githubusercontent.com/62911518/81934179-87071500-95bc-11ea-81b7-59632ef0a997.jpeg)

**Comment by phirework** [comment]
Hello! Thanks for reporting this. Are you actually able to record when you open the site from the homescreen app? In our testing we found that only opening it in a regular instance of Safari directly worked, it's possible we overlooked something.

**Comment by Githubuxer** [comment]
Are there any free open source screen recording apps that are safe to use? It just opens right to the website and you can press the microphone button.

**Comment by phirework** [comment]
Your iPhone should have screen recording natively, but you might have to [add it to the control center](https://support.apple.com/en-us/HT207935) if it's not already there, to easily get to it.

Once you've recorded those clips, are you then also able to play them back? If you tap on any of the numbers once you've recorded on it, a little control tray should pop up.

**Comment by Githubuxer** [comment]
I was able to open it and record/play it back to ensure it heard my voice. 


Download “IMG_6909.MP4” with Firefox Send: simple, safe file sharing https://send.firefox.com/download/d64ad6282ffd58eb/#18skwopMV9WC2C8vfqr54A

**Comment by phirework** [comment]
Awesome, thanks for the confirmation, we'll definitely look into it.
