### ISSUE TITLE
Flag potentially offensive content.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#272]
We should another button to the validation screen that allows users to flag content as being offensive. Offensive content should not be shown again for validation until we manually go through it.

**Comment by Omniscimus** [comment]
What if a troll spends a couple of hours clicking 'offensive' though? There would be too much flagged content to review, and the system might run out of recordings for legitimate users.

**Comment by mikehenrty** [comment]
That's a good point @Omniscimus, but let's deal with that problem when we get to it. There are some things we can do around heuristics that could make the process for less manual, but from what I've seen so far, trolls are a very small population of our users right now.

**Comment by nmstoker** [comment]
Assuming each piece is validated by multiple people, you could possibly find a way to mitigate the troll impact by treating later flaggings as a lower priority (after all, if two independent people first listened to it and didn't flag it as offensive, then chances are a later flag is less likely to be genuine)

Also flagging more than a certain threshold in a period clearly suggests a troll (although it's possible they're just unlucky), so you could then simply offer a polite please come back later notice or you could send them a manually verified record and only continue with them if they get that right. But as @mikehenrty says maybe it's not worth this complexity yet...

**Comment by mikehenrty** [comment]
I haven't heard this myself, but I know of people reporting very sexual content in some of the recordings. This is a feature I think we will need to implement, but I agree it is non-trivial (especially the moderation part).

**Comment by Gregoor** [comment]
@mikehenrty should we then maybe look at putting it into the new contribution experience (with low priority), since we already have sentence flagging in there?

**Comment by mikehenrty** [comment]
@Gregoor In the new contribution experience we have a "flag" icon on the "Listen" flow. What do you think is missing from that to fix this bug?

**Comment by Gregoor** [comment]
@mikehenrty oops, pardon. Had a knot in my brain. I should've posted all this in https://github.com/mozilla/voice-web/issues/890 as we don't have flagging in recording (i.e. for flagging sentences) in the new contribution experience.

**Comment by mbransn** [comment]
@mikehenrty @Gregoor I'm looping in @georai here. We'd like to understand what parameters are included in the reporting process to better build out a flow. Essentially: what happens when a user clicks '[Report](https://projects.invisionapp.com/share/3UG9HFKGSFC#/screens/296610230)', what are you hoping to understand technically? E.g.; This could open a modal that provides some checkbox or dropdown driven feedback and submit...but what type of feedback? :)

**Comment by grailean** [comment]
@mikehenrty @Gregoor Here is the invision link for this issue: https://invis.io/SAMVA4M3E7F#/296610225_Listen_1_Active

**Comment by grailean** [comment]
Screenshot reference: https://www.dropbox.com/s/7pcsgc4bh63xt6f/Screenshot%202018-10-03%2014.01.56.png?dl=0

**Comment by mbransn** [comment]
Thanks @georai -- appreciate the work here. 👍 @mikehenrty take a look when you get a chance and holler with any thoughts.

**Comment by mikehenrty** [comment]
Awesome work @georai ! No flags from me on the visuals.

For the "Flag" options, my initial thoughts are:

* offensive content
* grammatical/spelling error
* wrong language
* other

cc @mbransn , @Gregoor

**Comment by mikehenrty** [comment]
> should we require a comment if 'other' is selected from the options?

My vote would be yes.

**Comment by mikehenrty** [comment]
another one I just thought of:

* sentence too long

We only allow contributors 10 seconds to speak certain sentences, and if a sentence takes much more than that to read, it becomes unusable. Contributors should be able to report that situation.

@mbransn @grailean

**Comment by dabinat** [comment]
I feel like abuse is starting to become a problem now. A few weeks back I had to weed through 60 or so recordings of racial slurs. Today I’ve had loads of racial slurs again and also a woman who tells random stories about her life instead of reading the text.

Can the reporting function be bumped up the priority list? Then if a speaker gets x number of reports from a certain number of users in a certain amount of time the system automatically rejects any remaining recordings from them.

**Comment by mbransn** [comment]
Thanks @dabinat we hear you and acknowledge that this is an issue. We've struggled to find prioritization time for it based on our healthy backlog and need to press forward with project feature growth / dataset integrity. All of that said @LRSaunders4 @Gregoor and I have had discussions re: bringing this up in priority. Thanks for the patience, good news is we have UI for it! This is an implementation exercise at this point which will require work across the stack. Stay tuned!

**Comment by Gregoor** [comment]
Reporting is now live!
