### ISSUE TITLE
Pre-trained model files for Common Voice

### ISSUE THREAD

**Issue by amilkh** [mozilla/voice-web#2733]
We want to train a speech recognition machine learning model to predict age, gender, and ethnicity based on the speaker's voice. Common Voice seems like the best dataset for this!

Is there any pre-trained model files we can use to do transfer learning on top of?
Or a simple command-line tool to do the above task?

**Comment by nukeador** [comment]
Hello amilkh,

This repo is to report issues with the common voice site, for question about machine learning models, please post it on Deep Speech discourse

https://discourse.mozilla.org/c/deep-speech/247

Thanks!
