### ISSUE TITLE
Add a new collumns to the dataset: reported for reason X

### ISSUE THREAD

**Issue by stefangrotz** [mozilla/voice-web#2734]
Since the reported sentences have never been removed for most languages and the reports itself could be valuable information for the training,  the best solution for now to give people the chance to use this information would be to include it into the dataset. 

The reports could almost work as a tagging system, for example "Offensive language"

So my proposal is to add these columns to the dataset (in the tables validated.tsv,...) 

- Reported_for_offensive_language
- reported_for_gramar_spelling_error
- reported_for_different_language
- reported_for_ difficult_to_pronounce
- reported_for_other (maybe we should keep this one out because it makes only sense with the additional text, and this could be problematic)

This field could contain the number of reports for a given sentence (many sentences are reported again and again since they don't disappear from the website)

What do you think about this?

EDIT: This would only work for sentences reported during validation. Sentences that are reported during recording need some more thoughts.

**Comment by nilabja-bhattacharya** [comment]
I am a new contributor, I would like to work on this, let me know which files to check?

**Comment by phirework** [comment]
Hello! The new dataset release now includes a tsv file for each language that lists all of the reported sentences for that language :) This is just a straight export of all the reports for that language which covers reports both during recording and validation, and you'll have to do a bit of filtering yourself to see # of reports for each sentence. https://voice.mozilla.org/datasets

**Comment by stefangrotz** [comment]
That's a great solution! Thanks.
