### ISSUE TITLE
Limit of 28 validations in target segment too simplistic

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#2738]
I fully agree that validating an endless stream of repetitive one-word recordings would be tedious, however I think the current solution of limiting it to 28 validations may not be the best solution to the problem.

I don’t want to do more than 28 repetitive validations _in sequence_ but I am more than happy to do more than 28 over a longer period of time.

So perhaps a better solution would be a certain number per day or week, rather than a hard limit that lasts forever?

**Comment by nukeador** [comment]
Can you move this conversation to discourse?

https://discourse.mozilla.org/t/help-create-common-voices-first-target-segment/59587/

We will be checking with the Firefox Voice team soon and might be able to come with their recommendation on how much to collect.
