### ISSUE TITLE
Record HTML tags?

### ISSUE THREAD

**Issue by wischi-chr** [mozilla/voice-web#274]
I got some html tags (a title) and a doctype definition to record. Is that done on purpose?

**Comment by mikehenrty** [comment]
No, that's a bug! Please give us a screenshot if you see it happen again.

**Comment by wischi-chr** [comment]
Sadly I've no screenshot, but I'm pretty sure it's related to issue #271 because the content of the title tag was _**HTTP Error 503 - Service unavailable**_

**Comment by dmarto** [comment]
Here are 2 screenshots from few minutes ago. You can advance thru the html of the response by trying to re-record the sentence. 

![screen shot 2017-07-18 at 11 15 31 pm](https://user-images.githubusercontent.com/1244744/28337749-57914662-6c0f-11e7-8f7b-5c1c53998a16.png)
![screen shot 2017-07-18 at 11 20 18 pm](https://user-images.githubusercontent.com/1244744/28337893-bbff0e90-6c0f-11e7-8d7b-0c7e1313c4b4.png)

**Comment by kdavis-mozilla** [comment]
@dmarto Interesting. I wonder if this is a result of the auto scaling group starting/stopping servers and a request going to a server that isn't ready/is shutting down.

**Comment by mikehenrty** [comment]
Weird stuff! Probably related to #288, but even so we should put some better error messaging there.
