### ISSUE TITLE
German Single World "Hei" to "Hey" 

### ISSUE THREAD

**Issue by jofish** [mozilla/voice-web#2747]
As per the discussion in Discourse https://discourse.mozilla.org/t/help-create-common-voices-first-target-segment/59587/21, in the Single Word corpus, let's replace the German "Hei" with "Hey".

**Comment by mbransn** [comment]
@phirework assigning to you and adding to Jira for sprint 29.

**Comment by rileyjshaw** [comment]
This has been fixed and will go out with our next release on Tuesday, June 9.
