### ISSUE TITLE
Trailing slash handling redirects to wrong URL

### ISSUE THREAD

**Issue by ObjectBoxPC** [mozilla/voice-web#2753]
https://voice.mozilla.org/en/ redirects to https://voice.mozilla.org/en/voice.mozilla.org/en which doesn't seem correct. I believe this is due to the fix for #946: The redirect URL does not include the scheme (the header is `Location: voice.mozilla.org/en`) so it's interpreted as a relative URL instead of an absolute one.

**Comment by phirework** [comment]
Thanks for the report! This will be fixed in the next release.

**Comment by phirework** [comment]
This has been fixed on prod. Thanks for flagging!
