### ISSUE TITLE
Words of the first target segment are not showing for Basque and Esperanto

### ISSUE THREAD

**Issue by Txopi** [mozilla/voice-web#2754]
If I visit voice.mozilla.org to collaborate with Basque language, I see the message in the header of the website announcing the creation of the first target segment. When I enter the speak page I should see the Basque words for numbers and yes/no, but I get the standard Basque sentences instead: https://voice.mozilla.org/eu/speak
The same happens at least with Esperanto: https://voice.mozilla.org/eo/speak

**Comment by phirework** [comment]
Thanks for flagging this! This should be fixed. Can you confirm?

**Comment by Txopi** [comment]
> Can you confirm?

Yes, it works now. Thank you!

**Comment by stefangrotz** [comment]
The manager for basque have to confirm it before it gets published. His name is julen you can find him in this list here: https://pontoon.mozilla.org/eu/common-voice/contributors/

**Comment by Txopi** [comment]
I'm sorry but that string's state is Translated, not Unreviewed.

**Comment by stefangrotz** [comment]
You are right, sorry I did not check this. The translation was imported a while ago:
https://github.com/mozilla/voice-web/commit/f0a55d0dc0dbf2379a67d3c07e0b0e3ce19833f3

AFAIK the master branch from GitHub gets released every two weeks or so, always on Tuesday if I remember correctly. It took a while until it was visible for Esperanto too.

**Comment by Txopi** [comment]
Finally this issue has been fixed on deployment. Thank you!
