### ISSUE TITLE
Adding a CC0 1.0 licensed voice database for Odia

### ISSUE THREAD

**Issue by psubhashish** [mozilla/voice-web#2760]
There are two main categories on Wikimedia Commons that list more than 4000 audio recordings of pronunciations of words ([here](https://commons.wikimedia.org/wiki/Category:Lingua_Libre_pronunciation-ory_and_ori) and [here](https://commons.wikimedia.org/wiki/Category:Audio_files_created_using_Kathabhidhana)). It would be useful to bring those recordings on Common Voice as the license is compatible (CC0 1.0) and they can be validated on Common Voice. Though these are recording of words and not sentences, they are mostly from a 1930 Public Domain lexicon called Purnachandra Ordiya Bhashakosha and words used on Wikipedia articles, and hence have a wide variety domains. Many words (and phonemes) that might not be recorded on Common Voice can be found from those recordings. This is a request that I made when Michael Henretty was around as he was helping a lot in building the initial foundation of Common Voice (per his recommendation I, as the copyright holder of the recordings, made a request on Commons to relicense all the audio files under a CC0 1.0 license). Would really appreciate if this can be added to the workflow for importing those audio from Wikimedia Commons to Common Voice.

**Comment by psubhashish** [comment]
Tagging some of the usual suspects @nukeador @MichaelKohler @phirework as this seems to have gone under the radar. Is there anything that I might have missed and need to share with you?

**Comment by nukeador** [comment]
Hello,

Sorry for missing this out, but we are not tracking github for this kind of conversations (only for technical issues with the site). Can you please open it up on Common Voice discourse so we bring visibility to the conversation?

https://discourse.mozilla.org/c/voice/239

Thanks!

**Comment by phirework** [comment]
Thanks for tagging and this idea! Just a quick note that as Common Voice is currently set up now we cannot accept CC-BY licensed content, because all of the data we have is republished under CC0 and we cannot enforce the attribution requirements. If you meant that you made a request to relicense all of the audio under **CC0** (not 1.0), then definitely bring that up to Discourse and we will see if we can integrate that.

**Comment by psubhashish** [comment]
Thanks @nukeador: will create a thread there on Discourse then. @phirework these audio files are all under CC0 (and not CC-BY) license.
