### ISSUE TITLE
inificient compression

### ISSUE THREAD

**Issue by reniermin** [mozilla/voice-web#2769]
When unpacking the English data set the 38Gb .tar.gz file was unpacked to only 12 Gb

**Comment by phirework** [comment]
Hello, thanks for reporting this. Can you tell me how many files you were able to unpack? There should be approx 45gb of clips in the tarball.

**Comment by reniermin** [comment]
Yah when I unpacked there were only 11Gb of mp3 files in the clips folder

**Comment by phirework** [comment]
Can you tell me: 

* The number of clips in the folder
* What operating systems you're on
* What you're using to unzip?

Thanks!

**Comment by reniermin** [comment]
So there's around 300,000 clips reported on gnome file explorer. I'm using
Mankato Linux just using the default archive manager.

**Comment by phirework** [comment]
Hmm, I'm not able to replicate this bug and we haven't heard any other users report missing files. There should be ~1million files in that archive. 

Can you try extracting the file on the command line? E.g. 

```
tar -xvzf en.tar.gz
```

**Comment by reniermin** [comment]
Ok, I just unpacked the folder and the problem is solved. Thanks for all
the help

**Comment by phirework** [comment]
Thanks for reporting back!
