### ISSUE TITLE
[speak] Add feature to skip a sentence

### ISSUE THREAD

**Issue by rongjiecomputer** [mozilla/voice-web#278]
In recording voice section, user will record voices for three random sentences, review them and redo some of them before sending all three recordings.

However, as a non-native English speaker, some times I will encounter a sentence with word(s) that I just can't get them right. I do like skip the sentence entirely instead of sending an obviously broken recording.

This feature is also useful as I now see certain sentences repeatedly.

**Comment by jdittrich** [comment]
> However, as a non-native English speaker, some times I will encounter a sentence with word(s) that I just can't get them right.

I had the same problem and also wished to skip

**Comment by monkeyfish99** [comment]
Yeah, I have the issue of names, mostly, and I fear I'm butchering them, which would throw off training data.

**Comment by mikehenrty** [comment]
see also #407, which is about skipping validations

**Comment by Gregoor** [comment]
@SimonHFrost over at #407:
>I could take up this task if nobody else is already looking at it. 
>
>I would add a skip button similar to in the screenshot here:
>
>![screen shot 2017-12-07 at 21 06 20](https://user-images.githubusercontent.com/877992/33736610-89f82a64-db93-11e7-93ff-ca5f82f11967.png)
>
>Once you reach the confirmation, the sentence you’ve skipped would simply not appear in the list, and not get sent to the backend when confirming.
>
>There would be an edge case when a user skips all three sentences, then I’d show perhaps a new button that says ‘Get new sentences’, and navigate back.
>
>Does that sound good?

The flow I had in mind was to get a new sentence instead. So you'd still submit 3 sentences, but could request new sentences any time (no idea about design on that yet though).

**Comment by SimonHFrost** [comment]
That works too 😄 

I could open a PR with a placeholder button for 'retrieve new sentence', or should I wait for some design approval?

**Comment by m-branson** [comment]
@Gregoor @SimonHFrost can we pause on adding or removing anything to the user flow just yet? I would welcome more UI exploration at this phase. This is a great example of a feature request that we should prototype and test before adding to production. Timeline for that would be after the Service Design experience workshop in JAN, we're looking to prioritize UX and feature updates based on the results of that work.

cc @mikehenrty

**Comment by Gregoor** [comment]
We've added it to the [new contribution experience](http://voice.allizom.org/en/speak)* which will be on production soon.

* This links to staging on which clips are not collected. It's only for testing purposes.
