### ISSUE TITLE
L10n issues

### ISSUE THREAD

**Issue by SafaAlfulaij** [mozilla/voice-web#2783]
Untranslatable:

https://github.com/mozilla/voice-web/blob/cd745fd49a8dc7862a7717aaaa4e26fefe84b10d/web/src/components/pages/dashboard/goals/custom-goal-steps.tsx#L180

Needs plural:

https://github.com/mozilla/voice-web/blob/e70863b1224c86224e88b6f2174712b9b924041f/web/src/components/pages/dashboard/goals/custom-goal.tsx#L181

https://github.com/mozilla/voice-web/blob/e70863b1224c86224e88b6f2174712b9b924041f/web/src/components/pages/contribution/success.tsx#L124

https://github.com/mozilla/voice-web/blob/e70863b1224c86224e88b6f2174712b9b924041f/web/src/components/pages/contribution/contribution.tsx#L368

https://github.com/mozilla/voice-web/blob/e70863b1224c86224e88b6f2174712b9b924041f/web/src/components/pages/contribution/contribution.tsx#L485

https://github.com/mozilla/voice-web/blob/e70863b1224c86224e88b6f2174712b9b924041f/web/src/components/pages/contribution/success.tsx#L151

https://github.com/mozilla/voice-web/blob/e70863b1224c86224e88b6f2174712b9b924041f/web/src/components/pages/dashboard/goals/custom-goal-steps.tsx#L121

https://github.com/mozilla/voice-web/blob/e70863b1224c86224e88b6f2174712b9b924041f/web/src/components/pages/dashboard/goals/custom-goal-steps.tsx#L194
(This one is hard)

**Comment by bacharakis** [comment]
Hi, @SafaAlfulaij can you please give me more information about the issue here?
What are the exact L10n issues?

**Comment by SafaAlfulaij** [comment]
Hi!
First one is an untranslatable string, I think it's obvious that it shoud be wrapped in a `Localized` tag and added to the ftl file.

Others are plural strings that are not marked as plural. Check this PR please: https://github.com/mozilla/voice-web/commit/b88002f1ef91aecf218c4bf80232607a06053e91

The last one is pretty hard as it contains 4 plural parts in one sentence. Normally people would divide the plural parts each in a string, and join them using another string. For example "{num_apples} apples and {num_oranges} oranges" would be 3 strings: **"{num_apples} apples"** (plural), **"{num_oranges} oranges"** (plural), **"{apples} and {oranges}"** (normal). Not sure what the best soulution here is though.

Thanks!

**Comment by NanaKay007** [comment]
Hello @SafaAlfulaij ,
thank you for submitting this. My name is Nana: I'm a student working with the design team and I was assigned this issue;
After taking a very close look, I think all of the pluralization issues you highlighted are not really issues; pluralization will be necessary if the number variable used in each message string is <= 1, however that is not the case in all reasonable edge cases. For example, the n-clips id used in the custom goals page (that basically asks users to contribute a number of clips per week etc) looks like this

<img width="407" alt="105 clips" src="https://user-images.githubusercontent.com/32800421/86810508-fba18180-c04a-11ea-8f20-5dc3bea4aedb.png">

In this case, it wouldn't be reasonable to ask a user to contribute "0 clip" or "1 clip" per week,daily etc. 

It's pretty much the same pattern with the other issues you highlighted. I looked at every instance in which each localization id was used and arrived at this conclusion. 

Kindly let me know if I'm missing something. Thank you :)

**Comment by SafaAlfulaij** [comment]
Hi @NanaKay007 !
Wish you the best :)

Well, that's true for English and some other languages, since there are languages that have +3 forms, please take a look here: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals
Check the examples section for better... examples.

> **Polish**
> seconds=sekunda;sekundy;sekund
> minutes=minuta;minuty;minut
> hours=godzina;godziny;godzin
> days=dzień;dni;dni

**Comment by NanaKay007** [comment]
Oh right. I think I understand now. I'll check in with @phirework to see what the next steps are. Thanks for your time! :)

**Comment by NanaKay007** [comment]
@SafaAlfulaij I consulted my mentor; since it would be difficult to implement solutions for the various pluralization cases for other languages, would a "one/other" solution - as used in the PR you referenced - suffice?

**Comment by SafaAlfulaij** [comment]
@NanaKay007 If you notice that the PR is chaging only the FTL file. Pontoon is smart enough to notice that this is a plural form, and provide the proper forms for it, and Fluent is smart as designed to choose the form depending on the number.
Check https://www.projectfluent.org/fluent/guide/selectors.html to get a better idea.

**Comment by NanaKay007** [comment]
@SafaAlfulaij Perfectly understood. Thanks for clarifying this.
