### ISSUE TITLE
Automatically change language of tops

### ISSUE THREAD

**Issue by deevroman** [mozilla/voice-web#2786]
When switching the language in the header, the language of the tops does not change, although it would be more convenient and logical if it did.  

![CommonVoiceFeature](https://user-images.githubusercontent.com/25708359/85627472-384aa180-b677-11ea-8397-62eb8e02153f.gif)

**Comment by phirework** [comment]
Thanks for reporting! This was included in the [sprint 31 release](https://github.com/mozilla/voice-web/releases/tag/release-v1.31.0).
