### ISSUE TITLE
Automatically crop silence at the beginning and end of recordings before validating

### ISSUE THREAD

**Issue by a3nm** [mozilla/voice-web#279]
When presenting sentences to the user for validation, it would be better to process them to automatically crop silence at the beginning and end of the recording. I suppose that this shouldn't be too hard to do in software, and it would save time when validating (avoid having to wait through silence).

An added benefit is that this would make it possible to automatically filter out recordings that are not sensible because they consist only of silence (I've seen this happen). If the length of the record after having removed silence is too short then the recording could be discarded without asking for user validation.

**Comment by mikehenrty** [comment]
good idea, looks like this guys work could be useful here: https://petewarden.com/2017/07/17/a-quick-hack-to-align-single-word-audio-recordings/

**Comment by Djfe** [comment]
and Auto delete/don't accept completely empty recordings.
I just came across a 1/3s long recording of nothingness ^^

**Comment by mikehenrty** [comment]
Hi @Djfe, thanks for your suggestion. We now automatically block uploading clips that are too silent. However, there still could be some old clips in our database from before that silence check. So it's technically fixed, but we will still see the bugs sometimes.
