### ISSUE TITLE
Width of the percentage is wrong

### ISSUE THREAD

**Issue by Sav22999** [mozilla/voice-web#2790]
**Describe the bug**
The pertentage in "Progress" (Stats) go out of the container

**To Reproduce**
1. Go to https://voice.mozilla.org/en/dashboard/en/stats or https://voice.mozilla.org/en/dashboard/it/stats (or also https://voice.mozilla.org/it/dashboard/en/stats, https://voice.mozilla.org/it/dashboard/it/stats)
2. Click on "Stats", then selct a language (in my case Italian or English)
3. See error

**Screenshots**
![immagine](https://user-images.githubusercontent.com/32335378/85921604-9c3eb700-b87d-11ea-8da0-dd171b558ec7.png)
![immagine](https://user-images.githubusercontent.com/32335378/85921573-5eda2980-b87d-11ea-93b2-151cd03601e8.png)

**Desktop or Mobile (please complete the following information):**
 - OS: Windows / Linux / Android
 - Browser: Firefox (Dev Edition)
 - Version: 78.0b9

**Comment by bacharakis** [comment]
Thanks for the report @Sav22999 . Are you facing this issues in Windows, Linux, and Android as well?

Thank you

**Comment by Sav22999** [comment]
Yes. This is on Android ![Capture+_2020-06-30-19-19-49.png](https://user-images.githubusercontent.com/32335378/86156837-d7075000-bb06-11ea-9514-17cfbdb01190.png)
