### ISSUE TITLE
Cannot choose language in Dashboard for Italian on mobile

### ISSUE THREAD

**Issue by Sav22999** [mozilla/voice-web#2791]
**Describe the bug**
"Your language" and the select-box is not visible in mobile website for Italian language

**To Reproduce**
1. Go to voice.mozilla.org/it/dashboard
2. See error (You cannot chabge language)

**Expected behavior**
It should show the select-box

**Screenshots**
![Screenshot_20200627-140022.png](https://user-images.githubusercontent.com/32335378/85921778-eaa08580-b87e-11ea-92a5-316da82f1a3c.png)

**Desktop or Mobile (please complete the following information):**
 - OS: Android
 - Browser: Firefox and Firefox Preview
 - Version: 68.9.0

**Comment by phirework** [comment]
Hello, thanks for reporting this! Where are you expecting to be able to select language, in that screenshot you posted? If you click on your profile pic, does a menu like this show up?

<img width="390" alt="Screen Shot 2020-06-30 at 18 29 38" src="https://user-images.githubusercontent.com/582683/86183286-b091e680-baff-11ea-8217-2099345edd47.png">

**Comment by Sav22999** [comment]
@phirework there you change the language of the website, not the language of statistics. It should appear like this screenshot (it's from another device)

![Screenshot_20200701-014406.png](https://user-images.githubusercontent.com/32335378/86187582-6844e980-bb3c-11ea-8ce3-82e918a02e72.png)

**Comment by phirework** [comment]
Ahh got it, thanks for the clarification!

**Comment by phirework** [comment]
Thanks for reporting! This should be fixed with [release 31.0](https://github.com/mozilla/voice-web/releases/tag/release-v1.31.0).
