### ISSUE TITLE
Clips I’ve already validated reappear again

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#2792]
I’ve been getting a problem over the last few days where clips I validate reappear for validation again in the queue. Some clips I will vote on and then they appear for validation again a mere 5 or 6 clips later.

At first I wasn’t 100% sure that they weren’t just ones that I skipped and forgot, but it has now happened frequently enough that I can confirm it is definitely occurring on clips I voted on.

Also, maybe it only occurs on clips I vote yes on? I need a bit more data to confirm if that’s definitely the case.

**Comment by bacharakis** [comment]
Hi @dabinat and thank you for your message. 
On which language you are experiencing that?

Also, can you please share a few setences that re-appear? Thank you
