### ISSUE TITLE
Counter of sentences recorded & weekly goal counter for Odia (language "or") show zero "0"

### ISSUE THREAD

**Issue by psubhashish** [mozilla/voice-web#2798]
**Describe the bug**
Counter of sentences recorded for Odia (language "or") shows zero -- "0" -- and the weekly goal counter also does not change from yesterday's recording.

**To Reproduce**
1. Go to 'https://voice.mozilla.org/en/dashboard/or/stats' when logged on
2. Click on 'Help us get to 1,200'
3. Record five sentences
4. Again go to 'https://voice.mozilla.org/en/dashboard/or/stats'. The counter shows the number of clips recorded from the previous day's record and shows zero "0" for "Today's Common Voice progress on clips recorded". I have logged out, logged on again, and even have checked https://voice.mozilla.org/or from a private window and the total number of sentences recorded today shows zero.

**Expected behavior**
The counter for the week (if a target is set) and the number of sentences recorded for today should show accurately.

**Screenshots**

<img width="602" alt="Screen Shot 2020-07-01 at 8 56 14 PM" src="https://user-images.githubusercontent.com/1258090/86263089-5c116880-bbde-11ea-8488-c2b95ca14ffd.png">

**Screenshot**: _Counter showing no changes from yesterday_

<img width="749" alt="Screen Shot 2020-07-01 at 8 56 03 PM" src="https://user-images.githubusercontent.com/1258090/86263102-62074980-bbde-11ea-960d-7a73f7a595d7.png">

**Screenshot**: _Post-recording, the % of recorded sentences for today remains same after recording 20 or so sentences._

**Desktop or Mobile (please complete the following information):**
 - OS: [MacOS]
 - Browser [Firefox]
 - Version [77.0.1]

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: Blue Yeti USB mic
 - Model:

**Additional context**

**Comment by psubhashish** [comment]
#2799 Also reports about the same issue

**Comment by phirework** [comment]
Hi all - I think this is a symptom of something that we notice happening when people have the Common Voice website open for a very long time without refreshing or changing the tab, because then when we do a code release, your browser is still using an old version of the frontend to send data to a new version of the backend. Can you confirm if that's something that would apply here? If yes, the fix for it is to hard refresh and try submitting clips again, and the stats should start showing up.

**Comment by phirework** [comment]
Never mind, we've identified a different potential source for the bug. We're investigating, will follow up when we have more info!

**Comment by psubhashish** [comment]
Oh great. The answer, for what it's worth, is no. As I've mentioned I logged out and logged in (so certainly not the case of keeping it open for long on a tab). I also tried it yesterday and recorded some (by opening in a new tab and I closed after recording) but the issue persists. Thanks for investigating the issue.

**Comment by phirework** [comment]
We pushed a fix for this last night, can you verify if your stats are available now?

**Comment by psubhashish** [comment]
It's working now. Thanks again for pushing it on a priority.
