### ISSUE TITLE
Make it impossible to validate a sentence without having listened to it first

### ISSUE THREAD

**Issue by a3nm** [mozilla/voice-web#280]
I misclicked on the "Yes!" button to validate a sentence before I had listened to it, and apparently the system took this into account. I think it would be better if the system didn't allow the validator to click "Yes!" or "Nope." before having listened to the sentence to be validated.

**Comment by mikehenrty** [comment]
Duplicate of #212.

**Comment by a3nm** [comment]
OK, sorry for the duplicate and thanks for closing.

**Comment by mikehenrty** [comment]
No problem! Duplicates are like votes for the original bug, so it's useful. Thanks for all your contributions @a3nm !!
