### ISSUE TITLE
Preload next sentence when validating

### ISSUE THREAD

**Issue by a3nm** [mozilla/voice-web#281]
When validating a sentence, there is a delay before the next one is displayed for validation, presumably because the system is submitting feedback on the previous sentence and retrieving the next sentence.

It would be better if there were no delay. This could be achieved by submitting the feedback on the previous sentence in the background, and preloading the next sentence in the background while the previous sentence is being validated.

**Comment by paskalito** [comment]
Also in terms of "kinda gamification" it would be nice if it yould be a neverending interface.

something like.
4+x lines: (best read from bottom to top)

*** sentences get constantly uploaded (in case upload is slower than new sentences new lines appear, maybe at line 10 or so theres a warning / forced stop till the uploads clear out again.
*** the just recorded  sample to review and possibility to rerecoard
*** Curent active line you need to record ( of course started and stopped with "space" (enter for next sentence))
*** Next sentence that had already be loaded

i think that would make the experience for th user very seamless, keeping them longer on the site generating more data.
also very compatible concept for swiping on smartphones

as i just discovered a timeshift in recording on my phone (s3 on firefox lineageOS 7) (first theres a too long silence, but recording stops too early) ( compared to my action and also the "getting red" on the UI)

next superusefull stepp would be no key hitting at all, just starting litening mode, i read out the sentence, the software recognizes i have done so cuts silence before and after and presents me the next sentence to read. so i can just read sentences to it. - finish.

i would rather like a cc-sa licence btw.

hope my visions come true :) - i really hope folks from voxforge, librivox, mycroft and also now mozilla get togheter and produce something usable. with all the data already available i think its more the work of combining everything that needs to be done than actually more samples. (but it's of course a very good tool to have that theres now a tool again like this an in html5 :) )

**Comment by Gregoor** [comment]
Now a few sentences are always preloaded. It's not quite instant, but it's close.

**Comment by jf99** [comment]
@Gregoor Sentences are indeed being preloaded now. It seems as if the preloaded sentences aren't used however. When pressing Yes/No, the web page always loads a new mp3 file and the UI doesn't refresh until it has been loaded. I have checked it with Firefox's web developer tools. All files are loaded twice. Once during preloading and once after clicking Yes/No. Tested with Firefox ESR 52.5.3 (64-bit) on Arch Linux.

**Comment by Gregoor** [comment]
@jf99 In the dev tools you should see that the second request actually hits the cache. Unfortunately that still leads to a bit of a delay in FF (in Chrome it feels instant). The sentences that are loaded after pressing yes/no are the ones after the next sentence, which you can see when inspecting the payload of the requests.

**Comment by jf99** [comment]
@Gregoor Thanks for the quick answer and sorry for my late response. I didn't have the browser cache enabled, so I couldn't observe caching. However, with caching enabled there is still something fishy. Have a look at the video I made. Many audio files are still loaded twice. Even weirder, sometimes the same file has different sizes.


[voice-validation.mp4.zip](https://github.com/mozilla/voice-web/files/1671346/voice-validation.mp4.zip)

**Comment by jf99** [comment]
@Gregoor Have you seen my last comment? This is still happening. The sentences load instantly, but I think there's still some bandwidth wasted, unless I'm misinterpreting the debugging output of Firefox.

**Comment by Gregoor** [comment]
@jf99 thanks for notching me again, I did indeed miss it. Sorry about that!

Interesting catch! I could indeed reproduce it in FF, Chrome and Edge. It always happens for the first request and then every couple ~30. Given that it happens across browser and no amount of spacing between caching seems to change that behavior, I think that behavior is inteded by spec. Maybe related to Range-Request. But I don't quite grok it yet. If I find the time in the next weeks, I'll do some more reading on it.
