### ISSUE TITLE
UX: Icon for re-record in review looks like "close". 

### ISSUE THREAD

**Issue by jdittrich** [mozilla/voice-web#286]
**Problem:**  The ✕ icon for "re-record" the review view, where you can re-listen and submit your recordings looks like "delete" or "close". 

**Solution:** 
* Make it look like the symbol for "record" ●
* Since there is no standard icon for **re**-record, [it might be better to write it out instead ](http://uxmyths.com/post/715009009/myth-icons-enhance-usability)

(related to #278 since it can be assumed that ✕ allows to exclude the recording from the submission.)

**Comment by ruchita20** [comment]
I dont see an assignee on this issue. 
Looking to contribute to UX for this project. 
Can I take this up? 

Thanks
Ruchita

**Comment by mikehenrty** [comment]
Sounds great @ruchita20! Unfortunately, I don't have much input into how to fix this issue except to say that I agree this is a problem. I know @jdittrich is also a UX expert, so perhaps you can use this gh issue to collaborate and arrive at a good solution. I'll be here if you need me, and I'll make sure your work makes it in the final product 👍

**Comment by jdittrich** [comment]
> you can use this gh issue to collaborate and arrive at a good solution.

…here my visualized suggestions: 

1. Change the icons like this:

![grafik](https://user-images.githubusercontent.com/3416487/28482928-037b4fb0-6e6b-11e7-8545-486ea11615d5.png)

2. Change the text on top of the row of Play from ~~Play/Stop~~ to *Play/Pause* (since that reflects its behavior)

3. Change the back arrow in the record step: 

 Currently it looks like: 
![grafik](https://user-images.githubusercontent.com/3416487/28483024-78226006-6e6b-11e7-8890-8630ea25c041.png)

It should look like: 
![grafik](https://user-images.githubusercontent.com/3416487/28483182-30c7bf34-6e6c-11e7-9472-6b5eebe08a68.png)

So the arrow looks less like the "redo" for the current step. But feel free to make the arrow a bit fatter, this was the first one I found.

**Comment by m-branson** [comment]
Thanks for your UX/UI input here @jdittrich! We're currently assessing and aggregating updates for our next round of UX iteration and will indeed be including your language and icon suggestions. (Also note, the back arrow may change a bit, but will be an icon that is distinct from 'redo' in previous screens.) Cheers and thanks again.

cc @mikehenrty

**Comment by elahmo** [comment]
Working on this one :)

**Comment by mikehenrty** [comment]
This is being handled in various broken out bugs. Since @elahmo fixed the undo arrow in https://github.com/mozilla/voice-web/commit/0cbfa132d55575d975fea3756d48081bec70966c, we will close this one.
