### ISSUE TITLE
Document sentence source

### ISSUE THREAD

**Issue by lucaswerkmeister** [mozilla/voice-web#287]
It would be nice to know where the sentences that are being read come from – not necessarily for any one particular sentence, but at least the collected sources for all sentences together. As far as I can tell, this information isn’t currently available – even in git history ([`server/data` commits](https://github.com/mozilla/voice-web/commits/master/server/data)), only the last one (e969b19b3b266976ee184caf2af3a08afed7f60a) records the source in the commit message (and there seem to be several works titled “The Alchemist”).

**Comment by mikehenrty** [comment]
Good idea @lucaswerkmeister! Right now we really only use War of the Worlds and The Alchemist, but we will add more shortly. Any suggestions on where we should track this?

**Comment by lucaswerkmeister** [comment]
Perhaps in the FAQ, as long as the list is short enough?

**Comment by angelawyman** [comment]
Hunh, Where does the text "Can I get woot woo" come from? Are you taking new book suggestions as currently War of the Worlds and the Alchemist text are heavily male pronoun biased.

**Comment by DeathCamel57** [comment]
I added links for the source text files with all of the phrases to the FAQ page.

**Comment by angelawyman** [comment]
Great!! That clears it up to their origin. Glad to see "You don't know shame until you drunkenly confuse Hellen Keller and Anne Frank in a game of charades." was removed. What year is the 'funny' texts from? There are references to "Mrs Butterworth", "I can't believe its not butter", "Hamburger Helper" and "I have to check with the Mrs!". That's the 70's, right?

**Comment by lucaswerkmeister** [comment]
This doesn’t answer the question, though. It’s nice to see the full list of sentences, but the files don’t document the sentence sources.

**Comment by mikehenrty** [comment]
> What year is the 'funny' texts from? There are references to "Mrs Butterworth", "I can't believe its not butter", "Hamburger Helper" and "I have to check with the Mrs!". That's the 70's, right?

Yeah, I agree these are not good. I'll remove them all today.

**Comment by mikehenrty** [comment]
I removed all the problematic ones I could find in https://github.com/mozilla/voice-web/commit/c5fd185c3ec67bd91090ae0ec9770bee65f009f5. If you find more, please file a new issue for that and I will remove them.

**Comment by DeathCamel57** [comment]
#330 Should cover it now.

**Comment by mikehenrty** [comment]
We now document the source text in our faq thanks to #330.
