### ISSUE TITLE
Audio doesn't load on Firefox 54, Ubuntu 16.04

### ISSUE THREAD

**Issue by 0b10011** [mozilla/voice-web#289]
# Steps to reproduce

1. Load https://voice.mozilla.org/listen with Firefox 54 on Ubuntu 16.04
2. Click the play button

## Expected outcome

Audio should play.

## Actual outcome

No audio plays. The console shows that the audio doesn't load (`audio/mpeg` tries to load twice?). Copy of console output:

```
Invalid URI. Load of media resource  failed. listen
HTTP “Content-Type” of “audio/mpeg” is not supported. Load of media resource blob:https://voice.mozilla.org/6fc3a7cc-9e39-4ac6-85a0-9256f32c0683 failed.  listen
HTTP “Content-Type” of “audio/mpeg” is not supported. Load of media resource blob:https://voice.mozilla.org/39dcc400-53d8-4dce-908a-e4a0388526ea failed.  listen
Cannot play media. No decoders for requested formats: audio/mpeg, audio/mpeg  listen
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  listen
```

**Comment by Omniscimus** [comment]
I found [this Ubuntu help page](https://help.ubuntu.com/community/RestrictedFormats) which states that Ubuntu does not come with an MP3 decoder by default. Does installing the `ubuntu-restricted-extras` package fix the issue for you?

**Comment by iGEL** [comment]
I actually run Firefox 54 on Ubuntu 16.04 and have no audio problems. `ubuntu-restricted-extras` is not installed here, but `gstreamer1.0-plugins-bad` & `gstreamer1.0-plugins-ugly` are.

**Comment by 0b10011** [comment]
Installing `gstreamer1.0-plugins-bad` with `sudo apt install gstreamer1.0-plugins-bad` adds support for `audio/mpeg`.

However, I would argue that it would be better to use a format (even if only as an alternative) that works on Ubuntu+Firefox by default.

**Comment by Gregoor** [comment]
More in #999
