### ISSUE TITLE
What statement is "10,000 hours" (FAQ) referring to? [non-technical]

### ISSUE THREAD

**Issue by sirlantis** [mozilla/voice-web#292]
In the FAQ there is a separate section with a headline:

> Why is 10,000 hours the goal for capturing audio?

This number isn't mentioned anywhere on the website. It's also not mentioned in the [blog post](https://blog.mozilla.org/internetcitizen/2017/06/19/commonvoice/).

Should this section be removed? Or were you planning on providing a progress counter somewhere on the page which got removed last minute?

**Comment by sirlantis** [comment]
Ah, found where it was mentioned 

https://twitter.com/mozilla/status/887356583696642049

**Comment by mikehenrty** [comment]
Hi @sirlantis, yeah that is definitely the number we are trying to hit. We are looking into building a counter in #262, so stay tuned!
