### ISSUE TITLE
Show error to user for invalid recordings

### ISSUE THREAD

**Issue by scilganon** [mozilla/voice-web#301]
For instance, we should warn user, if nothing was recorded.

**Comment by Kusaha** [comment]
Also it would be nice if the website would explain more clearly how you can re record things. Heard several recordings where people messed up the sentence and finished it with some profanity.

**Comment by mikehenrty** [comment]
> Also it would be nice if the website would explain more  clearly how you can re record things. Heard several recordings where  people messed up the sentence and finished it with some profanity.

Good point! Mind filing a separate bug for this?

**Comment by Kusaha** [comment]
Done -> #313

**Comment by mikehenrty** [comment]
We now put a warning in the console if the recording was silent, what's left is to display a message to the user when this happens, and not allow the recording to be submitted.

We are waiting on some designs from UX for this.

**Comment by Gregoor** [comment]
Those errors are now also shown to the user.
