### ISSUE TITLE
Recording view not vertically aligned when tapping "Donate your voice!" button

### ISSUE THREAD

**Issue by 5k9m** [mozilla/voice-web#311]
Hey,

when I scroll down to the "Donate your voice!" button on the home page, press it to be routed to the recording view, the view is not vertically aligned - so I have to scroll up to see the content (which can be annoying from a UX point of view). 

<img width="1486" alt="donate-button" src="https://user-images.githubusercontent.com/13706131/28452504-5767597a-6df3-11e7-8c59-26fe5d0e3d8f.png">
<img width="1487" alt="record-view" src="https://user-images.githubusercontent.com/13706131/28452503-5765c4e8-6df3-11e7-95db-f19770f63a5f.png">

My setup:
macOS Sierra 10.12.5
Opera 46.0.2597.46
Chrome 59.0.3071.115
Firefox 54.0.1

**Comment by mikehenrty** [comment]
We have some code that tries to scroll back to the top when navigating. I think we just need to make sure we do this when hitting the Donate button:

https://github.com/mozilla/voice-web/blob/c84ce400f03030a463bdc813dd3cd11516bad3b2/web/src/lib/components/pages.tsx#L264

**Comment by 5k9m** [comment]
Well, this seems to be a known issue with Preact: [https://github.com/developit/preact-www/issues/22](https://github.com/developit/preact-www/issues/22)

I'll look into this in the evening and report back if I'm able to find something.
