### ISSUE TITLE
Ask for user demographics in the recording flow.

### ISSUE THREAD

**Issue by SirCmpwn** [mozilla/voice-web#312]
Simple change would dramatically improve the quality of the dataset.

**Comment by mikehenrty** [comment]
Good call out. In our specs, we actually have collecting demographics in the first time contribution flow (similar to how you need to agree to the terms of service). Now it's just a matter of prioritizing and implementing it.

https://mozilla.github.io/voice-web/docs/specs/index.html#artboard14

**Comment by mikehenrty** [comment]
Our new specs allow users to enter demographics in the recording flow, let's use this bug to track that.
