### ISSUE TITLE
Apache app deployment

### ISSUE THREAD

**Issue by Omniscimus** [mozilla/voice-web#315]
To test a fix for an issue, I tried to set up the app on my web server. By following the instructions in the README, I got the website working on localhost:9000. However, I would like it on my Apache server to change some Apache settings, as [this file](https://github.com/mozilla/voice-web/blob/master/nubis/puppet/web.pp) seems to suggest. It looks like it should automatically redirect requests at the Apache server to port 9000, but that's not working for me. Does it need additional configuration to get the Nubis part working?

Files in nubis/ seem to suggest that the Apache server would use the /var/www/voice directory. I can configure Apache to use this, but would I need to place additional files there? Also, is a Ubuntu server a requirement? (since it chowns something as ubuntu:ubuntu)

I was trying to work on #103. If there's no easy fix due to server infrastructures / deployment / whatever then I'll just move on to another issue.

**Comment by gozer** [comment]
The nubis/ contents is specific to our internal Nubis deployment tool.

If all you are trying to do is add a header for CSP, have a look at:

https://github.com/mozilla/voice-web/blob/master/nubis/puppet/web.pp#L40

Where we are already setting up a couple.

**Comment by Omniscimus** [comment]
Yes I found that, but I couldn't test my fix. The CSP header should be as strict as possible but if it's too strict, things may break. I'll submit a PR anyway. Thanks!
