### ISSUE TITLE
She & Her in short supply on texts

### ISSUE THREAD

**Issue by angelawyman** [mozilla/voice-web#319]
Just from a random sampling  of texts I listened to 21 male pronouns, 0 female and 9 its  and another 10 references to King, guy, Englishman and boy. I'm not a statistician but I'm fairly certain this sampling is representative of the text.

Where are these texts from? I've seen 'Fatima' twice. The more of these I listen to or record the more I notice female voice is missing from pronouns.

Can we draw from another text?

**Comment by ardaozkal** [comment]
around ~20% of the pronouns I listened to were female pronouns. I agree that addition of texts that have a higher ratio of female pronouns would help.

**Comment by mikehenrty** [comment]
Totally agreed, and we would love some help with this! I'm going to copy my response to the topic you raised on discourse:

From the [discourse thread](https://discourse.mozilla-community.org/t/200-ways-to-hear-him-and-only-10-ways-to-hear-her/17301):

> Thank you for raising this important topic, and we appreciate your insight.
> 
> Totally agreed the text needs more diversity and representation. It has actually been quite hard for us to get good sentences because we want to release the voice data into the public domain, and so we need public domain source sentences. Since a lot of conversational text that is in the public domain is old movies and books, the language can be quite antiquated and biased. We are currently investigating using The Stanford Natural Language Inference (SNLI) Corpus, but there are some licensing issues we need to work through. See this github thread1 for more details.
> 
> In the meantime, we would love help expanding our sentence collection! If anyone public domain source suggestions, or if you have text you personally wrote and want to put in the public domain (as part of Common Voice), this would be very helpful to the project.

**Comment by ajaydee** [comment]
I made sure that I added female pronouns to my list of extra sentences. ;-)

**Comment by mikehenrty** [comment]
We are in the process of updating and refreshing our sentences by asking for donations in #341. In the meantime, I have removed all the old sentences, got some contributor text donations, and added some dialog from public domain movie scripts in which I went and changed the pronouns to be more evenly split. You can find the new sentences here:

https://github.com/mozilla/voice-web/tree/9130530c6c21cc53cd0925eb5adeab4a4c1dc8ce/server/data

I will keep an eye on this as we continue to grow our corpus.

**Comment by ftrotter** [comment]
As I posted on the other thread, the various public domain resources on women's health (i.e. Medline) are likely to use feminine pronouns more frequently. 

HTH,
-FT
