### ISSUE TITLE
Publish Android app on F-Droid

### ISSUE THREAD

**Issue by rugk** [mozilla/voice-web#320]
Please publish the Android app on F-Droid.

**Comment by mikehenrty** [comment]
Would love some help with this if anyone is familiar with F-Droid.

**Comment by rugk** [comment]
https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/ could help here.

**Comment by Omniscimus** [comment]
I can't find the app on the Google Play store, does it have a different name or is it not on there?

The Common Voice app is currently just a wrapper for the website. I'd say putting it in any app store in its current state wouldn't be very useful, because the user can get the exact same just by navigating to the website in their browser. It might be useful later on if the app gets additional features though.

The Common Voice app would probably be listed as having '[Antifeatures](https://f-droid.org/wiki/page/Antifeatures)' in the F-Droid store, because:

> Tracking – the application tracks and/or reports your activity to somewhere, either without your permission, or by default (i.e. you’d have to actively disable it)

Common Voice uses Google Analytics by default

> Non-free Network Services – the application promotes or depends entirely on a non-Free network service

The app uses Amazon cloud storage to save recordings.

**Comment by mikehenrty** [comment]
Yeah, we never released the Android app, because chrome and firefox on android both allow you to use the microphone on a webpage. The current safari doesn't expose the mic, so we wrote the iOS wrapper app as a workaround. The VC android app was just a quick prototype.

**Comment by rugk** [comment]
However, at least releasing this app on F-Droid, could also have some "marketing/advertising effect" as many users interested in FLOSS/"open data/things" likely look on F-Droid for new apps and they may notice your project there…

**Comment by est31** [comment]
Hi! F-droid developer here (and fan of the open voice project :)).

Sadly this app builds on gulp and such apps are not supported by f-droid (yet). See this issue: https://gitlab.com/fdroid/fdroidserver/issues/60

**Comment by Rudloff** [comment]
Hello,
I would be insterested in packaging your Android app on F-Droid (when it is ready).
We will need [tagged releases](https://github.com/mozilla/voice-web/releases) for this.

**Comment by rugk** [comment]
See the help article on how to [tag releases](https://git-scm.com/book/en/v2/Git-Basics-Tagging) your [releases](https://help.github.com/articles/about-releases/), so they can be seen [on GitHub](https://help.github.com/articles/creating-releases/).

**Comment by IzzySoft** [comment]
@mikehenrty any chance for the tags?

**Comment by Gregoor** [comment]
Haven't looked at it yet and we'd like to not have native app wrappers in the future (once safari has feature parity for what we need). Is there sth specific you're missing from the web app?

**Comment by IzzySoft** [comment]
@Gregoor that ^^ probably goes to @rugk – I'm just asking on behalf of F-Droid as we wait to respond to the packaging request (disclosure: I'm one of the F-Droid maintainers).

**Comment by rugk** [comment]
What? Are you just suggesting the web app?
That is not the solution, nor the question.

The thing is: You apparently have an Android app on Google Play.
As such, it should also be on F-Droid. For a FLOSS app, there is no reason to (only) be on Google Play.

**Comment by Gregoor** [comment]
Thanks for the clarification. I wasn't intending to say that it's not valid, just that it's not foreseeable that I'll invest time in it (apart from reviewing PRs if anyone is willing to take this on). And yes in the future we'll probably want the native apps to inform the users to use the webapp instead (we might not take them down though).

**Comment by IzzySoft** [comment]
@Gregoor and [tagging releases](https://github.com/mozilla/voice-web/releases) is investing too much time? Come on…

(as @Rudloff reported above, he'd be willing to package your app – all that's missing is you tagging releases)

**Comment by Gregoor** [comment]
As a one off kind of thing it wouldn't be too much effort, but as a process change it would be. And from my understanding we'd have to do that continually, wouldn't we?

**Comment by rugk** [comment]
Just for each release. Doing so is best-practise on GitHub anyway, so it would also help to document the source code.

**Comment by Gregoor** [comment]
Well, we do have a continuous release model, I think versioning numbers would be pretty arbitrary for us (no interface to semantically version against). I'm definitely happy to look at a PR that would automatically tag each commit, if that helps.

**Comment by Gregoor** [comment]
Can someone link me to the app on Google Play? It was news to me that we have it there and I also can't find it.

Also from Michael's last comment on this:

> Yeah, we never released the Android app

**Comment by Rudloff** [comment]
Hello,
I understand from https://github.com/mozilla/voice-web/issues/320#issuecomment-458651764 that your goal is to deprecate the Android (and only use a web app).
If so, I think we can close this issue and the F-Droid RFP.

**Comment by Gregoor** [comment]
Yes, that's very much the goal! The only reason for having an iOS app was a missing Safari API (MediaRecorder) which is in technical preview. Once that's out, we'll deprecate the iOS app.
