### ISSUE TITLE
grading test: Self-test with known samples user before letting him/her contribute

### ISSUE THREAD

**Issue by rugk** [mozilla/voice-web#322]
What about first asking the user about one or two sentences, whcih are already well known to the AI?
Then the AI should try to recognize the sentences and if it can't maybe let the user try again one time and afterwards just do not allow the user to contribute.
If the user passes the test he/she can just use the tool as anyone would.

This would a kind of introductory "grading test" just too confirm the people can actually speak English or so… (and don't try to read the sentences in their local language, whatever)

It may sound discriminating/bad to exclude users when they cannot speak English well enough, but would not it make the data better?
Also, I, as a non-native speaker itself, would actually feel relieved by such a test, as I really don't know whether I speak "well enough" and would just "pollute" the data. And I do not want to trust my self-evaluation here…
So such a small test could make one a bit confident and just assure one . I also think/hope that not many people fail in the test as it should be really basic. It must not even be shown, but can be done "transparently" without revealing that the first sentence is a test sentence (unless they fail). You don't want to scare contributors away…

**Comment by mikehenrty** [comment]
Thanks for the suggestion @rugk.

My thoughts are this: we actually want heavy accents in the database, with the hope that if we get enough of them the resulting voice recognition engine will be more robust and able to understand people.

I am also not sure if we have the technology for doing what you mentioned. We'd need a really low word error rate STT engine if we were to rely on the results.

@kdavis-mozilla any thoughts?

**Comment by rugk** [comment]
> we actually want heavy accents in the database

Aha, makes sense, interesting. You never mentioned this anywhere in the FAQ or so.

**Comment by mikehenrty** [comment]
At this point, we don't even have an STT engine in Common Voice, and we're not planning to add one (yet). If we ever do (or we start using the webspeech api), we'll re-examine this. For now, closing as WONTFIX.
