### ISSUE TITLE
Original text with errors

### ISSUE THREAD

**Issue by rugk** [mozilla/voice-web#323]
> And, tomorrow, his enemy would also be a part of that Soul.

Why has "Soul" a capital letter? Without context you can only guess, whether Soul is e.g. a city name or so or the real "soul" (aka mind/psyche/marrow)…

**Comment by emhoracek** [comment]
This (like a lot of the samples) is a quotation from [a novel](https://en.wikipedia.org/wiki/The_Alchemist_(novel)). So the author or translator chose to capitalize that word. I don't think it matters to how you pronounce it.

**Comment by mikehenrty** [comment]
Thanks for raising this issue, @rugk 

Yeah, like @emhoracek said, this is part of the source text and doesn't effect pronounciation so I think it's fine.
