### ISSUE TITLE
"Problems. Please try again later."

### ISSUE THREAD

**Issue by emhoracek** [mozilla/voice-web#325]
I was reviewing sentences today and saw this one:

<img width="836" alt="screen shot 2017-07-22 at 5 11 35 pm" src="https://user-images.githubusercontent.com/5353499/28494598-fae3fbe0-6f00-11e7-9845-7bab30451dff.png">

I hit "play", and the reader said, "Problems, please try again later."

Not sure how to gather debugging info for this, but here's the source of the "listen-box":

```
<div class="listen-box loaded">
  <div class="sentence-box">
    <b style="">What we asked them to read:</b>
    &lt;/head&gt;&lt;body&gt;
  </div>
  <div class="play-box">
    <b style="">What they said:</b>
    <span class="" aria-hidden="true" data-icon=""></span>
  </div>
  <div style="display: none;" class="delete-box">
    <span class="" aria-hidden="true" data-icon=""></span>
  </div>
  <div style="" class="vote-box">
    <a><span class="" aria-hidden="true" data-icon=""></span>Yes!</a>
    <a><span class="" aria-hidden="true" data-icon=""></span>Nope.</a>
  </div>
  <audio class="audio-box" preload="auto" src="blob:https://voice.mozilla.org/8d00d464-78de-9e42-b90b-68112e3b403b"></audio>
</div>
```

**Comment by Omniscimus** [comment]
Good find! :smile: This was caused by a bug in the recording section of the app (#274). It asked contributors to read this kind of sentence and some contributors actually did so. This should just be marked 'Nope.' for now.

Duplicate of #300.

**Comment by emhoracek** [comment]
@Omniscimus thanks!
