### ISSUE TITLE
Typo in funny.txt

### ISSUE THREAD

**Issue by DeathCamel57** [mozilla/voice-web#328]
Line 1 of [server/data/funny.txt](github.com/mozilla/voice-web/blob/master/server/data/funny.txt) is
> 'm all about those invisible cosmic connections that transcend time and distance.

An "I" should be added at the start of the line, so it reads as follows.
> I'm all about those invisible cosmic connections that transcend time and distance.

**Comment by DeathCamel57** [comment]
Will fork and pull.

**Comment by DeathCamel57** [comment]
Pull request sent in.
#329

**Comment by mikehenrty** [comment]
Fixed in https://github.com/mozilla/voice-web/commit/100d604588eaebd19f4eec9558eab737f467d563
