### ISSUE TITLE
[iOS app] Disable overscroll

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#33]
Right now you can drag the content of the webview up and down due to Safari's overscroll ability. Can we disable this in the app?

**Comment by mbebenita** [comment]
Addressed (partially) by https://github.com/mozilla/voice-web/commit/85f0aad4911cb06d70c2b1be7f10f3c01bd57d23

I'm not sure what happens if we have a scrollable element in the page. So for instance, the About page doesn't scroll, and probably should.

**Comment by mikehenrty** [comment]
We can make scrolling happen inside the app's DOM tree if we need to. Let's leave the top level scrolling disabled for now, and revisit if we can't work around it in the app.
