### ISSUE TITLE
Submitting extra sentences.

### ISSUE THREAD

**Issue by ajaydee** [mozilla/voice-web#333]
I've written a load of sentences for use in this project with an aim to include many technical words and names. Things like 'terminal', 'platinum' and 'wireless'.

Should I just link a pastebin, or is there another preferred method?

**Comment by mikehenrty** [comment]
Pastebin would work just fine :) Thank you @ajaydee !

**Comment by ajaydee** [comment]
Excellent. Here's a pastebin link:

https://pastebin.com/aFAbnT4z

If you want more, I'll make a new list.

**Comment by ajaydee** [comment]
I've just noticed that line 16 has a double 'the'. That might need things up.

**Comment by ajaydee** [comment]
Here's some more:

https://pastebin.com/TcMjCM7F

**Comment by mikehenrty** [comment]
This is great! Right now, I am looking into replacing our entire sentence set. If we can get to 1.5K sentences, I'm going to do it. So, the more you can submit the merrier!

**Comment by mikehenrty** [comment]
Alright, I've submitted a PR with your sentences.

> I've just noticed that line 16 has a double 'the'.

fixed.

I appreciate you sharing that part about the tower collapsing, but it's a little dark to read and so I hope you don't mind that I removed it.

> Michael opened a browser and navigated to an anonymous search engine.

haha

I'm going to open a new bug to try and get more people to contribute to this list of home grown text. I think it's really nice.

**Comment by mikehenrty** [comment]
@ajaydee, would you like attribution? i was thinking of putting your sentences in a file called `ajaxdee.txt`

**Comment by ajaydee** [comment]
Yeah, whatever you want. ;-)

**Comment by mikehenrty** [comment]
I put it here: https://github.com/mozilla/voice-web/blob/8e50fa0d1c71437f7d2e8b010214aefb7c2d0d63/server/data/ajaydee.txt

**Comment by angelawyman** [comment]
You know how they have hipster ipsum, this is kind of like that:
[](https://pastebin.com/A8yngLSr)

**Comment by angelawyman** [comment]
You know how their is hipster ipsum, this is kinda like that:
[https://pastebin.com/A8yngLSr]

**Comment by mikehenrty** [comment]
Great @angelawyman , yours are in too:

https://github.com/mozilla/voice-web/commit/dc506c1da91380b14c8fbc9057b6333dd7869a7b
