### ISSUE TITLE
Use already-existing Librivox recordings

### ISSUE THREAD

**Issue by MichaelNMaggs** [mozilla/voice-web#352]
(I've seen this mentioned elsewhere, but apparently there's no GitHub issue covering it).

In addition to asking people read public domain material for the first time, existing already-read material ought to be incorporated into the database.    All **Librivox.org** recordings are immediately available, as both the underlying text and the corresponding audio recordings are in the public domain.  There are a very large number of Librivox recodings, covering a wide range of material,  by a wide variety of readers, with many being of moderate-to-poor audio quality.  Just what is needed here, I think.

**Comment by jdittrich** [comment]
Maybe you saw it on #302 (Mine audio from Wikimedia Commons)

**Comment by mikehenrty** [comment]
Great idea, we will definitely explore including Librivox data when we publish our initial dataset on the site. Stay tuned!

**Comment by mikehenrty** [comment]
We will try to publish the Common Voice data and have links (or bundles to LibroVox). Thanks for the suggestion @MichaelNMaggs !
