### ISSUE TITLE
Sentences skipping during voice recording

### ISSUE THREAD

**Issue by MichaelNMaggs** [mozilla/voice-web#353]
During voice recording, sentences are intermittently shown which immediately disappear without any button being pressed. I haven't logged the exact frequency, but perhaps one in every 20 sentences or so.   Sentences which are skipped over in that way don't appear on the subsequent review screen.

**Comment by jf99** [comment]
I think this happens during high server load. When the user clicks the submit button, but nothing happens, he will click a second time. As a consequence, new sentences will be loaded twice (with a long delay in between).

**Comment by mikehenrty** [comment]
@MichaelNMaggs , I pushed an update to the upload page which changes how these sentences are loaded. Are you still seeing this issue?

https://github.com/mozilla/voice-web/commit/c84ce400f03030a463bdc813dd3cd11516bad3b2

**Comment by MichaelNMaggs** [comment]
I no longer see the problem. Thanks.
