### ISSUE TITLE
Collect Noise

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#354]
It would be useful to collect noise from a variety of sources in order to train algorithms to remove it. Using the Common Voice app seems like an interesting way to do this, it would probably require some changes to the copy on the website and may be tricky to shoehorn into the current app.

Perhaps we can include some sentences that say "Please don't read this sentence, just leave your microphone on for a few minutes."

**Comment by kdavis-mozilla** [comment]
While useful for other things, this is not part of the Common Voice's goals. We should not dilute Common Voice's messaging and goals with other projects.

**Comment by jdittrich** [comment]
@mbebenita: I agree with @kdavis-mozilla but I suppose it would be comparatively easy to create a *Common Noise* project based on the code in the repo.

**Comment by mbebenita** [comment]
@kdavis-mozilla I share your concern about not diluting the messaging, and we should probably wait before expanding Common Voice to other use cases, however, I don't understand why removing noise wouldn't be generally beneficial as part of a speech recognition system.

I'll close it for now, and we can revisit this at a later time.

**Comment by kdavis-mozilla** [comment]
@mbebenita Removing noise happens automatically as part of the current Deep Speech system. We don't need do do anything extra if we have speech samples with background noise.

**Comment by mbebenita** [comment]
I don't really have a strong intuition about this, but how is it that a specially tuned system for removing noise paired with a STT engine is not better than a more generic system for detecting speech that also trains on noise?

**Comment by kdavis-mozilla** [comment]
When a system is tuned end-to-end all its pieces generally work better together. 

For examples see the recent trends on TTS WaveNet, Deep Voice, Deep Voice 2, Tacotron or the papers on end-to-end STT system that train STT systems to handle multi-microphone inputs. The system learns to handle noise, echo, reverb, beamforming...
