### ISSUE TITLE
"Sorry! We are processing our audio files, please try again shortly."

### ISSUE THREAD

**Issue by orschiro** [mozilla/voice-web#359]
Since yesterday, I am getting this error. Anyone else?

![image](https://user-images.githubusercontent.com/170947/28605324-4f46aeda-71d1-11e7-8a9b-71ff3d33d3f2.png)

**Comment by MichaelNMaggs** [comment]
Intermittently, yes

**Comment by Omniscimus** [comment]
Yes, I'm getting this as well. @mikehenrty could this have been caused by 717dd525d18d35056fdee5a60c6cc8e2e5c742aa?

**Comment by mikehenrty** [comment]
This was caused by our servers running out of memory, rebooting, and then taking a while to load audio clips for you to listen to. We have added some memory, and deployed some stability fixes so I hope this should be fixed now. We can re-open if this comes back.
