### ISSUE TITLE
No text to read when recording

### ISSUE THREAD

**Issue by jf99** [mozilla/voice-web#360]
When recording my own voice, I sometimes get no text to read.
![empty1](https://user-images.githubusercontent.com/7962377/28625473-ac7c05c8-721c-11e7-8d4c-9b3000dcfa24.png)
![empty2](https://user-images.githubusercontent.com/7962377/28625474-ac9ca35a-721c-11e7-9093-7562300e9dca.png)

**Comment by jdittrich** [comment]
Does this always happen for *all* of the text you get? Or are there also sets where you get e.g. 2 with text and 1 without?

**Comment by jf99** [comment]
No, it's not always. After hitting submit in the second picture, chances are good to get new text.

**Comment by augustnmonteiro** [comment]
I've got this error a couple of times too, It happens when the random.json endpoint take too much to answer

**Comment by mikehenrty** [comment]
I just did a major update to the recording flow in https://github.com/mozilla/voice-web/commit/c84ce400f03030a463bdc813dd3cd11516bad3b2, and we have done some work on site stability. Let's call this as fixed for now, but re-open if we are still seeing it.

**Comment by jf99** [comment]
Not exactly the same, but similar: Two of the sentences showed up, one did not.

![single empty sentence](https://user-images.githubusercontent.com/7962377/28663428-9d4e74a4-72bd-11e7-8976-2adc22c82666.png)

**Comment by mikehenrty** [comment]
Oh, that looks pretty bad. Are you seeing this regularly? Did you do anything differently? @jf99

**Comment by jf99** [comment]
I saw it the first time, have done about 300 recordings since then, and it didn't show up again. Maybe there is an empty line somewhere in the text files containing the sentences?

**Comment by mikehenrty** [comment]
Could be, let's keep an eye on this one.

**Comment by kylepolich** [comment]
I tried the site for the firs time two.  I was given two sentences and after that a blank one.  I don't know how to get past it.

**Comment by mikehenrty** [comment]
@jf99 yup, you were right. when we were putting our txt files together, we were adding empty lines between each of the files. fix coming up shortly.

**Comment by jf99** [comment]
The same issue as in the first post just occurred again. @augustnmonteiro is right. The Firefox console says that it could not fetch https://voice.mozilla.org/upload/random.json:

![no text console](https://user-images.githubusercontent.com/7962377/29171574-41fa5c64-7ddd-11e7-8ca6-07053451043b.png)

**Comment by mikehenrty** [comment]
@jf99 I think the issue is that when the site has problems loading sentences, there is no error message displayed. we fixed this for listening functionality, but need to do the same for speaking. can you file a new bug for this?
