### ISSUE TITLE
Mixed Accents

### ISSUE THREAD

**Issue by Fionaussie** [mozilla/voice-web#368]
No clue if this is the appropriate forum for this feedback.

Humans migrate. If they do this as adults, they may take on the accent of their new country but never completely lose the accent of their mother tongue. The end result is a bit of this accent, and a bit of that accent. For example, because I was raised in Australia, English speakers in the US think I have an Australian accent. Yet when I am visiting my family in Australia, the English speakers there say I have an American accent. So do I answer "Australian English" or "US English"?

**Comment by ajaydee** [comment]
IMHO, you would be US English. I don't think it would matter too much either way.

**Comment by kdavis-mozilla** [comment]
@Fionaussie I'd second the take @ajaydee had on this. I think as you're some mixture, whichever choice you make is fine.

**Comment by mikehenrty** [comment]
See also #242 .

**Comment by nukeador** [comment]
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
