### ISSUE TITLE
Safari - Doesn't seem to work and prompts to use another browser?

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voice-web#370]
(Issue filed on Dees' behalf)
https://www.dropbox.com/s/44levf8z39xczdu/Screenshot%202017-07-21%2011.35.26.png?dl=0

**Comment by mikehenrty** [comment]
Safari, as of yet, doesn't support getUserMedia(), so we are not supporting Safari yet. They do plan on implementing it soon, and when they did it should start to work automatically.
