### ISSUE TITLE
[static] Move all static content under a single url prefix

### ISSUE THREAD

**Issue by gozer** [mozilla/voice-web#371]
Something like /s/ or /static/ or /assets/ for instance

That way, managing it outside of node itself becomes a lot easier

**Comment by mikehenrty** [comment]
Can we just use the `web` folder @gozer ? There is nothing in there that I would mind serving publicly, and all of our static assets (including the ones that are built with gulp) reside there.

**Comment by gozer** [comment]
Yes, I know it's the web/ folder on disk, however, from the URLs, it's not as easy to determine.

For instance what's static: /css/foo.css or /clip/random.json ?

For now, see in #372, I am making a list of assets to consider static, but that will miss some in the future, most likely, once you add some other static folder.

**Comment by mikehenrty** [comment]
AFAICT, only `web/tsconfig.json` and the `src` files are the only files in `web` that is not part of the app. But I don't see it a problem if we serve these along with everything else. What do you think?

**Comment by mikehenrty** [comment]
Ah gotcha, yeah, we can definitely change the folder structure to help distinguish.

**Comment by gozer** [comment]
For instance, I am just looking at things requested for /dist/ and having a hard time mapping that back to where it's from...

**Comment by mikehenrty** [comment]
I just added a PR to serve `dist` rather than `css` for a bandaid. Later I will create a `public` folder inside of web I think. For now, I think this should do us good:

https://github.com/mozilla/voice-web/pull/374

**Comment by rugk** [comment]
If you do so, you can e.g. use static compression or other things more easily.

**Comment by MichaelKohler** [comment]
All these assets are now served from the /dist endpoint, I'm closing.
