### ISSUE TITLE
Have keyboard shortcuts for player interaction

### ISSUE THREAD

**Issue by jdittrich** [mozilla/voice-web#379]
**Need:** I want to be as efficient as possible when evaluating many sound samples.

**Possible Solution:** Create keyboard shortcuts.

## Spec 
Have shortcuts for:
* Give the sample a "yes": Y
* Give the sample a "no": X
* Play/Pause: SPACE

**Extension:** If you press SPACE and the sample has not loaded yet, "remember" it and start playing right away. 

**Extension:** Jump back and forward with ARROW-LEFT and ARROW-RIGHT

## Appendix

* Related: #337 (Autoplay option in listening mode) 
* Possibly implement using [mousetrap.js](https://github.com/ccampbell/mousetrap), though a custom solution might work well, too. 
* [Keystroke Level Modeling of Interaction](https://en.wikipedia.org/wiki/Keystroke-level_model)
   *  KLM  for the current UI**:
 Think (1.35) +MoveMouse (0.5)+KlickPlay(0.1) + Think (1.35) + MoveMouse (0.5) + KlickYes/No (0.1) 
**= 3.9** (with a generous assumption for mouse, since the way is rather short)
    * KLM for keyboard shortcut UI:
Think (1.35) + PressSPACE (0.1) + Think (1.35) + PressY/X (0.1) 
**=2.9**  
*difference= 3.9 - 2.9=1s  |  so there would be 1sec gain for each sample*

**Comment by jdittrich** [comment]
![grafik](https://user-images.githubusercontent.com/3416487/28733566-0944ef38-73dd-11e7-98e7-954ca07a2150.png)

We could also have a pop-up appear on click and/or hover:

![grafik](https://user-images.githubusercontent.com/3416487/28733717-bd696746-73dd-11e7-8c21-83ba1c298cd4.png)

**Comment by jdittrich** [comment]
@mikehenrty: Would it make sense to include a library for managing shortcuts of the react components like [react shortcuts](https://github.com/avocode/react-shortcuts) ? Or would that be too heavy and we would have one global handler via [mousetrap.js](https://craig.is/killing/mice) and call the functions from there?

**Comment by Gregoor** [comment]
Hi @jdittrich, thanks for writing down your thinking on this. Also nice to see KLM again, haven't seen it since university. I want to look into implementing it this week (I also miss this feature very much).

___

RE keys: Why Y/X? I was wondering what the shortcuts for similar actions on other site's are. There are the VI `HJKL`-keys which Feed sites like FB, Twittter or Feedreaders typically implement, where `J` & `K` are used for going from post to post and `L` is usually liking of a post. So maybe should we go with:

| Key | Action|
| --- | --- |
| `J` | Play | 
| `L` | Yes |
| `H` | No |

But CV is far from being a feed, so maybe using those keys would be misleading. Happy to hear about shortcuts on other sites.

___

RE display of the keys: We could also show them on hover as I don't want to clutter the design. Though that would likely lead to many people not knowing that there are shortcuts. Do you have an idea for this @m-branson?

___

RE implementation: I'd likely build it by hand for now, as I don't see it being that much code. But `react-shortcuts` and its dependency `combokeys` look like they solve some problems we might have in the future when localising Common Voice into other languages. So we should definitely keep them in mind.

**Comment by m-branson** [comment]
@jdittrich @Gregoor great topic, would be a super helpful implementation for accessibility as well.

I agree with this:

> Another approach would be to go with a natural language mapping, i.e.:
>
> Key | Action
> -- | --
> P | Play
> Y | Yes
> N | No

The 'J,L,H' keys are not quite intuitive, my impression would be that users may go to language mapping in instinct. Note this is not founded in any data, but is something we could implement and test against.

---

> RE display of the keys: We could also show them on hover as I don't want to clutter the design. Though that would likely lead to many people not knowing that there are shortcuts. Do you have an idea for this @m-branson?

Preference would be to show them on hover as a tooltip `Play [P]` and add potentially this info to the FAQ page for those who are looking for it. I'm hesitant at the moment to add any further UI to the design. Especially as this is still an interim design, not one that is founded in research or testing. We will be doing more of this work in early 2018 and would prefer to put more thinking behind these types of use cases. Again thanks @jdittrich for flagging and pushing for an initial implementation.

---

Another note re: accessibility would be to implement focused states; e.g. allow users to tab through the experience and interact using the enter button. I realize this would require clearer UI styles for focused vs. hover, apologies that this clearer style guide hasn't been provided yet (it is meant to happen in 2018).

**Comment by jdittrich** [comment]
> Preference would be to show them on hover as a tooltip Play [P]

Usually I dislike hover-infos, but since touch devices (which don't hover) rarely have a keyboard, I think it is fine. 

> [users] may go to language mapping in instinct.

I would assume that, lacking a standard, most users would need to look up the shortcuts anyway.
Alternatively or in parallel to hover one could use a system like the underlining the needed letter:

![image](https://user-images.githubusercontent.com/3416487/33581155-fc90fd62-d94f-11e7-9479-178277892046.png)

however, this does not work with icons instead of text.

**Comment by Gregoor** [comment]
I like the idea of underlining it (in addition to a hover text). I'll implement it that way for now if there are no objections.

**Comment by Gregoor** [comment]
You can see the shortcuts on our staging server: https://voice.allizom.org/
Please note that this server is for testing only, so no need to correctly validate/record on it

**Comment by jdittrich** [comment]
Works for me. I found the p-shortcut for play harder to find, but it is still OK considering it is for more experienced users. 

I would find it useful to see the button chosen to give a brief feedback ("feedback/show system state to user-Principle), like a CSS :active state (in this case, a brief inversion of colors)

**Comment by Gregoor** [comment]
Good point, button feedback would definitely help. If no one from the community picks it up, I'll look into it in the next week.
Also I'm thinking about adding shortcuts for recording as well, though we should probably only move on that if we see people using the listening shortcuts.

**Comment by m-branson** [comment]
@jdittrich @Gregoor appreciate where this has gone, thanks and great work! And agreed, testing for a bit on validate before adding to record is a good way to proceed.

**Comment by jdittrich** [comment]
It seems to be there and work well. Thanks a lot, it seems a minor improvement but makes contributing more fun!
