### ISSUE TITLE
Click "Donate voice" doesn't open page with scroll position at the top

### ISSUE THREAD

**Issue by orschiro** [mozilla/voice-web#386]
Not a major issue but slightly annoying that I always have to scroll up again just to see the contents of that screen.

![peek 2017-07-30 08-37](https://user-images.githubusercontent.com/170947/28751235-a2f1ca36-7502-11e7-8590-17e4044626b2.gif)

**Comment by Omniscimus** [comment]
Duplicate of #311

**Comment by orschiro** [comment]
Ups, sorry!
