### ISSUE TITLE
When are changes applied to the website?

### ISSUE THREAD

**Issue by jf99** [mozilla/voice-web#390]
This is more of a question than a bug report. I noticed there are some commits like this one https://github.com/mozilla/voice-web/commit/99e7d7b4c21d5a0890823f97067559798536ebf8 that change the content of the website. However, the commit linked above is already 4 days old and the FAQ hasn't changed yet.

Is there any sort of schedule when the servers get updated to the new code base?

**Comment by mikehenrty** [comment]
Hi @jf99, yeah we haven't pushed for a little bit. My goal is to try and push ever other day or so. But I have been on vacation and wasn't around to debug if anything went wrong. Changes will be up soon!
