### ISSUE TITLE
Synchronize your stats across multiple devices (Firefox account integration?)

### ISSUE THREAD

**Issue by xKeiro** [mozilla/voice-web#392]
I would like to see merged stats on my devices, especially since I know you are planning on introducing achievements and goals in the future. 

So what I'm suggesting is, it would be nice if you would implement an **optional** account sync (login) feature. 
In my books the ideal solution would be to use Firefox account to sync, but really anything would work (password, google, GitHub etc.)

_Extra fun feature:
If you want to make this whole voice collecting project more fun for the participants you could include a couple extra button like: “I like your voice”, “I love your accent” and show them how many they've got. Just to make some people's day brighter._

**Comment by mikehenrty** [comment]
I like these ideas! We are planning to add a `login` of sorts to the site soon, but there are legal issues around privacy we need to work through first. Stay tuned!

**Comment by jf99** [comment]
But don't make a login mandatory.

**Comment by mikehenrty** [comment]
> But don't make a login mandatory.

Never!

**Comment by woj-tek** [comment]
> but there are legal issues around privacy we need to work through first.

Could you share some light on the legal issues you would be facing while implementing this?

**Comment by mikehenrty** [comment]
> Could you share some light on the legal issues you would be facing while implementing this?

Most importantly, we don't want to associate anyone's email address (or any other personally identifying information) with the data we release. Now that we have released v1 of the data, we have tools that can help us here. So the biggest hurdle now is design and implementation.

**Comment by delgermurun** [comment]
Any update on it please? @mikehenrty

**Comment by Gregoor** [comment]
@delgermurun we're about to put Authorization #899 in, after that we just need a good story to tie it into existing profiles. So bear with us, it's not far away!

**Comment by Gregoor** [comment]
Jeesh, that was in March! 🙈 Well, now it's here.
