### ISSUE TITLE
"United States English" accent is too broad

### ISSUE THREAD

**Issue by Riamse** [mozilla/voice-web#395]
I'm surprised that anglophone European accents are broken down into Scottish, Welsh, Irish, and British (I assume this is Received Pronounciation?) while the numerous accents of the United States are simply grouped together as the United States. Midwest and California accents being omitted, I can understand, but there's certainly nobody who could not tell that the "Southern Accent" and African American English differ from both each other and the dominant accent of the Northeast, just going by voice alone.

**Comment by kdavis-mozilla** [comment]
@Riamse Thanks for you comment.

However, I've a question related to your comment. The question is:

_Too broad for what?_

It's seems you have some unspoken application, or something else, in mind for which this accent is too broad. But you don't mention this "application".

Could you flesh out this context a bit more? The context in which this accent is "too broad".

**Comment by Riamse** [comment]
Thank you for the response Kelly. It's not a question of having any specific application. What I'm saying is that the pronounciation of "United States English" drastically varies within the United States itself. There are enormous differences in how someone from South Carolina speaks and how someone from New York City speaks. There are enormous differences in how an African American from Georgia speaks and a white person from Georgia speaks.

Suppose Mozilla Voice was collecting Spanish samples instead - an equally absurd analogue of the current "US English" would be having one selection, "New World Spanish", to represent Spanish spoken in the Americas, from Mexico to Argentina, Cuba to Hispaniola.

And yes, there are also enormous differences in how Scottish people speak and how Irish people speak. And in this case, Mozilla has made the right choice: give each accent its own label. What is the justification to do the opposite with the United States?

**Comment by kdavis-mozilla** [comment]
The prototypical application that the corpus targets is training a speech-to-text engine.

Speech-to-text engines are generally released on a language-country basis, e.g. en-us or en-ie. They are not released on a language-country-region, e.g. en-us-south-carolina or en-us-georgia.
So we take our grouping lead from this rule. However, sometimes accents straddle national boundaries. In this case we group nations together.

**Comment by mikehenrty** [comment]
Given Kelly's comment, I'm going to close this as working as designed. Let's re-examine this if we discover in our research that more data consumers want this granular distinction.

**Comment by nukeador** [comment]
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
