### ISSUE TITLE
Move Discourse link to the blue bottom bar

### ISSUE THREAD

**Issue by Kusaha** [mozilla/voice-web#396]
I've seen quite a lot of people asking questions here on GitHub (including myself) because the Discourse forum is really underused and if I understand it right that should be the place where we ask questions, share what we learned about the project and just discuss things and GitHub the place where we ask for new features/report bugs and things like that. 

**The problem:**
I think under usage comes from these issues:
- the discourse link is hard to spot on the website
- it's not clearly explained what discourse is

**Possible solution:**
My proposition is to move the discourse link to the bottom blue bar, and call it somewhat else, that explains itself, here's a little mock-up I've made:
![discourse idea](https://user-images.githubusercontent.com/7066695/28871661-e7eb0456-7785-11e7-89f3-0764efa8780d.png)

**Comment by mikehenrty** [comment]
Yup, let's do this. We have an icon in our icon font that could be used for this. So if someone wants to work on this, just comment here and I'll provide details.

**Comment by deepakks1995** [comment]
I would like to work on the above problem @mikehenrty

**Comment by mikehenrty** [comment]
> I would like to work on the above problem @mikehenrty

Do eeeet! 👍

**Comment by deepakks1995** [comment]
I have moved the discourse link to the blue bottom bar @mikehenrty , have a look at the pull requests

**Comment by mikehenrty** [comment]
Fixed, thanks @Kusaha  and @deepakks1995 !
