### ISSUE TITLE
Normalize voice samples volume

### ISSUE THREAD

**Issue by azymohliad** [mozilla/voice-web#399]
Sometimes voice samples differ in volume really significantly, which is very irritating. I'd propose to normalize their volume level before putting them for validation. I guess they are anyway normalized before further processing. This will make validating process more simple and pleasant.

**Comment by azymohliad** [comment]
Oh, sorry, I didn't see that [similar issue](https://github.com/mozilla/voice-web/issues/336) already exist. Closing this one as a duplicate.

**Comment by mikehenrty** [comment]
Thanks for the report!
