### ISSUE TITLE
Use usertesting.com to get some rapid feedback on stickiness options

### ISSUE THREAD

**Issue by geroter** [mozilla/voice-web#4]
Quickly mock-up (not code) and get feedback on stickiness/gamification options before we make a final choice.

Depends on building out a long-list of options.

**Comment by mikehenrty** [comment]
Let's make this a part of Sprint 3 since it's a nice to have and we've already sanity checked the concept of levels at the Taipei workshop.

**Comment by mikehenrty** [comment]
Not going to get to this before release.

**Comment by mikehenrty** [comment]
Closing this as not immediately actionable. If and when we decide to use user testing, we ca file a new big.
