### ISSUE TITLE
British, Scottish and Welsh English?

### ISSUE THREAD

**Issue by jhwinters** [mozilla/voice-web#404]
There's a rather odd choice of accent for the resident of Great Britain (which encompasses England, Wales and Scotland).  These are often lumped together as "British English" although there are vast differences in pronunciation between them.

For this project however, Welsh English and Scottish English have been separated out - perfectly sensible since this project is to do with pronunciation - but what remains is then English English, not British English.  It might be necessary to clarify it as "English as spoken in England" or something like that.  As it stands, inhabitants of Wales and Scotland have two logical choices from the list ("British" or "Welsh", and "British" or "Scottish") whilst inhabitants of England have just one which lumps them in with the Welsh and the Scots.

**Comment by kdavis-mozilla** [comment]
What about "England English" as a phrasing?

**Comment by nukeador** [comment]
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
