### ISSUE TITLE
Typo in Singapore English

### ISSUE THREAD

**Issue by kenrick95** [mozilla/voice-web#405]
Occurred at [this line](https://github.com/mozilla/voice-web/blob/master/web/src/lib/user.ts#L19). The word "Singaporian" does not exist; it should be "Singaporean". (this could be a good first bug)

Further reading on Wikipedia's article [Singapore English](https://en.wikipedia.org/wiki/Singapore_English) shows that there are two forms: Standard Singapore English, and Singlish. So which one is actually being referred to in this project? Thanks

**Comment by kdavis-mozilla** [comment]
"Singaporian" to "Singaporean" is a great  first bug.

Right now Singaporean means both. The fear was that not enough data would be obtained to split it in to Standard Singapore English and Singlish.

**Comment by caro401** [comment]
Hi, I'd like to have a go at fixing this, but have never made a pull request before, is that OK?

**Comment by kenrick95** [comment]
@caro401 Sure, go ahead and fix it. Let me know if you have any questions. Thanks

**Comment by nevik** [comment]
@mikehenrty seems like this wasn't properly closed by merging the PR?
