### ISSUE TITLE
Can I use this project to collect voice in different language?

### ISSUE THREAD

**Issue by delgermurun** [mozilla/voice-web#408]
Hello,

Awesome project and effort.

Can I use use this for my collect voice in different language (e.g Mongolian) and use collected data for private purpose?

Thank you.

**Comment by kdavis-mozilla** [comment]
As the license is [MPL-2.0](https://github.com/mozilla/voice-web/blob/master/LICENSE), the answer is "Yes," you can use it to collect voices in different languages.

However, we are also hoping to start collection in various languages too. So, to increase your reach and the diversity of languages that you and others have access to, we should try to work together on subsequent languages. This way everyone wins.

**Comment by delgermurun** [comment]
Thank you @kdavis-mozilla 

I am gonna participate when multi language support began.
