### ISSUE TITLE
[Bug] When a new file clip gets uploaded, we don't add it to the random voice pool

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#41]
This is ok right now since we restart the server frequently. But this will need to be fixed before release.

**Comment by kdavis-mozilla** [comment]
Hack fixed as part of 83088c8

See the line here [clip.ts:L184](https://github.com/mozilla/voice-web/blob/master/server/src/lib/clip.ts#L184) where upon each audio save the list of unconvered mp3's is re-created and converted.

**Comment by kdavis-mozilla** [comment]
My fix is not idea but it works. So I'm going to close.
