### ISSUE TITLE
Typo in sentence "We used all your imgination to design the place"

### ISSUE THREAD

**Issue by azymohliad** [mozilla/voice-web#413]
The word _im**a**gination_ misses _**a**_.

Since this is a very minor kind of issue, what's the best way to report them? Is it worth to create new issue for each case? Or maybe rename this one to something like "Typo reports" and report in comments? Or you have already defined another way (sorry, if I couldn't find it)?

**Comment by kdavis-mozilla** [comment]
Reporting just as you have is fine. It also has the advantage of creating an issue that's a nice first pull request for a new contributor.
