### ISSUE TITLE
Some HTML made it into the voice samples (bug or easteregg?)

### ISSUE THREAD

**Issue by nevik** [mozilla/voice-web#425]
I just ran into a text sample (while validating) that is the top line of an HTML document (doctype definition), and the audio sample did, in fact, contain someone reading off an HTML tag (though not the text in the sample).

I'm not sure if this is someone having fun with the corpus, or if this sample slipped in by accident. I can't find it in the `server/data` folder in this repo -- is the actual corpus being kept somewhere else? (or did my search-fu not suffice?)

I'm attaching a screenshot of this text sample below.

Unfortunately, this happened on my iPad, so I couldn't inspect the page to pull out any more info.

![img_0018](https://user-images.githubusercontent.com/1099818/29248094-3f71a676-800f-11e7-848a-ae13babb7f37.PNG)

**Comment by kenrick95** [comment]
I think this issue is duplicate of #300

**Comment by nevik** [comment]
Woops, you're right! Totally didn't see that there :)

Duplicate of #300.
