### ISSUE TITLE
Text corpus vs. existing voice samples

### ISSUE THREAD

**Issue by nevik** [mozilla/voice-web#426]
While the available source texts are in this repository (in `server/data`, I think), as is indicated in #287 and #330, during validation I still encounter a lot of voice samples with sentences that are not part of this corpus.

What is the project's approach here? Some of the sentences or sentence collections seem to have been removed from use (or removed from the list entirely) due to one reason or another. Are the voice samples already recorded for those sentences going to be removed from the voice database?

**Comment by kdavis-mozilla** [comment]
The voice samples that have already been recorded using the removed sentences will not be removed from the voice database. We want to keep the voice database as large as is possible.
