### ISSUE TITLE
Running gulp script results in repeated CredentialsError

### ISSUE THREAD

**Issue by nevik** [mozilla/voice-web#427]
I'm trying to set up a local dev environment for voice-web, following the instructions in the README.

However, when running the gulp script, after some build steps, I repeatedly get the following error output in the terminal (I'm also attaching the anonymized full log output as a text file):

> Error while fetching clip list, CredentialsError: Missing credentials in config

I've not found any mention of having to fill in credentials, or which credentials to use.

Is this situation expected? How do I proceed to get the local server running?

---

Environment:
OS: macOS Sierra 10.12.6 (16G29)
Node.js v8.3.0
npm v5.3.0

[credentialserror-report.txt](https://github.com/mozilla/voice-web/files/1220432/credentialserror-report.txt)

**Comment by kenrick95** [comment]
I think it is expected if you didn't edit `config.json` file.

When running `gulp`, could you open up your browser and go to `localhost:9000`? At least, the front-end part of the site should be up and running.

**Comment by nevik** [comment]
Just tried it: Yup, the frontend part is working.

Thanks for the heads-up, that way I could at least work on frontend changes :)

Naturally, this instance then isn't connected to any backend, so I can't test/change anything in regards to that.

It would be great if some more info about the (local/dev and production) environment could be added to the project docs. From looking around the Travis and gulp config today, I found out that the backend also wants a local MySQL server to run against, which I haven't seen mentioned anywhere. The connection to AWS (and if it can be mocked for testing) is also somewhat nebulous to me.

**Comment by iveskins** [comment]
Is anyone able to provide a quick check list for building a dev environment.. is it just, stand up a mysql db, make a s3 bucket and put the config in the config.json file? what is the expected format of the aws config?

**Comment by echonox** [comment]
Any update on this? We can't contribute properly without a proper documentation..

**Comment by mikehenrty** [comment]
We are indeed working on updating the documentation in #423.

This bug is that there are unfriendly errors when someone has not configured their s3 buckets. Ideally we should support not having s3. So there are two possible steps to this bug:

1. Make the error message more friendly, and ask users to set up s3 and their aws config file.
2. Allow saving and reading from the local file system when s3 creds aren't found.

For the time being, I'd settle for a better error message, and then documenting how to configure s3 better.

**Comment by mikehenrty** [comment]
There is now a better error message when s3 isn't configure so I'm going to mark this bug as closed. I'll open a new bug to document how to configure an s3 bucket, and credentials.
