### ISSUE TITLE
[iOS] need to show something when offline

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#43]
right now we just show a blank screen. i have a feeling this will be a show stopper for the apple review

**Comment by mikehenrty** [comment]
@andrenatal or @mbebenita, do either of you know if we could show some static image if we are offline on the app side? I have been thinking about ways to do this on the web side with caching, but you still need that first load to work, as I guess offline is something Apple will check.

**Comment by andrenatal** [comment]
Fixed [here](https://github.com/mozilla/voice-web/commit/34b8107cc26d6a3ec23552a65a348306fc999bd2)

I am adding a check and displaying a message. We can add an image too. 

So I'll close this and open another issue asking for the offline image for replacement that should be produced by the UX team.
