### ISSUE TITLE
UX: These floating numbers on navbar don't clearly show their meaning

### ISSUE THREAD

**Issue by kenrick95** [mozilla/voice-web#431]
![capture-ux](https://user-images.githubusercontent.com/3090380/29319492-d0510788-8206-11e7-95c4-6fc5e6dc7245.PNG)

I mean, only after I read the source code that I know what they means. When I see it from the site, I don't know what they means.

**Comment by jdittrich** [comment]
I agree that they are hard to understand (I don't know what they mean either…)
On the other hand, I assume them to be not very irritating either – I always considered them as a kind or graphical element, not knowing they react to my actions.

**Comment by mikehenrty** [comment]
These are just a tiny easter egg. Soon we plan to add profiles that track your progress, and have leaderboards. At that point, we will remove these. I'm going to close this bug for now, since (while it's confusing) it's working as expected.
