### ISSUE TITLE
[iOS] expose api to request for micorophone, and a callback for when we have it.

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#44]
We could even attach the permission prompt to the first time I call "start_capture".

**Comment by mikehenrty** [comment]
@andrenatal or @mbebenita, would either of you be able to have a look?

**Comment by mikehenrty** [comment]
The reason I think this is important is because I think Apply looks at UX in their decision making process, and prompting for a mic without user action is bad UX.

**Comment by andrenatal** [comment]
@mikehenrty  This was fixed [here](https://github.com/mozilla/voice-web/commit/d2c0522293bde26a4ea6aa3c82756a0b47da0a8c). So now the permission request is handled when you call start_capture. 

I also introduced a new [callback](https://github.com/mozilla/voice-web/blob/master/ios/voicebank-ios-wrapper/index-cv.html#L54) to send messages to the webapp so those can be displayed properly to the user.

**Comment by andrenatal** [comment]
Currently are being sent the following messages:

- errorplaying: if the audio file could not be played
- capturestarted: when the mic starts recording
- errorrecording: when some error happened when started recording
- nomicpermission: when the user denied permission to record
