### ISSUE TITLE
No english-as-a-second language option!

### ISSUE THREAD

**Issue by olegserov** [mozilla/voice-web#443]
Hi,

I'm from Russia and I have an accent. I would like to have an opportunity to specify my accent in order to get better recognition.

**Comment by PaulXiCao** [comment]
That sounds like a good idea imo.
I see two options:
1. have the option "English as a second language"
2. have more countries to choose from: Russia, France, Poland, ...

I wouldn't mind to implement either feature. Which one is favored?

**Comment by PaulXiCao** [comment]
This issue is addressed in detail in #242 
I guess this one could be closed..

**Comment by jdittrich** [comment]
@mikehenrty: can you close this?

**Comment by nukeador** [comment]
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
