### ISSUE TITLE
Trimming non-speech at start and end of clips

### ISSUE THREAD

**Issue by NAHarris** [mozilla/voice-web#446]
Many clips contain long periods of background sound before or after the speech sample.  This should be trimmed if possible before presentation for review. 

One possible algorithm for this would be to detect voiced sounds, and dropping all audio that is outside a window that starts (say) two seconds before the first voiced sound, and two seconds after the last voiced sound.

**Comment by jdittrich** [comment]
Someone else suggested this before on issue #279 – maybe your ideas for the algorithm could be useful!

Meta: duplicates #394 #279 
@mikehenrty please close.

**Comment by mikehenrty** [comment]
Thanks for the report @NAHarris, and thanks for the follow up @jdittrich
