### ISSUE TITLE
createDb.js tool script error

### ISSUE THREAD

**Issue by iveskins** [mozilla/voice-web#447]
when trying to create the database I got
`database create error ER_ACCESS_DENIED_ERROR: Access denied for user 'voicecommons'@'172.17.0.1' (using password: YES)`

Seems to be because of the line
`CREATE USER '${USERNAME}'@'localhost'..`

Because I was running mysql in docker, the incoming connection from node to mysql was not on localhost but on the docker bridge ip.
I had to change the script to CREATE USER '${USERNAME}'@'172.17.0.1'

**Comment by mikehenrty** [comment]
Yeah, the database was never really implemented properly. We will be doing this in the next month or so, which will fix this problem.

**Comment by mikehenrty** [comment]
This file is deprecated and will soon be removed from the repo. Closing.
