### ISSUE TITLE
Waiting for localhost forever

### ISSUE THREAD

**Issue by smolendawid** [mozilla/voice-web#450]
I run the voice-web locally. After first run, I have some files saved on S3 and everything works fine. 

However after the second run (after killing first run and calling another gulp) voice-web doesn't work - "listen" shows "Loading..." and "speak" shows blank frame...

**Comment by smolendawid** [comment]
In _Developer tools -> Network_ in Chrome I can see that I am waiting for the upload of _random.json_ file. It still tells me nothing...

**Comment by mikehenrty** [comment]
Are there any errors coming from your node.js process?

**Comment by mikehenrty** [comment]
We've improved some error messaging, and some of the flow here. I'm going to close this for now, but let's re-open if it resurfaces.
