### ISSUE TITLE
Microphone permission issue

### ISSUE THREAD

**Issue by kjanko** [mozilla/voice-web#452]
If the microphone is consistently enabled on the website (i.e. if it requires no permission to be enabled, but is enabled by default) there is a big delay between the moment the user clicks record and when he actually starts recording.

**Comment by mikehenrty** [comment]
@kjanko what browser and OS are you using? I haven't seen this lately, but it was a problem in an earlier version of the code.

**Comment by kjanko** [comment]
@mikehenrty happens on both, Firefox and Chrome. Windows 7.

**Comment by Omniscimus** [comment]
For me, it does start recording immediately, but the record button turns red a short while after you press it, when the animation is finished. This may make it seem like it starts recording only after the animation is finished instead of immediately when you press the button. Maybe this is the issue here?

**Comment by kjanko** [comment]
@Omniscimus just tested this, It's pretty inconsistent for me. Sometimes It allows me to record, sometimes it doesn't. Not sure what's going on.

**Comment by mikehenrty** [comment]
@kjanko do you have multiple tabs (or browsers) with different versions of Common Voice running? i've noticed for myself that having multiple tabs open screws with the microphone input.

**Comment by kjanko** [comment]
Yes, tested on a single tab and it seems to be working.

**Comment by mikehenrty** [comment]
> Yes, tested on a single tab and it seems to be working.

Ah in that case, this will be fixed by #460.

**Comment by Gregoor** [comment]
Since #460 is fixed, this should be fixed as well :)
