### ISSUE TITLE
UI: Show error to user for invalid recordings

### ISSUE THREAD

**Issue by Omniscimus** [mozilla/voice-web#453]
(issue intended to track this)

When the recording is too short, too long or silent, a message with the error gets logged to the console (#432). This error should be shown to the user somehow (possibly with troubleshooting steps?), and the recording should be rejected.

**Comment by mikehenrty** [comment]
Thanks for filing @Omniscimus, our UX/Designer @m-branson is taking a look at this.

**Comment by mikehenrty** [comment]
Let's close this one in favor of #301 since it's older and has more information.
