### ISSUE TITLE
Update CV Wordmark

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#461]
Common Voice + Mozilla wordmark needs refinement to better align with brand standards (spacing and removal of white pixel border around Mozilla logo).

@mikehenrty I'll provide SVGs, unless you prefer otherwise...🎉

**Comment by m-branson** [comment]
Also please assign to me. :)

**Comment by m-branson** [comment]
Mozilla brand application guidelines have been updated, requiring changes to the changes. 😉  [See more here.](https://mozilla.ninja/expression/)

Will accomplish and deliver for implementation early next week.

**Comment by m-branson** [comment]
@mikehenrty inline are logo SVGs for implementation. Further assets (pngs, eps, ai file) in all versions are [here](https://drive.google.com/open?id=0B0vmiicLLrGuOU5fdjNHN093bm8).

`cv-logo-bw.svg` is your go to for primary usage; ~150px wide (as it is currently on the site) should still be ideal sizing. `cv-logo-one-color-white.svg` is best for the footer; ~100px wide there is just fine as well. 👍

[cv-logo-svgs.zip](https://github.com/mozilla/voice-web/files/1350269/cv-logo-svgs.zip)

Let me know if you run into anything odd with implementation.

**Comment by mikehenrty** [comment]
Welp, we ran into a roadblock. The SVG logo is not displaying properly in Firefox Nightly. I've filed a bug.

One other note is that the "Common Voice" part of the logo could be done in pure text (we already download the normally weighted font for this). The only issue is that the Common Voice text won't be bold (as that would require a separate download). Just an option if the bug below is taking too long. They may offer us a workaround in the meantime.

https://bugzilla.mozilla.org/show_bug.cgi?id=1405280

**Comment by mikehenrty** [comment]
The other thing I want to be aware of is the fact that logo guidelines have been changing a lot the last few months. It might be better to wait until this stabilizes a bit, to avoid multiple updates to our site as we evolve our guidelines.

**Comment by nevik** [comment]
Depending on the timelines of the word mark, new design and logo guidelines, it might be a good idea to delay updating the word mark until we have the design as well? 

On the other hand, might be less surprising for users if we roll out these changes slowly...

**Comment by m-branson** [comment]
@mikehenrty, got it. Sorry to hear about the bug, if there's a chance it's an issue with the SVG please let me know.

> One other note is that the "Common Voice" part of the logo could be done in pure text...

True, though the text portion of the logo is 'semi-bold' and is required to be. If the SVG will mean faster load times (and less font loading), we should wait until the bug is resolved.

> The other thing I want to be aware of is the fact that logo guidelines have been changing a lot the last few months. It might be better to wait until this stabilizes a bit, to avoid multiple updates to our site as we evolve our guidelines.

Understand the reservation, though I don't see this changing much more. This is the usual evolution of new branding (especially one that was done in the open w/much input). As the logo needs updating either way, I recommend we push this change when it is technically possible.

> Depending on the timelines of the word mark, new design and logo guidelines, it might be a good idea to delay updating the word mark until we have the design as well?

@nevik this wordmark is considered the logo. An icon would be an addition to the logo and allow us to form a 'logo lockup'. As the icon is not imperative to the user experience at this point, it is not something we'll want to hold up minor logo enhancements for.

> On the other hand, might be less surprising for users if we roll out these changes slowly...

Yep, iterative is good. Less 'big changes' and more, regular enhancements to the overall experience. 👍

**Comment by mikehenrty** [comment]
The bug in Firefox had to do with the fact that the SVGs you provided used inline styling, and our security policy forbids that. I added some mechanisms (nonce) to allow the SVGs you provided to use inline. I'll push to the main site soon.
