### ISSUE TITLE
Recordings counter counts wrongly

### ISSUE THREAD

**Issue by jf99** [mozilla/voice-web#464]
Each time when you hit the submit button, the counter increases by two, although you submit three recordings.

**Comment by mikehenrty** [comment]
what browser and OS are you using @jf99 ? desktop?

**Comment by jf99** [comment]
Firefox 55.0.3 (64-bit) on Arch Linux.

**Comment by jf99** [comment]
Same on 32-bit Windows 7 with Firefox 56. No errors on the console.
