### ISSUE TITLE
"Open in app" on iOS should launch app if installed

### ISSUE THREAD

**Issue by nevik** [mozilla/voice-web#467]
_Noticed while implementing #466._

When viewing the CV website in Safari on iOS, an "Open in app" banner is shown at the bottom of the screen.

However, unlike its label, tapping the banner always opens the AppStore page of the CV app, even if the app is already installed:

https://github.com/mozilla/voice-web/blob/6e646414efe984f98cb39c398ed92bb56dc7ba35/web/src/lib/components/pages.tsx#L128-L130
https://github.com/mozilla/voice-web/blob/6e646414efe984f98cb39c398ed92bb56dc7ba35/web/src/lib/components/pages.tsx#L347-L349

This behavior should be adapted to directly launch the app if it is already installed.

This is usually done using a URL callback scheme (see http://x-callback-url.com).

**Comment by elahmo** [comment]
How about using the Smart App Banner, which Apple (recommends)[https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html] as a native way to do this on iOS? 

It will show the rating from the App Store, as well as show links to either Install or Open the app, depending is it installed on the device.

**Comment by nevik** [comment]
@elahmo that is already in progress in #484 :)

**Comment by elahmo** [comment]
Oh, you might close this one then :)
