### ISSUE TITLE
Add support for Safari 11 & Edge

### ISSUE THREAD

**Issue by nevik** [mozilla/voice-web#469]
Safari 11 on macOS and Safari on iOS 11 (supposedly) add support for WebRTC. This could make the CV native wrapper app obsolete.

We should investigate whether the support for UserMedia in current Safari suffices for CV's needs, and think about when to abandon the app if this is the case.

_Note: I mostly wanted to bring this up so we don't forget. I'm going to look around and add some sources for this in the next few days. I might also try around in the simulator and/or on my iOS devices._

**Comment by mikehenrty** [comment]
getUserMedia is there in Safari 11, the problem is we also use the MediaRecorder api to manipulate the audio data client side before uploading it. the question would be around workarounds for MediaRecorder functionality, which i haven't looked at just yet

**Comment by nevik** [comment]
Sigh.

Unfortunately, you're right @mikehenrty.

As of iOS 11.0:
* `getUserMedia` / Stream API is supported ✅ -> http://caniuse.com/#feat=stream  
* MediaRecorder is **not** supported ❌ -> http://caniuse.com/#feat=mediarecorder

I just confirmed this by testing it on my iPad (running iOS 11).

**Comment by nevik** [comment]
Oh. However. I just stumbled over [recorder.js](https://github.com/chris-rudmin/Recorderjs/blob/master/src/recorder.js), which claims to work on iOS 11 as well.

@mikehenrty, if it's a general goal of the project to do away with the native app if possible, I think we should look into this.

**Comment by mikehenrty** [comment]
Indeed it's a general goal to get rid of the app, but it's not a high priority. Having a native app on iOS allows us to do push notifications, which won't be possible in mobile safari until they properly implement service workers.

https://webkit.org/status/#specification-service-workers

**Comment by Gregoor** [comment]
@nevik looks like recorder.js is using getUserMedia as well. From my reading I've come to the conclusion that there's no way to do it in Safari 10. Happy to be proven wrong though 🙃

**Comment by mikehenrty** [comment]
I think this is supposed to say Safari 11.

**Comment by Gregoor** [comment]
Oops, where is my mind 🙈 
This would also bring support to MS Edge! Let's make it happen!

**Comment by Gregoor** [comment]
I just played around with reccorder.js and it indeed looks like we would be able to have recording with it. Unfortunately playback does not work on Edge & Safari with it (I think due to missing ogg support). If you have Edge/Safari you can confirm that here:
https://rawgit.com/chris-rudmin/Recorderjs/master/example/encoder.html

There are a few paths I see around this:
- don't have playback on these platforms (easy to implement but suboptimal in usage)
- use ogv to decode & play the blobs in JS (emscripten) land (harder to implement, 60kb extra size but at least retains all functionality)
- upload blobs and return a format that is playable across browsers ("hardest" to implement but reatins all functionality without adding extra size)

**Comment by mritunjaygoutam12** [comment]
@Gregoor  why not give a try to webAsm pocketsphinx or https://github.com/muaz-khan/RecordRTC ?






> * upload opus files and return mp3 ("hardest" to implement but reatins all functionality without adding extra size)
> 
and this option is long and hardest to implement but we can give a try.

**Comment by Gregoor** [comment]
If we can extract their recorder from the source, that'd be great. I think it might be this one: https://github.com/muaz-khan/RecordRTC/blob/master/dev/StereoAudioRecorder.js

**Comment by mritunjaygoutam12** [comment]
yes it is the [recorder](https://github.com/muaz-khan/RecordRTC/blob/master/dev/StereoAudioRecorder.js) (recorderRTC API for this https://recordrtc.org/StereoAudioRecorder.html).
WebAsm recorder  https://github.com/muaz-khan/RecordRTC/blob/master/dev/WebAssemblyRecorder.js though may be it provide only worker thread web audio API

**Comment by mritunjaygoutam12** [comment]
:boom:
@Gregoor look at this minimal working example with Microsoft's recorder demo. It uses web audio Convolver for converting audio buffer output to a dedicated wav file format.
Live : https://mritunjaygoutam12.github.io/edge-audio-recorder/index.html
Repository : https://github.com/mritunjaygoutam12/edge-audio-recorder

**Comment by MichaelKohler** [comment]
As far as I know latest versions of Safari and Edge should work. I don't have the possibility to check on iOS, so please feel free to reopen.
