### ISSUE TITLE
CSP Header breaks recording on iOS

### ISSUE THREAD

**Issue by nevik** [mozilla/voice-web#471]
Just noticed that the newly introduced Content Security Policy header seems to break recording functionality on iOS (observed in iOS 11 on a real device, and on iOS 10.3 in simulator).

When finishing a recording (i.e. clicking the red circle button), the following error appears in the console:
> Refused to load data:audio/mp4;base64,`<base64 string>` because it does not appear in the media-src directive of the Content Security Policy.

The microphone still seems to work (the waveform BG image moves while speaking). 

However, after finishing three recordings, all three play-boxes for double-checking are disabled. (I have not tried submitting the recordings this way, so I don't know if that still works.)

**Comment by mikehenrty** [comment]
Let's see if https://github.com/mozilla/voice-web/commit/c7d8fc7f63d0b4647c2c35cee1aaa6795f060a00 fixes this.

**Comment by mikehenrty** [comment]
Yup, fixed by https://github.com/mozilla/voice-web/commit/c7d8fc7f63d0b4647c2c35cee1aaa6795f060a00
