### ISSUE TITLE
Introduce automated tests?

### ISSUE THREAD

**Issue by nevik** [mozilla/voice-web#476]
There currently appear to be no automated tests in the backend nor the frontend part of CV.

Should we work to introduce them?

Or is this a deliberate decision?

**Comment by mikehenrty** [comment]
Yes please! This was not a decision, just lack of bandwidth. Now is definitely the time to start discussing these things.

**Comment by nevik** [comment]
that's great to hear!

do you have any experience/preference in terms of testing frameworks/libraries and assertion libraries? (personally, I have some experience with [Jasmine](https://jasmine.github.io/), [karma](https://karma-runner.github.io/1.0/index.html), [mocha](https://mochajs.org), and [chai](http://chaijs.com))

**Comment by kenrick95** [comment]
To chime in, I have experience at work to write unit test using [Jest ](https://facebook.github.io/jest/) (+ [enzyme ](http://airbnb.io/enzyme/index.html) for rendering React components for testing)

**Comment by mikehenrty** [comment]
Most of my testing experience is with mocha, chai, and sinon. I'm not married to any toolkit though.

Here are some test suites we need:
1. Test main server api calls (run the server, load `web/src/lib/api.ts` in a unit testing framework)
1. Test that `index.html` can be loaded
1. Test all the gulp commands

**Comment by itsravenous** [comment]
I've got a lot of experience with building React components TDD, in both Mocha and Jest, and would love to help. There doesn't seem to have been any UI tests written yet - I'd be happy to help if this is still a priority?

**Comment by Gregoor** [comment]
Happy to hear that, it is still something we very much want. I personally prefer Jest, as it imo has a better ouf of the box experience. Do you have a preference @itsravenous? And is there already a/some components you have in mind for testing?

**Comment by mikehenrty** [comment]
We now have a place to start with the tests using Jest. I'm going to close this for now, and we can open individual bugs for new tests and enhancements to the framework.
