### ISSUE TITLE
[Listen Screen] Flow

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#48]
There are several issues here I'm not sure if I should break them up in different issues.

- The general flow should be the user only needs to press on `Yes` / `No` to move on to the next sentence. No separate `Submit` button.
- Instead of the browser sound controls, we should have a `Play` button, which becomes `Repeat` after the first time it is pressed.
- After submitting, the next sentence should be loaded and the audio played automatically. The goal is to have as few user interactions as possible.
- A user should not hear the same (sentence, audio) pair more than once. 
- There seems to several types of recorded audio samples:
  * Accurate readout of the sentence
  * Medium quality, perhaps a word or two are missing
  * Nothing was recorded at all
  * Background noise
  * Something else was recorded entirely, perhaps the used accidentally pressed the record button and left it on, posing a privacy concern.
  * Profanity, or vulgar content that should be flagged.

**Comment by kdavis-mozilla** [comment]
I'm wondering if we should wait on a lot of this until the UI/UX first draft comes through later today.

I don't want to end up doing the same thing twice with the limited time we have.

**Comment by mbebenita** [comment]
Agreed, I just wanted to have some of the issues I ran into written down.

**Comment by kdavis-mozilla** [comment]
Going to close as it refers to older UI/UX
