### ISSUE TITLE
Can't use Speak

### ISSUE THREAD

**Issue by SHeredia** [mozilla/voice-web#481]
I've contributed over 350 spoken recordings but now it won't work for me.  I've tried resetting the microphone permissions and refreshing the page but it doesn't do anything when I click to record.

**Comment by mikehenrty** [comment]
Oh no!

What is your browser, and what is your OS?

**Comment by SHeredia** [comment]
I'm using Firefox on a Mac.

**Comment by mikehenrty** [comment]
Can you tell me if there are any errors in the web console?

https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console

**Comment by SHeredia** [comment]
I don't see anything written there.  I tried clicking for speaking, no message, I refreshed, no message, then I clicked to speak again, still nothing in the console section.

**Comment by mikehenrty** [comment]
Hmm, do you have multiple tabs open with Common Voice (or perhaps other tabs which use the Microphone)? Can you try in a different browser just to see if it works?

**Comment by SHeredia** [comment]
I don't have other tabs with either Common Voice or microphone access open.

I ise a Mac and can't use Common Voice with the browser it comes with.
Firefox is the only other one I have installed. What's weird is that it
worked fine for a while.

Shannon

**Comment by mikehenrty** [comment]
Yeah, and there could be more users like you having this problem. I'd love to get to the bottom of this if we can, and I appreciate your help.

Can you tell me what version of Firefox you are using? You can find out by selecting "Firefox" from the upper menu bar, then "About Firefox". In the pop-up window, there should be a number (and a date) right below the big Firefox title.

**Comment by SHeredia** [comment]
This is what it says: 55.0.3 (64-bit)

Also, when I did that I noticed that there's an update for it so I've
started that, hopefully that's all that's needed!

**Comment by SHeredia** [comment]
That did it!  I wish I'd realized there was an update sooner!

**Comment by mikehenrty** [comment]
That's great to hear. Let us know if the issue comes back.

Thanks for lending us your voice!
