### ISSUE TITLE
Debug experience: Several Files, React Dev tools

### ISSUE THREAD

**Issue by jdittrich** [mozilla/voice-web#483]
**Usecase:** I would like to step through the code and use the react dev tools. 

**Problem:** The code seems to be in one big file of 3000+ lines (at least with a source map, but still) and the react dev tools are not activated (though [they can work with preact, too](https://github.com/developit/preact/pull/339#issuecomment-252769393))

**Comment by mikehenrty** [comment]
One thing we could do here is add a "Developer Mode" which would do things like:
* disable js bundling
* output source maps
* not minify css

Perhaps we could use a command like `gulp develop` or maybe even switch the gulp default to work this way (although I usually prefer defaulting to production).

**Comment by jdittrich** [comment]
> Perhaps we could use a command like gulp develop…

Yes, that would be awesome and would have helped me to understand the project and where I could start contributing!

**Comment by jdittrich** [comment]
hi @mikehenrty any progress with this or any way I can help? I tried to configure this with gulp on my own, but I was unsuccessful.

**Comment by jdittrich** [comment]
Is that possibly solved already? I am not very experienced in TypeScript and Preact, but it seems I could now use the source maps for debugging the TypeScript of the components in the dev tools. If that is the case, it seems that `yarn start` already does what is needed.

**Comment by mikehenrty** [comment]
Yeah, I think this is mostly working. We still need to figure out how to get good stacks #592, but that is tracked in a different bug. @jdittrich if you don't mind we could close this bug.

**Comment by jdittrich** [comment]
Yes, please close, if you think it moves the general make-dev-easier
