### ISSUE TITLE
Recording is not working after first correct submittion of recordings 

### ISSUE THREAD

**Issue by Palciny** [mozilla/voice-web#486]
Enviromnent:
Nexus 5, Android 7.1.2, Firefox Nightly
Steps to reproduce:
1) Record first 3recordings
2) Play recordings - correct - submit
3) Record anither 3recordings
4) Play recordings - failed - voice was not recorded
5) If I submit these recordings Red counter adds 3points

**Comment by mikehenrty** [comment]
Can anyone else with an Android phone test this?

**Comment by mikehenrty** [comment]
@Gregoor do you have FF nightly on your phone?  Can you test this and close it if it's working? I have a feeling this was fixed at some point in the update.

**Comment by Gregoor** [comment]
@mikehenrty I was just able to record 9 recordings with FF Nightly without a hitch. So it seems to be fixed :)
