### ISSUE TITLE
Sentences use dumb quotes

### ISSUE THREAD

**Issue by rmjordas** [mozilla/voice-web#493]
I noticed that a lot of sentences use dumb/straight quotes (instead of smart/curvy quotes). I’m no typography expert but from what I understand, dumb quotes should be avoided when the text is not source code\[1\]\[2\]?

\[1\]: https://www.typewolf.com/cheatsheet
\[2\]: https://practicaltypography.com/straight-and-curly-quotes.html

**Comment by jdittrich** [comment]
I agree, that would be better. 

However, I assume it is not an urgent issue, since I see no misunderstandings arising due to using the straight quotes.

**Comment by MikeAlphaBravo** [comment]
For clarification, are you looking to change just the visible in browser " and ' to curly quotes?

**Comment by rmjordas** [comment]
Sorry bout this. I was too inexperienced with contributing when i opened this. I don't remember exactly why I opened this issue so I'm closing this.
