### ISSUE TITLE
Remove 'home' from main navigation

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#495]
Remove the ‘home’ option in the navigation. Instead, utilize the Common Voice wordmark to bring users back to the homepage. 

This is an effort to refine the user experience by improving page hierarchy through removal of extraneous UI elements and distracting color additions.

**Comment by mikehenrty** [comment]
I think we should keep Home in the mobile drop-down. What do you think @m-branson ?

**Comment by mikehenrty** [comment]
@greegoor can you take a look?

**Comment by Gregoor** [comment]
@mikehenrty .close(this)
