### ISSUE TITLE
Update/Replace 'Try it!' copy on homepage

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#496]
Replace 'Try it!' `h1` on the homepage with the copy beneath it: 'Help us validate sentences!' <-- style as `h1`, keep all `text-color: #000000`.

<img width="807" alt="screen shot 2017-10-10 at 4 48 13 pm" src="https://user-images.githubusercontent.com/18686986/31415882-d8d7eef8-adda-11e7-9abd-02def52dfb4a.png">

**Comment by MikeAlphaBravo** [comment]
Michael A. Brooks & Margaret Berry are working on this pull request with a self deadline of Sunday Oct 15th end of day.
