### ISSUE TITLE
Update footer help-links background color

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#497]
Footer `div #help-links` background color needs updating to `#e7e5e2` from `#3dfefd`. (Aligning to Mozilla brand colors.)

<img width="835" alt="screen shot 2017-10-10 at 4 54 48 pm" src="https://user-images.githubusercontent.com/18686986/31416085-c5bb2474-addb-11e7-8468-03b4ee4ca47c.png">

**Comment by heltmm** [comment]
I can take this

**Comment by mikehenrty** [comment]
closed in #506
