### ISSUE TITLE
Update footer link color

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#498]
Update footer links to match primary green `#b7d43f` UI color.

<img width="498" alt="screen shot 2017-10-10 at 5 02 34 pm" src="https://user-images.githubusercontent.com/18686986/31416302-04b3caae-addd-11e7-8f64-41a145ca5d0e.png">

**Comment by heltmm** [comment]
I can take this.

**Comment by mikehenrty** [comment]
Fixed by #505 .
