### ISSUE TITLE
Update voice-submit headline/subhead

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#499]
For `div id=voice-submit` update:

- [ ] 'Thank you!' headline to 'Review & Submit'
- [ ] 'Want to review your recording?' subhead to 'Thank you for recording! Now review and submit your clips below.'
- [ ] For now maintain styling for both.

<img width="336" alt="screen shot 2017-10-10 at 5 08 57 pm" src="https://user-images.githubusercontent.com/18686986/31416408-bb5a60ec-addd-11e7-93cc-68f38e248490.png">

**Comment by MikeAlphaBravo** [comment]
Will be working on this.  Submit by Sunday October 15th.

**Comment by margaret85** [comment]
Finished fix Friday 10/13 at 7pm PST.
