### ISSUE TITLE
Finalize SOW for Softvision for QA

### ISSUE THREAD

**Issue by geroter** [mozilla/voice-web#5]
Figure out scope of testing, writing into SOW, get over to Softvision for quote

**Comment by mikehenrty** [comment]
@geroter can you explain a bit more about what this task is about? I haven't worked with Softvision before, and am wondering what they will bring here. Bug filing?

**Comment by geroter** [comment]
This is related to the thread with Mihai.

Basically, they would put together and execute a testing plan that would look at:
- behavior as expected
- functionality cross-browser
- performance and stress testing (not sure if they can cover this)

We would probably involve them both at intermediate and final steps.

**Comment by kdavis-mozilla** [comment]
This assigned to sprint 1 which ends May 17th and we haven't even initiated contact with Softvision. Finishing this by May 17th seems unrealistic.

Can we move this to another sprint or do this internally?

**Comment by geroter** [comment]
We already have a meeting with them on Tuesday and because there's an
existing relationship it should be quick to contract.

We were going to bring the SOW to you by Thursday for review and sign off.

**Comment by mikehenrty** [comment]
Just an update here, I spoke with Softvision earlier this week. George and I are discussing this now.

**Comment by geroter** [comment]
SOW is received from SoftVision -- filed with legal

**Comment by mikehenrty** [comment]
Everything seems to be working great here, so I'm calling this done.

Yaaaay Milestone 1 finished 2 days before release! \o/ ;)
