### ISSUE TITLE
[Web] If the user denies the permission to record, give instructions to do so in Settings

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voice-web#50]

**Comment by andrenatal** [comment]
We'll need an UX for this

**Comment by mikehenrty** [comment]
Ah good flag! @andrenatal would it be possible to expose a function on `window` that calls `UIApplicationOpenSettingsURLString` on the backend so we can directly link into settings?

**Comment by andrenatal** [comment]
I guess so. Let me try.

**Comment by andrenatal** [comment]
@mikehenrty  now with this [commit](https://github.com/mozilla/voice-web/commit/a5c8ae203fa37f4d5f46997cbfaa1e9a202e1c20), if you just call `window.vcopensettings();` like [this](https://github.com/mozilla/voice-web/blob/master/ios/voicebank-ios-wrapper/index-cv.html#L46) from the webapp, it will open the phone's settings page.

**Comment by mikehenrty** [comment]
Awesome!

To be honest, I didn't know you had already implemented the open settings functionality in 77c4c669 when I made the above comment. `postMessage("openSettings")` works great too, but I didn't know it existed. But `vcopensettings` is even better haha

**Comment by andrenatal** [comment]
ha ha

**Comment by mikehenrty** [comment]
I'm hoping this is fixed in 9f45d940eecd466bb7289313e249ba2e14a12284. Will close this if so.

**Comment by andrenatal** [comment]
Worked for me.
