### ISSUE TITLE
Update Play/Stop box-header

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#500]
For `div id=voice-submit` update `p id=box-headers` 'Play/Stop' to 'Review'

<img width="83" alt="screen shot 2017-10-10 at 5 19 05 pm" src="https://user-images.githubusercontent.com/18686986/31416613-25a539f8-addf-11e7-852c-984cfdfc9eb3.png">

**Comment by AlaaSarhan** [comment]
would like to work on this
