### ISSUE TITLE
Update sentence-box background color

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#501]
For `div class="sentence-box"` update to `background-color: #e7e5e2 `.

Intent is to differentiate this as a static object and improve legibility of the black text. Additionally the play and re-record buttons will appear more ‘clickable’.

<img width="461" alt="screen shot 2017-10-10 at 5 25 14 pm" src="https://user-images.githubusercontent.com/18686986/31416730-02a234e6-ade0-11e7-8fb0-3effcd77fcc5.png">

**Comment by irmela** [comment]
I think this looks like a good issue to start with and to get to know the code base. Would like to work on this.

**Comment by irmela** [comment]
@m-branson I have one suggestion about the icon type. What about using the `redo` icon?

![common voice 2017-10-14 13-10-03](https://user-images.githubusercontent.com/6471346/31575236-25f93408-b0e2-11e7-92d2-a08cdf46ef32.png)
