### ISSUE TITLE
Update re-record icon

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#502]
For `div class=delete-box` update:

- [ ] the ‘x’ icon to a record icon -- reference #286
- [ ] green background changes to a black outline w/transparent fill
- [ ] add a hover state where button inverts to fill back with a white record icon

<img width="94" alt="screen shot 2017-10-10 at 5 31 41 pm" src="https://user-images.githubusercontent.com/18686986/31416877-f49e202a-ade0-11e7-89ed-606c5e0d52ca.png">

**Comment by irmela** [comment]
Would like to work in this.

**Comment by irmela** [comment]
@m-branson I have one suggestion about the icon type. What about using the `redo` icon?

![common voice 2017-10-14 13-10-03](https://user-images.githubusercontent.com/6471346/31575238-4687dca6-b0e2-11e7-847e-a80e1e9d6d8e.png)

**Comment by jdittrich** [comment]
@irmela: I think that would be a good choice! (maybe not *ideal* since it is not the same as undo, but certainly much better than the current "close" icon)

**Comment by mikehenrty** [comment]
I just spoke with @m-branson, and she likes the icon but I'll add a white background instead of transparent. I can do that after merging #512 .

**Comment by m-branson** [comment]
Thanks @irmela! This is a step in the right direction! For now we'll get this implemented and continue to iterate (thinking a nearly full circle with the arrow would be more inline with re-record).
