### ISSUE TITLE
[iOS] We need a png to be displayed when the user is offline

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voice-web#53]

**Comment by mikehenrty** [comment]
I see we now have an offline screen, which is great!
One thing I noticed is that when I come back online (by disabling airplane mode in my case), it still says I'm offline. Would be great to see this page come up and down dynamically as a user comes on and offline.

**Comment by MichaelKohler** [comment]
Given that the focus will be on the Web experience and not on the iOS experience, I'm closing this.
