### ISSUE TITLE
[Bug] Using back/forward button does not update the page content

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#533]
Step to reproduce:

1. Go to https://voice.mozilla.org/
2. Click on "Speak" or "Donate your voice!"
3. On the recording back, hit the back button

Expected Results:
The user returns to the home page.

Actual Results:
The URL is updated, but the content on the screen remains the same.

**Comment by VestigeJ** [comment]
I'm looking into this but running out of time - a potentially helpful link to solving the problem. 
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate

**Comment by nevik** [comment]
@kenrick95 do you know if preact-router takes care of this behavior?

**Comment by kenrick95** [comment]
It should just work as expected, [as I believe it already handles this case](https://github.com/developit/preact-router/blob/master/src/index.js#L140)

**Comment by nevik** [comment]
@Gregoor i see what you've been doing and I approve of it :D

**Comment by Gregoor** [comment]
I appreciate the approval :)
