### ISSUE TITLE
Replace getElementById/querySelector with React refs

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#541]
There are a couple of components that use `document.getElementById` and `document.querySelector`:
https://github.com/mozilla/voice-web/search?utf8=%E2%9C%93&q=document.getelementbyid&type=

Replace those with [React's ref](https://reactjs.org/docs/refs-and-the-dom.html) so it's more React-idiomatic.

**Comment by jcfausto** [comment]
I would like to work on this issue :-) I'll submit a PR most likely by this Sunday with these improvements.
