### ISSUE TITLE
Split up config and only access it one place

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#543]
- split up config into
  - user specific config
    - simple JSON file
    - gitignore it
    - add description in CONTRIBUTING.md
  - main config imports user config and merges it with defaults
- only access main config in one place and pass it through
  - https://github.com/mozilla/voice-web/search?utf8=%E2%9C%93&q=config.json&type=
  - facilitates testability

**Comment by mikehenrty** [comment]
I'm going to take a stab at this one.
