### ISSUE TITLE
Add Profile actions underneath record

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#549]
- horizontal divider
- Create Profile Button for #550 
- Why Profile link-button with closable explanation (filler text for now)

Default State:
![record](https://user-images.githubusercontent.com/4051932/31960736-f6e8c9c0-b8f8-11e7-8f5e-fbb7700330f1.jpg)

After clicking "Why a profile?":
![record-why-profile](https://user-images.githubusercontent.com/4051932/31960761-099c7a4e-b8f9-11e7-9e05-da224f666811.jpg)

**Comment by epq** [comment]
Hi! I'd like to work on this issue.
