### ISSUE TITLE
HOWTO_S3.md - Setting up S3 Storage - small typo

### ISSUE THREAD

**Issue by jcfausto** [mozilla/voice-web#560]
I found a typo on [HOWTO_S3.md](https://github.com/jcfausto/voice-web/blob/master/docs/HOWTO_S3.md) while I was setting up my local environment.

====
Create a new S3 bucket:
1. Log into your new Amazon Services account:
2. Choose "S3" under the "Storage" **catagory** in the "Services" drop down.

====

The word "catagory" should be corrected to "category". 

Shall I fix and and submit a PR for this quick fix?

**Comment by mikehenrty** [comment]
> Shall I fix and and submit a PR for this quick fix?

Yes please! Good catch!

**Comment by jcfausto** [comment]
Ok. I'll do it.
