### ISSUE TITLE
Review Recordings Redesign

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#566]
rrrr

Maybe extract the record text-box card into its own component, so we can reuse it here.

![review-summary](https://user-images.githubusercontent.com/4051932/32110404-bf8aee86-bb37-11e7-8042-483a5356002f.jpg)

**Comment by nevik** [comment]
@Gregoor are the new "play" and "re-record" icons shown here available somewhere?

also, would be great if you could describe/highlight (e.g. in screenshot) what part of the (re)design is part of this ticket :)

**Comment by Gregoor** [comment]
@nevik Right, good points! We don't have an export of these assets yet, so for now placeholders would need to be used. I'll add them to this card, as soon as we have them.

#564  and #550 cover the profile stuff under the `<hr/>`, so this issue only relates to:
![screenshot-2017-10-29 32110404-bf8aee86-bb37-11e7-8042-483a5356002f jpg jpeg image 2880 x 3156 pixels](https://user-images.githubusercontent.com/4051932/32146548-6e60a976-bcd9-11e7-8f8b-4eb8b6ca0fef.png)

**Comment by Gregoor** [comment]
Okay okay I'll do it 👷

**Comment by Gregoor** [comment]
Alright, I'll take it
