### ISSUE TITLE
Submit Success "alert"

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#567]
Create a closable alert component where one can supply a text as a child. We're going to reuse that one!

And then we need to show it after recordings where submitted (as seen below). Probably best if the alert is also closed, when the user clicks record.

![submit-success](https://user-images.githubusercontent.com/4051932/32110684-6d70e4e2-bb38-11e7-8980-d440634110f6.jpg)

**Comment by aerohitk** [comment]
@Gregoor I would like to take a shot at this, if that's alright?

**Comment by Gregoor** [comment]
@aerohitk that's more than alright :)

**Comment by nevik** [comment]
@Gregoor i'd prefer to name this element a "notification banner" or similar. For me, an "alert" (at least in a web context) refers to something like a popup or modal dialog - from what I can tell, the element we want here is not as aggressive as that.

**Comment by Gregoor** [comment]
@nevik while I agree with you about the literal meaning of an alert, this is the naming bootstrap & foundation went with for such a component. So, it's hard to say what's the web standard here.
Notification is imo a bit off as well, since we do have real notifications on the web now.

**Comment by nevik** [comment]
fair enough, then let's keep the nomenclature that way :)
