### ISSUE TITLE
Unsupported signature version for S3 when using eu-central-1 region

### ISSUE THREAD

**Issue by jcfausto** [mozilla/voice-web#569]
**The problem**
When loading the home page, the requests to GET the audio resources are being rejected by AWS due to unsupported signature version. As a consequence, I cannot play the audio clips in the listen-box component. This component stays disabled.

```sh
GET https://mozz-voice-web-eu-01.s3.eu-central-1.amazonaws.com/...&Signature=8DI5xX66DyqpTMOFR8i4oYFrX0k%3D 400 (Bad Request)
```

```xml 
<Error>
    <Code>InvalidRequest</Code>
      <Message>
        The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
      </Message>
    <RequestId>227B51E6364C0B16</RequestId>
    <HostId>
        ...
    </HostId>
</Error>
```
**The cause**
I did my S3 setup to use eu-central-1 region (Frankfurt). This region, and most of the recently created ones, doesn't support the signature version 2. They now require the signature version 4. 

Two S3 instances were created inside the server. One was created with the signature V4 defined, but the other one wasn't. This cause the requests to be created with signature version 2, leading to the error described. 

**Proposed solution**

I did some modifications on the server code to have a single point of creation for the S3 object and the classes that need this object inside the API now receive this object through their constructors. This way we avoid some duplication and also the risk of having different instances of S3 initialized with different parameters. 

Also, I added a step 3 to aws CLI configuration section in the HOWTO_S3.md file just to make sure that the CLI will also use as default the signature version 4. 

Please take a look at the changes here [https://github.com/jcfausto/voice-web/commit/1053d8538be5458dca71b1c86e6cd593b6df1a41](https://github.com/jcfausto/voice-web/commit/1053d8538be5458dca71b1c86e6cd593b6df1a41 ) and let me know if you'd like to have a PR submitted for this issue. 

Kind regards, 

Julio.

**Comment by mikehenrty** [comment]
excellent analysis @jcfausto ! yes please submit a PR based on your branch above. thank you!

**Comment by jcfausto** [comment]
Cool. Thanks, @mikehenrty. PR submitted.
