### ISSUE TITLE
Save Profile Success Alert

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#579]
When alerts are implemented (#567), we'll also need to add one for profile creation (inside of the record page):

![Save Alert](https://screenshots.firefoxusercontent.com/images/a7221603-87c7-4715-8b73-7eb0e2530f87.png)

**Comment by Gregoor** [comment]
Hi @aerohitk, are you still interested in looking into this? If not, I would take it over tomorrow or beginning of next week.

**Comment by aerohitk** [comment]
@Gregoor sorry, I've been busy with work recently. I'm definitely still interested, but I probably won't have time to work on this until the weekend. Let me know if this can wait that long.

**Comment by Gregoor** [comment]
@aerohitk no worries, just wanted to have the redesign done next week but I've got plenty of other stuff to do, so it can wait this long.

**Comment by aerohitk** [comment]
@Gregoor submitted a PR. Is there anything else I can help with?

**Comment by Gregoor** [comment]
Thanks @aerohitk, will review it first thing tomorrow.

#625 is definitely something we want to get done this week, so if you want to look it in one of the next days, feel free to grab it.
