### ISSUE TITLE
[web] Refactoring list & discussion

### ISSUE THREAD

**Issue by nevik** [mozilla/voice-web#582]
From looking through and working with the code, I've found a few things I'd like to improve by refactoring. Overall, the goals here are improved legibility and thereby improved maintainability and extensibility, for an overall more robust and better-quality code base.

The idea is that this is a jumping off point for the things I've collected so far.
If certain points are rejected entirely by the maintainers, we can drop them immediately in this ticket.
If certain points need more detailed discussion or are chosen to be implemented/applied, we should create separate tickets for them to track their progress.

_Note: I'll probably update this top post to keep the list up-to-date, e.g. crossing out dropped items and linking to newly created issues._

---

* prefer named exports over default exports (reasoning e.g. [in the TS deep dive book](https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html))
  * note: applies to server code as well
* use `obj.addEventListener('event', …)` instead of `obj.onevent = ...`
* use more [destructuring declarations](https://www.typescriptlang.org/docs/handbook/variable-declarations.html#object-destructuring)
  * see #578 for examples of this style
* extract interface for `AudioWeb` and `AudioIOS`, and move `AudioInfo` to separate file (`AudioWeb` and `AudioIOS` should not depend on each other)
* overall: split the big components into smaller parts, following the single-responsibility principle, and trying to keep any single component and class to sizes that don't become unwieldy
  * e.g. `pages.tsx`: try to make this smaller
* `not-found.tsx` / all pages: prop ‘active’ (and other there-or-not props deciding states like activeness, visibility, etc.) should be boolean (and mapped to appropriate classNames inside the component that applies them)
* ~`record.tsx`: extract “why profile” box to separate component~
  * done in #578 
* `record.tsx`: extract “UnsupportedPlatform” content to separate component
* `record.tsx`: only render `#voice-record` / `#voice-submit` boxes in the actual state they belong to
* `index.css`: move all `@import`s to start or end of file 
  * optionally, extract CSS rules to a `global.css`, so that index.css is only an entry point with imports
* `index.css`: Icon-related CSS should be split to `icon.css` next to `icon.tsx`

**Comment by Gregoor** [comment]
I agree with most of those. At first I was a bit hesitant on not using default exports anymore, but there's some good reasoning there. Though refactoring could also be solved by better tooling and there might just be eslint rules for enforcing default imports to match the module name.
___
Moving `@import`s to the top of the file, is an issue that requires disentangling the cascade. Also while we're at it we might want to look for a solution that makes writing styles more explicit (which imo means, less cascadey) and makes it less likely to introduce unused styles. My favorite solutions for that is still [styled-components](http://styled-components.com/). But I'm open to other solutions as well. I think @kenrick95 might have an opinion on that as well.

**Comment by nevik** [comment]
re: default exports:
i prefer using the compiler for what it can do, instead of relying on the linter :)

re: `@import`s:
yeah, i think reducing the cascading of the style sheets a bit is a good idea. other than some global styles (e.g. regular links), i think the idea of components is good for also encapsulating styles with them (and scoping them so closely they're not likely to affect other things, if not using styled-components).

**Comment by kenrick95** [comment]
Re: CSS imports: I agree that styles written for a component should be encapsulated within the component. But to me, using styled-components, could be quite a big change from what is already being used. One style that I like (and is being used at my daily job) is writing a style (SCSS) file alongside a component with a BEM naming convention (the "block" being the component itself) and then at the component, we'll call "`import './style.scss'` (and our build tool (webpack) will bundle all of them together into one CSS file. There are some caveats like sometimes the style cascading is different on dev build and production build, but more or less, we're happy with it.

**Comment by Gregoor** [comment]
Thanks for compiling that list, I think most of it was adressed. There's definitely still ample room for refactoring, but let's discuss that in separate specific issues.
