### ISSUE TITLE
[link] Possible resource: BBC speech-to-text project

### ISSUE THREAD

**Issue by jibe-b** [mozilla/voice-web#584]
In case it stayed out of your radar:

http://www.bbc.co.uk/rd/projects/speech-to-text

**Comment by mikehenrty** [comment]
Great @jibe-b ! I wasn't aware of that, and I've added it to a list I have for places to investigate :)

cc @kdavis-mozilla

**Comment by kdavis-mozilla** [comment]
I've talked with this group extensively. We are not able to use any of their data due to legal constraints
