### ISSUE TITLE
(Maybe) move to React 16

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#591]
We're considering moving to React 16, as it has some niceties we'd want (and it's not foreseeable that Preact will get those anytime soon). Those are:
- [ability to return null, arrays, strings,...](https://reactjs.org/docs/react-component.html#render)
- [portals](https://reactjs.org/docs/portals.html) 🌌 
- larger ecosystem, as some modules are already using React 16 exclusive features, which makes them preact-incompat

The cons are:
- 32kb extra size
- some code modifications needed
  - replace `class=` with `className=`
  - some typing stuff
  - AFAIK refs are handled a bit differently 

___

If anyone has an opinion on it, feel free to participate in the discussion. I'll update the list above accordingly.

**Comment by Gregoor** [comment]
Okay, I hit a blocker. In our "router" we're using preact's top level render function and its third argument, which is `replaceNode`. Now I'd just remove the element given for `replaceNode` before rendering, but that is bound to have a perf penalty as React would rebuild the DOM (in contrast to preact's-render with `replaceNode` which tries to update it). Short term, for the React migration we could just turn `app.tsx` into a Component, longer term we should probably just add a routing lib, to minimize the amount of code we have to maintain.

**Comment by mikehenrty** [comment]
I'm all for cleaning up `app.tsx`, it's a little bit of a frankenstein's monster right now
