### ISSUE TITLE
[Sourcemaps] Call stack is wrong

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#592]
If I set a breakpoint somewhere in a TypeScript file (like api.ts for instance), when the browser pauses, the callstack will show a bunch of random places in the code rather than the actual function calls that led to where we are.

Perhaps this is because the preact sourcemap is missing?

**Comment by Gregoor** [comment]
After #615 has landed, this could be solved like this:
- use `cheap-module-eval-source-map` in `webpack.dev.config.js`
- `"sourceMap": true` in tsconfig
- disable the CSP header during development (use the config.prod flag)
