### ISSUE TITLE
Landing Page Redesign

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#594]
This is what it should look like:
![landing](https://user-images.githubusercontent.com/4051932/32338631-a5330452-bff5-11e7-8a34-984138de2342.jpg)

For the welcome message, I'd go with:
"Project Common Voice is a Mozilla venture to make quality voice data more readily available."
But I hope @mikehenrty has something better for it 🙃 

Functionality wise we got:
- the "speak up, contribute here!"-button should navigate to "/speak", just like "Donate your voice" currently does
- the wall of text is now collapsable (and collapsed by default). Once collapsed, we probably don't need a way to uncollapse it (so no need for a "Read less"-linkbutton)
- The Validator is very similar to the current one, afaik only the buttons need to be restyled
- the overall project status is a different issue (#595)
- the new menu positioning is also a different issue (#596)

**Comment by mikehenrty** [comment]
For the welcome message, how about:

"The Common Voice project is Mozilla's initiative to help teach machines how real people speak"

**Comment by Gregoor** [comment]
3... 2... 1... Meins! (I'm looking into it now)

**Comment by ukii** [comment]
@Gregoor I've also started working on this. Do you need any help? If you do, can we somehow coordinate, so I can take some load of the work.

**Comment by Gregoor** [comment]
@ukii oh great! Then I'll leave it to you and won't touch anything home-related. I'll be working on the menu #596 then, so you don't have to think about the positioning of the robot or background image for now. Lmk if there's anything else you need!
