### ISSUE TITLE
Listen not working in IE11

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#597]
Since I learned today that we're supporting, I took that bad boy for a ride around our site. Unfortunately the listen-box just said `undefined` 😞 
Of course my first reaction was to check GA to see whether I can rationalize the problem away, but we did indeed have ~70 IE11 sessions in the last month, so there's people we're letting down. If there's an IE veteran here who'd like to take this on...

**Comment by Gregoor** [comment]
[Looks like it broke again](https://bugzilla.mozilla.org/show_bug.cgi?id=1464624)

**Comment by mikehenrty** [comment]
from bugzilla:
> In JS code is using 'class' tag. Some browsers, including IE 11 (default for Windows 7), Firefox < 45, Opera and others, don't support this tag. So, in the best case about 3% (30 millions) users can't use voice.mozilla.org and watch on white screen.

**Comment by Gregoor** [comment]
For various reason we decided to stop supporting IE11 for now.
