### ISSUE TITLE
Standard approach - Harvard Sentences

### ISSUE THREAD

**Issue by praxnex** [mozilla/voice-web#598]
In the 1980's many speech recognition projects used the so-called "Harvard Sentences". These provided overlapping coverage of synonyms, transitions, and diphones. These are well understood and therefore have codecs to decompose and associate with dictionaries.
The general collection of speech as in the Mozilla voice app, tends to help with cultural and regional variation in pronunciation. Additional speaker identification (if feasible) helps by associating gender, age, early (<6) and late (>12) language environments and location, etc.

**Comment by mikehenrty** [comment]
Great find! Looks like the Harvard Sentences live here:
http://www.cs.columbia.edu/~hgs/audio/harvard.html

Would be great if someone could make a PR adding a `harvard-sentences.txt` file with the above sentences into the `server/data` folder.

**Comment by mikehenrty** [comment]
Looks like there are a bunch of other sentences here:
http://www.voiptroubleshooter.com/open_speech/index.html

**Comment by iveskins** [comment]
There is a lot more sentences hosted here
http://www.cs.cmu.edu/afs/cs.cmu.edu/project/fgdata/OldFiles/Recorder.app/utterances/
The http://www.cs.cmu.edu/afs/cs.cmu.edu/project/fgdata/OldFiles/Recorder.app/utterances/Type1/ folder seems to have sentences grouped by phoenetic features.
I could make a PR, but what about usage rights?

**Comment by mikehenrty** [comment]
@iveskins the hardvard sentences look like fair game to me (i didn't see copyright information on any of the sites hosting it, but there is language that says we can "freely use" them.

for the other utterances you found, i couldn't find any licensing information at first glance. if we can find something like that, I think we will be able to use it.

**Comment by iveskins** [comment]
So looking at https://www.lti.cs.cmu.edu/directory/all/154/1, there is a list of staff, some of whom might know about these files.. 
Maxine Eskenazi who wrote a book "Crowdsourcing for Speech Processing" , might be interested in helping. 
I could email and ask if there is anyone who could give information about the licensing of those files. But is that in the scope of public contributing to this project?

**Comment by mikehenrty** [comment]
@iveskins that would be super helpful if you would start that conversation! feel free to include me on the cc list if you like (mikey (at) mozilla.com). thank you for helping investigate this!

**Comment by mikehenrty** [comment]
Since we already have the Harvard Sentences, let's close this bug and open a new one (or PR) with any other datasets.
