### ISSUE TITLE
Spritesheet our Robot

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#602]
Right now, we load and swap svg images for our robot. This leads to unpredictability for when the image actually updates on the screen, and is not good network performance. We should put all the robot images in a spritesheet, and use background-position.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images/Implementing_image_sprites_in_CSS

**Comment by jdittrich** [comment]
For people who want to pick this up:
* The robot images are in `/web/img`: 
![image](https://user-images.githubusercontent.com/3416487/33238790-a414d828-d294-11e7-8738-ba0975258b8d.png)
* Currently, the image is swapped by adjusting the scr-parameter of an `<img>` in the react `robot` component, but CSS-classes which correspond to the different robot states/images are already in place.

@mikehenrty: 
* Does it need any tool-ish approach or should it be done manually (= copy/paste robots in one SVG and adjust CSS classes with correct positions)?

**Comment by Gregoor** [comment]
@jdittrich Thanks for the summary!

One could do it by hand, but that'd be pretty tedious. A tool such as [this](http://draeton.github.io/stitches/) one which also generates the CSS background-positions should make it much easier.

**Comment by mikehenrty** [comment]
Thanks for the thorough investigation @mrchrisadams !

Based on your findings, I don't think it's worth the complexity of adding a spritesheet for the robot this time. In addition to the change in file size, we only use 2 robots now. Let's close this bug, and re-examine later if we start using the robot again.
