### ISSUE TITLE
[Slack] help us set up an auto-invite bot for slack.

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#604]
We already set up a Slack channel, common-voice.slack.com. But unfortunately, we haven't had time or knowledge to set up the auto-invite bot. If someone out there would like to help us out, we would switch from IRC to Slack for our official chat channel.

**Comment by Gregoor** [comment]
https://common-voice-slack-invite.herokuapp.com/
@mikehenrty Should we put in the README, CONTRIBUTING or directly on the site? Personally, I'd go with 1 & 3.

**Comment by mikehenrty** [comment]
Brilliant!
