### ISSUE TITLE
Listen box should have white background, not transparent.

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#606]
The listen box component has a dom element that displays the text of the sentence being read. Right now, this element has a transparent background, and so you can see content behind it whenever it overlaps. Let's make it white instead.

**Comment by ac-rossello** [comment]
I've been investigating this issue. I'm not sure, but it appears to me as though this issue has already been solved. Right now, I believe the sentence-box element is only transparent when a voice clip has not been loaded, and is opaque when a voice clip has been loaded.

**Comment by mikehenrty** [comment]
Yup, I think you're right @ac-rossello, it's not an issue anymore. Thanks for your help!
