### ISSUE TITLE
Review button during playback not working 

### ISSUE THREAD

**Issue by iveskins** [mozilla/voice-web#608]
After recording a set of sentences, when reviewing your recordings, if you press the play button on a sentence and then while the audio is still playing, press the re-record button, the re-record button will be highlighted black, and the audio will stop, but you won't be taken to the redo page. At this point you have to push the re-record button again.
I expected the button to work the same way (one touch) even if audio is playing.

**Comment by benjamin21st** [comment]
Can I take this one?

**Comment by benjamin21st** [comment]
I think i found the culprit, small fix, will send for PR in a bit :)
