### ISSUE TITLE
[Proposal] Add support for OpenStack Swift API

### ISSUE THREAD

**Issue by realitix** [mozilla/voice-web#614]
Hello,
Currently, *voice-web* needs Amazon S3 to work properly. I tried some hacks to make it work with OpenStack Swift but it's not straightforward and buggy.

What do you think about adding support for OpenStack Swift API ?

Sincerely,
Jean-Sébastien Bevilacqua

**Comment by mikehenrty** [comment]
I like the idea!

The other approach would be to allow saving and loading clips from the local file system. The server actually used to work this way, and I hope it wouldn't be too bad allowing that option.

Here's the commit where we switched to S3:
https://github.com/mozilla/voice-web/commit/83088c8f6c161a6db8340e8f3fb4bce5aa646e06

**Comment by mbransn** [comment]
@phirework can I get your opinion here?

**Comment by phirework** [comment]
I don't envision our team having the bandwidth supporting any other storage mechanism any time soon, but if someone wants to fork our repo and add workarounds for their own implementation they're more than welcome to do it.
