### ISSUE TITLE
Re-thinking the existing verification module

### ISSUE THREAD

**Issue by kjanko** [mozilla/voice-web#618]
I think the verification module can be totally removed for the English version of Common Voice.
I propose to use an existing production STT system that'd label the speech that was recorded by the user. Then we can use doc2vec to convert the labeled sentence into a vector and compute the distance to the original sentence vector. If the distance is above a certain threshold (should be statistically tested - and the STT system's WER should be taken into consideration) we can say that the sentence is valid.

**Comment by DNGros** [comment]
This could be a good way of speeding validation. Though, I don't think the human can go out of the picture. The goal is to improve on existing openly available systems, so there could be a lot of false negatives. Using a doc2vec threshold could help, but ideally you want the cleanest data and avoid anything but an exact match.
But there could be a system where you run it through a existing SST system, and if it exactly matches, you don't ask for verification. It could certainly help get through them a lot faster.
The necessity of this of this is dependent on whether the project is currently way behind on validation, or if enough people are validating that it is pretty caught up. One of the maintainers would have to say what the state is.

**Comment by iveskins** [comment]
What about speech that is accented, has bad audio quality, or for some reason would not be identified correctly with existing stt systems. I sometimes find myself having to use an american accent to even get google stt to give me the word I want. Would this introduce a bias into the data that is not there with human validation?

**Comment by kjanko** [comment]
@iveskins that's where the threshold would come into play. If appropriately chosen it shouldn't introduce any bias. But without seeing the data distribution It's hard to say. Another approach would be removing outliers from clusters where each cluster would be a single sentence.

**Comment by mikehenrty** [comment]
Validation is indeed an ongoing problem for Common Voice. We get about 2 validations for every recording. We "verify" a clip by a 2 out of 3 vote, so in an idea world 2 validations would be enough. In reality, some "controversial" recordings require 3 votes to verify. So we are indeed behind.

We plan to expose this information on the homepage so that users can see how far behind we are. We probably won't include this feature before next month though, when we plan to release the data.

**Comment by MichaelKohler** [comment]
I'm closing this, please feel free to open a discussion at https://discourse.mozilla.org/c/voice/239 in case this needs to be discussed further.
