### ISSUE TITLE
Project Status Card

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#625]
We don't have an API endpoint for it yet, so the values can be hardcoded for now.

For positioning of the component, see #594 

![project-status](https://user-images.githubusercontent.com/4051932/32701283-f7bf821a-c7d2-11e7-9ba7-79cccf6ebbad.jpg)

**Comment by DNGros** [comment]
What do the Goals correspond to? Release checkpoints or something else?

**Comment by Gregoor** [comment]
@DNGros For now we'll only show the number of validated hours, but we might show other metrics at a later point in time.
