### ISSUE TITLE
Type annotations for Redux

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#635]
Atm only `connect` and the user store is annotated. Would sure be nice to have everything related to the store annotated (where feasible).

**Comment by mikehenrty** [comment]
@Gregoor coming from a Redux n00b, what does annotation give us?

**Comment by Gregoor** [comment]
@mikehenrty nothing Redux specific, just type safety. First time I'm using Redux with Typescript (have used it with Flow a couple of times) and still have some catching up to do on typing best-practices.
