### ISSUE TITLE
Text for Dataset page

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#636]
https://github.com/mozilla/voice-web/blob/3670398077bbf02074a81a09e431e5aa3b032207/web/src/components/pages/data/data.tsx#L111-L125

**Comment by mikehenrty** [comment]
The text is at the bottom of this page

![image](https://user-images.githubusercontent.com/635365/33032236-e4e5536e-ce20-11e7-8678-88d3d4d3889b.png)
