### ISSUE TITLE
[Download] Download data button on page needs adjusting

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#645]
Download data button needs some adjustments:

1. Space between "Common" and "Voice"
2. Font weight value should be "600" (SemiBold) rather than "bold"
3. Download icon on button should be 22px width and height
4. There should be a 4px hard drop shadow of 15% black opacity
5. Space between Download button and license link below should be 3x the current space
 
![white-button](https://user-images.githubusercontent.com/1466558/32929196-4f1982dc-cb24-11e7-9472-9c0f9568d12a.png)

cc/ @m-branson

**Comment by ivonnekn** [comment]
@Gregoor  apologies for this change but can we reduce the top margin on the license link to 0.5em from it's current 1em? I think I went too far in my suggestion.

**Comment by Gregoor** [comment]
no apology necessary :)

**Comment by ivonnekn** [comment]
@Gregoor Thanks for that fix. Though I think we lost the underline on the link?

**Comment by ivonnekn** [comment]
seems to be fine now
