### ISSUE TITLE
[Navigation] Text should be bold 

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#647]
Navigation text should be in bold but appears too thin?

cc/ @m-branson

**Comment by ivonnekn** [comment]
On further investigation I see that the font weight is being applied but on Chrome the text appears thin. Though on Firefox it looks great. 

Chrome:
![nav-chrome](https://user-images.githubusercontent.com/1466558/32931506-96d10808-cb32-11e7-9f0e-33273e8f8490.png)

Firefox:
![nav-firefox](https://user-images.githubusercontent.com/1466558/32931507-96e59fc0-cb32-11e7-873a-390bff54cca7.png)

**Comment by nevik** [comment]
This could be a combination of browser, OS and screen DPI.

What OS and hiDPI / regular DPI screen did you test this on?

**Comment by ivonnekn** [comment]
Viewed this on macOS Sierra v10.12.6 / 11.6 inch MacBook Air at 1366x768

**Comment by Gregoor** [comment]
@nevik do you happen to be on a MacBook? Cause it looks identical on FF vs Chrome on Windows with my T450s at 1080p.

**Comment by ivonnekn** [comment]
@Gregoor Did you make an adjustment to this? Today I opened this on Chrome and text looks good.

**Comment by Gregoor** [comment]
@ivonnekn huh, that's strange. Not consciously, no. 🙈

**Comment by Gregoor** [comment]
So we're good here, right @ivonnekn?

**Comment by ivonnekn** [comment]
Yes @Gregoor. Seems to be fixed somehow :)
