### ISSUE TITLE
[Download] Partner card styles needs adjusting

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#649]
Partner card has some styles that need adjusting:

1. Red color for headline text should be hex value #FF4F5E or rgb(255, 79, 94)
2. Headline text should be regular font weight (not hold)
3. Paragraph and link text color should be hex value #4A4A4A

![screen shot 2017-11-16 at 11 47 53 pm](https://user-images.githubusercontent.com/1466558/32929809-9f3362f2-cb28-11e7-910f-8ddc71311147.png)

cc/ @m-branson

**Comment by ivonnekn** [comment]
@Gregoor Can you also make the link color of the license link in they same grey? (note that the link in the paragraph text above all these cards should remain black)

**Comment by mikehenrty** [comment]
Re-opening based on @ivonnekn comment.

**Comment by Gregoor** [comment]
Thanks Michael, would have overlooked it 🙈

**Comment by ivonnekn** [comment]
verified
