### ISSUE TITLE
[Download] Initiate download not in place

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#658]
@Gregoor Clicking on download buttons take us to Mozilla.org website. This may just be placeholder for now, but flagging it.

Here's the dialog that should appear when download is initiated:
![download-success](https://user-images.githubusercontent.com/1466558/32954720-e28e2150-cb81-11e7-9dfd-7d914dc095be.png)

cc/ @m-branson

**Comment by ivonnekn** [comment]
The dialog is now in place and looks great, but the link still opens the mozilla.org website and does not begin download of the data file.

**Comment by Gregoor** [comment]
Thanks for flagging this. I'm gonna assign @mikehenrty because he might already have some of those links.

**Comment by mikehenrty** [comment]
great flag. making it also a release blocker.

**Comment by mikehenrty** [comment]
Fixed in https://github.com/mozilla/voice-web/commit/598a0027ac7aeef4246134d2267b7eb2726739bd
