### ISSUE TITLE
Include Nepal in South Asia Accent.

### ISSUE THREAD

**Issue by Avasz** [mozilla/voice-web#662]
Please include Nepal in the accent of South Asia.

We are planning to have a small event for this in Nepal, and it will be great if we can select it while contributing to it. Even better if all the countries of South Asia are listed there. :)

**Comment by Gregoor** [comment]
Thanks for starting the discusssion, if it's alright with you let's continue it in the PR (referenced above) and in the mor general issue #242

**Comment by nukeador** [comment]
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
