### ISSUE TITLE
Home page missing progress widget

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#670]
Home page is missing progress widget. 

![screen shot 2017-11-19 at 5 17 49 pm](https://user-images.githubusercontent.com/1466558/32996188-ba886c4c-cd4d-11e7-8e1b-b2af670bb4b3.png)

cc/ @m-branson

**Comment by Gregoor** [comment]
duplicate of #625 (marked it as a design-blocker just now)

**Comment by ivonnekn** [comment]
@Gregoor Can we capitalize the Y and V in "Contribute your voice" text link?

**Comment by ivonnekn** [comment]
verified :)
