### ISSUE TITLE
Review & submit record screen buttons and links need adjustments

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#672]
- the submit and create a profile buttons should be same width
- submit button should be black button with white text
- increase top and bottom margin around Submit button by 150% of what it is now
- increase margin above Create a Profile button by 150% of what it is now
- Why a profile? link should be semibold (600) font weight

![screen shot 2017-11-19 at 5 25 33 pm](https://user-images.githubusercontent.com/1466558/32996297-d1740b2c-cd4e-11e7-962f-933a808b4eec.png)

cc/ @m-branson

**Comment by ivonnekn** [comment]
@Gregoor this is still relevant:
- increase top and bottom margin around Submit button by 150% of what it is now 

Also:
- Cancel Submission text link should be semibold, not bold

cc/ @m-branson

**Comment by SimonHFrost** [comment]
Hi, I opened a PR that addresses these two small changes. Hope I didn't step on anyone's feet 👼
