### ISSUE TITLE
Profile screen needs margin above profile box

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#680]
Please add a 3em top margin above profile box on Profile page:

![screen shot 2017-11-19 at 6 08 43 pm](https://user-images.githubusercontent.com/1466558/32996752-e898ae4c-cd54-11e7-8704-99f5944d5b36.png)

cc/ @m-branson

**Comment by ukii** [comment]
Does this only needs to be fixed on profile page? Cause I think there also should be top margin when you open "Create a profile" from the Speak page.
![image](https://user-images.githubusercontent.com/18581861/33021170-2ff35628-ce01-11e7-95ae-fd8a8d872a02.png)

**Comment by ivonnekn** [comment]
@ukii  @Gregoor  Agree with @ukii's comment. There should be more spacing above the create profile box on the Speak page as well.

**Comment by m-branson** [comment]
@ukii @Gregoor @ivonnekn 50px top margin for the profile form in all instances (record flow and on profile page) is desired. Thanks!

**Comment by ivonnekn** [comment]
verified
