### ISSUE TITLE
Buttons should have hard corners (not rounded)

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#683]
Most buttons have rounded corners when they should all have hard corners. This occurs in many places.

![screen shot 2017-11-20 at 10 07 24 am](https://user-images.githubusercontent.com/1466558/33025022-bf6f805a-cdda-11e7-94f5-18261fa4bca1.png)
![screen shot 2017-11-20 at 10 07 16 am](https://user-images.githubusercontent.com/1466558/33025023-bf7a8c48-cdda-11e7-9202-e92ab19e1412.png)
![screen shot 2017-11-20 at 10 07 10 am](https://user-images.githubusercontent.com/1466558/33025024-bf85b032-cdda-11e7-963f-817917245640.png)
![screen shot 2017-11-20 at 10 07 06 am](https://user-images.githubusercontent.com/1466558/33025025-bf92e248-cdda-11e7-95f0-f0bfa9878835.png)
![screen shot 2017-11-20 at 10 05 11 am](https://user-images.githubusercontent.com/1466558/33025026-bf9f1cfc-cdda-11e7-9539-63139331ba21.png)

cc/ @m-branson

**Comment by Gregoor** [comment]
Hi @iveskins, I can't seem to reproduce it. Can you check again (after a hard-reload)? I looked at it in FF & Chrome on both staging and prod and couldn't find rounded borders.

**Comment by m-branson** [comment]
@ivonnekn @Gregoor I'm also seeing hard corners in FF.

**Comment by ivonnekn** [comment]
@Gregoor @m-branson Seeing a discrepancy on Chrome on Mac OS X

Seeing this in the latest version Version 62.0.3202.94 (Official Build) (64-bit). I think the browser is setting a default border-radius of 4px. Might be worth setting an explicit border-radius: 0 to be sure?

**Comment by Gregoor** [comment]
yaiks, looks like chrome made the change to rounded buttons in their user agent styles. Fortunately the outcry was already large enough that they reverted the change (https://bugs.chromium.org/p/chromium/issues/detail?id=752450).

**Comment by ivonnekn** [comment]
@Gregoor  Happy to close this out since they're reverting it :)
