### ISSUE TITLE
Dropshadow button hover states

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#684]
The hover state on this button style in the Download page is too harsh and there is no hover state on this button on the home page.

Please add/adjust hover states of these drop shadow buttons to do the following on hover:

1. change opacity to 80%
2. remove box shadow
3. shift button down by 1px
4. shift button to the right by 1px

![screen shot 2017-11-20 at 3 04 26 pm](https://user-images.githubusercontent.com/1466558/33038902-2ec1ca2a-ce04-11e7-8023-713b002af9c8.png)
![screen shot 2017-11-20 at 3 04 08 pm](https://user-images.githubusercontent.com/1466558/33038903-2ecf7526-ce04-11e7-96da-8b76fd270c91.png)

cc/ @m-branson

**Comment by Gregoor** [comment]
I hope I got this one right @iveskins. Lmk what you think :)

**Comment by iveskins** [comment]
@Gregoor check your autocomplete I think you mean @ivonnekn ;)

**Comment by Gregoor** [comment]
🙈 sorrythanks

**Comment by ivonnekn** [comment]
@Gregoor I forgot to mention that the color should remain white background with black text and colored icon on hover :)

**Comment by Gregoor** [comment]
@ivonnekn like this? I assumed the dataset download buttons should still change bg color?

**Comment by ivonnekn** [comment]
@Gregoor Yes the "Download Common Voice Data" button looks great on the download page now. And yes the download buttons on the partner cards should remain as is.

However, the home page Speak button doesn't shift in the same way and the drop shadow is still there. Let's make that consistent with the "Download Common Voice Data" hover state.

**Comment by ivonnekn** [comment]
verified
