### ISSUE TITLE
Re-record screen needs ability to cancel re-record

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#688]
On the record screen, when it is a re-record, please add a **Cancel Re-recording** text link positioned to the right of the record button, right aligned with the box above. See InVision mockup for reference. This text link should be styled like the other text links (ex. Why a profile?)

**Comment by Gregoor** [comment]
Didn't find a re-record screen so I freestyled it from your description.

**Comment by Gregoor** [comment]
Didn't find a re-record screen so I freestyled it based on your description.

**Comment by ivonnekn** [comment]
@Gregoor looks good, thanks!
