### ISSUE TITLE
[Mobile] FAQ and Terms page overlaps with header

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#694]
![photo5240275347604351174](https://user-images.githubusercontent.com/635365/33184967-d4cb65a2-d07f-11e7-937d-8b3fe965c3a1.jpg)

**Comment by Gregoor** [comment]
@mikehenrty given that I see the old hamburger icon there, I'd assume this is on prod? It's fixed on staging.

**Comment by mikehenrty** [comment]
Great!
