### ISSUE TITLE
[Mobile] Validate text too small

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#711]
On home page in mobile/small screens, the validate text is too small. Please maintain the same font size as on desktop.

![screen shot 2017-11-27 at 11 54 39 pm](https://user-images.githubusercontent.com/1466558/33303036-59832ffe-d3ce-11e7-8013-b41e8a5141c8.png)

cc/ @m-branson

**Comment by Gregoor** [comment]
@iveskins the same size was used on mobile and desktop. I changed it to scale up a bit on mobile.
