### ISSUE TITLE
[Mobile] Subfooter needs adjustments to icons

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#714]
On mobile screens, adjust the subfooter with the icon links such that:

1. divider lines are gone
2. size of icon and text are reduced by 20%

![screen shot 2017-11-28 at 12 10 23 am](https://user-images.githubusercontent.com/1466558/33303368-d5061d42-d3d0-11e7-9d0d-865919f4dd14.png)

cc/ @m-branson

**Comment by jdittrich** [comment]
when touching this, we could also fix the strange outline widths of the Discourse icon.

**Comment by flyingpimonster** [comment]
@jdittrich That appears to have been fixed in commit ea761fb.

**Comment by flyingpimonster** [comment]
With the reduced icon size, I think it looks better to also reduce the height of subfooter. Comparison:

![screen shot 2017-12-05 at 13 43 42](https://user-images.githubusercontent.com/24497353/33627176-51558f26-d9c2-11e7-8b4f-54eac7674beb.png) ![screen shot 2017-12-05 at 13 43 28](https://user-images.githubusercontent.com/24497353/33627180-530a668e-d9c2-11e7-9212-4b95f2d3631b.png)


Thoughts?

**Comment by Gregoor** [comment]
@flyingpimonster I agree, looks better with reduced height 👍
