### ISSUE TITLE
[Mobile] Navigation icon needs to be shifted right

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#717]
On mobile screens, the navigation icon should align to the right edge of the content. There looks to be too much space to the right of the icon.

![screen shot 2017-11-28 at 12 25 16 am](https://user-images.githubusercontent.com/1466558/33303709-c36b8c46-d3d2-11e7-9ca9-cb03ff0281b5.png)

Shift right so as to align with right edge of content:
![screen shot 2017-11-28 at 12 25 16 am](https://user-images.githubusercontent.com/1466558/33303735-e86f4668-d3d2-11e7-97b7-0f59136ca670.png)

cc/ @m-branson

**Comment by willstott101** [comment]
I'm new here. Love this project, and I thought I might as well take this as an initial easy picking.
