### ISSUE TITLE
[Mobile] Download Common Voice Data button should not stack text

### ISSUE THREAD

**Issue by ivonnekn** [mozilla/voice-web#719]
There should be enough space to make the "Download Common Voice Data" text on the button just span 1 line on mobile screens.

![screen shot 2017-11-28 at 12 33 33 am](https://user-images.githubusercontent.com/1466558/33303926-e45301b8-d3d3-11e7-8dcb-6fc9b0c97399.png)

cc/ @m-branson

**Comment by Gregoor** [comment]
@iveskins I also centered the license label & link as I felt it looks better that way on mobile. lmkwyt

**Comment by ivonnekn** [comment]
@Gregoor I'm guessing you mean me, not @iveskins ? :)

**Comment by ivonnekn** [comment]
@Gregoor Can you keep the width of the button just large enough to fit the text and icon, rather than stretching to fit the width of the screen? At a maximum it should have left and right margins that align with the margins on rest of the content.
![screen shot 2017-11-28 at 10 31 20 am](https://user-images.githubusercontent.com/1466558/33328197-57410b40-d427-11e7-8acb-90a4d9045c56.png)

Like the centered license text!

Thanks!

**Comment by Gregoor** [comment]
Yaiks, this is getting embarrassing, I'm sorry iveskins!

Made the change so that it doesn't go full width.

**Comment by ivonnekn** [comment]
verified - thanks @Gregoor!
