### ISSUE TITLE
Global Common Voice Logo Update

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#730]
@Gregoor @mikehenrty realize this is quite late, so not a design blocker for tomorrow, but ideal for implementation as soon as possible. Have conferred with Mozilla brand re: spacing between Common Voice and the Mozilla logo in current lockup -- it felt extremely tight and has now been opened up.

See PNG here for visual reference and SVGs attached for implementation. Please use `cv-logo-bw` for header and social uses (this has white within the Mozilla logo to help it read best on a variety of backgrounds); and `cv-logo-one-color-white` for footer.

<img width="337" alt="cv-logo-bw" src="https://user-images.githubusercontent.com/18686986/33350769-749748de-d455-11e7-8209-64a546894498.png">

[cv-logo-svgs.zip](https://github.com/mozilla/voice-web/files/1512031/cv-logo-svgs.zip)

[Files are updated](https://drive.google.com/drive/folders/0B0vmiicLLrGuOU5fdjNHN093bm8?usp=sharing) on drive as well.

cc @ivonnekn

**Comment by Gregoor** [comment]
Swapped it out. And I like it! (not that that matters)
