### ISSUE TITLE
Is there a plan for collecting TTS data?

### ISSUE THREAD

**Issue by nanma** [mozilla/voice-web#738]
I really appreciate Mozilla's Common Voice project, which will contribute to application of voice systems.
I notice that the data collected by Common Voice is mainly for acoustic speech recognition, which emphasizes on diversity of voice. However, Text to speech(TTS) systems require high quality and professional, usually single speaker data corpus for training. So I'm wondering do you have a plan for collecting TTS corpus?

**Comment by mikehenrty** [comment]
No, we are not doing that. But our partner Tatoeba has 180 hours of a single person in their data set. Perfect for TTS. You can download that dataset on our download page:

https://voice.mozilla.org/data (lower right)

**Comment by nanma** [comment]
Thanks for reply, I will check Tatoeba's data.
