### ISSUE TITLE
Some sentences in "flickr30k" dataset too long

### ISSUE THREAD

**Issue by Qantas94Heavy** [mozilla/voice-web#739]
When I was trying out the "recording" functionality, I ended up with the following sentence that was too long to record:

> An elderly gentleman dressed in a formal white shirt and pinstriped black slacks and black shoes is dancing with a middleaged woman in a short white dress and black high heeled shoes on a wood floor in a dimly lit room while another similar dressed couple dances

It appears to be from the "flickr30k" dataset which was introduced a few hours ago. Is there some way we can deal with this?

**Comment by mikehenrty** [comment]
@Qantas94Heavy yes! thank you I'm on this

**Comment by mikehenrty** [comment]
@Qantas94Heavy ok, i removed all sentences that are more than 18 words long
