### ISSUE TITLE
"Cancel re-recording" does not actually stop recording

### ISSUE THREAD

**Issue by Qantas94Heavy** [mozilla/voice-web#740]
Steps to reproduce:

1. Record three sentences.
2. Click the "re-record" button on one of them.
3. Click the "record" button to start recording.
4. Click "cancel re-recording".
5. Click "re-record" on the same recording.

After this you will see that the record button is still illuminated, and if you click that button it will say "The recording was too long."

**Comment by Gregoor** [comment]
Hi @Qantas94Heavy, good catch, thank you! Should be fixed in the next deploy.
