### ISSUE TITLE
[String localization] Parsing a string in a HTML atribute not working

### ISSUE THREAD

**Issue by ukii** [mozilla/voice-web#743]
Having done almost everything for String Localization, except fixing some of the string names so it can be reusable I've encountered this problem. Example, I'm having this component in review.tsx
`<Modal
            buttons={{
              'Се согласувам': () => this.handlePrivacyAction(true),
              'Не се согласувам': () => this.handlePrivacyAction(false),
            }}>
            {STRINGS.reviewTermsAgreements}
            <a target="_blank" href="/terms">
              {STRINGS.terms}
            </a>{' '}
            и{' '}
            <a target="_blank" href="/privacy">
              {STRINGS.privacyInfo}
            </a>.
          </Modal>`

I can't fit a string in the place of 'Се согласувам' and 'Не се согласувам'. Their appropriate localized strings are STRINGS.agree and STRINGS.disagree. Any idea how to fix this?

**Comment by Gregoor** [comment]
Great, looking forward to reviewing it. I think what you're looking for in this case is [Computed property names](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names). Let's continue the discussion in #723.
