### ISSUE TITLE
Clicking on "profile" from homepage error

### ISSUE THREAD

**Issue by cs4allnyc** [mozilla/voice-web#744]
After validating about 20 sentences, I clicked on "profile" and for half a second it seems like it will take me to a new page, but then it takes me to a blank page. When I click to go back to the homepage, the homepage is also blank until I reload the page. 

I'm on a desktop using Google Chrome.

![blankpage_mozillavoice](https://user-images.githubusercontent.com/17147758/33488710-83bb615c-d67f-11e7-94fb-3320b08ca26a.PNG)

**Comment by jdittrich** [comment]
Could not reproduce – Profile loads for me. 

Firefox 57, Ubuntu 16.04

**Comment by cs4allnyc** [comment]
Still not working on Chrome.

**Comment by Gregoor** [comment]
Works for me on Chrome 62. Which Chrome version are you using @cs4allnyc?
Is it reproducable when you only validate one sentence and go to profile or does it have to be a couple?

**Comment by mikehenrty** [comment]
also @cs4allnyc , could you check the developer console in chrome and see if there are any errors in there?

https://developers.google.com/web/tools/chrome-devtools/console/

**Comment by cs4allnyc** [comment]
Using Chrome Version 55 because I can't update it on my networked computer at the NYCDOE. 

This is the error from the console when I clicked on "Profile" in the nav bar:
Uncaught TypeError: Failed to execute 'scrollTo' on 'Window': No function was found that matched the signature provided.

**Comment by cs4allnyc** [comment]
And same error when I opened a new incognito window and did not validate any sentences. And same error when I validated just one sentence. Still in Chrome v 55 and error is: Uncaught TypeError: Failed to execute 'scrollTo' on 'Window': No function was found that matched the signature provided.

**Comment by Gregoor** [comment]
While we could try to support older Chrome versions, my stance would be that we shouldn't incentivize usage of browsers that don't receive security fixes anymore. Afaik Google only backports bugfixes 1-2 browser versions.
I'm sorry that this affects you, @cs4allnyc and it's probably not something you have any control over. But if you have a line of communication to your IT staff, I'd recommend telling them running outdated software (and more critically outdated) browsers is a big security risk.
