### ISSUE TITLE
[front-end] We need to find a way to enable speech collection from multiple users in a row and how to deal with the demographic data 

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voice-web#75]

**Comment by kdavis-mozilla** [comment]
A possible easy solution is to not deal with demographic data

**Comment by mikehenrty** [comment]
I think the more important thing here is that we need each user to agree to the terms if we are going to use their voice data.

The current thinking right now is that we will give them a version of the app that points to our staging server (test.mozvoice.org), and edit the code to always prompt for terms (and also we will put some cool sentences about net neutrality into the corpus).

**Comment by mikehenrty** [comment]
In the end, we decided to deploy a version of the app that points to staging, and then on staging we use the `activate` branch that always prompts for terms of service.
