### ISSUE TITLE
Audio Encoding

### ISSUE THREAD

**Issue by navta** [mozilla/voice-web#751]
Using a lossy compression such as mp3 may affect recognition accuracy. Is there any reason why not using  raw PCM or lossless compression instead?

**Comment by mikehenrty** [comment]
mp3 offers us a great trade-off between compression ration, quality, and browser support. the head of machine learning here at Mozilla said the mp3 artifacts won't affect recognition in any substantial way, an assertion which has been validated by some other machine learning groups we are working with. it mp3 is indeed a deal breaker for you, i would love to some published results showing this. before we see such results, i'm inclined to believe our ML team about this.

**Comment by RuABraun** [comment]
> the head of machine learning here at Mozilla said the mp3 artifacts **won't affect recognition in any substantial way**, an assertion which has been validated by some other machine learning groups we are working with.

I'm very late to the party, but I cannot help but point out that this is a completely false statement, and your "head of machine learning" clearly has no experience with audio.

**Comment by Gregoor** [comment]
That tone is not appreciated, let's keep it civil please.

Would you mind elaborating and supplying some sources on the limitations of MP3s?
