### ISSUE TITLE
IE11 Support  - We're sorry, but your platform is not currently supported.

### ISSUE THREAD

**Issue by KBPsystem777** [mozilla/voice-web#763]
Our workplace is running `IE11` and a lot of potential voice contributor here but were getting this message: **We're sorry, but your platform is not currently supported.**

**Comment by Gregoor** [comment]
Thanks for the willingness to contribute and I'm sorry to hear about that issue. Unfortunately there's not good way to make IE11 support happen for recording without relying on deprecated proprietary technologies like Flash or Silverlight. The only option I see would be a file upload but I'd wager that would be too tedious for most users.
On the bright side, we're looking into Safari 11 support which would also bring Microsoft Edge support, if that's something you can use at your workplace.

**Comment by KBPsystem777** [comment]
Thanks for considering Safari as well 👍

**Comment by Gregoor** [comment]
Let's continue the conversation in #469

(though I'm happen to reopen this one if someone finds a way to support IE11 with the given constraints)
