### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by reinhart1010** [mozilla/voice-web#769]
Hello, I found out this grammar error from one of the sample sentences.

![screenshot_2017-12-10-17-00-16](https://user-images.githubusercontent.com/17312341/33803842-c56c1cce-ddcb-11e7-9228-ec49da064b52.png)

**Hint**: it should be **an adult**, not **a adult**.

**Comment by Gregoor** [comment]
There are a few of those issues. I think what we'd want in the future is an in-app option for reporting incorrect sentences.
