### ISSUE TITLE
Recording button bug on Chrome/WebView on Android

### ISSUE THREAD

**Issue by reinhart1010** [mozilla/voice-web#770]
In Chrome (or WebView-based browsers) on Android, pressing the "Record" button will trigger the action twice. This causes "recording is too short" error once the button is pressed on this browser.

![Recording is too short](https://user-images.githubusercontent.com/17312341/33814286-c5138e5c-de5b-11e7-829b-415bb1619abf.jpg)

**Comment by Gregoor** [comment]
Thanks for the report, we were attaching two handlers on that button, I think to handle click delay on mobile devices. As that is [a solved problem in modern browsers](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away), I just dropped the code. If we want to eliminate that delay on old browsers as well, we should use [react-tappable](https://github.com/JedWatson/react-tappable).

**Comment by reinhart1010** [comment]
The bug still occurs after the PR. Has the website updated yet?

**Comment by Gregoor** [comment]
Good catch, thanks! For some reason the problem disappeared in the device emulator, but I can indeed still reproduce it on my mobile. I went ahead and just debounced the record handler. It'll be deployed on our [staging](http://voice.allizom.org/) env in around an hour. Would appreciate feedback!
