### ISSUE TITLE
Add download URL to the datasets page (to make wget, etc easier)

### ISSUE THREAD

**Issue by galv** [mozilla/voice-web#771]
I would like to point that it'd be very helpful to provide a raw link to the dataset [here](https://voice.mozilla.org/data).

I understand that you've set things up the way you have so you can immediately provide users with a way to enter their contact info in order to create an account. But it's often useful in the case of ASR to be able to have a raw download link, so that I can download the data via wget to a remote machine (one without a monitor), without going through my desktop or laptop as a middleman.

**Comment by Gregoor** [comment]
Great point! Actually it was first implemented as a proper link (I also like to copy download links), so there is no conflict with having the signup modal afterwards. But the requirements changed a bit and we needed the button to be able to trigger multiple downloads (which wouldn't be solvable with a single link). What might be a solution here is adding a "copy to clipboard"-button. A few questions I have on this:

1. What would that look like design-wise (@m-branson might have some thoughts on this)?
2. When putting multiple links into the clipboard, would they just be space-separated?

**Comment by mikehenrty** [comment]
note: we do have such a URL for Common Voice data:
https://common-voice-data-download.s3.amazonaws.com/cv_corpus_v1.tar.gz

It's just a matter of putting this on the data page.

**Comment by liordon** [comment]
what about different data sets and languages?
the link you posted is for the English dataset, isn't it?
I was really hoping I could train deepSpeech on the Esperanto dataset and see how well it does

**Comment by Gregoor** [comment]
We got this right, this time: https://voice.mozilla.org/datasets

The download button link should be easy to copy

**Comment by cameron-martin** [comment]
This seems to have changed since closing this. Now the website passes a time-limited cryptographic token to S3.

**Comment by phirework** [comment]
Yep, we made those changes at the end of last year when there was a sudden spike in direct downloads to those links that was quadrupling our server bill at a time when the future of the project was uncertain due to the Mozilla restructuring. Other than that, the main reason we ask everyone to go through the /datasets page is for the sake of GDPR compliance, which is a thing the Mozilla legal team requested.

**Comment by CorentinJ** [comment]
Would it still be possible to have access to a link to an archive of the entire dataset, up to the most recent version?

**Comment by ftyers** [comment]
I don't think that is possible because of the GDPR compliance, but feel fee to get in contact with us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).
