### ISSUE TITLE
Upload recordings in background

### ISSUE THREAD

**Issue by a3nm** [mozilla/voice-web#782]
Uploading recordings takes quite some time, and I feel it really slows the user down. It would be better if, after pressing the submit button, uploading happened in the background while the user can continue recording sentences.

One downside of uploading in the background would be that some users may leave the page before their recordings have been fully uploaded, but on average I would imagine that getting rid of the load uploading delay would encourage users to contribute more.

**Comment by paskalito** [comment]
also that design would solve that
https://github.com/mozilla/voice-web/issues/281#issuecomment-320030802

**Comment by Gregoor** [comment]
I think this would be a nice thing to have and won't be too much work, implementation-wise. Atm we don't have "toats" or some other page global notification UI to indicate to users the upload is done. @m-branson Do you maybe have an idea for a simple enough UI that we can work on implementing this or should we postpone it for now?

Users leaving the site while uploading is easy enough to handle with a modal that pop ups when uploading is not yet complete.

**Comment by paskalito** [comment]
@Gregoor ^^
i still think that my original idea is quiet fancy.

staying with the current approach something like.

> after you hit submit you get imedeatly the recording interface again
at the same time the submittbotton renames itself to an upoad button and flies nicely animated  on top of the robot maybe top of the (visible) screen (without destroying any margins/paddings (oder heights and places of things) does its upoading thing there gets green when it's sucessfully finished and then vanishes (fade out or fade up) - there could be multiple of those as well.
one would need to make sure to not interfere with the oder messages ( too long recording etc)

so far my first thought  :)

**Comment by Gregoor** [comment]
@m-branson forgot to label it Design earlier. Hope it's not too late 🙃

**Comment by m-branson** [comment]
@Gregoor never too late (thanks for the tag)! Will review this idea inline with contribution flow refinement next sprint (deep in language land currently).

**Comment by m-branson** [comment]
@Gregoor I've been thinking on this some...do we know on average how long it takes for upload to occur successfully? Is it feasible technically for upload to happen in the background without causing the experience to lag (especially on mobile)?

**Comment by Gregoor** [comment]
@m-branson I think the average is around 700ms, so ~2s for the whole set. We do get progress events from the browser itself on how far the upload has progressed. So that should be accurate enough for something like a progress bar.
Uploading in the background should not cause lag, as the browser handles that independently of the UI thread and from my understanding the limiting factor for upload speed is not the device's processing power but the network speed.

**Comment by m-branson** [comment]
Thanks @Gregoor, good to know. An my understanding is the same re: upload being limited by network speed rather than device.

**Comment by Gregoor** [comment]
We've added it to the new contribution experience* which will be on production soon.

* This links to staging on which clips are not collected. It's only for testing purposes.

(pardon my macro responses 😁 )
