### ISSUE TITLE
Total time of validated voice samples still stuck at 253 hours

### ISSUE THREAD

**Issue by reinhart1010** [mozilla/voice-web#784]
There is a counter of validated speech in hours in the homepage of [Common Voice](https://voice.mozilla.org). Since November, I still do not see any progress of the this counter.

I believe that this is an issue in validation process, since there are still many voce samples that have not been validated yet. I would suggest that contributors should concentrate on validating samples that are sent on the earliest three days, so the validation process would be faster.

**Comment by flyingpimonster** [comment]
[It looks like that number is hardcoded.](https://github.com/mozilla/voice-web/blob/master/web/src/components/pages/home/project-status.tsx#L5)

**Comment by Gregoor** [comment]
Thanks for the great flag. It is indeed hardcoded at the moment. We're in the process of migrating more data to our database and this should be among the issues easier solved after.

**Comment by flyingpimonster** [comment]
@Gregoor It might be a good idea to update the hardcoded value now so it doesn't look like the project has stalled.

**Comment by Gregoor** [comment]
Good point 👍 We made a conservative estimate on how many more hours we have and updated it.

**Comment by flyingpimonster** [comment]
Wait, still only 254 hours? According to [this article](https://medium.com/mozilla-open-innovation/sharing-our-common-voice-mozilla-releases-second-largest-public-voice-data-set-e88f7d6b7666), the downloadable dataset contains 500 hours.

**Comment by jf99** [comment]
Agree, if your progress is that slow, you should really make some advertising. We don't want to wait for 10 years until the goal of 10,000 hours is reached.

**Comment by MichaelNMaggs** [comment]
This is giving potential contributors the very bad (and I hope inaccurate) impression that the project stalled a couple of months ago, and there has been no progress whatsoever since then. If it's too difficult to update this figure, I think it should be removed entirely at least for the moment.

**Comment by Gregoor** [comment]
I'm sorry if this is frustrating to people, we'll have dynamic non-hardcoded hours very soon. The first step was moving more data into our database so it's simple to build such queries. Now solving issues such as this one is a lot simpler. Stay tuned!

**Comment by Gregoor** [comment]
Not as soon as I wanted, but it is in now: Validated hours are now dynamic 🎉
