### ISSUE TITLE
Chinese voice enhancement

### ISSUE THREAD

**Issue by jinfagang** [mozilla/voice-web#785]
Is there any separate Chinese voice in common voice dataset? I think Chinese voice should take into consideration.

**Comment by flyingpimonster** [comment]
[Multi-language support is coming soon.](https://github.com/mozilla/voice-web/issues/213) They're currently doing some database migrations, so this will probably need to wait until after that gets done.

**Comment by jinfagang** [comment]
I am so much hoping for this!!!!! I will keep tracking this project and wish I can get a Chinese voice recognisor!!!
