### ISSUE TITLE
Voice Validation buttons not working in Firefox Mobile

### ISSUE THREAD

**Issue by reinhart1010** [mozilla/voice-web#789]
The **YES** and **NO** buttons are not working (do not fetch another voice sample to validate).

This bug occurs in Firefox 57.0.1 and Nightly 59 on Android 6.0. However, this bug does not occur in Chrome and Android System WebView.

![Screenshot](https://user-images.githubusercontent.com/17312341/34400992-b0b5771a-ebc9-11e7-8976-bdd9000ad0a4.png)

**Comment by Gregoor** [comment]
Thanks for reporting this, that regression was introduced recently. Clicking the validation buttons now works again.
