### ISSUE TITLE
audio validation script Type: Enhancement

### ISSUE THREAD

**Issue by eliaho** [mozilla/voice-web#790]
Hi, 
this project is an amazing idea!! great job!
after downloading the data i realized that some audio files under validated are around 1mb and include long minutes of silence, there are also a very big number of audio segments that have a few seconds of silence at its ends.
i think that this can be handled with a simple validation script that maximize the length of each audio relatively to its text and with simple audio trimming of silence at the beginnings  and ends of the segments.
and naturally supporting multi-languages will bring this project to a higher level

**Comment by mikehenrty** [comment]
See also #779.

We have some logic that warns users when a recording is too long now. The next step would be to not allow these clips to be uploaded. We could also go into the data, and delete big files. We could also add some tools for removing quiet sound at the beginning and end of clips.
