### ISSUE TITLE
Release the Common Voice corpus with lossless format (e.g., FLAC) instead of MP3

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [mozilla/voice-web#791]
It would be nice to have a version of the Common Voice corpus released with a lossless format (e.g., FLAC, as LibriSpeech does) instead of MP3.

**Comment by paskalito** [comment]
depends a bit on how they are recorded, but from a FOSS standpoint it would make more sense anyway to provide them in a free audio format. ogg/opus

**Comment by Franck-Dernoncourt** [comment]
opus is lossy though. What's the license issue with FLAC? Just curious.

**Comment by Gregoor** [comment]
Duplicate of #751
