### ISSUE TITLE
Mobile UI: Make Submit Button bigger(higher) and add some space to the "cancel submission"

### ISSUE THREAD

**Issue by paskalito** [mozilla/voice-web#793]
while contributing i found it hard to hit the submit button.

if you look a the screen heighwise. you notice theres a hughe space for your thumb to hit the play and the rerecord buttons.
but for the the submit button the one you want to hit most likely theres significantly less space.

in addition the "button" to cancel the submission is so close that there is kinda high chance you press there.

![screenshot_20180105-234841](https://user-images.githubusercontent.com/8012793/34632185-5766f04c-f274-11e7-89a8-f2c1f49a553e.png)

**Comment by Gregoor** [comment]
The new contribution experience's submit button should be more clickable 🙂 
Thanks for raising this!
