### ISSUE TITLE
Mobile UI: reset the "viewport" to the textbox after uploading

### ISSUE THREAD

**Issue by paskalito** [mozilla/voice-web#794]
if you have longer sentences your endscreen looks like this
![screenshot_20180105-235149](https://user-images.githubusercontent.com/8012793/34632352-304d405a-f275-11e7-8bf2-aad093991f23.png)

in order to submit you need to scroll down.

because of that your nex view looks like this:
![screenshot_20180105-235249](https://user-images.githubusercontent.com/8012793/34632373-514a879a-f275-11e7-938a-082b7a21bd41.png)
you cannot read the box, and you need to scroll up again to do so.

that turns out to be very anoying flow wise.

i'd suggest that after every upload you get taken to the top of the box so you can read the sentence always. and just continue contributing.

it might also be a good idea to make whitespace padding/margin whatever of the box smaller.

![screenshot_20180105-234830](https://user-images.githubusercontent.com/8012793/34632451-c8978226-f275-11e7-8923-4c23c3382333.png)

**Comment by Gregoor** [comment]
Good flag, thank you!

**Comment by paskalito** [comment]
very cool you fixed that thanks.
it would be neat if the reset also happens when you rerecord something :)

**Comment by Gregoor** [comment]
Makes sense, thanks for the flag!
