### ISSUE TITLE
Mobile UI: More efficient Recording page

### ISSUE THREAD

**Issue by paskalito** [mozilla/voice-web#795]
this is kinda follow up for https://github.com/mozilla/voice-web/issues/794 (and https://github.com/mozilla/voice-web/issues/793)

Current situation:
![screenshot_20180106-001312](https://user-images.githubusercontent.com/8012793/34632570-81176294-f276-11e7-9c91-df94b9926f55.png)

there is this nice loking robot with the nice blue background that starts to move and turns red wenn you start recording and talking.

the problem with that is:

- at least on my scren the record button which is the element you need to interact with is so much cut that chances are close to 0 you press it without having to scroll down first.
- if you scroll down first you wont see the nice animation anymore at all.
- at least on my device (s3) the animation still lags and i would waste a lot of time always looking at it / waiting for it. and also cause a unecessary silence on the beginning of every recording.

other general problem the indication of the recording and the button to start the recording are splitted by the textbox.

Approach for a better soloution:

- kick out the waverecording indication on the top. ( still keep the welcoming robot but maybe replace him)
- decrease the whitespace of the textbox
- increase the size of the record button ( maybe also make it square like / full width of screen)
- make the already great indication of recording of the recording button itself ( currently it the white between outer and inner circle gets a little more red) more visible. ( maybe make it pulse or change into a small audiowave line that still vibrates when it gets audio input ( but only if that does not go on cost of performance) ( because the getting red is at the moment the most instant and accurate indicator that tells you when the recording started)

that would make it already i think.

just found that on longer texts the recording button is not shown at all.
![screenshot_20180105-234752](https://user-images.githubusercontent.com/8012793/34632902-c19ff43c-f278-11e7-880a-d00defe97308.png)

**Comment by Gregoor** [comment]
These are great notes, thank you! I've had similar thoughts when using the mobile site, there is definitely room for improvement.

I think our UX designer @m-branson also has some thoughts about that, as we talked about more design iterations coming up. Though I think atm the priority are somewhere else, so it might take a few weeks before we do a deeper dive.

Imo the things you outlined are mostly actionable and I could look into them once I have a few extra hours. I wouldn't kick out the animation though, rather I'd detect the performance of the animation and throttle/remove it accordingly.

**Comment by m-branson** [comment]
Agreed @Gregoor, these are indeed great notes. Thanks for submitting @paskalito. 👍

These are very much known UX issues on the mobile experience (across devices) and are indeed being prioritized against some higher level experience priorities and features. That said, it is great to have them documented here.

Any work that can be done to improve upon this current mobile experience execution is greatly welcomed, based on this thread here is my recommendation for the short-term:

- [ ] Use @Gregoor's preference to detect the performance of the animation and throttle/remove it accordingly
- [ ] Decrease the whitespace of the textbox, potentially making text box size dynamic based on sentence length?
- [ ] Increase padding around record button to improve hit state accuracy. (Current size and pulsing of record button is acceptable for this iteration of active record session feedback.)
- [ ] Move the `#record-help` message below the `#recordings-count`, allowing the record button to move up. If this change requires implementation globally (as opposed to mobile only) I'm still of the mind that it will be beneficial.

Thanks both!

**Comment by Gregoor** [comment]
Thanks for that. It made it even more actionable so I took the time to implement it. I like it a lot more now (the space waste was even a problem on my phablety device).

Unfortunately our staging server currently has a certificate issue, I'll let you know when you can look at it.

**Comment by paskalito** [comment]
@Gregoor and @m-branson thanks a lot for the flowers and even more for the work you've already done!!

as far as i can see everything is done except

- [ ]  make submit button taller, and add more space to the cancel submission button

and because of the other space savings.

- [ ]  the popup messages are now shown on top of the text one needs to read.
(maybe show them now above the box / in front of the robot)
![screenshot_20180116-214548](https://user-images.githubusercontent.com/8012793/35246964-f7dd670c-ffc8-11e7-8fff-afd6687f2e09.png)

also cool to hear that there is more to come. i personally still like my idea from [here](https://github.com/mozilla/voice-web/issues/281#issuecomment-320030802) a lot. it sounds like you already have people to discuss this ux related stuff with and unfortunately i cannot find so much time to spend on the computer and great projects like this but if you want i still would like to say that i would be happy to talk with you about theese things.

with that all said and issued i want to say i generally like this html5 recorder super much so :clap: for all of you that made it possible. and one of my favourite feature/gimmick is the upload process statusbar in the submit button :)

**Comment by paskalito** [comment]
oh i just saw the first thing is a seperate issue already sorry
https://github.com/mozilla/voice-web/issues/793

**Comment by Gregoor** [comment]
Thank you @paskalito for being part of the conversation and the nice words. Much appreciated! 👍 

And again, great flag. Should've noticed that!

RE process statusbar, what do you then think of #782? (feel free to comment there if you find the time)

**Comment by Gregoor** [comment]
I think we succeeded on most of these points with the new experience. Thank you for your thoughts!
