### ISSUE TITLE
Desktop jumps around

### ISSUE THREAD

**Issue by MichaelNMaggs** [mozilla/voice-web#801]
Recording on a laptop is now quite difficult, as the screen position often moves significantly during the recording -  sometimes so much that it has to be scrolled to make the 'finish' button visible again.  Also, clicking on the button to complete the recording is frequently not recognised, particularly if the system is engaged in overlaying the text to be recorded with a green background (what does that mean, anyway?)

Firefox quantum 57.0.4 on a Mac

**Comment by Gregoor** [comment]
I need some clarifications here:

At what point does the screen position change during recording? I couldn't get that to happen in my browser, but maybe it's a platform specific problem. Can you provide a recording of the issue? (I think there's a screen recorder preinstalled with Mac OS).

And are we talking about this green background?
![screenshot-2018-1-15 common voice by mozilla](https://user-images.githubusercontent.com/4051932/34935603-bb8cd3fe-f9de-11e7-828e-a3bf1f89e0bf.png)

**Comment by MichaelNMaggs** [comment]
Hi Gregoor - apologies, please ignore this report. I found when trying to replicate it that it was due to Dragon Naturally Speaking which was listening in on the mic. It was attempting to control the Mac from my voice, and the green background was Dragon's attempt to highlight words on the screen  that corresponded with what I was saying. Sorry to have bothered you with this.

**Comment by Gregoor** [comment]
No worries, happy to hear it was no hard to reproduce anomaly :)
