### ISSUE TITLE
Avoid having to scroll the screen in order to submit recordings

### ISSUE THREAD

**Issue by MichaelNMaggs** [mozilla/voice-web#802]
When recording on a laptop the submission screen is difficult to use. The picture of the robot and associated graphics push the sentences so far down the screen that the 'submit' button is not visible, and the user has to scroll every time to make it visible before clicking on it.

Firefox Quantum 57.0.4 on a Mac

**Comment by Gregoor** [comment]
Thanks, that's an excellent flag! We'll keep it in mind for our next design iteration.

cc @m-branson
