### ISSUE TITLE
already know "The DARPA TIMIT Acoustic-Phonetic Continuous Speech Corpus"?

### ISSUE THREAD

**Issue by jibe-b** [mozilla/voice-web#809]
Available at:

http://academictorrents.com/details/34e2b78745138186976cbc27939b1b34d18bd5b3

**Comment by kdavis-mozilla** [comment]
I wasn't aware of it. However, the license 

> No license specified, the work may be protected by copyright.

seems to preclude any use of it in Common Voice.

**Comment by jibe-b** [comment]
True about the license. Unfortunately.

**Comment by ftyers** [comment]
It's available through [LDC](https://catalog.ldc.upenn.edu/ldc93s1). The licence is the [standard LDC one](https://catalog.ldc.upenn.edu/license/ldc-non-members-agreement.pdf) which precludes its use in Common Voice.

**Comment by mikehenrty** [comment]
WONTFIX :'(

**Comment by noelweichbrodt** [comment]
TIMIT was published by the NIST (https://www.nist.gov/publications/darpa-timit-acoustic-phonetic-continuous-speech-corpus-cd-rom-timit), which according to https://www.nist.gov/nist-research-library/faqs means that it is public domain in the United States.

(IANAL, was researching copyright status of various corpora for an unrelated project and came across this thread, apologies for the necro)

**Comment by mikehenrty** [comment]
thanks for the reference @noelweichbrodt 

Looking at the faq page you linked to, it looks like the works must be credited. But we promised our users the data they contributed would be published under cc0, which stipulates you do not need to credit anyone when using the work. This is the conflict, and precludes us from using any "attribution" sources.
