### ISSUE TITLE
Mistake in text already corrected on Github but still appearing in validation

### ISSUE THREAD

**Issue by zecakeh** [mozilla/voice-web#810]
I was just doing some validation on the website, and in one of the sentences I saw the word "bicycle" mispelled as "bycicle".
I then went to Github to fix it, but I didn't find it with the search bar. I find several sentences with the proper spelling though, so I guess it's already been corrected, since I don't remember which one it was.

Does that mean that spelling errors corrected on Github aren't applied to the database ? If so, shouldn't they be ? As a mispelled word seems kind of useless...
Also, in general, shouldn't sentences be thoroughly checked before being used ?

**Comment by mikehenrty** [comment]
Hi @zecakeh, thanks for the report.

Indeed, that was a bug we fixed a while back, probably this one:
https://github.com/mozilla/voice-web/commit/7be0163f483098b1d0f7b2ec750a6cf0d028e575#diff-d4b45118aca4be607586b46d4eb0eb8bL29

In cases where you see the typo in the sentence, the best thing we can do for now is vote "No"

In the future, we may put some tools in for correcting sentences after they have been submitted. But it's not a high priority for now.
