### ISSUE TITLE
Talk on Common Voice project at Fossasia

### ISSUE THREAD

**Issue by sonusandeep** [mozilla/voice-web#812]
Hi Michael,

Hope you are doing great.

I have been selected as a speaker for FOSSASIA'18 at Singapore. I will be speaking on Common Voice Project. Is it possible to get approved of my travel budget to attend this through Reps Program.

I have contacted George and review team,George told me to talk with you regarding this and proceed accordingly.

Please let me know your views.

Thanks in advance.

Best,
Sandeep
Mozilla Representative

**Comment by mikehenrty** [comment]
Let's talk about this over email :)
