### ISSUE TITLE
asking for microphone access does not work in LineageOS standrad browser

### ISSUE THREAD

**Issue by paskalito** [mozilla/voice-web#815]
after cklicking the record button i only get the message from the site " you must allow migrophone access cancel / retry" but now possibility in the (browser/system) UI to do so..
sadly i don't know the real name of that browser... appinfo tells me org.lineageos.jelly version 7.1.2 appname is just browser...

device is gt-i9300 / s3 Android 7

**Comment by mikehenrty** [comment]
Sounds like LineageOS browser doesn't support the microphone API (getUserMedia). Our best be here would probably be to detect the User Agent, and show a page asking them to install Firefox (similar to what we do with Firefox Focus and mobile Safari.

**Comment by paskalito** [comment]
unfortunately i'm not entirely sure but i think i remember that it did work some weeks ago :S ...

**Comment by Gregoor** [comment]
Afaik Jelly Browser is build on the AOSP Browser, which is more or less and old Webkit version. As that doesn't support getUserMedia, I don't see how we could support recording on it. Sorry!
