### ISSUE TITLE
[iOS] can't scroll in iOS native app

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#819]
iPhone SE
iOS 11.2.5

**Comment by Gregoor** [comment]
Was able to reproduce it. As it works in Safari, I think it's related to the removal of the container scroll elements (which caused various styling and behavior problems). I think there's a way to fix it on the iOS side:
https://stackoverflow.com/a/32007438/1501916

**Comment by syilmaz** [comment]
I could reproduce this problem as well. 

`isUserInteractionEnabled` defaults to true. I can see that scrolling is intentionally disabled. I'm not sure what the reason behind it is. 

See pull request #822. This resolves the issue.

**Comment by mikehenrty** [comment]
This bug is fixed by reverting some old scrolling logic. But #882 is still valuable as it will allow us to reduce DOM complexity.
