### ISSUE TITLE
ES5 Incompatable Code in clip.ts

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/voice-web#82]
The following methods are used but not part of ES5
- `string.startsWith()`
- `string.includes()`

They can easily be replaced with equivalent code

**Comment by mikehenrty** [comment]
Looks like this is causing a build failure on travis that I can't reproduce locally:

https://travis-ci.org/mozilla/voice-web/builds/242373930?utm_source=email&utm_medium=notification

**Comment by kdavis-mozilla** [comment]
In my branch I've fixed these just to get things compling, see cc52e6e and a8b91f0

It'd be best to do them as a PR distinct from the S3 work. I can do that.
