### ISSUE TITLE
[iOS] "Open in App" banner missing on Mobile Safari

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#821]

**Comment by Gregoor** [comment]
Showed up for me just now. Maybe it was closed before or the app is already installed?

**Comment by syilmaz** [comment]
Or perhaps private mode was used? Smart App Banner doesn't work with private mode.

**Comment by mikehenrty** [comment]
Ah, @syilmaz was correct! I use private mode by default in Safari <.<

Thanks!
