### ISSUE TITLE
Backend Routing

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#823]
This is a meta issue for tracking the progress of reworking the Backend Routing:
- [x] Router #834
- [x] Route Typing #835 
- [x] Route Restructuring #836

**Comment by apoorvaagupta** [comment]
Hello, may I give this issue a try if no one else has taken it up?

**Comment by Gregoor** [comment]
Hi @apoorvaagupta, you're very welcome to take a stab at it. I wanted to look at it tomorrow or Friday, but I've got plenty of other things I can look at first. So it's yours if you want it 👍

**Comment by apoorvaagupta** [comment]
Thanks @Gregoor . I will do give it a shot and try to refactor the code as much as I can. 
I may require your help in between though!

**Comment by Gregoor** [comment]
Great, thank you! Feel free to ask for help anytime, here or on our Common Voice Slack

**Comment by apoorvaagupta** [comment]
So to get started, I will need to convert the code in server/src to express first and then probably refactor the routes. Right?

**Comment by Gregoor** [comment]
Yes, I think that's the right place to start. I think it might not be possible to do this one route at a time though, so you'd have to comment out whichever route is not migrated to express yet.
Also express has this nice feature of creating separate routers, so we could use that to still encapsulate different routes in different files.

**Comment by apoorvaagupta** [comment]
Yep, I have used express in all my node projects. So I am familiar with its features more or less! I feel I would be able to give it a shot.
