### ISSUE TITLE
Can't fetch sentences, and so can't record audio

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#825]
We are getting a 504 (timeout) when trying to request sentences.

**Comment by mikehenrty** [comment]
In the production logs, I'm seeing the following error on all three machines: `unhandled mysql error, Connection lost: The server closed the connection.`

**Comment by mikehenrty** [comment]
When we get an unhandled database error ([here](https://github.com/mozilla/voice-web/blob/4379374be9c354b6e02048a8daaf4553210a831f/server/src/lib/model/db/mysql.ts#L105)), we probably want to call `this.endConnection` so that we re-initiate the connection the next time we try to query the db.

**Comment by mikehenrty** [comment]
The problem might not be related to our app. After re-deploying, all of our machines still could not access the DB (CONNREFUSED), even when it first booted. That coupled with the fact that all three connections died at once initially 9 hours after our latest deploy makes my think it's infra related.

I asked in Nubis and they suggested I `FLUSH HOSTS` on the db server. I'm trying that out now.

**Comment by mikehenrty** [comment]
Looks like FLUSH HOSTS fixed the DB connection problem, but we are still seeing timeouts when trying to fetch sentences. To fix it for the short-term, I deployed a really old version of the code:
https://github.com/mozilla/voice-web/commit/cc7334c7b1c758c97472dea231a4193df0578f59

The connection problem is probably due to the DB machine running on a nano instance. We can upgrade (with no downtime) to a small with #829.

But we are going to have to figure out why the api request times out, and I'm guessing it's due to a slow query when fetching least-used sentences. Let's investigate more tomorrow.

**Comment by syilmaz** [comment]
Looking at `findSentencesWithFewClips` I can see that this part: `ORDER BY COUNT(clips.id) ASC` introduces a filesort. It seems like the query time will increase as the clips table grows.

**Comment by Gregoor** [comment]
The major slow query was the (updated) hearbeat, which happened every minute. It now only happens every 30 minutes. I'll also do some more digging which other queries are currently slow (we do have that log). Not entirely sure yet if findSentencesWithFewClips was part of the problem (but likely enough it was), as I reverted the DB retrieval of sentences. We'll test that when the dust has settled.

Thanks you two for the input and writing down your thoughts and observations!
