### ISSUE TITLE
When sentences can't be loaded, the error message displays improperly

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#828]
![screenshot from 2018-01-31 23-17-31](https://user-images.githubusercontent.com/635365/35650636-16530604-06dd-11e8-9dc0-d7a6e2efd0f1.png)

**Comment by himanish-star** [comment]
@mikehenrty, can I try and fix this issue?

**Comment by mikehenrty** [comment]
Hi @himanish-star, we would love your help here! Let us know if you have any questions.

**Comment by himanish-star** [comment]
Sure I'll complete the setup and start my work

**Comment by himanish-star** [comment]
Actually @Gregoor I have a number of commitments at other repositories, so I am not quite getting time to look upon this issue. So is it ok if someone else can take over this?

**Comment by Gregoor** [comment]
Sure no worries, I'll look into it. Just wanted to make sure I'm not eating someone else's pie 🙃

**Comment by flyingpimonster** [comment]
I went ahead and submitted PR #883 to fix this. I hope that wasn't someone else's pie--it looked extremely delicious.
