### ISSUE TITLE
Backend Router

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#834]
Current routing logic could be more declarative by using a router. I'd just go with express as it is quite solid and well-known (which helps contributors read the code).

There's an error in the way we do routing, e.g. https://voice.mozilla.org/metrics/upload/random.json gives us a random recording as we don't check for exact route match but rather whether certain routes are included in the string. When I first noticed that I didn't want to change it, because I didn't know whether anything relied on that behavior. Now I'm fairly certain that this isn't the case. This would also be fixed by using a router.

@apoorvaagupta expressed interest in tackling this.

**Comment by Gregoor** [comment]
@apoorvaagupta let me know if there's anything I can help with

**Comment by Gregoor** [comment]
Hi @apoorvaagupta, if you didn't find the time for it yet, no worries. Then I might take a stab at it today myself.

**Comment by apoorvaagupta** [comment]
Hey @Gregoor ,
Sorry I didnt respond earlier, but I have been unwell for past 10 days. So no laptop!! 
But yes I have started with it. 
On seeing the code, I think the conversion to express can be done incrementally.  
So, I think it would be great if we team up together and I convert some of the files and you convert some of the files!!

What do you think about this?!
Sorry again for such a late reply :(

**Comment by Gregoor** [comment]
@apoorvaagupta I'm sorry to hear that and no problem, take your time and get well soon. Health is priority number 1.

On doing it incrementally: I agree, that should be possible. Do you want to start a PR with the foundation of express support or shall I?

**Comment by apoorvaagupta** [comment]
Thanks @Gregoor 
I will do the foundation of express part PR today!
One more thing, I just need to make sure whether it has to be done in Typescript or Javascript?!

**Comment by Gregoor** [comment]
Great! Typescript would be ideal, though you can also start with typing
everything as `any` and then I'll look into more fine grained typing.

**Comment by Gregoor** [comment]
Hi @apoorvaagupta,

1. it's fine to submit it to master, that's how we do it for all changes. Then we can work on the branch until we're happy with it and merge it in. Sounds good?
2. Do you see a specific place where there is a need for an ORM. I think atm we're good and in any case that change should be separated from the router change.
3. Unfortunately not, that will be part of this effort. But the [frontend's api module](https://github.com/mozilla/voice-web/blob/master/web/src/services/api.ts) shows all the routes that are being used by the FE.

**Comment by apoorvaagupta** [comment]
Ok @Gregoor So I will just generate a PR and tag you there!

**Comment by Gregoor** [comment]
Sorry I just rushed through it and we're done with this issue 🙊 Though this is only the first step in redoing the routing. Would definitely appreciate thoughts and ideas on the next steps => #823
