### ISSUE TITLE
Fluentify

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#838]
This is a meta-issue for tracking the progress of wrapping all our user-facing strings with [Fluent](http://projectfluent.org/). To get an idea how to fix any of those, take a look at the [messages](https://github.com/mozilla/voice-web/blob/master/web/locales/en/messages.ftl) file and at the already localized [homepage](https://github.com/mozilla/voice-web/blob/master/web/src/components/pages/home/home.tsx).

- [x] Profile-Component #841 
- [x] Record-Page #839
- [x] Datasets-Page #840
- [x] After-Download-Modal #870
- [x] Profile-Page #842
- [x] static pages #843
- [x] Contact Modal #871

**Comment by MekliCZ** [comment]
I'd like to take all of these, could you assign them to me, please? :)

**Comment by Gregoor** [comment]
Awesome, thanks @MekliCZ! Are you already on the Records Page? Looks like there's another interested contributor for that.

**Comment by MekliCZ** [comment]
Oh. Yes, I already started. :/ Should I write to the issue or let him finish it?

**Comment by Gregoor** [comment]
Let's write and see how far they are 👍

**Comment by Gregoor** [comment]
Thanks to @MekliCZ, we should be all done 🙂
