### ISSUE TITLE
Fluentify Record-Page

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#839]
See meta-issue #838 for a description

**Comment by ad1rie1** [comment]
I Will help for this :)

**Comment by MekliCZ** [comment]
Hi @ad1rie1, I wrote in #838 that I'd like to take all Fluentify issues and I have already started with this one. How far are you? I have about half of the strings completed so if you haven't started yet/have done only few strings, I'd rather finish it.

**Comment by ad1rie1** [comment]
As you can see in commit 
https://github.com/mozilla/voice-web/pull/846/commits/a472b40b97e3d30947a05b31f4987c48970c2ef2

When Text is hard coded in JavaScript, Fluentify can be used ? 
My first try is good or contain errors ?
