### ISSUE TITLE
Fluentify Datasets-Page

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#840]
See meta-issue #838 for a description

**Comment by MekliCZ** [comment]
taking this one

**Comment by MekliCZ** [comment]
@Gregoor should dataset names be translatable?

**Comment by Gregoor** [comment]
Hi @MekliCZ, I'd say no, as they are all proper names. Only one I'm not so sure about is the TED LIUM Corpus (which would be Korpus in German). So maybe we should put that into a Localized-Tag as well.
