### ISSUE TITLE
Fluentify Profile-Component

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#841]
See meta-issue #838 for a description

**Comment by MekliCZ** [comment]
Not sure how to fix that. :/ @stasm, could you take a look? More info is in #845.

**Comment by Gregoor** [comment]
One option would be to use the [withLocalization-HOC and `getString`](https://github.com/projectfluent/fluent.js/blob/master/fluent-react/examples/higher-order/src/App.js) to explicitly set the label. I have not yet found word on whether it's possible to only set attributes, without replacing children.
