### ISSUE TITLE
should we display a mic volume too low warning/error?

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#859]
the website should advise people to increase their mic volume if it is below a certain level.
Do you agree?

**Comment by Gregoor** [comment]
[We do have an error for that](https://github.com/mozilla/voice-web/blob/6f390019beed283227ae2d6ab0e3336288044597/web/src/components/pages/record/record.tsx#L120-L124) though our notion of too low is probably a bit naive there. But I don't think we have the time to implement a more sophisticated solution atm. Though if someone has an idea for that, PRs are always welcome!
