### ISSUE TITLE
snippets from not-used folder are actually used

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#860]
The website uses strings/snippets from the not-used folder.
And those don't seem to have been proofread (tomy -> to my)

![screenshot_20180210-103800](https://user-images.githubusercontent.com/5685512/36060698-e3bfc9ce-0e4e-11e8-9ded-d29ba242e636.png)

**Comment by Gregoor** [comment]
Thanks for reporting that. I can confirm that it's from not_used but looking at `corpus.ts` those should not be served. Awfully weird. Before investing more time in this, we might just make the switch to serving those from the DB directly.

**Comment by mikehenrty** [comment]
Yup, this is expected behavior. What happened was, that sentence was "active" at some point (ie. not in the "not-used" folder), and went into our dataset. We don't remove these clips, and we still need to validate them, even if the sentence is no longer active.
