### ISSUE TITLE
jaggy audio samples (lag while recording?)

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#861]
every now and then I stumble across laggy/jaggy audio, is there anything we can do about that?
Should we even allow/use these recordings?

**Comment by mikehenrty** [comment]
If you can understand what they said despite the jaggy-ness, then we do indeed want these clips. We want our speech recognition engine to be able to cope with bad microphones, or whatever problems exist in real world user environments. So this is a "feature" of our data, believe it or not.

On the other hand, if you can't understand it, then mark it "No."
