### ISSUE TITLE
Typos in strings

### ISSUE THREAD

**Issue by 12people** [mozilla/voice-web#863]
Some strings have typos like "the a" in them, or are missing a comma. These are easily missed by both the reader and a reviewer, and the resulting text match could be faulty.

**Comment by mikehenrty** [comment]
Hi @12people, thanks for the report.

Yup, we have some bad sentences. We generally try to fix them as we spot them, or clean up a bunch at once like in #776 .

No need for us to keep an issue for it open, it's just continual maintenance. If you happen to remember the sentence, you can file a bug about that sentence, or issue a PR with the fix.

Thanks!
