### ISSUE TITLE
Firefox asks me to share microphone on every contribution

### ISSUE THREAD

**Issue by geroter** [mozilla/voice-web#873]
**Platform**
Firefox 58.0.2 on Android Mobile
Pixel2 XL
Android 8.1.0

**Problem**
Firefox asks for permission to access the microphone on every single "set of 3" time I record.

Chrome works as expected on the same device.

**Expected behaviour**
Firefox only asks me to share my microphone once, at the beginning of a contribution session.

**Comment by Gregoor** [comment]
Hi George, this is actually intended behavior as per community request in #460. Though I agree that it's a bit of a trade-off UX wise.

**Comment by geroter** [comment]
IMO it's a really hurtful tradeoff. My personal experience is that it probably cuts my contribution by 90% due to inconvenience and annoyance.

It would be good to get @m-branson 's take, especially with the new/refreshed experience.

**Comment by Gregoor** [comment]
That's understandable. A better compromise might be to only release the microphone once the user switches tabs. That way there's no stopper for doing streaks. Alternatively we could remind users that the browser has the option to remember permissions.

**Comment by m-branson** [comment]
@geroter @Gregoor my expectation would be the same as @geroter's: microphone access response is cached in Firefox (and all browsers). I do understand the desire to have the microphone be released when the tab is no longer focused, is it possible to 'have it all'; e.g. remember microphone access granting and release a non-focused tab from the microphone during that session (without losing permission)?

**Comment by mikehenrty** [comment]
@Gregoor fixed this exactly how @m-branson asked. Good work!
