### ISSUE TITLE
Bogus localization entries on Pontoon

### ISSUE THREAD

**Issue by lissyx** [mozilla/voice-web#877]
Some entries, especially those including a `DATETIME` reference, seems to be improperly parsed and exposed on pontoon. So far, spotted that on keys `terms-effective` (https://github.com/mozilla/voice-web/blob/630a7830742d7063c6b8972ba6aac487b20636fa/web/locales/en/messages.ftl#L108
![screenshot-2018-2-20 common voice french fr](https://user-images.githubusercontent.com/1645737/36434001-3d0054c4-165e-11e8-9d6c-5b8a6fd9f162.png)
) and `privacy-effective` (https://github.com/mozilla/voice-web/blob/630a7830742d7063c6b8972ba6aac487b20636fa/web/locales/en/messages.ftl#L97)

**Comment by MekliCZ** [comment]
This looks more like a Pontoon bug than voice-web bug. The FTL file is valid. Maybe @mathjazz can tell us more...?

**Comment by mathjazz** [comment]
The string looks OK to me. Could you specify what exactly is wrong?

We are planning to make such strings easier to use, at least by highlighting the placeable:
https://bugzilla.mozilla.org/show_bug.cgi?id=1437857

**Comment by MekliCZ** [comment]
Well, the string itself is OK, but Pontoon includes the string ID in the UI (visible on screenshots)

**Comment by mathjazz** [comment]
Yup, that's because such strings are only translatable in the "source editor" (which is why the FTL icon turns green). We'll make it more obvious it's a source editor soon:
https://bugzilla.mozilla.org/show_bug.cgi?id=1433994

**Comment by lissyx** [comment]
Thanks @mathjazz, so it's just misleading Pontoon UI, I'm closing this.
