### ISSUE TITLE
Server sometimes returns HTTP 500 when counting votes

### ISSUE THREAD

**Issue by flyingpimonster** [mozilla/voice-web#884]
Sometimes, a POST to `/api/v1/clips/<clip-id>/votes` will return a 500 error, with a response of `{"message":""}`. Looking at the code, it's probably either an error in the database or with S3. However, I don't have an S3 account to test myself.

In addition, the webpage does not handle the error gracefully. It does not display the next sentence, but simply shows the old one greyed out.

**Comment by Gregoor** [comment]
Good catch, thank you! It looks like we have a few dead DB-connections lying around. I'm switching the DB code over to use connection pooling, I think that should fix this problem.

**Comment by Gregoor** [comment]
Looks like pooling fixed the problem 🙂
