### ISSUE TITLE
translation pontoon question: line-breaks

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#892]
Some strings have line-breaks after x characters, should we try to copy those or will that be done automatically before merging?

If translators should apply them:
Which value does x have exactly?

**Comment by Gregoor** [comment]
Ty for reporting this! Can you link some examples?

**Comment by Djfe** [comment]
https://pontoon.mozilla.org/de/common-voice/messages.ftl/?time=201802271115-201803142224&string=175939
https://pontoon.mozilla.org/de/common-voice/messages.ftl/?time=201802271115-201803142224&string=175922
https://pontoon.mozilla.org/de/common-voice/messages.ftl/?time=201802271115-201803142224&string=175923 (actual linebreaks plus the tags in there)

Actually those are the only ones so far, that I encountered, I think.

**Comment by Gregoor** [comment]
Oh, right. Thanks for the examples!

That's a bit of a weird thing with Fluent, as we're using linebreaks in the english message file to make it more readable. While those breaks make it into the string, they're ignored in the app itself. So the only visible linebreaks are the ones in the third link.

**Comment by Djfe** [comment]
Ok I'll use lineBreak tags and report the other thing as a bug report on bugzilla.
Pontoon isn't fully ftl compliant, yet (according to the dev in the other report)
