### ISSUE TITLE
Legal review of experience we will be submitting to Apple for review

### ISSUE THREAD

**Issue by geroter** [mozilla/voice-web#9]

**Comment by geroter** [comment]
Figure out how Brian will have access to this - @andrenatal

**Comment by mikehenrty** [comment]
I believe @andrenatal added Brian to the TestFlight group. Next steps are:

1. have Brian/Marshall look over the wireframes from Geekettes
1. have Brian/Marshall review the final experience right before we publish

Moving to second milestone to complete part 1.

**Comment by mikehenrty** [comment]
Experience review, app submitted and live on the app store.
