### ISSUE TITLE
Some incomplete translations error

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#901]
https://voice.allizom.org/zh-CN (also fails locally)

**Comment by mikehenrty** [comment]
looks like the error we are getting is:
```
br is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.

**Comment by Gregoor** [comment]
There was a space in inside of a `<lineBreak> </lineBreak` tag (which resolves to a `<br>`). Fixed this for now, but I don't really like that Fluent let's us do it, so [I filed an issue in their repo](https://github.com/projectfluent/fluent.js/issues/174).
