### ISSUE TITLE
Some analysis of word frequencies in the dataset

### ISSUE THREAD

**Issue by flyingpimonster** [mozilla/voice-web#902]
I got bored, so I fired up my terminal and wrote some scripts to analyze word frequencies in the dataset. All the scripts I used, as well as the results and a writeup, are [here.](https://github.com/flyingpimonster/common-voice-analysis) Any thoughts?

**Comment by mikehenrty** [comment]
This is great work @flyingpimonster !!

We are in the process of coming up with a best practice guide for collecting sentences (mostly for new languages, but also useful for english). I could see your tools being very useful to this effort. Would you mind if we pull some of your code into the main repo at some point?

**Comment by flyingpimonster** [comment]
Sure! It's all Python code at the moment, but it shouldn't take me long to write it in typescript if that's better for you.

**Comment by Undigon** [comment]
This is important! We could then check if a certain language "most used words" are present in the database or not and of course in what proportion.

**Comment by reinhart1010** [comment]
Well, I previously did a similar thing (generated from a bash script) on https://github.com/reinhart1010/common-text , and I am currently trying to rewrite the script to support other Latin and non-Latin (e.g. CJK characters) and re-release the code under MPL instead of MIT.

**Comment by Gregoor** [comment]
I wonder what's a better place to put and talk these scripts. In the DeepSpeech Discourse more people might be interested & have ideas around it: https://discourse.mozilla.org/c/deep-speech
