### ISSUE TITLE
parts of the footer don't scale correctly with longer translations

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#903]
~~I found a few issues, that should be fixed before the multi-language release:~~
~~1.~~
![firefox_2018-03-25_08-56-12](https://user-images.githubusercontent.com/5685512/37872560-632a7c68-300a-11e8-86c8-732a3519776d.png)
![firefox_2018-03-25_08-57-34](https://user-images.githubusercontent.com/5685512/37872571-a248ffd2-300a-11e8-82c5-df0e8f2fc8c6.png)
The sharing div doesn't have a fixed (max-)width.
On mobile it looks fine though, but it's a 3 line paragraph there (at least)

I already suggested a shorter translation for the German version.
It might be good to define character number limitations for this string in the ftl file though ;)
(comments like the ones in the engagement project: "Limit character length to 180, preferably under 160. Please rephrase as needed to fit." etc.)

~~2.~~
~~I think this might be due to the way you read the ftl files, but I'm not sure (could also be a Pontoon bug):~~
~~https://pontoon.mozilla.org/de/common-voice/messages.ftl/?search=stunden&string=175869
looks like this on the staging server:~~
~~![firefox_2018-03-25_09-19-53](https://user-images.githubusercontent.com/5685512/37872691-b638b930-300d-11e8-9d50-2b5ce2b56585.png)~~
~~Does your ftl interpreter convert all & to ``` &amp; ``` without checking whether it's already part of an html entity?~~

~~3.~~
~~Probably a known issue, but there are several strings on buttons (and links) left that are still using an english string in the source code instead of the localized tag.~~
~~I can list them, if needed.~~

**Comment by Djfe** [comment]
This could also help with 1.:
https://stackoverflow.com/questions/20626685/better-way-to-set-distance-between-flexbox-items

**Comment by Djfe** [comment]
2. is definitely not a Pontoon bug:
https://github.com/mozilla/voice-web/blob/ccd9f766e141e74b7798dbaae5f34683eea29f5c/web/locales/de/messages.ftl#L84

**Comment by MekliCZ** [comment]
@Djfe I've created #893 and I'm working on it, if you find any untranslatable strings that are not listed in the issue, you can just comment the issue :)

**Comment by Gregoor** [comment]
Imo this footer design iteration fixed this :)

**Comment by Djfe** [comment]
great! :)
