### ISSUE TITLE
Show Browser languages first in languages overview

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#904]
Similar to what we've done in request a language, we can use `navigator.languages` to show the user's language(s) first. Atm I've sorted them by translation percentage and language population.

**Comment by MekliCZ** [comment]
I don't think it's good idea to sort them by translation percentage and language population, no other Mozilla website does this and it's pretty hard to find the right language if you expect that they are ordered by name. But showing browser languages at the beginning of the list is good idea.

**Comment by Gregoor** [comment]
Consistency is a good point. The reasoning behind the current sorting is that languages are rewarded for their effort and one can immediately see which languages is closest to launch (though as sentence collection is atm not part of it, it might be a bit illusive).

**Comment by flekkowich** [comment]
Related to issue #1057
