### ISSUE TITLE
ftl interpreter converts &thinsp; to &amp;thinsp;

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#913]
this issue was part of #903 before, now I created a new bug report to make the remaining parts of that issue more visible (by their subject)

imo HTML entities should be supported in translations, if they make sense.

Example string:
[Pontoon](https://pontoon.mozilla.org/de/common-voice/messages.ftl/?search=stunden&string=175869)
[GitHub](https://github.com/mozilla/voice-web/blob/ccd9f766e141e74b7798dbaae5f34683eea29f5c/web/locales/de/messages.ftl#L84)
[Staging server - FAQ page](https://voice.allizom.org/de/faq)

HTML code on the staging server:
![Screenshot](https://i.imgur.com/RO6yW0u.png)

**Comment by mikehenrty** [comment]
@Gregoor do you know if this is a fluent issue? or is it on our side?

**Comment by Gregoor** [comment]
@mikehenrty I think this should either be fixed in the string itself (i.e. don't use html entities) or on the Fluent side (accept html entities).

@Djfe from looking at the Pontoon history it looks like you contributed a non-entities version of that string, and then @koehlermichael changed it to a version using html entities. Why wouldn't we want to have a "real" thin-space in there?

**Comment by Djfe** [comment]
@gregoor Michael's string was first, mine followed (when I saw that the thinsp wasn't handled correctly).

He probably used HTML entities since they are readable and easy to write down and maybe they work in other projects.
The advantage of Pontoon is though: it highlight's such characters and thereby makes them visible.

I just decided to approve the non HTML entities version (I didn't have those permissions back when I write that string. Michael gave them to me since then) for now.

But I still wanted to bring this up, so you can at least take a look and decide what your preferred way of handling HTML entities should be.

**Comment by Gregoor** [comment]
Thanks for that extra explanation for me @Djfe. It might be helpful for Pontoon to not do that kind of syntax highlighting in projects using Fluent, as it wouldn't work for those. So, I see two things we do here: either we ask the Pontoon team if they could disable that highlighting for Fluent projects or we ask the Fluent team if they want to support entities.

CC @stasm

**Comment by Djfe** [comment]
I'm sorry for the confusion, pls reread the 2nd and 3rd section of my previous post.
I had to rephrase them, because they made you get the wrong impression.

Pontoon hightlights the special character thinspace, therefore html entities aren't needed to make the character visible to other Pontoon users.
![screenshot](https://i.imgur.com/bGhNNZB.png)

HTML entities on the contrary aren't highlighted in Pontoon

**Comment by Gregoor** [comment]
No worries, I could've just checked 🙈 Well then. Is there a case where you'd find HTML entities especially useful over their non-encoded equivalent? Otherwise, I'd say we're good?!

**Comment by stasm** [comment]
This is a bug in `fluent-react`, sorry about it! HTML entities should be supported just as they are in `fluent-dom`. The fix is simple, I'll fix it in the next release.

**Comment by stasm** [comment]
(Thanks for working around the bug by using the actual thinsp character in the translation.

**Comment by stasm** [comment]
To close the loop here: I published [`fluent-react` 0.7.0](https://github.com/projectfluent/fluent.js/releases/tag/fluent-react%400.7.0) last week which has the fix to this issue.
