### ISSUE TITLE
Broken Link: VoxForge

### ISSUE THREAD

**Issue by samgd** [mozilla/voice-web#915]
The VoxForge [link](http://www.repository.voxforge1.org/downloads/SpeechCorpus/Trunk/) found on the Common Voice [data page](https://voice.mozilla.org/en/data) gives `ERR_NAME_NOT_RESOLVED` when accessed. (Note: Not the `Download Data' link - this is currently OK)

**Comment by mikehenrty** [comment]
@samgd thanks for the report! it looks like the link is back up for me. can you retest it to see if it's back for you too?

**Comment by samgd** [comment]
It's back!
