### ISSUE TITLE
spelling error, not-used folder

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#919]
I just spotted a spelling error, while listening to some recordings:
https://github.com/mozilla/voice-web/blob/0a405690e860c5a3da923d8838bb8a588fd07a0d/server/data/not-used/anoian.txt#L32
it's "lightning" not "lighting"

and the person on the recording spoke it as lightning

I'm just wondering, whether doing pull-requests for files in the not-used ordner are still welcome or not exactly necessary anymore.

Regards,
Djfe

**Comment by mikehenrty** [comment]
@Djfe, yes pull requests are definitely welcomed!
