### ISSUE TITLE
Language Selector should use translated names of languages, rather than english version

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#921]
For instance, German should read "Deutsche", not "German"

**Comment by akuckartz** [comment]
Minor correction: "Deutsch", not "Deutsche".

**Comment by Gregoor** [comment]
Stas made a point on this, that I found convincing:
> I'm naively thinking that it makes it hard to go back to a language if I accidentally change to Arabic or Chinese :slightly_smiling_face:

Flod's recommendation was
> localized name (english name)

Though we already use parantheses qualifying where languages are spoken, e.g. "Chinese (Taiwan)".

Any other ideas?

**Comment by peiying2** [comment]
To make matter a bit complicated, spoken Chinese comes in many varieties, not categorized as Simplified (in China and Singapore) or Traditional (Taiwan and Hong Kong) in written form, but Mandarin (official spoken language in China, Taiwan, Singapore), Cantonese (Hong Kong), Taiwanese (the native dialect spoken in Taiwan: https://en.wikipedia.org/wiki/Taiwanese_language_(disambiguation).

**Comment by Gregoor** [comment]
Just realized that I went off-issue description by localising languages in the selector as that was not what was asked here. I wonder how I got that idea 😕 

@peiying2 is the way the different chinese are labeled on staging, alright?

**Comment by peiying2** [comment]
@Gregoor 正體中文（繁體）is how it's labeled on mozilla.org language dropdown list. This is purely for the written script, not the spoken part. Basically it says Chinese (Traditional). 

In terms of format, do we need to put English in parenthesis? If people don't read the language, chances are, they won't click on it even if we have English label to indicate what it is.

**Comment by Gregoor** [comment]
Yes, I agree that we probably don't need english in parenthesis. 

Thanks for the infos!
