### ISSUE TITLE
you must allow microphone access error appears when no mic is plugged in

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#926]
the error "you must allow microphone access" is a bit misleading.
I disabled the mic input on my PC (windows) and only use a usb mic, so it's only available when plugged in.

The website tells me that it doesn't get the permission for the mic (even when I set the permission in firefox for the website manually).

It should display a warning that no microphone is connected/available instead in that case

**Comment by Gregoor** [comment]
@Djfe @mikehenrty How about "No microphone found."?

**Comment by mikehenrty** [comment]
@Gregoor can we detect difference between when a microphone is not present, or when the user deny's access? my understanding was that either way, the browser tells us the same thing.

**Comment by Gregoor** [comment]
@mikehenrty yup, surprised me as well. But we do get a different error when no microphone is available.

**Comment by Djfe** [comment]
Did a search and now Gregor was quicker hehe
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
