### ISSUE TITLE
make website look correct on edge

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#927]
this issue is just about the design (unlike #469 which exists to add recording support)

we have the same issue like these guys:
https://github.com/mozilla/send/issues/476
![screenshot](https://i.imgur.com/QUo4urh.png)
looks like fluent might no be telling edge the correct way to interpret the text as unicode
(this also happens on the dataset page and a few others)

edge has problems interpreting the flex css box on the language page for some reason (it should display 3 language in a row):
![screenshot](https://i.imgur.com/51bVxxO.png)

**Comment by Gregoor** [comment]
Thanks for reporting that, I think I got it all.

- disabled string isolating in Fluent
- reduced LocalizationBox width denominator, due to float division problem on Edge
- added focus-within PostCSS plugin to make language selection work
