### ISSUE TITLE
Requesting a language aka Newsletter changes profile's e-mail

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#929]
IMO it's weird, that requesting a language sets up a profile/change's your profile's e-mail address, if you've got a profile already

What do you think?

**Comment by mikehenrty** [comment]
we did this on purpose so we can keep a single email for each user (because we will be using your profile email for most communications from Common Voice).

what is the use case for having a different profile email vs. email we use to send you updates about a particular language?

**Comment by Djfe** [comment]
I just stumbled upon it.
I don't think it's much of a use-case to allow a different email, but why ask for the email in the form at all then?
Just a checkbox and a submit button and either a disabled input box (for users with a profile) or even just a label showing the email, to communicate: this will be send to your profile's email ;)

On that instance:
Are there any differences between emails about the common voice project and signing up for language updates for one particular language?
There is only one checkbox on the profil settings page for disabling those again.

**Comment by Djfe** [comment]
All in all it's just a very minor detail.

When deleting your profile, the website doesn't tell you, that Mozilla will also stop sending emails:
![Screenshot](https://i.imgur.com/N3kbRZm.png)

Yes, you could assume this, but it's not entirely clear, since subscribing to a newsletter doesn't tell you, that this just created a profile for you.
