### ISSUE TITLE
tabindex issues, switching languages by keyboard

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#931]
I can't switch languages via my keyboard

there's one invisible thing with a tab index between the Button to add the page link to your clipboard and the facebook-sharing button.
My guess is, it's the invisible input containing the url

**Comment by mikehenrty** [comment]
@Djfe are the two issues you mention here related?

**Comment by Gregoor** [comment]
Thanks for raising this @Djfe, it was at the back of my mind when building the select but then I forgot it. We should be using Downshift here (which we already use for the autocomplete), as it helps a lot with accessibility and keyboard interactions.
I'll have something to look at early next week.

**Comment by Gregoor** [comment]
I had to do some coercing*, but Downshift now handles that select for us (and thus we have keyboard navigation). From my testing it looked good, but a more thorough accessibility review would be valuable (any input is valuable ofc 🙂 ).

* Downshift seems to be primarily built for selects with input fields. Also we handle open state ourselves (in CSS). Still, it feels solid to me.
