### ISSUE TITLE
Use vector for the language selector icon

### ISSUE THREAD

**Issue by MekliCZ** [mozilla/voice-web#932]
<img width="393" alt="snimek obrazovky 2018-04-19 v 9 16 36" src="https://user-images.githubusercontent.com/9162439/38976719-61428330-43b2-11e8-957a-7b05509ac24a.png">
^ icon compared to play and record icons

**Comment by MekliCZ** [comment]
Also, the GitHub and Discourse icons in the footer are lowres pngs

**Comment by MekliCZ** [comment]
Ok, I just found out that none of them are PNGs but they are SVGs with some weird gradient that looks pixelated on retina display.

**Comment by MekliCZ** [comment]
Looks like this is fixed in `master`, but some other branch with old icons is being deployed to staging.

**Comment by Gregoor** [comment]
Heya @MekliCZ, it looks weird to me as well. I asked our UI designer to take another look at it, as the icon itself looks good to me, it only becomes pixelated when embedded. I'll post here when he gets back to me.

**Comment by MekliCZ** [comment]
As I said, it's fixed in master (there are different icons), but something else is deployed to allizom.

**Comment by mikehenrty** [comment]
could be cache issue, or deployment delay
