### ISSUE TITLE
Shortcuts across languages

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#933]
As alluded to in #893, I'm not sure how to best bring shortcuts to other languages. Reason being that I assume there could be languages where their words for "Yes", "No" or "Record" start with the same letter. Atm we just use the first letter as the shortcut. I'd guess most UIs in that case just look for the first unique letter in the word and use that.

Anyway, I'd love to get some input from people with different language backgrounds. I also currently have no idea how shortcuts in languages with large alphabets work.

Once we found a solution, we should also fluentify the related strings => https://github.com/mozilla/voice-web/issues/893#issuecomment-382577880

**Comment by Djfe** [comment]
I don't know much about this.
Afaik Firefox handles it via Pontoon -> a second string for the Mnemonic (at least it looks like it:
https://pontoon.mozilla.org/de/firefox/all-resources/?status=missing&search=H&string=177771 )

Gnome has a section on it, but they don't have Mnemonics for yes/no/record:
https://wiki.gnome.org/de/UebersetzungsRichtlinien
I'm not sure about commandline short versions for yes/no (can't find any info on that)

If you do it via a string, then you might want to group it with the yes and no text from the according button.
