### ISSUE TITLE
Need to support Right to Left (or bi-di) languages

### ISSUE THREAD

**Issue by peiying2** [mozilla/voice-web#937]
Hebrew is not laid out correctly: https://voice.allizom.org/he and https://voice.allizom.org/he/privacy.

@Gregoor @mikehenrty

**Comment by MichaelKohler** [comment]
There have been some improvements in the past, there might still be some issues though. I'm closing this, but if you see any specific instances where the layout is wrong, can you please file a specific issue? Thanks!
