### ISSUE TITLE
language page doesn't scroll to top on mobile

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#938]
the title says it all.
All other pages scroll you to the top, when you open them.

**Comment by Gregoor** [comment]
Thanks for the re-review! I could reproduce the inconsistencies. Since I can't quite figure out what's causing that, I put a timeout for the scrolling up in, which from my experiments looks like it "solved" it. LMK if it still seems off to you.

**Comment by Djfe** [comment]
seems to be fixed now :)
great!

(my guess is, that it takes some time to update the DOM and executing it, while the DOM is empty makes the change go away, maybe your framework even tries to remember the old scroll position and adds it back, right after replacing parts of the DOM)
