### ISSUE TITLE
Arrange legal docs sync through GitHub legal repo

### ISSUE THREAD

**Issue by peiying2** [mozilla/voice-web#942]
This is related to https://github.com/mozilla/voice-web/issues/936.

Should work out the process to get legal docs pushed to production from legal repo: https://github.com/mozilla/legal-docs. 

@mikehenrty @Gregoor

**Comment by Gregoor** [comment]
I'm tackling this today. Still not entirely sure what the most elegant way would be (i.e. without increasing the bundle size). I'd guess just linking to those files would not suffice?

**Comment by mikehenrty** [comment]
@peiying2 i assume it's ok if we manually pull them in?

my thinking here is that we just hard code them in the website for the languages we get translations for

**Comment by peiying2** [comment]
@mikehenrty I have always wondered if this is a possible solution. Can we create a separate file in Pontoon, using the same strings and IDs, updated with Feldman's content. Or does everything have to be in one file to make it work? Agency can have access to Pontoon, and communities can make edits after reviews. If we make it clear  that this is legal content, communities are not asked to complete this task.
