### ISSUE TITLE
Dead link in staging-banner

### ISSUE THREAD

**Issue by jf99** [mozilla/voice-web#943]
It's pointing to https://voice.mozilla.com/ instead of https://voice.mozilla.org/. I would have fixed it and created a PR for it, but unfortunately one can only have one fork at a time on Github. Here's the line:
https://github.com/mozilla/voice-web/blob/ee28bc0fce2a2a0882929e992e6375426066ca6c/web/src/components/layout/layout.tsx#L247

**Comment by Djfe** [comment]
exactly
just keep the master branch unchanged, update the master branch ( ``` git fetch upstream ``` , ``` git pull ``` )
then ``` git checkout -b patchx ```
do your changes there, commit
``` git push ```
do a pull request on github in your fork, master repo from origin repo is already selected, select patchx branch from your repo, submit pull request

**Comment by Djfe** [comment]
if you already changed something your master branch, then create a new branch, checkout master branch, force pull changes, checkout the new branch and merge all changes from the master branch, done

**Comment by jf99** [comment]
@Djfe Thanks for the tutorial :) I have now created a separate branch "german" where you can open your pull request https://github.com/jf99/voice-web-de-fork/tree/german.
I propose you open it soon, whether you're done yet or not. When multilanguage Common Voice starts next week, we should have a few German sentences to start with (even if it's "only" 5,000).
