### ISSUE TITLE
linebreak doesn't show up (translated string)

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#944]
I would like to use a linebreak in the following string but it doesn't show up:
https://pontoon.mozilla.org/de/common-voice/all-resources/?search=linebreak&string=177874
![screenshot_20180424-213451](https://user-images.githubusercontent.com/5685512/39209885-6ccd7a94-4807-11e8-9b3e-e45a8ca4df7d.png)

**Comment by Gregoor** [comment]
I'd refer to this issue: https://github.com/mozilla/voice-web/issues/892#issuecomment-373687903
So adding a tag would still be the way to go, unfortunately.

**Comment by Djfe** [comment]
that's the problem, I used those tags and they don't work in this particular string lol.
(take a look at Pontoon ;) ``` <lineBreak></lineBreak> ``` )

**Comment by Gregoor** [comment]
Ah sorry missed that. The reason it wasn't working is, that the lineBreak wasn't supplied to the `Localized`-element. [Now it is](https://github.com/mozilla/voice-web/commit/33c55ab0c9df1fa81f4aab9b2ab4f86090e6953d).

**Comment by Djfe** [comment]
thx, for the fix! :)
I didn't know that.

the original string doesn't contain a lineBreak after all.
