### ISSUE TITLE
Lang selection on staging shows prior selected language in drop-down

### ISSUE THREAD

**Issue by geroter** [mozilla/voice-web#945]
This is tricky to describe...

When selecting a new language (on staging) from the language selector drop-down on the top right, there are two unexpected results:

1) The drop-down of language appears in the previously selected language vs. the currently selected language (so it has a delay of one page/refresh)

2) The drop-down of language probably should show languages not in the language selected but instead in the language that people would be navigating to (i.e. if I accidentally switch to simplified Chinese it's tough to go back to English because I don't know how English is spelled in simplified Chinese characters).

**Comment by Gregoor** [comment]
1. This one is a problem with Fluent, or with my intuitions around Fluent. Though from talking to Stas this week, he agreed with my intuitions, which means we'll get a fix. If we don't get it before friday, I'll push a work-around.

2. This is an interesting issue, as I've heard multiple people express different opinions. Some of it is captured in #921. We also just checked mozilla.org and native name only is indeed how it's done there. So I'll make that change tomorrow!

Thanks!

**Comment by Gregoor** [comment]
Just realized that 2 solves 1. Cool! 🙂
