### ISSUE TITLE
Some In Progress language names not visible 

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#952]
The `h2` for some languages is not visible on the Languages page when 'In Progress' is expanded.

Would characterize this as a bug, though not sure if it should block release?

cc @Gregoor @mikehenrty 

<img width="1214" alt="screen shot 2018-04-26 at 3 57 42 pm" src="https://user-images.githubusercontent.com/18686986/39336155-dffec81a-496a-11e8-9402-72c6fa0f9862.png">

**Comment by Gregoor** [comment]
💉 is ⬆️  (Fix is up)
