### ISSUE TITLE
Languages Page: Add 'See Less' link to bottom of list

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#954]
@Gregoor when our languages list(s) are open they get quite long. When the list is open, possible to duplicate the 'See Less' button centered at the bottom of the list too? This will alleviate the need to scroll back up to collapse the list.

See below for a quick example done in browser. Ideally the UI would be nicer for this : button styling similar to mobile where we have a nearly full width rectangular button with thin border and white background. On hover it would darken grey and on click would collapse the list. For now at a minimum let's duplicate the simple text link.

<img width="1188" alt="screen shot 2018-04-26 at 4 17 49 pm" src="https://user-images.githubusercontent.com/18686986/39336698-d0140070-496d-11e8-97ef-dfbc3af6593f.png">

**Comment by Gregoor** [comment]
I think I did it as described, happy to refine tho 🙃

**Comment by m-branson** [comment]
@Gregoor when reviewing with Rina today it became apparent that the 'see more' link on desktop is not obvious/visible as we'd like. The new implementation of 'see less' as a bottom button is much more so; it would be great to do the following:
1. remove 'see more' from top right
2. use same styling as 'see less' at the bottom for 'see more'

I've mocked quickly in browser, see screenshot below. Also removing `blocking-release` tag as this is an enhancement now.

<img width="1416" alt="see-more" src="https://user-images.githubusercontent.com/18686986/39447250-115c174c-4c76-11e8-86b1-a2e0b261e90c.png">

cc @flekkowich
