### ISSUE TITLE
Mobile navigation 'zooms in' when activating translate, doesn't zoom back out.

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#960]
@Gregoor when testing mobile on iPhone X navigation translate zooms in when activated. After interacting with and closing translation menu screen does not zoom back out. Bug or possible to turn this off?

<img src=https://user-images.githubusercontent.com/18686986/39339589-82928cfc-497e-11e8-9f98-224df7fa8ac5.PNG width="200">
<img src=https://user-images.githubusercontent.com/18686986/39339590-82b6885a-497e-11e8-885c-d87bbc04509b.PNG width="200">
<img src=https://user-images.githubusercontent.com/18686986/39339591-82fdb590-497e-11e8-93fd-7c181ddfca25.PNG width="200">

**Comment by Gregoor** [comment]
I'll have to find someone in the Berlin office next week with an X. My tiny android behaves differently here.

**Comment by Gregoor** [comment]
I tried it on the device simulator on Mac but didn't have much luck. Just to make sure that I'm doing it right:
1. open hamburger menu
2. click on the language select
3. choose a language and click done
4. it should stay zoomed in?

**Comment by m-branson** [comment]
You have the steps for recreation correct above. FWIW I was able to recreate on iPhone 8 Plus as well. It **does not** occur for me in browser dev tools or in device simulator on Mac either. 🤷‍♀️

**Comment by Gregoor** [comment]
Okay, I'll have to get my hands on one of those newer phones. Couldn't reproduce with an iPad, Simulator or iPhone 5. @mikehenrty do you have a newer iPhone? Will probably take longer to get one from the Hub.

**Comment by mikehenrty** [comment]
@Gregoor I've got one, and can reproduce. let's see if we can work on this today

**Comment by mikehenrty** [comment]
https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone#6394497
