### ISSUE TITLE
iOS 'open in app' UI out of date

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#963]
@Gregoor iOS 'open in app' banner is out of date (and so intense! wow!) 😆 

Let's update this to a black background color and ensure the type is open sans (same text styling as our other buttons). Possible to update the 'x' to be an icon rather than text based?

FYI the sticky, full width nature of this button is good and what I'm hoping we can achieve for the 'see less' button issue I also submitted today.

<img src=https://user-images.githubusercontent.com/18686986/39340078-e0c736f4-4980-11e8-972a-88594519b35d.jpg width="360">

**Comment by Gregoor** [comment]
I have no excuse for overlooking that color. I still have an afterimage of it
