### ISSUE TITLE
listen/record numbers - stats for mult lang release

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#964]
Will user's be able to see stats from each language on their profile or only the combined numbers? (multi-lang release)
If not, then I would suggest that.

**Comment by Gregoor** [comment]
cc @m-branson

**Comment by m-branson** [comment]
@Djfe great flag. @Gregoor if contribution is available for a selected language, is it possible to reflect those stats specifically? e.g. When the site is in language A my stats reflect my language A contributions; when the site is in language B my stats reflect my language B contributions.

A more robust version would be explored as part of the updated profile iteration: a dashboard reflecting individual stats in more detail. It's there where contributors may see their stats for each language together.

cc @mikehenrty

**Comment by Gregoor** [comment]
Yes, we could have per-languages per-user stats 🙂

**Comment by m-branson** [comment]
@Gregoor great! Do you need anything from UX to make this happen?

**Comment by m-branson** [comment]
Agreed that it could be confusing. We’ll most likely want to have a solve by the time we launch contribution in other languages. This could take the form of a notification banner highlighting that “You haven’t lost your progress, your stats have only updated to reflect contribution in the site’s selected language.” I could see this being an interim step before we rollout newer profile/dashboard capability. Thoughts?

**Comment by Djfe** [comment]
or display: language count/total count

5/35

the total count won't change by switching languages. (might look weird for people that only contribute to one language)

Or show a flag instead to indicate that the count is for one language.

**Comment by m-branson** [comment]
@Djfe at this point we're looking to avoid adding more to the header, especially as this proves difficult and unusable/legible on smaller devices.

Re: showing a flag to indicate the count as for one language, we're also looking to avoid utilizing flags as identifiers. They aren't always fully inclusive of every nation or dialect that speaks a given language.

For an early iteration, I'm leaning toward a timed/dismissable banner (below the header) that contains a clear message with a ^ to indicate that it pertains to the stats above. Users only have to translate back to english one more time to most likely 'learn' this experience. Which again, would be a short term solve as we continue to build a more robust profile experience. Would love to get @Gregoor and @mikehenrty's take on this short-term solution.

**Comment by Gregoor** [comment]
oops, didn't mean to close this one 🙈
