### ISSUE TITLE
[staging] Need a way to see recording page in new languages, even if they aren't launched yet

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#969]
Localizers need to see their translated sentences in context, and since we hide the record page they won't be able to see it right now.

Perhaps on staging we could still show the English recording page (and listen widget), and on only on production we can hide it.

**Comment by Gregoor** [comment]
Done. Though we might want to add something that allows us to switch to prod-mode (for testing the site in non-contributable mode)
