### ISSUE TITLE
Make language lists searchable on Languages page

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#970]
@Gregoor curious what you think of this; would love to help people find a language more readily as these lists grow. Perhaps a search icon next to 'In Progress' and 'Launched' that reveals a field when clicked/tapped? Would be great to have search filter and update results as users a typing.

cc @mikehenrty @flekkowich

**Comment by Gregoor** [comment]
Me likey. If someone sends me a nice search icon, I'll build it 🙃

**Comment by m-branson** [comment]
Will make this happen. :)
