### ISSUE TITLE
Locale switch dropdown: use full localized name for Traditional and Simplified Chinese

### ISSUE THREAD

**Issue by petercpg** [mozilla/voice-web#971]
![Screenshot](https://user-images.githubusercontent.com/205738/39395506-fbcec59c-4b11-11e8-872e-1669878ace51.png)

The short localized names for both Traditional Chinese (zh-TW) and Simplified Chinese (zh-CN) is 中文 (Chinese). Having two same item in the list would make users difficult to switch locale, we should use the full localized name, e.g. Chinese (Taiwan) / 中文（台灣）

Moreover, as Chinese is an umbrella language and usually referred to the written language, when referring the spoken language used, it would be more precise to use Mandarin/Mandarin Chinese instead. 

There are also other languages/dialects such as Min, Yue, Wu (see https://en.wikipedia.org/wiki/Varieties_of_Chinese) used by large population across the globe that might be worth to add to the language list to train too.

**Comment by Gregoor** [comment]
Thanks for reporting that. We had the same problem with Spanish, Portuguese and Swedish. Should be good now.
