### ISSUE TITLE
Unified Spanish: need to copy es-CL to es

### ISSUE THREAD

**Issue by peiying2** [mozilla/voice-web#975]
@Gregoor, @mikehenrty  Ruben (native Spanish speaker) from OI team convinced the es-CL team to have a unified version. Chilean community has made sure that the current content in Pontoon is neutral. 

Please copy to es and we can remove es-CL repository. If this is too much to do before the launch, let's move over after the launch.  This will affect the language labels for everyone because of the update.

**Comment by nukeador** [comment]
Clarification, es-CL wants to wait till we review the "es" copy before deleting the es-CL one.

Community coordination is happening here (in Spanish):

https://foro.mozilla-hispano.org/t/localizacion-al-espanol-de-common-voice/23915/
