### ISSUE TITLE
Test Web page is down, SOX error

### ISSUE THREAD

**Issue by cnevinc** [mozilla/voice-web#98]
I just build the Android app. https://test.mozvoice.org/record is down.

**Comment by kdavis-mozilla** [comment]
Know issue. It looks like there's a problem with the [sox](http://sox.sourceforge.net/) install on the server and as far as I know @mikehenrty is the only one with ssh access.

**Comment by mikehenrty** [comment]
Hi @cnevinc, thanks for the report! Yup, I am working on this and should have things back up today.

**Comment by mikehenrty** [comment]
Site's back up! Thanks again.

**Comment by cnevinc** [comment]
Hmm.. strange.
Still see 502 today.
Should I use Mozilla's VPN?

**Comment by nevik** [comment]
considering the time in between, this is probably down "again", not "still" 😉 

would you create a new issue for this?
