### ISSUE TITLE
[Backend] Email Validation

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#980]
we've been seeing some weird email address show up in the DB, we need to do some validation before saving it in the db.

**Comment by Djfe** [comment]
Maybe some verification might be useful as well?
(or even a login with https://www.mozilla.org/de/firefox/accounts/)

**Comment by missuniverse** [comment]
From what I've found there doesn't seem to be a way to verify email addresses other then checking them with a regex unless you use a service or another language like PHP to check the validity.
