### ISSUE TITLE
Please add /contribute.json to your project.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/voice-web#981]
Hi, the HTTP Observatory noticed that your site is missing a valid `contribute.json` file. While it isn't necessary to fill out every possible field in it, various incident response teams at Mozilla do really appreciate having one with the basics "where to file bugs" "what is this site" filled out. Webops can assist with writing one and/or there's a lot of examples hiding on various Mozilla sites as well.

https://observatory.mozilla.org/analyze.html?host=voice.mozilla.org

**Comment by Undigon** [comment]
I'll start looking at https://www.contributejson.org/ and see what I can make with it.
