### ISSUE TITLE
Translation de - how to translate "Launched"

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#983]
I need some help from the German contributors of this project:
How shall we translate the "Launched" section header on the languages page?
(I'll continue in German from now on)

Das Problem: Das Wort existiert nur als französisches Lehnwort im Deutschen: lanciert.
Und das hab ich noch nie zuvor gehört, ihr?

Mögliche alternative Übersetzungen:
- "Abgeschlossen" — Da es nur um den Status der Übersetzungen geht. 
- "Gestartet" — Wurde vorher mal vorgeschlagen, impliziert aber wie ich finde, das die Übersetzung gerade begonnen hat.
- "Live" — Die Übersetzung ist fertig und live im Betrieb.

Was das ganze noch verkompliziert: Wenn eine Sprache bei 100% ist, bedeutet das nur, dass die Website übersetzt wurde, nicht, dass bereits Sätze zum Einsprechen/Verifizieren existieren.
Die Sprache ist also noch nicht gelaunched.

Ach ja: Denglisch wie "gelaunched" wollen wir vermutlich auf der Webseite vermeiden, oder?

Grüße,
Djfe

![image](https://user-images.githubusercontent.com/5685512/39660826-194ceb1e-5047-11e8-9948-052d2dbd6393.png)

**Comment by Djfe** [comment]
Früher (auf dem staging server) war es 100% und die Prozentwerte entsprachen Pontoon.

Die 50% seh ich grad zu ersten Mal.
Das wurde also angepasst. So passt Launch auch deutlich besser, find ich.

In Aufnahmephase klingt gut. Ich finde, da fragt man sich nur, ob es um die Aufnahme der Sprache geht oder darum dass nun Sprachaufnahmen gesammelt werden. (natürlich letzteres, aber das Wort ist nicht ganz eindeutig)

Wie wärs mit "Umsetzung im Gange" für "In Progress"?

**Comment by jf99** [comment]
Lass uns doch einfach bei "In Arbeit" bleiben. Das ist eigentlich mindestens so gut, wie die anderen Vorschläge hier. Ich denke, man muss da auch keine Wissenschaft draus machen.

**Comment by Djfe** [comment]
Das stimmt natürlich auch. "In Arbeit" fand ich an sich bisher auch am passendsten.
Relevant ist aber weiterhin "launched"

Wenn niemand anderes bis Sonntag Abend noch ne Idee einwirft, setze ich es wieder auf "Gestartet".
Diesen Issue lass ich aber mindestens eine Woche auf.

**Comment by Gregoor** [comment]
Gute Diskussion. Ich mag die "Aufnahme freigeschaltet" Idee und auch die "Phasen" sagen mir zu. 

"Abgeschlossen" finde ich etwas problematisch, da daraus misverstanden werden koennte, dass schon genug Aufnahmen fuer diese Sprache gesammelt wurden.

Und "In Arbeit" und "Gestartet" gefaellt mir auch.

**Comment by Djfe** [comment]
Wie wärs mit Vorbereitungsphase und Aufnahmephase?

**Comment by Gregoor** [comment]
Finde ich noch besser!

**Comment by Djfe** [comment]
ok, dann nehm ich erstmal das.
Was meinst du @jf99?

**Comment by jf99** [comment]
Vorbereitungsphase und Aufnahmephase finde ich super. Ist beides kurz und verständlich.

**Comment by Djfe** [comment]
Dann schließ ich die erfolgreiche Diskussion hiermit :)

**Comment by Djfe** [comment]
Wär ja auch zu schön gewesen haha
Der Text wird in der mobilen Ansicht abgeschnitten.
Was machen wir am besten?
Andere kürzere Wörter? 
Horizontales scrolling über den buttons?
Oder das Aufteilen der Begriffe in zwei Zeilen mit Bindestrich? 
![screenshot_20180509-044054](https://user-images.githubusercontent.com/5685512/39792916-4fde4ef8-5343-11e8-8758-5fd6a7723b99.png)

**Comment by Gregoor** [comment]
Mist! Gar nicht dran gedacht 🙈 

Zwei Zeilen wuerden glaube ich nicht so gut aussehen. Noch eine Option waere, die font-size auf mobile von der viewport breite abhaengig zu machen. Wobei unser Design Team das wahrscheinlich auch nicht super finden wuerde 😁

**Comment by Djfe** [comment]
Vorbereitung und Aufnahmephase?

Oder ist das noch zu lang?

**Comment by Gregoor** [comment]
Das ist leider noch immer zu lang. Das Maximum an Textlaenge waere "Vorbereit" und "Aufnahme" (nicht dass das viel Sinn machen wuerde tho 😁 ). Aber vielleicht sollten wir doch einfach 2 Zeilen draus machen.

**Comment by Djfe** [comment]
ah verstehe, ändere Geräte sind schmaler als meins.

**Comment by Djfe** [comment]
Falls in Zukunft noch mehr Phasen dazukommen, könnte man auch eine Art Inhaltsverzeichnis wie das von Wikiseiten haben.

also aufklappbar Unterpunkte (Überschrift anklicken -> aufklappen)

**Comment by jdittrich** [comment]
> Wobei unser Design Team das wahrscheinlich auch nicht super finden wuerde
Jep. da wäre ich auch nicht so für zu haben. 

Ich nehme mal an, dass das Problem nicht nur im Deutschen existiert. Daher wäre es gut, hier eine robuste Lösung zu finden, die bei längeren Labels trotzdem noch OK aussieht.

**Comment by Djfe** [comment]
An welcher Stelle denn noch, ich finde sie nicht 😳 hehe

**Comment by mikehenrty** [comment]
Is there anything actionable here? If not, I suggest we close this rather than keeping a bug open for a discussion about this word.
