### ISSUE TITLE
Switching languages - sharing on Twitter, wrong language

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#986]
The link to share a statement on twitter uses a get argument for the default message.
Switching the language doesn't update that link to the new language.
Only reloading with F5 does.

**Comment by Gregoor** [comment]
Happy to hear that, then I'll try to be more verbose in general (which is also a good sanity-check for me, to see if my explanations make sense 😁 )

**Comment by Djfe** [comment]
Well you certainly can do that, but it of course also takes more time, right? (it's probably best if you decide on your own ^^)

**Comment by Gregoor** [comment]
@Djfe if you're interested in the details of the fix, you can check out the PR over at the Fluent repo 🙂
