### ISSUE TITLE
Back To Top button doesn't work (mobile)

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#987]
The back to top button in the footer isn't working.

**Comment by Djfe** [comment]
since the # looks kinda ugly:
What do you think about using span elements instead of "a" or something similar?
(I know that this requires a lot more work and changing the css, so if you don't think it's worth the effort or will do it during the redesign of the page, then that's fine by me)

**Comment by Gregoor** [comment]
I agree that the # is a bit ugly. Though I'd probably go with a button, styled like text. For non-links/buttons there's a couple of things one has to do to make them more accessible:
- add tabindex to make them "tabable"
- add a keydown handler to make enter work
And even then I'd assume some screenreaders aren't too happy with it.

So I guess an unstyled button is our best shot here.
