### ISSUE TITLE
Support gamepads as input

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#988]
Since I have a gamepad lying around, I had the idea:
Why not support gamepads as input?

https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API

I could display common voice on my tv (fullscreen) and use a game pad and (optionally) my headset to speak or listen.
All while comfortably lying on an arm chair :)

Also: the gamepad input is easier than constantly looking on your keyboard for y/n or the space bar.

of course some designs would need to be adjusted (the mnemonics texts for example)
But this could over all work out quite well IMO

Useful inputs:
Speaking
- start/stop recording
- up/down or left/right for previous/next recording
- keys on the right to play/rerecord sentences
- left/right back tabs to go to previous/next sentence and to continue from the overview page (that shows the 3 past sentences)
- special keys to switch between listening and speaking

Listening
- keys on the right for yes/no
- left/right back tabs for previous/next sentence
- special keys for flagging, data dropdown etc.

Do we want to be able to fully control the website by gamepad or just the listen/speak pages?
For me the latter would be enough

When looking at https://projects.invisionapp.com/share/K4FV4BPY6TX#/screens/290773972 this could really work out.

**Comment by Djfe** [comment]
@m-branson @Gregoor @mikehenrty

**Comment by Djfe** [comment]
I could that once the overhaul is on staging :)
(or even before that, if the design is final enough)

**Comment by mbransn** [comment]
Will close this out as it's an edge use case for the platform at the moment. If someone finds this and is eager to take a pass, please reach out.
