### ISSUE TITLE
What to show when there's nothing to validate?

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#989]
This would happen when `recording rate < clip validation rate` and is especially likely when we launch a new language (given that in the beginning there are no clips). I was thinking of a message like this:
```html
We didn't find new clips to validate. <recordLink>Why not record some yourself?</recordLink>
```

I'll do some database querying to figure out if that case is even likely (after a language has been launched for a while).

cc @m-branson @mikehenrty

**Comment by m-branson** [comment]
Sounds great @Gregoor, good flag. We'll probably want to fine tune the copy a bit:

`Looks like there aren't any clips to listen to in this language. Help us fill the queue and by recording some now. <recordLink>Speak</recordLink>`

Would be ideal to have this centered on the page in place of a sentence card with button for link (as opposed to a banner).

cc @flekkowich

**Comment by Gregoor** [comment]
fallback on processing string

**Comment by Gregoor** [comment]
@m-branson @georai: Viorela noticed that we don't yet have a view for this in the new contribution experience

**Comment by m-branson** [comment]
@Gregoor in the short-term can we do this?

![screen shot 2018-06-28 at 10 14 12 am](https://user-images.githubusercontent.com/18686986/42049831-12eb5180-7abc-11e8-91b0-f4019eda1b9f.png)

@georai how can we improve this ^ UI state? Perhaps show some of the other tooling but in a disabled state? Can you explore further?

**Comment by ftyers** [comment]
@m-branson (this should be looked at by a copyeditor) but I think wording like "Looks like there isn't anything left to validate" is better than using "yet" --- "yet" suggests that there was never anything e.g. that people haven't started, but someone could get this screen after validating for an hour straight... so "yet" might sound a bit odd... :D

**Comment by m-branson** [comment]
@ftyers agreed, still working on that copywriter resourcing currently. I did not realize this screen was also showing when a language 'ran out' of sentences to validate. Good to know. I wrote this text for the use case of landing here when a young language does not have any recorded sentences to validate. @Gregoor any other times this screen will pop up?

For the time being, I'm quite alright with this text being:
`We don't have anything to validate in this language, help us fill the queue.`

cc @mikehenrty

**Comment by mikehenrty** [comment]
> @Gregoor any other times this screen will pop up?

I believe the only times will be before we have recordings and when we run out (which is awesome to hear that we run out!). The language you suggested @m-branson sounds great to me.

**Comment by lissyx** [comment]
@ftyers Totally agree with you, I did actually ran into that screen after a few hundreds of validations :-)

**Comment by m-branson** [comment]
Hi all, we're working on getting a new version of this screen up during our next sprint. The copy will be as noted above for the interim. We have made steps forward with copywriter resourcing and should have some more keen eyes on this feedback in the near future. Thanks for your feedback as always!

Here's the screen we're implementing currently: https://projects.invisionapp.com/share/3UG9HFKGSFC#/screens/309137841
