### ISSUE TITLE
Get involved popup doesn't show completely on the staging server

### ISSUE THREAD

**Issue by danielsjf** [mozilla/voice-web#990]
I'm using a OnePlus 3T cellphone using Chrome. See #982.

Reprex:
1) Go to voice.allizom.org
2) Open menu and go to LANGUAGES
3) Click on the collaborate button on any language

I can never scroll completely down on this screen. There are always a few lines that are hidden.

![bug](https://user-images.githubusercontent.com/6696142/39768374-704b111c-52e9-11e8-8dad-654bc35b52ab.jpg)

**Comment by Djfe** [comment]
I can confirm this.
Firefox on Android works fine though (I'm a OnePlus 3T user as well ^^)
